reconcile/github_org.py, reconcile/openshift_rolebinding.py, reconcile/quay_membership.py, reconcile/test/fixtures/github_org/desired_state_simple.yml, reconcile/test/fixtures/openshift_rolebinding/desired_state_simple.yml, reconcile/test/fixtures/quay_membership/desired_state_simple.yml
This PR deprecated roles/members:
https://github.com/app-sre/qontract-server/pull/24
=> Use roles/users and roles/bots instead of roles/members

reconcile/openshift_resources.py, utils/vault_client.py
I think this will be a simpler solution (and a more general one) instead of fetching all the secrets from vault before we begin execution.
=> openshift-resources parallelism

reconcile/cli.py, reconcile/ldap_users.py
this change does not improve execution time by much, but if we need to in the future, we can increase the number of threads.
=> add parallelism to ldap-users

reconcile/openshift_resources.py, reconcile/test/test_openshift_resource.py, utils/openshift_resource.py
=> add update timestamp annotation

reconcile/terraform_resources.py
=> fix rrr in managedTerrraformResources

README.md, reconcile/cli.py, reconcile/openshift_namespaces.py, reconcile/openshift_resources.py, reconcile/terraform_resources.py, utils/oc.py
this integration:
1. gets the desired state
2. finds namespaces which do not exists
3. creates those namespaces
1. delete namespaces
2. annotate namespaces
=> [openshift-namespaces] introduce new integration

README.md, reconcile/cli.py, reconcile/openshift_groups.py, reconcile/openshift_resources.py, utils/oc.py, utils/openshift_api.py
* add users to groups
* delete users from groups
* manage all groups (only ones specified in a cluster file under `managedGroups`)
* creates groups
* deletes groups
=> [openshift-groups] introduce new integration

reconcile/cli.py, reconcile/jenkins_roles.py, utils/jenkins_api.py
* assigns roles to users
* unassignes roles from users
* creates users
* deletes users
* creates roles
* deletes roles
=> [jenkins-roles] introduce new integration

README.md, reconcile/cli.py, reconcile/jenkins_plugins.py, reconcile/jenkins_roles.py, utils/jenkins_api.py
* installs the latest version of the listed plugins
* uninstalls plugins
* updates plugins
=> [jenkins-plugins] introduce new integration

README.md, reconcile/aws_iam_keys.py, reconcile/cli.py, utils/aws_api.py
* deletes IAM keys from AWS accounts
* create IAM keys
* activate/deactivate IAM keys
depends on #84.
=> [aws-iam-keys] introduce new integration

utils/pagerduty_api.py
required for sync with pagerduty
=> [slack-usergroups] change time to utc

README.md, reconcile/slack_usergroups.py, utils/pagerduty_api.py
this PR adds support for referencing an escalation policy instead of a schedule.
=> [slack-usergroups] add support for escalation policies

reconcile/openshift_groups.py, utils/oc.py
this integration now creates and deletes groups if required
=> [openshift-groups] create and delete groups

reconcile/quay_membership.py, reconcile/test/test_quay_membership.py, utils/quay_api.py
covers https://jira.coreos.com/browse/APPSRE-607
=> [quay-membership] add quay user validation

utils/raw_github_api.py
covers https://jira.coreos.com/browse/APPSRE-694
=> [github] add retry mechanism

reconcile/slack_usergroups.py
includes all keys (approvers, reviewers)
=> [slack-usergroup] include all keys in owners file

README.md, reconcile/gitlab_members.py, utils/gitlab_api.py
- change access level from integer to string with an enum
- update qontract-reconcile README with the new integration
- fix integration logging to be more like `INFO: ['add_user_to_group', u'app-sre', u'owner', u'jzelinsk']`
=> [gitlab-members] integration cleanup

reconcile/cli.py, reconcile/openshift_groups.py
add threading to the openshift groups integration to make it run faster
=> [openshift-groups] add threading

reconcile/cli.py, reconcile/gitlab_permissions.py
add threading to gitlab-permissions integration to speed up the runtime from ~a minute to ~9 seconds
=> [gitlab-permissions] add threading

reconcile/slack_usergroups.py
when showing a warning, proceed with actions (remove `else`)
=> [slack-usergroups] proceed on warning

reconcile/github_org.py
Reverts app-sre/qontract-reconcile#166
=> Revert "[github] delete empty teams"

reconcile/github_org.py
this one is not working as expected (see [this](https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-build-master/1024/artifact/reports/reconcile_reports_success/reconcile-github.txt))
=> [wip][github] delete empty teams fix

reconcile/openshift_users.py
fixes this - https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-pr-check/2544/app-interface_20JSON_20validation/
=> [openshift-users] do not delete admin users

reconcile/github_users.py, utils/oc.py, utils/raw_github_api.py, utils/retry.py, utils/terraform_client.py
created a retry decorator that retries the function if it throws an error as requested in this [PR](https://github.com/app-sre/qontract-reconcile/pull/154#pullrequestreview-269575846)
=> Retry decorator

utils/gql.py
and re-raise it as a GraphQL error, as done in rest of function.
closes #110
=> catch graphql error

reconcile/github_org.py
This PR adds the ability to specify vault secret path in a v2 secret engine.
This would probably need to be done for other integrations as well as we move forward.
=> [github-org] handle vault v2 secret engine

reconcile/quay_membership.py
This PR adds the ability to specify vault secret path in a v2 secret engine.
=> [quay-*] handle vault v2 secret engine

utils/gitlab_api.py
fixes the access_level so adding members is successful.
also did some cleanups.
=> [gitlab-members] fix integration

e2e_tests/create_namespace.py, e2e_tests/dedicated_admin_rolebindings.py, e2e_tests/test_base.py, reconcile/openshift_groups.py, reconcile/openshift_namespaces.py, reconcile/openshift_resources.py, reconcile/openshift_users.py, reconcile/terraform_resources.py, reconcile/terraform_users.py, utils/oc.py, utils/terrascript_client.py
as many integrations were added in a short period of time, a lot of code was duplicated.
this PR consolidates the usage of oc_map by creating a reusable `OC_Map` class.
this will also lay the ground work for #112.
covers https://jira.coreos.com/browse/APPSRE-922
contributes to https://jira.coreos.com/browse/APPSRE-897
=> consolidate usage of oc_map

reconcile/cli.py, utils/binary.py
covers https://jira.coreos.com/browse/APPSRE-899
closes #93
=> add binary test before integration execution

reconcile/github_org.py
covers https://jira.coreos.com/browse/APPSRE-804
=> [github-org] case insensitive

utils/oc.py
fixes https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-pr-check/2825/app-interface_20JSON_20validation/
https://github.com/app-sre/qontract-reconcile/blob/master/utils/oc.py#L197-L198
=> fix AttributeError: 'bool' object has no attribute 'cleanup'

reconcile/quay_membership.py, reconcile/test/test_quay_membership.py
instead of testing each user processed, only check users about to be added (as anyone already in the team obviously exists).
=> [quay-membership] Hurry up

dockerfiles/Dockerfile, reconcile/cli.py, reconcile/openshift_resources.py, utils/openssl.py
covers https://jira.coreos.com/browse/APPSRE-637
depends on #188
=> [openshift-resources] Routes - validate TLS certificate FQDN matches route FQDN

reconcile/gitlab_housekeeping.py, utils/gitlab_api.py
covers https://jira.coreos.com/browse/APPSRE-925
replaces #196
=> [gitlab-housekeeping] add support for merge requests

reconcile/github_users.py, reconcile/gitlab_permissions.py, reconcile/ldap_users.py, reconcile/openshift_groups.py, reconcile/openshift_namespaces.py, reconcile/openshift_resources.py, reconcile/openshift_rolebinding.py, reconcile/openshift_users.py, reconcile/terraform_resources.py, utils/aws_api.py, utils/terraform_client.py, utils/terrascript_client.py, utils/threaded.py
consolidate how we do multi-threading across the code base.
=> consolidate threading

utils/aws_api.py
This PR does:
1. makes the map_resources run concurrently for all resource types.
2. adds pagination for resources list where applicable.
covers:
- https://jira.coreos.com/browse/APPSRE-900
- https://jira.coreos.com/browse/APPSRE-951
closes #89
=> [aws-garbage-collector] add threading and pagination

e2e_tests/create_namespace.py, e2e_tests/dedicated_admin_rolebindings.py, e2e_tests/test_base.py, reconcile/openshift_groups.py, reconcile/openshift_namespaces.py, reconcile/openshift_resources.py, reconcile/openshift_rolebinding.py, reconcile/openshift_users.py, reconcile/terraform_resources.py, utils/oc.py
This PR adds the ability to specify integrations and e2e tests that should not be executed for specific clusters.
=> [openshift-*] add option to disable specific clusters

openshift/qontract-reconcile.yaml, utils/slack_api.py
also adds parameter to sleep duration between executions
=> error handle for rate limit

reconcile/slack_usergroups.py
covers https://jira.coreos.com/browse/APPSRE-995
=> [slack-usergroups] improve missing users warnings

utils/jjb_client.py
covers https://jira.coreos.com/browse/APPSRE-994
=> [jenkins-job-builder] introduce global levels

reconcile/gitlab_housekeeping.py
fixes https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-build-master/1313/artifact/reports/reconcile_reports_fail/reconcile-gitlab-housekeeping.txt
=> [gitlab-housekeeping] except error

reconcile/openshift_resources.py, utils/threaded.py, utils/vault_client.py
Reverts app-sre/qontract-reconcile#219
=> Revert "[openshift-resources] sort by type"

reconcile/cli.py, reconcile/openshift_network_policies.py
This integration reconciles NetworkPolicies to allow traffic between namespaces.
covers https://jira.coreos.com/browse/APPSRE-1027
=> [openshift-network-policies] introduce integration

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/jira_watcher.py, setup.py, utils/jira_client.py, utils/slack_api.py
this integration detects changes in Jira issues and sends updates on Slack
=> [jira-watcher] introduce new integration

reconcile/terraform_users.py, utils/terrascript_client.py
covers https://jira.coreos.com/browse/APPSRE-1048
=> terraform-users fix user policy attachments

reconcile/cli.py, reconcile/gitlab_housekeeping.py
This PR adds a new function to housekeeping - auto merge.
when a MR is labeled with (currently hard coded) either `lgtm` or `automerge`, it will be merged when:
- all pipelines are done
- last pipeline is a sucess
=> [gitlab-housekeeping] automerge

utils/vault_client.py
as we have most of our secrets in v2, this would probably ease the pressure off vault a bit.
=> [vault_client] try v2 before v1

e2e_tests/test_base.py
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-periodic-job-e2e-tests/97/console
=> ignore uhc integration tests in e2e tests

reconcile/gitlab_housekeeping.py
=> [gitlab-houseleeping] iterate in reverse order

reconcile/aws_garbage_collector.py, reconcile/aws_iam_keys.py, reconcile/aws_support_cases_sos.py, reconcile/github_scanner.py, reconcile/github_users.py, reconcile/gitlab_housekeeping.py, reconcile/gitlab_members.py, reconcile/gitlab_permissions.py, reconcile/jenkins_job_builder.py, reconcile/jenkins_webhooks.py, reconcile/ldap_users.py, reconcile/queries.py, reconcile/terraform_resources.py, reconcile/terraform_users.py
this PR adds the following functions to queries:
queries.get_repos - returns all repos defined under code components
queries.get_aws_accounts - returns all aws accounts
queries.get_gitlab_instance - returns a single gitlab instnace
=> [queries] add common query functions

reconcile/cli.py, utils/environ.py
this decorator checks the existence of environment variables before execution.
=> add environ decorator

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
this PR adds the following integrations to run inside the pod:
- github-users
- github-scanner
- aws-support-cases-sos
=> add new integrations to pod

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
=> different requests and limits

reconcile/openshift_base.py, reconcile/terraform_resources.py, utils/oc.py
covers https://jira.coreos.com/browse/APPSRE-1142 (effort 2)
=> [terraform-resources] recycle pods

reconcile/aws_iam_keys.py, reconcile/terraform_resources.py, utils/aws_api.py, utils/lean_terraform_client.py
covers https://jira.coreos.com/browse/APPSRE-1142 (effort 1)
=> [aws-iam-keys] automated key recycle

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
since we are getting rate limited and this integration is not really acting at this time, disable it.
=> [github-users] disable integration

utils/gitlab_api.py
now that we have automated recycle in place, these PRs can be auto merged!
=> automerge PRs to delete aws keys

utils/terrascript_client.py
handle disable section not defined properly
=> fix aws disable integrations

reconcile/ldap_users.py
and do that after users are removed!
=> [ldap-users] check that users has a single user file

reconcile/openshift_groups.py, reconcile/openshift_rolebindings.py, reconcile/openshift_users.py
covers https://jira.coreos.com/browse/APPSRE-1177
=> [openshift-groups] refactor to use access

reconcile/github_org.py, reconcile/test/test_github_org.py
covers https://jira.coreos.com/browse/APPSRE-1178
=> [github] refactor cluster auth

reconcile/github_org.py, reconcile/test/test_github_org.py
Reverts app-sre/qontract-reconcile#301
=> Revert "[github] refactor cluster auth"

README.md, dockerfiles/Dockerfile, dockerfiles/Dockerfile.test, reconcile/openshift_resources.py, setup.py, tox.ini, utils/gpg.py, utils/jinja2_ext.py, utils/jump_host.py, utils/oc.py, utils/openshift_resource.py, utils/terraform_client.py
this PR, if and when merged, closes issue #27 and #28.
=> python3 migration

e2e_tests/cli.py, reconcile/cli.py, reconcile/openshift_base.py, reconcile/openshift_resources.py, reconcile/openshift_resources_annotate.py, reconcile/openshift_rolebindings.py, utils/aggregated_list.py, utils/aws_api.py, utils/jjb_client.py, utils/jump_host.py, utils/oc.py, utils/terrascript_client.py
also replaces an iteration over a dictionary with an iteration over a copy of the dictionary
=> py3: replace e.message with str(e)

reconcile/terraform_resources.py, utils/terrascript_client.py
covers https://jira.coreos.com/browse/APPSRE-1185
=> [terraform-resources] add support for ElastiCache parameter group

reconcile/terraform_resources.py, utils/terrascript_client.py
covers https://jira.coreos.com/browse/APPSRE-1191
=> [terraform-resources] RDS parameter group support

utils/terrascript_client.py
covers https://jira.coreos.com/browse/APPSRE-1097
=> [terraform-resource] enable s3 encryption

reconcile/gitlab_housekeeping.py
currently the labels are hard coded, we would need to extract labels from all around to parameters. this will be done in a future PR.
=> [gitlab-housekeeping] ignore labels on rebase

reconcile/openshift_rolebindings.py, reconcile/openshift_users.py
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-pr-check/4477/app-interface_20JSON_20validation/
=> fix integraitons using openshift_rolbindings.fetch_desired_state

reconcile/gitlab_members.py, reconcile/jenkins_plugins.py, reconcile/jenkins_roles.py, reconcile/openshift_groups.py, reconcile/openshift_users.py
```
INFO: dict_values(['assign_role_to_user', 'ci-int', 'ci-int', 'username'])
```
=> py3 - fix dict_values logging

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
covers https://jira.coreos.com/browse/APPSRE-1206
=> add integrations as pods

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
templating does not work with this, need to fix template in helm chart
=> double curly brackets

utils/terrascript_client.py
use name of parameter group if specified
=> [terraform-resources] minor fix

e2e_tests/cli.py, e2e_tests/create_namespace.py, e2e_tests/dedicated_admin_rolebindings.py, e2e_tests/dedicated_admin_test_base.py, e2e_tests/default_project_labels.py, e2e_tests/test_base.py, tox.ini
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-periodic-job-e2e-tests/134/
https://coreos.slack.com/archives/CCX9DB894/p1574316491397100
=> fix e2e tests

reconcile/openshift_resources.py, reconcile/slack_usergroups.py
openshift-resources - fail on fetch errors
slack-usergroups - retry github/gitlab owners fetch
=> error handling in integrations

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
adjust resources for new integrations
=> adjust resources

utils/terrascript_client.py
Reverts app-sre/qontract-reconcile#365
=> Revert "sqs split policies by spec"

utils/oc.py
covers https://jira.coreos.com/browse/APPSRE-1277
=> openshift-users delete user identity

reconcile/cli.py, reconcile/terraform_resources.py
covers https://jira.coreos.com/browse/APPSRE-1275
=> [terraform-resources] run light mode

utils/terraform_client.py
https://jira.coreos.com/browse/APPSRE-1274
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-periodic-job-periodic-integrations/11771/artifact/reports/reconcile_reports_fail/reconcile-terraform-resources.txt
=> terraform init retry

reconcile/terraform_resources.py, utils/terrascript_client.py
covers https://jira.coreos.com/browse/APPSRE-1282
This PR adds a new terraform provider: `ecr`.
=> [terraform-resource] add ecr support

utils/terrascript_client.py
covers https://jira.coreos.com/browse/APPSRE-1236
=> [terraform-resources] validate rds name

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/terraform_resources.py, utils/vault_client.py
covers https://jira.coreos.com/browse/APPSRE-1284
=> terraform-resources vault outputs

reconcile/openshift_resources.py
This PR adds an ability to specify `validate_json` for a `resource` in app-interface, and that resource's data will be json validated.
covers https://jira.coreos.com/browse/APPSRE-1139
=> validate json for dashboards

reconcile/jenkins_plugins.py, utils/jjb_client.py
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-pr-check/5187/app-interface_20JSON_20validation/
=> fix jenkins integrations

utils/gpg.py
covers the following cases that were uncaught but were invalid:
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2279
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2283
@apahim @mmclanerh please review
=> [terraform-users] add more gpg validations

README.md, reconcile/cli.py, reconcile/openshift_acme.py, reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_groups.py, reconcile/openshift_limitranges.py, reconcile/openshift_namespaces.py, reconcile/openshift_network_policies.py, reconcile/openshift_resources.py, reconcile/queries.py, reconcile/terraform_resources.py, utils/oc.py, utils/openshift_resource.py
covers https://jira.coreos.com/browse/APPSRE-1060.
a lot of previous art taken from #259 
matching app-interface PR - https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2302
=> [openshift-clusterrolebindings] introduce new integration

dockerfiles/Dockerfile
covers https://jira.coreos.com/browse/APPSRE-1314
=> add v4 user id to dockerfile

reconcile/openshift_acme.py, reconcile/queries.py, utils/openshift_acme.py, utils/openshift_resource.py
required to properly reconcile on a v4 cluster
=> [openshift-acme] add rbac api version override

reconcile/openshift_acme.py, reconcile/openshift_resources.py, reconcile/queries.py
covers https://issues.redhat.com/browse/APPSRE-1357
completed by https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2430
=> [openshift-acme] add support for account secret

README.md, reconcile/cli.py, reconcile/gitlab_permissions.py, reconcile/gitlab_projects.py, reconcile/queries.py, utils/gitlab_api.py
covers https://issues.redhat.com/browse/APPSRE-1371
completes https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2485
This PR adds a new integration that creates projects in gitlab on on request.
=> [gitlab-projects] introduce new integration

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_groups.py, reconcile/openshift_groups.py, reconcile/openshift_users.py, reconcile/queries.py, utils/ocm.py
covers https://issues.redhat.com/browse/APPSRE-1382
This integration adds the ability to manage OpenShift groups via OCM.
=> [ocm-groups] introduce new integration

utils/ocm.py
this should help reduce `ERROR: Certificate did not match expected hostname`
=> [ocm-groups] increase retry max_attempts to 10

utils/openshift_resource.py
covers https://issues.redhat.com/browse/APPSRE-774
=> apply Role without sorting keys

utils/container.py
tags/list endpoint is paginated. This patch adds support for pagination
so we get all the tags.
=> Fix TAG listing pagination

utils/container.py
=> Fix manifest url

reconcile/openshift_resources.py, utils/terrascript_client.py
covers https://issues.redhat.com/browse/APPSRE-1299
=> ignore $schema on resources

utils/openshift_resource.py
required to deploy prometheus operator via app-interface.
see https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2571
=> [openshift-resources] add support for Service

reconcile/quay_mirror.py
The deep sync - where we compare each image's tag manifest - is expensive
and time consuming. Also, there's no need to run it all the time.
For new tags in the mirror images, the tag will still be sync'ed right away,
but checking tag's manifests will now happen every ~8h.
That means that tags that are constantly updated, like 'latest', 'master',
'build', ... will face a delay to be freshly available in quay.io
=> [quay-mirror] Avoiding constant deep (slow) image sync

reconcile/terraform_resources.py, utils/terrascript_client.py
covers https://issues.redhat.com/browse/APPSRE-1244
=> [terraform-resources] add support for s3-cloudfront

dockerfiles/Dockerfile
part of https://issues.redhat.com/browse/APPSRE-1341
=> add prod v4 user to dockerfile

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
=> Use busybox from quay.io

tools/qontract_cli.py
a tool that does templating should also be able to print the templated result.
try it!
```
qontract-cli --config config.toml template <cluster> <namespace> <kind> <name>
```
=> [qontract-cli] add template command

tools/app_interface_reporter.py, utils/gitlab_api.py
this PR changes:
- each report name (`<app>` -> `<app>-<date>`)
- the title of the email (isodate -> short date)
=> [app-interface-reporter] touchups

utils/container.py
Not all the endpoints will require authorization. Those who do will
inform the realm, the service and the scope in the Www-Authenticate
response header.
Can't get tags from registry.centos.org:
```
>>> from utils.container import Image
>>> i = Image('registry.centos.org/centos/nginx')
>>> list(i)
[]
```
`get_manifest()` raises an exception:
```
>>> from utils.container import Image
>>> i = Image('registry.centos.org/centos/nginx')
>>> i.get_manifest()
File "<stdin>", line 1, in <module>
File "/home/apahim/git/qontract-reconcile/utils/retry.py", line 16, in f_retry
return f(*args, **kwargs)
File "/home/apahim/git/qontract-reconcile/utils/container.py", line 159, in get_manifest
'Authorization': f'Bearer {self._get_auth_token()}',
File …
```
=> Fix auth logic

utils/container.py
=> Log error message for unauthorized token

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/openshift_base.py
to avoid revealing secrets so easily.
also re-enabled logging to slack.
=> [openshift-resources] check namespaces exists before apply

reconcile/sentry_config.py
running sentry-config in dry-run mode
=> Fix issue trying to list project alert rules for a new project when

reconcile/jenkins_job_builder.py, reconcile/queries.py, utils/jjb_client.py
still need to add support for bots
=> [jenkins-job-builder] validate admins are app-interface users

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
=> Bumping memory for sql-query

reconcile/queries.py, reconcile/sql_query.py
=> Adding support for filesystem output

e2e_tests/dedicated_admin_rolebindings.py, e2e_tests/dedicated_admin_test_base.py, e2e_tests/default_network_policies.py, e2e_tests/network_policy_test_base.py
adjusting the following tests to OSDv4:
- default-network-policies
- dedicated-admin-rolebindings
=> [e2e-tests] adjust to v4

README.md
=> Adding SQL-Query to the README

utils/terrascript_client.py
took another look at:
- https://issues.redhat.com/browse/APPSRE-1244
- https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-bucket-user-policy-specifying-principal-intro.html
=> [terraform-resources] fix s3-cloudfront principal

helm/qontract-reconcile/templates/template.yaml, reconcile/github_repo_invites.py
=> Using the github-mirror as github API

reconcile/github_repo_invites.py, utils/raw_github_api.py
Let's use it for more integrations now that it's proven to work.
=> Moving the GITHIB_API from the integration to the util

reconcile/github_org.py, reconcile/github_users.py
=> PyGithub to use github-mirror

utils/terrascript_client.py
=> [terraform-resources] fix reconcile of cloudfront bucket policy

reconcile/openshift_namespaces.py
=> Added error handling for openshift-namespace

reconcile/slack_usergroups.py, utils/git_secrets.py, utils/oc.py, utils/raw_github_api.py, utils/secret_reader.py, utils/slack_api.py, utils/terraform_client.py
=> Fix retry import

setup.py
=> Fix terrascript version

reconcile/openshift_acme.py, reconcile/queries.py, utils/openshift_acme.py
Related to https://issues.redhat.com/browse/APPSRE-1435
Wait for https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3314 to be merged before merging this.
=> Add support for named secrets in openshift-acme

reconcile/owner_approvals.py, reconcile/queries.py
This PR changes the ownership model from owning an app to owning a saas file.
This will grant more granularity to allow different people to own specific deployments.
app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3369
=> [owner-approvals] owners per saas file

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
moving it to run in app-interface periodic job for now
=> remove openshift-saas-deploy from template

reconcile/openshift_saas_deploy.py, reconcile/queries.py, utils/saasherder.py
This PR adds an option to define a secret in vault that contains 'user' and 'token' keys to authenticate with a docker registry.
This is required to check images in private repos.
app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3375
=> [openshift-saas-deploy] add image auth

reconcile/cli.py, reconcile/gitlab_housekeeping.py
=> Housekeeping optinal rebases

reconcile/queries.py
=> Add gitlabRepoOwners to the query

utils/repo_owners.py
=> Fix root owners

reconcile/slack_usergroups.py
Since we have no repository context, only one OWNERS_ALIASES is allowed.
There seems to be different standards for this file although the most
commonly found is to have just one in the root of the repository. We
will follow this approach.
See https://issues.redhat.com/browse/APPSRE-1484
=> Take OWNERS_ALIASES into account

utils/saasherder.py
python's True should be set to 'true'
python's False should be set to 'false'
=> [openshift-saas-deploy] fix parameters collection

reconcile/gitlab_owners.py, utils/repo_owners.py
=> Adding get_root_owners to the RepoOwners class

utils/gpg.py
terraform-users is currently failing with the following error:
```
gpg: Fatal: can't create directory `//.gnupg': Permission denied
```
adding this option should prevent the creation of the gnupg directory.
=> gpg no options

README.md, reconcile/cli.py, reconcile/gitlab_fork_compliance.py, utils/gitlab_api.py
This re-implements the `test_fork.sh` as an integration.
=> New integration: gitlab-fork-compliance

reconcile/gitlab_fork_compliance.py
Turned the checks into a class for more convenience.
=> Adding error code handler

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml
Change logs config in the Helm chart file. Prepare to ship logs to additional providers
https://issues.redhat.com/browse/APPSRE-1618
=> change log value

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
=> Silence quay-mirror from slack

utils/sentry_client.py
This PR adds retries to Sentry API calls.
=> [sentry] retry api calls

reconcile/cli.py, reconcile/gitlab_housekeeping.py, reconcile/queries.py
covers https://issues.redhat.com/browse/APPSRE-1633
this PR changes gitlab-housekeeping to iterate over projects found in app-interface query.
matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3670
=> [gitlab-housekeeping] run integration according to gql query

reconcile/gitlab_fork_compliance.py, utils/gitlab_api.py
=> Replacing direct calls to gl client by our APIs

reconcile/openshift_saas_deploy.py, reconcile/queries.py, utils/saasherder.py
This PR adds github auth for private repos, and extracts the image auth from the resource templates.
matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3691
=> improve saas file authentication

reconcile/jira_watcher.py, utils/jira_client.py, utils/slack_api.py
covers https://issues.redhat.com/browse/APPSRE-1630
revive jira-watcher!
=> [jira-watcher] basic auth instead of oauth

utils/openshift_resource.py
this workaround is required due to https://redhat.service-now.com/surl.do?n=INC1224482
=> [openshift-saas-deploy] handle Deployment apiVersion mutation

utils/oc.py
match https://github.com/openshiftio/saasherder/pull/120
=> [openshift-saas-deploy] ignore-unknown-parameters

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, utils/terrascript_client.py
matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3728
=> [terraform-vpc-peerings] add connection name

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
closes https://issues.redhat.com/browse/APPSRE-1630
depends on https://issues.redhat.com/browse/DPP-4517
=> [jira-watcher] re-add to template

utils/terrascript_client.py
=> Fix crash is terraform-resources is disabled for an aws account.

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
Integration is failing. Disabling for now as this is not critical.
=> Temporarily disable terraform-vpc-peerings

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
Reverts app-sre/qontract-reconcile#597
=> Revert "Temporarily disable terraform-vpc-peerings"

reconcile/terraform_resources.py
=> handle errors thrown during reconcile run

reconcile/jenkins_job_builder.py, utils/jjb_client.py
Covers https://issues.redhat.com/browse/APPSRE-1663
This PR improves the error handling of the jenkins-job-builder integration.
=> [jenkins-job-builder] improve error handling

reconcile/cli.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, utils/saasherder.py
This PR adds slack notifications of deployments.
It is very raw, but it will mostly return the right result. Notifications are currently only for a change in the commit hash (if hash is set to `master` - it looks at the backing commit).
matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3818
=> [openshift-saas-deploy] basic slack notifications

reconcile/terraform_resources.py, utils/terrascript_client.py
covers https://issues.redhat.com/browse/APPSRE-1667
This PR adds support for RDS enhanced monitoring by adding a required role and policy attachment, as described in:
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/v1.17.0/examples/enhanced-monitoring/main.tf
=> [terraform-resources] add RDS enhanced monitoring support

utils/terrascript_client.py
retention_in_days was ignored. this PR fixes it.
=> [terraform-resources] fix cloudwatch log groups retention in days

reconcile/jira_watcher.py, utils/jira_client.py
part of https://issues.redhat.com/browse/APPSRE-1680
=> extract jira server from jira board

reconcile/jira_watcher.py, reconcile/queries.py, utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-1680
=> extract slack workspace from jira board, intoduce slack workspace integrations

README.md, reconcile/cli.py, reconcile/gitlab_integrations.py, reconcile/queries.py
Covers https://issues.redhat.com/browse/APPSRE-1650
This PR adds a new integration called `gitlab-integrations`.
This integration will configure integrations for GitLab projects, starting with the Jira integration.
=> [gitlab-integrations] introduce new integration

utils/slack_api.py
This PR reduces the number of API calls by the number of user groups we manage.
yay!
=> [slack-usergroups] reduce API calls

openshift/qontract-reconcile.yaml
=> update fluentd memory limit

tools/app_interface_reporter.py
temporary fix for reports.
fixes https://issues.redhat.com/browse/APPSRE-1709
depends on https://issues.redhat.com/browse/APPSRE-1674 to re-enable.
=> [app-interface-reporter] disable SLO section

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
part of https://issues.redhat.com/browse/APPSRE-1587
=> update cpu requests and limits

openshift/qontract-reconcile.yaml
This was missing in https://github.com/app-sre/qontract-reconcile/pull/627
=> Add performance parameters to openshift template

dockerfiles/Dockerfile
=> Fix permissions inside jsonnet vendor dir

openshift/qontract-reconcile.yaml
It was accidentally deleted in #641
=> Add performance parameters to openshift template (#633)

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
part of https://issues.redhat.com/browse/APPSRE-1587
=> update CPU reqa and limits

utils/saasherder.py
this PR improves the logging messages to include the saas file name, resource template name and the template url in order to quickly find locations of problems.
=> [openshift-saas-deploy] improve logging

README.md
=> Add doc reference to the existing helm chart

utils/openshift_resource.py, utils/saasherder.py
example: https://github.com/RedHatInsights/saas-templates/blob/master/templates/inventory/insights-host-delete.yaml#L6
=> [openshift] handle null annotations

dockerfiles/Dockerfile.test
=> Fix helm version

reconcile/gitlab_owners.py, utils/repo_owners.py
They don't merge, but the do cleanup reviewers messages.
Example:
https://gitlab.cee.redhat.com/service/managed-tenants/merge_requests/113
=> Adding reviewers to the loop

utils/repo_owners.py
=> Return sorted list

reconcile/gitlab_owners.py
=> Fix reviewers approval

README.md, reconcile/cli.py, reconcile/ldap_users.py, reconcile/queries.py, reconcile/user_validator.py
covers https://issues.redhat.com/browse/APPSRE-1760
this PR adds a new validating integration which should only run in pr-checks (same as service-dependencies).
=> [user validator] introduce new integration

reconcile/queries.py, reconcile/slack_usergroups.py, utils/github_api.py
Depends on https://github.com/app-sre/qontract-reconcile/pull/632
=> Replacing OWNERS logic by RepoOwners util

utils/oc.py
=> Recycle pods connected to Deployments and DeploymentConfigs using

utils/terrascript_client.py
covers https://issues.redhat.com/browse/APPSRE-1771
=> rename terraform provider service-account to aws-iam-service-account

reconcile/jira_watcher.py
covers https://issues.redhat.com/browse/APPSRE-1772
=> [jira-watcher] add summary

reconcile/github_scanner.py
The try block is starting too late, after the point where the exception
can actually happen. Fixing, while increasing the logging severity.
=> Place the try in the correct position

reconcile/openshift_saas_deploy.py, setup.py, utils/saasherder.py
This PR adds multithreading to the desired state population.
It also removes the retry without image auth as fixed in https://github.com/app-sre/sretoolbox/pull/7.
cc @kylape
=> [openshift-saas-deploy] fetch desired state with mutlithreads

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
=> Get the GITHUB_API endpoint from the ConfigMap

reconcile/queries.py, templates/slo-rules.jsonnet.j2
There has been some effort of simplification on the SLOs definition. https://gitlab.cee.redhat.com/service/app-interface/merge_requests/4196. This PR reflects that work
=> Simplify handling of errors and volume SLOs

utils/oc.py
Reverts app-sre/qontract-reconcile#674
=> Revert "Recycle pods connected to Deployments and DeploymentConfigs using"

reconcile/jenkins_job_builder.py, utils/jjb_client.py
Reverts app-sre/qontract-reconcile#603
=> Revert "[jenkins-job-builder] improve error handling"

reconcile/gitlab_housekeeping.py
In the case that a MR has additional labels expect for `lgtm`, the automerge doesn't work. This PR handles that.
still very ugly that the labels are hard coded. we'll get there.
@apahim can you please review?
=> [gitlab-housekeeping] handle additional labels

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
This PR adds log output to different integrations.
It only adds `cloudwatch` to some of them.
@BumbleFeng, can you give your blessing?
=> add log outputs to integrations

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/openshift_resourcequotas.py, reconcile/queries.py
covers https://issues.redhat.com/browse/APPSRE-1761
This PR adds a new integration called openshift-resourcequotas which manages ResourceQuota resources in OpenShift namespaces.
=> [openshift-resourcequotas] introduce new integration

reconcile/cli.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, utils/openshift_resource.py, utils/saasherder.py
This PR adds a handler for empty saas-file-name or env-name.
It also adds some improvements in resource comparison, and changes slack notifications to only be executed in non dry-run mode.
=> [openshift-saas-deploy] handle empty saas-file-name or env-name

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
So that we can avoid `latest` tag
=> Make busybox and fluentd images configurable

reconcile/openshift_resources.py
trying to make this error message more readable for users.
wdyt?
=> invalid resource type error message

reconcile/jenkins_job_builder.py, reconcile/queries.py
This PR adds a dynamic jenkins job generation per saas file per environment.
=> [jenkins-job-buidler] dynamically generate openshift-saas-deploy jobs

tools/qontract_cli.py
This command shows the usage of each acme-account secret across app-interface.
=> [qontract-cli] add acme-accounts get command

reconcile/openshift_saas_deploy.py, utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-1809
=> [openshift-saas-deploy] validate unique saas file names

utils/jenkins_api.py
=> [jenkins_api] add trigger_job method

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py
=> multiple_callers to caller

reconcile/cli.py, reconcile/jenkins_job_builder.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, utils/saasherder.py
This PR removes Slack notifications from openshift-saas-deploy.
The responsibility to send notifications will be on the actual worker. In our case - Jenkins.
This PR also adds a templating of slack_channel in to the JJB template.
=> [openshift-saas-deploy] remove slack notifications

reconcile/queries.py, utils/saasherder.py
This PR adds the option to define `parameters` in an environment file, or in the root level of a saas-file.
=> [openshift-saas-deploy] add environment and saas-file level parameters

reconcile/github_org.py, utils/saasherder.py
this will make it easier to run this integration in jenkins instances with lesser privileges.
=> [openshift-saas-deploy] avoid initiating all github orgs

utils/saasherder.py
this is the most common failure scenario we are seeing, let's retry a couple of times
=> [openshift-saas-deploy] add retry to _get_file_contents

reconcile/owner_approvals.py
=> [owner-approval] hash to ref

reconcile/openshift_performance_parameters.py, templates/slo-rules.jsonnet.j2
https://issues.redhat.com/browse/APPSRE-1839
=> Add component to labels

README.md, reconcile/cli.py, reconcile/openshift_saas_deploy_trigger_configs.py, utils/saasherder.py
This PR adds an integration called openshift-saas-deploy-trigger-configs.
Whenever configuration changes in app-interface, this integration will trigger the correct jobs in Jenkins to perform the required deployment operations.
=> [openshift-saas-deploy] trigger configs

reconcile/jenkins_job_builder.py
This PR adds support for using a `with-upstream` job template if `upstream` is defined on the target (a jenkins job to build after).
=> [jjb] support upstream targets

reconcile/gitlab_owners.py
=> Avoid approving empty commits

utils/repo_owners.py
=> bug fx - change item[path] to iten[name]

reconcile/owner_approvals.py, utils/gitlab_api.py
This PR adds a message to the app-interface owner approval mechanism.
=> gitlab add comment to merge request method

utils/terrascript_client.py
Resolves https://issues.redhat.com/browse/APPSRE-1870
=> update db name validation logic

utils/saasherder.py
we need to override parameters in the following order:
environment -> saas file -> resource template -> target
=> [openshift-saas-deploy] consolidate parameters the right way

utils/saasherder.py
This PR adds support for:
* dictionary like objects in parameters
* initContainers in image checks
* CronJobs in image check
* CatalogSources in image check
=> [openshift-saas-deploy] align with latest saasherder additions

utils/saasherder.py
each saas file must have at least one owner.
=> [openshift-saas-deploy] warn on no owners

utils/repo_owners.py
This actually broke the integration. Let's revert now until there's a proper implementation.
=> Revert OWNER_ALIASES changes

tools/qontract_cli.py
make the output of the command more useful. namely, allow to pipe it to bash.
=> [qontract-cli] saas-dev add oc apply to output

utils/oc.py
covers https://issues.redhat.com/browse/APPSRE-1817
This PR adds support to recycle pods when a change is detected in a ConfigMap and it has the `qontract.recycle: true` annotation.
=> [openshift] recycle on ConfigMap change

reconcile/openshift_saas_deploy_trigger_configs.py, utils/saasherder.py
watch for changes in saas file and resource template parameters.
=> [openshift-saas-deploy-trigger-configs] watch for changes in more parameters

README.md, reconcile/cli.py, reconcile/saas_file_owners.py
https://issues.redhat.com/browse/APPSRE-1899
=> rename owner-approvals to saas-file-owners

reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, utils/jenkins_api.py
exit with error when triggers are not succesful
first need to fix ci-ext job triggers:
```
403 Client Error: No valid crumb was included in the request for url: https://ci.ext.devshift.net/job/openshift-saas-deploy-saas-github-mirror-App-SRE-stage/build
```
=> [openshift-saas-deploy-triggers] exit on error

dockerfiles/Dockerfile, dockerfiles/Dockerfile.test, helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml, reconcile/aws_garbage_collector.py, reconcile/aws_iam_keys.py, reconcile/aws_support_cases_sos.py, reconcile/cli.py, reconcile/github_org.py, reconcile/github_repo_invites.py, reconcile/github_scanner.py, reconcile/github_users.py, reconcile/github_validator.py, reconcile/gitlab_housekeeping.py, reconcile/gitlab_integrations.py, reconcile/gitlab_members.py, reconcile/gitlab_permissions.py, reconcile/gitlab_pr_submitter.py, reconcile/gitlab_projects.py, reconcile/jenkins_job_builder.py, reconcile/jenkins_plugins.py, reconcile/jenkins_roles.py, reconcile/jenkins_webhooks.py, reconcile/ldap_users.py, reconcile/quay_membership.py, reconcile/quay_mirror.py, reconcile/quay_repos.py, reconcile/sentry_config.py, reconcile/slack_usergroups.py, setup.py
part of https://issues.redhat.com/browse/APPSRE-1728
this PR adds a check for the state of a feature toggle in an unleash instance.
if the feature toggle does not exist, the integration will be executed.
depends on https://gitlab.cee.redhat.com/service/app-interface/merge_requests/4816
=> introduce feature toggles using unleash

utils/terrascript_client.py
=> change the way db name is handled

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/github_owners.py
part of https://issues.redhat.com/browse/APPSRE-1909
this PR adds a new integration called `github-owners`, which adds users an Owner role in github organizations (this will only happen after user has accepted the invitation).
=> [github-owners] introduce new integration

reconcile/saas_file_owners.py, utils/gitlab_api.py
part of https://issues.redhat.com/browse/APPSRE-1857
this PR adds:
- print required owners if applicable
- add handle for the following comments: "/hold", "/lgtm cancel", "/hold cancel"
=> [saas-file-owners] improvements

reconcile/saas_file_owners.py
part of https://issues.redhat.com/browse/APPSRE-1857
=> [saas-file-owners] add handle for new saas file

e2e_tests/cli.py, e2e_tests/create_namespace.py, e2e_tests/dedicated_admin_rolebindings.py, e2e_tests/default_network_policies.py, e2e_tests/default_project_labels.py
covers https://issues.redhat.com/browse/APPSRE-1934
=> [e2e-tests] add threading

reconcile/openshift_network_policies.py
Fixes https://issues.redhat.com/browse/APPSRE-1955
=> register error on cross cluster namespace policy

reconcile/quay_membership.py, reconcile/quay_mirror.py, reconcile/quay_repos.py, utils/quay_api.py
part of https://issues.redhat.com/browse/APPSRE-1926
this PR adds support for an alternate server url for a quay instance to all relevant integrations.
=> add support for an alternate server url for quay

utils/repo_owners.py
See individual commits for details
=> Small fixes to gitlab-owners

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/gcr_mirror.py
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/5135
=> New integration: GCR-Mirror

utils/terrascript_client.py
tenant-insights
https://projects.engineering.redhat.com/browse/RHCLOUD-6825
=> add https to endpoint

reconcile/gitlab_projects.py, utils/gitlab_api.py
covers https://issues.redhat.com/browse/APPSRE-2010
this PR adds an initiation for requested projects which have `resource: bundle` in the `codeComponents` section.
it will initiate a `master`, `staging` and `production` branches.
=> gitlab-projects initiate saas-bundle repos

setup.py
It contains a fix for the gcr-mirror integration
=> Bump sretoolbox to 0.5.2

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
openshift-network-policies
openshift-rolebindings
openshift-acme
=> run some integrations externally

dockerfiles/hack/run-integration.py
=> LOG_FILE is not always provided

dockerfiles/hack/run-integration.py
=> SLEEP time is not always provided

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
=> Fix port name

dockerfiles/hack/run-integration.py
=> Keep the previous behaviour until we have alerts

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
=> Values cannot be int

utils/sharding.py
=> Sharding log to DEBUG: INFO will flood the slack channel

reconcile/sentry_config.py
=> Sentry-config: survive to missing github user

reconcile/openshift_namespaces.py
Testing with 2 shards, each shard will:
Before
After
It didn't avoid the peaks though.
=> Moving the shards check

utils/gitlab_api.py
Reverts app-sre/qontract-reconcile#847
=> Revert "[jenkins-webhooks] diable ssl verification"

setup.py
=> Bump sretoolbox 0.6.0

reconcile/cli.py, reconcile/gitlab_housekeeping.py, reconcile/queries.py
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/5556
=> [gitlab-housekeeping] re-add support for days_interval, limit and closing

utils/saasherder.py
=> [openshift-saas-deploy] auth fix - do not return None

utils/oc.py
Come on, don't give up so easily!
=> [oc] try a bit harder

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
reverts #810 
related to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/5714
=> revert running some integration externally

utils/saasherder.py
avoid checking images when all we want to deploy is, say, ServiceMonitors.
=> [openshift-saas-deploy] filter resources before checking images

reconcile/saas_file_owners.py, utils/gitlab_api.py
=> [saas-file-owners] can't lgtm yourself

reconcile/cli.py, reconcile/github_repo_permissions_validator.py, utils/jjb_client.py
covers https://issues.redhat.com/browse/APPSRE-2048
adds an integration to validate the the app-sre-bot has edit access to all repos in which we have pr-checks defined.
=> [github-repo-permissions-validator] introduce new validating integration

utils/aws_api.py
=> [aws_api] get_cluster_vpc_id docs and key check

reconcile/saas_file_owners.py
we would like to be able to skip all integrations when changes are only to saas files.
by reading the valid_saas_files_changes_only key from the output file, we can know that.
=> [saas-file-owners] write to throughput if changes are all valid saas file changes

reconcile/github_repo_invites.py
when an invitation comes from an organization that is already present in app-interface in codeComponents sections, we now immediately accept the invitation.
=> [github-repo-invites] accept invitations from known github organizations

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
=> Fix OOM-Kill

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
=> More OOM-Kill fixes

utils/saasherder.py
covers https://issues.redhat.com/browse/APPSRE-2139
=> [openshift-saas-deploy-trigger-configs] trigger job on change to managedResourceTypes

reconcile/saas_file_owners.py
covers https://issues.redhat.com/browse/APPSRE-2138
=> [saas-file-owners] collect managedResourceTypes and imagePatterns

reconcile/openshift_saas_deploy_trigger_configs.py
reverts #873 and replaced by https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/6065
=> revert [openshift-saas-deploy-trigger-configs] skip trigger when upstream is building

reconcile/ocm_groups.py, reconcile/openshift_groups.py
covers https://issues.redhat.com/browse/APPSRE-2146
=> add support for groups management in v4 clusters via oc

reconcile/openshift_saas_deploy_trigger_configs.py
since we are running this integrations once after a merge, we want to retry triggering the job until it succeeds or until the very end.
this is to handle cases where a new config is added and leads to creating a new job (which may take a few minutes).
in addition, we are adding an option to run this job concurrently in jenkins in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/6127
=> [openshift-saas-deploy-trigger-configs] try until you die

reconcile/terraform_vpc_peerings.py
fixes https://issues.redhat.com/browse/APPSRE-2197
=> [terraform-vpc-peerings] do not reuse requester

reconcile/gitlab_housekeeping.py
by throwing an exception and using a retry, we are retrying the function `max_attempts` times.
this should make the integration insist on merging MRs according to the priority level instead of moving on to the next label.
=> [gitlab-housekeeping] insist on merging by label priority

reconcile/ocm_clusters.py, reconcile/queries.py, utils/ocm.py
This PR adds the ability for the ocm-clusters integration to provision clusters.
Provision only! no deletions, no updates, provision only.
=> [ocm-clusters] create cluster

README.md, helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/dashdotdb_cso.py
=> New integration - dashdotdb-cso

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/queries.py, reconcile/unleash_watcher.py, utils/unleash.py
this integration notifies about changes in feature toggles in Unlesah.
is is based on the same logic as jira-watcher, and we should try to re-use some of the logic in a later PR.
=> [unleash-notifier] introduce new integration

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/dashdotdb_cso.py
=> Dashdotdb: disabling slack logging

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/openshift_resources_base.py
this includes the following integrations:
- openshift-resources
- openshift-vault-secrets
- openshift-routes
=> [openshift-resources] add sharding

reconcile/cli.py
No need to be aggresive here. We have a small DB intance. Let's not
overload it.
=> Slow down dashdotdb-cso

reconcile/jenkins_job_builder.py, reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, reconcile/slack_base.py, utils/config.py, utils/saasherder.py
we want to enable users to define that they want to get a pretty version of the job logs as slack messages.
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/6778
=> saas file output support

reconcile/saas_file_owners.py, utils/gitlab_api.py
Reverts app-sre/qontract-reconcile#866
=> Revert "[saas-file-owners] can't lgtm yourself"

reconcile/openshift_base.py
covers https://issues.redhat.com/browse/APPSRE-1370
this PR adds a post deployment validation to resources of kind Subscription.
=> [openshift-saas-deploy] validate Subscription

reconcile/openshift_base.py
part of https://issues.redhat.com/browse/APPSRE-2066
to run post deployment tests we can deploy a job and validate that it succeeds.
=> [openshift-saas-deploy] validate job

reconcile/openshift_base.py
100 retries. yeah, that's how we role.
=> [openshift-saas-deploy] validate as hard as you can

reconcile/openshift_base.py
covers https://issues.redhat.com/browse/APPSRE-2308
=> [openshift-saas-deploy] skip validation when desired replicas is 0

dockerfiles/Dockerfile
Reverts app-sre/qontract-reconcile#974
=> Revert "more multistage build in Dockerfile"

reconcile/cli.py
Reverts app-sre/qontract-reconcile#975
=> Revert "tick tock"

reconcile/cli.py, reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, utils/oc.py, utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-2066
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/7306
this PR adds a collection of logs to files defined in io-dir.
=> [openshift-saas-deploy] collect jobs pods' logs to files

reconcile/openshift_groups.py, reconcile/openshift_network_policies.py, reconcile/openshift_resourcequotas.py
as we are catching exceptions at a higher level, this try-except actually causes integrations to fail when they are not supposed to.
=> remove try-except from run functions

reconcile/openshift_base.py, utils/oc.py
part of https://issues.redhat.com/browse/APPSRE-2064
=> fixes for 0x0 handle

reconcile/openshift_base.py
part of https://issues.redhat.com/browse/APPSRE-2321
=> raise error on apply that is not 0x0

utils/terrascript_client.py
=> Add S3 ObjectTagging

reconcile/service_dependencies.py
fixes https://issues.redhat.com/browse/APPSRE-2344
=> [service dependencies] github.com instead of github

setup.py
fixes #563 
w00t w00t, 1k PRs!!!
=> fix license in setup.py

reconcile/terraform_resources.py
part of https://issues.redhat.com/browse/APPSRE-2350
=> [terraform-resources] use jumphost

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml, reconcile/dashdotdb_cso.py
=> dashdotdb-cso: Use basic auth

tools/app_interface_reporter.py
Example:
$schema: /app-sre/report-1.yml
labels:
app: app-sre-observability
name: app-sre-observability-2020-08-10
app:
$ref: /services/observability/app.yml
date: '2020-08-10'
contentFormatVersion: 1.0.0
content: |
production_promotions: null
merges_to_master:
- repo: https://github.com/app-sre/aws-resource-exporter
total: 1
success: 1
container_vulnerabilities:
- cluster: app-sre-stage-02
namespace: app-sre-observability-per-cluster
vulnerabilities:
Negligible: 52
Unknown: 6
Medium: 35
High: 12
Low: 25
- cluster: app-sre-stage-02
namespace: openshift-customer-monitoring
vulnerabilities:
High: 3
- cluster: app-sre-stage-01
namespace: app-sre-observability-per-cluster
vulnerabilities:
Negligible: 52
Unknown: 6
Medium: 24
High: 5
Low: 22
- cluster: app-sre-stage-01
namespace: …
=> Monthly Report: Adding Container Vulnerabilities

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/aws_route53.py, reconcile/cli.py, reconcile/queries.py, utils/aws/route53/__init__.py, utils/aws_api.py, utils/test/test_aws_route53.py
This is a rewrite of the never-released terraform-based route53 integration. This time around I used Boto which turned a 10 minutes runtime using terraform into a runtime that takes a few seconds.
Reason why Terraform was so slow is well known upstream and is caused by the fact Terraform does multiple API calls per record per zone, causing throttling from AWS. Even though the API permits retrieving multiple records at once, Terraform does not do that.
Depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/7275
=> New aws_route53 integration

reconcile/queries.py, tools/qontract_cli.py
This tool displays the list of clusters to upgrade:
```
NAME               UPGRADE
-----------------  ---------
REDACTED           batch2
REDACTED           batch1
```
=> qontract-cli get cluster-upgrades

reconcile/jenkins_job_builder.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-2368
=> [jjb] support slack notify start for openshift-saas-deploy jobs

reconcile/ocm_clusters.py
ignores the `upgrade` key in `spec`.
cc @jmelis
=> [ocm-clusters] fix validation

reconcile/pull_request_gateway.py, utils/sqs_gateway.py
It's currently breaking with this message:
```
'SQSGateway' object has no attribute 'create_update_cluster_ids_mr'
```
=> fix ocm-clusters

reconcile/openshift_base.py
fixes:
```
[ERROR] [openshift_saas_deploy.py:run:81] - 'readyReplicas'
```
=> [openshift-saas-deploy] fix Deployment validation

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/queries.py, reconcile/sentry_helper.py, reconcile/slack_base.py, utils/smtp_client.py
this integration watches our smtp server and finds messages sent due to user issues (access requests, etc).
the integration will send a slack notification to the user pointing them to the sentry documentation that will assist them.
=> [sentry-helper] introduce new integration

reconcile/sentry_helper.py, utils/smtp_client.py
extract sentry logic out of smtp_client added in #1023
=> [sentry-helper] refactor

reconcile/openshift_saas_deploy.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/saas_file_validator.py, tools/qontract_cli.py, utils/saasherder.py
we can force reusing parameters defined on the environment instead of redefining them in saas files.
this will help us rebuild complete environments faster and update full environments to point to new endpoints, such as dependencies.
=> validate saas files are reusing environment parameters

utils/terrascript_client.py
=> add advanced_options for aws_elasticsearch_domain

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
part of https://issues.redhat.com/browse/APPSRE-2412
=> [aws-ecr-image-pull-secrets] run once per 2h

reconcile/terraform_resources.py, utils/terrascript_client.py
=> add s3 notification to sqs

reconcile/cli.py, reconcile/terraform_resources.py, utils/terrascript_client.py
=> allow running terraform-resources based integrations per account

README.md, reconcile/cli.py, reconcile/gitlab_mr_sqs_consumer.py, templates/aws_access_key_email.j2, templates/email.yml.j2, utils/mr/README.md, utils/mr/__init__.py, utils/mr/app_interface_reporter.py, utils/mr/aws_access.py, utils/mr/base.py, utils/mr/cluster_ids.py, utils/mr/cluster_version.py, utils/mr/labels.py, utils/mr/notificator.py, utils/mr/user_maintenance.py
https://issues.redhat.com/browse/APPSRE-2375
I'd higly reccomend reviewing it per-commit basis & reading the inner README as the first step :)
At the moment, this does nothing.
To use it as an SQS consumer, we have to change here:
https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/hack/periodic_job.sh#L49
From `gitlab-pr-submitter` to `gitlab-mr-sqs-consumer`.
Using it as SQS producer will be a later PR to this repo.
MR examples:
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8760
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8776
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8789
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8798
=> pr_gateway refactoring

utils/mr/app_interface_reporter.py, utils/mr/aws_access.py, utils/mr/cluster_ids.py, utils/mr/cluster_version.py, utils/mr/user_maintenance.py
=> Adjusting the labels to match gitlab_api ones

reconcile/ldap_users.py
It uses gitlab instead of sqs.
=> Fix ldap_users

reconcile/openshift_resources_base.py
This is a fix for #993 which should have done this, but apparently was not tested well enough :wink: 
Full description in #993.
=> [openshift-resources] pass dry-run when api resource is still not installed

reconcile/queries.py, reconcile/sentry_helper.py, utils/smtp_client.py
=> [sentry-helper] fixes

utils/terrascript_client.py
=> s3-sqs fix

utils/terrascript_client.py
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-key-management.html
=> enable kms encryption for sqs

utils/secret_reader.py
At the moment, if we use `secret_reader.read` to read a vault secret and we don't have permission to access the vault path, the `hvac` package will raise an exception that isn't very helpful.
This is especially problematic for integrations or utilities we use that tries to read multiple secrets consecutively. For instance some integrations will iterate through all known clusters and will attempt to get their automation token. Currently if we get a permission denied on reading one of these secrets, we don't know anything on what secret caused the error.
This change aims to catch the generic permission error from `hvac` and return a more useful exception that contains the path that couldn't be read.
=> secret_reader should raise a useful exception on vault forbidden error

reconcile/gitlab_housekeeping.py
after changes made in #949 to wait for pipelines to complete, we now no longer want to wait.
the reason for #949 was to handle a capacity issue (multiple jobs running for the same MR).
with an addition of a job cancellation (per branch) in app-interface, we now no longer want to wait:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/9454
instead, we want to rebase as soon as we can and we will cancel the currently running job (as the only job that matters is the last one before a merge).
this should shorten the time between automated merges.
=> [gitlab-housekeeping] do not wait for incomplete pipelines

reconcile/gitlab_mr_sqs_consumer.py
The way SQS works, if we don't delete the messages withing 30s from
the receive_messages(), they messages will come back in SQS ans up
for consuption.
We could just extend that 30s timeout OR, better, we can just delete in
SQS all the messages we just received right away and then process
them. This patch implementes the latter.
Baseline is: no real changes are introduced here, we now just delete
the messages in time.
=> Fixing the SQS cleaning logic

reconcile/gcr_mirror.py, reconcile/quay_mirror.py
- Private mirror
- Tags filtering
Depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/9505
=> quay-mirror/gcr-mirror new features

reconcile/saas_file_owners.py
Follow up of https://github.com/app-sre/qontract-reconcile/pull/1081#issuecomment-696534845
=> add saas_label via saas_file_owners

setup.py
- 48bfef5 Support for manifest v2
=> Promoting sretoolbox

reconcile/saas_file_owners.py
=> saas label fix

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/openshift_upgrade_watcher.py, reconcile/openshift_users.py, reconcile/queries.py, utils/oc.py
part of https://issues.redhat.com/browse/APPSRE-2514
this integration watches for the UpgradeConfig resource in each cluster and notifies in a slack channel if the cluster is currently being upgraded.
=> [openshift-upgrade-watcher] introduce new integration

reconcile/openshift_limitranges.py
=> limitrange fix

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> increase limitrange memory

reconcile/saas_file_owners.py
=> fix user with tag_on_merge_requests can not lgtm change

reconcile/openshift_base.py, utils/openshift_resource.py
Fix https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/9999 not get apply
=> fix oc resources not apply for clean up data field in configmap or secret

utils/openshift_resource.py
=> fix openshift-resource data compare

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [slack-cluster-usergroups] move from CronJob to Deployment

reconcile/saas_file_owners.py
=> Small fix to the valid_diff compare

reconcile/terraform_resources.py, utils/terrascript_client.py
=> rename alt_db_name to output_resource_db_name

utils/slack_api.py
slack is having some issues, let's hit them harder :smile: 
seriously though, retry the request when it fails.
=> slack retry get

reconcile/openshift_upgrade_watcher.py
fixing according to docs: https://api.slack.com/reference/surfaces/formatting#mentioning-groups
=> [openshift-upgrade-watcher] fix usergroup mention

reconcile/saas_file_owners.py
this PR adds a comment to MRs updating saas files with the compare url for each of the saas file diffs in the MR.
this will allow us and our users to quickly review what is currently being promoted.
=> [saas-file-owners] add compare diffs as comment to merge request

reconcile/gitlab_housekeeping.py
this PR changes the integration to first check if relevant labels exist on the MR, and only then does time consuming calculations.
this speeds up the integration from ~4m to ~30s.
=> [gitlab-housekeeping] speed up

utils/saasherder.py
this will allow to have .md files in a directory with dashboards (for example)
=> [openshift-saas-deploy] allow non-yaml files in directory provider

utils/saasherder.py
if not specified it will default to latest
=> [openshift-saas-deploy] get contents for correct ref

reconcile/terraform_resources.py
part of https://issues.redhat.com/browse/APPSRE-2614
this lays the ground to adding `sharedResources` with `terraformResources`.
=> [terraform-resources] extract tf-resource to query section

dockerfiles/Dockerfile
Made some modifications to support going from centos:7 to ubi8:8.2 for the base image
=> Convert container base form centos:7 to ubi8:8.2

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_machine_pools.py, reconcile/queries.py, utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2623
this PR introduces a new integration - ocm-machine-pools
with this integration we will be able to manage machine pools, which will allow us to run multiple instance types in a single cluster!
depends on schema changes: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10861
example usage: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10862
=> [ocm-machine-pools] introduce new integration

utils/saasherder.py
the saas file owners feature is well known at this time. we should error out on missing owners.
=> [saas-file-validator] error out on missing saas file owners

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [APPSRE-2639] Fixing openshift-users OOM-Kills

utils/mr/clusters_updates.py
check if any changes were made, and cancel MR if there weren't any.
=> [gitlab-mr-consumer] do not submit empty clusters-updates MR

reconcile/jira_watcher.py, utils/sharding.py
this PR adds a round-robin approach to the sharding module and adds usage of it for jira-watcher
=> [jira-watcher] board per shard (round robin)

utils/terrascript_client.py
=> [terraform-resources] rds determine password in dry-run without oc 2

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml, utils/gql.py
part of https://issues.redhat.com/browse/APPSRE-2663
=> [gql] add logging for graphql endpoint

utils/jsonnet.py, utils/oc.py
Reverts app-sre/qontract-reconcile#1157
cc @arilivigni @apahim
=> Revert "Don't fail on unreachable cluster retry & move on"

dockerfiles/Dockerfile
part of https://issues.redhat.com/browse/APPSRE-2684
=> upgrade oc client to v4

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
this PR adds resources for terraform-resources (we need to shard it) and adds a shard to openshift-resources.
=> increase resources for oc related integration

dockerfiles/Dockerfile
Reverts app-sre/qontract-reconcile#1166
=> Revert "add temp fix for failing rpm packages"

dockerfiles/Dockerfile
=> fix more missing dependencies

README.md, reconcile/cli.py, reconcile/kafka_clusters.py, reconcile/queries.py, utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2727
as we are onboarding Managed Services API, we need to prepare to consume their API.
this integration will create Kafka clusters via OCM and will output a Secret with required information to namespaces which will be defined as consuming a Kafka cluster.
we currently only output `bootstrapServerHost`, as the API is still WIP.
=> [kafka-clusters] introduce new integration

dockerfiles/hack/run-integration.py
=> Fix config path

dockerfiles/hack/run-integration.py
This is no behaving on stage and need more testing. Let me get out of the way for promotions to prod. I will try again later.
=> Revert main loop changes

utils/github_api.py
this should alleviate some alert fatigue related to slack-usergroups: https://ci.int.devshift.net/job/qontract-reconcile-timed-slack-usergroups/28077/console
=> [github_api] retry get_file

reconcile/quay_mirror.py
Updating secret_reader based on new structure
=> quay-mirror secret_reader update

reconcile/dashdotdb_cso.py, reconcile/ocm_github_idp.py
=> Additional fixes

reconcile/dashdotdb_cso.py
=> dashdotdb-cso fix secret_reader

reconcile/email_sender.py, reconcile/github_users.py, reconcile/requests_sender.py, reconcile/sentry_helper.py, reconcile/terraform_users.py, utils/smtp_client.py
This is yet another refactoring to avoid the global initialization of
objects.
=> SmtpClient refactoring

utils/ocm.py
https://docs.google.com/document/d/1J7HNNFIWXq5gjpsT8QQw8ehkSe40A0N55eX584fdKMA
=> [ocm-clusters] fix provision_shard_id

utils/state.py
This fixed the unleash-watcher integration on stage.
=> state: Don't get Contents from empty object

utils/vault.py
Token might expire. Let's make sure we always have a valid
token to work with.
=> Vault client: renew authentication

utils/vault.py
- Reverts commit fbc669aed0713dccb397c5c8d6e403425a2cc735.
- Creates a singletown for the VaultClient. The Class instance is then only renewed when the `is_authenticated()` return false on instance creation.
=> Vault client optimizations

README.md, reconcile/cli.py, reconcile/ocm_addons.py, reconcile/queries.py, utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2697
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/11961
this PR adds a new integration to manage addons installations via OCM.
=> [ocm-addons] introduce new integration

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_external_configuration_labels.py, reconcile/queries.py, utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2734
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/12059
=> [ocm-external-configuration-labels] introduce new integration

reconcile/cli.py, reconcile/gitlab_owners.py
part of https://issues.redhat.com/browse/APPSRE-2768
=> [gitlab-owners] ignore 0 commits MRs and run in parallel for all repos

dockerfiles/hack/run-integration.py, reconcile/cli.py, reconcile/openshift_resources.py, reconcile/status.py, utils/gql.py, utils/metrics.py, utils/oc.py, utils/qrtracking.py
```
qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{integration="openshift-resources",le="10.0",name="utils.oc.OC.apply"} 0.0
qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{integration="openshift-resources",le="30.0",name="utils.oc.OC.apply"} 0.0
qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{integration="openshift-resources",le="60.0",name="utils.oc.OC.apply"} 0.0
qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{integration="openshift-resources",le="150.0",name="utils.oc.OC.apply"} 0.0
qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{integration="openshift-resources",le="300.0",name="utils.oc.OC.apply"} 10.0
qontract_reconcile_function_elapsed_seconds_since_bundle_commit_buck …
```
=> [APPSRE-2611] Tracking decorator

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> Sharding openshift-vault-secrets even more

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/quay_base.py, reconcile/quay_membership.py, reconcile/quay_permissions.py, reconcile/quay_repos.py, reconcile/queries.py, reconcile/test/test_quay_membership.py, reconcile/test/test_quay_repos.py, utils/quay_api.py
part of https://issues.redhat.com/browse/APPSRE-2764
this PR adds a new integration called `quay-permissions` which grants permissions for quay teams to quay repos.
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/12591
=> [quay-permissions] introduce new integration + quay refactor

dockerfiles/hack/run-integration.py
=> Fix handlers initialization

reconcile/terraform_resources.py, utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-1247
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/12785
=> [terraform-reousrces] allow attaching policy to s3 bucket

reconcile/ocm_clusters.py
fixes the issue displayed in the first commit in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/12857
=> ocm-clusters update from cluster_id to id

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> More memory and cpu for openshift-upgrade-watcher

dockerfiles/Dockerfile
=> revert package pinning in Dockerfile

dockerfiles/Dockerfile.test
related to https://issues.redhat.com/browse/APPSRE-2821
=> Dockerfile.test pull from centos/centos

reconcile/openshift_base.py
related to https://issues.redhat.com/browse/RHCLOUD-9974
we now validate ClowdApp resources deployed for Clowder.
=> [openshift-saas-deploy] validate ClowdApp resource

dockerfiles/Dockerfile
Reverts app-sre/qontract-reconcile#1243
checking, checking, 1, 2, 3
=> Revert "Dockerfile temp updated to fix skopeo install"

dockerfiles/Dockerfile
Reverts app-sre/qontract-reconcile#1244
=> Revert "Revert "Dockerfile temp updated to fix skopeo install""

reconcile/queries.py, reconcile/sql_query.py
part of APPSRE-2830
this PR will add an imagePullSecret to the job's pod spec to be able to pull private images.
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13182
replaces #1247
=> [sql-query] use image pull secret

dockerfiles/Dockerfile
Reverts app-sre/qontract-reconcile#1245
=> Revert "Revert "Revert "Dockerfile temp updated to fix skopeo install"""

reconcile/quay_mirror.py
=> Check public mirror only when mirroring from docker.io

utils/repo_owners.py
=> fix repo_owner ref

reconcile/gitlab_owners.py
=> Don't fail on missing report

utils/gql.py
=> Do not validate schema when querying for resources

reconcile/gitlab_owners.py
Let's make maintanance easier.
=> Adding comments all around

reconcile/gitlab_owners.py
=> gitlab-owners: approval comment fixes

reconcile/openshift_resources_base.py, utils/saasherder.py
=> prometheusrule add html_url annotation only if annotations exist

utils/terrascript_client.py
=> fix auth_token output name

reconcile/terraform_resources.py
just a small fix to cleanup the terraform configuration temp directories.
=> add cleanup to exit on error

reconcile/openshift_base.py
with this PR, we can call `ob.realize_data` without allowing resources to be deleted and without recycling pods.
this will be used a safety net for the upcoming terraform upgrade.
=> add option to call realize_data with safety nets

reconcile/gitlab_owners.py
Instead of exposing only the closest owners in the comment message,
let's add also the parent owners.
Before this patch:
```
[OWNERS] You will need a "/lgtm" from one person from each of these
groups:
* amoran, crarobin, jcueto, mciccone, mfreer, pcremin, raananda,
sclarkso
```
After this patch:
```
[OWNERS] You will need a "/lgtm" from at least one person from the
following group:
* amoran, crarobin, jcueto, mciccone, mfreer, pcremin, raananda,
sclarkso
Override approvers, from parent directories, are:
* asegundo, cbrookes, dffrench, jeder, jmelisba, kasingh, pamccart,
pbrookes, sfrancog, weil
Other relevant reviewers, from parent directories, are:
* mafriedm
```
=> Adding information about parent owners

utils/terrascript_client.py
related to https://issues.redhat.com/browse/APPSRE-2269
=> [terraform-resources] sqs provider get from dict

utils/terraform_client.py
=> fix terraform apply with plan file

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [sql-query] increase memory

reconcile/cli.py
=> remove cluster token in sentry

reconcile/cli.py
=> check crumb field

reconcile/cli.py
=> fix sentry change

dockerfiles/Dockerfile
Need to do this for the container-common package as well
=> Fix skopeo install

utils/gql.py
add resiliency against qontract-server
=> retry gql.query

reconcile/utils/sentry_client.py
this reduces the number of requests in the integration by about half.
=> [sentry-config] cache some responses

dockerfiles/Dockerfile
part of https://issues.redhat.com/browse/APPSRE-2692
=> [wip] switch FROM to qontract-base

dockerfiles/Dockerfile
fixes #1305 that was accidentally merged.
=> use correct version of qontract-base

reconcile/queries.py, reconcile/sql_query.py
Merge after https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13633
=> sql-query output encrypted

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py
openshift-saas-deploy-wrapper to 10 threads (default)
openshift-resources and openshift-vault-secrets to 10 shards with a bit less memory each.
=> adjust integrations

dockerfiles/Dockerfile
depends on https://github.com/app-sre/qontract-base/pull/3
=> Dockerfile upgrade qontract-base

dockerfiles/Dockerfile
For OpenShift giving write permission to group
=> APPSRE-2473 Fix permissions for plugin-cache

reconcile/sql_query.py
=> fix public_gpg_key format

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> Bump openshift-performance-parameters limits

reconcile/sql_query.py
=> fix sql-query delete

reconcile/cli.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-2882
this PR adds the logic to gate promotions based on the success published to a "channel" by a previous job.
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13877
=> gate production promotion based on post-deployment test results

reconcile/openshift_base.py
fixes https://github.com/app-sre/qontract-reconcile/pull/1279#discussion_r551238698
=> only allow to override enable_deletion if no errors were found

reconcile/utils/mr/__init__.py, reconcile/utils/saasherder.py
fixes #1327
sqs messages should be formatted properly (no set()).
fixes https://ci.ext.devshift.net/view/github-mirror/job/openshift-saas-deploy-saas-github-mirror-test-App-SRE-stage/27/console
=> [openshift-saas-deploy] fix sqs messages

reconcile/dashdotdb_dvo.py, reconcile/queries.py
Adjusts verify in prometheus request based on whether cluster.spec['private'] returns True or False
=> Dvo insecureskip

tools/app_interface_reporter.py
o fix casting typo in monthly reporter for dddb/dvo
o fix method call name (. vs _) in monthly reporter for dddb/dvo
=> Dddb dvo reporter

README.md, helm/README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/queries.py, reconcile/sendgrid_teammates.py, setup.py
More info here: https://issues.redhat.com/browse/APPSRE-2919
=> APPSRE-2919: SendGrid Integration

reconcile/utils/metrics.py
We need more resolution in the upper part as it is where data is getting concentrated.
=> Change bucket distribution for reconcile times

reconcile/ocm_clusters.py, reconcile/queries.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2917
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/14339
=> [ocm-clusters] add support for autoscaling and cluster update

reconcile/utils/ocm.py
related to https://issues.redhat.com/browse/APPSRE-2917
fixes #1351
=> [ocm-clusters] fix create cluster with autoscale

reconcile/utils/slack_api.py
=> fix slack integrations

setup.py
=> will this fix templates?

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml, reconcile/utils/oc.py
=> Instrument oc time to reconcile

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
=> Fix typo in env variable

reconcile/utils/gql.py
=> Add commit to running state

.pylintrc, reconcile/sql_query.py
=> [APPSRE-3017] Fix anomalous-backslash-in-string

reconcile/sql_query.py
by adding quotes when assigning the password.
this is an attempt to fix https://issues.redhat.com/browse/APPSRE-2982
=> [sql-query] support password special chars

reconcile/openshift_base.py, reconcile/utils/oc.py
=> create resource if not found

reconcile/utils/ocm.py
fixes https://coreos.slack.com/archives/CS0E65QCV/p1613385943423800
=> OCM client retry init

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> enable cloudwatch log for ocm-clusters and ocm-aws-infrastructure-access

tox.ini
-j0 tells pylint to detect and use all available cores
=> pylint parallel execution of checks

reconcile/saas_file_owners.py
related to https://issues.redhat.com/browse/APPSRE-3029
replaces #1385
we are seeing issues of incorrect comments on MRs, where the saas-file-owners integration believes it is changing saas files which it does not. I've investigated a bit and my current working assumption is that this happens when a merge was made to master but the build-master job has not yet completed or has completed and the data was not yet reloaded in the server. This causes a MR to believe it is the one changing the other saas file.
=> [saas-file-owners] check that diff is in changed paths

reconcile/utils/jenkins_api.py
fixes #1411
cc @violetyao @BumbleFeng
=> [App-interface-reporter] Get all builds fix

reconcile/cli.py, reconcile/jenkins_job_builder.py, reconcile/utils/jjb_client.py
https://issues.redhat.com/browse/APPSRE-2773
=> [jenkins-job-builder] print out job

reconcile/utils/jjb_client.py
=> fix jjb instance-name

reconcile/utils/promtool.py
This detail was removed in #1399
=> More detail in promtool errors

reconcile/jenkins_job_builder.py
=> [JJB] add generate xml file based on config name in print only mode

reconcile/quay_mirror.py, reconcile/queries.py, tools/qontract_cli.py
Example:
```
$ qontract-cli --config config.prod.toml get mirrors
REPO                                               UPSTREAM                                     PUBLIC
-------------------------------------------------  -------------------------------------------  --------
quay.io/REDACTED/REDACTED                          REDACTED                                     True
```
=> new command that displays quay mirrors

reconcile/utils/oc.py
=> Add exception details to the unreachable cluster

reconcile/queries.py, reconcile/utils/ocm.py
related to https://issues.redhat.com/browse/APPSRE-2865
this PR adds support to pass parameters for an addon installation.
=> [ocm-addons] add support for addon parameters

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
adding more memory to openshift-resources, adding more replicas to openshift-rolebindings and openshift-network-policies
=> add more resources for slow/ooming integrations

reconcile/ocm_machine_pools.py, reconcile/queries.py, reconcile/utils/ocm.py
change of labels and taints on the current machine-pool will only be applied to new Nodes.
https://github.com/openshift/machine-api-operator/blob/master/FAQ.md
=> [ocm-machine-pools] add taints and fix update

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
the integration is very noisy and we are trying to clean the channel from noise.
cc @rrati
=> [sentry-config] remove slack notifications

reconcile/utils/quay_api.py
=> better error msg

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
until we shard this integration...
=> [terraform-resources] increase resources

tools/qontract_cli.py
https://pypi.org/project/tabulate/
=> [qontract-cli] add support for markdown output

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [terraform-users] add memory

reconcile/gitlab_housekeeping.py
Jenkins issue is related to connecting between its master and slave node. 
Rebase is not related.
=> revert do not rebase saas-file-update

reconcile/ocm_aws_infrastructure_access.py, reconcile/utils/ocm.py, tools/qontract_cli.py
=> [ocm-aws-infrastructure-access] recreate failed role

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [dashdotdb-dvo] run once a day

tools/app_interface_reporter.py
Before threading: 
`Elapsed Time : 648.7196950912476 s `
Three runs after threading: 
```
Elapsed Time : 119.03765201568604 s
Elapsed Time : 122.96811819076538 s
Elapsed Time : 121.87917304039001 s
```
Example (`promotions` and `merge_activities` not null):
```
$schema: /app-sre/report-1.yml
labels:
app: quayio
name: quayio-2021-03-18
app:
$ref: /services/quayio/app.yml
date: '2021-03-18'
contentFormatVersion: 1.0.0
content: |
promotions:
quayio-utils:
- env: quay-stage
cluster: quays02ue1
namespace: quay
total: 3
success: 2
- env: quay-production
cluster: quayp05ue1
namespace: quay
total: 3
success: 2
quayio:
- env: quay-stage
cluster: quays02ue1
namespace: quay
total: 2
success: 2
- env: quay-production
cluster: quayp03ue1
namespace: quay
total: 4
success: 2
- env: quay-production …
```
=> [App Interface Reporter] Add threading

tools/app_interface_reporter.py
Jira: https://issues.redhat.com/browse/APPSRE-2954
=> [App Interface Reporter] Use cli threaded

README.md, reconcile/cli.py, reconcile/ecr_mirror.py, reconcile/queries.py
=> ECR Mirror

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> Adding ecr-mirror to the template

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> Bump ECR Mirror memory

reconcile/utils/terraform_client.py
=> Fixing tf-r rds replica probe

reconcile/utils/terraform_client.py
=> better tf-r error msg

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
=> tf-r code fix

reconcile/terraform_tgw_attachments.py, reconcile/terraform_vpc_peerings.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3150
this will add the provisioning of the vpc<->tgw attachment (requesting in the cluster's aws account and accepting in the calling aws account).
=> [terraform-tgw-attachments] add support for vpc attachment and accepter

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
part of https://issues.redhat.com/browse/APPSRE-3150
=> [terraform-tgw-attachments] add integration to chart

reconcile/utils/vault.py
https://sentry.devshift.net/sentry/app-interface-prod/issues/265699/?query=is%3Aunresolved
=> [vault] read_all refresh token

reconcile/utils/terrascript_client.py
=> [tf-r] enhance sqs with customer policy, fifo queue, dead-letter queue

reconcile/utils/saasherder.py
Support a new template parameter, `REPO_DIGEST`. If required in the template, we will query the registry data for the image based on `REGISTRY_IMG` and `IMAGE_TAG`, which must also be present (whether specified or generated). `REPO_DIGEST` will be set using the same form as produced by
`docker image inspect ${REGISTRY_IMG}:${IMAGE_TAG} --format '{{index .RepoDigests 0}}'`
(except the image need not be present locally)
That is, `${REGISTRY_IMG}@sha256${DIGEST}`, where `${DIGEST}` is a 64c
hex string. For example, given:
- `REGISTRY_IMG = "quay.io/app-sre/osd-metrics-exporter-registry"`
- `IMAGE_TAG` = "production-2cb14b0"`
...we will set:
- `REPO_DIGEST = "quay.io/app-sre/osd-metrics-exporter-registry@sha256:c94893c302cf5ef8aae0581f60bf59c3f65860aeefdd6046440bdc95f258c26e"`
APPSRE-3207
=> APPSRE-3207: Generate `REPO_DIGEST`

reconcile/utils/terrascript_client.py
=> fix sqs iam policy

reconcile/utils/terrascript_client.py
No change to current resources
=> [tf-r]fix kms key get ignored if start with arn

reconcile/openshift_base.py
clusterIP is an immutable field and cannot be modified
=> Allow Service clusterIP changes

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
Depends on: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17451
=> Add support for AWS ACM certificate creation

reconcile/utils/terrascript_client.py
revert domain/domain_name variable keys, disable domain_name from output
=> terrascript_client: update acm support code

reconcile/utils/terrascript_client.py
=> add action for quay-config-tool

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocp_release_mirror.py, reconcile/osd_mirrors_data_updater.py, reconcile/quay_base.py, reconcile/queries.py
Information and context: https://issues.redhat.com/browse/APPSRE-3226
=> Ocm quay mirror

reconcile/ocp_release_mirror.py
The tag in the releaseImage has been changed from a tag to a digest.
This has caused the mirroring of the ocp-release repo to use the digest
as the tags.
Instead of using the digest as the tag, we are changing the logic to
pick up the CIS name as the tag name for destination ocp release.
=> Use the CIS .metadata.name as the target tag

reconcile/quay_base.py, reconcile/quay_repos.py, reconcile/queries.py
This PR only addresses the repo management piece (not the content mirroring).
App-Interface counterpart:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17927
=> Support for downstream quay org repo management

tools/qontract_cli.py
in case smtp fails, no reason to not keep this information in app-interface-output in clear text (passwords are gpg encrypted).
part of https://issues.redhat.com/browse/APPSRE-3254
=> [qontract-cli] add get terraform-users-credentials command

reconcile/saas_file_owners.py
=> fix KeyError of use_channel_in_image_tag

reconcile/queries.py, reconcile/terraform_tgw_attachments.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3259
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/18205
=> [terraform-tgw-attachments] add support for security group rules

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [terraform-tgw-attachments] increase resources

reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3259
=> [terraform-tgw-attachments] SG rules all protocols all ports

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [kafka-clusters] increase resources

reconcile/kafka_clusters.py
=> fix KeyError of sa

reconcile/slack_usergroups.py
fixes https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/56851/console
=> [slack-usergroups] add github resiliency

reconcile/utils/saasherder.py
Make the error message include the image URI for debuggability.
=> Improve error output for REPO_DIGEST failure

reconcile/github_owners.py
https://coreos.slack.com/archives/CS0E65QCV/p1619324458455200
=> [github-owners] add resiliency

reconcile/sendgrid_teammates.py
https://coreos.slack.com/archives/CS0E65QCV/p1619335223455900
=> [sendgrid-teammates] add resiliency

reconcile/gitlab_owners.py
=> [gitlab-owners] use default branch

dockerfiles/Dockerfile
xref: https://github.com/app-sre/container-images/pull/11
xref: https://github.com/app-sre/container-images/pull/15
=> Upgrade qontract-reconcile-base

reconcile/prometheus_rules_tester.py
=> Better error message on missing rules file

dockerfiles/Dockerfile, reconcile/cli.py
related to https://issues.redhat.com/browse/APPSRE-3279
depends on https://github.com/app-sre/container-images/pull/16
=> upgrade terraform to 0.13.7

reconcile/queries.py, tools/qontract_cli.py
=> Add service-owners-for-rds-instance cli command

reconcile/openshift_resources_base.py, reconcile/utils/jinja2_ext.py
=> Add extension to jinja to raise errors

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-external.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
part of APPSRE-3261
this MR will (when promoted) deploy the internal integrations in the internal cluster(s).
=> add internal integrations

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
=> tweak APP_INTERFACE_PROJECT_ID for internal integrations

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
=> [gitlab-mr-sqs-consumer] remove slack output

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
=> add more memory for openshift-rolebindings internal

reconcile/utils/mr/auto_promoter.py
=> [openshift-saas-deploy] automerge when automatically promoting

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
=> Make jenkins-webhooks a StatefulSet

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml
=> indent volumeClaimTemplates

reconcile/utils/terrascript_client.py
=> grant s3 PutObjectAcl

reconcile/utils/terrascript_client.py
Reverts app-sre/qontract-reconcile#1567
cc @Piojo @rporres 
reverting this one as I thought it will override the issue reported in https://issues.redhat.com/browse/LOG-998.
It didn't, and I prefer not to change all Secrets right now.
=> Revert "[terraform-resources] add crendentials file like secret"

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py
=> Add comment to better understand a list usage

reconcile/quay_membership.py
Nobody cares about warning messages, only about failed PR checks
=> Quay membership must fail on missing users

reconcile/quay_membership.py
=> Always return something in quay_membership runners

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, reconcile/cli.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_upstream_jobs.py, reconcile/queries.py, reconcile/utils/jenkins_api.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-3321
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/19991
this PR adds a new integration - `openshift-saas-deploy-trigger-upstream-jobs` which triggers deployments based on successful builds of jobs defined in jenkins. this is to allow to link a build job with a stage deployment job for example.
=> [openshift-saas-deploy-trigger-upstream-jobs] introduce integration

reconcile/openshift_saas_deploy_trigger_upstream_jobs.py
copy-pasta
part of https://issues.redhat.com/browse/APPSRE-3321
=> [openshift-saas-deploy-trigger-upstream-jobs] fix update method

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
part of https://issues.redhat.com/browse/APPSRE-3321
=> bump resources for trigger integrations

reconcile/utils/saasherder.py
error shows in https://console-openshift-console.apps.appsrep05ue1.zqxk.p1.openshiftapps.com/k8s/ns/app-sre-pipelines/tekton.dev~v1beta1~PipelineRun/saas-grafana-app-sre-stage-202106031002/logs/openshift-saas-deploy
=> [saasherder] do not assume kind is present in a resource

reconcile/utils/gitlab_api.py
these methods are used from most of the gitlab integrations and often fail. let's add some retries.
https://issues.redhat.com/browse/ASIC-30
=> add retry to gitlab-api

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
https://issues.redhat.com/browse/ASIC-30
=> [terraform-resources] internal remove slack notifications

reconcile/utils/gql.py
this method fails and should be retried.
https://issues.redhat.com/browse/ASIC-30
=> [gql] init_from_config retry

reconcile/openshift_saas_deploy_trigger_base.py
This will help us building URLs from AlertManager
Part of https://issues.redhat.com/browse/APPSRE-3320
=> Add tkn cluster info to saas-deploy PipelineRun

reconcile/openshift_saas_deploy_trigger_base.py
Reverting as it got late and couldn't test it properly in prod. I don't
want to leave it around while other changes may pick it up.
This reverts commit fb0c01051b4af801e424b03fa6281b1977e3659f.
=> Revert "Add tkn cluster info to saas-deploy PipelineRun (#1614)"

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/openshift_saas_deploy_trigger_upstream_jobs.py, reconcile/utils/saasherder.py
=> [openshift-saas-deploy-trigger] refactor

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/openshift_saas_deploy_trigger_upstream_jobs.py, reconcile/utils/saasherder.py
Failing in PR checks
This reverts commit 62643fd4c7ef8606f42da64174fc45fced7c213a.
=> Revert "[openshift-saas-deploy-trigger] refactor (#1608)"

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/openshift_saas_deploy_trigger_upstream_jobs.py, reconcile/utils/saasherder.py
redo of #1608 with fixes (reverts #1624)
=> [openshift-saas-deploy-triggers] refactor #2

reconcile/utils/ocm.py
to avoid KeyError on `nodes` and to only add the autoscale/nodes if it is being updated
follow up on #1612
=> [ocm-clusters] another fix to update logic

reconcile/utils/saasherder.py
related to https://issues.redhat.com/browse/APPSRE-3331
this is an alternate approach for #1610 which was reverted in #1615 
cc @rporres
=> [saasherder] add handle for ResourceKeyExistsError

reconcile/openshift_base.py
=> [openshift_base] readd actions to FieldIsImmutableError

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/queries.py
The tekton implementation remove running pods associated with the
TaskRun, which is not acceptable for us
https://issues.redhat.com/browse/APPSRE-3352
=> Remove timeout via tekton

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/queries.py
This reverts commit b844357cc9d740c28974d94cdb08d2612a992f46.
PR checks are taking forever due to external issues and I will merge this next Monday
=> Revert "Remove timeout via tekton (#1629)"

reconcile/utils/saasherder.py
In case of build result return as {"_class": "hudson.model.FreeStyleBuild", "number": 43, "result": null}
https://coreos.slack.com/archives/CCRND57FW/p1623421769462000
=> fix build_result is None

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/queries.py
The tekton implementation remove running pods associated with the
TaskRun, which is not acceptable for us
https://issues.redhat.com/browse/APPSRE-3352
=> Remove timeout via tekton (#1629)

reconcile/test/test_utils_gpg.py, reconcile/utils/gpg.py
=> [utils/gpg] add tests

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
currently, whenever we want to add resources to an integration, we must make the changes in the repo and promote them to production.
with this PR, we can now override any resources that we want directly from the saas file.
=> allow providing resources values from saas file and not only through helm chart

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
relate to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/20844
=> allow override sleep_duration_secs

helm/qontract-reconcile/values-external.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
since we need to delete users from internal clusters as well
=> openshift-users run internally

.coveragerc
=> bump coverage threshold to 20.75

reconcile/slack_usergroups.py
we are seeing occasional timeouts reading from the PD api. let's retry.
=> [slack-usergroups] retry pagerduty

reconcile/ldap_users.py, reconcile/queries.py
some users have references to them (credential requests, sql queries). with this PR, the referencing files will also be deleted automatically as part of user deletion.
related to https://issues.redhat.com/browse/APPSRE-3327
=> [ldap-users] delete user references

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_additional_routers.py, reconcile/queries.py, reconcile/test/fixtures/ocm_additional_routers/state.yml, reconcile/test/test_ocm_additional_routers.py, reconcile/utils/ocm.py
https://issues.redhat.com/browse/APPSRE-3062
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/20784
=> introduce integration ocm-additional-router

reconcile/cli.py
=> fix ocm_additional_routers cli

reconcile/test/test_utils_gpg.py, reconcile/user_validator.py, reconcile/utils/gpg.py, reconcile/utils/terrascript_client.py
=> [user-validator] key singer should match with user org email

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> fix ocm-additional-routers template

reconcile/test/test_utils_gpg.py, reconcile/utils/gpg.py
=> temporary change mismatch of gpg singer to warning

reconcile/gitlab_integrations.py, reconcile/utils/gitlab_api.py
https://coreos.slack.com/archives/GGC2A0MS8/p1625127753151200?thread_ts=1625127621.150700&cid=GGC2A0MS8
=> [gitlab] add retries

reconcile/cli.py, reconcile/terraform_resources_wrapper.py
part of https://issues.redhat.com/browse/APPSRE-3424
adding extra labels support to this integration to be able to alert on failing aws account.
=> [terraform-resources-wrapper] add extra labels

reconcile/utils/ocm.py
as a result of https://issues.redhat.com/browse/MGDSTRM-3466, the base API url changed.
=> update KAS Fleet Manager base API url

reconcile/cluster_deployment_mapper.py, reconcile/utils/vault.py
=> rename base64 arg in vault write

reconcile/utils/ocm.py
endpoint has changed (still finding out where).
slack thread: https://coreos.slack.com/archives/CCRND57FW/p1626333748237800
=> update kafka service accounts endpoint

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
as jobs are currently not getting deleted from centos ci
=> add jenkins-job-cleaner to internal integrations

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/utils/jenkins_api.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-3484
this PR helps the trigger integrations (specifically upstream-jobs) to handle an unreachable instance and still trigger deployments based on jobs from reachable instances.
=> [openshift-saas-deploy-trigger] error handle

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
Reverts app-sre/qontract-reconcile#1701
=> Revert "do not use jump host in internal openshift integrations"

reconcile/utils/saasherder.py
=> [openshift-saas-deploy] default to compare (true) resources fix

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml, reconcile/utils/oc.py
=> add USE_NATIVE_CLIENT to template

reconcile/queries.py
=> fix disable openshift-serviceaccount-tokens

reconcile/dashdotdb_dvo.py
Update the DVO DashDotDB integration to work with tokens and to pull metric names from the prometheus instances instead of using a fixed set of names.
We need to pull the metric names because the new DVO is based on kube-linter and we don't want to try to keep up to date with the checks in kube-linter that are running as it evolves.
This is related to:
https://issues.redhat.com/browse/APPSRE-2897
https://issues.redhat.com/browse/APPSRE-2910
=> Dvo dddb updates

reconcile/dashdotdb_cso.py, reconcile/utils/oc.py, reconcile/utils/unleash.py
Allow using unleash to control which client is used by specific clusters
=> Selective client

reconcile/utils/oc.py
=> Set the number of retries to 5 for the native client to try to

.coveragerc
=> bump code coverage 20.75 -> 23.25

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> slow down ocm-aws-infrastructure-access

tools/app_interface_reporter.py
fix due to https://github.com/app-sre/dashdotdb/pull/41
=> fix app-interface-reporter

reconcile/openshift_rolebindings.py
=> fix rolebindings apigroup in V3 cluster

reconcile/gitlab_housekeeping.py, reconcile/queries.py, reconcile/test/test_gitlab_housekeeping.py
Related MR:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/22859
Jira Ticket:
https://issues.redhat.com/browse/APPSRE-3358
=> Support to cancel pending gitlab pipelines

reconcile/queries.py
Depends on
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/23171
=> Adapt to schema changes

reconcile/gitlab_permissions.py, reconcile/ocm_groups.py, reconcile/openshift_groups.py, reconcile/openshift_users.py, reconcile/queries.py, reconcile/utils/saasherder.py
https://github.com/app-sre/qontract-reconcile/pull/1593#discussion_r642454327
=> refactor sublist to itertools chain

reconcile/kafka_clusters.py, reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_limitranges.py, reconcile/openshift_network_policies.py, reconcile/openshift_resourcequotas.py, reconcile/openshift_resources_base.py, reconcile/openshift_rolebindings.py, reconcile/openshift_saas_deploy.py, reconcile/openshift_serviceaccount_tokens.py, reconcile/terraform_resources.py
part of https://issues.redhat.com/browse/APPSRE-3416
=> refactor openshift_base.realize_data to run with parallelism

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, reconcile/cli.py, reconcile/ldap_users.py, reconcile/utils/ldap_client.py
part of https://issues.redhat.com/browse/APPSRE-3547
instead of searching user by users, we get all users and find missing ones in memory.
=> [ldap-users] remove threading

reconcile/quay_repos.py
current logging: `['create_repo', OrgKey(instance='quay.io', org_name='app-sre'), 'repo-name']`
desired logging: `['create_repo', 'quay.io', 'app-sre', 'managed-scripts']`
=> [quay-repos] properly log OrgKey

reconcile/utils/slack_api.py
related to https://issues.redhat.com/browse/APPSRE-3566
=> [slack_api] consider retry-after header on ratelimit

reconcile/utils/saasherder.py
=> fix auth_server

setup.py
=> bump version to 0.3.0

setup.py
=> upgrade requests to remove warning

reconcile/quay_mirror.py, setup.py
This reverts commit bae493e50f8ac3fd6eaf762366798d5cbe8aa836.
It is currently failing to fetch tags.
=> Revert "Add a response cache to quay_mirror (#1691)"

reconcile/openshift_saas_deploy_trigger_cleaner.py
This integration cleans up old PipelineRuns but keeps the newest `minimum` amount of runs
and additionally all runs that are younger than `days` days.
There was a bug sorting the PipelineRuns in the wrong order (from oldest to newest) which then resulted in the `minimum`cut-off producing the `minimum` OLDEST PipelineRuns to be kept.
There was another bug in the `within_retention_days` function which compared date differences and not hours passed (the actual timedelta), which made python say that everything from yesterday was older than 1 day even though it was just, say, 5 hours old.
Co-authored-by: Mayank Shah <mashah@redhat.com>
Co-authored-by: Nico Schieder <nschiede@redhat.com>
Signed-off-by: Josh Gwosdz <jgwosdz@redhat.com>
=> fix openshift_saas_deploy_trigger_cleaner PipelineRun sort order

reconcile/dashdotdb_base.py, reconcile/dashdotdb_cso.py, reconcile/dashdotdb_dvo.py, reconcile/dashdotdb_slo.py
This is dependent upon 
https://github.com/app-sre/dashdotdb/pull/46
=> Implement tokens for CSO and SLO DashDotDB types

reconcile/utils/jump_host.py, reconcile/utils/oc.py
openshift-saas-deploy-wrapper run multiple OC_Map instances, and they all using the same ssh tunnel for the native client.
When one OC_Map starts to clean up, it will stop the tunnel and the rest instances will fail to connect.
This PR allows each ocm_map to have its own local ports for the tunnels, so it will clean up its own tunnels. Meanwhile, JumpHostSSH will store all the ports globally and generate a unique one when required.
=> use random local port

reconcile/utils/oc.py
fix https://github.com/app-sre/qontract-reconcile/pull/1776
=> fix cluster jumpHost could be None

reconcile/utils/openshift_resource.py
=> allow delete key/value in matchLabels

tekton/README.md, tekton/qontract-reconcile.yaml
this will help us explain our CD process using OpenShift Pipelines
=> add tekton example

reconcile/requests_sender.py, reconcile/test/test_requests_sender.py, reconcile/test/test_utils_gpg.py, reconcile/user_validator.py, reconcile/utils/gpg.py
=> gpg_encrypt with recipient form imported key

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
follows up on:
- #1793
- #1795
=> [ocm-upgrade-scheduler] run in new format

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> [ocm-upgrade-scheduler] add state to execution

reconcile/test/test_utils_ocm.py, reconcile/utils/ocm.py
=> simplify version blocked function + tests

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
retry https://github.com/app-sre/qontract-reconcile/pull/1701
=> do not use jump host in internal openshift integrations

tools/qontract_cli.py, tools/test/test_sre_checkpoints.py
part of https://issues.redhat.com/browse/APPSRE-3572
this PR adds an option to sort (or not) the output of `get` commands.
=> [qontract-cli] sort output

reconcile/gitlab_housekeeping.py
1. use utcnow to get the date time as the same as gitlab.
2. get project for source_project_id which is actually the fork repo.
=> fix gitlab-housekeeping

reconcile/quay_mirror.py
To be merged after we have verified the effectiveness of the caching
strategy.
=> Re-enable deep-syncs

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3669
in order to be able to provision iam roles.
this is required for https://issues.redhat.com/browse/APPSRE-3645.
=> [terraform-resources] add support for iam role

reconcile/openshift_base.py
to allow updating the type of (pull) secrets
=> add support for immutable fields in Secrets

reconcile/utils/terrascript_client.py
Reverts app-sre/qontract-reconcile#1820
=> Revert "get_dependencies() refactor"

helm/qontract-reconcile/values-external.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/openshift_namespace_labels.py, reconcile/queries.py, reconcile/test/test_openshift_namespace_labels.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py
I believe this could be much simpler and to the point, but i don't see how for now.
Creating the PR before diving into other potential changes, to get reviews.
I'd be happy to get feedback and revisit as needed.
=> APPSRE-3522 openshift namespace labels integration

reconcile/terraform_vpc_peerings.py
a little something to make #1780 easier to review
=> [terraform-vpc-peerings] refactor imports

tools/qontract_cli.py
=> [qontract-cli] get clusters-egress-ips sort ips

reconcile/utils/terrascript_client.py
Reverts app-sre/qontract-reconcile#1825
=> Revert "get_dependencies() refactor (v2)"

reconcile/openshift_base.py
=>  [openshift-saas-deploy-trigger] annotate and fix call to create

tools/qontract_cli.py
=> fix broken qontract-cli query

.pylintrc, reconcile/email_sender.py, reconcile/gitlab_owners.py, reconcile/ocp_release_mirror.py, reconcile/slack_usergroups.py, reconcile/test/test_utils_oc_native.py, reconcile/utils/mr/__init__.py, reconcile/utils/mr/cluster_service_install_config.py, reconcile/utils/quay_api.py, reconcile/utils/repo_owners.py, reconcile/utils/saasherder.py, reconcile/utils/smtp_client.py, reconcile/utils/terrascript_client.py, reconcile/utils/vault.py, tools/app_interface_reporter.py
Re-enable the checks I disabled yesterday after the upgrade to pylint
2.11. And then fix a few more easy checks.
=> Re-enable some pylint checks

reconcile/cli.py
I pushed some test changes by mistake
=> Recover old desired OC version

tools/qontract_cli.py
new qontract-cli command to display cluster upgrade policies as well as available upgrades and their soaking time for each workload
```
$ qontract-cli --config $CONFIG_TOML cluster-upgrade-policies
CLUSTER            VERSION     CHANNEL    SCHEDULE        SOAK_DAYS  WORKLOAD    SOAKING_UPGRADES
-----------------  ----------  ---------  ------------  -----------  ----------  ----------------------------------------------------------------------
app-sre-prod-01    4.9.0-rc.0  candidate  0 8 * * 1-5             7  appsre      4.9.0-rc.1 (6.14)
app-sre-prod-03    4.9.0-rc.0  candidate  0 3 * * 1-5             3  crda        4.9.0-rc.1 (3.27)
app-sre-prod-04    4.7.21      stable     0 14 * * 1-5           18  ocm         4.7.22 (0), 4.7.23 (0)
app-sre-stage-01   4.9.0-rc.1  candidate  0 12 * …
```
=> APPSRE-3762 display cluster upgrade policies and soaking upgrades

reconcile/terraform_resources.py
=> [terraform-resources] query for cidr_block

reconcile/test/test_utils_state.py, reconcile/utils/state.py, requirements-test.txt, setup.cfg, tools/qontract_cli.py, tools/test/test_qontract_cli.py
JIRA: [APPSRE-3703](https://issues.redhat.com/browse/APPSRE-3703)
This adds two more development dependencies, [python-mock](https://pypi.org/project/pytest-mock/) and [moto](https://pypi.org/project/moto/).
=> Fix ls method in State util class

reconcile/test/test_utils_state.py, reconcile/utils/state.py
JIRA: https://issues.redhat.com/browse/APPSRE-3779
Docs on AWS S3: 
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/ListingKeysUsingAPIs.html
Docs in boto3:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2
=> Fix list more than 1000 keys

reconcile/utils/terraform_client.py
=> 'after' key can be missing in tf output_change

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/aws_iam_password_reset.py, reconcile/cli.py, reconcile/queries.py, reconcile/utils/aws_api.py
part of https://issues.redhat.com/browse/APPSRE-3885
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/26571
this PR adds support to self-service aws password reset. this integration will delete the user's login profile, which will be re-created by `terraform-users` (and the password will be updated in app-interface-output).
=> [aws-iam-password-reset] introduce new integration

reconcile/utils/ocm.py
response is 200 but there are no items.
=> [ocm-aws-infrastructure-access] get items

.coveragerc
=> Bump test coverage

reconcile/openshift_serviceaccount_tokens.py
=> fix add_desired to skipped cluster

dockerfiles/Dockerfile
Use a base image that actually builds this stuff.
=> Try Python 3.9 builds again

grafana-dashboards/grafana-dashboard-integrations.configmap.yaml
Adding the qr dashboard to qr repo. [APPSRE-3936](https://issues.redhat.com/browse/APPSRE-3936)
Signed-off-by: Suzana Nesic <snesic@redhat.com>
=> adding qr dashboard to qr repo

reconcile/openshift_namespace_labels.py
=> ignore deleted namesapce

reconcile/test/test_utils_github_api.py, reconcile/test/test_utils_gitlab_api.py, reconcile/utils/github_api.py, reconcile/utils/gitlab_api.py
=> Add default timeout values for gitlab/github api clients

setup.py, tox.ini
=> Remove py36 tests

e2e_tests/test_base.py, reconcile/gcr_mirror.py, reconcile/github_org.py, reconcile/jenkins_job_builder.py, reconcile/jenkins_plugins.py, reconcile/jenkins_roles.py, reconcile/openshift_network_policies.py, reconcile/openshift_resources_base.py, reconcile/quay_mirror.py, reconcile/quay_permissions.py, reconcile/queries.py, reconcile/terraform_resources.py
part of https://issues.redhat.com/browse/APPSRE-4068
follows up on #1994
=> More automation token version

reconcile/openshift_resources_base.py
so we don't see this again and again
=> log debug of override kind

reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-4068
=> add fields for image authentication is saasherder

reconcile/openshift_tekton_resources.py
=> The no saas files to process message is on debug

reconcile/test/fixtures/saasherder_populate_desired/saas_remote_openshift_template.yaml
This fixture is missing the required `app` parameter. I fix it bc is breaking a test an ongoing work
=> Fix saasherder tests fixture

reconcile/test/test_aggregated_list.py
pylint 2.12.x detectes more issues which are fixed in this PR
=> fix pylint 2.12.x issues

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
=> run status-page-components integration

reconcile/utils/elasticsearch_exceptions.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-4123
replace of https://github.com/app-sre/qontract-reconcile/pull/2017
=> remove validate_elasticsearch_version

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3925
depends on https://github.com/app-sre/qontract-schemas/pull/24
=> add tf provider secrets-manager

reconcile/utils/terrascript_client.py
slack thread: https://coreos.slack.com/archives/C02HE93TAFN/p1638558312486200
=> [terraform-resources] alb add vpc cidr block to output secret

setup.py
follows up on:
- https://github.com/app-sre/sretoolbox/pull/65
- https://github.com/app-sre/sretoolbox/pull/66
=> bump sretoolbox to 1.2.2

reconcile/utils/terraform_client.py
=> [terraform-users] fix return value

reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-4171
we want to validate images being used before deploying them for ClowdApp resources.
=> [saasherder] add support to collect images from ClowdApp

reconcile/saas_file_owners.py
=> [saas-file-owners] allow owners to enable/disable targets

reconcile/utils/saasherder.py
this will fail for ClowdJonInvocations:
https://github.com/project-koku/koku/blob/827c0838d7c02f92a05bf66297f4d560be72bdde/deploy/koku-cji.yaml#L34-L41
=> [saasherder] collect images suppress TypeError

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
Related to APPSRE-3695
Requires https://github.com/app-sre/qontract-schemas/pull/31
=> add idle_timeout support for AWS ALB

README.md
=> add statuspage-components to the list of integrations

reconcile/kafka_clusters.py, reconcile/utils/ocm.py
https://issues.redhat.com/browse/ASIC-146
=> [kafka-clusters] fix api case

reconcile/queries.py, reconcile/saas_file_owners.py
part of https://issues.redhat.com/browse/APPSRE-4182
this will allow MRs changing deployResources to be self-serviced.
=> [saas-file-owners] make deployResources self-service

dockerfiles/Dockerfile, reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3925
depens on https://github.com/app-sre/qontract-schemas/pull/34
=> add terrafrom asg

reconcile/aws_support_cases_sos.py
the integration currently does not detect the keys in the existing list.
it was very hard to debug in the list comprehension, so switched it to for loops.
=> [aws-support-cases-sos] fix and switch from list comprehension to for loops

Makefile, helm/qontract-reconcile/values-fedramp.yaml, openshift/qontract-reconcile-fedramp.yaml
https://rh-osd-gitlab.redhat-osd.local/app-sre/app-interface/-/tree/master/data/integrations
```
$ qontract-cli get integrations
NAME                        DESCRIPTION
--------------------------  --------------------------------------------------------------
openshift-namespace-labels  Manages OpenShift Namespace Labels
openshift-namespaces        Manages OpenShift Namespaces
openshift-network-policies  Manage Network Policies
openshift-resources         Manages OpenShift resources
openshift-saas-deploy       Manage OpenShift resources defined in Saas files (SaasHerder).
openshift-vault-secrets     Deletion of users from OpenShift clusters
service-dependencies        Validate that a service has all dependecies defined
terraform-aws-route53       Provisions AWS Route53 DNS zones and …
```
=> add fedramp values file

reconcile/openshift_network_policies.py, reconcile/openshift_resources_base.py, reconcile/queries.py, reconcile/terraform_resources.py, reconcile/utils/oc.py
part of https://issues.redhat.com/browse/APPSRE-3991
depends on https://github.com/app-sre/qontract-schemas/pull/42
=> support insecure-skip-tls-verify

reconcile/utils/oc.py
solves https://coreos.slack.com/archives/CS0E65QCV/p1640761622277700
=> [oc] add retry to get_items

reconcile/test/test_openshift_tekton_resources.py
We're standarizing our test framework.
part of [APPSRE-4190](https://issues.redhat.com/browse/APPSRE-4190)
=> Move openshift-tekton-resources tests to pytest

reconcile/openshift_tekton_resources.py
We have actually overriden a large amount of files. It is time to
avoid problems once and for all.
=> Larger defaults for tekton tasks

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/queries.py, reconcile/test/fixtures/openshift_tekton_resources/provider1.json, reconcile/test/fixtures/openshift_tekton_resources/provider2-with-resources.json, reconcile/test/fixtures/openshift_tekton_resources/provider4-with-task-duplicates.json, reconcile/test/fixtures/openshift_tekton_resources/provider5-with-unknown-task.json, reconcile/test/fixtures/queries/pipelines_providers_all_defaults.json, reconcile/test/fixtures/queries/pipelines_providers_mixed.json, reconcile/test/fixtures/queries/pipelines_providers_no_defaults.json, reconcile/test/test_openshift_tekton_resources.py, reconcile/test/test_queries.py
covers [APPSRE-4165](https://issues.redhat.com/browse/APPSRE-4165)
related schema changes: https://github.com/app-sre/qontract-schemas/pull/44
=> Add support for pipelines providers defaults

Makefile
Add CONTAINER_ENGINE variable, with docker as default
to not break existing usages
=> Add CONTAINER_ENGINE variable

helm/qontract-reconcile/values-fedramp.yaml, openshift/qontract-reconcile-fedramp.yaml
https://issues.redhat.com/browse/APPSRE-4277
=> add integrations to fedramp

helm/qontract-reconcile/values-fedramp.yaml, openshift/qontract-reconcile-fedramp.yaml
=> update integrations in fedramp

reconcile/queries.py
=> fix aws accounts query with uid

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
=> add slack logs for ocm integrations

reconcile/openshift_saas_deploy.py
Since pipeline names have changed once they are created from
openshift-tekton-resources the link now was using a no longer existing
pipeline name.
This was missing in #1998, #2023, #2080 and #2094
=> Fix tekton console link in openshift-saas-deploy

reconcile/jenkins_webhooks_cleaner.py
related to https://issues.redhat.com/browse/APPSRE-4302
it was found that some webhooks were duplicated. this PR will remove duplicates.
=> [jenkins-webhooks-cleaner] remove duplicate items

reconcile/utils/terrascript_client.py
part of [APPSRE-4219](https://issues.redhat.com/browse/APPSRE-4219)
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#advanced_security_options
schema changes: https://github.com/app-sre/qontract-schemas/pull/56
=> Added AWS ES advanced security options support

reconcile/openshift_groups.py, reconcile/openshift_rolebindings.py, reconcile/test/fixtures/openshift_resource/expiration_date_check.yml, reconcile/test/fixtures/openshift_resource/invalid_expiration_date.yml, reconcile/test/test_openshift_resource.py, reconcile/utils/openshift_resource.py
Handling temp roles in app-interface by implementing an expirationDate field. Work for [APPSRE-2284](https://issues.redhat.com/browse/APPSRE-2284)
Signed-off-by: Suzana Nesic <snesic@redhat.com>
=> enabling expiration to temp roles in app-interface

reconcile/utils/slack_api.py
Remove code part that would call join_channel
=> Remove join channel

helm/qontract-reconcile/values-fedramp.yaml, openshift/qontract-reconcile-fedramp.yaml
This MR deploys gitlab-housekeeping integration for fedramp.
=> Enable gitlab housekeeping in fedramp

helm/qontract-reconcile/values-fedramp.yaml, openshift/qontract-reconcile-fedramp.yaml
these certificates are for RH internal, i don't think they apply for FR.
also adding slack logs
cc @TGPSKI 
https://issues.redhat.com/browse/APPSRE-4276
=> add slack logs to fedramp and remove internal certificates

reconcile/jira_watcher.py, reconcile/slack_base.py, reconcile/test/test_utils_slack_api.py, reconcile/unleash_watcher.py, reconcile/utils/slack_api.py
Do join channels only if an error up joining slack channels is received
=> Only join on error

reconcile/utils/sentry_client.py, reconcile/utils/terrascript_client.py
https://service.pages.redhat.com/dev-guidelines/docs/appsre/python-style-guide/#naming-conventions
=> rename functions ending with underscore

reconcile/gitlab_fork_compliance.py
when a user forks a project in gitlab, they may choose the visibility of their fork (public, internal, private).
for the fork compliance check, we don't really mind, as long as the bot has access to the fork.
this PR updates the initiation of the source (fork) to be inside the bot access check. this contributes to returning a sane message to the user instead of a stack trace in the job logs:
```
File "/usr/local/lib/python3.9/site-packages/gitlab/exceptions.py", line 259, in wrapped_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/gitlab/mixins.py", line 50, in get
server_data = self.gitlab.http_get(path, **kwargs)
File "/usr/local/lib/python3.9/site-packages/gitlab/__init__.py", line 588, in http_get
result = self.http_request( …
```
=> [gitlab-fork-compliance] check fork as part of bot access

setup.py
Reverts app-sre/qontract-reconcile#2146
https://github.com/openshift/openshift-restclient-python/issues/425 is closed
=> Revert "pin openshift version to 0.12"

reconcile/cli.py
=> fix github-repo-permissions-validator cli call

tools/qontract_cli.py
followup fix of https://github.com/app-sre/qontract-reconcile/pull/2000
=> fix clusters_egress_ips

reconcile/utils/constants.py, reconcile/utils/mr/app_interface_reporter.py, reconcile/utils/mr/aws_access.py, reconcile/utils/mr/notificator.py
Store the PROJ_ROOT constant that is recalculated the same way in many
places.  Other constants will follow in the future.
=> Start a module for constants
