app-sre/qontract-reconcile

reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
remove_none_value method has been changed to work with a None value input. This could happen when a new saas target is deployed and there is no current configuration stored in the State
=> Fix remove_none_values method

reconcile/cli.py, reconcile/terraform_aws_route53.py, reconcile/terraform_resources.py, reconcile/terraform_resources_wrapper.py, reconcile/terraform_tgw_attachments.py, reconcile/terraform_users.py, reconcile/terraform_vpc_peerings.py, reconcile/utils/git.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-4208
this will prevent terraform printed configuration files from being leaked in an accidental commit
=> [terraform-client] print only to file that is not in a git repository

reconcile/openshift_base.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py
related to https://issues.redhat.com/browse/ASIC-145
during the incident, we noticed that pods were being picked up by the newly applied statefulset without being restarted, including picking up an updated storage size.
this needs to be validated through docs or an experiment.
=> [openshift-base] statefulset pvc resize

reconcile/openshift_base.py, reconcile/openshift_resources_base.py, reconcile/test/test_openshift_base.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py, reconcile/utils/openshift_resource.py, reconcile/utils/saasherder.py
This change introduces a field `clusterAdmin` in a `namespace-1.yml` file similar to how `saas` files use this flag. When it is set to true, the cluster-admin token of a cluster is used to reconcile resources.
~~This change needs more testing, i opened this MR to get a feeling what people think of the general approach~~
Two things needed touching to implement this change: the OC_Map and the ResourceInventory initialisation and usage
Instead of tracking all clusters in one dict and having either all of them authenticated with dedicated-admin or cluster-admin, this change introduces the ability for clusters being present in a cluster map both ways at the same time. This is mostly relevant (and necessary) for `OC_Map` initialisation based on a set of namespaces, where one namespace requires …
=> allow namespaces to use cluster-admin token for openshift resource mgmt

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
Be able to create SNS notification through App Interface for existing topic and bucket.
1. Change the query to get the event_notification information;
2. Add it in the terraform-resources integration to loop through event_notification and create SNS topic;
Local run was able to create it.
=> Create SNS event notification for S3 

reconcile/gitlab_labeler.py
As the integration is always running with dry_run mode, we should apply the changes even with the flag on true on the current implementation.
=> Fix Gitlab-labeler integration

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
schema changes: https://github.com/app-sre/qontract-schemas/pull/40
JIRA: APPSRE-3695
This change supports per-path ALB targets. Sample config:
```
provider: alb
...
targets:
- name: py2
openshift_service: py2-svc
default: true
- name: py3
openshift_service: py3-svc
rules:
- condition:
path: /v2/auth*
methods: read
action:
- target: py2
weight: 100
- condition:
path: /v2*
methods: read
action:
- target: py3
weight: 100
- target: py2
weight: 0
```
=> Add per-path targets for ALB

reconcile/gitlab_labeler.py, reconcile/test/fixtures/apps/parentapp.json, reconcile/test/test_gitlab_labeler.py
* correctly add onboarding status on parent apps without "child" updates on the MR
* Only add tenant information if path is under data/services
=> Improve gitlab-labeler

reconcile/test/test_status_page_components.py
We're standarizing our test framework.
part of APPSRE-4190
=> move statuspage-component tests to pytest

reconcile/utils/terrascript_client.py
It appears AWS is requiring this stickiness parameter even though the terraform docs mark it as optional
Fixes
```
[terraform-resources-wrapper] error: b'\nError: Error modifying LB Listener Rule: ValidationError: Target group stickiness duration must be between 1 and 604800 seconds\n\tstatus code: 400, request id: 676c4a12-20c3-430d-b254-a95f3dd20564\n\n  on config.tf.json line 2487, in resource.aws_lb_listener_rule.foo-alb01-rule-01:\n2487:       },\n\n\n'
```
=> add stickiness config for forwarding rule

reconcile/utils/gitlab_api.py
Adding parameter in get_app_sre_group_users method that will allow all members to be listed recursively, fixing the pagination issue that caps the list at 20. 
Signed-off-by: Suzana Nesic <snesic@redhat.com>
=> getting all members from appsre recursively

reconcile/ocm_clusters.py, reconcile/queries.py, reconcile/utils/ocm.py
Enable network type selection clusters
Linked to https://github.com/app-sre/qontract-schemas/pull/52
The default is the current only value: `OpenshiftSDN`
=> APPSRE-4229 ocm-clusters network type

reconcile/utils/terrascript_client.py
even if the account has integrations disabled (avoid KeyError)
=> terrascript client make get partition succeed

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, reconcile/blackbox_exporter_endpoint_monitoring.py, reconcile/cli.py, reconcile/queries.py, reconcile/test/fixtures/blackbox_exporter_endpoint_monitoring/test_endpoint.yaml, reconcile/test/fixtures/blackbox_exporter_endpoint_monitoring/test_invalid_endpoints.yaml, reconcile/test/fixtures/blackbox_exporter_endpoint_monitoring/test_multiple_providers_per_endpoint.yaml, reconcile/test/fixtures/blackbox_exporter_endpoint_monitoring/test_probe_building.yaml, reconcile/test/test_blackbox_exporter_endpoint_monitoring.py, reconcile/utils/vaultsecretref.py, setup.cfg, setup.py
this new integration `blackbox-exporter-endpoint-monitoring` implements the blackbox-exporter part (phase 1) of service
endpoint monitoring as defined in this [design doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/service-endpoint-monitoring.md)
Schema change: https://github.com/app-sre/qontract-schemas/pull/45
Part of: https://issues.redhat.com/browse/APPSRE-4209
With this change, tenants can declare blackbox-exporter backed `EndpointMonitoringProviders` and attach app endpoints to it to setup basic closed box monitoring. This concept of `EndpointMonitoringProviders` will be enhanced in a followup PR where Catchpoint probes are going to be implemented as an additional provider (phase 2 of design doc).
* use `Probe` instead of …
=> [endpoint monitoring] integration backed by blackbox-exporter

reconcile/ocm_aws_infrastructure_access.py, reconcile/utils/ocm.py
related to:
- https://issues.redhat.com/browse/SDA-4422
- https://issues.redhat.com/browse/OHSS-9286
some role grants are "stuck" in Deleting. if we try to delete those, we get a 5xx error from OCM.
this PR updates the behavior to avoid deleting role grants in the "deleting" state.
the implementation is to remove any "Deleting" role grants from the current state, preventing them from being attempted to be deleted. because we remove these role grants from the current state, they will be attempted to be added because they may be in the desired state. we prevent that by removing any role grants in "Deleting" from the role grants to be added.
=> [ocm-aws-infrastructure-access] do not delete deleting role grants

reconcile/jenkins_job_builder.py, reconcile/saas_file_validator.py, reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
adding repos to a `codeComponent` section gives us some benefits:
- the repo is being backed up automatically by git-keeper.
- any github invitations to that repo will be accepted automatically.
it's worth while to validate that all repos from saas files (`.resourceTemplates[].url`) are in `codeComponents` section.
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/32054
=> [saas-file-validator] validate saas file repos are in codeComponents

reconcile/utils/terrascript_client.py
https://issues.redhat.com/browse/ASIC-168
if an integration is disabled, we don't need warnings to constantly appear.
=> terraform logging debug for disabled integrations

Makefile, README.md, dockerfiles/hack/run-integration.py
**Motivation**
The reconcile loop can be triggered in local dev env, however, it requires proper binaries to be in `PATH`. I see 2 ways to automate this issue away:
1. Run reconcile dev loop inside a container
2. Add make target which downloads binaries to repo local `./bin` directory and add an .env script to source those bins as prefix to PATH
This PR targets the first approach.
**Proposed Changes**
- added a make target to run reconcile loop inside a docker container
- added documentation about that new make target
- set 3.9.x as compatibility target (same as in `setup.py`)
=> Container integration loop for local development

dockerfiles/hack/run-integration.py
**Motivation**
When I started using the DRY_RUN environment variable, I assumed that it just needs to be declared in order to activate dry run mode, like `DRY_RUN=1`. However, the script exited with a command error. 
**Change**
This PR validates that a proper option is passed to the script. Further, an explanation is printed if a bad option is passed.
=> enhanced dry_run parsing

reconcile/terraform_resources.py
depends on https://github.com/app-sre/qontract-schemas/pull/68
the intention is that when terraform-resources is disabled per cluster, all terraform resources will still be created, but their output resources will not be reconciled on the disabled cluster.
=> [terraform-resources] disable per cluster

reconcile/openshift_saas_deploy.py, reconcile/test/fixtures/saasherder/saas.gql.yml, reconcile/test/fixtures/saasherder/saas_post_deploy.state.json, reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
This PR solves a problem with the current saas file deployments based on config_changes. 
```
DeployTarget ------[promotes]---------> TestTarget
- parent_config_hash
```
When a automatic promotion happens, a hash from the DeployTarget configuration is added to TestTarget  in an automated MR (AutoPromote). This MR validation uses `saasherder.validate_promotions` method to ensure the parent_config_hash set in the promotion matches the **current** DeployTarget configuration in app-interface. 
This is causing issues in pipelines that could run in parallel because only the last promotion is valid (configuration is matched with app-interface state).
To solve this, the validation is changed to match the hash in the success state of DeployTarget instead of app-interface. The state is stored for …
=> Update validate_promotions to use the state instead of graphql

reconcile/jira_watcher.py, reconcile/slack_base.py, reconcile/test/test_utils_slack_api.py, reconcile/unleash_watcher.py, reconcile/utils/slack_api.py
Join Slack channels, whenever required and possible.
Join only when initializing instances of SlackApi.
Related ticket: [APPSRE-3988](https://issues.redhat.com/browse/APPSRE-3988)
=> Join slack channels

reconcile/github_org.py, reconcile/github_owners.py, reconcile/jenkins_roles.py, reconcile/openshift_clusterrolebindings.py, reconcile/quay_membership.py, reconcile/sentry_config.py, reconcile/test/fixtures/github_org/desired_state_simple.yml, reconcile/test/fixtures/quay_membership/desired_state_simple.yml
follows up on:
- #2125
- #2033
this PR adds support for role expiration for all remaining integrations which are calculating their desired state based on roles.
=> add support for role expiration to all integrations

reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-4364
in case we lose job history, or if the state becomes corrupt due to changing the upstream back and forth between ci instances, we currently fail to trigger new deployments.
this PR solves it essentially by checking if the last build number is different from the stored value in the state, instead of checking if the last build number is larger from what is stored in the state.
=> [openshift-saas-deploy-trigger-upstream-jobs] handle loss of job history

setup.py
=> pin openshift version to 0.12

reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-4366
it makes less sense to specify a commit sha as `ref` and using `upstream`, because even if we trigger a deployment after each build, the deployment will change nothing in the environment. the template is identical, and the image that is deployed is either automatically generated according to the `ref` or is hard coded as `IMAGE_TAG` in the parameters. in either case, a new deployment will not change anything.
=> [saas-file-validator] validate that upstream is not used when ref is a commit sha

reconcile/utils/gitlab_api.py
Listing all groups is inefficient, and when the list grows too large
gives problems with pagination. Turns out we can just get the group
directly.
Refs https://redhat.pagerduty.com/incidents/Q30ZS9DDETNT5Q
=> Get groups directly by name

helm/qontract-reconcile/values-fedramp.yaml, openshift/qontract-reconcile-fedramp.yaml, reconcile/queries.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py
part of https://issues.redhat.com/browse/APPSRE-4092
depends on https://github.com/app-sre/qontract-schemas/pull/13
to be able to create vpc peerings without OCM using the account-vpc provider.
=> [terraform-vpc-peerings] add support to provide role to assume for account-vpc

.pylintrc
import-order is not very helpful, and we can't rely on any automatic
sorting since isort and pylint disagree here.
=> Disable some pylint checks

reconcile/utils/jjb_client.py
#2151 introduced a bug causing the integration to fail with
```
ERROR: Error running qontract-reconcile
File "/run-integration.py", line 150, in main
command.invoke(ctx)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/reconcile/utils/environ.py", line 15, in f_environ
f(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
return …
```
=> utils/jjb_client: fix subprocess's CompletedProcess method name

reconcile/openshift_tekton_resources.py
some pipelines may not have one of the sections (specifically, `finally`).
as the sections are currently "mandatory", we can define them as empty (`finally: []`). that creates a never ending attempt to reconcile, since the resource on the cluster will not contain the section at all.
this PR changes the behavior to allow missing sections from the desired resource.
=> [openshift-tekton-resources] allow missing section

reconcile/queries.py, reconcile/test/test_utils_slack_api.py, reconcile/utils/slack_api.py, reconcile/utils/smtp_client.py, tools/qontract_cli.py
depends on https://github.com/app-sre/qontract-schemas/pull/72
we currently store the smtp settings in the qontract-reconcile toml file.
this PR adds support to get smtp settings from app-interface settings.
=> add smtp settings to app-interface settings

reconcile/github_org.py, reconcile/github_owners.py, reconcile/github_repo_permissions_validator.py, reconcile/github_users.py, reconcile/utils/saasherder.py, reconcile/utils/terrascript_client.py
depends on https://github.com/app-sre/qontract-schemas/pull/74
instead of hard coding the name of our org, we can define it as `default: true` in app-interface, allowing other consumers to do the same.
=> add support for default github org

reconcile/utils/terrascript_client.py
the --print-to-file flag of terraform integrations results in the contents managed by terrascript to be dumped to a file. currently, only the contents of the last handled account is present in the file, because the dump loop keeps overwriting the same file over and over again.
this change makes sure that the file will contain the tf information from all accounts, delimited by `##### account name #####`
Ref: https://issues.redhat.com/browse/APPSRE-4421
=> terraform --print-to-file handle output for multiple accounts

reconcile/utils/terrascript_client.py
Ref.: https://issues.redhat.com/browse/APPSRE-4502
Currently the terrascript/ALB code will provision the ALB and related resources in the AWS account's default region
This is not the desired behavior as we expect the ALB to be in the same region as the cluster it is configured for. This is to avoid cross-region latency and extra network costs. The ALB is also expected to talk to the target cluster via a VPC that is configured in the same region as the cluster.
=> terrascript/alb: provision ALB in the same region as the cluster it is configured for

reconcile/openshift_saas_deploy.py, reconcile/utils/saasherder.py
This PR introduces a control to do automatic promotions only if there are changes in the promoting stage. 
Saas deployments are basically a desired/current resources reconciliation. If a deployment succeeds, it can trigger promotions to other saas deployments that comes next in the pipeline. If a deployment succeeds without doing anything (no changes to reconcile) it will trigger its promotions causing the pipeline to advance to the next steps. This can cause undesired effects when a target needs to run before moving to the next stage. 
Deployment(stage) --- > Test(stage) ---> Deployment(production)  --> ... 
Imagine this example pipeline runs and fails at `Test(stage)`. The pipeline won't continue because failed, but if `Test(Stage)` is rerun from the console, tests won't run because the …
=> APPSRE-3528: Auto-promote targets only if there are changes

reconcile/jenkins_job_builder.py, reconcile/utils/jjb_client.py
Improved two aspects: 
* Set `encoding` to `subprocess.run()` to avoid calling decode. 
* Add generic Exception handling. CalledProcessError is only raised if the process could run. If, for example, `jenkins-jobs` executable file does not exist, a `FileNotFoundException` is raised instead of CPE.
=> APPSRE-4225: Improve Exception handling

reconcile/utils/saasherder.py
Just add a log statement to print that auto-promotions are disabled in case someone reruns a stage that does not introduce any change. I think it's worth to add this msg to prevent misunderstandings.
=> APPSRE-3528: Add a log statement about disabled auto-promotions

reconcile/aws_iam_password_reset.py
we need to iterate over all accounts, and not only the account storing the state.
this is a bug introduced in #2049
=> fix aws-iam-password-reset accounts

reconcile/utils/terrascript_client.py
The issue was introduced in #2180 and applies only for elasticache instance & parameter groups that are in different region that the default one
=> Fix elasticache parameter group dependency assignment

.gitignore, reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
**Motivation**
Allow to specify which kinds of ES logs should be published.
Related schema change https://github.com/app-sre/qontract-schemas/pull/63
**Changes**
- support log_types: [`INDEX_SLOW_LOGS`, `SEARCH_SLOW_LOGS`, `ES_APPLICATION_LOGS`]
- create one dedicated cloudwatch loggroup per log_type per ES domain (AWS recommended)
- create ES resource policy to allow ES to create a logstream. Single policy per account required, as there is a limit of 10 per account.
**Tests**
Test data: https://github.com/app-sre/app-interface/pull/15
3 ES domains bootstrapped in dev account. 1 had a single log. 1 had all 3 logs. 1 had zerio logs. Logs (where expected) were successfully published.
Further, there was no plan diff on prod data.
=> APPSRE-4119 ES log publishing feature

reconcile/utils/jjb_client.py, requirements-test.txt, setup.py
This MR monkey-patches the use of md5 in jenkins-job-builder to support fedramp environment.
Concept: http://blog.serindu.com/2019/11/12/django-in-fips-mode/
I tested the code changes by rshing into a running container in fedramp and executing the changes. Calling hashlib.md5 on its own in a fedramp environment will cause a ValueError normally, however this shell snippet shows otherwise.
```
Python 3.9.6 (default, Aug 11 2021, 06:39:25) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> import hashlib
>>> import jenkins_jobs
>>> jenkins_jobs
<module 'jenkins_jobs' from '/usr/local/lib/python3.9/site-packages/jenkins_jobs/__init__.py'>
>>> def _non_security_md5(*args, **kwargs):
... …
```
=> Monkey patch JJB / MD5 usage for fedramp

reconcile/utils/jjb_client.py
This MR is a follow on to the jjb monkey patch MR, expanding the module list for patching.
=> Patch jenkins_jobs.builder for md5 in fips env

reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-4505
AWS best practices recommends using customer managed policies instead of inline policies: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#best-practice-managed-vs-inline
with this approach, we are no longer using inline policies, which have a limit of 2048 chars:
```
LimitExceeded: Maximum policy size of 2048 bytes exceeded for user
```
=> [terraform-users] replace inline policies with managed policies

reconcile/test/test_utils_aws_api.py, reconcile/utils/aws_api.py
similar to #1971
the default region to initiate the Session should be the account's default region and not the region where the terraform state bucket is located. since this is only the default region, this change is not expected to cause any issues (famous last words).
=> aws api use the account default region instead of terraform state bucket region as default

reconcile/openshift_resources_base.py
similar to the way we can use `vault()`, this PR adds support to template using `github()`. example:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: example
data:
public_policy.json: |-
{{ github('org/repo', 'path/to/file', 'ref') }}
```
```
=> [openshift-resources] add support to template resources from github files

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py
**Why do we need this change?**
Currently, VPC peerings (and other aws infra integrations) refer to the `cluster-1#awsInfrastructureAccess` section and use the last group with network-mgmt permissions for terraform interaction. 
This change is about to make this explicit!
**Change description**
The default account from the `cluster-1#awsInfrastructureManagementAccounts` list is used to manage `cluster-vpc-accepter` peering endpoints. the `cluster-vpc-requester` just follows the lead of the accepter. This makes it consistent with how account-vpc works, where the VPC plays the role of the accepter and the account of the VPC is used.
The `awsInfrastructureManagementAccounts` list remains optional to adhere to the qontract-schema evolution strategy of backwards compatibility, the current …
=> [terraform-vpc-peerings] use explicit infra account to mng vpc peerings

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/OSD-8770
depends on https://github.com/app-sre/qontract-schemas/pull/85
follows up on #1962
this will allow us to define a "safe" identifier (without dots), and a `name`, such as `dns.example.com`.
=> support providing name field to route53 zones

reconcile/utils/terrascript_client.py
related to https://issues.redhat.com/browse/OSD-8770
these outputs are added to the output resources. some services may only require the credentials in the supplied secret, and may fail to operate normally in case of additional keys in the secret.
this is the behavior with hive.
these outputs were only here for traceability and are not functionally required.
=> [terraform-resources] remove outputs for route53-zone

reconcile/blackbox_exporter_endpoint_monitoring.py, reconcile/queries.py
if a blackbox-exporter endpoint monitoring provider uses a module not listed in app-interface-settings, fail the integration (and as such also PR checks introducing invalid changes). if the app-interface-settings do not mention any allowed blackbox-exporter modules, no check will be conducted.
Part of: https://issues.redhat.com/browse/APPSRE-4523
Depends on schema change: https://github.com/app-sre/qontract-schemas/pull/80
=> check if blackbox-exporter monitoring provider uses only allowed modules

reconcile/utils/terraform_client.py
in some cases, there are outputs to be deleted without any resources being deleted. we currently can not detect that.
we decide whether or not to `terraform apply` based on resources changing, and a partial ability to find values changing for outputs.
this means that the outputs will never be removed. or, only removed the next time a resource is removed.
this PR adds a way to detect outputs being deleted and as a result, perform `terraform apply`.
=> [terraform] detect deleted outputs

reconcile/ocm_aws_infrastructure_access.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-4397
this PR changes the way we (implicitly) add `network-mgmt` role grants to terraform users, to (explicitly) define accounts that their terraform user should get a role grant.
=> [ocm-aws-infrastructure-access] explicitly define terraform user access

tools/qontract_cli.py
similar to `qontract-cli get bot-login`, but for AWS accounts. this will result in the credentials of the terraform user.
these creds should be used in case someone can't access their own creds or aws account and a swift action is required.
=> [qontract-cli] add aws-creds get subcommand

setup.cfg
Mypy only checks typed methods by default. This can be a sane default
for teams starting out with types. Now that we're enforcing types, it
makes more sense to enable a stricter mode so that Mypy will always
check functions for errors. There are >80 files that have errors that
Mypy would detect currently, but they were being ignored because there
weren't type hints. This should stop that behavior for new code and for
files that don't have existing errors.
See this link for more information on the motivation: https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code
=> Enable untyped def checks in Mypy

reconcile/utils/amtool.py, reconcile/utils/secret_reader.py, reconcile/utils/slack_api.py, setup.cfg
The docs for SlackResponse indicate that it can also be accessed by a dict
because __getitem__ is implemented. So, by avoiding the direct access of the
data attribute, we can avoid the need to deal with the potential for the data
to be bytes.
Related to the amtool error, you cannot catch the broad Exception and then
access attributes like stdout that only exist on certain types of exceptions.
I didn't perform any manual testing of these errors given the limited scope of the changes.
=> Cleanup Mypy errors for amtool, slack_api, and secret_reader

reconcile/checkpoint.py, reconcile/dyn_traffic_director.py, reconcile/test/test_gitlab_labeler.py, reconcile/test/test_openshift_base.py, reconcile/test/test_openshift_tekton_resources.py, setup.cfg
This changes ensures that there aren't Mypy ignores that are stale
that could mask other type issues in the future. This also includes
the removal of several ignore statements that no longer appear to be
necessary, or were made unnecessary via other methods (ignoring
missing imports).
=> Enable warn_unused_ignores option in Mypy

reconcile/checkpoint.py
We expect bad inputs, and we expect to report it as tickets. The stack
traces of `logging.exception` make it hard to understand what went
wrong or to spot the ticket that was actually created. We can still
get it under debug, if we want it.
=> Improve logging of validation issues

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/aws_ami_share.py, reconcile/cli.py, reconcile/queries.py, reconcile/test/test_aws_ami_share.py, reconcile/test/test_utils_aws_api.py, reconcile/utils/aws_api.py
part of https://issues.redhat.com/browse/APPSRE-4621
depends on https://github.com/app-sre/qontract-schemas/pull/91
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/34669
this integration is an idea from @BumbleFeng and will help simplify this: https://github.com/app-sre/qontract-reconcile/pull/2100#discussion_r817030105
this PR introduces a new integration that shares AMIs between AWS accounts.
by defining a `sharing` section in an AWS account file, we turn on sharing, according to the `provider`.
we start out by only supporting the `ami` provider, which will share images and copy image tags.
still TODO: tests and type hints
=> [aws-ami-share] introduce new integration

reconcile/utils/aws_api.py
https://coreos.slack.com/archives/CS0E65QCV/p1646713787105329
```
[aws-ami-share]     tag_type_def = TagTypeDef(Key=tag['Key'], Value=tag['Value'])
[aws-ami-share] TypeError: object() takes no arguments
```
=> fix ami tag type error

reconcile/test/test_utils_aws_api.py, reconcile/utils/aws_api.py
follows up on #2216
we can not share an AMI that is not available. this PR filters these AMIs out.
error: https://coreos.slack.com/archives/CS0E65QCV/p1646740896836509
```
Error running qontract-reconcile
File "/run-integration.py", line 150, in main
command.invoke(ctx)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
return …
```
=> [aws-ami-share] check that AMI is available

reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
as the IMAGE_TAG parameter is automatically generated, we should enforce cleaner configuration.
if IMAGE_TAG is the same as the ref, IMAGE_TAG is not required.
https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/continuous-delivery-in-app-interface.md#automatically-generated-parameters
=> [saas-file-validator] fail validation when IMAGE_TAG matches ref

reconcile/terraform_resources.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_client.py
Depends on https://github.com/app-sre/qontract-schemas/pull/53
Part of https://issues.redhat.com/browse/APPSRE-3925
Design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/34670
First implementation. Tf-r will fail when the packer job is running or failed, as the commit has been pushed but the AMI has not been built. Will add upstream info for checking Jenkins job state in a second PR.
=> [tf-r]auto promote asg ami id

reconcile/aws_iam_keys.py, reconcile/test/test_aws_iam_keys.py
related to https://issues.redhat.com/browse/APPSRE-4621
if there is nothing to do, why not filter it.
=> [aws-iam-keys] filter accounts without delete keys

reconcile/aws_support_cases_sos.py, reconcile/test/test_aws_support_cases_sos.py
related to https://issues.redhat.com/browse/APPSRE-4621
if premium support is not enabled, the integration can't do it's work. it's worthless to try :)
=> [aws-support-cases-sos] filter accounts without premium support

e2e_tests/cli.py, e2e_tests/create_namespace.py, helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
* Add dry_run mode to e2e_tests.
* Add cronjobs to run e2e-tests in cluster.
As part of efforts to pivoting away from Jenkins.
APPSRE-3615
Deployed yaml contains only new e2e related cronjobs to Staging and they ran successfully.
=> Add cronjobs to run e2e-tests; Add dry_run mode to e2e_tests.

reconcile/aws_iam_keys.py, reconcile/test/test_openshift_tekton_resources.py, tools/qontract_cli.py
Related to this Slack thread: https://coreos.slack.com/archives/GGC2A0MS8/p1647030227605789
I also was unlucky and lost the CI dependencies changing game, so two minor fixes there to unblock CI. They were minor enough that it didn't make much sense to create a separate PR.
=> More help for sre checkpoint metadata

reconcile/terraform_resources.py, reconcile/test/test_utils_terrascript_client.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3925
depends on https://github.com/app-sre/qontract-schemas/pull/95
now that we have support for continuous deployment of AMIs, we want to avoid failing under healthy conditions.
for example, once a new commit is pushed, the integration tries to use a corresponding AMI. initially, that AMI is being built, which means it doesn't exist yet.
to be able to not fail in this condition, and to improve visibility from the ASG definition, this PR adds support for an upstream job to wait for (like saas files).
=> [terraform-resources] ASG add support for upstream job

reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_groups.py, reconcile/openshift_rolebindings.py, reconcile/queries.py, reconcile/test/test_openshift_base.py
part of part of https://issues.redhat.com/browse/APPSRE-4663
depends on https://github.com/app-sre/qontract-schemas/pull/100
this PR introduces new logic to the following integrations:
- openshift-clusterrolebindings
- openshift-groups
- openshift-rolebindings
- openshift-users (because it uses `fetch_desired_state` from the above integrations)
instead of always using the `github_username` field, we choose which field to use based on the cluster auth `service`.
the addition in this PR - for `service: oidc` we use `org_username`.
note: this PR also removes logic to add github bots to cluster access since it is not something we need to do (and it's not used).
=> determine user key for openshift access

reconcile/github_repo_invites.py, reconcile/queries.py, reconcile/test/test_github_repo_invites.py
**Motivation**
We currently store configuration for the github-repo-invites integration in our config.toml. This PR makes `github-repo-invites` read the configuration from `app-interface`, making the `[github-repo-invites]` section redundant.
Further, this PR refactors the `github-repo-invites` integration and adds unit tests for it.
~This PR keeps backwards compatibility by using `config.toml` if gql does not return required data. Once all app-interfaces are migrated, we can remove this backwards compatibility option.~ Backwards compatibility is not required, as there is only one app-interface using this integration.
**Test**
- Successfully ran with `--dry-run` for corresponding schema https://github.com/app-sre/qontract-schemas/pull/97
- added unit tests to cover the important logic
=> APPSRE-4404 move data from toml to app-interface

reconcile/queries.py, reconcile/terraform_aws_route53.py, reconcile/test/test_utils_aws_api.py, reconcile/utils/aws_api.py, requirements/requirements-type.txt
part of https://issues.redhat.com/browse/APPSRE-4705
depends on https://github.com/app-sre/qontract-schemas/pull/98
similar to using `_target_cluster` to obtain the elb fqdn, we can target a namespace with a route53-zone provisioned in it to automatically obtain NS records of that zone (instead of hard coding them): `target_namespace_zone`.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/35369
=> [terraform-aws-route53] add support for target namespace zone

reconcile/test/test_openshift_resource.py, reconcile/utils/openshift_resource.py
the ACM ManagedCluster CR has lots fields/labels/annotations that
are applied and removed dynamically by ACM controllers. removing
them in the canonicalization step (and thus removing them from the
comparision logic to detect drift) allows the a-i management of those
CRs.
part of https://issues.redhat.com/browse/APPSRE-4619
=> canonicalize ACM ManagedCluster CR

reconcile/utils/aws_api.py
part of https://issues.redhat.com/browse/APPSRE-4705
fixes #2240
=> aws_api get_route53_zone_ns_records return empty list when all record sets are filtered out

reconcile/utils/terrascript_client.py
Fixes an issue with ALB where the IPv6 security group rule doesn't get added
=> Remove ipv6_cidr_blocks preset value from ALB SG

reconcile/test/test_openshift_resource.py, reconcile/utils/openshift_resource.py
cluster controllers that are labeling resources break our drift detection
for openshift_resources. this MR introduces a way to declare
which labels on which kind are supposed to be ignored because
their existance or values are managed by a cluster controller.
usually additional fields in the current state of a resource are ignored by
the `OpenshiftResource``eq` implementation, but labels drift is checked
specifically.
e.g. ACM (Advanced Cluster Manager) controllers put dynamic labels on
the `ManagedCluster` CRs, e.g. the generated ID of a cluster or the
detected Openshift `version` running on the cluster.
=> controller managed labels per kind

reconcile/test/test_utils_aws_helper.py, reconcile/test/test_wrong_region.py, reconcile/utils/aws_api.py, reconcile/utils/aws_helper.py, reconcile/utils/terrascript_client.py
if the state bucket region (coming from the vault secret) is different from the account's resources default region (coming from the account file) - the region selected for the terraform backend configuration is the wrong one. it should be the region of the state bucket, coming from the vault secret.
when `aws_api` and `terrascript_client` are initiated, they interfere with each other if `resourcesDefaultRegion` is different from the terraform bucket region.
this issue was introduced in #2165 (famous last words indeed), where we actually started overriding the state bucket region with the resources default region.
this PR starts by adding tests that are expected to pass. the fact that they are failing proves the existence of the bug.
i've isolated the "fix" to this single commit: …
=> [bug] terrascript_client initiates terraform state backend with wrong region when aws_api is initiated

reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-4365
reverts #927
replaces #2134
this PR removes the possibility to skip checking images. this feature was relying heavily on jenkins functionality which is not present for tekton. more details in the ticket.
=> [openshift-saas-deploy] do not skip checking images

reconcile/openshift_base.py, reconcile/utils/oc.py
related to https://issues.redhat.com/browse/APPSRE-4733
in this incident, we leaked a Secret because the raised exception was not caught to be REDACTED.
this is where we introduced redacting: #1768
this is where we introduced the uncaught exception: #1903
this PR changes the thrown exception to (the only) one that is caught.
=> [openshift] redact Secret when unable to apply

reconcile/slack_usergroups.py
part of https://issues.redhat.com/browse/APPSRE-4737
github usernames may appear in lower case or not in OWNERS files.
=> [slack-usergroups] check github username lower as well

reconcile/terraform_aws_route53.py, reconcile/terraform_resources.py, reconcile/terraform_tgw_attachments.py, reconcile/terraform_users.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_utils_terraform_client.py, reconcile/utils/aws_api.py, reconcile/utils/terraform_client.py, tools/qontract_cli.py
RDS engine_version changes are unique because a tenant may want to change
this value, but allow RDS to upgrade the instance during the next maintenance
window. This window could be up to 7 days away, which in the meantime would
cause Terraform to apply the change every time that the integration runs (as
well as log the change, which is more annoying than harmful). Unnecessary
apply operations will result in state changes and any instances of
terraform-resources running will need to restart (think PR checks).
The manual tests that I performed so far were:
1. Upgrade RDS `engine_version` without `apply_immediately` and confirm that the next time terraform-resources runs, it skips the Terraform `apply`
2. After doing above, set `apply_immediately: true` and run again, then RDS is upgraded …
=> Skip Terraform apply when the only RDS update would be engine_version

reconcile/terraform_aws_route53.py, reconcile/terraform_resources.py, reconcile/terraform_tgw_attachments.py, reconcile/terraform_users.py
The initialization of these AWSApi objects was introduced in #2254,
so this should not break existing functionality. This should avoid
needing to initialize users where it doesn't seem necessary to do
so. Also fixed cases where settings weren't properly defined as a
kwarg.
For testing I ran through the same tests for `terraform-resources` as what was described in #2254. The rest of the terraform integrations should not even be using `AWSApi` at this point given that this is a new dependency that was added to `TerraformClient`.
=> Switch usage of AWSApi in terraform integrations to skip init_users

reconcile/utils/aws_api.py
A recent change, #2257, changed the way that the AWS region is determined for sessions that are created in `AWSApi`. One consequence of this is that some AWS services are only located in `us-east-1`, in this case the support API.
Before this change:
```
$ qontract-reconcile --config config.prod.toml --dry-run --log-level INFO aws-support-cases-sos
[2022-03-23 14:58:12] [INFO] [gql.py:init_from_config:220] - using gql endpoint http://localhost:4000/graphqlsha/514f61fcfa6299538bd9e172211f230df64ae191e53db006d3a87c40e8d558d6
[2022-03-23 14:59:58] [ERROR] [aws_api.py:get_support_cases:696] - [account-name] error getting support cases. details: Could not connect to the endpoint URL: "https://support.eu-central-1.amazonaws.com/"
```
With this change the integration runs without errors.
=> Update AWSApi.get_support_cases to use us-east-1 for the support API

dockerfiles/Dockerfile.test, tox.ini
pylint was using all available core due to the '-j0' option. It seems
that running tox environments in parallel will provide better improvements
in the total execution time.
On my laptop, this ran in `7m7.225s` compared to `8m56.947s` without tox parallelization. We can get more real-life data from our builds over the next week or two.
=> Parallelize tox runs in Dockerfile.test

reconcile/openshift_resources_base.py
part of https://issues.redhat.com/browse/APPSRE-4750
with this PR, we can add sections to be templated based on graphql query results.
for example:
```
{{ query('/queries/jira_boards.graphql') }}
```
this will results in an iterable which we can use to template.
in this example, this is the content of /queries/jira_boards.graphql:
```
{
jira_boards_v1 {
name
}
}
```
=> enable option to template resources with graphql query results

reconcile/test/test_utils_gql.py, reconcile/utils/gql.py, setup.py
This MR replaces `graphqlclient` which is a library unmaintained since 2018 with the official graphql client per https://github.com/graphql-python/gql
I tested some of the integrations locally and they seem to work well. However to get 100% confident I suggest we deploy this in our staging and let it observe for couple of days just to ensure there aren't any missing edge cases. 
I have verified the client displays detailed error message which was hampering our troubleshooting earlier.
```
reconcile.utils.gql.GqlApiError: Could not connect to GraphQL server ({'message': 'Cannot query field "booh" on type "User_v1".', 'locations': [{'line': 10, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}})
```
=> APPSRE-4731: Use official graphql library

reconcile/openshift_resources_base.py
part of https://issues.redhat.com/browse/APPSRE-4750
follows up on #2272
this PR adds support to pass keyword arguments to a `query()` function in a templated resource, to allow us (for example) to query a resource by it's unique key.
for example:
```
{{ query('/queries/jira_boards.graphql', name=MYBOARD) }}
```
in this example, this is the content of /queries/jira_boards.graphql:
```
{
jira_boards_v1
(
name: "{{ name }}"
)
{
name
}
}
```
=> add support to pass kwargs to query()

reconcile/prometheus_rules_tester.py
if a PrometheusRule is templated and does not have `variables` - the integration fails:
```
File "/home/mafriedm/repos/app-sre/qontract-reconcile/venv/bin/qontract-reconcile", line 33, in <module>
sys.exit(load_entry_point('qontract-reconcile', 'console_scripts', 'qontract-reconcile')())
File "/home/mafriedm/repos/app-sre/qontract-reconcile/venv/lib64/python3.10/site-packages/click/core.py", line 829, in __call__
File "/home/mafriedm/repos/app-sre/qontract-reconcile/venv/lib64/python3.10/site-packages/click/core.py", line 782, in main
File "/home/mafriedm/repos/app-sre/qontract-reconcile/venv/lib64/python3.10/site-packages/click/core.py", line 1259, in invoke
return …
```
=> [prometheus-rules-tester] variables may be None

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
part of https://issues.redhat.com/browse/APPSRE-4758
this PR adds usage of the qontract-reconcile ServiceAccount instead of using the default ServiceAccount.
=> [helm] CronJob should use service account

setup.py
It used to break unleash but it seems to have been fixed. We want to
be able to receive security updates easily.
=> Remove direct dependency on tzlocal

reconcile/checkpoint.py, reconcile/openshift_resources_base.py, reconcile/test/test_checkpoint.py
this will allow us to test the existence of a url and template based on the results.
the `url_makes_sense` function was introduced in https://github.com/app-sre/qontract-reconcile/pull/2141/commits/fcbd19d35d93bcf84d3d9b0707ae221e6e95b4b5.
the intention behind this PR is to use it for the same purpose - to check if an `architectureDocument` link makes sense.
example usage: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/36181
=> [openshift-resources] add support to test if a url exists within a resource

reconcile/utils/lean_terraform_client.py
Without this change, we don't see which account is causing issues unless
Exception was raised 3 times (due to retry() usage elsewhere in the code).
=> Add more context about the failed account for stale terraform errors

setup.py
After merging a newer tzinfo, we are stuck with a dependency chain
that relies on a very old API, causing a lot of messages like
```
/usr/local/lib/python3.9/site-packages/apscheduler/triggers/interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
```
A newer UnleashClient fixes these dependencies and uses non-deprecated
APIs.
=> Use a newer unleash client

reconcile/test/test_utils_ocm.py, reconcile/utils/ocm.py
Clusters created with ROSA lack some fields we rely on, such as `storage_quota`. If they are missing, we simply skip them since app-interface won't handle them anyways.
Refs https://issues.redhat.com/browse/APPSRE-4790
=> Do not crash OCM if storage_quota isn't defined

reconcile/utils/vault.py
It warns (rightly) that we can leak memory. A maxsize of 2048 items
looks enough for most cases, and will keep the linter happy.
=> Fix lint error on lru_cache usage

reconcile/ocm_upgrade_scheduler.py, reconcile/test/test_ocm_upgrade_scheduler.py
This allows to prioritize clusters sharing the same upgrade mutex.
The cluster with lower version, or lower soakDays (when versions are equal) will get upgraded first
@maorfr PTAL. Do you think that's fine ? I am actually wondering if higher version clusters should not upgrade first. It's a matter of taste..
=> sort clusters according to their version and soakDays before considering their upgrade

setup.py
i think we'd want to start enforcing that every PR requires a bump of the version.
and after that, probably change the release to pypi from tag based to push based.
cc @fishi0x01 @Piojo
=> bump version to release to pypi

reconcile/test/test_utils_gql.py, reconcile/utils/vault.py
Test directly the relevant function instead of the decorated one.
The retry decorator introduces sleeps that slow us down and we don't
want to test within this file.  More reading:
https://service.pages.redhat.com/dev-guidelines/docs/appsre/python-testing-guide/#testing-decorated-methods
To be merged after #2323
=> Speed up GQL-related tests by ~300x

reconcile/ocm_upgrade_scheduler.py, setup.py, tools/qontract_cli.py
When several upgrades where possible, with enough soak days, the wrong one could be selected as the next one being performed (the one with most soak days instead of the highest version matching conditions)
=> fix ready upgrade in qontract-cli cluster-upgrade-policies

reconcile/utils/terrascript_client.py, setup.py
The current one allows for deprecated, insecure, and banned inside Red
Hat TLS protocols. We must use at least TLSv1.2, which is 11 years
old. It should be compatible with everything under the sun.
Refs https://issues.redhat.com/browse/APPSRE-4803
=> Change the default security policy for ELB

reconcile/cli.py, reconcile/template_tester.py, setup.py
part of https://issues.redhat.com/browse/APPSRE-4750
depends on https://github.com/app-sre/qontract-schemas/pull/117
this PR adds a new integration called `template-tester` which tests templated resources and verifies that their result (rendered resource) matches an expected result.
the approach of this PR is similar to https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/prometheus_rules_tester.py
=> [template-tester] introduce new integration

reconcile/quay_permissions.py, reconcile/quay_repos.py, setup.py
part of https://issues.redhat.com/browse/ASIC-208
we currently fail silently when we should error out.
=> Quay error on repo actions when managedRepos is set to false

reconcile/utils/gql.py, setup.py
Not setting timeout can lead to situations such as indefinite wait on network I/O, so if graphql server is down for example, the request library may indefinitely wait and cause current process to go under sleeping state. 
The `retry` decorator should automatically cover the retries as TimeoutError will be rethrown as `GqlApiError`.
=> Add timeout to gql client

.gitignore, MANIFEST.in, Makefile, README.md, build_deploy.sh, build_tag.sh, dockerfiles/Dockerfile, reconcile/test/test_version_bump.py, release/test_version.py, release/version.py, setup.py, tox.ini, version
Releasing proposal
Why:
- avoid merge conflicts due to manual version bumping
- version each commit automatically
- simple X.Y.Z version management: simply git tag & push.
Challenges
- Python does not strictly follow Semver: https://peps.python.org/pep-0440/
- docker image tags don't support `+` signs, so dropping it there
- we run setup.py without git repos in several cases (tox does sdist and then setup again, docker builds don't include .git, rightfully). So the git version is first saved as a file GIT_VERSION.
=> [PROPOSAL] versioning automation

release/test_version.py, release/version.py
This seems to cause 'Can't use PEP 440 local versions'
=> remove the commitid from the pip version

reconcile/prometheus_rules_tester.py
part of https://issues.redhat.com/browse/APPSRE-4765
to allow adding a single prometheus rule to multiple namespace files and to retain ability to test it, we currently add the resource's variables to support templating of the prometheus rules tests. example: https://gitlab.cee.redhat.com/service/app-interface/-/blob/43dfaffd6eab6e771ad51ea84ed7a396d378f709/resources/services/backplane/backplane-api-prod-common.prometheusrules-test.yml#L26
this PR adds the actual resource to the variables, to support templating based on the resource itself (`resource.namespace.cluster.name` for example).
this is the same as we do for templating the resource itself:
https://github.com/app-sre/qontract-reconcile/blob/5a107eeedff8a579d06ad91a889862aac80f7adc/reconcile/openshift_resources_base.py#L508
example …
=> [prometheus-rules-tester] keep resource in variables

reconcile/utils/jjb_client.py, setup.py
Version 3.12.0 of the jenkins-job-builder dependency was not compliant with FIPS and caused the jjb integration to fail within the fedramp environment. 
Changes:
- Update to version 4.0.0, which contains FIPS patch
- Monkey patch attempt within `jjb_client.py` removed
Note: dry-run against commercial and fedramp environments yields no diffs between `current/` and `desired/`
Ticket: https://issues.redhat.com/browse/APPSRE-4411
=> use jjb version with fips patch

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-fedramp.yaml, openshift/qontract-reconcile-fedramp.yaml, reconcile/cli.py, reconcile/resource_scraper.py
this is a utility integration that collects resources from specific namespaces of clusters and stores them in vault.
this utility can be used for different purposes, such as disaster recovery.
the current use case is https://issues.redhat.com/browse/OSD-10326
=> [resource-scraper] introduce utility integration

dockerfiles/hack/run-integration.py, reconcile/utils/metrics.py
increase an execution counter on integration run start.
if the counter does not increase for a while, we can assume a stuck integration
```yaml
sum(increase(qontract_reconcile_execution_counter[1h])) by (integration, shards, shard_id) == 0
```
Part of https://issues.redhat.com/browse/APPSRE-4904
=> [run-integration] expose integration start counter

reconcile/queries.py, reconcile/sql_query.py
part of https://issues.redhat.com/browse/APPSRE-4765
the sql-query integrations creates Jobs (or CronJobs) in a tenant's namespace to perform a query against their database.
the integration currently tries to use the same image of the database engine, by looking for the version in the `defaults` file. however, the version may not be there, and may be in the `overrides` section.
this PR makes it so the integration searches for the version in the `overrides` section as well, by re-using the logic from terrascript_client:
https://github.com/app-sre/qontract-reconcile/blob/02252e58cf1f4579ffd3815ac12485cab68c17d2/reconcile/utils/terrascript_client.py#L3075-L3113
this will help us in running less with `latest`.
as a result, and this is why the linked ticket is about DVO, this will help remove …
=> [sql-query] try not to use latest

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-fedramp.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
part of https://issues.redhat.com/browse/APPSRE-4765
docs: https://www.civo.com/learn/yaml-best-practices-using-kubelinter#ignoring-a-check
this PR disables the DVO check of minimum 3 replicas for integrations, as our scaling mechanism is shards and not replicas.
=> disable DVO minimum-three-replicas check for integrations

reconcile/prometheus_rules_tester.py, reconcile/template_tester.py
part of https://issues.redhat.com/browse/APPSRE-4765
this PR adds the option to test resources referenced by shared resources files referenced from namespace files. without this change, only resources defined in a namespace's `openshiftResources` section can be tested.
this is the function being used:
https://github.com/app-sre/qontract-reconcile/blob/a3285f140702cdd9386a4faa7357b0c7ac149af5/reconcile/openshift_base.py#L775-L799
this PR enables https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/37591
=> consider shared resources in tester integrations

reconcile/service_dependencies.py
Old `saas-file-1` was used in `service_dependencies` integration. This PR removes it
=> APPSRE-3556 remove saas-file-1

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
depends on https://github.com/app-sre/qontract-schemas/pull/131
this included some changes around how we handle `availability_zone`, to add a validation that there is no conflict.
=> add support to define region for rds instances

reconcile/terraform_resources.py, reconcile/test/test_openshift_resource.py, reconcile/test/test_terraform_resources.py, reconcile/test/test_utils_terraform_client.py, reconcile/test/test_utils_terraform_resource_spec.py, reconcile/utils/openshift_resource.py, reconcile/utils/terraform_client.py, reconcile/utils/terraform_resource_spec.py, reconcile/utils/terrascript_client.py
Refactor the desired state and vault handling for terraform resource output. This change introduces additional unittesting and typehints, to prepare for future changes like terraform output formats and shared terraform resources.
_Scope:_ refactor the the use of terraform resources from qontrac-server within terraform-resources and terraform-client.
_Out of scope:_ terrascript-client was not touched to keep the size of this change manageable and reviewable. A followup change will start using the changes of this MR.
Please review commit by commit. Each commit contains a smaller logical change along with a detailed commit message and respective type hints and unittests.
This refactor introduces a dataclass `TerraformResourceSpec` that holds data and context for terraform resources, namely: …
=> [terraform-resources] refactor desired state and vault handling

reconcile/terraform_resources.py
https://github.com/app-sre/qontract-reconcile/pull/2331 started using the tf output secrets for vault writing instead of the ResourceInventory secrets.
former ones are not b64 encoded, latter ones are, so the vault write must not try to decode the secret otherwise the write fails because of the failed b64 decoding
=> don't b64 decode the tf output secret on vault write

reconcile/terraform_resources.py
this came up as a result of the recent terraform-resources refactor.
this fix is a temporary one. the real fix should avoid processing tf resource specs when the integration is not enabled on the respective cluster
=> don't attempt to write empty tf secrets to vault

tools/qontract_cli.py
new qontract-cli get command to group ocm-aws-infrastructure-access-switch-role-links output by user, making it simpler to search.
Example output: https://gitlab.cee.redhat.com/-/snippets/5238
=> new cli command ocm-aws-infrastructure-access-switch-role-links-by-user

setup.py
We're having issues with version 37.0.1 in routers as we're getting the
default cluster cert instead of the router one.
See [APPSRE-5475](https://issues.redhat.com/browse/APPSRE-5475)
=> Pin cryptography module to avoid cert issues

reconcile/checkpoint.py
we use this function as part of the openshift resources `url` templating (check if a url exists).
when an SSL issue exists (as happens with gitlab for example), we deem the url bad, while it is in fact good.
instead of getting caught up on SSL (which we care about in other perspectives of course), let's let this through without verifying SSL.
=> url makes sense no verify

reconcile/openshift_base.py, reconcile/openshift_resources_base.py, reconcile/terraform_resources.py, reconcile/test/test_openshift_base.py, reconcile/test/test_openshift_resource.py, reconcile/test/test_openshift_resources_base.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py, reconcile/utils/openshift_resource.py, reconcile/utils/saasherder.py
The core change of this PR enables the use of full qualified kube `kinds` (resource types) in `managedResourceTypes` of `saas` files and `namespace` files. This replaces the need for `managedResourceTypeOverrides` in saas files and enables resource handling in saas files where the proposed `kind` is not unique without the `group`.
https://issues.redhat.com/browse/APPSRE-4915
e.g. instead of
```yaml
managedResourceTypeOverrides:
- resource: Subscription
override: Subscription.operators.coreos.com
managedResourceTypes:
- Subscription
```
this change enables the declaration to look like this
```yaml
managedResourceTypes:
- Subscription.operators.coreos.com
```
Both declarations will lead to the same results but the latter one also enables saas files and namespaces files to managed same-named …
=> [openshift-resources + saas] allow full-qualified kinds in managedResourceTypes

reconcile/test/test_utils_aws_helper.py, reconcile/utils/aws_api.py, reconcile/utils/aws_helper.py, reconcile/utils/terraform_client.py
We are seeing errors when upgrading a database in a region other than `us-east-1`. This is because there is logic to check whether a RDS change should skip `terraform apply`, but that logic doesn't account for RDS instances in regions other than `us-east-1`.
The error that we'd see was:
```
botocore.errorfactory.DBInstanceNotFoundFault: An error occurred (DBInstanceNotFound) when calling the DescribeDBInstances operation: DBInstance <database-name> not found.
```
**Testing**
- Changed the `engine_version` of a database in `us-west-2` and observed the error above
- Applied the code fix in the PR and the error was no longer present in dry-run mode
- Changed the `engine_version` of a database in `us-east-1` and confirmed dry-run finished successfully
=> Fix RDS ignored modifications logic to be region aware [APPSRE-5483]

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
as we work on https://issues.redhat.com/browse/APPSRE-4765, we will get more traction on DVO metrics.
this means tenants would want to see their work reflected in dashboards.
with this job running once every 24 hours, the feedback loop will be too slow.
is there a reason not to run this job once an hour?
=> run dashdotdb-dvo once an hour

reconcile/utils/openshift_resource.py
another attempt similar to #2375 (which was partially reverted in #2378), but from a different approach.
instead of only "fixing" our own template to not have empty values (which are hard to compare), this PR adds a special handle to compare environment variables.
if an current environment variable only has the `name` key, it means the desired value that was applied is empty (`""`). 
by "faking" an empty `value`, we are able to compare (and not apply when "equal").
=> add fake empty value for env section compare

reconcile/terraform_resources.py, reconcile/test/test_utils_terraform_resource_spec.py, reconcile/utils/openshift_resource.py, reconcile/utils/terraform_resource_spec.py
this PR implements the `generic-secret` provider, that can render output secret content based on jinja2 templates, e.g.
```yaml
---
$schema: /openshift/namespace-1.yml
...
terraformResources:
- provider: aws-iam-service-account
output_format:
provider: generic-secret
data:
aws_access_key_id: {{ aws_access_key_id }}
aws_secret_access_key: {{ aws_secret_access_key }}
credentials: >-
[default]
aws_access_key_id = {{ aws_access_key_id }}
aws_secret_access_key = {{ aws_secret_access_key }}
```
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/terraform-output-secret-format.md
part of https://issues.redhat.com/browse/APPSRE-4766
=> [terraform-resources] provider driven terraform secret output format

dockerfiles/Dockerfile
follows up on:
- https://github.com/app-sre/container-images/pull/39
- https://github.com/app-sre/container-images/pull/40
this PR adds the helm binary to the qontract-reconcile image.
=> update base images

reconcile/integrations_manager.py
follows up on #2384
the integrations-manager should be able to run without input, to support deploying it before any integrations.
=> integrations-manager exit on empty input

dockerfiles/Dockerfile, dockerfiles/structure-test.yaml
the integrations-manager integration is failing with the following message:
```
reconcile.utils.helm.HelmTemplateError: Error running helm template [helm template ./helm/qontract-reconcile -n qontract-reconcile -f /tmp/tmpc9kul414] Error: path "./helm/qontract-reconcile" not found
```
this PR should make the integration run from a location where `./helm` exists.
=> run integration with current work dir near source code

dockerfiles/hack/run-integration.py, helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager.yaml, reconcile/test/fixtures/helm/integrations_manager.yml
fixes a bug introduced in #2384
the issue is that `integrations-manager` should be able to run in non dry-run mode, and at the same time create integrations that run in dry-run mode.
since the container env vars override app-interface environment parameters, the `MANAGER_DRY_RUN` was actually considered as the `DRY_RUN` for the managed integrations:
https://github.com/app-sre/qontract-reconcile/blob/faa5da9f4918cb8f6b79c2bc010091d7a0546be5/reconcile/test/test_integrations_manager.py#L80-L97
this PR splits the dry-run to have different template parameters for `integrations-manager` and for managed integrations.
=> [integrations-manager] self dry-run

helm/qontract-reconcile/templates/template.yaml
`failedJobHistoryLimit` is currently set as a string, while it should be an integer. the reason it is not an integer is because the value `0` is interpreted as non-exists, and the default value of `1` is being used.
this PR fixes it so integer with value `0` is working as expected.
reference: https://github.com/helm/helm/issues/3164#issuecomment-709537506
history: #1344
=> fix helm template to accomodate failedJobHistoryLimit with value 0 (integer)

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-fedramp.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml, reconcile/test/fixtures/helm/concurrency_policy.yml, reconcile/test/fixtures/helm/cron.yml, reconcile/test/fixtures/helm/dashdotdb.yml, reconcile/test/fixtures/helm/failure_history.yml, reconcile/test/fixtures/helm/restart_policy.yml, reconcile/test/fixtures/helm/success_history.yml
this PR updates the apiVersion for CronJobs and fixes typos in the job history limit field names (this never worked :scream:)
=> fix helm chart for CronJobs

reconcile/queries.py
since sql-query is using terrascript to get info of the DB to be queries, we need to conform to the namespace required fields that were added in #2386
=> [sql-query] fix usage of terrascript

reconcile/utils/ocm.py
use `cluster["version"]["raw_id"]` to get the version as this field gets updated only after the upgrade is fully complete, nodes included.
`cluster["openshift_version"]` gets updated before that.
@maorfr could you PTAL ? I did not find anything that could have a bad side effect.
Looking at our clusters, it seems `["version"]["raw_id"]` is always present for OSD clusters. If we want to be sure, we could also use `cluster["version"].get("raw_id") or cluster["openshift_version"]`
=> update version once all nodes are upgraded

reconcile/cli.py, reconcile/integrations_manager.py, reconcile/test/test_cli.py, reconcile/test/test_integrations_manager.py
when running integrations-manager against multiple environments, each such environment may have a different version of integrations-manager running. as a result, managed integrations in different environments will be using a different `IMAGE_TAG`.
for this reason, running integrations-manager without environment awareness (`ENVIRONMENT_NAME`, `IMAGE_TAG` env vars) will result in the integration wanting to update all integrations in all environments to use `latest` (the default from the OpenShift template).
this PR adds an option to pass a list of environments, and for each of them - which `ref` of the qontract-reconcile repository should be used.
with this change, integrations-manager can run (specifically in dry-run) without showing any changes when there aren't any changes required.
=> [integrations-manager] add support for image-tag-from-ref

reconcile/aws_iam_password_reset.py, reconcile/test/test_aws_iam_password_reset.py
Prevents errors like: An error occurred (NoSuchEntity) when calling the DeleteLoginProfile operation: The user with name foobar cannot be found.
=> Assert that user is AWS account

reconcile/utils/terraform_client.py
```
File "/usr/local/bin/qontract-reconcile", line 8, in <module>
sys.exit(integration())
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/reconcile/utils/binary.py", …
```
=> [terraform-resources] update _is_ignored_rds_modification to handle missing keys

reconcile/terraform_resources_wrapper.py
when disabling terraform-resources from a cluster, the cluster doesn't understand that the calling integration is the wrapper.
ref: https://github.com/app-sre/qontract-reconcile/blob/55751e39d6bf49c2fa43c0bd80cebcbb1c85fa06/reconcile/terraform_resources.py#L429
this approach is similar to: https://github.com/app-sre/qontract-reconcile/blob/55751e39d6bf49c2fa43c0bd80cebcbb1c85fa06/reconcile/openshift_vault_secrets.py#L19-L20
=> [terraform-resources-wrapper] fix calling integraions name for filtering out clusters

README.md, reconcile/cli.py, reconcile/query_validator.py
part of https://issues.redhat.com/browse/APPSRE-5561
depends on https://github.com/app-sre/qontract-schemas/pull/153
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/schema-compatibility.md
this PR adds an integration (`query-validator`). This integration acts on `query-validation-1` files. The integration will be pretty straight forward: For each entry in the `queries` list, execute the query. If it fails - fail the integration.
This integration will only run within app-interface pr-check to gate merges of schema promotions that break the tenants' queries. In case this integration fails, we will contact the responsible team to make adjustments to their source code and to the queries in app-interface.
=> introduce query-validator

reconcile/cli.py, reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/openshift_saas_deploy_trigger_upstream_jobs.py, reconcile/queries.py, reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-5484
currently we can trace what caused a deployment to be triggered only based on the time.
with this change, we will know what integration triggered a deployment and for what reason.
the reason will be:
- openshift-saas-deploy-trigger-moving-commits - the upstream commit
- openshift-saas-deploy-trigger-upstream-jobs - the jenkins job
- openshift-saas-deploy-trigger-configs - the app-interface commit
parameters are added in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/39361
=> [openshift-saas-deploy-trigger] add information on what caused a trigger

reconcile/test/test_openshift_resource.py, reconcile/utils/openshift_resource.py
if a resource has a `status` section, it should be ignored when comparing current with desired resource.
if a resource has a `status` section deep under another field, it needs to be compared. example: CRDs.
this PR introduces a concept of `depth` into our compare logic. if `status` is on depth 0, it needs to be ignored.
slack thread: https://coreos.slack.com/archives/CCRND57FW/p1653423187653079
=> openshift ignore status on object compare only at the root level

reconcile/cli.py, reconcile/gitlab_fork_compliance.py
the most important thing about fork-compliance is to add a bot account to a fork.
not all tenants who want to use it have a gitlab group, but still want the bot added.
this PR makes the gitlab maintainers group argument optional to support that.
=> [gitlab-fork-compliance] make gitlab group optional

reconcile/terraform_resources.py, reconcile/utils/terrascript_aws_client.py
part of https://issues.redhat.com/browse/APPSRE-4611
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/additional-terraform-providers.md
replaces #2203
depends on https://github.com/app-sre/qontract-schemas/pull/87
this PR adds support to provision resources using `externalResources`, and prepares for addition of new provision providers, such as gcp, CNA, cloudflare, and more.
=> [terraform-resources] add support for external resources

reconcile/test/test_gabi_authorized_users.py, reconcile/test/test_instrumented_wrappers.py, reconcile/test/test_utils_mr_clusters_updates.py, reconcile/test/test_utils_oc.py, reconcile/utils/terraform_resource_spec.py
with a recent pylint update, certain checks have been removed and trying to disable them results in failed linter execution
this change removes those `disables`
=> remove unsupported pylint ignores

reconcile/queries.py, reconcile/service_dependencies.py, reconcile/test/test_utils_external_resources.py, reconcile/utils/external_resources.py
part of https://issues.redhat.com/browse/APPSRE-5711
following up on prep work in #2444
this PR (mostly) adds the `externalResources` section to queries. this "enhances" the integrations so they can work with both `terraformResources` and `externalResources`.
=> External resources enhancement

dev/run.sh, tools/app_interface_reporter.py
There have been schema changes which app-interface-reporter needs to be aligned with:
- `saas_file_v1` was removed. We do not have any deploy jobs in jenkins. A follow-up ticket should take care of getting state from tekton pipelines
- the `upstream` dict changed its structure
=> ASIC-238 align reporter with new schema

tools/qontract_cli.py
during a cluster provisioning, and before a cluster has AWS infrastructure access set up, this command will fail.
with this PR, such a cluster will be skipped.
=> [cli] get/clusters-egress-ips handle account without infra assume role

reconcile/openshift_network_policies.py
to create NetworkPolicies, we rely on a `name` label present on the namespace/project.
this label is added to specific projects (as can be seen in this example: https://github.com/openshift/managed-cluster-config/pull/374)
automatic labeling was added in Kubernetes 1.21: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#automatic-labelling
OpenShift version 4.8 uses Kubernetes 1.21: https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html
this PR changes the openshift-network-policies integration to create a NetworkPolicy using the new automatically added label instead of relying on a `name` label to exist.
=> [openshift-network-policies] use kubernetes.io/metadata.name instead of name

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-manager.yaml, reconcile/cli.py, reconcile/integrations_manager.py, reconcile/queries.py, reconcile/test/fixtures/helm/aws_account_shards.yml, reconcile/test/test_integrations_manager.py, reconcile/test/test_utils_helm.py, reconcile/utils/oc.py, reconcile/utils/runtime/__init__.py, reconcile/utils/runtime/meta.py
enable integration-manager to shard integrations based on a sharding strategy.
delegate the handling for shards to the `IntegrationShardManager` which knows how to react to different strategies and builds sharding specs for each integration.
a sharding spec is part of the generated `values` file within `integration_spec.shard_specs` which is passed to the helm chart.
a shard spec consists of the following fields:
* `shard_id`, `shards` - the backwards compatible fields for the `SHARD_ID` and `SHARDS` env vars, specifying which shard within a shard set a deployment will represent.
* `shard_name_suffix` - this i used to influence the `name` of the deployment/statefulset
* `extra_args` - contains the aggregation of an integrations global `extraArgs` and the shard specific extra args
this is …
=> [integration-manager] automatic integration sharding based on AWS accounts in app-interface

reconcile/integrations_manager.py
this can happen for integration of e2e tests and go integrations because currently metadata about supported args is read from cli.py click metadata
this would only affect e2e or go integrations wanting to use the `per-aws-account` sharding strategy
this change is a workaround and needs fixing once we figured out a way to provide the required metadata
fixes #2428
=> [integration-autoscaler] don't fail on missing integration metadata

reconcile/cli.py
to be sharded per aws account, an integration should expose a `--account-name` arg. this work was already done in #2176, and this is just exposing the argument for the cli.
=> enable terraform-users to be sharded per-aws-account

dockerfiles/hack/run-integration.py, helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager.yaml, reconcile/cli.py, reconcile/integrations_manager.py, reconcile/terraform_resources.py, reconcile/test/test_integrations_manager.py, reconcile/test/test_utils_helm.py, reconcile/utils/metrics.py
shard_id has been an integer to identify a bucket of workloads within a collection of shards. since a hashing strategy is used to distribute workload based on the number of buckets, shard_id does not necessarily represent a stable bucket of workload but needs the `shards` label along with it.
this change seeks to make shard_id a true identifier for a workload bucket by allowing it to be one of the following
* shard-nrOfShards, e.g. 2-18
* sharding key, e.g. an aws account
the first option will be enabled by standard sharding (`static` strategy) while the second one will be served by other sharding strategies like the `per-aws-account` strategy.
alerting rule grouping based on `integration` and `shard_id` will be unaffected by this change (maybe short hickups during an initial rollout). …
=> [integration-manager] shard_id metric label as identifier for workload buckets

reconcile/utils/ocm.py
This allows to update the cluster version only once all nodes are upgraded
=> use .version.raw_id for OSD cluster version

reconcile/utils/terrascript_aws_client.py
APPSRE-5533
New tentative after the revert of https://github.com/app-sre/qontract-reconcile/pull/2423.
The problem was that `data.aws_canonical_user_id("current")` was added only when `--account-name` was set and not for each account shard.
=> terraform-resources: set S3 bucket ACL for cloudfront logging

reconcile/queries.py, reconcile/service_dependencies.py, reconcile/terraform_resources.py, reconcile/test/fixtures/expiration/expiration_date_check.yml, reconcile/test/fixtures/gabi_authorized_users/apply.yml, reconcile/test/fixtures/openshift_resource/invalid_expiration_date.yml
part of https://issues.redhat.com/browse/APPSRE-5726
this is essentially the opposite of #2447
once all accounts in all app-interface instances were migrated to externalResources, we can deprecate them terraformResources (this PR).
=> deprecate terraformResources

pyproject.toml
When using VS code black plugin, because the filename is passed
explicitly, the file referred to in `extend-exclude` is not properly
excluded. Use `force-exclude` instead to say we really mean it.
see https://github.com/psf/black/issues/438
=> Used black's force-exclude instead of extend-exclude.

reconcile/test/test_terraform_resources.py, reconcile/test/test_utils_external_resources.py, reconcile/utils/external_resources.py
this PR will remove support for `terraformResources` from the inner logic. the inner logic itself is no longer used following #2465.
=> remove logic to handle terraform resources

reconcile/queries.py, reconcile/terraform_aws_route53.py
part of https://issues.redhat.com/browse/APPSRE-5885
fixes #2474
some dns zones are delegating to zones in other accounts, so `all_accounts` should really be all accounts.
=> [terraform-aws-route53] fix running per account

reconcile/openshift_upgrade_watcher.py, reconcile/test/test_openshift_upgrade_watcher.py
Ref APPSRE-5552
We currently only notify Slack when a cluster upgrade starts. This adds a notification when the cluster upgrade completes, based on the fact that OCM gets the `version.raw_id` updated only at that time (ref #2408, #2467).
Contrarily to #2452 , this implementation is done in `openshift_upgrade_watcher`, which is more coherent.
Notes:
- during the first production loop, we will get a notification for each cluster we currently run.
- Since we query ocm clusters, the following schemas need to be granted in the `openshift-upgrade-watcher` app-interface integration defintion (https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/41318)
```
- /aws/group-1.yml
- /aws/vpc-1.yml
- /openshift/cluster-addon-1.yml
```
=> Slack notification on cluster upgrade completion

reconcile/ecr_mirror.py, reconcile/gabi_authorized_users.py, reconcile/ocm_aws_infrastructure_access.py, reconcile/ocp_release_mirror.py, reconcile/osd_mirrors_data_updater.py, reconcile/sql_query.py, reconcile/terraform_aws_route53.py, reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py, reconcile/test/test_utils_external_resource_spec.py, reconcile/test/test_utils_external_resources.py, reconcile/test/test_utils_terraform_client.py, reconcile/utils/external_resource_spec.py, reconcile/utils/external_resources.py, reconcile/utils/terraform_client.py, reconcile/utils/terrascript_aws_client.py, tools/qontract_cli.py
following up on #2472, this PR consolidates the two approaches that were used for external resources - `dicts` and `ExternalResourceSpec` (previously called TerraformResourceSpec). it also replaces the use of `account` with `provisioner_name`, making things more generic.
review recommendations:
start from looking at the changes in `reconcile/utils/external_resource_spec.py` and `reconcile/utils/external_resources.py`.
these files hold the changes that are reflected in the rest of the files.
you can review commit by commit to see how each one is really not changing much. this whole PR is really a refactor, and should mostly not have any logic changes.
=> consolidate external resources and spec

reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py, reconcile/test/test_utils_terrascript_aws_client.py, reconcile/utils/terrascript_aws_client.py
the logic to collect external resource specs is duplicated in terraform-resources. this PR removes the duplication and adds resource specs into terrascript.
=> [terraform-resources] consolidate external resource specs into terrascript

reconcile/dyn_traffic_director.py, reconcile/test/test_utils_helpers.py, reconcile/utils/helpers.py, reconcile/utils/jjb_client.py, reconcile/utils/jump_host.py, reconcile/utils/unleash.py
our integrations attempt to log only things that are acted on. any logging from imported packages are attempted to be silenced.
this PR consolidates the logger toggling around the code base.
=> toggle logger

reconcile/ecr_mirror.py, reconcile/sql_query.py, reconcile/utils/terrascript_aws_client.py
this PR aims to replace the current arguments that are currently passed to terrascript populate method: resource, namespace_info (existing_secrets will be replaced in a different PR)
instead, we will pass the external resource spec, which will contain all the needed information.
=> [terrascript] use external resource spec in populate methods

reconcile/terraform_resources.py, reconcile/utils/terrascript_aws_client.py
follows up on #2481, where we removed the resource and namespace_info arguments.
in this PR, we remove the existing_secrets argument, and instead we rely on the external resource spec secret (which is now initialized earlier).
=> [terrascript] use external resource spec in populate methods #2

reconcile/queries.py, reconcile/sql_query.py
Depends on https://github.com/app-sre/qontract-schemas/pull/175
Part of [APPSRE-3787](https://issues.redhat.com/browse/APPSRE-3787), this MR adds new behavior to the SQL query feature in App Interface to delete CronJobs after they have been created in OpenShift by adding a `delete: true` flag to the SQL query schema. Meaning that tenants will now be able to delete those queries without manual AppSRE intervention required. Tested this on dashdotdb staging, details in linked Jira issue.
=> CronJob SQL Query Deletion - APPSRE-3787

reconcile/test/test_utils_password_validator.py, reconcile/utils/password_validator.py, reconcile/utils/terrascript_aws_client.py
All ES domains must have auth enabled. 
In the first step, this PR adds an `auth` feature for ES domains. This is fully backwards compatible.
Once this is merged, we start migrating existing ES domains to use the new `auth` feature. This migration work will be coordinated with each team individually.
When the migration is done, we will make the `auth` feature mandatory and remove backwards compatible code, which is also marked in this PR as `TODO`.
Corresponding schema change: https://github.com/app-sre/qontract-schemas/pull/170
=> APPSRE-3409 prepare migration towards ES auth

reconcile/sql_query.py
related to https://issues.redhat.com/browse/APPSRE-3787
follows up on #2494
since the `delete` key is only added if `delete` is set to true: https://github.com/app-sre/qontract-reconcile/blob/28957384ffaa6a0d98124442d012b1bf349cffda/reconcile/sql_query.py#L269
this condition will encounter a KeyError for every CronJob that does not have `delete` set to true: https://github.com/app-sre/qontract-reconcile/blob/28957384ffaa6a0d98124442d012b1bf349cffda/reconcile/sql_query.py#L473
this is causing the sql-query integration to endlessly apply.
=> [sql-query] cronjob delete keyerror fix

reconcile/test/test_openshift_base.py
when adding `py310` to tox.ini, these are the only errors it returns.
this is related to https://github.com/python/cpython/pull/23737
does this mean we are python 3.10 compatible?
=> make tox happy about py310

reconcile/utils/terrascript_aws_client.py
This MR corrects a bug with generating the lambda resource for rosa-authenticator.
=> Force terrascript to calculate lambda_iam_role_resource.arn

reconcile/utils/terrascript_aws_client.py
This MR fixes a bug with the sms role arn - fixing the reference to point to the correct iam resource.
=> Use correct sms role for cognito user pool [rosa-authenticator]

reconcile/cli.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py
implement account filtering capabilities for terraform-vpc-peerings to allow account based sharding by integration-manager
the relevant account for filtering is the acceptors account
* for cluster to cluster VPC peering, the infrastructure management account on the acceptor cluster is used for filtering
* for cluster to account (normal peerings and mesh peering), the account plays the role of the acceptor and is used for filtering
Ref: https://issues.redhat.com/browse/APPSRE-5917
=> [terraform-vpc-peerings] account filter capability

reconcile/ocm/types.py
When using Pydantic, a Field alias will be used to override the name of
a field when it's initialized. In order to use both the field name and
alias, which is useful when dealing with snake case (Python) and camel
case (JSON), the allow_population_by_field_name config can be used.
```
[2022-07-01 15:45:33] [INFO] [ocm_clusters.py:_app_interface_updates_mr:213] - [<cluster_name>] desired root key consoleUrl will be updated automatically with value None
[2022-07-01 15:45:33] [INFO] [ocm_clusters.py:_app_interface_updates_mr:213] - [<cluster_name>] desired root key serverUrl will be updated automatically with value None
```
```
[2022-07-01 15:46:29] [INFO] [ocm_clusters.py:_app_interface_updates_mr:213] - [<cluster_name>] desired root key consoleUrl will be updated automatically with value …
```
=> Fix cases where console_url and server_url were missing

reconcile/utils/terrascript_aws_client.py
This will hopefully feed these variables to terraform in a format that it is perhaps strictly expecting.
This is very similar to https://github.com/app-sre/qontract-reconcile/pull/2519, but will hopefully do as actually intended.
=> (fedramp) rosa-authenticator: fix http_method references

reconcile/queries.py, reconcile/saas_file_owners.py
part of https://issues.redhat.com/browse/APPSRE-5940
this change is required to support external flows to app-interface, and allow teams to use their own bots to submit saas-file-update MRs, and to be able to `/lgtm` them.
tested in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/42134
=> add bots to be saas file owners

reconcile/saas_file_owners.py, reconcile/utils/gitlab_api.py
part of https://issues.redhat.com/browse/APPSRE-5940
allow creating a MR, including a `/lgtm` in the MR description, which will be considered as a `/lgtm` comment.
this will be mostly used for creating promotion MRs that will be automatically merged. the main use case is usage by bots (following up on #2539).
=> [saas-file-owners] consider MR description as comment

reconcile/saas_file_owners.py, reconcile/utils/gitlab_api.py
related to https://issues.redhat.com/browse/APPSRE-3029
fixes a bug that was introduced in #1404
this bug shows itself when there are multiple promotions within the same saas file to different environments.
since we use `changed_paths` and update it while we iterate over the `diffs`, if there are 2 changes to the same saas file to different environments - they are considered 2 differents `diffs`, but only one changed path. when we remove this path from `changed_paths`, and get to the 2nd iteration - the integration is mistaken to think it is not a part of the MR, but it is.
the outcome of this bug is not harmful at all - only logging a warning.
it is, however, very confusing.
to resolve it, we will keep the current behavior and usage of `changed_paths` exactly as is, but when checking if …
=> [saas-file-owners] fix diff not found in changed paths bug

reconcile/ocm_upgrade_scheduler.py
This avoids a hard failure of the integration due to an OCM 400:
```
{
"kind": "Error",
"id": "400",
"href": "/api/clusters_mgmt/v1/errors/400",
"code": "CLUSTERS-MGMT-400",
"reason": "Upgrade policy 'xxx-xxx' is in 'started' state and cannot be updated",
"operation_id": "xxx-xxx"
}
```
=> print warning when currently upgrading to a blocked version

reconcile/template_tester.py
Currently, the `template-tester` will output the full content of both the rendered and the expected resources, leaving it to the user to find differences
This changes it so that using `difflib` we only show the differences in a familiar unified diff output
Sample of current output:
```
expected:
some: var
another:
thing: inside
thang: again
the: end
rendered:
some: var
another:
thing: inside
new: thing
thang: again
the: end
```
Output after this change
```
--- expected
+++ rendered
@@ -2,5 +2,6 @@
some: var
another:
thing: inside
+  new: thing
thang: again
the: end
```
=> template-renderer: show diff of rendered and expected outputs

reconcile/utils/terrascript_aws_client.py
Somehow we missed provisioning this resource in our code: https://gitlab.redhat-osd.local/service/terraform-ocm-cognito-api-gw/-/blob/efaf6e75e080a71e439fb8f7c06e16aaf6da124d/cognito.tf#L279-283
This PR fixes that.
Basically, this just adds the redhat logo to the cognito signin page.
The redhat-logo PNG file is pulled from the "cognito_callback_bucket".
=> (fedramp) rosa: create userpool_ui resource

reconcile/github_repo_permissions_validator.py, reconcile/jenkins_job_builder.py, reconcile/jenkins_job_cleaner.py, reconcile/jenkins_webhooks.py, reconcile/queries.py, reconcile/saas_file_validator.py, reconcile/utils/aws_api.py, reconcile/utils/jjb_client.py, reconcile/utils/state.py, tools/app_interface_reporter.py, tools/qontract_cli.py
the jenkins-job-builder integration declares a lot more schemas than it actually queries, because it uses some generic app-interface-settings and aws-account queries that are too broad.
this change introduces a `get_secret_reader_settings()` query that fetches minimal information for secret reader initialization. also the `State` can be initialized with a new function `init_state` that requires minimal data about the involved account.
as a result, a lot of schemas can be removed from the jenkins-jobs-builders `integration-1.schemas` list in app-interface, which has positive side effects for PR checks. also the `integration-1.pr_check.run_for_valid_saas_file_changes` option can be removed for this integration, since the saas-file-2 schema is not required to be in the schema list anymore. …
=> [jenkins-job-builder] reduce required schemas for integration run

reconcile/github_org.py, reconcile/github_repo_invites.py, reconcile/github_repo_permissions_validator.py, reconcile/queries.py
the motivation for this change is the same as for https://github.com/app-sre/qontract-reconcile/pull/2547, namely getting rid of as many required schemas as possible so these integrations run less frequently during PR checks. the most important change though is the removal of the saas-file-2 schema. as a result the `run_for_valid_saas_file_changes` flag in `integration-1.pr_check` might not be relevant anymore, reducing complexity in our CI pipeline.
the schema reduction is mostly driven by special queries for github repos and secret reader settings
the remaining schemas for github-repo-permissions-validdator are
```
schemas:
- /app-sre/integration-1.yml
- /app-interface/app-interface-settings-1.yml # for secret reader
- /dependencies/jenkins-config-1.yml # for pr check jobs
- …
```
=> reduce schemas for gh-repo-permissions-validdator and gh-repo-invites

reconcile/utils/oc.py
```
$ oc delete deploy busybox --cascade=false
warning: --cascade=false is deprecated (boolean value) and can be replaced with --cascade=orphan.
```
=> use cascade orphan

tools/qontract_cli.py
The command will show all the alerts in the file along with its
receivers. It will make easier to check how a certain change in routing
tree affects all the alerts in a rules file.
Example of the new behaviour:
```
qontract-cli --config config.local.toml alert-to-receiver -s config \
crcp01ue1 \
openshift-customer-monitoring \
/insights-prod/ros-prod/ros.prometheusrules.yml 
App-insights-ros-backend-api-service-In-ros-prod-Absent|slack-team-consoledot-alert
App-insights-ros-backend-processor-service-In-ros-prod-Absent|slack-team-consoledot-alert
ROSHttp5xx|slack-team-consoledot-alert
```
Output has also changed to always print the alert name. This will also clarify the case in which we have multiple alerts of the same name in a rules file.
Part of APPSRE-5808
Signed-off-by: Rafa Porres …
=> Make alert name optional in alert-to-receiver

reconcile/queries.py, reconcile/terraform_aws_route53.py, reconcile/terraform_resources.py, reconcile/terraform_tgw_attachments.py, reconcile/terraform_users.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_utils_terrascript_aws_client.py, reconcile/test/test_wrong_region.py, reconcile/utils/terrascript_aws_client.py
We have implemented a new schema change that displays terraform state information through an account file
Schema setup for a file tf-state-test.yml:
```
---
$schema: /dependencies/terraform-state-1.yml
provider: s3
bucket: someBucket
region: someRegion
integrations:
- integration: terraform-resources
key:  qontract-reconcile.tfstate
- integration: terraform-tgw-attachements
key: qontract-reconcile-tgw-attachments.tfstate
```
AWS account file call:
```
terraformState:
$ref: /aws/app-sre-stage/tf-state-test.yml
```
This MR will implement logic that will check if the new schema changes are present within app-interface and if it is, it will execute logic to retrieve bucket information the new way (looking within app-interface and extracting the information) or the current way (looking within …
=> Logic to retrieve bucket information from new terraform state schema

reconcile/saas_file_owners.py
following #2540 where we started treating the MR description as a comment, this MR allows for the MR body to be null, to avoid crashing on such a scenario.
=> [saas-file-owners] handle null comment body

reconcile/terraform_resources.py
Enable cluster-admin token for terraform-resources inteagration. There are some cases where this integration need cluster-admin access. 
e.g: `aws-iam-service-account` within a `openshift-*` namespace needs cluster-admin permissions to populate the secret.
=> Enable clusterAdmin attribute for terraform-resources integration

reconcile/jenkins_job_builds_cleaner.py, reconcile/jenkins_job_cleaner.py, reconcile/jenkins_plugins.py, reconcile/jenkins_roles.py, reconcile/utils/jenkins_api.py, reconcile/utils/terrascript_aws_client.py
followup to https://github.com/app-sre/qontract-reconcile/pull/2558
schema reduction for `jenkins-job-builds-cleaner`, `jenkins-job-cleaner` and `jenkins-roles` was accomplished with narrow queries for SecretReader and JenkinsAPI instantiation
remaining schemas for jenkins-job-builds-cleaner
```
schemas:
- /app-sre/integration-1.yml
- /app-interface/app-interface-settings-1.yml # for secret reader
- /dependencies/jenkins-instance-1.yml # to find jobs
- /dependencies/jenkins-config-1.yml # to find jobs
```
remaining schemas for jenkins-job-cleaner
```
schemas:
- /app-sre/integration-1.yml
- /app-interface/app-interface-settings-1.yml # for secret reader
- /dependencies/jenkins-instance-1.yml # for jobs
- /dependencies/jenkins-config-1.yml # for jobs
```
remaining schemas for jenkins-roles …
=> reduce schemas for jenkins-job-builds-cleaner/cleaner and jenkins-roles

reconcile/gitlab_mr_sqs_consumer.py, reconcile/jenkins_webhooks.py, reconcile/jira_watcher.py, reconcile/ldap_users.py, reconcile/mr_client_gateway.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, reconcile/slack_base.py, reconcile/slack_cluster_usergroups.py, reconcile/slack_usergroups.py, reconcile/test/test_ldap_users.py, reconcile/test/test_slack_base.py, reconcile/test/test_slack_usergroups.py, reconcile/test/test_utils_slack_api.py, reconcile/unleash_watcher.py, reconcile/utils/gitlab_api.py, reconcile/utils/mr/README.md, reconcile/utils/slack_api.py, reconcile/utils/sqs_gateway.py
followup to https://github.com/app-sre/qontract-reconcile/pull/2560
schema reduction for jenkins-webhooks, ldap-users, gitlab-mr-sqs-consumer and slack-cluster-user-groups was accomplished with narrow queries for SecretReader, roles and slack permissions. most importantly none of these require the saas-2 schema anymore and that brings us closer to depcrecate `run_for_valid_saas_files` flag in the integration-1 schema.
remaining schemas for jenkins-webhooks
```
schemas:
- /app-sre/integration-1.yml
- /app-interface/app-interface-settings-1.yml # for secret reader
- /dependencies/gitlab-instance-1.yml # find projects to add webhooks to
- /dependencies/jenkins-config-1.yml # the jenkins config ...
- /dependencies/jenkins-instance-1.yml # ... and instances to add webhooks to
```
remaining …
=> reduce schemas for integrations

.coveragerc, reconcile/cli.py
Every import in cli.py has to complete before any integration begins
running. This is because import statements are executed when the cli
module is imported, which happens as a result of console_scripts in
setup.py. Currently, memory usage can reach ~120MB before an integration
ever starts running. This change scopes the imports inside the integration
command functions so that the import only happens when the function
is executed (we only expect to execute a single integration function per
container).
There are probably more elegant ways to fix this issue, but for now
this should work and saves us 50MB or more of imports for many
integrations that don't require the importing of the majority of
qontract-reconcile modules.
Here are some rough estimates of how much memory usage we'll save …
=> Locally scope cli.py imports to save memory usage

reconcile/utils/terrascript_aws_client.py
This MR adds support for the "website" and "request_payer" parameters for the S3 provider in terrascrit_aws_client.py.
This property is passed to the provider via a customized defaults file, but is not assigned because of specific property callouts in the S3 provider pattern.
=> Add website values support for s3 provider [rosa-authenticator]

requirements/requirements-type.txt
boto3-stubs 1.24.30 was released a few hours ago and causing mypy tests to fail with the following
```
reconcile/utils/aws_api.py:11: error: Module "boto3" has no attribute "Session"; maybe "session"?  [attr-defined]
```
This pins boto3-stubs to 1.24.29 for now
=> pin boto3-stubs to 1.24.29

reconcile/gitlab_members.py, reconcile/slack_usergroups.py
depends on https://github.com/app-sre/qontract-schemas/pull/191
with this PR, gitlab-members is able to add users to gitlab groups based on a pagerduty schedule/escalation policy.
this means that tenants will be able to ping @app-sre-ic on merge requests, just like they ping @app-sre-ic on slack.
=> add pagerduty as a source of truth for gitlab group membership

reconcile/utils/terrascript_aws_client.py
This MR updates the trigger strategy for api_gateway_deployment to play nicer with AWS and our reconciliation patterns.
=> Rework  ROSA triggers for single reconcile deploy

reconcile/jenkins_job_builder.py, reconcile/utils/jjb_client.py
the jenkins job builder integration loads config_path resources one by one which results in slower reconciliation runs.
to improve that, we use the resource reference resolver feature from qontract-server introduced with https://github.com/app-sre/qontract-server/pull/147
while the impact on integration speed is not that hight for jenkins job builder, the resource resolution capability can be easily showcased on this integration so others like terraform-resources have a working example
part of https://issues.redhat.com/browse/APPSRE-6003
depends on schema change https://github.com/app-sre/qontract-schemas/pull/190
=> [jjb] config_path loading via resource resolver

reconcile/openshift_base.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py
Procedure:
* openshift_base.apply handles FieldIsImmutableError for Deployments
* Checks that the update strategy is RollingUpdate for the current running Deployment; otherwise, reraise FieldIsImmutableError
* Remove old Deployments without removing the last ReplicaSet and Pods
* Apply new Deployment
* Adapt ownership of old ReplicaSet, it'll be removed automatically afterward when the new Deployment is ready
See APPSRE-5728
=> Support updates to a Deployment's label selector.

tools/qontract_cli.py
This command was before in app-interface but finally it got impossible due to
the amount of logic that we have in the templates, so now it's a
qontract-cli command.
```
$ qontract-cli --config config.local.toml run-prometheus-test --help
Usage: qontract-cli run-prometheus-test [OPTIONS] PATH CLUSTER
Run prometheus tests in PATH loading associated rules from CLUSTER.
Options:
-n, --namespace TEXT            Cluster namespace where the rules are
deployed. It defaults to openshift-customer-
monitoring.
-s, --secret-reader [config|vault]
Location to read secrets.
--help                          Show this message and exit.
```
part of [APPSRE-5843](https://issues.redhat.com/browse/APPSRE-5843)
=> CLI command to run prometheus tests locally

reconcile/utils/terrascript_aws_client.py
I am trying to update terraform provider for insights-fedramp-stage but found tf-r has been disabled. Someone manually added a log_publishing_options to its kibana-elasticsearch. Due to a [aws API bug ](https://github.com/hashicorp/terraform-provider-aws/issues/5752), terraform can not remove it once it gets added. So I need to persist log_publishing_options in app-interface to prevent it from [continuously updating](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/32936) and enable tf-r on that account. However, in our code we get region info for log_groups_policy from the openshift cluster spec, while crcgovs02ue1 does not manage by us and we don't have spec info for that cluster. So without this change, I can not persist log_publishing_options in …
=> get region from resources instead of openshift cluster

reconcile/utils/terrascript_aws_client.py
This MR adds cloudwatch logging support to API gateway for rosa-authenticator.
=> Add cloudwatch support to api-gateway 

reconcile/utils/terrascript_aws_client.py
Follow up of https://github.com/app-sre/qontract-reconcile/pull/2588
Due to a [aws API bug ](https://github.com/hashicorp/terraform-provider-aws/issues/5752), terraform can not remove it once it gets added.
=> remove es log publishing explicitly with enabled = false

reconcile/saas_file_owners.py
part of https://issues.redhat.com/browse/APPSRE-6028
this PR introduces support for the `saas-file-owners` integration such that tenants can self-service valid saas file changes, even if those changes happen in a referenced saas file target, rather then an inlined one (https://github.com/app-sre/qontract-schemas/pull/200).
=> [saas-file-owners] support referenced targets

reconcile/test/test_unleash.py, reconcile/utils/oc.py, reconcile/utils/unleash.py
Keep the client, do not create one per Request. This reduces the number
of requests to unleash. This reduces likelyhood of DNS errors due to
failed lookups during cluster upgrades.
Related ticket: APPSRE-5719
=> Refactor unleash implementation

reconcile/openshift_tekton_resources.py
We want to remove the managedResourceNames and we need that every shard
sees full namespaces or different shards will try to remove resources
that are not part of its namespace (dynamically created) definition.
part of APPSRE-6031.
=> Different shard mechanism for tekton resources

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py, reconcile/utils/openshift_resource.py
depends on #2260
this PR adds logic to validate resources to be deployed before they are actually deployed.
this allows us to gradually add checks as we discover use cases that can be validated pre-deployment.
this PR adds the first condition - validate that all Secrets[1] used by a Deployment[2] exist[3] along with the required keys[4].
[1] or ConfigMaps
[2] or DeploymentConfig
[3] or will exist
[4] where applicable
this will reduce load from AppSRE by automating a pretty routine check, and will help onboarding tenants by validating that what they are trying to deploy makes sense.
in addition, we see multiple MRs to app-interface which promote a saas file target together with a secret from vault. as these secrets need to be updated in advance to contain any new keys, this PR will force a …
=> [openshift-saas-deploy] validate planned data

reconcile/openshift_base.py
fixes #2261
```
File "/usr/local/bin/qontract-reconcile", line 8, in <module>
sys.exit(integration())
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File …
```
=> make resource end result consistent

reconcile/openshift_base.py, reconcile/utils/oc.py
follows up on #2261
dependent resources can be defined as optional: https://kubernetes.io/docs/concepts/configuration/secret/#restriction-secret-must-exist
in such cases, we don't want to fail a deployment.
=> [openshift-saas-deploy] consider planned data optional resources

reconcile/terraform_resources.py, reconcile/utils/terrascript_aws_client.py
For terraform-resources integration,
* Add support for creating SNS topics
* Add support for creating  RDS event subscription to SNS topics
We want to provide tenants the ability to be able subscribe to email notifications about their RDS instances's activity. 
Design doc [here](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/rds-upgrades-and-maintenance.md#database-maintenance-notifications).
* Running terraform-resources integration through dry-run mode and check the output consistent with the yml defined in open source App Interface.
* Running the integration without dry-run mode against ter-int-dev AWS account and was able to see SNS topics and RDS event subscriptions created( and deleted) as intended. This includes multiple subscriptions, …
=> Add support for creating SNS topic and RDS event notification

build_deploy.sh
if tests are failing, we shouldn't proceed to build and push an image.
this is a safety net for merges with failing tests (like #2626 :facepalm:)
=> run make test as part of a push

reconcile/utils/terrascript_aws_client.py
We have an open alert for this. Revert.
```
Error: Error attaching policy {aws_iam_policy.ocm-sts-access.arn} to IAM User {ocm-sts-access}: ValidationError: The specified value for userName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-
```
This reverts commit f1df0cd2ef28a53f9b7f0b15592450a3dcea11f4.
cc @esron
=> Revert "APPSRE-4543 - Add managed user policies (#2625)"

reconcile/utils/gitlab_api.py, tools/qontract_cli.py
once someone from AppSRE assigns a MR, it should be removed from the IC review queue.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44155
=> [qontract-cli/app-interface-review-queue] filter out MRs assigned by app-sre

reconcile/test/test_unleash.py, reconcile/utils/oc.py, reconcile/utils/unleash.py
Standard Strategies used in the last try, see https://github.com/app-sre/qontract-reconcile/pull/2616 returned wrong results.
Added `DisableNativeClientStrategy`, which returns True, unless a cluster is added to the cluster_name list of the feature.  If the feature is disabled it is also set to false (see https://github.com/Unleash/unleash-client-python/blob/main/UnleashClient/features/Feature.py#L64). Additionally, I did add some tests, that use httpretty to ensure this behavior.
=> Unleash client refactor

reconcile/slack_usergroups.py
try and avoid errors such as:
```
Error running qontract-reconcile
File "/run-integration.py", line 162, in main
command.invoke(ctx)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/reconcile/cli.py", line 736, in slack_usergroups …
```
=> [slack-usergroups] retry harder to get slack usernames from owners

reconcile/utils/gitlab_api.py
without this, some groups may not be returned, and we will not be able to manage them via app-interface.
=> [gitlab-api] get all groups

reconcile/test/test_utils_jjb_client.py, reconcile/utils/jjb_client.py, reconcile/utils/saasherder.py, tools/qontract_cli.py
Refactor the review-queue command to support other app-interface instances (e.g. fedramp or app-interface-dev-data) hosted on GitLab or GitHub.
APPSRE-6086
=> qontract-cli - review-queue: support for other app-interface instances

reconcile/queries.py, reconcile/utils/saasherder.py
depends on https://github.com/app-sre/qontract-schemas/pull/210
required for #2646
this PR introduces logic to validate that secret parameter paths are allowed in a list: `allowedSecretParamterPaths`.
this is to allow full self-service over secretParameters, without allowing usage of unpermitted secrets.
=> [saas-file-validator] validate allowed secret parameter paths

reconcile/saas_file_owners.py
a very late follow up on #2247
with this change, saas file owners will be able to self-service changes in `secretParameters` sections.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44240
to restrict users from using any secret path they want: #2648
=> [saas-file-owners] add control over secretParameters

setup.py
This version of sretoolbox properly compares simple single arch images
with multiarch images returning `False` instead of throwing an exception.
This will effectively make that every deep sync we will synchronize
these images although we may have the corresponding single arch image in
Quay. Unfortunately, sretoolbox does not yet support comparations such
as:
```
single_image in multi_image
````
so this is the best we can do for the moment.
xref: https://github.com/app-sre/sretoolbox/pull/72
part of https://issues.redhat.com/browse/APPSRE-6084
=> Bump sretoolbox to 1.4.0

reconcile/gitlab_housekeeping.py, reconcile/queries.py
depends on https://github.com/app-sre/qontract-schemas/pull/212
example usage in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44367
with this PR, if a user adds a label but they are not within the allowed labels roles, the label will be removed. this is to handle users with Developer access adding labels to MRs in gitlab.
=> [gitlab-housekeeping] remove labels when not added by allowed users

reconcile/gitlab_housekeeping.py
fixes #2653
the bot should obviously be able to add labels.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44474
=> allow our bot to add labels

reconcile/gitlab_housekeeping.py
we should call this "python under pressure". fixes #2660
=> come on bot!!!

reconcile/utils/gitlab_api.py
example where this is failing: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/43616
=> if MR is not assigned it can not be last assigned

grafana-dashboards/grafana-dashboard-integrations.configmap.yaml
[APPSRE-5835](https://issues.redhat.com/browse/APPSRE-5835)
* Add SQS MR queue metrics.
* Some other parameters have been updated since we updated our Grafana instance. I was able to successfully import the JSON into Grafana staging.
=> MR Queue Metrics

reconcile/openshift_base.py
ConfigMap or Secret can exist without a `data` field.
This changes handles cases when `data` is not present in the resource
=> [openshift_base] handle resources without data when validating

reconcile/utils/saasherder.py
fix the url from logs to something that is a valid link.
we've seen tenants assuming that the broken link means a problem with the integration, so let's at least get that out of the way.
=> [saasherder] fix url paths in error messages

reconcile/gitlab_housekeeping.py
MRs that are created with a `bot/automerge` label are automated, and are not looked at after their creation.
some of these MRs get to a merge conflict situation and can not be merged.
let's close them automatically!
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44593
=> [gitlab-housekeeping] automatically close auto merge MRs that cannot be merged

reconcile/quay_mirror.py
sretoolbox currently doesn't handle well the comparation of OCI images
with content-type 'application/vnd.oci.image.index.v1+json'. These are
manifest list type of images that don't have `mediaType` in their
manifest so sretoolbox logic fails.
The real fix is in sretoolbox.container.image module, but that's going
to take a bit longer since we will need to change how image comparation
is done as it will need to inspect the manifest headers instead of the
manifest itself.
In the meantime, we have this to avoid the integration to crash.
=> Temp fix to handle the comparation of OCI images

reconcile/openshift_base.py
it is possible that a resource being deployed references a Secret that originates from a Service object's `serving-cert-secret-name` annotation. When that Service resource is initially deployed alongside the using resource, the secret is not present and thus we have to look for such a service and annotation
As such we iterate through all the Services that are being deployed along with the saas-file objects (same
cluster, same namespace) and we check if such an annotation exists and has the same name as the using resource
I have tested this locally and it fixes the issue that prompted this change: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44658
=> [saas-file-validator] consider Services's serving-cert secrets

reconcile/gql_queries/introspection.json, reconcile/gql_queries/service_dependencies/service_dependencies.gql, reconcile/gql_queries/service_dependencies/service_dependencies.py, reconcile/service_dependencies.py
If a saas file has an upstream dependency to ci-int/ci-ext, then it should be verified by `service_dependencies`.
=> APPSRE-6103 check saas upstream deps present

reconcile/utils/jira_client.py
not able to reproduce this locally, but we need CI passing.
```
reconcile/utils/jira_client.py:37: error: Argument 1 to "extend" of "list" has incompatible type "Union[Dict[str, Any], ResultList[Issue]]"; expected "Iterable[Dict[str, Any]]"  [arg-type]
```
=> jira-client ignore arg-type

tox.ini
Fix
```
generate run-test: commands[2] | git diff --exit-code
WARNING: test command found but not installed in testenv
cmd: /usr/bin/git
env: /package/.tox/generate
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.
DEPRECATION WARNING: this will be an error in tox 4 and above!
```
--> git must be marked as external dependency that is not managed by tox.
=> mark git as external tox dep

.coveragerc
redo #2297, which was reverted in #2573
we are currently at 34.19% coverage.
=> Bump minimum coverage to 34%

reconcile/utils/jira_client.py
The `jira` module had a wrong type hint which was recently fixed https://github.com/pycontribs/jira/commit/cc2508485c12232a4a9c4a56ee74175ed818ee20
Our current logic expects a `ResultList` to be returned.
This PR ensures that only `ResultList` is processed and occurrences of `Dict` log a warning.
**Local Test on Prod Data**
```
qontract-reconcile_1  | [2022-08-08 10:57:57] [INFO] [gql.py:init_from_config:250] - using gql endpoint http://qontract-server:4000/graphqlsha/eb59c0d13fd7232954c7aa3eb3fd74509a9bece78a486261f9b49864cf669578
qontract-reconcile_1  | [2022-08-08 10:58:01] [INFO] [jira_watcher.py:act:84] - https://issues.redhat.com/browse/ASIC-273 ([FIRING:1] QontractReconcileIntegrationStuck2hours app-sre-prod-01 app-interface) status change: Done -> To Do
qontract-reconcile_1  | …
```
=> Properly handle return type from jira_client

reconcile/sql_query.py
With the default limits from app interface the ratio between the memory request and the limit should be
4 or less. With request_mem at 64Mi the ratio is 8, so in some namespaces, this leads to errors
https://coreos.slack.com/archives/CCRND57FW/p1659958449416839
=> Fix memory requests for SQL jobs / cronJobs

reconcile/openshift_base.py
to prevent cases of two saas files fighting over the same resources -
if this is a saas file (caller) and it's not a take over, error out when checking a current item that is also desired.
related to https://issues.redhat.com/browse/OHSS-14340
=> openshift realize data error when caller is different from resource caller and this is not a take over

reconcile/cli.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_github_org.py, reconcile/test/test_quay_membership.py, reconcile/test/test_terraform_vpc_peerings.py, reconcile/utils/gql.py, setup.cfg, setup.py
introduce an early exit run mode for integrations during dry-runs that checks if the desired state has changed between two bundles. if no change in desired state can be found, the integration exits early and saves time and resources.
if a cli flag `--early-exit-compare-sha` provides a bundle sha, integrations supporting early exit will fetch the desired state from the comparison and the current bundle and compare them. if no difference an be found, the integration exits early.
this early exit feature is supposed to improve speed for PR checks. early exit will only be considered if the integration has been started in dry-run mode.
an integration supports early exit, if the integration module provides a function
```
def early_exit_desired_state(*args, **kwargs) -> dict[str, Any]
```
it is …
=> [pr-check] early exit for integration dry-runs when no change in desired state

Makefile
qenerate: create `__init__.py` files after qgl classes generation to fix mypy errors
APPSRE-6113
Ref: https://github.com/app-sre/qenerate/pull/27
=> qenerate: create __init__.py files after qgl classes generation to fix mypy errors

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py
following up on #2694
apparently, there are many resources with a stale caller annotation. until the above PR, it was fine. now pipelines are failing.
the use cases we've seen so far are related to saas files being renamed.
so this PR is really an enhancement to allow renaming saas files.
occurrences:
- https://coreos.slack.com/archives/CCRND57FW/p1660201791354399
- https://coreos.slack.com/archives/C01V4S8GXPD/p1660221678123869
current workaround:
manually update the caller annotation on a resource that is causing pipelines to fail to the current name of the saas file (make sure the current value no longer exist).
=> [openshift-saas-deploy] take ownership of resources with missing caller

reconcile/gitlab_housekeeping.py
when listing MRs, some come back with `merge_status: unchcked`. calling the merge request endpoint gets this information.
follows up on #2673
ref: https://docs.gitlab.com/ee/api/merge_requests.html#merge-requests-list-response-notes
=> gitlab-housekeeping if MR status is unchcked for automerge - check it harder

reconcile/quay_mirror.py
based on #2672
following #2700, quay-mirror now fails when it attempts to mirror a repo from docker hub publicly. this failure will happen when the integration runs.
this integration was disabled from running on pr-checks in the commercial app-interface in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/21108, to remediate extensive calls to docker hub.
this means that MRs with public mirroring may be merged, and only later quay-mirror will start failing. we need to catch these cases in pr-check.
at the same time, running quay-mirror on pr-check is time consuming. the integration takes a lot of time to run. if only there was a way to run this integration only when relevant content is being changed... oh, wait! early exit!
this PR implements early exit for quay-mirror, …
=> [quay-mirror] early exit

reconcile/slack_usergroups.py
some integrations are "dynamic", such that they respond to changes that happen outside of app-interface.
for example, ocm-upgrade-scheduler decides on its own when to upgrade a cluster.
some integrations are "static", such that they only respond to changes that happen within app-interface.
for example, openshift-network-policies.
i suppose that a "dynamic" integration has other sources of truth except for app-interface.
slack-usergroup is somewhat "hybrid". it reconciles based on pagerduty schedules (dynamic) and also based on user-role-permission (static).
when running in dry-run, it means we are running within a MR. slack-usergroups should only run within a MR if that MR is changing data that is more "static". for example, when we see output from slack-usergroups within a MR that says …
=> [slack-usergroups] early exit

reconcile/test/test_utils_terraform.py, reconcile/test/test_utils_terrascript_aws_client.py, reconcile/utils/terraform/__init__.py, reconcile/utils/terrascript_aws_client.py
Small change to extract the helper method `safe_resource_id` into `reconcile.utils.terraform` as suggested here https://github.com/app-sre/qontract-reconcile/pull/2691#discussion_r945878684
PTAL @bhushanthakur93
=> extract safe_resource_id helper method to reconcile.utils.terraform

reconcile/terraform_aws_route53.py
early exit criteria is a change in the zones.
=> [terraform-aws-route53] early exit

reconcile/openshift_routes.py
the desired state for routes is captured within namespaces and referenced resources.
there is also a part if vault (TLS), but in case the vault path/version does not change, we can safely ignore it.
using `fetch_provider_resource` fetches the resource, and is really the only relevant part of `fetch_provider_route`: https://github.com/app-sre/qontract-reconcile/blob/af0a7fcdf102686075bc79450e0fd73710c1db33/reconcile/openshift_resources_base.py#L441
the rest is validations and adding tls data from vault.
depends on https://github.com/app-sre/qontract-reconcile/pull/2706
=> [openshift-routes] early exit

reconcile/prometheus_rules_tester.py
State changes from this integration will come from rules changing
(either directly or via jinja parameters) or tests themselves changing.
This will certainly save some time, but not as much as we would like
since `get_prometheus_tests` is quite slow.
I will come back to the effort of refactoring the integration, or at
least the part that deals with fetching the prometheus rules.
=> Add early exit support to prometheus-rules-tester

reconcile/utils/terrascript_aws_client.py
AWS default volume_type for es has changed to gp3 while terraform aws provider 3.75.2 does not support gp3.
Making gp2 as our default volume_type 
Depends on https://github.com/app-sre/qontract-schemas/pull/223
=> set default es volume_type to gp2

reconcile/terraform_resources.py
the desired state is represented by:
- aws accounts
- namespaces with external resources
- resources referenced from defaults path (or parameter_group for rds).
with no yaml loading, an early exit takes.................. 6 seconds!
=> [terraform-resources] early exit

reconcile/sentry_config.py
as dirty as possible. we need all the query results.
=> [sentry-config] early exit

reconcile/openshift_resources.py
part of https://issues.redhat.com/browse/APPSRE-6098
fixes #2711
monkey patching is causing a faulty behavior in case early exit determined a full dry-run is needed.
this PR makes the monkey patching use a context manager, to restore the previous functions.
=> [openshift-resources] early exit monkey patch to context manager

reconcile/gql_queries/introspection.json, reconcile/gql_queries/quay_membership/quay_membership.py, reconcile/gql_queries/service_dependencies/service_dependencies.py, reconcile/gql_queries/vpc_peerings_validator/vpc_peerings_validator.py, reconcile/quay_membership.py, reconcile/service_dependencies.py, reconcile/utils/helpers.py, reconcile/vpc_peerings_validator.py, requirements/requirements-type.txt
qenerate received an [update](https://github.com/app-sre/qenerate/pull/34) which aligns it closer to the GQL standard.
Currently, our GQL schema allows null elements in lists in many places. Sadly, this results in more `Optional` fields and more null checks in the code.
Note, that in order to avoid these `Optional`s, we must adjust our GQL schema properly to enforce `NonNull` fields in lists (see https://issues.redhat.com/browse/APPSRE-6153).
**Validation**
Ran integrations locally in dry-run mode
=> APPSRE-5972 obey to default GQL nullable standard

reconcile/gitlab_housekeeping.py, reconcile/utils/gitlab_api.py
=> gitlab-housingkeeping: fix retrieval of mr label events

reconcile/gitlab_housekeeping.py
Sometimes the label attribute is empty but shouldn't. Try it again by fetching the MR separately
similar to https://github.com/app-sre/qontract-reconcile/pull/2699
=> gitlab-housekeeping: harder label retrieval

reconcile/cli.py
the current way to find out if the desired state of both bundles of an early exit check uses too much resources because it tries to ignore the order of elements in a list. ignoring the order is not really necessary (or might even be hurtful in some situations). this PR disables this feature.
tests showed the increased performance while not yielding false differences between the states.
=> early early-exit desired state diff performance

reconcile/test/test_integrations_manager.py
Namespace for integ3 had wrong path set, this caused some assertions to be wrong, cause this integration was as result added into another namespace. Changed path of that namespace ns3 and added another namespace to integration integ2
=> Fixes for integration manager tests

reconcile/openshift_resources.py, reconcile/openshift_resources_base.py
related to https://issues.redhat.com/browse/APPSRE-6098
depends on https://github.com/app-sre/qontract-schemas/pull/225
resources with dynamic content (generated based on graphql query results) must be checked, but only them.
with this field, we will know exactly the ones to check. we will add a validation that if the query() function is used, this option must be set to true.
=> [openshift-resources] early exit enable query support

reconcile/utils/terrascript_aws_client.py
user creds are needed for lambda and service.
=> add master user creds to es output

reconcile/openshift_resources.py, reconcile/openshift_resources_base.py, reconcile/openshift_routes.py, reconcile/prometheus_rules_tester.py, reconcile/utils/openshift_resource.py
this PR refactors the `openshift-resources`, `openshift-route` and `prometheus-rules-tester` to work with qontract-server resource resolution (instead of sequential fetching). the `openshift-resources` early-exit code has been refactored so it can be reused by the other mentioned integrations as well.
at the same time, general performance issues for early-exit have been adressed by:
* not parsing resource YAML during early exit - this is not required because the content of a resource is sufficient to drive a decision for early-exit
* jinja2 template compilation caching
(!) review commit by commit
depends on https://github.com/app-sre/qontract-schemas/pull/227
relates to relates to https://issues.redhat.com/browse/APPSRE-6098
=> openshift-resource/route/prometheus-rule-tester resource resolution and early-exit performance

reconcile/openshift_resources.py, reconcile/openshift_resources_base.py, reconcile/openshift_routes.py, reconcile/prometheus_rules_tester.py, reconcile/utils/openshift_resource.py
this PR refactors the openshift-resources, openshift-route and prometheus-rules-tester to work with qontract-server resource resolution (instead of sequential fetching). the openshift-resources early-exit code has been refactored so it can be reused by the other mentioned integrations as well.
at the same time, general performance issues for early-exit have been adressed by:
not parsing resource YAML during early exit - this is not required because the content of a resource is sufficient to drive a decision for early-exit
jinja2 template compilation caching
(!) review commit by commit
depends on https://github.com/app-sre/qontract-schemas/pull/229
relates to relates to https://issues.redhat.com/browse/APPSRE-6098
=> 2nd try - openshift-resource/route/prometheus-rule-tester resource resolution and early-exit performance

reconcile/utils/terrascript_aws_client.py
AWS suggests using a path kind name to manage cloudwatch log group.
=> update es log group name

reconcile/quay_mirror.py, setup.py
This brings the support of OCI images comparation so we can remove now
the workaround introduced in #2675.
part of APPSRE-6101.
=> Bump sretoolbox to 1.5.0

reconcile/gitlab_housekeeping.py
the previous attempt to check for unmergable MRs failed because the attribute `merge_error` is not present all the time in MR objects. additionally the place to check is the `get_merge_request` function.
this change removes the check for `merge_error` in favour of the `merge_status` check and adds a check for the gitlab status `cannot_be_merged_recheck` (a.k.a. last time i checked it was not mergable but currently checking)
fixes https://github.com/app-sre/qontract-reconcile/pull/2745
=> gitlab-housekeeper fix check for unmergable MRs

reconcile/openshift_base.py
If the Secret is embedded in the openshift template, it may contain keys in `stringData` instead of `data`.
=> consider templated secrets stringData when checking valid keys

reconcile/queries.py, reconcile/terraform_aws_route53.py, reconcile/utils/terrascript_aws_client.py
[APPSRE-6143](https://issues.redhat.com/browse/APPSRE-6143)
Schemas update here: https://github.com/app-sre/qontract-schemas/pull/232
Optionally split the Terraform/App Interface identifier for a Route 53 zone from the name of the zone as defined in App Interface. With this change we should be able to define both a private and public DNS zone within the same AWS account that refer to the same domain name.
This will allow us to do [split view DNS](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-considerations.html#hosted-zone-private-considerations-split-view-dns) within the Fedramp environment for our work to get certificates working.
=> Split DNS support by separating zone name and ID

reconcile/quay_mirror.py, setup.py
We make use of the new `Image.is_part_of` method.
See https://github.com/app-sre/sretoolbox/pull/78
part of APPSRE-6202
=> Do not mirror images part of multi-arch ones

reconcile/utils/jira_client.py
Fixes a typing error where the variable type did not match the method's return type, causing mypy to complain. we can let it infer from the method return type
```
reconcile/utils/jira_client.py:44: error: Incompatible types in assignment (expression has type "Union[List[Dict[str, Any]], ResultList[Issue]]", variable has type "Union[Dict[str, Any], ResultList[Issue]]")  [assignment]
```
Because we check that the variable is of instance ResultList this was never an issue other than a type mismatch
=> jira_client: fix type error

reconcile/cli.py, reconcile/quay_mirror.py, reconcile/test/test_quay_mirror.py
Compare tags (previously known as deep-sync) control file was updated
at the beginning of the run. Hence, even if the run was unsuccesful,
the next one would have seen that the previous execution of the
integration was a compare-tags one and would run in non-compare-tags
mode, which would mask any potential issue with the slow mode. This
patch fixes by changing the moment of the update of the control file to
the end of the execution of the integration.
In order to be able to properly test these changes without needing to
modify the source code, a few options have been added to the
integration to control:
* where the control file is created.
* how often to compare tags.
* to force the comparation of tags.
* to specify a certain image.
The first one is particularly interesting as it can …
=> Fix deep sync mode

reconcile/cli.py, reconcile/quay_mirror.py, reconcile/test/test_quay_mirror.py
Compare tags (previously known as deep-sync) control file was updated
at the beginning of the run. Hence, even if the run was unsuccesful,
the next one would have seen that the previous execution of the
integration was a compare-tags one and would run in non-compare-tags
mode, which would mask any potential issue with the slow mode. This
patch fixes by changing the moment of the update of the control file to
the end of the execution of the integration.
In order to be able to properly test these changes without needing to
modify the source code, a few options have been added to the
integration to control:
* where the control file is created.
* how often to compare tags.
* to force the comparation of tags.
* to specify a certain image.
The first one is particularly interesting as it can …
=> Fix compare-tags (aka deep-sync) mode

reconcile/dyn_traffic_director.py
since this integration has a tendency to fail from time to time and potentially blocking MRs, implementing early exit to prevent it from running in the first place.
=> [dyn-traffic-director] early exit

reconcile/queries.py, reconcile/utils/saasherder.py
we can't deploy the same resource template to the same namespace twice right now, due to a problem with `openshift-saas-deploy-trigger-configs`. it stores the current state of the configuration of each target in s3, and compares the desired state against it to know what to trigger.
it stores the state in a key that is calculated by: https://github.com/app-sre/qontract-reconcile/blob/3087bd06936744b11c3ac5df10b11667c477260a/reconcile/utils/saasherder.py#L1534-L1538
so in case there is a saas file with a resource template that has 2 targets of the same namespace, you can see how this key is not unique.
with the addition of `name` to a saas file target, we can use the name to allow uniqueness: https://github.com/app-sre/qontract-schemas/commit/7d6a2d18176b7ba8793d4285eed250b4792266fc#diff-6ba …
=> [openshift-saas-deploy-trigger-configs] consider target name for uniqueness

reconcile/ocm/types.py, reconcile/ocm_clusters.py, reconcile/queries.py, reconcile/test/fixtures/clusters/rosa_spec.json, reconcile/test/fixtures/clusters/rosa_spec_ai.yml, reconcile/test/test_ocm_clusters.py, reconcile/utils/ocm.py
* Added logic to manage ROSA clusters in app-interface
* Fix cluster_updates diff logic
* Disable instance_type cluster updates: Instance_type attribute can not be updated in the default machine pool
* Remove disable_uwm_test: Removing this attribute from the spec is not going to change the attribute anymore
Requires: https://github.com/app-sre/qontract-schemas/pull/233
Ticket: https://issues.redhat.com/browse/APPSRE-4268
=> OCM managed clusters improvements

reconcile/change_owners.py, reconcile/test/test_change_owners.py
if files were added or deleted entirely, diff detection would fail in the case of resourcefiles. this change makes sure this does not happen.
as a nice sideeffect, the old and new colums of a detected diff now show more reliable output in the case of added or removed dict elements.
additionally: exceptions during diff detection will not fail PR checks anymore for now, while the diff logic is still stabilizing
=> [change-owners] deal with new or deleted files

reconcile/gql_definitions/vpc_peerings_validator/vpc_peerings_validator.gql, reconcile/gql_definitions/vpc_peerings_validator/vpc_peerings_validator.py, reconcile/test/test_vpc_peerings_validator.py, requirements/requirements-type.txt
qenerate now supports different naming collision strategies. By default, the parent class name is prefixed if a collision is detected. However, the `vpc_peerings_validator` enumerates now, instead of prefixing the parent class name.
cc @maorfr
=> APPSRE-5962 qenerate naming collision strategy

reconcile/utils/openshift_resource.py
When there is no `env` in the current state and an `env` is being added (or even set to `null`), `openshift-resources complains it cannot iterate over `NoneType`.
=> openshift-resources: fix error on non-existing env in current state

reconcile/change_owners.py
due to the recent change in qontract-server, all `isRequired` lists are non NonNull from a GraphGL perspective. also the elements of a list are NonNull as well. based on that, qenerate comes up with much simpler type hints on the generated data classes, which results in a lot less None checks within integrations.
=> [change-owners] remove unnecessary none checks

reconcile/gitlab_housekeeping.py
when a label has been removed, the label attribute in label events can be None
=> gitlab-housekeeping: fix for deleted label

reconcile/terraform_resources.py, reconcile/utils/terrascript_aws_client.py
Related: APPSRE-4798
This change depends on https://github.com/app-sre/qontract-schemas/pull/242 
Background: The current process for major version upgrade involves updating parameter_group in place with new engine_version. Due to existing implementation this causes terraform to delete the old parameter group first before the upgrade is complete resulting into the error. 
This MR addresses the issue by allowing to specify new parameter group which will be used for upgrade while keeping the old parameter group intact.
Test cases using app-interface-dev-data:
1.  Create a new RDS instance. This is to ensure we don't break existing process.
```
- provider: rds
identifier: dev-bhthakur-rds
defaults: /terraform/rds/bhthakur-rds-defaults.yml
parameter_group: …
```
=> [APPSRE-4798] Add support for new parameter_group for RDS upgrade while keeping the old one intact.

reconcile/queries.py, reconcile/saas_file_owners.py, reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
depends on https://github.com/app-sre/qontract-schemas/pull/246
with the changes introduced in https://github.com/app-sre/qontract-schemas/pull/220, we will slowly begin our migration of saas file ownership through `saas_file_owners` to `self_service`.
this PR introduces changes to consider `self_service` alongside `saas_file_owners` for a backwards compatible migration:
this PR updates saas-file-validator and saas-file-owners.
=> consider self-service configs for saas file ownership

reconcile/change_owners.py, reconcile/cli.py, reconcile/gql_definitions/change_owners/queries/change_types.py, reconcile/gql_definitions/change_owners/queries/self_service_roles.gql, reconcile/gql_definitions/change_owners/queries/self_service_roles.py, reconcile/gql_definitions/introspection.json, reconcile/queries.py, reconcile/saas_file_owners.py, reconcile/test/test_change_owners.py, reconcile/utils/saasherder.py, tools/qontract_cli.py
once a migration away from `owned_saas_files` have been completed, this PR may be promoted.
it removes the usage of `owned_saas_files` which was replaced with `self_service` in #2800.
=> deprecate owned_saas_files

reconcile/change_owners.py, reconcile/cli.py, reconcile/gql_definitions/change_owners/queries/self_service_roles.gql, reconcile/gql_definitions/change_owners/queries/self_service_roles.py, reconcile/test/fixtures/change_owners/changetype_cluster_owner.yml, reconcile/test/test_change_owners.py, reconcile/utils/gitlab_api.py, reconcile/utils/mr/labels.py, reconcile/utils/output.py
this PR adds to following functionality to change-owners
* parse basic decision commands from MR comments (`/lgtm`, `/lgtm cancel`, `/hold`, `/hold cancel`) and manage `bot/approved` `bot/hold` and `awaiting-approval` labels when not running in dry-run mode
* support bots as approvers
* honor `tag_on_merge_requests` flag when mentioning users in MR comments
* add `self-servicable` and `not-self-serviceable` labels to MRs to indicate if all changes are approvable by tenants (a.k.a. covered by change-types)
* manage bot-approved, bot-hold
* write MR decision state command if not running in dry-run mode
* add new integration parameter `--change-type-processing-mode` and supported `limited` and `authorative`
* make `changes.context.when` to optional and react according to the semantics …
=> [change-owners] approval-flow dry-run

reconcile/query_validator.py
related to https://issues.redhat.com/browse/APPSRE-4709
depends on https://github.com/app-sre/qontract-schemas/pull/255
query-validator currently only validates that queries are executed successfully.
with the addition of resources, we can do everything we already can in openshiftResources (jinja2 for example). with this addition, we can validate the actual data, and not only the query results.
=> [query-validator] add option to validate resources with queries

reconcile/terraform_cloudflare_resources.py
We want a list comprehension, not a list with a dict comprehension
The current behavior if no resources or account are present is this returns a list that contains an empty dict `[{}]` which is not what we want
The change will return an empty list if no resources are found, otherwise a list of dicts
=> fix list comprehension returning empty dict when no accounts

reconcile/ocp_release_mirror.py, reconcile/test/test_openshift_base.py, reconcile/test/test_openshift_resources_base.py, reconcile/utils/oc.py, reconcile/utils/openshift_resource.py, reconcile/utils/saasherder.py
Part of [APPSRE-3866](https://issues.redhat.com/browse/APPSRE-3866)
We have two integrations that rely on server having the value of None in the OC class since it relies on one method in said class. The goal of this MR is to take that method out into its own class and refactor OC to return meaningful errors whenever client/api_kind_version need to be set
=> Create local OC class to allow for meaningful errors

reconcile/dyn_traffic_director.py
This will help us avoid manual restart of pods by ensuring we close the session properly.
=> [APPSRE-6286] Fix dyn_traffic_integration connection issue

reconcile/change_owners.py, reconcile/cli.py, reconcile/utils/gql.py
log additional information for debugging purposes. this includes
* the `reconcile.utils.gql` module has been changes to provide commit id und build timestamp from the bundle represented by a SHA
* comparison bundle metadata (commit id, bundle build timestamp)
* information and details about run-mode (limited vs authorative)
contains also typos and minor fixes not worth of a dedicated PR
=> [change-owners] log debug information

reconcile/change_owners/change_owners.py, reconcile/change_owners/decision.py, reconcile/test/test_change_owners.py
* skip processing if the MR is not open anymore (closed, locked, merged)
* skip processing if the MR has been opened by the app-interface gitlab bot itself (e.g. auto promotions)
* fix bug when parsing MR comments with no body (e.g. the MR description itself)
* remove management of the `awaiting-approval` label - it is not something `saas-file-owners` does so lets not do this for now
=> [change-owners] MR handling fixes

reconcile/utils/terrascript_aws_client.py
[APPSRE-6076](https://issues.redhat.com/browse/APPSRE-6076)
Resolve an issue in FedRamp where IAM policies are resolving to the `aws` partition rather than `aws-us-gov` partition which is causing terraform-resources to fail reconcilation.
=> Use get_partition for IAM policies

reconcile/utils/terrascript_aws_client.py
Reverts app-sre/qontract-reconcile#2817
Producing unexpected output in commercial AI.
=> Revert "Use get_partition for IAM policies"

tools/qontract_cli.py
it's easier to track `changes-requested` MRs with an `updated_at` column.
=> qontract-cli app-interface-review-queue: add updated_at column

reconcile/utils/terrascript_aws_client.py
Fix for #2817 which includes the correct f-string syntax. Validated against FedRamp and Commercial A-I repos in dry-run mode to ensure that the output is correct this time.
=> Use get_partition for IAM policies (take 2)

reconcile/utils/gitlab_api.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-6349
when using `all=True` there is still pagination going on, but we do not control it.
in an effort to reduce API calls from gitlab, using our `get_items` pagination method, we use a higher value for `page_size`, causing less API calls (larger payloads per call).
=> [gitlab] replace all=True occurences with pagination

reconcile/utils/unleash.py
Should have done that in the first place. We do not need any logging except for error logs from the scheduler
=> Silence scheduler logging

reconcile/openshift_serviceaccount_tokens.py, reconcile/utils/openshift_resource.py
Now that we are on Openshift 4.11( Kubernetes 1.24) which means that 
`oc serviceaccounts get-token` does not work anymore ([see this post for detail explanation](https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0).
Our openshift-serviceaccount-tokens integration need to use a different method to find the token.
* Filter all secrets in the namespace to find the one created with the service account, since now the secret is no longer discoverable through 'oc sa get-token' command. 
* Remove base64 encoding since the new method is getting the encoded verion.
* Remove unused variable.
* Created SA manually in OpenShift 4.11 cluster and verified that 1. token still created under a similar pattern but`oc sa get-token` not longer work with error msg …
=> APPSRE-6255: Different way to get ServiceAccount's token

reconcile/change_owners/change_owners.py
to simplify the run logic of the change-owners integration, MR based prechecks have been removed.
they are not essential and have only been an optimization.
=> remove conditional change-owners run based on MR data

reconcile/utils/terrascript_aws_client.py
[APPSRE-6297](https://issues.redhat.com/browse/APPSRE-6297)
Schema change here: https://github.com/app-sre/qontract-schemas/pull/260
Add support for max_instance_lifetime for AWS auto-scaling groups. Such that image builder workers can be ephemeral in nature. Following up with a QR change.
Tested locally by changing ASG defaults for image-builder workers and then running QR in dry-run mode.
=> [ASG] add max_instance_lifetime param

reconcile/change_owners/change_types.py, reconcile/change_owners/diff.py, reconcile/test/test_change_owners.py
not all changes to datafile survive the transformation from YAML in the app-interface repo to JSON in the qontract-server bundle (newlines, comments). therefore https://github.com/app-sre/qontract-validator/pull/45 adds a checksum to each datafile during bundling so a file change is at least reflected in the checksum and can be used in `change-owners` to drive the decision process about an MR.
if the only change in a file is the checksum, then a change invisble to the integrations is assumed (newlines, comments). as such, the change itself has no impact on the integrations themselves. since it is still a change, that needs to be approved, every person who is a potential approver on such a file, can lgtm such changes.
depends lightly on https://github.com/app-sre/qontract-validator/pull/45 …
=> change-owners rely on checksum if no diffs found in file

reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
automated promotions rely on the git commit sha as the unique key that indicates if a previous step was published with success or failure.
as such, defining an automated promotion will cause the `ref` to be updated by the promotion automated MRs. this means that keeping this `ref` as master/main, or any other branch name, will be overridden pretty quickly.
this means that an auto promoted target can only rely on the change in ref in order to be triggered, and can should not rely on anything else:
- `ref: main`
- upstream jenkins job
- image push (#2833)
this PR adds a validation that when automated promotion is set, the only acceptable `ref` is a commit sha. there are already existing validations that when a commit sha is used, `upstream` can not be used, so that should cover our case as …
=> [saas-file-validator] validate auto promotion used with commit sha

reconcile/cli.py, reconcile/openshift_saas_deploy_trigger_images.py
qontract-reconcile-openshift-saas-deploy-trigger-container-images is too long for Kubernetes. shortening the name,
=> shorten integration name

reconcile/change_owners/change_owners.py, reconcile/gitlab_housekeeping.py, tools/qontract_cli.py
* the review queue will not show MRs with the label self-servicable anymore
* gitlab housekeeper will remove the `lgtm` label when an MR has the `self-serviceable` label because it expects people to /lgtm which yield the `bot/approved` label
`change-owners` will not manage the `self-serviceable` label (and even remove it) if the integration runs without activated `--mr-management`
=> [review-queue][gitlab-housekeeper] handle self-serviceable label like saas-file-update

reconcile/cli.py, reconcile/openshift_saas_deploy_change_tester.py, reconcile/queries.py, reconcile/saas_file_owners.py, reconcile/test/test_openshift_saas_deploy_change_tester.py
`saas-file-owners` and `openshift-saas-deploy-wrapper` are closely related integrations. `saas-file-owners` creates an input file about saas-file that have changed that is passed to `openshift-saas-deploy-wrapper`, so it can run `openshift-saas-deploy` for each changed saas-file to verify the content.
when we switch from `saas-file-owners` to `change-owners` for self-service approvals, `saas-file-owners` will not run as part of `app-interface` PR checks anymore, so the input `openshift-saas-deploy-wrapper` expects is not there anymore.
This MR introduces a new integration `openshift-saas-deploy-change-tester` which takes over the responsibility to run `openshift-saas-deploy` for each changed saas-file. This integration will be able to detect for itself what saas-files changed without the …
=> replace openshift-saas-deploy-wrapper with o-s-d-change-tester

reconcile/utils/gitlab_api.py, reconcile/utils/metrics.py
Add instrumentation for GitlabApi client so we can track how many calls we make per integration.
This data will be used to potentially identify any improvements to reduce no of calls we make to gitlab.
We can follow up this MR with even better instrumentation that tells us http method, path, status code etc. This is not the scope of this MR right now.
=> Gitlab api client instrumentation

reconcile/change_owners/change_types.py, reconcile/test/fixtures/change_owners/changetype_cluster_owner.yml, reconcile/test/test_change_owners.py
the `$` sign represents the document root in jsonpath. if this is used as a path for change coverage, every change in a document is covered by it.
=> [change-owners] jsonpath root ($) matches all changes in files

reconcile/queries.py, tools/qontract_cli.py
[APPSRE-6355](https://issues.redhat.com/browse/APPSRE-6355)
* To increase visibility of MRs for ICs in AppSRE, this allows us to define repos to watch for MRs within the codeComponents section of an app file (app interface appfile will have to be updated to add this flag as well)
* The watched repos must be on GitLab.cee and [managed by the AppSRE Bot](https://gitlab.cee.redhat.com/service/app-interface#enable-gitlab-features-on-an-app-interface-controlled-gitlab-repository) as well as have a PR check job setup
* Schemas change here: https://github.com/app-sre/qontract-schemas/pull/271
* Tested with [infra repo](https://gitlab.cee.redhat.com/app-sre/infra) and [managed tenants repo](https://gitlab.cee.redhat.com/service/managed-tenants/) to ensure that MRs show up as expected
Example of …
=> [APPSRE-6355] Additional repos for review queue

reconcile/openshift_resources_base.py
This allows to get the cluster region in jinja2 resource templates:
```
{{ REGION | default(resource.namespace.cluster.spec.region) }}
```
=> allow access cluster region in resource-templates

reconcile/dashdotdb_slo.py
This only affects type-hints -> so it does not make a difference in the running program. Also I checked in the debugger and there is no difference.
However, the thread pool returns a list of lists and that should be noted correctly, even if mypy doesnt catch it in this scenario.
=> APPSRE-6433 proper type when threads join

reconcile/change_owners/change_types.py, reconcile/change_owners/self_service_roles.py, reconcile/test/test_change_owners.py
Make change-type jsonpath selector expressions jinja templateable so they have access to the context they operate in.
the `aws-account-owner` change-type will grant tenants permissions to change terraform-resources for the account they own. since tf resources are defined in namespaces files where resources from various accounts can be mixed, we need to restrict the self-serviceable resources to the granted account.
```yaml
---
$schema: /app-interface/change-type-1.yml
labels: {}
name: aws-account-owner
description: |
allow all actions on resources of an AWS account
contextType: datafile
contextSchema: /aws/account-1.yml
changes:
- provider: jsonPath
changeSchema: /openshift/namespace-1.yml
jsonPathSelectors:
- externalResources[?(@.provisioner.'$ref'=='{{ ctx_file_path }}')].resources …
```
=> [change-owners] templated jsonpath expressions

reconcile/change_owners/change_types.py, reconcile/change_owners/self_service_roles.py, reconcile/change_owners/tester.py, reconcile/gql_definitions/change_owners/queries/change_types.gql, reconcile/gql_definitions/change_owners/queries/change_types.py, reconcile/gql_definitions/change_owners/queries/self_service_roles.gql, reconcile/gql_definitions/change_owners/queries/self_service_roles.py, reconcile/gql_definitions/introspection.json, reconcile/test/test_change_owners.py, setup.cfg, tools/qontract_cli.py
adds a qontract-cli command for change-type testing
```
qontract-cli test-change-type --change-type-name aws-account-owner --role-name app-sre --app-interface-path ~/dev/service/app-interface
```
role and change-type are loaded from a qontract-server. datafiles and resources are loaded from disk right now because we don't have a way to load those files in full from qontract-server
part of: https://issues.redhat.com/browse/APPSRE-6460
depends on: https://github.com/app-sre/qontract-schemas/pull/276
=> [change-type] qontract-cli change-type tester

reconcile/utils/oc.py
Reverts app-sre/qontract-reconcile#2866
The thread locks that were introduces seem to be causing issues with the kubernetes client, used by the OCNative client. The kubernetes client creates cache files in /tmp that contains the resource kinds, verbs and versions that are available on clusters. Right when these changes were introduced we began seeing errors such as
```
[openshift-serviceaccount-tokens] load cache error: Expecting ',' delimiter: line 1 column 40958 (char 40957)
```
Upon closer inspection the json files are sometimes getting corrupted. This happens almost on every run, in at least one cache file (there is one per cluster targetted during the run)
I'm hoping reverting this MR will clear the errors. If not we can re-introduce the changes
ref.: …
=> Revert "OC client: only use Project kind if it is supported"

reconcile/gql_definitions/common/app_interface_vault_settings.gql, reconcile/gql_definitions/common/app_interface_vault_settings.py, reconcile/gql_definitions/common/smtp_client_settings.gql, reconcile/test/test_secret_reader.py, reconcile/typed_queries/app_interface_vault_settings.py, reconcile/utils/secret_reader.py, tools/cli_commands/test/test_gpg_encrypt.py
New integration for CNA should be fully typed. To achieve this, we must have a fully typed version of `SecretReader`.
This PR:
- Adds `TypedSecretReader`
- Adds `AppInterfaceSettings` query for vault settings for `TypedSecretReader`.
- Renames SMPT Settings, because a query name must be unique across our codebase.
The core idea is that `SecretReader` and `TypedSecretReader` both have the same base class. The base class is compatible with untyped `VaultClient`. The new `TypedSecretReader` abides to dependency inversion as agreed in recent discussions for new library components.
The new `SecretReader` is to be instantiated at integration `run()` level and injected into any sub-functions / classes, e.g.:
```python
from reconcile.typed_queries.app_interface_vault_settings import query as …
```
=> APPSRE-6295 typed secret-reader for CNA

reconcile/glitchtip/reconciler.py
Avoid a chicken-egg problem. See https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/173519/app-interface_20JSON_20validation/
To grant the automation user proper glitchtip permission, during the onboarding of a new glitchtip instance, the automation user must be added to a bootstrap organization manually (`app-sre` in this example). But this organization is maybe not app-interface managed and therefore we have to remove it after creating other ones.
```
[2022-10-20 14:05:33] [INFO] [reconciler.py:reconcile:244] - ['delete_organization', 'app-sre', 'https://glitchtip.stage.devshift.net']
[2022-10-20 14:05:33] [INFO] [reconciler.py:reconcile:250] - ['create_organization', 'app-sre-stage', 'https://glitchtip.stage.devshift.net']
```
=> create orgs first and delete orgs afterward

reconcile/utils/smtp_client.py
`SecretReader` now supports `SupportsSecret` -> we can use that in smtp-client.
=> smtp-client secret_reader new function

reconcile/cli.py, reconcile/slack_usergroups.py, reconcile/test/test_slack_usergroups.py
with this PR, we can run the integration with the following options: `--workspace-name coreos --usergroup-name app-sre-ic`.
currently meant only for local execution, but there is a bigger plan behind this :magic_wand:
=> [slack-usergroups] add option to run per workspace and usergroup

reconcile/slack_usergroups.py, reconcile/utils/pagerduty_api.py
when a single usergroup is defined, it is likely more performant to avoid initiating all users in a pagerduty instance, and instead search for a user when needed.
follows up on the introduction of `usergroup-name` in #2882
=> [slack-usergroups] do not init pagerduty users if usergroup name is defined

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/self_service_roles.py, reconcile/change_owners/tester.py, reconcile/gql_definitions/change_owners/queries/change_types.gql, reconcile/gql_definitions/change_owners/queries/change_types.py, reconcile/gql_definitions/introspection.json, reconcile/test/fixtures/change_owners/changetype_cluster_owner.yml, reconcile/test/fixtures/change_owners/changetype_role_member.yaml, reconcile/test/fixtures/change_owners/changetype_saas_file.yaml, reconcile/test/fixtures/change_owners/changetype_secret_promoter.yaml, reconcile/test/test_change_owners.py, reconcile/test/test_change_owners_inheritance.py, setup.cfg, setup.py
The granular permission model based on `change-types` allows fine grained control of what is self serviceable but to really allow the right amount of change for the right people, we would need to define a lot of change-types for individual aspects. Having a lot of similar `change-types` eventually leads to duplication. `change-type` inheritance is an approach to keep duplication at bay.
A `change-type` can inherit change detector configurations (jsonpaths, etc.) from other `change-types`
```yaml
$schema: "/app-interface/change-type-1.yml"
name: a-change-type
inherit:
- $ref: "/another-change-type.yml"
- ...
```
All changes along the inheritance paths will be aggregated into the `ChangeTypeProcessor` representing a `change-type`. The rest of the code is unaware this aggregation happens. …
=> [change-owners] change-type inheritance

reconcile/test/test_utils_terraform_client.py, reconcile/utils/terraform_client.py
This extends the log message to contain fields updated by a terraform change. Only update actions are considered. Example for a log message, backup retention was 14 and is reduced to 7:
```
[2022-10-21 14:06:08] [INFO] [terraform_client.py:log_plan_diff:362] - ['update', 'app-int-example-01', 'aws_db_instance', 'dev-jboll-rds', {'backup_retention_period': 7}]
```
=> APPSRE-5975 Log fields and diffs on updates

reconcile/ocm/utils.py, reconcile/ocm_additional_routers.py, reconcile/ocm_addons.py, reconcile/ocm_aws_infrastructure_access.py, reconcile/ocm_clusters.py, reconcile/ocm_external_configuration_labels.py, reconcile/ocm_github_idp.py, reconcile/ocm_groups.py, reconcile/ocm_machine_pools.py, reconcile/ocm_upgrade_scheduler.py
## Overview 
* Standardize all the OCM integrations to get clusters the same way. Clusters suitability is now checked in a `_cluster_is_compatible` method in all the integrations. Also, cluster filtering is now made within the `run` method in all cases. 
* Enable integration disablement at the cluster level. This is required to early support Hypershift clusters where a lot of OCM administration tasks are not yet in place and will be disabled in the cluster spec.  
Requires: https://github.com/app-sre/qontract-schemas/pull/282
=> Standardize OCM integrations

tools/qontract_cli.py
The date tooltip does not display correctly on the new JSON-based table 👎 . This fixes it by not using tooltips anymore, but displaying schedule and long-running upgrade info directly.
Example output:  https://gitlab.cee.redhat.com/-/snippets/5874
=> qli cluster-upgrade-policy: fix broken tooltip by showing better data

reconcile/ocm_additional_routers.py, reconcile/ocm_addons.py, reconcile/test/fixtures/ocm_additional_routers/state.yml
- Standardize OCM integrations and allow its disablement at cluster level
- Fix cluster_is_compatible methods
=> Fix cluster_is_compatible method in some ocm integrations

reconcile/test/test_ocm_clusters.py, reconcile/test/test_utils_ocm.py, reconcile/test/test_utils_ocm_versions.py, reconcile/utils/ocm.py, reconcile/utils/ocm_base_client.py
`OCMBaseClient` is a thin layer between the OCM API and more complex OCM clients (e.g., `OCMClient` or `CNAClient`). `OCMBaseClient` can be used by more sophisticated clients to interact with the OCM API. It takes care of authentication and provides basic API operations GET, POST, PATCH, DELETE.
Using `OCMBaseClient` will also ease testing, as it can easily be mocked and passed to the sophisticated client as an input parameter.
=> APPSRE-6295 add OCMBaseClient

reconcile/change_owners/self_service_roles.py, reconcile/closedbox_endpoint_monitoring_base.py, reconcile/dashdotdb_dvo.py, reconcile/service_dependencies.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_change_owners.py, reconcile/utils/saasherder.py, reconcile/utils/slack_api.py, setup.cfg
This enables blacks' `truthy-bool` and `redundant-expr` checks.
* for a detailed explanation of `truthy-bool` see this [blog post](https://adamj.eu/tech/2022/10/24/python-type-hints-truthy-bool/)
* and for `redundant-expr` see the [official one](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-expression-is-redundant-redundant-expr)
=> enable blacks' truthy-bool and redundant-expr checks

.gitignore, reconcile/test/test_utils_terraform_client.py, reconcile/utils/terraform_client.py
The Pull Request https://github.com/app-sre/qontract-reconcile/pull/2254 brought about an ability to _skip_ an attempt to perform a Terraform **apply** when the RDS database settings had been modified, and the `apply_immediately` property had not been set to `true`.
The initial implementation took care of cases where the underlying database version (the engine) had been changed, for example, as part of routine maintenance or needing a specific version.
This change expands the current implementation beyond only detecting that there has been a change to **`engine_version`** resource attribute on the Terraform's side (or **EngineVersion** as per the AWS' API) and adds several commonly changed [settings](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html# …
=> APPSRE-4645: Add more RDS pending modifications for which to skip Terraform apply

reconcile/change_owners/change_types.py, reconcile/change_owners/diff.py, reconcile/test/test_change_owners.py
resource files without schema are not parsed right now, which means that fine jsonpath expressions to pinpoint the change in a file will not work in those situations.
a lot of resource files are parsable though even without a schema, e.g. ConfigMaps while at the same time not all resource files with a schema are parsable when they include jinja2 templating.
this change will try to best-effort parse resource files and falls back to handling the file content as clob if not parsable.
=> [change-owners] best effort parse resource files without schema

reconcile/gitlab_housekeeping.py
gitlab-housekeeping was not handling stale items properly.
this is obviously because i am dumb: #241
i mean, seriously. update_date is the latest note or `now`???
this PR simplifies the logic to not care about notes, but use the item's `updated_at` attribute.
=> [gitlab-housekeeping] fix stale items handling

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.gql, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.py, reconcile/terraform_cloudflare_resources.py
part of https://issues.redhat.com/browse/APPSRE-6478
This adds the `deletionApprovals` capability to the Cloudflare accounts, like we have for AWS, allowing users to mark a resource for deletion while keeping deletion protection as default
This depends on schema change https://github.com/app-sre/qontract-schemas/pull/289
=> tf-cloudflare-resources: add deletionApprovals

reconcile/openshift_base.py
`is_kind_supported` works even if `init_api_resources` is false. So remove the condition
=> Fix exception for missing resources

reconcile/gql_definitions/introspection.json, reconcile/queries.py, reconcile/test/fixtures/clusters/osd_spec_ai.yml, reconcile/test/fixtures/clusters/rosa_spec_ai.yml, reconcile/test/test_ocm_clusters.py, reconcile/utils/ocm.py, reconcile/utils/ocm_base_client.py, tools/qontract_cli.py
part of https://issues.redhat.com/browse/APPSRE-2494
depends on https://github.com/app-sre/qontract-schemas/pull/292
docs: https://www.appsdeveloperblog.com/keycloak-client-credentials-grant-example/
=> Switch OCM auth from offline token to client secret

reconcile/ocm/types.py, reconcile/utils/ocm.py
related to https://issues.redhat.com/browse/APPSRE-6517
CCS clusters are OSD clusters created within a customer's AWS account. As such, they do not have storage/LB quota.
This PR adds a handle for a CCS cluster so we can work with such clusters.
=> [OCM] add support for CCS clusters

README.md, reconcile/cli.py, reconcile/ocm_upgrade_scheduler_org.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-6517
depends on https://github.com/app-sre/qontract-schemas/pull/294
this PR introduces a new integration - `ocm-upgrade-scheduler-org`.
this integration managed upgrades in the exact same way as `ocm-upgrade-scheduler`, but it works for OCM orgs defined in app-interface, while the clusters themselves are not managed via app-interface.
this allows external groups to submit MRs to app-interface adding their OCM org with a list of clusters and upgrade policies, and poof! it works.
=> introduce ocm-upgrade-scheduler-org

reconcile/queries.py, reconcile/terraform_aws_route53.py
[APPSRE-6393](https://issues.redhat.com/browse/APPSRE-6393)
`unmanaged_record_names` in the `dns-zone-1.yml` schema is no longer needed as Terraform won't overwrite existing DNS records and only modifies records explicitly outlined in DNS zone files. Removed from schemas in https://github.com/app-sre/qontract-schemas/pull/296
Here we remove the corresponding logic from the terraform-aws-route53 integration
=> Remove unmanaged_record_names field from terraform-aws-route53

reconcile/ocm/types.py, reconcile/ocm_clusters.py, reconcile/queries.py, reconcile/test/fixtures/clusters/osd_spec.json, reconcile/test/fixtures/clusters/osd_spec_ai.yml, reconcile/test/fixtures/clusters/rosa_spec.json, reconcile/test/fixtures/clusters/rosa_spec_ai.yml, reconcile/test/test_ocm_clusters.py, reconcile/utils/ocm.py
* Introduce ROSA hosted-cp clusters creation 
* OCM-clusters app-interface updates will now update values when they differ, not only when the AI values are missing. This is needed to recreate clusters automatically when they got deleted by OCM (clusters in ocm-staging are ephemeral) 
* Removed the pydantic validator to set default Rosa AWS role ARN's. Roles must be set. 
* Changed ocm-clusters updates conditions: Rosa hosted-CP clusters do not inform provision_shard nor external_id
Requires: https://github.com/app-sre/qontract-schemas/pull/291
=> Add ROSA/Hypershift clusters support

reconcile/ocm_clusters.py, reconcile/test/test_ocm_clusters.py
This change reverts cluster manifest updates from the OCM API. There was a problem updating the cluster's elbFQDN due to DNS record length. 
The changes introduced here will be managed separately from the ROSA/Hypershift initiative.
=> Fix: Rollback OCM cluster attribute updates

reconcile/terraform_aws_route53.py
Verify CNAME records by resolving the target cluster elb record. This will crash the integration on failures in DNS resolution
=> Add call to get_a_records for cluster CNAMES

reconcile/ocm_upgrade_scheduler.py, reconcile/ocm_upgrade_scheduler_org.py, reconcile/queries.py, reconcile/test/test_ocm_upgrade_scheduler.py, tools/qontract_cli.py
with this PR, the upgrade scheduler will not rely on the data found in app-interface for `version` and `channel`, but on the same information returned from the OCM API.
this makes the integration more resilient, in case the version has not been updated (we currently rely on an automation to update the field).
=> [ocm-upgrade-scheduler] rely on spec from ocm

reconcile/utils/mr/clusters_updates.py
part of https://issues.redhat.com/browse/APPSRE-6532
this is a small piece of #2923, to allow for more review time while not skipping CI on cluster updates.
=> do not skip ci on clusters updates MRs

README.md, reconcile/cli.py, reconcile/ocm_upgrade_scheduler_org_updater.py, reconcile/queries.py, reconcile/test/test_ocm_additional_routers.py, reconcile/test/test_ocm_clusters.py, reconcile/utils/mr/__init__.py, reconcile/utils/mr/ocm_upgrade_scheduler_org_updates.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-6517
depends on https://github.com/app-sre/qontract-schemas/pull/302
in order to keep `upgradePolicyClusters` up-to-date with clusters being created/deleted, we need to define conditions of clusters (ClusterDeployment labels a.k.a external configuration labels) based on which we select an upgrade policy for a discovered cluster.
this PR creates a separate integration that will submit MRs to app-interface to update `upgradePolicyClusters`, so we can keep the logic of `ocm-upgrade-scheduler-org` unchanged. the reason is that the current "static" nature of defining clusters is a no-go for management of OSD-FM fleets.
the OSD FM requirements are more complex compared to a regular customer, which usually has a single OCM org in a single OCM …
=> ocm-upgrade-scheduler-org-updater

reconcile/jenkins_job_builds_cleaner.py, reconcile/utils/jenkins_api.py
Fixing:
```
File "/run-integration.py", line 164, in main 
command.invoke(ctx) 
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke 
return _process_result(sub_ctx.command.invoke(sub_ctx)) 
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke 
return ctx.invoke(self.callback, **ctx.params) 
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke 
return __callback(*args, **kwargs) 
File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func 
return f(get_current_context(), *args, **kwargs) 
File "/usr/local/lib/python3.9/site-packages/reconcile/cli.py", line 780, in jenkins_job_builds_cleaner …
```
=> APPSRE-6535 Return empty array if job dosen't return allBuilds key

reconcile/test/test_utils_mr.py, reconcile/utils/mr/README.md, reconcile/utils/mr/app_interface_reporter.py, reconcile/utils/mr/auto_promoter.py, reconcile/utils/mr/aws_access.py, reconcile/utils/mr/base.py, reconcile/utils/mr/cluster_service_install_config.py, reconcile/utils/mr/clusters_updates.py, reconcile/utils/mr/notificator.py, reconcile/utils/mr/ocm_upgrade_scheduler_org_updates.py, reconcile/utils/mr/user_maintenance.py
part of https://issues.redhat.com/browse/APPSRE-6532
follows up on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/51044
in this MR we granted our bot self-service permissions over *some* cluster updates, excluding `elbFQDN` for example.
this PR adds a `description` field when submitting automated MRs. the clusters updates automated MR, which used to contain a `bot/automerge` and a `bot/skip-ci` labels will now contain a `/lgtm` in the MR description. this will lead to an automated merge, if the updates are within the self-service role.
=> replace cluster updates auto MR automerge label with /lgtm comment

tools/qontract_cli.py
Part of [APPSRE-6517 ](https://issues.redhat.com/browse/APPSRE-6517)
Reuse the same code and layout for ocm-org and cluster-based upgrade policies. This allows to also show soaking upgrades for ocm-org based policies.
Examples:
* ocm-org upgrade policies: https://gitlab.cee.redhat.com/-/snippets/5954
* app-interface clusters upgrade-policies: https://gitlab.cee.redhat.com/-/snippets/5874
=> qcli ocm fleet upgrade policies

reconcile/test/test_ocm_clusters.py, reconcile/test/test_utils_ocm.py, reconcile/test/test_utils_ocm_versions.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-6526
some SAs may have non-org scoped permissions. in such cases, using a SA may mean we are a danger to the entire fleet.
this PR makes initiating clusters only consider clusters within the SA's org.
=> ocm initiate clusters from own org only

reconcile/cna/assets/__init__.py, reconcile/cna/assets/asset.py, reconcile/cna/assets/asset_factory.py, reconcile/cna/assets/aws_assume_role.py, reconcile/cna/assets/aws_utils.py, reconcile/cna/assets/null.py, reconcile/cna/client.py, reconcile/cna/integration.py, reconcile/cna/state.py, reconcile/test/cna/test_asset.py, reconcile/test/cna/test_aws_assume_role.py, reconcile/test/cna/test_client.py, reconcile/test/cna/test_integration.py, reconcile/test/cna/test_null.py, reconcile/test/cna/test_state_assembly.py, reconcile/test/cna/test_state_diff.py, reconcile/test/cna/test_state_overrides.py
* use registration process to make asset classes, their provider and CNA kind known to the integration
* use pydantic `alias` fields to map the difference from CNA api and python dataclasses
* drive dataclass<->API conversion through this metadata
* load CNA metadata into the client so we can test for dataclass<->API compatibility
* renamed kind to asset_type (kind means something different in the CNA API)
* creator filtering
=> rely on asset field metadata for CNA API and asset class conversion

tools/qontract_cli.py
This ensures we keep the same OCM org display order in https://gitlab.cee.redhat.com/service/app-interface-output/-/blob/master/ocm-fleet-upgrade-policies.md
=> sort ocm org by names in q-cli ocm-fleet-upgrade-policies

reconcile/quay_mirror.py, reconcile/test/test_instrumented_wrappers.py, reconcile/utils/instrumented_wrappers.py, setup.py
The former implementation of the Image class had a few problems (and was broken for registries not returning `Docker-Content-Digest` header on manifest retrieval). A new implementation has been written and we have used the cache stats provided by it instead of rolling our own InstrumentedCache that was highly dependent of the previous implementation.
See the following PRs for more context on the Image change:
* https://github.com/app-sre/sretoolbox/pull/80
* https://github.com/app-sre/sretoolbox/pull/82
Signed-off-by: Rafael Porres Molina <rporres@gmail.com>
=> Use new implementation of Image response cache

reconcile/glitchtip/integration.py, reconcile/test/glitchtip/test_glitchtip.py
Glitchtip switches to auth.redhat.com as IdP therefore the GitHub email lookup code isn't required anymore.
Ticket: https://issues.redhat.com/browse/APPSRE-6553
=> glitchtip: remove github support - glitchtip uses auth.redhat.com as IdP

reconcile/sql_query.py, reconcile/utils/gql.py, reconcile/utils/terrascript_aws_client.py
* use bulk request to fetch "/aws/rds-defaults-1.yml" resources all at once
* use state.ls instead of state.exists for query states
QUERY_COUNT * "get rds default resource" + QUERY_COUNT * (state.exists + state.get)
674 + 674 * 2 = 2022 http calls
"get all rds default resources" + QUERY_COUNT * state.get + state.ls
1 + 674 + 1 = 676 http calls
APPSRE-6546
=> sql-query: performance improvements by reducing http calls

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/test/test_change_owners.py
this fixes a bug in the priority calculation logic for non-self-serviceable MR.
an MR that has only uncovered changed, will not yield any priority for self-service merges because it can't be self-service merged anways.
=> change-owners fix MR priority for uncovered changes

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/queries.py, reconcile/test/test_utils_parse_dhms_duration.py, reconcile/utils/parse_dhms_duration.py
Tekton default timeout for PipelineRuns are 60 minutes. We may need to allow for larger timeouts for certain jobs, but we don't want to allow for smaller timeouts since the current implementation is to delete the underlying pods, which gets us without logs.
schema: https://github.com/app-sre/qontract-schemas/pull/312
Part of APPSRE-4670
Signed-off-by: Rafael Porres Molina <rporres@gmail.com>
=> Allow tekton timeouts bigger than 60 minutes

reconcile/queries.py
See https://github.com/app-sre/qontract-schemas/pull/315
This fix will allow integrations manager to spawn new pods in FedRamp with Google Chat logging. Tested locally in dry run and saw the expected Fluentd config.
https://issues.redhat.com/browse/APPSRE-6564
=> Update queries.py to add googleChat logging parameter for integrations

reconcile/github_org.py, reconcile/gql_definitions/common/clusters_minimal.py, reconcile/gql_definitions/introspection.json, reconcile/ocm_github_idp.py, reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_groups.py, reconcile/openshift_rolebindings.py, reconcile/slack_cluster_usergroups.py, reconcile/test/test_openshift_base.py, tools/qontract_cli.py
In preparation for [cluster logins via RedHat SSO](https://issues.redhat.com/browse/APPSRE-6374),
the `/openshift/cluster-1.yml.auth` attribute needs to be a list of auth objects. This PR adapts all integrations and utils.
* [APPSRE-6374](https://issues.redhat.com/browse/APPSRE-6374)
* [APPSRE-6554](https://issues.redhat.com/browse/APPSRE-6554)
Depends on https://github.com/app-sre/qontract-schemas/pull/317
=> support for the usage of multiple cluster authentication backends at the same time

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.gql, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.py, reconcile/terraform_cloudflare_resources.py, reconcile/test/test_utils_terrascript_cloudflare_client.py, reconcile/utils/terrascript/cloudflare_client.py, reconcile/utils/terrascript/cloudflare_resources.py
Rework of #2964 to include fields which were missing and causing issues
Ref.: [APPSRE-6571](https://issues.redhat.com/browse/APPSRE-6571)
This adds a `cloudflare_account` definition which allows setting 2FA enforcement on accounts. The plan type also needs to be defined on that resource otherwise it default to "standard"
Depends on
* https://github.com/app-sre/qontract-schemas/pull/321
=> tf-cloudflare: add cloudflare account 2fa enforcement

reconcile/gql_definitions/change_owners/queries/change_types.py, reconcile/gql_definitions/change_owners/queries/self_service_roles.py, reconcile/gql_definitions/cna/queries/cna_provisioners.py, reconcile/gql_definitions/cna/queries/cna_resources.py, reconcile/gql_definitions/common/app_interface_vault_settings.py, reconcile/gql_definitions/common/clusters_minimal.py, reconcile/gql_definitions/common/smtp_client_settings.py, reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.py, reconcile/gql_definitions/glitchtip/glitchtip_instance.py, reconcile/gql_definitions/glitchtip/glitchtip_project.py, reconcile/gql_definitions/glitchtip/glitchtip_settings.py, reconcile/gql_definitions/jumphosts/jumphosts.py, reconcile/gql_definitions/quay_membership/quay_membership.py, reconcile/gql_definitions/service_dependencies/service_dependencies.py, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.py, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_resources.py, reconcile/gql_definitions/vpc_peerings_validator/vpc_peerings_validator.py, requirements/requirements-type.txt, setup.cfg
Apply latest qenerate upgrade https://github.com/app-sre/qenerate/pull/60
There was a type-hint missing for `**kwargs` for `query` convenience function.
=> Add missing type hint to generated files

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager-fedramp.yaml, reconcile/test/fixtures/helm/enable_google_chat.yml
Navigating Google Chat threads is very slow and requires a lot of scrolling. This MR just changes the webhook to post log messages from all pods to a single "thread" so you can easily see sequential log messages.
https://developers.google.com/chat/how-tos/webhooks#start_or_reply_to_a_message_thread
=> Condense GChat logs to single 'thread'

reconcile/openshift_clusterrolebindings.py
Fix clusterrolebinding KeyError introduced in #2973
=> openshift_clusterrolebindings: resources are cluster scoped

reconcile/ocm_upgrade_scheduler.py, reconcile/queries.py, reconcile/test/test_ocm_upgrade_scheduler.py, reconcile/test/test_utils_ocm.py, reconcile/utils/ocm.py, tools/qontract_cli.py
Depends on https://github.com/app-sre/qontract-schemas/pull/314
See [APPSRE-6545](https://issues.redhat.com/browse/APPSRE-6545) and [ADR 0032](https://docs.google.com/document/d/1_aRuF_Owlryo50mycbS7E0m9I6pzE_KPNUnLp7nQaXE/edit)
This pull request introduces the notion of OCM sectors. A sector regroups a set of clusters. Sectors are enablers for progressive rollout of versions across a fleet of clusters. In the context of this PR, only cluster versions are considered, but sectors could be later used for component (applications, resources, ...) progressive rollouts.
* An OCM organization can define a set of sectors by naming them
* A sector name is unique within the OCM organization
* Sectors can depend on each other, creating one or multiple dependency chains.
* loops are being detected …
=> APPSRE-6545 upgrade policy sector

reconcile/utils/repo_owners.py
gitlab-owners expects a dictionary like structure in an OWNERS file. this fix makes sure that the integration does not fail if that is not the case and logs the repo and owner file that makes troubles.
=> [gitlab-owners] detect and log basic OWNER file format

reconcile/utils/terrascript_aws_client.py
This error message will give a fast hint on which upstream was failing.
=> more details in error message about failure in upstream job

helm/qontract-reconcile/templates/template.yaml
[APPSRE-6480](https://issues.redhat.com/browse/APPSRE-6480)
In FedRamp, ship logs from *-trigger integration to a separate channel to avoid spamming the main reconcile channel with messages.
=> Add triggers channel for GChat in FedRamp

reconcile/slack_base.py, reconcile/slack_cluster_usergroups.py, reconcile/test/test_slack_base.py, reconcile/test/test_slack_usergroups.py, reconcile/test/test_utils_slack_api.py, reconcile/utils/slack_api.py, setup.cfg
Refactor `SlackApi` ([APPSRE-6594](https://issues.redhat.com/browse/APPSRE-6594)):
* remove `SecretReader` dependency
* full type hints support
* prepare it to be used/configured via GQL classes
This is some preparation work for
* [APPSRE-6592 - refactor slack-usergroups](https://issues.redhat.com/browse/APPSRE-6592)
* [APPSRE-6593 - merge slack integrations](https://issues.redhat.com/browse/APPSRE-6593)
* and finally [APPSRE-6374 - slack-cluster-usergroups OIDC support](https://issues.redhat.com/browse/APPSRE-6575)
Hints for the reviewer:
* I ran `slack-usergroups` and `slack-cluster-usergroups` locally with `dry-run`
* `slack_base.get_slackapi` will be used with [APPSRE-6592](https://issues.redhat.com/browse/APPSRE-6592) and replaces `slack_base.slackapi_from_permissions`
=> refactor slack-api

helm/README.md, helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-manager-fedramp.yaml, openshift/qontract-manager-fedramp.yaml
Take 2 at https://github.com/app-sre/qontract-reconcile/pull/2992 using Helm templating.
[APPSRE-6600](https://issues.redhat.com/browse/APPSRE-6600)
With Fluentd -> GChat logging now deployed in FedRamp, we have noted the Fluentd containers consistently running over the existing memory limit of 120Mi. This MR allows users to specify on an integration level the Fluentd resource limits/requests, similar to what we can currently do with the QR pod.
=> Fluentd Customizable Resource Limits and Requests 

reconcile/queries.py
Follow-up to #2996 to update queries.py to include the new `fluentdResources` part of the Integration Spec query so that integrations manager can properly update new pods.
=> Include fluentdResources in queries.py

reconcile/ocm_upgrade_scheduler_org_updater.py, reconcile/queries.py, reconcile/test/test_ocm_upgrade_scheduler_org_updater.py
https://issues.redhat.com/browse/APPSRE-6595
Depends on https://github.com/app-sre/qontract-schemas/pull/325
Allow to reference an upgradepolicy template from OCM `upgradePolicyDefaults`.
This avoids repeating many time the same default for different labels such as `sector` (or `region`, or `cluster-type`, ...).
Example usage: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52219/diffs
=> process upgradePolicyTemplate in OCM upgradePolicyDefaults

reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py
similar to #2942, but for terraform-resources.
this means that when a namespace is marked as `delete: true`, the cloud resources will be deleted (and will need `deleteionApproval` if account is deleteion protected).
=> [terraform-resources] ignore deleted namespaces

reconcile/cna/assets/asset.py
An asset can also be in state `Error`
=> allow Error state

reconcile/glitchtip/integration.py, reconcile/gql_definitions/glitchtip/glitchtip_project.gql, reconcile/gql_definitions/glitchtip/glitchtip_project.py, reconcile/gql_definitions/introspection.json
follow up on https://github.com/app-sre/qontract-schemas/pull/334
this PR changes the way the glitchtip integrations queries for projects. instead of going through apps, we query them directly.
=> glitchtip queries adjustments

reconcile/openshift_resources_base.py
without querying this field, openshift-resources based integrations can not ignore deleted namespaces.
another fix on top of #2942
=> add delete to namespaces query for openshift-resources

reconcile/test/test_utils_expiration.py
the test data for `reconcile.utils.expiration` was defined in local time but the expiration lib itself operates on UTC. the result is failing tests every day around day change.
this is one of those rare occasions where coding around day change provides value... for when we need to hot fix something around day change ¯\\_(ツ)_/¯
i'm a bit afraid though that i [verschlimmbessert](https://en.wiktionary.org/wiki/verschlimmbessern) the situation and that tests might start to fail outside of day change, which would provide evidence that coding around day change does not provide value.
but it is late and i can't do timezone math when it is late and i don't want to argue with myself when it is late so here we go -> "Create pull request". future me will take care i guess
Signed-off-by: Gerd …
=> fix expiration date test data to UTC

reconcile/cna/assets/aws_rds.py, reconcile/cna/state.py
- username is required and cannot be optional
- is_production is implicitly set
- family is implicitly calculated (postgres only)
Corresponding schema change https://github.com/app-sre/qontract-schemas/pull/338
=> make RDS work

reconcile/change_owners/change_owners.py, reconcile/change_owners/decision.py, reconcile/test/test_change_owners.py
part of https://issues.redhat.com/browse/APPSRE-6638
in some cases, we want changes to be automatically accepted and merged. such cases do not require a human review.
to define such cases, we can use the bot user behind our automations as an approver. if the bot is the only approver for a change - consider the change approved.
app-interface implementation: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52773
=> [change-owners] auto approve when bot is the only approver

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/gql_definitions/change_owners/queries/self_service_roles.gql, reconcile/gql_definitions/change_owners/queries/self_service_roles.py, reconcile/test/fixtures/change_owners/changetype_role_member.yaml, reconcile/test/test_change_owners.py
verify that the datafiles referenced in `Role_v1.self_service` together with a `change-type` match the `contextSchema` of that `change-type`. fail the integration if they don't match
ref https://issues.redhat.com/browse/APPSRE-6628
=> [change-owners] validate context schema for role assignments

tools/qontract_cli.py
the code currently assumes that a repo has a `pr-check` job to determine what is the regex expression of the job that indicates `/retest`. but what if the repo doesn't have a pr-check job?
this PR handles that case.
=> [qontract-cli] get\app-interface-review-queue handle no pr-check job

reconcile/ocm_upgrade_scheduler.py, reconcile/test/test_utils_ocm.py, reconcile/utils/ocm.py
This fixes the case where a cluster is removed from OCM but remains in the ocm schema definition.
However, there seem to be other subsequent issues in this case. I will need to dig more.
=> Fix issues when a cluster is deleted in OCM

.pylintrc, reconcile/ocm_upgrade_scheduler.py, reconcile/ocm_upgrade_scheduler_org.py, reconcile/queries.py, reconcile/test/test_ocm_upgrade_scheduler.py, reconcile/test/test_utils_cluster_version_data.py, reconcile/utils/cluster_version_data.py, reconcile/utils/ocm.py, tools/qontract_cli.py
[APPSRE-6549](https://issues.redhat.com/browse/APPSRE-6549)
Allow to inherit cluster version data information from one org to an other. Currently, this is limited to soak days. We will add current version stats (lowest current version, ...) in a subsequent PR.
The first commit is the implementation. The second one is a refactor of the version history deep-dict into a set of dataclasses.
Depends on https://github.com/app-sre/qontract-schemas/pull/330
=> Cluster upgrade shared version data

reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-6638
follows up on #3028
saas-file-validator is failing due to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/53099
=> allow bots to own saas files

reconcile/gql_definitions/glitchtip/glitchtip_instance.gql, reconcile/gql_definitions/glitchtip/glitchtip_instance.py, reconcile/gql_definitions/glitchtip/glitchtip_project.gql, reconcile/gql_definitions/glitchtip/glitchtip_project.py, reconcile/test/fixtures/glitchtip/desire_state_projects.yml
* Glitchtip switched to Red Hat SSO as IDP, therefore the `github_username` attribute is obsolete.
* Remove unused `organizations` attribute from `glitchtip.instance` object
[APPSRE-6615](https://issues.redhat.com/browse/APPSRE-6615)
=> [glitchtip] cleanup

reconcile/cli.py, reconcile/ocm_cluster_admin.py, reconcile/queries.py, reconcile/utils/ocm.py, tools/qontract_cli.py
this integration enables `cluster-admin` via OCM API.
this will prevent us from requesting this for every cluster we create. this integration will act once a `clusterAdminAutomationToken` is added to a cluster file.
automating based on this SOP: https://github.com/openshift/ops-sop/blob/master/v4/utils/cluster-admin
app-interface counterpart: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52546
=> [ocm-cluster-admin] introduce integration

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, reconcile/utils/aws_api.py
probably the oldest tech debt around vpc peerings.
when we started out, we only had `account-vpc`. it could mostly manage the peering connection, and that's it. no route management support.
until today!
depends on https://github.com/app-sre/qontract-schemas/pull/347
`manageRoutes` currently exists on `account-vpc` connections to say "manage routes on the cluster side". we are adding a new field for backwards compatibility, and to allow a migration from routes managed elsewhere to being managed via app-interface.
once all `account-vpc` connections have both `manageRoutes` and `manageAccountRoutes`, we can refactor this PR and remove `manageAccountRoutes` altogether.
=> add support to manage routes in account-vpc on the aws side

reconcile/gabi_authorized_users.py, reconcile/queries.py, reconcile/test/fixtures/gabi_authorized_users/apply.yml
Use usernames for Gabi authentication based on configured cluster authentication methods.
[APPSRE-6612](https://issues.redhat.com/browse/APPSRE-6612)
=> [gabi-authorized-users] OIDC support

reconcile/openshift_resources_base.py
Add `urlescape` and `urlunescape` to Jinja2 for use in resource templates either as a filter or as a function to be run directly. Both additions are simple wrappers that expose `urllib.parse.quote()` and `urllib.parse.quote_plus()` to the template engine.
This change enables users to escape and unescape reserved characters using URL encoding, making a string value safe to use as URL components or turning it back into a raw string should it be currently URL-encoded.
Since both additions are wrappers around the standard library functions, the approach to handling character encoding during escaping and unescaping would be the same as what the library functions currently offer - there is a strong bias towards supporting UTF-8 as the default encoding that has also been preserved.
Related: …
=> APPSRE-6665: Add urlescape and urlunescape to Jinja2

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/utils/gql.py
an MR that has no detected changes, will not be marked as self-serviceable anymore. additonally, several log statements for info and debug loglevel have been introduce to make it easier to figure out why no changes were detected on an MR
=> [change-owners] MR with no changes is not self-serviceable + more logs

reconcile/gabi_authorized_users.py, reconcile/queries.py, reconcile/test/fixtures/gabi_authorized_users/apply.yml
Reverts app-sre/qontract-reconcile#3046
The OIDC related changes in qontract-reconcile and qontract-schemas break FedRAMP environment authentication. We have to revert and align on a strategy that can exist in parallel.
re: https://coreos.slack.com/archives/GGC2A0MS8/p1670432900179959
=> Revert "[gabi-authorized-users] OIDC support"

reconcile/openshift_users.py, reconcile/queries.py
Reverts app-sre/qontract-reconcile#3032
The OIDC related changes in qontract-reconcile and qontract-schemas break FedRAMP environment authentication. We have to revert and align on a strategy that can exist in parallel.
re: https://coreos.slack.com/archives/GGC2A0MS8/p1670432900179959
=> Revert "[openshift-users] OIDC support"

reconcile/jenkins_job_builds_cleaner.py
Many Jenkins integrations disable SSL verification. 
With us using this integration now in FedRamp, we need to disable verification for the CronJob to run as we are using a DigiCert certificate tied with a private Route53 DNS name for our Jenkins instance.
[APPSRE-6691](https://issues.redhat.com/browse/APPSRE-6691)
=> Disable ssl verification for jenkins job builds cleaner

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/diff.py, reconcile/change_owners/tester.py, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_coverage.py, reconcile/test/change_owners/test_change_type_diff.py, reconcile/test/change_owners/test_change_type_diff_splitting.py, reconcile/test/change_owners/test_change_type_inheritance.py, reconcile/test/change_owners/test_change_type_priorities.py, reconcile/test/change_owners/test_change_type_processor.py
When the detected changes within a file are too rough/high level, only high level `change-types` would be able to cover them. e.g. if a new file is introduced, the detected change would be the entire file, only coverable by the top-level JSONPath placeholder for the file-root '$'. Such `change-types` are the opposite of what we intend to do with `fine-grained` permissions.
Split high level changes in smaller changes so they can be covered by `change-types`. The process of splitting is driven by the involved change-types, so that the resulting splits are as fine as they are required to allow the change-types to have effect, but not finer than required in order to keep the list of changes as concise as possible.
The center-piece of this change is the list of splits (`_split_into`) within …
=> [change-owners] split high level changes into fine grained diffs

reconcile/closedbox_endpoint_monitoring_base.py
We currently only allow for monitoring from one cluster, as we can have multiple openshift-customer-monitoring namespaces in different clusters.
=> Move to list for namespace gathering in monitoring

reconcile/gitlab_housekeeping.py, reconcile/test/test_gitlab_housekeeping.py
These metrics should provide more data for guiding future enhancements related to speeding up gitlab-housekeeping, and improving the throughput of the integration.
I tested this manually as well by running the integration and ensuring that the metric calls returned proper data with the `collect()` method call. Any metrics that didn't run in dry-run mode were moved out of the conditional to make sure that they still work as expected.
Related: https://issues.redhat.com/browse/APPSRE-6653
=> Add integration-specific metrics for gitlab-housekeeping

reconcile/gitlab_housekeeping.py
It looks like the exception wasn't being bubbled up properly, but data was trying to be accessed that didn't exist. I'll look to replace this shortly with some improvements to type hints to catch this in the future.
=> Remove broken time-to-merge metric in gitlab-housekeeping

reconcile/openshift_users.py, reconcile/queries.py
`openshift-users` must consider all user identities based on cluster auth configuration, not just GitHub ones.
APPSRE-6646
Reapply reverted https://github.com/app-sre/qontract-reconcile/pull/3032
=> [openshift-users] OIDC support (#3032)

reconcile/queries.py
Adds missing query fields, right now ocm-update-recommended-version creates a new MR all the time, cause the fields are not set and thus it shows a diff.
=> Add channel and initialversion

reconcile/gitlab_housekeeping.py
Related: https://issues.redhat.com/browse/APPSRE-6653
Also, related to draft PR #3050 which introduced multiple ideas for improving the performance of gitlab-housekeeping, that are now being addressed as separate MRs.
After a week of data, we only found 3 instances where labels were empty, but after calling the GitLab API again, labels were returned. All of these cases appear to be related to timing because the log entries matched when the first label was added to the MR, to the minute. In these cases, `gitlab-housekeeping` would have ignored these MRs for the first run, and then found them on the next run.
The performance improvements are 10-30 second reduction is run time of the integration (close to 20% reduction) and 80 fewer API calls to GitLab (>10% reduction). These performance …
=> Skip extra GitLab labels API calls in gitlab-housekeeping

reconcile/change_owners/approver.py, reconcile/change_owners/bundle.py, reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/decision.py, reconcile/change_owners/implicit_ownership.py, reconcile/change_owners/self_service_roles.py, reconcile/gql_definitions/change_owners/queries/change_types.gql, reconcile/gql_definitions/change_owners/queries/change_types.py, reconcile/gql_definitions/introspection.json, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_context.py, reconcile/test/change_owners/test_change_type_coverage.py, reconcile/test/change_owners/test_change_type_decision.py, reconcile/test/change_owners/test_change_type_diff.py, reconcile/test/change_owners/test_change_type_diff_splitting.py, reconcile/test/change_owners/test_change_type_implicit_ownership.py, reconcile/test/change_owners/test_change_type_inheritance.py, reconcile/test/change_owners/test_change_type_various.py, reconcile/test/fixtures/change_owners/changetype_cluster_owner.yml, reconcile/test/fixtures/change_owners/changetype_role_member.yaml, reconcile/test/fixtures/change_owners/changetype_saas_file.yaml, reconcile/test/fixtures/change_owners/changetype_secret_promoter.yaml
For certain changes, the natural approvers can be found in the datafiles themselves and would not require explicit ownership via roles. To reduce the need for such explicit ownership, we can make change-types implicitly applicable on changes.
The following example enables users to approve updates on their `public_gpg_key`s. The `jsonPathSelector` is the mechanism to find a reference to an approver, either a `/access/user-1.yml` or `/access/bot-1.yml` object. In this example the selector is `$.path` which finds the approver in the changed file itself.
```yaml
$schema: /app-interface/change-type-1.yml
...
contextSchema: /access/user-1.yml
changes:
- public_gpg_key
implicitOwnership:
- provider: jsonPath
jsonPathSelector: $.path
```
the only commit introducing actual changes is …
=> [change-types] implicit ownership for change-types

grafana-dashboards/grafana-dashboard-integrations.configmap.yaml
Grafana is on a public cluster while integrations run on an internal cluster. We can use skupper to access metrics.
=> use skupper to access internal integrations prometheus

reconcile/utils/mr/ocm_upgrade_scheduler_org_updates.py
Setting `upgrade_policy_clusters` was not actually deleting items from the initial `upgradePolicyClusters` list.
=> fix ocm cluster upgrade-policy deletion

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager-fedramp.yaml, reconcile/test/fixtures/helm/enable_google_chat.yml
[APPSRE-6696](https://issues.redhat.com/browse/APPSRE-6696)
Fluentd in FedRamp often runs into rate-limiting 429 errors when trying to post logs to Google Chat. This MR adds [buffering](https://docs.fluentd.org/configuration/buffer-section) to a file with Fluentd, meaning that a buffer volume will be created and logs will be written to there prior to being posted to GChat. Every 15 seconds these buffers will be emptied and the messages will be posted. 
Retry logic will allow Fluentd to retry posting logs if it runs into rate limits.
=> Fluentd buffering for GChat

reconcile/openshift_network_policies.py
related to https://issues.redhat.com/browse/APPSRE-6737
to be able to manage NetworkPolicy objects in protected namespaces as cluster admin
=> [openshift-network-policies] support cluster admin

tools/qontract_cli.py
https://redhat.pagerduty.com/incidents/Q3PTYHHQPPS51L
```
File "/usr/local/bin/qontract-cli", line 8, in <module>
sys.exit(root())
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
File …
```
=> qontract-cli/get/clusters-egress-ips aws no init users

tools/qontract_cli.py
=> Fix missing path excpt in q-cli template command

requirements/requirements-type.txt
Synch qontract-reconcile with latest qenerate release. There are no changes to generated classes, so this will not have any special effect.
=> new qenerate version - no changes in generated classes

reconcile/cli.py, reconcile/ocm_addons_upgrade_tests_trigger.py, reconcile/queries.py, reconcile/utils/ocm.py
https://issues.redhat.com/browse/APPSRE-6756
depends on https://github.com/app-sre/qontract-schemas/pull/363
this integration will trigger jobs in jenkins following an upgrade of an addon for all clusters within an OCM org.
=> [ocm-addons-upgrade-tests-trigger] introduce new integration

reconcile/dashdotdb_base.py, reconcile/dashdotdb_cso.py, reconcile/dashdotdb_dvo.py, reconcile/dashdotdb_slo.py, setup.cfg
Introducing more types to dashdotdb-* integrations by using typed secret reader in dashdotdb_base.
Ran each integration locally in dry-run mode for verification.
This is not urgent and thus will be merged next week after feature freeze period is over.
=> APPSRE-6609 dashdotdb-base uses typed secret_reader

README.md
Qenerate examples directory does not exist any longer. We now have a sufficient amount for pretty much every use-case in our code base, so we can reduce verbosity of the README.
=> Update qenerate docu

reconcile/utils/terrascript_aws_client.py
At the moment is not possible to run a single node instance of opensearch, as if we try to turn off zone awareness this check will fire.
If we try to work around it, schema validation will block it.
=> do not check for AZ count to equal number of subnet if zone awareness is disabled

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager-fedramp.yaml, reconcile/test/fixtures/helm/enable_google_chat.yml
Related to #3085. After monitoring the changes in FedRamp over the past week, noticed that sometimes chunks don't get correctly sent and are dropped. 
This change updates buffering settings to set a default wait time of 30 seconds before a retry and then increase the max number of retries to 5 to decrease the likelihood that chunks are dropped.
See https://docs.fluentd.org/configuration/buffer-section for documentation.
Current errors:
```
2022-12-26 11:33:59 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=81.73582330183126 slow_flush_log_threshold=20.0 plugin_id="object:c2d8"
2022-12-27 09:12:50 +0000 [warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2022-12-27 09:12:51 +0000 chunk="5f0cba6ec3cd3fc6354c1ff5f47ee147" …
```
=> Adjust GChat Rate Limit Settings 

dockerfiles/Dockerfile
Depends on:
- https://github.com/app-sre/container-images/pull/63
- https://github.com/app-sre/container-images/pull/64
Related: [APPSRE-6370](https://issues.redhat.com/browse/APPSRE-6370)
=> APPSRE-6370: Update base and builder images release tags

reconcile/test/glitchtip/conftest.py, reconcile/test/glitchtip/test_glitchtip.py, reconcile/test/glitchtip/test_glitchtip_reconciler.py, reconcile/test/glitchtip/test_utils_glitchtip_client.py, reconcile/test/glitchtip/test_utils_glitchtip_models.py, setup.cfg
=> [glitchtip] add type hints to glitchtip tests

reconcile/change_owners/decision.py, reconcile/test/change_owners/test_change_type_decision.py
leading or trailing spaces in approval rendered the approval comment invalid. this fix ignores such spaces
=> [change-owners] ignore leading/trailing spaces in approval comments

reconcile/utils/terrascript_aws_client.py
FedRAMP Insights initiative needs to leverage AMS and a new oauth scope which does not currently exist. This PR is to add the scope to Cognito in FedRAMP so a service account can be created with this new scope.
@aleccohan can address any questions for more details as the originator of the request
=> adds insights service account oauth scope to ocm resource server

reconcile/utils/ocm.py
I had a closer look at ocm.py and might have spotted an issue. The OCM query looks like this:
```graphql
ocm {
name
url
accessTokenClientId
accessTokenUrl
accessTokenClientSecret {
... VaultSecret
}
blockedVersions
inheritVersionData {
name
publishVersionData {
name
}
}
sectors {
name
dependencies {
name
ocm {
name
}
}
}
}
```
I.e., `publishedVersionData` is part of `inheritVersionData`. Running this against latest app-interface shows that we do not have any occurrence of inheritVersionData, which might explain why this didnt produce any errors yet.
=> Remove redundant published version data

reconcile/utils/terrascript_aws_client.py
Addresses error encountered when attempting to provision supporting role for cloudwatch within FR
=> Add support for aws gov partition within `populate_tf_resource_cloudwatch`

reconcile/ocm_upgrade_scheduler.py, reconcile/queries.py, reconcile/test/test_ocm_upgrade_scheduler.py, reconcile/test/test_utils_cluster_version_data.py, reconcile/test/test_utils_ocm.py, reconcile/utils/cluster_version_data.py, reconcile/utils/ocm.py
[APPSRE-6675](https://issues.redhat.com/browse/APPSRE-6675)
The first implementation of cluster upgrade sectors ([APPSRE-6545](https://issues.redhat.com/browse/APPSRE-6545)) allowed to reference sectors cross orgs. This implementation has several drawbacks:
- knowledge of sectors from one org to the other, which may not be the case/needed/wanted and makes changes to sector list more complex.
- complex code where a sector map needs to be global. It also forbids (or make complex) sharding of integrations that use this feature.
This PR changes this by relying on the `inheritVersionData` flag in the ocm org schema:
if `sector` is defined in the cluster upgradepolicy and the cluster org inherits from an other one, we will allow an upgrade to a version if either:
- all the cluster `workloads` …
=> cluster upgrade cross org sector dependencies

reconcile/slack_usergroups.py, reconcile/utils/pagerduty_api.py
pagerduty raises an exception for invalid resource_ids, slack-usergroups reconciles all user groups but exits with exit code 1 when an error occurs.
Ticket: [APPSRE-6621](https://issues.redhat.com/browse/APPSRE-6621)
=> invalid pagerduty IDs

reconcile/change_owners/bundle.py, reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/decision.py, reconcile/change_owners/implicit_ownership.py, reconcile/change_owners/self_service_roles.py, reconcile/change_owners/tester.py, reconcile/gql_definitions/change_owners/queries/change_types.gql, reconcile/gql_definitions/change_owners/queries/change_types.py, reconcile/gql_definitions/introspection.json, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_context.py, reconcile/test/change_owners/test_change_type_coverage.py, reconcile/test/change_owners/test_change_type_decision.py, reconcile/test/change_owners/test_change_type_diff_splitting.py, reconcile/test/change_owners/test_change_type_implicit_ownership.py, reconcile/test/change_owners/test_change_type_inheritance.py, reconcile/test/change_owners/test_change_type_integration.py, reconcile/test/change_owners/test_change_type_ownership_expansion.py, reconcile/test/change_owners/test_change_type_priorities.py, reconcile/test/change_owners/test_change_type_processor.py, reconcile/test/change_owners/test_change_type_various.py, reconcile/utils/gql.py, tools/qontract_cli.py
Add a new change provider named change-type to /app-interface/change-type-1.yml#changes.provider that can reference an existing change-type and put it into the context of changes.context.
```yaml
name: app-owner
...
changes:
- provider: change-type         <-- new provider
changeTypes:
- $ref: namespace-owner.yml   <-- puts the existing change-type ...
context:                      <-- ... into a new context
selector: app.'$ref'
```
This makes the referenced change-type usable in the ownership context of the referencing change-type. It redurced ownership management toil and makes the change-types reusable. It also enables the definition of higher level concepts for ownership, e.g. the owned entity is an app and by putting existing change-types into the context of the app change-type, …
=> reusable change-types through composition

reconcile/change_owners/change_types.py, reconcile/test/change_owners/test_change_type_ownership_expansion.py, reconcile/test/change_owners/test_change_type_various.py
if a change-type with context detection (`changes[provider=jsonpath].context` is used in conjunction with ownership expansion (`changes[provider=change-type]`), the ownership calculation is faulty.
e.g.
```yaml
name: cluster-owner
changes:
- provider: change-type
changeTypes:
- $ref: /app-interface/changetype/saas-file-namespace-target-self-service.yml
changeSchema: /openshift/namespace-1.yml
context:
selector: cluster.'$ref'
---
name: saas-file-namespace-target
contextType: datafile
contextSchema: /openshift/namespace-1.yml
changes:
- provider: jsonPath
changeSchema: /app-sre/saas-file-2.yml
jsonPathSelectors:
- resourceTemplates[*].targets[?(@.namespace.'$ref')=='{{ ctx_file_path }}']
context:
selector: resourceTemplates[*].targets[*].namespace.'$ref'
when: added
```
this fix resolves …
=> [change-owners] bugfix for ownership-expansion with context detection

tools/qontract_cli.py
OCM orgs fleet upgrades are managed by a dedicated integration, with a dedicated state. We were not relying on the good state for this output. So we were not getting any version history nor stats.
=> use correct state in qontract-cli ocm-fleet-upgrade-policies

reconcile/ocm_addons_upgrade_scheduler_org.py, reconcile/utils/ocm.py, tools/qontract_cli.py
https://issues.redhat.com/browse/APPSRE-6809
This is a bit more simple than clusters' output as addons can be upgraded to only one version. We can review later if more fancy display is deemed necessary (🎉 )
Example output:
https://gitlab.cee.redhat.com/-/snippets/6206
=> qontract-cli output for ocm addon upgrade policies

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager-fedramp.yaml, openshift/qontract-manager.yaml, reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml, reconcile/test/fixtures/helm/aws_account_shards.yml, reconcile/test/fixtures/helm/basic.yml, reconcile/test/fixtures/helm/cache.yml, reconcile/test/fixtures/helm/command.yml, reconcile/test/fixtures/helm/disable_unleash.yml, reconcile/test/fixtures/helm/enable_google_chat.yml, reconcile/test/fixtures/helm/environment_aware.yml, reconcile/test/fixtures/helm/exclude_service.yml, reconcile/test/fixtures/helm/extra_args.yml, reconcile/test/fixtures/helm/extra_env.yml, reconcile/test/fixtures/helm/integrations_manager.yml, reconcile/test/fixtures/helm/internal_certificates.yml, reconcile/test/fixtures/helm/logs_slack.yml, reconcile/test/fixtures/helm/shards.yml, reconcile/test/fixtures/helm/sleep_duration.yml, reconcile/test/fixtures/helm/state.yml, reconcile/test/fixtures/helm/storage.yml, reconcile/test/fixtures/helm/trigger.yml
Use [fluentd read_from_head](https://docs.fluentd.org/input/tail#read_from_head) to log all integration output from the start, even if fluentd takes more time than the integration to start.
This should avoid missing early logs on pod startup.
I will check on stage once merged if fluentd starts correctly.
=> fluentd read_from_head

reconcile/slack_usergroups.py
After an error occurred, the global `error_occurred` flag was still set. Reset it on each integration run to avoid that.
[APPSRE-6818](https://issues.redhat.com/browse/APPSRE-6818)
=> [slack-usergroups] reset error flag at startup

reconcile/utils/cluster_version_data.py
with `exclude_unset` the `Workload` we're adding for new versions (such as `4.12`) are considered unset as their `soak_days` remain `0`. this means new versions don't get reported (and accumulated) anymore in the state.
We keep `exclude_none` to not store `inherited` data when there are none..
=> bug fix: version_data does not report any histiry on new versions

reconcile/change_owners/approver.py, reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/self_service_roles.py, reconcile/gql_definitions/change_owners/queries/self_service_roles.gql, reconcile/gql_definitions/change_owners/queries/self_service_roles.py, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_self_service_roles.py
this change lists approver group contact information as part of the MR change report. this way, MR authors have an easier time identifying a communication channel to approach the approver group as a whole instead of reaching out to individuals.
the slack user groups and gitlab user groups of a `RoleV1` are the relevant group communication information used for this feature.
e.g. the following message will be available within an MR
```
Reach out to approvers for reviews on
* Slack group abc
* GitLab group def
```
Ref: https://issues.redhat.com/browse/APPSRE-6847
=> [change-owners] show approver groups on merge requests

reconcile/change_owners/change_owners.py, reconcile/change_owners/decision.py, reconcile/test/change_owners/test_change_type_decision.py, reconcile/utils/gitlab_api.py
part of https://issues.redhat.com/browse/APPSRE-6786
similar to #3028
when the author is the only approver - it's approved. tests will block merges if something is wrong. the user can only `/hold`.
=> [change-owners] auto approve when author is the only approver

tools/qontract_cli.py
Attempting to use alert-to-receiver on [this rules file](https://gitlab.cee.redhat.com/service/app-interface/-/blob/f5595a956235d08e6e807cb8d0f159e87c38a9ae/resources/observability/prometheusrules/hive-production-capacity.prometheusrules.yaml) resulted in an exception:
```
File "/home/mold/gitwork/qontract-reconcile/venv/bin/qontract-cli", line 33, in <module>
sys.exit(load_entry_point('qontract-reconcile', 'console_scripts', 'qontract-cli')())
File "/home/mold/gitwork/qontract-reconcile/venv/lib64/python3.9/site-packages/click/core.py", line 1130, in __call__
File "/home/mold/gitwork/qontract-reconcile/venv/lib64/python3.9/site-packages/click/core.py", line 1055, in main
File …
```
=> alert-to-receiver: ignore rules with no alerts/labels

reconcile/ocm_oidc_idp.py
Using the standard OIDC claims avoids additional user-defined claims and setup errors for all OIDC clients.
APPSRE-6795
=> [ocm-oidc-idp] use standard OIDC claim names

reconcile/cli.py, reconcile/gql_definitions/introspection.json, reconcile/test/runtime/demo_integration.py, reconcile/test/runtime/demo_integration_early_exit.py, reconcile/test/runtime/demo_integration_no_run_func.py, reconcile/test/runtime/demo_integration_shard_config.py, reconcile/test/runtime/fixtures.py, reconcile/test/runtime/test_utils_desired_state_diff.py, reconcile/test/runtime/test_utils_integration.py, reconcile/test/runtime/test_utils_runtime_runner.py, reconcile/test/test_utils_jsonpath.py, reconcile/utils/jsonpath.py, reconcile/utils/runtime/desired_state_diff.py, reconcile/utils/runtime/integration.py, reconcile/utils/runtime/runner.py, setup.py
This PR refactors the current `cli.py` based integration startup function and enhances it with `sharded` dry-runs.
REVIEW COMMIT BY COMMIT
commit 1
The main logic for integration running has been moved to the `reconcile.utils.runtime` module. An integration and the required callback hooks `run` and `get_early_exit_desired_state` are now part of a class `QontractReconcileIntegration`. New integrations can subclass this one directly and implement the hook methods. Existing integrations are wrapped during startup into an `ModuleBasedQontractReconcileIntegration`. This way the code in `reconcile.utils.runtime.runner` deal only with `QontractReconcileIntegration` and can rely on a typed interface.
And integration can be executed by constructing a `IntegrationRunConfiguration` object which …
=> integration runner refactor + sharded dry-runs

reconcile/change_owners/bundle.py, reconcile/test/change_owners/test_change_type_bundle.py
this PR fixes a bug that occures when ownership expansion happens on files that are freshly introduced into the app-interface state
=> [change-owners] bugfix ownership resolution

.pylintrc, reconcile/test/test_status_page_components.py, reconcile/utils/statuspage/atlassian.py
Pylint recently started complaining about `broad-exception-raised` in multiple modules.
The errors seem to come from the latest pylint release https://github.com/PyCQA/pylint/releases/tag/v2.16.0
Since we explicitly do not want to pin mypy, I guess the same should hold true for pylint.
=> pylint complains about broad exceptions

reconcile/quay_base.py, reconcile/quay_mirror_org.py, reconcile/queries.py, reconcile/test/test_quay_mirror.py
This mimics how we include/exclude tags in quay-mirror.
part of APPSRE-6916
depends on schema changes in https://github.com/app-sre/qontract-schemas/pull/374
=> Add filtering capabilities to quay-mirror-org

reconcile/cli.py, reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py, reconcile/utils/terrascript_aws_client.py
JIRA: [APPSRE-6586]( https://issues.redhat.com/browse/APPSRE-6586)
With `qontract-server` configured with `app-interface-dev-data` do the following.
Run `terraform-resources` without any account filter in dry-run mode:
```
APP_INTERFACE_STATE_BUCKET="a" APP_INTERFACE_STATE_BUCKET_ACCOUNT="a" qontract-reconcile --config config.dev.toml --log-level INFO --dry-run terraform-resources
```
Run `terraform-resources` passing one account name filter in dry-run mode:
```
APP_INTERFACE_STATE_BUCKET="a" APP_INTERFACE_STATE_BUCKET_ACCOUNT="a" qontract-reconcile --config config.dev.toml --log-level INFO --dry-run terraform-resources --account-name=app-int-example-01
```
Verify that the resources belonging to account `app-int-example-01` appears in the second output are the same that appear in the …
=> Support multiple aws accounts to act in terraform resources

reconcile/utils/mr/auto_promoter.py
if a null element makes it into the promotions list of an `AutoPromoter` message, the processing fails with an error. ignore those elmenets is a quick fix to resolve the issue.
a proper solution would prevent such elements from being produced. right now we don't know yet how they come into existence.
=> [autopromoter] ignore null elements in the promotions list

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/decision.py, reconcile/test/change_owners/test_change_type_decision.py
Currently, a user adding a hold on an MR is the only one able to remove that hold with `/hold cancel`. this might block the MR from being merged even if another role member decides that it is now good to proceed.
this change fixes the situation while still making sure that a person from another team can't cancel another persons hold.
```
user 1 from role A: /hold
user 2 from role A: /hold cancel
result: hold is canceled
```
```
user 1 from role A: /hold
user 2 from role B: /hold cancel
result: MR is still on hold
```
https://issues.redhat.com/browse/APPSRE-6942
=> [change-owners] role members can cancel /lgtm and /hold from role peers

reconcile/cli.py, reconcile/test/runtime/test_utils_integration.py, reconcile/utils/runtime/integration.py
tf-resources got passed the shard arg multiple times to the run function: once as arg, once as kwarg
right now, sharded dry-runs rely on the shard arg to be passed exclusively as kwarg
=> [terraform-resources] fix sharded dry-runs

reconcile/terraform_users.py
terraform-users is an integration that runs very long if it has to process all aws accounts. by running it only on affected aws-accounts, the dry-run runtime is a fraction of what it is when it runs in full.
like in https://github.com/app-sre/qontract-reconcile/pull/3149, the `IDENTIFIER_FIELD_NAME` field is introduced to speed up the fine grained diff extraction between the involved desired states.
https://issues.redhat.com/browse/APPSRE-6967
=> [terraform-users] sharded pr-checks on affected accounts

reconcile/change_owners/change_types.py, reconcile/change_owners/implicit_ownership.py, reconcile/change_owners/self_service_roles.py, reconcile/test/change_owners/test_change_type_context.py, reconcile/test/change_owners/test_change_type_ownership_expansion.py
right now, change-type ownership expansion forbids cycles to protect against endless loops during the expansion process.
but still, there are some legitimate usecases where self-referencing change-types are meaningful (self-reference == shortest cycle possible), e.g. ownership of an app grants ownership on child-apps.
such a cycle is not automatically problematic, it depends on the actual data, e.g. is there something like `app A -parent-> app B -parent-> app A`.
the protective means against such situations can be at ownership expansion runtime instead of change-type declaration loading/verification.
this change replaces the static configuration verification against cycle detection during runtime.
=> [change-owners] prevent cycles in ownership expansion on data level

reconcile/openshift_base.py
if a `kind: Service` has `metadata.annotations` explicitely set to `null` in desired state, processing can fail under certain circumstances (related to serving-cert Secrets).
https://issues.redhat.com/browse/APPSRE-6965
=> openshift resource processing fix for Service with `null` annotations

reconcile/test/test_make.py, reconcile/utils/git.py
our ci pipelines fails if there are modified files in the work dir after certain generational tasks (helm chart, qenerate files, file reformats). if that happens, it is quite hard/annoying to debug and to find the affected files.
this PR prints those changes to ease the debug process.
=> show diffs when modified files are present during build

reconcile/openshift_resources.py, reconcile/openshift_resources_base.py, reconcile/openshift_routes.py, reconcile/openshift_vault_secrets.py
enables `openshift-resources`, `openshift-routes` and `openshift-vault-secrets` to run their dry-run operations on affected clusters only for more performance and cluster isolation.
https://issues.redhat.com/browse/APPSRE-6785
this is just temporary work to benefit from PR check speed and isolation until @lechuk47 s work on partitioning/sharding has been implemented - https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/55171
=> [openshift-resources-*] dry-run on affected clusters only

reconcile/test/runtime/test_utils_desired_state_diff.py, reconcile/utils/runtime/desired_state_diff.py
due to a bug, too many affected shards were extracted from desired state diff, which prevented some sharded dry-runs due to the shard-maximum integrations can opt-in (tf-resources, tf-users, openshift-resources, ...).
this part of the code was not properly tested before. this PR therefore also adds test coverage.
https://issues.redhat.com/browse/APPSRE-6972
=> [integration-runtime] fix extraction of affected shards from PR

reconcile/test/fixtures/oc_connection_parameters/namespace_with_admin.yml, reconcile/test/oc/test_oc_connection_parameters.py, reconcile/test/test_jump_host.py, reconcile/utils/jump_host.py, reconcile/utils/oc.py, reconcile/utils/oc_connection_parameters.py, reconcile/utils/oc_map.py, requirements/requirements-test.txt, setup.cfg
Add types and tests for jumphost implementation. This is required to have a typed `OCMap` class.
Follow-up of `OC_Map` refactor https://github.com/app-sre/qontract-reconcile/pull/3154
After this is merged, another PR will be opened to make `OCDeprecated` and `OCNative` fully compatible with new `OCMap` (in a backwards-compatible manner).
**Test**
- Tested with new `OCMap` class (dashdotdb-cso integration)
- Tested with old `OC_Map` class (openshift-users integration)
=> APPSRE-6609 typed jumphost (OC_Map refactor Part 2)

reconcile/glitchtip/integration.py, reconcile/gql_definitions/glitchtip/glitchtip_instance.gql, reconcile/gql_definitions/glitchtip/glitchtip_instance.py, reconcile/gql_definitions/introspection.json
Refactor `glitchtip-instance-1` and get the automation user email address from a vault secret instead of specifying it manually. The vault secret is used by the glitchtip application during the startup to create/reconcile the API users.
This avoids glitchtip instance misconfigurations.
Ticket: [APPSRE-6904](https://issues.redhat.com/browse/APPSRE-6904)
Hint for the reviewer:
I've tested the glitchtip integration locally against a local glitchtip instance.
=> [glitchtip] get automation user email from vault secret

reconcile/change_owners/change_owners.py, reconcile/change_owners/implicit_ownership.py
the change-owners integration writes a table of all detected bundle changes to an MR comment for give the reviewer an overview about what changes.
changes in the app-interface repo, that are not part of a bundle are not shown in this difference table. they are invisible to change-owners. but change-owners know that such changes exist (a.k.a. non-authoritative-mode) and can make the reviewer aware of such changes by leaving a note on the MR.
=> [change-owners] awareness for changes outside of the bundle

reconcile/openshift_resources_base.py
the `sharedResources` field of a namespaces desired state gets aggreated into the `openshiftResources` fields during desired state loading. after that, the `sharedResources` field itself it not required anymore. removing it has positive effects on the diffing process between desired states.
=> [openshift-resources] remove sharedResources from desired state

reconcile/openshift_resources.py, reconcile/openshift_resources_base.py
when openshift-resources-base (so openshift-resource, vaults-secrets, etc) are executed with cluster or namespace filtering, there might be no namespace left after filtering. this does not necessarily indicate a usage issue but can happen during cluster deprovisioning.
this fix prevents those integrations to fail in such scenarios, but gracefully exits with a log message.
=> [openshift-resources] no namespaces left after cluster-filtering

helm/qontract-reconcile/templates/template.yaml, reconcile/integrations_manager.py, reconcile/test/test_integrations_manager.py
Reverts app-sre/qontract-reconcile#3116
error spotted in stage
```
[2023-02-08 13:31:47] [ERROR] [openshift_base.py:_realize_resource_data:665] - [xxx/app-interface-stage] [https://api.xxxx.com:6443]: Error from server (BadRequest): error when creating "STDIN": Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field LabelSelector.spec.selector.matchLabels of type string
```
=> Revert "[integration-manager] sharding labels for integration workload"

reconcile/skupper_network/reconciler.py
The connection token must be created on the receiver site instead of the source site.
[APPSRE-6995](https://issues.redhat.com/browse/APPSRE-6995)
=> [skupper] create connection token on receiver site

helm/qontract-reconcile/templates/template.yaml, reconcile/integrations_manager.py, reconcile/test/test_integrations_manager.py
the current matchLabels on a Deployment are not sufficient to catch only the pods spawned by ReplicaSets of the deployment itself, because the app label alone is the same for all potential shards of an integration.
this has no negative effect because the ReplicaSets still handle pod creation/termination correctly. the only downside is the incorrect pod filtering within the openshift UI within Deployment/Pods.
to fix this, we will add a shard label qontract_reconcile_integration_shard to both the pod template and the matchLabels of the deployment if applicable.
the first attempt of this PR failed because number based shard labels have not been cast to strings and the resulting `Deployment` manifest was invalid. this has been addressed in this PR and specifically covered by a test …
=> [integration-manager] sharding labels for integration workload (2nd try)

reconcile/utils/state.py
This will allow integrations to use the new secret_reader implementations with the `State` class. The new secret_reader class is fully backwards compatible, i.e., this shouldn't cause any difference and is really just a matter of type declaration.
=> APPSRE-6941 new secret_reader for state

reconcile/skupper_network/integration.py, reconcile/skupper_network/models.py, reconcile/test/skupper_network/test_skupper_network_models.py
Spawn skupper networks between sites on internal clusters because all internal clusters can reach each other without peerings.
[APPSRE-6997](https://issues.redhat.com/browse/APPSRE-6997)
=> [skupper-network] internal clusters don't need a peering to reach each other

reconcile/skupper_network/models.py, reconcile/test/skupper_network/test_skupper_network_models.py
Shrink the connection-token `token-receiver` label to an upper limit of 63 characters.
[APPSRE-6993](https://issues.redhat.com/browse/APPSRE-6993)
=> [skupper-network] k8s labels have a 63 characters limit

reconcile/utils/vault.py
This change is related to a proposal in a Slack thread. The list capability was added for VaultReplication and it's only used there for now. 
The problem that we found is that if there was a path in the replication list without secrets the integration fails as there are no keys, a temporal solution was adding a dummy secret on the path to ensure that there is at least one secret to be listed. Adding this change we are making sure that in the case that there are no secrets we return an empty list.
Tested by running the vault replication integration locally, and everything working as expected.
=> Fix case where there are no secrets in a path

reconcile/gql_definitions/common/clusters.py, reconcile/gql_definitions/common/clusters_minimal.py, reconcile/gql_definitions/common/namespaces.py, reconcile/gql_definitions/fragments/jumphost_common_fields.gql, reconcile/gql_definitions/fragments/jumphost_common_fields.py, reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/jumphosts/jumphosts.py, reconcile/gql_definitions/skupper_network/skupper_networks.py, reconcile/test/fixtures/oc_connection_parameters/cluster_with_jumphost.yml, reconcile/test/fixtures/oc_connection_parameters/namespace_with_admin.yml, reconcile/test/oc/test_oc_connection_parameters.py, reconcile/utils/oc_connection_parameters.py, reconcile/utils/oc_map.py
Introduce `remotePort` to jumphost fragment.
This is a result of a discussion in https://github.com/app-sre/qontract-reconcile/pull/3176
Relies on schema change: https://github.com/app-sre/qontract-schemas/pull/378
=> APPSRE-6609 add remotePort to schema

reconcile/cluster_deployment_mapper.py, reconcile/dashdotdb_cso.py, reconcile/utils/oc.py, reconcile/utils/oc_map.py, setup.cfg
Integration `cluster-deployment-mapper` should use the new typed `OCMap` class.
This is part of the `OC_Map` refactor attempt. See https://github.com/app-sre/qontract-reconcile/pull/3176
This also adds convenience functions to init an `OCMap` object. Goal of the convenience function is to hide the underlying `OCConnectionParameter` class.
=> APPSRE-6609 cluster-deployment-mapper uses OCMap

reconcile/ocm_upgrade_scheduler.py, reconcile/test/test_ocm_upgrade_scheduler.py
Skip version gates, if the version gate version is not a bigger major.minor version then the cluster.
=> Fix version gate error

tools/qontract_cli.py
Adds a CLI command to copy aws credentials from terraform output to vault. These credentials need to be migrated, cause the get terraform-users-credentials reads these from vault
Related issue: [APPSRE-4706](https://issues.redhat.com/browse/APPSRE-4706)
=> Add cli command user-credentials-migrate-output

reconcile/cli.py, reconcile/test/runtime/fixtures.py, reconcile/test/runtime/test_utils_integration.py, reconcile/test/runtime/test_utils_runtime_runner.py, reconcile/utils/runtime/integration.py, reconcile/utils/runtime/runner.py
replace the generic `*args: Any, **kwargs: Any` parameterlist on the `run` function of class based integrations with a dedicated parameter class on an integrations `__init__` function. wrapping parameters in a dataclass enables validations at runtime (e.g. pydantic) but also at static code analysis (e.g. mypy).
to leverage type safety all the way, the type of the parameter class can be defined as type hint when inheriting from `QontractReconcileIntegration`. the `__init__` function will then accept that type and the `param` property of the class will have that as a verifable type as well.
```python
class SimpleTestIntegrationParams(PydanticRunParams):
int_arg: int
opt_str_arg: Optional[str] = None
class SimpleTestIntegration(QontractReconcileIntegration[SimpleTestIntegrationParams]):
def …
```
=> [integration-runtime] replace integration args, kwargs run parameters with class

reconcile/openshift_base.py, reconcile/openshift_resources_base.py, reconcile/test/fixtures/namespaces/ns-overrides-cluster-resources.yml, reconcile/test/test_openshift_base.py, reconcile/test/test_openshift_resources_base.py, reconcile/test/test_utils_oc.py, reconcile/test/test_utils_oc_native.py, reconcile/utils/oc.py, reconcile/utils/openshift_resource.py
This PR introduces a validation to ensure that cluster-scoped resources managed by App-Interface are not duplicated. 
With our current approach, multiple namespace files can define the same cluster-scoped resource using `openshiftResources`. That has happened sometimes and ends up with a clash of the reconciliation loop trying to reconcile the same resource from multiple locations. 
This change forces the cluster-scoped defined in `openshiftResoures` to be defined under `ManagedResourceNames` within the service namespace files. This allows a validation at PR-check to ensure that newly introduced cluster-scoped resources are not duplicated in the same cluster.
There are two checks: 
* CheckClusterScopedResourceNames: Ensures that all cluster-scoped resources in the desired state of a …
=> Define Cluster-Scoped resources in app-interface (2)

build_deploy.sh, build_tag.sh
`build_tag.sh` is executed on builder node. We want to have it containerized to isolate build environment.
=> APPSRE-7067 containerize pypi publish

reconcile/terraform_resources.py, reconcile/utils/terrascript_aws_client.py
part of https://issues.redhat.com/browse/APPSRE-7044
depends on https://github.com/app-sre/qontract-schemas/pull/380
this will enable the ingress cidr blocks to be configurable (and self-serviceable).
=> [terraform-resources] add support for ingress cidr blocks for alb provider

reconcile/terraform_resources.py, reconcile/utils/terrascript_aws_client.py
Allow configuring ip_address_type for ALB resources
This is an optional parameter as per the [terraform aws provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#ip_address_type) and neither the terraform aws provider or aws api docs document a default. The AWS console defaults to `ipv4` so we set that as a default here to be more consistent/explicit
part of https://issues.redhat.com/browse/APPSRE-7044
depends on https://github.com/app-sre/qontract-schemas/pull/381
=> [terraform-resources] add ability to set ip_address_type to ipv4/dualstack for alb

reconcile/utils/saasherder.py
Correct typos in error messages and how one message has been concatenated to improve clarity.
No functional changes are intended.
=> Fix typos and string concatenation in error messages

reconcile/dashdotdb_cso.py, reconcile/gql_definitions/skupper_network/skupper_networks.gql, reconcile/gql_definitions/skupper_network/skupper_networks.py, reconcile/openshift_base.py, reconcile/openshift_users.py, reconcile/skupper_network/integration.py, reconcile/skupper_network/reconciler.py, reconcile/test/fixtures/skupper_network/skupper_networks-island.yml, reconcile/test/fixtures/skupper_network/skupper_networks.yml, reconcile/test/skupper_network/conftest.py, reconcile/test/skupper_network/test_skupper_network_integration.py, reconcile/test/skupper_network/test_skupper_network_models.py, reconcile/test/skupper_network/test_skupper_network_reconciler.py, reconcile/utils/oc_map.py
Refactor `skupper-network` to use the new typed `OCMap` class. 
* improve `openshift_base` to support old `OC_Map` and new `OCMap`
* improve `OCMap.get()` and `OCMap.get_cluster()` returned types
* remove unneeded `oc` checks in `openshift_users` and `dashdotdb_cso`
Ticket: [APPSRE-7033](https://issues.redhat.com/browse/APPSRE-7033)
=> [skupper-network] use typed OCMap

reconcile/cli.py, reconcile/openshift_namespaces.py, reconcile/test/test_openshift_namespaces.py
`cluster_name` and `namespace_name` args make it easy debug
example:
```
qontract-reconcile \
--config config.debug.toml \
--dry-run \
--log-level DEBUG \
openshift-namespaces \
--cluster-name some-cluster \
--namespace-name some-namespace
```
=> Add cluster_name and namespace_name args to openshift_namespaces

dockerfiles/hack/run-integration.py, reconcile/cli.py, reconcile/utils/runtime/environment.py, tools/app_interface_reporter.py
extract the configuration and setup of the qontract-reconcile environment to a dedicated module. the `init_env` function sets up logging, initializes the config and sets up GQL connectivity to the `qontract-server`.
`init_env` can be called with or without parameters about loglevel and config. if no parameters are passed, their values are extracted from env variables.
if it is called with parameters, their values are stored in env variables. this way, if a child process is spawned, it can call `init_env` without parameters and a log + config + GQL environment compatible with the parent process is established.
the intended way to use `init_env` is with parameter from the main entry point of q-r (cli.py). this sets up env vars to allow child processes to use `init_var` without parameters to …
=> extract runtime environment config

reconcile/openshift_groups.py, reconcile/openshift_users.py
Fixing bug introduced in https://github.com/app-sre/qontract-reconcile/pull/3216
Didn't run `slack-usergroups` locally, so this went unnoticed.
=> APPSRE-6609 fix null issues

.coveragerc
yes 42 ... forty-two ... https://en.wikipedia.org/wiki/42_(number)
the current tests cover approx 44% so 42 looks legit
=> raise min test coverage to 42

reconcile/vault_replication.py
We don't want to cause a failure of the integration as this cause a critical page to the team, but we want to be sure that we are aware of this cases.
=> Add a new exception to hande the case of a secret with no versions

reconcile/gitlab_housekeeping.py
Reverts app-sre/qontract-reconcile#3159
There is no upper bound on how many types `/retest` is triggered so an MR can end up blocking the merge queue.
See: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/59447
=> Revert "[gitlab-housekeeping] retest approved failed MRs"

reconcile/queries.py, reconcile/terraform_aws_route53.py
elbFQDNs are used in a zone in our `app-sre` account. Having a bad FQDN in a single cluster can block this integration for other clusters too, so we should have a way to disable it on a per cluster base.
Schema: https://github.com/app-sre/qontract-schemas/pull/393
=> allow disable per cluster for route53

reconcile/queries.py, reconcile/terraform_aws_route53.py
This reverts commit 0c2558a321c5966632bd382e525e0c56bf910d39.
disabling on per-cluster basis is not a safe operation because tf state is on per-account basis.
=> Revert "allow disable per cluster for route53 (#3233)"

reconcile/utils/terrascript_aws_client.py
AWS has been rolling out their new approach to enabling a default S3 Bucket encryption policy.
Many of the old S3 Buckets did not have the SSE (Server Side Encryption) encryption enabled in the past, and there was also no default, or rather the default was no encryption of the objects stored at rest. This rollout of new settings and policies will result in the Terraform detecting drift perpetually where the SSE wasn't previously enabled.
Thus, add a new default SEE setting that will be applied where the configuration was not explicitly added to stop the problem with the state drift and align with the new recommendation from AWS per:
- [Setting default server-side encryption behavior for Amazon S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html)
- …
=> APPSRE-7138: Support default Server Side Encryption (SSE) setting for S3 buckets

reconcile/utils/oc.py
a change made in #3206 assumes that `self.api_resources` will be initialized in advance. most integrations do not set `init_api_resources`, hence when using OCDeprecated they will all face `cluster has no API resource`.
=> [OCDeprecated] fix is_kind_supported

reconcile/test/oc/test_oc_connection_parameters.py, reconcile/utils/oc_connection_parameters.py, reconcile/utils/oc_map.py
At the moment we use a jumphost whenever we find a configuration for it. However, we should obey to the `use_jump_host` variable on whether to use a jumphost or not.
=> APPSRE-6609 obey to use_jump_host setting

reconcile/utils/oc.py
This is an interim patch to fix some integration that does not init api_resources. 
There will be a follow-up discussion about if it's really needed to allow the initialization of the OC client without gathering the API resources.
=> Fix OCDeprecated to load api resources before using them

reconcile/cli.py, reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py
Related to  [APPSRE-6586](https://issues.redhat.com/browse/APPSRE-6586) 
Things to teste here:
* Running `terraform-resources` with `--dry-run` show the changes in resources for all accounts;
* Running `terraform-resources` with `--dry-run`, `--account-name` and `--exclude-accounts` gives the user an error;
* Running `terraform-resources` with  `--exclude-accounts` and not `--dry-run` gives the user an error;
* RUnning `terraform-resources` excluding an account that doesn't exist gives the user an error; 
* Running `terraform-resources` excluding all accounts gives the user an error;
* Running `terraform-resouces` with `--exclude-account=a --exclude-account=b` show the changes in resources for all accounts except `a` and `b`.
This is testable by using `app-interface-dev-data`.
=> Add exclude account parameter

reconcile/openshift_namespace_labels.py, reconcile/test/fixtures/openshift_namespace_labels/namespace.yml, reconcile/test/test_openshift_namespace_labels.py, reconcile/typed_queries/namespaces.py
Introducing new `OCMap` for `openshift-namespace-labels` integration.
Note, that the `reconcile` method has a complicated typing situation using `LabelsOrKeys`, which introduces a dict/list ambiguity. I do not dare to solve that in this PR as I do not know the full context behind it. So the integration is not fully typed now.
=> APPSRE-6609 OCMap for namespace-labels

reconcile/openshift_namespace_labels.py, reconcile/test/fixtures/openshift_namespace_labels/namespace.yml, reconcile/test/test_openshift_namespace_labels.py, reconcile/typed_queries/namespaces.py
Follow-up on https://github.com/app-sre/qontract-reconcile/pull/3243. The PR was reverted due to a json issue.
The [2nd commit](https://github.com/app-sre/qontract-reconcile/pull/3245/commits/ceb2a8c6d90e6bbfe03cf6d9b2423a0bd8e5b852) shows what fixes it. Basically I removed the `json.loads` logic, as the `pydantic.Json` type is already a `dict`. 
Ran locally against a couple of clusters w/o issues.
=> APPSRE-6609 namespace labels - 2nd try

reconcile/test/test_utils_terrascript_cloudflare_client.py, reconcile/utils/terrascript/cloudflare_resources.py
The terraform-cloudflare-resources integration is responsible for creating certificate packs (automatic renewing Let's Encrypt certificate), but the integration doesn't create the DNS records required for validation. This change will make these records available as an output so that another integration can be responsible for creating the DNS records.
Related: [APPSRE-6695](https://issues.redhat.com/browse/APPSRE-6695)
I'm still working through which integration would consume this, so leaving this in draft status for now.
The `terraform plan` produces the expected outputs:
```
Changes to Outputs:
+ cloudflare-<account_name>-zone__validation_records = {
+ _acme-challenge.somedomain.local = "<TXT record value>"
+ _acme-challenge.subdomain.somedomain.local       = "<TXT record value>"
}
``` …
=> Add DCV validation_records output to terraform-cloudflare-resources

reconcile/change_owners/change_types.py, reconcile/test/test_utils_jsonpath.py, reconcile/utils/jsonpath.py
for certain operations, jsonpaths need to be sorted. the currently used naive approach simply compared the jsonpath strings, which starts to fail when double digit indices are involved.
e.g. `a.b.[10] comes before a.b.[9]` in a pure string comparison
this PR introduces a function that creates a sortable string representation of jsonpaths that takes care of those index numbers by padding with zeros.
https://issues.redhat.com/browse/APPSRE-7197
=> [change-owners] fix jsonpath sorting

reconcile/test/runtime/test_utils_desired_state_diff.py, reconcile/utils/runtime/desired_state_diff.py
when a configuration items is moved from one shard to another one, the integration runtime only detects the old shard as the affected one, instead of detecting both.
https://issues.redhat.com/browse/APPSRE-7204
=> [integration-runtime] detect new shard when moving config from shard to shard

reconcile/openshift_upgrade_watcher.py
part of https://issues.redhat.com/browse/APPSRE-7182
UpgradeConfig is not found.
=> [openshift-upgrade-watcher] ignore hypershift clusters

reconcile/test/test_saasherder_allowed_secret_paths.py, reconcile/utils/saasherder.py
trying to make a test for another example of #3227.  In this test, we have `foo` in `allowedSecretParameterPaths` but the `secretParameters` has `path = "foobar/baz"`.
I think this means validation should fail in `_validate_allowed_secret_parameter_paths` with the log message `secret parameter path 'foobar/baz' does not match any of allowedSecretParameterPaths`.
But this is based on a naive reading of the code + test cases, and I could be wrong.  Somebody who uses this function should review.
https://issues.redhat.com/browse/APPSRE-7196
=> allowedSecretParameterPaths prefix but not parent of secretParameters

.gitleaks.toml, README.md, reconcile/cli.py, reconcile/glitchtip_project_dsn/integration.py, reconcile/gql_definitions/glitchtip/glitchtip_project.gql, reconcile/gql_definitions/glitchtip/glitchtip_project.py, reconcile/test/fixtures/glitchtip/api/0/projects/nasa/apollo-11-flight-control/keys/get.json, reconcile/test/fixtures/glitchtip/desire_state_projects.yml, reconcile/test/fixtures/glitchtip/dsn_projects.yml, reconcile/test/glitchtip/conftest.py, reconcile/test/glitchtip/test_glitchtip_project_dsn.py, reconcile/test/glitchtip/test_utils_glitchtip_client.py, reconcile/typed_queries/glitchtip_settings.py, reconcile/utils/glitchtip/client.py, reconcile/utils/glitchtip/models.py
The `glitchtip-project-dsn` integration populates glitchtip project dsn's as Kubernetes secret into the tenant's namespaces.
* Ticket: [APPSRE-6631](https://issues.redhat.com/browse/APPSRE-6631)
* Depends on: https://github.com/app-sre/qontract-schemas/pull/398
Do you want to run it by yourself? 😄 
```sh
$ qd profile create glitchtip-project-dsn --app-interface-pr 46 --qontract-schemas-pr 398 --qontract-reconcile-pr 3257
$ qd profile run dev glitchtip-project-dsn
$ docker compose up
```
A `.gitleaks.toml` config file has been added because the word `secret` is in one of the fixture files. For more information, see [How can I tell the scanner to allow certain things in my repo?](https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_secu …
=> [glitchtip-project-dsn] new integration

reconcile/gitlab_fork_compliance.py
This fixes a bug in gitlab fork compliance that will falsely report devtools-bot missing in cases where the user was not added to the repository directly but got permission by adding the grup instead. Prominent case for this is when devtools bot itself is creating MRs directly on the repository in question, this is common for automated MRs.
Required for: https://issues.redhat.com/browse/APPSRE-6369
=> Bugfix for gitlab for compliance

build_deploy.sh, tox.ini
- `py39` and `generate` test envs have a race condition when executed in parallel
- `set -e` is required for CI to fail
=> Fix race condition in tox

reconcile/test/fixtures/oc_connection_parameters/namespace_no_admin_token.yml, reconcile/test/fixtures/oc_connection_parameters/namespace_no_tokens.yml, reconcile/test/fixtures/oc_connection_parameters/namespace_with_admin.yml, reconcile/test/oc/test_oc_connection_parameters.py, reconcile/utils/oc_connection_parameters.py, reconcile/utils/oc_map.py
The current `OCMap` has a crucial bug: it does not create an unprivileged client if there is a privileged client available. This does not comply with how the original `OC_Map` behaves and leads to issues with namespace initialized `OCMap`s.
This overall aligns `OCMap` closer to the behavior of the old `OC_Map`.
This PR:
- fixes the bug: OCMap must hold a non-privileged client for **EVERY** cluster, also the ones that have a privileged connection established.
- reduces the number of vault requests on namespace queries by grouping clusters from namespaces.
- shifts all logic about how to group OC connections away from `OCMap`. `OCMap` is only concerned about creating and holding clients based on the given connection parameters.
**Test**
- ran `skupper-network` locally
- ran …
=> APPSRE-6609 fix OCMap connections

dockerfiles/Dockerfile
Depends on:
- https://github.com/app-sre/container-images/pull/65
- https://github.com/app-sre/container-images/pull/66
Signed-off-by: Krzysztof Wilczyński [kwilczynski@redhat.com](mailto:kwilczynski@redhat.com)
=> Update base and builder images release tags

reconcile/queries.py
APPSRE-7222
Allow to create AWS Route53 geolocation records
See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record#geolocation-routing-policy and https://docs.aws.amazon.com/Route53/latest/APIReference/API_GetGeoLocation.html
Depends on https://github.com/app-sre/qontract-schemas/pull/401
Doc and example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/60318
=> route53 geolocation records

reconcile/quay_mirror.py
When looking at `quay-mirror` logs, it is not clear in which mode it is running. The `compare-tags` mode is very slow and should only run once daily -> this extra log line gives more insights on what's happening.
=> increase quay-mirror verbosity

reconcile/statuspage/status.py
pydantic is able to implicitly convert datetime strings to proper datetimes, but explicit is safer so we can control what format we accept.
=> [statuspage] explicit datetime conversion

reconcile/aws_iam_keys.py, reconcile/aws_iam_password_reset.py, reconcile/email_sender.py, reconcile/jira_watcher.py, reconcile/ocm_addons_upgrade_tests_trigger.py, reconcile/ocm_upgrade_scheduler.py, reconcile/openshift_namespace_labels.py, reconcile/openshift_saas_deploy.py, reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_upgrade_watcher.py, reconcile/requests_sender.py, reconcile/sentry_helper.py, reconcile/sql_query.py, reconcile/statuspage/integration.py, reconcile/test/test_openshift_namespace_labels.py, reconcile/test/test_requests_sender.py, reconcile/test/test_saasherder.py, reconcile/test/test_utils_state.py, reconcile/utils/jenkins_api.py, reconcile/utils/saasherder.py, reconcile/utils/state.py, setup.py, tools/qontract_cli.py, tools/test/test_qontract_cli.py
change all initialization of the `reconcile.utils.state.State` class to be handled via the `init_state` function. this is a small minimal preparational step to make additional improvements in upcoming PRs easier where we will fully inject all dependencies to the `init_state` function (e.g. `SecretReader`) while getting  rid of other dependencies (e.g. `accounts`) and add other means of providing configuration data for state bucket initialization.
This change could have been bigger, touching `SecretReader` initializiation in various places, but the scope of this PR has been kept small on purpose.
https://issues.redhat.com/browse/APPSRE-7226
=> [app-interface state] initialize via builder function

reconcile/gabi_authorized_users.py, reconcile/test/fixtures/gabi_authorized_users/apply.yml, reconcile/test/fixtures/gabi_authorized_users/delete.yml, reconcile/test/test_gabi_authorized_users.py
Currently, the file this integration manages via a ConfigMap object for the GABI service only includes a simple new line delimited list of users allowed to use a particular GABI instance. There is no notion of the expiration date conveyed there in any shape or form. The only way an instance would currently "expire" is when it reaches the expiration date upon which the authorised users list is emptied, and the Deployment recycled to allow new Pods to load updated file content.
Thus, this change moves the expiration date forward into the GABI instance itself so that it can be verified locally, allowing one to distinguish between an instance that has expired or lacks user access permissions from now on with a different set of HTTP response codes.
To achieve this, the configuration file …
=> APPSRE-6175: Update instance expiration management

reconcile/cli.py
Based on https://github.com/app-sre/qontract-reconcile/pull/2573, we should try to put import in local scope to save memory.
`reconcile.terraform_cloudflare_users` is using about 70M on my machine.
=> Move terraform_cloudflare_users import to local scope

setup.py
High memory consumption is caused by old openssl packages, bumping `pyOpenSSL` to `23.0` and removing `cryptography` pinned version can greatly reduce heap size.
This change reverted https://github.com/app-sre/qontract-reconcile/pull/2369, need to keep an eye on cert issue after deployment.
APPSRE-4141
=> Bump pyOpenSSL to 23.0 to reduce heap memory

reconcile/utils/ocm.py
APPSRE-7191
* Updates ROSA based clusters' provision_shard_id attribute 
* Allows to pin a cluster to a specific provision_shard_id
=> Enable provision_shard_id with ROSA clusters

reconcile/test/conftest.py, reconcile/test/fixtures/glitchtip/dsn_projects.yml, reconcile/test/fixtures/skupper_network/skupper_networks.yml, reconcile/test/glitchtip/test_glitchtip_project_dsn.py, reconcile/test/skupper_network/conftest.py, reconcile/test/skupper_network/test_skupper_network_models.py
Introduce `gql_class_factory` and `data_factory` pytest fixtures.
**gql_class_factory**
This pytest fixture helps you to create GQL classes from test fixtures without worrying about `Optional` fields. Just specify all required and non-optional fields, and you're done.
**data_factory**
This fixture does the same as `gql_class_factory` but returns a data dictionary instead of a GQL class. Very handy to test and re-use the GQL `query` methods. 
Hints for the reviewer: This affects just tests; no prod code has been touched
=> gql_class_factory and data_factory pytest fixtures

reconcile/gabi_authorized_users.py, reconcile/test/fixtures/gabi_authorized_users/apply.yml, reconcile/test/fixtures/gabi_authorized_users/delete.yml, reconcile/test/test_gabi_authorized_users.py
Currently, both the legacy users file and the new configuration file are supported.  However, the old legacy support is no longer needed after the AppInterface integration has been updated to create the new style configuration file.
Thus, remove the old legacy users file support, as it's no longer needed.
Related: [APPSRE-6175](https://issues.redhat.com/browse/APPSRE-6175)
Depends on:
- https://github.com/app-sre/gabi/pull/54
Related to:
- https://github.com/app-sre/gabi/pull/46
- https://github.com/app-sre/qontract-reconcile/pull/3219
=> APPSRE-6175: Retire legacy users file support

reconcile/utils/vault.py
APPSRE-7074
SDE-2558
[related design doc](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/59519)
**Changes:**
* Adds option for kubernetes auth to be utilized by the Vault client
* Defaults to approle when specific kubernetes auth attributes are not set within toml or passed as arguments when initializing VaultClient
=> Add option for vault client to utilize kube auth

tools/qontract_cli.py
without this indentation we are missing all items except the last one :facepalm:
=> [qontract-cli/get/selectorsyncset-managed-resources] fix bug

reconcile/queries.py, reconcile/terraform_tgw_attachments.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_aws_client.py
https://issues.redhat.com/browse/APPSRE-7273
On TGW attachments to non-hive transit accounts, we may want to associate Private Hostedzones to our cluster VPC in order to resolve hostnames.
This is especially the case of the hypershift "service-transit-account", which contains private hosted zones for hypershift service clusters VPCE interfaces (privatelink endpoints).
Depends on https://github.com/app-sre/qontract-schemas/pull/408
=> manage route53 vpc associations on tgw peerings

reconcile/utils/vault.py, reconcile/vault_replication.py
`vault-replication` integration is leaking memory, every time it runs it will leak fd (sockets to vault).
`requests.Session()` need to be closed after the client is no longer needed.
In this change, I implemented context manager for `_VaultClient`, so it can be used with `with` to proper close session.
APPSRE-7274
=> Close VaultClient after replication to fix memory leak

tools/qontract_cli.py
to get a list of each cluster and it's VPC ID (required for HiveConfig, pending auotmation) as part of the clusters-network command.
used in app-interface-output.
this PR also adds clusters egress IPs to the clusters-network command.
=> [qontract-cli] add clusters vpc ids

reconcile/utils/vault.py
this is being done to resolve issue with https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/vault_replication.py#L436 when toml is switched to using kube auth parameters
=> switch logic for vault auth check

reconcile/terraform_cloudflare_dns.py, reconcile/terraform_cloudflare_resources.py, reconcile/test/test_utils_terrascript_cloudflare_client.py, reconcile/utils/terrascript/cloudflare_client.py
*  Adjust Cloudflare terraform provider's rps based on the number of records in the zone.
* Catch the 'referenced before assignment' error with a better error message.
Ran the terraform-cloudflare-dns locally against dev-data and was able to see the provider setting in the state file, and was able to `terraform apply`
Dry ran terraform-cloudflare-resources locally against dev-data.
=> Set Cloudflare provider rps based on zone

reconcile/ldap_users.py, reconcile/queries.py, reconcile/utils/mr/user_maintenance.py
Part of APPSRE-6367, requires https://github.com/app-sre/qontract-schemas/pull/411.
Extends the `ldap_users` integration to include removal of `resetPasswords` entries that no longer have a user associated in LDAP.  Schema changes are in https://github.com/app-sre/qontract-schemas/pull/411 to provide the paths to `user_maintenance.py`.  
Testing was done with qontract-reconcile-cli and qd.
=> add ability to remove resetPassword entries for users not in LDAP.

requirements/requirements-test.txt
[new version](https://pypi.org/project/typeguard/3.0.0/) does not work for our testslide package.
`AttributeError: module 'typeguard' has no attribute 'qualified_name'`
=> hard coded typeguard version

reconcile/utils/terrascript_aws_client.py
The aim is to avoid issues when using regions which are not the default for the terraform user
=> include region in route53 associations

reconcile/queries.py, reconcile/terraform_resources.py, reconcile/utils/terrascript_aws_client.py
another attempt at #2920
part of:
- https://issues.redhat.com/browse/APPSRE-5707
- https://issues.redhat.com/browse/APPSRE-7296
this PR adds support to specify records on a route53-zone provider. these records will be added to the zone.
schemas were added in https://github.com/app-sre/qontract-schemas/pull/299
=> [terraform-resources] support records for route53-zone provider

reconcile/utils/aws_api.py
`_session_clients` is used in `init_users` in `__init__`, put it on top to init
=> Fix session client init order in AWSApi

Makefile
qenerate version mismatch potentially fails CI. However, the error is not very obvious and leads to confusion.
This introduces an early exit with a clear error message if there is a version mismatch.
=> fail on bad qenerate version

tox.ini
We do not use lockfiles (yet). So for debugging purposes it would be nice to see which tool versions where run during a jenkins check.
=> print CI tooling versions

reconcile/jira_watcher.py
fix
`TypeError: run() got an unexpected keyword argument 'defer'`
=> [jira-watcher] fix missing defer argument

reconcile/utils/defer.py
Refactor defer with [contextlib.ExitStack.callback](https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack.callback), use build in functions to achieve the same effect as before.
=> Refactor defer with ExitStack

reconcile/openshift_base.py
fix following up on #813
we expect the namespace to eventually be created, so let's wait more. 30 attempts == 465 seconds.
we also want to catch the last attempt, should there be a real problem with creating the namespace. this PR updates the exception that is raised to one that is caught here:
https://github.com/app-sre/qontract-reconcile/blob/c9f902831b038b7b5986af4433f3d284728dc316/reconcile/openshift_base.py#L649-L682
this will cause an error to be registered and the deployment will be marked as failed.
=> [openshift_base] catch namespace does not exist (and wait more)

reconcile/test/conftest.py
This fixes dict <-> union matching.
1. For every class in a union we try if the given data matches -> first match wins
2. Lists like `list[Union[A, B]]` are handled a little differently -> we do the first step for every item in the list
3. We increase log verbosity, i.e., print what attributes are missing from your data in order to match a generated class
=> Union lists fix

reconcile/test/oc/test_oc_connection_parameters.py, reconcile/test/test_gabi_authorized_users.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py, reconcile/utils/oc_connection_parameters.py
Failing with some exception that looks related. Need to check
```
08:15:02   File "/usr/local/lib/python3.9/site-packages/reconcile/utils/oc_map.py", line 83, in _init_oc_client
08:15:02     cluster = connection_parameters.cluster_name
08:15:02 AttributeError: 'OCConnectionError' object has no attribute 'cluster_name'
```
Reverts app-sre/qontract-reconcile#3338
=> Revert "Check the server url before returning the client"

tools/qontract_cli.py
Noticed that while removing mutexes for a cluster:
```
08:07:10 Traceback (most recent call last):
08:07:10   File "/usr/local/bin/qontract-cli", line 8, in <module>
08:07:10     sys.exit(root())
08:07:10   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
08:07:10     return self.main(*args, **kwargs)
08:07:10   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
08:07:10     rv = self.invoke(ctx)
08:07:10   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
08:07:10     return _process_result(sub_ctx.command.invoke(sub_ctx))
08:07:10   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
08:07:10     return _process_result(sub_ctx.command.invoke(sub_ctx))
08:07:10 …
```
=> fix: mutexes may not be set

reconcile/utils/saasherder/saasherder.py
related to https://issues.redhat.com/browse/APPSRE-7269
```
[ERROR] [saasherder.py:validate_promotions:1837] - Parent saas target has run with a newer configuration and the same commit (ref). Check if other MR exists for this target
[ERROR] [openshift_saas_deploy.py:run:172] - invalid promotions 
```
the workaround to this error is to remove the `promotion_data` section in a separate MR.
while we are working on a better solution, we can add information to the error message that will allow a user to update the same MR with the updated config hash in order to get a passing pr-check.
=> [saasherder] add information to recover from configuration mismatch

reconcile/cli.py
`openshift_saas_deploy` can spawn 20 `oc` processes at peak time when thread pool size is 20, each `oc` process consumes 50+ MB, reduce thread pool size to limit memory usage.
=> Update thread size for openshift_saas_deploy to default 10

dockerfiles/Dockerfile
Missed a few version bumps in the main Dockerfile in #3359
=> add version bumps for q-r base image missing from #3359

reconcile/queries.py, reconcile/terraform_aws_route53.py, reconcile/utils/terrascript_aws_client.py
Related: https://issues.redhat.com/browse/APPSRE-6948
This feature will allow us to consume Vault records from other integrations and use them as a source for creating DNS records in the `terraform-aws-route53` integration. The primary use case is domain control validation (DCV) records for certificates created in Cloudflare through the ACM feature: https://blog.cloudflare.com/advanced-certificate-manager/
```yaml
---
$schema: /dependencies/dns-zone-1.yml
...
allowed_vault_secret_paths:
- some-path/to-a/secret
records:
- name: _acme-challenge.subdomain
type: TXT
_records_from_vault:
- path: some-path/to-a/secret
field: validation_records
key: _acme-challenge.subdomain.domain.com
```
`allowed_vault_secret_paths` must contain the approved paths from which a secret can be pulled. This will …
=> Support _records_from_vault in terraform-aws-route53 integration

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_resources.gql, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_resources.py, reconcile/test/test_terraform_cloudflare_resources.py, reconcile/utils/terrascript/cloudflare_resources.py
Adds ability to set [tiered_cache](https://registry.terraform.io/providers/cloudflare/cloudflare/3.32.0/docs/resources/tiered_cache) on a zone
Schema: https://github.com/app-sre/qontract-schemas/pull/421
Ref.: https://issues.redhat.com/browse/APPSRE-7363
=> tf-cloudflare-resources: add ability to set tiered_cache type

reconcile/ocm_update_recommended_version.py, reconcile/test/change_owners/conftest.py, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_context.py, reconcile/test/change_owners/test_change_type_coverage.py, reconcile/test/change_owners/test_change_type_decision.py, reconcile/test/change_owners/test_change_type_implicit_ownership.py, reconcile/test/change_owners/test_change_type_integration.py, reconcile/test/change_owners/test_change_type_priorities.py, reconcile/test/change_owners/test_change_type_processor.py, reconcile/test/change_owners/test_change_type_various.py, reconcile/test/runtime/conftest.py, reconcile/test/runtime/fixtures.py, reconcile/test/runtime/test_utils_desired_state_diff.py, reconcile/test/runtime/test_utils_runtime_runner.py, reconcile/test/test_gitlab_labeler.py, reconcile/test/test_utils_mr_clusters_updates.py, reconcile/utils/mr/clusters_updates.py, reconcile/utils/runtime/runner.py, requirements/requirements-test.txt
Fix a lot of pytest warnings:
* upgrade `pytest-cov`
* move `change-owners` and `runtime` pytest fixtures into a proper `contest.py`
* rename some stub classes. pytest considers a `class Test..." as a class with test cases
* fix `ruamel` and `semver` deprecations
Ticket: [APPSRE-7313](https://issues.redhat.com/browse/APPSRE-7313)
=> fix PyTest warnings

reconcile/aws_iam_keys.py
this integration is currently running in every pr-check, and may cause rate limiting.
another perspective like #2682
=> [aws-iam-keys] early-exit

reconcile/utils/sentry_client.py, reconcile/utils/vault.py
Use `@lru_cache` on instance methods will cause memory leak because `self` is captured.
Same fix as https://github.com/app-sre/qontract-reconcile/pull/1947, but for `vault` and `sentry_client`.
=> Fix memory leak caused by lru_cache on instance methods

reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/aus/ocm_upgrade_scheduler_org.py
the ocm env filter was not handled so all clusters/orgs/upgrade policies from all orgs were provided as state.
=> [ocm-upgrade-scheduler] fix ocm env sharding/filtering

reconcile/test/fixtures/clusters/osd_spec_ai.yml, reconcile/test/fixtures/clusters/rosa_spec_ai.yml, reconcile/test/fixtures/ocm/oidc/get_full.yml, reconcile/test/fixtures/ocm/oidc/get_minimal.yml, reconcile/test/ocm/conftest.py, reconcile/test/ocm/fixtures.py, reconcile/test/ocm/test_utils_ocm_cluster_groups.py, reconcile/test/ocm/test_utils_ocm_clusters.py, reconcile/test/ocm/test_utils_ocm_get_json.py, reconcile/test/ocm/test_utils_ocm_labels.py, reconcile/test/ocm/test_utils_ocm_oidc_idp.py, reconcile/test/ocm/test_utils_ocm_sectors.py, reconcile/test/ocm/test_utils_ocm_service_log.py, reconcile/test/ocm/test_utils_ocm_subscriptions.py, reconcile/test/ocm/test_utils_ocm_versions.py, reconcile/test/test_ocm_clusters.py, reconcile/test/test_utils_ocm.py, reconcile/test/test_utils_ocm_versions.py, reconcile/utils/ocm/ocm.py, reconcile/utils/ocm_base_client.py
this PR is a first step to harmonize the httpretty mocks and fixtures for OCM testability.
`reconcile.test.ocm.conftest` defines pluggable fixtures, e.g. for `OCMBaseClient` and `OCM` that enables concise test cases and fixture setup.
not all OCM related tests have been migrated to linted/mypy-verified/lean mocked tests so far, so this is only to be considered a first step.
=> [ocm-utils] testability and test refactor

reconcile/gql_definitions/glitchtip/glitchtip_project.gql, reconcile/gql_definitions/glitchtip/glitchtip_project.py, reconcile/test/fixtures/glitchtip/desire_state_projects.yml, reconcile/test/fixtures/glitchtip/dsn_projects.yml, reconcile/utils/mr/glitchtip_access_reporter.py, reconcile/utils/mr/notificator.py, setup.py, tools/glitchtip_access_reporter.py, tools/glitchtip_access_revalidation.py
We need an access revalidation policy for Glitchtip because we are subject to internal and corporate-level audits that will ask for evidence of risk being mitigated. 
This PR introduces: 
- an access report generator (1st commit)
- and sending an access revalidation email to all service owners with Glitchtip projects (2nd commit)
Depends on: https://github.com/app-sre/qontract-reconcile/pull/3371
Ticket: [APPSRE-7329](https://issues.redhat.com/browse/APPSRE-7329)
=> glitchtip access revalidation and report

reconcile/aus/base.py, reconcile/test/fixtures/clusters/osd_spec.json, reconcile/test/fixtures/clusters/rosa_spec.json, reconcile/test/ocm/test_utils_ocm_versions.py, reconcile/utils/ocm/ocm.py, tools/qontract_cli.py
using the CS `versions` endpoint to get upgrade paths for version+channel requires a special AMS capability only available to service-accounts that are bound to an organization. by using the `version.available_upgrades` data from the CS `clusters` endpoint, we can avoid that capability.
=> [ocm-cluster-upgrades] get available_upgrades from cluster endpoint

requirements/requirements-type.txt
Qenerate had a bug with inline fragments within fragments https://github.com/app-sre/qenerate/pull/80
We dont have a case like that yet in our queries, so there is no change to any generated classes.
=> qenerate upgrade

Makefile, README.md, dockerfiles/Dockerfile
* quote `run` parameters to avoid `INTEGRATION_EXTRA_ARGS` break command syntax
* use `exec` in `run.sh` to allow container process to handle signal
* add `qontract-development-cli` to README
=> Improve doc and experience to run integration in container

reconcile/openshift_resources_base.py, reconcile/test/test_quay_mirror.py, reconcile/test/test_quay_mirror_org.py, reconcile/utils/git_secrets.py, reconcile/utils/lean_terraform_client.py, reconcile/utils/oc.py, reconcile/utils/terrascript_aws_client.py, requirements/requirements-test.txt
This change fixed lint `consider-using-with` to ensure external resources are properly handled and release when not used.
* Replace `_log_lock.acquire()` and `_log_lock. release()` with `with _log_lock`
* Fix typo `teardown_mehtod` to `teardown_method`
* Replace `tempfile.mkdtemp()` and `shutil.rmtree(wd)` with `with tempfile.TemporaryDirectory() as wd`
* Replace `Popen` with high level `subprocess.run`
* Ensure `open` called using context manager `with open(...) as f:`
* Specify `pylint` version to `>=2.16` so all options in `.pylintrc` are supported
=> Fix Pylint consider-using-with

reconcile/utils/oc.py
A recent change modified the behavior of `OCDeprecated._run()` to sometimes return undecoded strings and other times return utf-8 decoded strings. Thus in FedRamp where we only utilize `OCDeprecated`, we were seeing the following error in PR checks:
```py
File "/usr/local/lib/python3.9/site-packages/reconcile/utils/oc.py", line 371, in _init_old_without_types
self.api_resources = self.get_api_resources()
File "/usr/local/lib/python3.9/site-packages/reconcile/utils/oc.py", line 718, in get_api_resources
results = self._run(cmd).decode("utf-8").split("\n")
AttributeError: 'str' object has no attribute 'decode'
```
This adds error handling so that if a string is already utf-8 decoded, `decode()` isn't called again.
=> Add error handling for already decoded strings in get_api_resources

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py, reconcile/saas_auto_promotions_manager/utils/vcs.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_housekeeping.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_namespace.result.yml, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_namespace.yml, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_namespace_no_hash.result.yml, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_namespace_no_hash.yml, reconcile/utils/gitlab_api.py
Next step of gradual rollout of SAPM. It will create and manage promotion MRs in Draft mode **without auto-merge**. This behavior can be turned on/off via unleash flags.
**Background**
SAPM has been running successfully  in dry-run mode for some time now. It is time now to allow SAPM to actually open and manage promotion MRs without any of them being merged, i.e., without doing any actual auto-promotion.
**Details**
In this PR the auto-merge tag is removed and draft mode is active, i.e., these MRs will not get merged automatically. Once they go stale (merge-conflict or newer promotion detected), SAPM will close them on its own, i.e., the MRs will clean-up on their own over time.
Doing this we can have SAPM run in parallel with the current auto-promotion mechanism and observe what it does …
=> APPSRE-7367 turning on SAPM w/o auto-merge

reconcile/saas_auto_promotions_manager/integration.py, reconcile/saas_auto_promotions_manager/publisher.py, reconcile/saas_auto_promotions_manager/subscriber.py, reconcile/test/conftest.py, reconcile/test/saas_auto_promotions_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/subscriber/conftest.py, reconcile/test/saas_auto_promotions_manager/test_integration_test.py, reconcile/test/utils/test_promotion_state.py, reconcile/utils/promotion_state.py
This is an attempt to make SAPM's DeploymentState usable by multiple integrations. In a next step, `openshift-saas-deploy` will use `DeploymentState` to store information about promotion. Afterwards we will make changes to this class to support multiple publishers per channel. 
In a gist what happens:
- Rename SAPM's `DeploymentState` to `PromotionState`
- Move `PromotionState` to general utlis module
=> APPSRE-7414 promotion-state for utils

reconcile/openshift_saas_deploy_change_tester.py
compare dicts against dicts which is much faster than comparing BaseModels
=> [openshift-saas-deploy-change-tester] performance improvement

reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/conftest.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/data_keys.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/multiple_namespaces.result.yml, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/multiple_namespaces.yml, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/test_content_multiple_namespaces.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/test_content_single_namespace.py
The SAPM renderer added data to targets that where not subscribed, when any target within the same saas file had a subscription.
This PR fixes that behavior by checking each targets channel subscriptions when rendering.
=> APPSRE-7367 fix renderer

reconcile/test/fixtures/oc_connection_parameters/cluster_custom_token.yml, reconcile/test/oc/test_oc_connection_parameters.py, reconcile/utils/oc_connection_parameters.py
Fix for #3354 so that `automationToken` no longer assumes that `token` is always the field specified for a cluster file. Also adds a test for it.
https://issues.redhat.com/browse/APPSRE-7463
=> [APPSRE-7463] OCConnectionParameters should support flexible vault token field

reconcile/gitlab_housekeeping.py
[APPSRE-7471](https://issues.redhat.com/browse/APPSRE-7471)
This error message constantly appears in the GitLab housekeeping integration. Let's clean up that noise and have it only do a debug log message as a warning for expected behavior isn't very useful.
=> Reduce noise on GitLab housekeeping

reconcile/cli.py, reconcile/utils/sqs_gateway.py, tools/app_interface_reporter.py
the checks for env vars are not required in cli.py anymore because the check for the vars and also check for alternative state bucket settings is done in state.py
part of: https://issues.redhat.com/browse/APPSRE-7226
=> remove state-bucket env var checks in cli.py

reconcile/saas_auto_promotions_manager/integration.py, reconcile/saas_auto_promotions_manager/publisher.py, reconcile/saas_auto_promotions_manager/subscriber.py, reconcile/test/saas_auto_promotions_manager/subscriber/conftest.py, reconcile/test/utils/test_promotion_state.py, reconcile/utils/promotion_state.py, reconcile/utils/saasherder/saasherder.py
saasherder should use `PromotionState` to publish promotion data. This will make it easier to align SAPM with saasherder when we change the S3 state path layout to support multiple publishers per channel.
=> APPSRE-7414 saasherder uses PromotionState

reconcile/change_owners/change_types.py, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_processor.py
resources files with schemas were not self-serviceable if they are used with generic change-types like `resource-owners` that does not enforce a schema.
with this change, resourcesfiles with schemas can now be made self-serviceable with change-types that don't enforce a schema.
=> [change-owners] resourcesfiles with schemas

reconcile/test/test_typed_queries/test_app_interface_vault_settings.py, reconcile/typed_queries/app_interface_vault_settings.py
This aligns our `get_vault_settings` query with conventions we have for other queries:
- add tests
- raise error instead of sys.exit
=> align vault_settings query

reconcile/change_owners/change_types.py, reconcile/change_owners/diff.py, reconcile/change_owners/implicit_ownership.py, reconcile/test/test_utils_jsonpath.py, reconcile/utils/jsonpath.py
With more and more jsonpaths being added to existing and new change-types, parsing those has a noticeable performance impact.
There are two parsers for jsonpath expressions, a simple one and an extended one. the simple one is considerably faster and works for most of the expressions. the extended parser is required when filters are involved. For now we can detect the difference between those two types expressions by looking for a filter literal and choose the appropriate parser.
https://issues.redhat.com/browse/APPSRE-7467
=> [jsonpath parsing] speed up jsonpath expression parsing

reconcile/test/test_saasherder.py, reconcile/utils/saasherder/saasherder.py
When an auto subscriber channel is removed from a saas target, then we should also make sure that its `promotion_data` is removed from the target. That way we ensure promotion_data is in synch, which will make logic easier during auto-promotion phase.
=> APPSRE-7367 detect dangling config hashes

reconcile/integrations_manager.py
Filtering integrations was removed here: https://github.com/app-sre/qontract-reconcile/pull/3461
Adding it again, since it is required for running multiple instances of integrations-manager
=> Fix integrations manager

reconcile/openshift_base.py, reconcile/test/oc/test_oc_map.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py, reconcile/utils/oc_map.py
related to https://issues.redhat.com/browse/APPSRE-6438
this PR is the answer to the question: "can we deprecate `OCDeprecated`"
the answer is: "no" :sweat_smile: 
why: because `OCNative` only implements GET related operations (#1400)
=> rename OCDeprecated to OCCli

reconcile/cli.py, reconcile/openshift_saas_deploy.py
part of https://issues.redhat.com/browse/APPSRE-6647
with this change, when we pass `--trigger-reason` to `openshift-saas-deploy`, it will add the content to the slack notification.
the content comes from the tekton [Pipeline/Taks](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/66496) (originating from the trigger integrations: #2422, #3303)
=> [openshift-saas-deploy] add trigger-reason to slack notification

reconcile/utils/jjb_client.py
part of https://issues.redhat.com/browse/APPSRE-7536
the `jenkins-webhooks` integration creates webhooks from gitlab to jenkins based on the job - either a hook for a merge request or a hook for a push.
in this [MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/66494) we added an option for a build job to not be triggered by a push. in such a case, there should be no webhook created:
```
triggers:
- gitlab:
trigger-push: false
```
ref: https://jenkins-job-builder.readthedocs.io/en/latest/triggers.html#triggers.gitlab
=> [jenkins-webhooks] allow no push hook

reconcile/utils/ocm/ocm.py
Hosted-CP clusters can become READY before the console attribute is populated
=> Fix cluster console update attribute

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/gql_definitions/introspection.json, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/typed_queries/saas_files.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/saasherder.py
depends on https://github.com/app-sre/qontract-schemas/pull/438
this PR adds a validation that when `validateTargetsInApp` is set to `true` all targets are validated to be in the same app as the saas file itself.
with such an attribute, we can grant saas file owner full permissions to `targets`.
=> [saas-file-validator] validate targets in app

reconcile/change_owners/self_service_roles.py, reconcile/test/change_owners/test_change_type_self_service_roles.py
self-service roles (roles with a self-service section) must be assigned to at least one approver (user or bot). this avoids the situation that an MR is marked as self-serviceable but no approvers are available.
https://issues.redhat.com/browse/APPSRE-7535
=> [change-owners] avoid orphaned self-service roles

tools/qontract_cli.py
in certain situations, soak day reporting did not choose the soak days for workload/cluster from the right OCM organization. this PR fixes that.
=> fix soak days in upgrade policy cluster fleet reporting

reconcile/aus/base.py
`AddonUpgradePolicy` should use `delete_addon_upgrade_policy` instead of `delete_upgrade_policy`.
=> [ocm-addons-upgrade-scheduler-org] Fix delete addon upgrade policy

reconcile/test/test_ocm_addons_upgrade_scheduler_org.py
Test for previous [pr](https://github.com/app-sre/qontract-reconcile/pull/3495)
=> [ocm-addons-upgrade-scheduler-org] Update test for delete_automatic_upgrade_policy

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/changes.py, reconcile/change_owners/decision.py, reconcile/change_owners/diff.py, reconcile/change_owners/implicit_ownership.py, reconcile/change_owners/self_service_roles.py, reconcile/change_owners/tester.py, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_bundle_change_post_processing.py, reconcile/test/change_owners/test_change_type_context.py, reconcile/test/change_owners/test_change_type_coverage.py, reconcile/test/change_owners/test_change_type_decision.py, reconcile/test/change_owners/test_change_type_diff.py, reconcile/test/change_owners/test_change_type_diff_splitting.py, reconcile/test/change_owners/test_change_type_implicit_ownership.py, reconcile/test/change_owners/test_change_type_priorities.py, reconcile/test/change_owners/test_change_type_processor.py, reconcile/test/change_owners/test_change_type_various.py
Moving files without changing their content is not necessarily self-serviceable via change-types. Since a-i is path-agnostic, we don't really care too much about path changes.
this PR introduces the ability to aggreate an delete/add change that represents a file move, into one change that only has the path as the changing attribute.
https://issues.redhat.com/browse/APPSRE-7590
=> [change-owners] make file moves self-serviceable

reconcile/change_owners/changes.py
disable the new aggregate_file_moves functionality for now because there is a situation where expected metadata seems to be not present, which fails the change-owners integration.
a fix will be provided in an upcoming PR.
https://issues.redhat.com/browse/APPSRE-7590
=> [change-owners] disable file move detection

reconcile/ocm/types.py, reconcile/utils/ocm/ocm.py
master_role_arn is not always set anymore.
Newer clusters do not report it anymore, therefore making it optional
Related issue:
https://issues.redhat.com/browse/SDA-8935
Related Slack thread: https://redhat-internal.slack.com/archives/C02LM9FABFW/p1683718655087619?thread_ts=1683645279.978359&cid=C02LM9FABFW
=> Control Plan Arn is optional

reconcile/aus/base.py, reconcile/test/test_ocm_upgrade_scheduler.py, reconcile/test/utils/test_filtering.py, reconcile/utils/filtering.py
instead of
```
[ocm-addons-upgrade-scheduler-org] ['create', 'my-org', 'my-cluster', '1.2.3']
```
action logging will look like this
```
[ocm-addons-upgrade-scheduler-org] create addon upgrade policy - {'cluster': 'my-cluster', 'ocm-org': 'my-org', 'addon-id': 'my-addon', 'version': '1.2.3', 'next-run': 'soon'}
```
this change also adds back the addon-id to the action log
=> [AUS] more details in action logging

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/aus/ocm_upgrade_scheduler_org.py, reconcile/cli.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, tools/qontract_cli.py
optionally define OCM env and OCM organization ID filters for OCM label based AUS
https://issues.redhat.com/browse/APPSRE-7602
hint for reviewer: the changes in qontract-cli on the various set commands is some cleanup because defining a func called set hides the `set` function that creates ... well a set
=> [AUS] filter clusters to process on a set of org IDs

reconcile/gitlab_owners.py, reconcile/queries.py
Handle `gitlabOwners.persistantLgtm` attribute. Adding a commit or rebasing an MR normally must be approved again (`/lgtm`). Setting `persistantLgtm` to `True` (default `False`) avoids re-approving the MR, and all previous `/lgtm`'s are still considered.
Depends on: https://github.com/app-sre/qontract-schemas/pull/443
Ticket: [APPSRE-7622](https://issues.redhat.com/browse/APPSRE-7622)
=> [gitlab-owners] persistantLgtm

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py, reconcile/cli.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, reconcile/test/ocm/fixtures.py, reconcile/test/ocm/test_utils_ocm_clusters.py, reconcile/test/ocm/test_utils_ocm_subscriptions.py, reconcile/utils/ocm/clusters.py, reconcile/utils/ocm/subscriptions.py, tools/qontract_cli.py
cluster upgrade policies can't be created for STS clusters using a service-account that is not bound to the clusters organization. until that is adressed in OCM, we will ignore STS clusters when using such a service account.
the AUS integration now supports a flag `--ignore-sts-clusters` to ignore STS clusters.
part of https://issues.redhat.com/browse/APPSRE-7578
=> [AUS] add option to ignore STS clusters

dockerfiles/hack/run-integration.py, reconcile/test/test_utils_metrics.py, reconcile/utils/metrics.py, reconcile/utils/runtime/runner.py
Metric families can be represented with pydantic dataclasses.
* use properties as labels - even though prometheus labels are always strings, all types that are convertable to a string can be used. the additional type safety is nice
* the dataclass docstring is used as the metrics description
* the metric name is provided via the `name` classmethod a metric dataclass must implement
* base classes `GaugeMetric`, `InfoMetric` and `CounterMetric` can be used to define what kind of metric a dataclass represents (histogram support will be added later)
```python
class SomeErrorCounter(CounterMetric):
"""
How often some error occured.
"""
component: str
subcomponent: str
critical: bool
@classmethod
def name() -> str:
"some_error_counter"
```
Metrics can be exposed by using the `set_gauge`, …
=> [metrics] pydantic based metrics + metric transactions

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings.py, tools/qontract_cli.py
part of https://issues.redhat.com/browse/APPSRE-7652
this PR adds support to provide `assumeRole` to a cluster to cluster vpc peering, to be used instead of OCM infrastructure access.
similar to #2000
=> [terraform-vpc-peerings] add support for cluster2cluster vpc peerings with assume role

reconcile/saas_auto_promotions_manager/publisher.py, reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py, reconcile/test/saas_auto_promotions_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/subscriber/conftest.py, reconcile/test/saas_auto_promotions_manager/test_integration_test.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_multiple_publishers_for_single_channel.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_saas_files_without_auto_promote.py, reconcile/test/test_auto_promoter.py, reconcile/test/test_saasherder.py, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/test/utils/test_promotion_state.py, reconcile/typed_queries/saas_files.py, reconcile/utils/promotion_state.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/models.py, reconcile/utils/saasherder/saasherder.py
The deployment information (promotion data) is stored in an S3 bucket. Make the S3 key unique to avoid overwrites if multiple publishers are using the same channel name.
`promotions/{channel}/{commit_sha}`  -> `/deployments/{saas_target_uid}/{commit_sha}`
`saas_target_uid` is an unique blake2s hash composed of `{saas_name}/{resource_template_name}/{target_name|"default"}/{cluster_name}/namespace_name}`
Ticket: [APPSRE-7414](https://issues.redhat.com/browse/APPSRE-7414)
=> [openshift saas deploy] multiple publishers

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py, reconcile/aus/metrics.py, reconcile/aus/models.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/aus/ocm_upgrade_scheduler_org.py, reconcile/cli.py, reconcile/test/test_ocm_addons_upgrade_scheduler_org.py, reconcile/test/test_ocm_upgrade_scheduler.py, reconcile/utils/ocm/ocm.py, reconcile/utils/ocm/subscriptions.py, tools/qontract_cli.py
Advanced Upgrade Service is not a regular qontract-reconcile integration but rather an SRE capability with a different support model. AUS will not fail as a mean to signal an issue if it detects something problematic during reconciling. Instead it will expose enough metrics so that fine grained alerts can be defined.
The `aus_cluster_upgrade_policy_info` and `aus_cluster_upgrade_policy_info` metrics are going to be used for reporting purposes.
All metrics are exposed by all flavours of cluster upgrade integrations (the addons upgrade scheduler exposes only counters for reconcile loops & failures per org for now).
See https://service.pages.redhat.com/dev-guidelines/docs/appsre/expose-metrics/ for more information about transactional and scoped metric exposure.
Gauge - Current validation …
=> [AUS] expose metrics

reconcile/aus/advanced_upgrade_service.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, reconcile/utils/ocm/labels.py
discover clusters for AUS based only on subscription labels. the organization labels don't hold any cluster configuration, only org-wide configuration for blocked versions and sectors.
=> [AUS] fix cluster discovery

setup.py
Once the memory leak [problems](https://github.com/boto/boto3/issues/3614) have been solved in boto, it is time to upgrade the libraries.
related to [APPSRE-7361](https://issues.redhat.com/browse/APPSRE-7361)
=> Upgrade boto libraries

reconcile/aws_ami_cleanup/integration.py
It is a condition that won't be solved in a MR, so it doesn't make sense to exit in error.
=> Do not on compare tags error in dry-run in cleanup

reconcile/sql_query.py
part of https://issues.redhat.com/browse/ASIC-417
the sql-query integration is running in a loop, while the previous apiVersion is now deprecated.
=> update cronjob template for sql-query to batch/v1

reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler_org.py
fix a bug that fails the addons-upgrade-scheduler integration if a cluster mentioned in an a-i OCM org file is deprovisioned. ignoring such declarations is a valid solution because such clusters get cleaned up automatically after a while anyways.
=> [addons-upgrade-scheduler] don't fail when clusters get deprovisioned

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/utils/terrascript_aws_client.py
part of https://issues.redhat.com/browse/APPSRE-7734
depends on https://github.com/app-sre/qontract-schemas/pull/460
this PR adds support to allow creating roles with:
- a different assume action (instead of AssumeRole)
- a Federated assume Principal
this is required to attach IAM roles to OpenShift ServiceAccounts.
this fits the backplane usage, but is a good pattern instead of using IAM credentials, so this possibly opens up a door for https://issues.redhat.com/browse/APPSRE-4201
=> add support for assume action and Federated assume principal

reconcile/aus/base.py, reconcile/test/ocm/test_utils_ocm_versions.py, reconcile/utils/ocm/ocm.py
the `OCM.get_available_upgrades()` function gets available upgrades for a specific version in a specific channel. behind the scenes it uses the CS `/v1/versions` endpoint, which potentially fails requests for non stable channels if the requesting account/service-account belongs to an OCM organization that lacks the capability to use such versions.
using this endpoint with a service-account that is not bound to an OCM organization, always fails. 
this PR changes the datasource for the available upgrades information to the`version` section of the OCM cluster spec, which can be safely consumed by service accounts.
`OCM.get_available_upgrades()` is changed to accept a cluster name instead of a current version and channel.
=> [cluster-upgrades] use available upgrade versions from OCM cache

reconcile/cli.py, reconcile/oum/base.py, reconcile/oum/labelset.py, reconcile/oum/metrics.py, reconcile/oum/models.py, reconcile/oum/providers.py, reconcile/oum/standalone.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, reconcile/test/ocm/fixtures.py, reconcile/test/ocm/oum/test_oum_base.py, reconcile/test/ocm/oum/test_oum_providers.py, reconcile/test/ocm/oum/test_oum_standalone.py, reconcile/test/ocm/test_utils_ocm_cluster_groups.py, reconcile/test/ocm/test_utils_ocm_clusters.py, reconcile/test/test_utils_ldap_client.py, reconcile/utils/ldap_client.py, reconcile/utils/metrics.py, reconcile/utils/ocm/cluster_groups.py, reconcile/utils/ocm/clusters.py, reconcile/utils/ocm/labels.py
Implementation of the [Red Hat User Management SRE capability](https://issues.redhat.com/browse/SDE-2628)
This capability can be used by RH internal teams to attach their LDAP groups (e.g. Rover) to the `cluster-admins` or `dedicated-admins` roles of a cluster. Users can declare their desire for group syncs via OCM organization or subscription labels. Group syncs defined on the organization are applied on all clusters of the organization. Group syncs defined on subscriptions will only be applied to the individual clusters. Configuration on the organization and on the subscriptions are cummulative.
If a cluster role is either managed on the organisation or subscription, its current members will be replaced by the ones from the defined LDAP groups.
The following label keys are supported:
* …
=> [cluster user mgmt] OCM cluster user mgmt based standalone service

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/test/test_utils_aws_rds.py, reconcile/utils/cloud_resource_best_practice/aws_rds.py, reconcile/utils/terrascript_aws_client.py
Ensure AWS RDS instances abide by best practices as per https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/aws-rds-backup-config-best-practices.md.
The integration terraform-resources fails if the database attributes does not comply with necessary attributes based on data_classification and loss_impact.
The exception thrown is of the following format
```
reconcile.utils.cloud_resource_best_practice.aws_rds.RDSBestPracticesNotComplied: AWS RDS instance my-db does not comply with best practices
Expected field delete_automated_backups with value "False", found "True" 
Expected field skip_final_snapshot with value "False", found "True"
```
Schema: https://github.com/app-sre/qontract-schemas/pull/439/files
Testing:
- (Happy path, no exceptions) Create a …
=> APPSRE-7526: RDS backup best practices

reconcile/gitlab_members.py, reconcile/test/test_utils_pagerduty_api.py, reconcile/utils/pagerduty_api.py
part of https://issues.redhat.com/browse/APPSRE-7755
the integration seems to be fine with this, as long as there are no permissions with a pagerduty target.
than again, if there are permissions with a pagerduty target, there is a pagerduty instance.
tl;dr this should be fine
=> [gitlab-members] allow to run without a pagerduty instance

reconcile/gitlab_members.py, reconcile/test/test_gitlab_members.py
if a user is associated to the same gitlab group with different access levels - grant them the higher one instead of simply taking the later one that appears in queries.
=> [gitlab-members] grant user higher access level if defined twice

reconcile/ocm_aws_infrastructure_access.py
related to https://issues.redhat.com/browse/APPSRE-7735
when `assume_role` is provided on a namespace aws external resource for an `aws-iam-service-account` provider - it means ocm-aws-infrastructure-access is not the entity to grant the access.
in such case, the integration should skip this resource.
the `assume_role` field is widely used in fedramp, where `ocm-aws-infrastructure-access` is not used.
=> [ocm-aws-infrastructure-access] ignore IAM SAs with assume_role

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py, reconcile/aus/metrics.py, reconcile/aus/models.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/aus/ocm_upgrade_scheduler_org.py, reconcile/gql_definitions/advanced_upgrade_service/aus_clusters.gql, reconcile/gql_definitions/advanced_upgrade_service/aus_clusters.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, reconcile/test/ocm/fixtures.py, reconcile/test/test_utils_metrics.py, reconcile/utils/metrics.py, reconcile/utils/ocm/clusters.py, reconcile/utils/ocm/subscriptions.py
* track organization reconciling total + error with a context manager (automatic counter increases when entering and when failing)
* add the organization name and the current version of a cluster to the `aus_cluster_upgrade_policy_info` metric - useful for dashboards
replaces https://github.com/app-sre/qontract-reconcile/pull/3547
=> [AUS] metrics improvements

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/gql_definitions/common/saas_target_namespaces.py, reconcile/gql_definitions/fragments/saas_target_namespace.gql, reconcile/gql_definitions/fragments/saas_target_namespace.py, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/saasherder.py
with this PR, `validateTargetsInApp` now allows saas file targets (namespaces) to reference a parent app of it's own app.
=> [saas-file-validator] validate targets in app may include parent app

reconcile/oum/base.py, reconcile/test/ocm/fixtures.py, reconcile/test/ocm/oum/test_oum_base.py, reconcile/utils/ocm/clusters.py
currently, the user-mgmt capability refuses to manage cluster-admins groups on clusters without the respective AMS capability. that is the right behaviour for OSD but not for ROSA. for ROSA clusters, the AMS capability is not required.
fix for https://issues.redhat.com/browse/APPSRE-7709
=> [user-mgmt] allow cluster-admin mgmt for rosa clusters

grafana-dashboards/sre-capability-aus.configmap.yaml
* the "currently soaking versions" panel was throwing errors in situations where target labels changed (e.g. pod restarts)
* show the current version of a cluster in the "remaining soak days" panel
* clean pre-selections for filters (accidentally introduced in earlier dashboard changes)
=> [AUS] customer dashboard currently soaking panel fixes

grafana-dashboards/sre-capability-aus.configmap.yaml
previously the dashboard showed the remaining soak days but did not take into account that accumulating soak days from multiple clusters speeds things up.
the update to the "Currently Soaking Versions" panel now shows an estimate on the remaining actual days a version still needs to soak for a specific cluster.
=> [AUS] show estimate remaining days a version needs to soak

reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
Fix `get_existing_state` for terraform repo. I was under the impression that `state.get()` would return a JSON string but instead it returns a Python object. Therefore, I'm switching to `parse_obj()`. See https://docs.pydantic.dev/latest/usage/models/#helper-functions for reference.
=> [tf-repo] Fix for loading state

reconcile/jenkins_job_builder.py, reconcile/queries.py, tools/app_interface_reporter.py
The promotions section is always empty so the data processing makes no sense.
The post_deploy_jobs appears to have more information, e.g.
```
post_deploy_jobs:
- cluster: insights-perf
namespace: platform-mq-perf
post_deploy_job: false
```
but there are never elements with post_deploy_job set to true since post_deploy_jobs are handled differently in Tekton world.
Since they don't longer show anything meaningful and they build on top of soon to be removed app-interface settings such as saasDeployJobTemplate it is good to remove them.
It's important to note that this patch does not remove the sections in the final report as that would imply a change in the content format version.
=> Remove data processing from report from Jenkins CD

reconcile/openshift_base.py, reconcile/openshift_resources_base.py, reconcile/test/test_openshift_resource.py, reconcile/utils/openshift_resource.py
it seems that we lost the ability to enforce managedResourceNames for openshift resource in namespaces (or it never was enforced, who knows).
this PR manages the allowed resources names as part of the `ResourceInventory`. the allowed names are registered along with the allowed resource types during clusteR/namespace/type registration. if a desired resources is added to the inventory with a name that is not managed, an error is raised. the resource inventory will be marked as failed, so the execution will fail (important for PR checks).
the managedResourcesNames remain optional. if none are defined, the resource inventory acts as before, allowing all names.
i'm unsure if we should also fail adding current state resources to the inventory if their name is not managed. i believe it is not …
=> [openshift-resources] enforce managed-resources names

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/utils/terrascript_aws_client.py
* make all AWS resource identifiers unique based on the external resource identifier
* create just one KMS for all scram secrets (save some AWS costs)
* add a human readable KMS alias
* fix scram secret association - it must be just one per MSK cluster
Depends on: https://github.com/app-sre/qontract-schemas/pull/469
Ticket: [APPSRE-7534](https://issues.redhat.com/browse/APPSRE-7534)
=> [terraform-msk] fix identifiers and scram_secret_associations

reconcile/change_owners/bundle.py, reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/changes.py, reconcile/change_owners/implicit_ownership.py, reconcile/change_owners/self_service_roles.py, reconcile/gql_definitions/change_owners/queries/change_types.gql, reconcile/gql_definitions/change_owners/queries/change_types.py, reconcile/gql_definitions/introspection.json, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_bundle_change.py, reconcile/test/change_owners/test_change_type_context.py, reconcile/test/change_owners/test_change_type_implicit_ownership.py, reconcile/test/change_owners/test_change_type_ownership_expansion.py, reconcile/test/fixtures/change_owners/changetype_cluster_owner.yml, reconcile/test/fixtures/change_owners/changetype_role_member.yaml
this PR introduces ownership expansions for resource files based on their usage (backref). if a resourcefile is used within datafile, ownership of the datafile can expand to ownership of the resourcefile with the following configuration, showcasing it for namespaces and RDS default files.
```yaml
$schema: /app-interface/change-type-1.yml
name: namespace-owner
contextType: datafile
contextSchema: /openshift/namespace-1.yml
changes:
- provider: change-type
changeTypes:
- $ref: /app-interface/changetype/rds-defaults-maintainer.yaml
context:
where: backrefs (1)
selector: externalResources[?(@.provider=="aws")].resources[?(@.provider=="rds")].defaults (2)
```
(1) `where: backrefs` defines that the backrefs of a resourcefile need to be inspected in order to relate it back to the owned namespace …
=> [change-owners] resourcefile backrefs for ownership expansion

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py
ownership expansion was not processed correctly when combined with change-type inheritance
part of https://issues.redhat.com/browse/APPSRE-7812
fix for https://github.com/app-sre/qontract-reconcile/pull/3596
=> [change-types] fix ownership expansion on inheritance edges

reconcile/openshift_saas_deploy.py, reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_tekton_resources.py, reconcile/test/fixtures/openshift_tekton_resources/provider2-with-resources.json, reconcile/test/fixtures/openshift_tekton_resources/provider4-with-task-duplicates.json, reconcile/test/fixtures/openshift_tekton_resources/provider5-with-unknown-task.json, reconcile/test/fixtures/openshift_tekton_resources/provider6-too-long-pipeline-name.yaml, reconcile/test/fixtures/openshift_tekton_resources/saas-deploy-too-long-name.pipeline.yaml.j2, reconcile/test/fixtures/openshift_tekton_resources/saas-deploy-with-unknown-task.pipeline.yaml.j2, reconcile/test/fixtures/openshift_tekton_resources/saas-deploy.pipeline.yaml.j2, reconcile/test/fixtures/openshift_tekton_resources/saas6-39-chars-name.yaml, reconcile/test/fixtures/queries/pipelines_providers_all_defaults.json, reconcile/test/fixtures/queries/pipelines_providers_mixed.json, reconcile/test/fixtures/saasherder/saas-templated-params.gql.yml, reconcile/test/fixtures/saasherder/saas.gql.yml, reconcile/test/fixtures/saasherder_populate_desired/saas_remote_openshift_template.yaml, reconcile/test/fixtures/typed_queries/saas_files-missing-provider.yml, reconcile/test/fixtures/typed_queries/saas_files.yml, reconcile/test/test_openshift_saas_deploy.py, reconcile/test/test_openshift_saas_deploy_change_tester.py, reconcile/test/test_openshift_tekton_resources.py, reconcile/test/test_typed_queries/test_saas_files.py
Pipeline names are built using the following convention:
```
o-<one per saas file pipeline name>-<saas file name>
```
The max size of `<saas file name>` was chosen to be 39 characters taking
into account that pipeline name was `openshift-saas-file`, so that we
can have pipelines with names up to 63 characters. This also worked well
with our PipelineRuns, which appended a 14 characeters date but trimmed
the Pipeline size so that, again, objects were right in size.
This didn't take into account that Tekton retries create PipelineRun names
that are named appending a 7 character random string to the corresponing
Pipeline name, which make certain Pipeline names not possible.
This patch makes sure that we have Pipeline names that will be suitable
for Tekton retries. It also changes many …
=> Limit the size of Tekton Pipeline names
