setup.py

part of https://issues.redhat.com/browse/APPSRE-4425
required so we can use the `black-list-commit-author` feature introduced in https://opendev.org/jjb/jenkins-job-builder/commit/987dbc4d2bf47502ba3ba367e8b62b5c629e9f73

update jjb module to latest

---

reconcile/jira_watcher.py

even if an issue was deleted, post the message with a link. it's likely it was moved, and a link will still lead to the moved ticket.
worst case - it's a dead link.

[jira-watcher] post link for deleted issues

---

reconcile/test/test_saasherder.py
reconcile/utils/saasherder.py

This PR adds additional validations on saas files at PR_CHECK level. 
* Check that channels set in `subscribe` are published by any target
* Check that source repository is equal for publisher and subscriber targets
Check the JIRA ticket for additional information

APPSRE-4422: Check saas promotions source respositories

---

reconcile/user_validator.py

Part of [APPSRE-4507](https://issues.redhat.com/browse/APPSRE-4507)
Signed-off-by: Suzana Nesic <snesic@redhat.com>

Making the error message more detailed by printing the expected username

---

reconcile/terraform_resources.py
reconcile/utils/terrascript_client.py

depends on https://github.com/app-sre/qontract-schemas/pull/79
1st step for https://github.com/app-sre/qontract-reconcile/pull/2100

move image id from default to namesapce file

---

reconcile/utils/terrascript_client.py

This was missing from the fix in #2182

fix pg name for elasticache instance

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.dev
dockerfiles/structure-test.yaml

following up on https://github.com/app-sre/container-images/pull/35

promote qontract-reconcile-base image to 0.7.2

---

reconcile/blackbox_exporter_endpoint_monitoring.py

Follows up to https://github.com/app-sre/qontract-reconcile/pull/2184
Part of: https://issues.redhat.com/browse/APPSRE-4523

code optimization for allowed bb-exporter modules

---

tools/qontract_cli.py

Due to a bad conflict resolution

Fix missing imports in qontract_cli

---

.pylintrc
reconcile/openshift_resources_base.py
reconcile/quay_membership.py
reconcile/sentry_config.py
reconcile/terraform_resources.py
reconcile/utils/aws_api.py
reconcile/utils/binary.py
reconcile/utils/environ.py
reconcile/utils/gitlab_api.py
reconcile/utils/jjb_client.py
reconcile/utils/oc.py
reconcile/utils/openshift_resource.py
reconcile/utils/raw_github_api.py
reconcile/utils/sentry_client.py

Fixing a couple of pylint issues and "un-disabling" the corresponding checks
* bad-super-call
* cell-var-from-loop
* consider-using-dict-items
* dangerous-default-value
This PR is best reviewed commit by commit

Pylint fixes

---

reconcile/queries.py

add resourcesDefaultRegion to aws infra management account query

---

.gitignore
reconcile/ldap_users.py
reconcile/queries.py
reconcile/test/test_ldap_users.py
reconcile/test/test_utils_ldap_client.py
reconcile/utils/ldap_client.py

This change is dependent on this [schema](https://github.com/app-sre/qontract-schemas/pull/90) and should not be merged in before schema update is merged. 
Definitely appreciate any feedback as this is my first time using python and also the testing framework.

APPSRE-4403 Update ldap_client to use a-i settings

---

reconcile/gitlab_members.py
reconcile/sendgrid_teammates.py

will fix https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/117473/app-interface_20JSON_20validation/

fix loop on None

---

helm/qontract-reconcile/values-external.yaml
helm/qontract-reconcile/values-internal.yaml
openshift/qontract-reconcile-internal.yaml
openshift/qontract-reconcile.yaml

https://coreos.slack.com/archives/CKN746TDW/p1646726576212579

run openshift-resourcequotas internally

---

reconcile/utils/terrascript_client.py

remove test code

---

reconcile/aws_ami_share.py

because why would you
part of https://issues.redhat.com/browse/APPSRE-4621

[aws-ami-share] do not initiate users

---

reconcile/aws_iam_keys.py

[aws-iam-keys] do not fail on missing account

---

reconcile/aws_iam_keys.py

Reverts app-sre/qontract-reconcile#2232

Revert "[aws-iam-keys] do not fail on missing account"

---

reconcile/terraform_resources.py
reconcile/utils/terrascript_client.py

[APPSRE-4674](https://issues.redhat.com/browse/APPSRE-4674
)
depends on https://github.com/app-sre/qontract-schemas/pull/92

add assume_condition

---

reconcile/test/test_utils_aws_helper.py
reconcile/test/test_utils_ocm.py
reconcile/utils/aws_helper.py
reconcile/utils/ocm.py
reconcile/utils/terrascript_client.py
tools/qontract_cli.py

along with some refactoring.
this command will find it's way into app-interface-output: https://gitlab.cee.redhat.com/service/app-interface-output

[qontract-cli] get clusters-aws-account-ids

---

reconcile/ocm_upgrade_scheduler.py
reconcile/queries.py
reconcile/test/test_ocm_upgrade_scheduler.py
tools/qontract_cli.py

depends on https://github.com/app-sre/qontract-schemas/pull/96

APPSRE-4029 simultaneous cluster upgrades

---

reconcile/github_org.py
reconcile/openshift_base.py
reconcile/openshift_clusterrolebindings.py
reconcile/openshift_resources_base.py
reconcile/openshift_rolebindings.py
reconcile/queries.py

fix determine user key for openshift access

---

reconcile/openshift_resources_base.py
reconcile/test/test_openshift_resource.py
reconcile/utils/openshift_resource.py

part of https://issues.redhat.com/browse/APPSRE-4714
this PR adds support for Secret stringData, which will not cause endless reconciliation.

openshift support for Secret stringData

---

tools/qontract_cli.py

https://issues.redhat.com/browse/APPSRE-4029

APPSRE-4029 add qontract-cli cluster-upgrade-policies md output doc for mutexes

---

reconcile/queries.py
reconcile/utils/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-4716
depends on https://github.com/app-sre/qontract-schemas/pull/101

saasherder add support for secret parameters

---

pyproject.toml
reconcile/github_org.py
reconcile/github_owners.py
reconcile/github_repo_permissions_validator.py
reconcile/github_users.py
reconcile/gitlab_fork_compliance.py
reconcile/gitlab_housekeeping.py
reconcile/gitlab_owners.py
reconcile/jira_watcher.py
reconcile/slack_base.py
reconcile/slack_cluster_usergroups.py
reconcile/slack_usergroups.py
reconcile/test/test_checkpoint.py
reconcile/test/test_openshift_resource.py
reconcile/test/test_saasherder.py
reconcile/test/test_slack_base.py
reconcile/test/test_slack_usergroups.py
reconcile/test/test_terraform_vpc_peerings.py
reconcile/test/test_terraform_vpc_peerings_build_desired_state.py
reconcile/test/test_utils_aws_api.py
reconcile/test/test_utils_expiration.py
reconcile/test/test_utils_sharding.py
reconcile/test/test_utils_slack_api.py
reconcile/test/test_utils_terrascript_client.py

Enable black formatting for:
- test files
- github integrations
- gitlab integrations
- jira integrations
- slack integrations

APPSRE-4354 more black formatting

---

tools/qontract_cli.py

- show ongoing upgrades (with a :dizzy: sign)
- show ready upgrades with 0 soak days (was not shown before)
- ensure maximum one versions shows ready or ongoing

qontract-cli cluster-upgrade-policies improvements

---

reconcile/test/test_utils_oc.py
reconcile/utils/oc.py

instead of searching for a specific name, process the entire pod spec to find used resources and check if the requested name exists in them.
TODO: tests.

[oc] refactor secret/configmap used in pod

---

reconcile/utils/aws_api.py

This was forgotten when refactoring code to aws_helper.py

Fix old reference to get_tf_secrets

---

reconcile/utils/aws_api.py

The previous attempt was buggy.

Re-fix dangling reference to get_tf_secret

---

reconcile/test/conftest.py
reconcile/test/test_secret_reader.py
reconcile/test/test_utils_gitlab_api.py
tox.ini

This should take >30 seconds off of the time it takes to run CI.

Speed up some unit tests and skip install for formatting

---

helm/qontract-reconcile/values-fedramp.yaml
openshift/qontract-reconcile-fedramp.yaml

This MR disables slack reporting from the q-r deployment side in fedramp.

Turn off slack reporting for fedramp

---

reconcile/prometheus_rules_tester.py

prometheus-rules-tester be more forgiving with variables

---

.github/dependabot.yml

Check for dependencies once per week

---

README.md
helm/qontract-reconcile/values-external.yaml
openshift/qontract-reconcile.yaml

part of https://issues.redhat.com/browse/APPSRE-4700

add signalfx-prometheus-endpoint-monitoring integration to template

---

README.md
build_deploy.sh
build_tag.sh
reconcile/test/test_utils_semver_helper.py
reconcile/test/test_version_bump.py
reconcile/utils/semver_helper.py
requirements/requirements-type.txt
setup.py

follows up on #2326
this PR will force each future PR to bump the version in setup.py to a higher version.

force setup.py version bump in PRs

---

reconcile/gitlab_housekeeping.py
reconcile/utils/gitlab_api.py
setup.py

Using MRState values instead of strings

---

reconcile/openshift_saas_deploy.py
reconcile/openshift_saas_deploy_trigger_base.py
reconcile/openshift_saas_deploy_trigger_configs.py
reconcile/openshift_saas_deploy_trigger_moving_commits.py
reconcile/openshift_saas_deploy_trigger_upstream_jobs.py
reconcile/queries.py
reconcile/saas_file_owners.py
reconcile/saas_file_validator.py
reconcile/utils/saasherder.py
tools/qontract_cli.py

There seem to be some open issues - while fixing those, we revert to latest stable
This reverts commit c8396c8cec05e9fd0a62a18c84ad6b5cbea41313.

Revert "APPSRE-3556 remove saas-file-1 logic (#2339)"

---

helm/qontract-reconcile/values-external.yaml
openshift/qontract-reconcile.yaml
reconcile/cli.py
reconcile/terraform_users.py
reconcile/terraform_users_wrapper.py

Add terraform users wrapper

---

reconcile/utils/terrascript_client.py

Making ami warning message more detailed

---

reconcile/gitlab_mr_sqs_consumer.py
reconcile/mr_client_gateway.py
reconcile/queries.py

Remove `saas-file-1` from:
- `gitlab-mr-sqs-consumer` integration
- `mr_client_gateway`
Tested locally via `gitlab-mr-sqs-consumer --dry-run`

APPSRE-3556 remove more saas-file-1 occurrences

---

debugging.py
reconcile/cli.py
reconcile/ocm_upgrade_scheduler.py
reconcile/test/test_ocm_upgrade_scheduler.py
reconcile/test/test_utils_ocm.py
reconcile/test/test_utils_ocm_versions.py
reconcile/utils/ocm.py
tools/qontract_cli.py

Make it possible to add verionGateAgreements to cluster resources.
Implements APPSRE-4704

Add Version Gate Agreements

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-reconcile-fedramp.yaml
openshift/qontract-reconcile-internal.yaml
openshift/qontract-reconcile.yaml

empty variables make it harder to compare current and desired resource. this MR updates the template so empty environment variables are not added to the template.

no empty environment variables in template

---

reconcile/terraform_resources.py
reconcile/utils/terrascript_client.py

https://issues.redhat.com/browse/APPSRE-4651
Depends on https://github.com/app-sre/qontract-schemas/pull/138

[tf-r] add secrets-manager-service-account

---

reconcile/utils/terrascript_client.py

fix iam user policy depends

---

reconcile/utils/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-5500
following up on https://github.blog/changelog/2022-05-03-increased-file-size-limit-when-retrieving-file-contents-via-rest-api
we are seeing a change in github API behavior. namely, a `GithubException` is no longer raised, and we can not detect that we have a problem with a file being too large. while the above blog post indicates the required changes to consume a file from a single endpoint regardless of it's size, that will require a change to headers, which should likely get implemented in PyGithub.
nonetheless, this change will work as is. in fact, this was how we should have done this to begin with (#1364).

saasherder get contents from endpoint by file size

---

helm/README.md
reconcile/test/fixtures/helm/basic.yml
reconcile/test/fixtures/helm/cache.yml
reconcile/test/fixtures/helm/command.yml
reconcile/test/fixtures/helm/concurrency_policy.yml
reconcile/test/fixtures/helm/cron.yml
reconcile/test/fixtures/helm/dashdotdb.yml
reconcile/test/fixtures/helm/disable_unleash.yml
reconcile/test/fixtures/helm/extra_args.yml
reconcile/test/fixtures/helm/extra_env.yml
reconcile/test/fixtures/helm/failure_history.yml
reconcile/test/fixtures/helm/internal_certificates.yml
reconcile/test/fixtures/helm/logs_slack.yml
reconcile/test/fixtures/helm/restart_policy.yml
reconcile/test/fixtures/helm/shards.yml
reconcile/test/fixtures/helm/sleep_duration.yml
reconcile/test/fixtures/helm/state.yml
reconcile/test/fixtures/helm/storage.yml
reconcile/test/fixtures/helm/success_history.yml
reconcile/test/fixtures/helm/trigger.yml
reconcile/test/test_utils_helm.py
reconcile/utils/helm.py

part of https://issues.redhat.com/browse/APPSRE-3344
generated docs: https://github.com/app-sre/qontract-reconcile/blob/f72b3dd2bf8c744afed9ae3f5fb5483dbfbfa9bd/helm/README.md

add documentation and tests for qontract-reconcile helm chart

---

reconcile/test/test_utils_ocm.py
reconcile/utils/ocm.py

Add pagination for ocm get calls

APPSRE-5476 Add pagination for lists

---

reconcile/test/test_utils_ocm.py
reconcile/utils/ocm.py

Reverts app-sre/qontract-reconcile#2376

Revert "APPSRE-5476 Add pagination for lists"

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.test

follows up on:
- https://github.com/app-sre/container-images/pull/41
- https://github.com/app-sre/container-images/pull/42

bump base images

---

dockerfiles/Dockerfile
dockerfiles/structure-test.yaml

Reverts app-sre/qontract-reconcile#2393

Revert "run integration with current work dir near source code"

---

reconcile/queries.py

based on https://github.com/app-sre/qontract-reconcile/tree/master/helm#integration-spec-configuration

integrations-manager query all integrations spec fields

---

reconcile/utils/terrascript_client.py

depends on https://github.com/app-sre/qontract-schemas/pull/142
part of https://issues.redhat.com/browse/APPSRE-5501

add vpc_zone_identifier for asg

---

reconcile/terraform_resources_wrapper.py

Reverts app-sre/qontract-reconcile#2418

Revert "[terraform-resources-wrapper] fix calling integraions name for filtering out clusters"

---

reconcile/utils/terrascript_client.py

depends on https://github.com/app-sre/qontract-schemas/pull/147
part of https://issues.redhat.com/browse/APPSRE-5501

remove availability_zones for asg

---

tools/qontract_cli.py

This will provide the cluster upgrade schedule in a tooltip on the 💫 sign when an upgrade is planned or ongoing

q-cli cluster-upgrade-policies md output : display the upgrade schedule time in a tooltip

---

reconcile/queries.py
reconcile/utils/saasherder.py

fix typo for trigger traceability

---

reconcile/cli.py
reconcile/openshift_saas_deploy.py
reconcile/openshift_saas_deploy_wrapper.py

right now we are (implicitly) using the jump host for all our deployments.
with this PR, we add an option to _not_ use the jump host.

[openshift-saas-deploy] enable option to not use jump host

---

tools/qontract_cli.py

these 2 commands show how many resources are managed via app-interface.

[cli] add stats commands for resource usage

---

reconcile/openshift_tekton_resources.py

Implements sharding as required per: [APPSRE-5705](https://issues.redhat.com/browse/APPSRE-5705)

Add sharding by saas file

---

tools/qontract_cli.py

[cli] add total line to resources commands

---

dockerfiles/Dockerfile

Bump base images to include new AWS Provider version

---

reconcile/ecr_mirror.py
reconcile/gabi_authorized_users.py
reconcile/ocm_aws_infrastructure_access.py
reconcile/ocp_release_mirror.py
reconcile/osd_mirrors_data_updater.py
reconcile/queries.py
reconcile/service_dependencies.py
reconcile/sql_query.py
reconcile/terraform_aws_route53.py
reconcile/terraform_resources.py
reconcile/test/fixtures/expiration/expiration_date_check.yml
reconcile/test/fixtures/gabi_authorized_users/apply.yml
reconcile/test/fixtures/openshift_resource/invalid_expiration_date.yml
reconcile/test/test_utils_external_resources.py
reconcile/utils/external_resources.py
reconcile/utils/terrascript_aws_client.py
tools/qontract_cli.py

part of https://issues.redhat.com/browse/APPSRE-5711
this PR adds a common function that considers `externalResources` and using it from across the code base.

External resources adjustment

---

reconcile/prometheus_rules_tester.py

Prometheus operator establishes a limit on the size of a single
PrometheusRule based on the maximum size of a ConfigMap. From that
moment on it will stop processing new rules.
Since we have rules that are heavily templated via queries, it is not
that uncommon that we get to that limit. This will protect us from that
to happen.
Part of APPSRE-5640

Added rule length check to prometheus rules tester

---

reconcile/jenkins_job_builds_cleaner.py

We need to know what instance has builds to delete

Add loggin instance to jb-cleaner

---

reconcile/utils/quay_api.py

Without a timeout in requests, it will default to no timeout, which
can cause requests to hang forever. This is suspected to be the cause
of some of the Quay integrations being stuck for hours.
Ran the `quay-mirror-org` integration in dry-run mode to ensure there weren't any major issues.

Add request timeouts to QuayApi

---

reconcile/utils/terrascript_aws_client.py

Reverting [2423](https://github.com/app-sre/qontract-reconcile/pull/2423)

Revert 2423

---

reconcile/cli.py
reconcile/queries.py
reconcile/terraform_aws_route53.py

part of https://issues.redhat.com/browse/APPSRE-5885
this will allow running this integrations sharded `per-aws-account`.

[terraform-aws-route53] enable running per account

---

reconcile/utils/smtp_client.py

A better approach should be done as part of [APPSRE-5894](https://issues.redhat.com/browse/APPSRE-5894)

Add hardcoded timeout to IMAP and SMTP clients

---

reconcile/openshift_upgrade_watcher.py
reconcile/test/test_openshift_upgrade_watcher.py

`ocm_map.cluster_specs()` returns all clusters under the OCM instance, not only those registered in app-interface. Which means we end up failing on those which are not registered because of missing slack group.
```
reconcile.utils.slack_api.UsergroupNotFoundException: appint-ex-01-cluster
```
This fix means we base our decision on the version in app-interface, which itself is being updated automatically by `ocm-clusters`. It also has a nice side effect that we have no more calls to ocm, which speeds things up.

fix: consider only clusters under app-interface control

---

reconcile/utils/saasherder.py

related to https://issues.redhat.com/browse/APPSRE-4854
whlie we investigate why github connection errors occur, we can retry harder.
the default number of attempts is 3.

retry harder to get file contents

---

pyproject.toml
reconcile/terraform_resources.py
reconcile/utils/terraform_client.py
reconcile/utils/terrascript_aws_client.py

as we are refactoring terraform related files as part of https://issues.redhat.com/browse/APPSRE-5833, we are not likely to revert.
time to format!

[black] format terraform

---

reconcile/sql_query.py
reconcile/test/test_utils_external_resource_spec.py
reconcile/utils/external_resource_spec.py
reconcile/utils/terrascript_aws_client.py

[terrascript] simplify init_values and init_common_outputs

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager.yaml
reconcile/test/fixtures/helm/aws_account_shards.yml
reconcile/test/fixtures/helm/basic.yml
reconcile/test/fixtures/helm/cache.yml
reconcile/test/fixtures/helm/command.yml
reconcile/test/fixtures/helm/disable_unleash.yml
reconcile/test/fixtures/helm/environment_aware.yml
reconcile/test/fixtures/helm/exclude_service.yml
reconcile/test/fixtures/helm/extra_args.yml
reconcile/test/fixtures/helm/extra_env.yml
reconcile/test/fixtures/helm/integrations_manager.yml
reconcile/test/fixtures/helm/internal_certificates.yml
reconcile/test/fixtures/helm/logs_slack.yml
reconcile/test/fixtures/helm/shards.yml
reconcile/test/fixtures/helm/sleep_duration.yml
reconcile/test/fixtures/helm/state.yml
reconcile/test/fixtures/helm/storage.yml
reconcile/test/fixtures/helm/trigger.yml

follows up on #2346
docs: https://www.civo.com/learn/yaml-best-practices-using-kubelinter#ignoring-a-check

disable dvo checks for probes

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager.yaml
reconcile/test/fixtures/helm/aws_account_shards.yml
reconcile/test/fixtures/helm/basic.yml
reconcile/test/fixtures/helm/cache.yml
reconcile/test/fixtures/helm/command.yml
reconcile/test/fixtures/helm/disable_unleash.yml
reconcile/test/fixtures/helm/environment_aware.yml
reconcile/test/fixtures/helm/exclude_service.yml
reconcile/test/fixtures/helm/extra_args.yml
reconcile/test/fixtures/helm/extra_env.yml
reconcile/test/fixtures/helm/integrations_manager.yml
reconcile/test/fixtures/helm/internal_certificates.yml
reconcile/test/fixtures/helm/logs_slack.yml
reconcile/test/fixtures/helm/shards.yml
reconcile/test/fixtures/helm/sleep_duration.yml
reconcile/test/fixtures/helm/state.yml
reconcile/test/fixtures/helm/storage.yml
reconcile/test/fixtures/helm/trigger.yml

fix typo in dvo diable annotation

---

reconcile/openshift_resources_base.py

[openshift-resources] add hint for unknown kind error

---

reconcile/queries.py
reconcile/sentry_helper.py
reconcile/test/test_utils_imap_client.py
reconcile/test/test_utils_smtp_client.py
reconcile/utils/imap_client.py
reconcile/utils/smtp_client.py
requirements/requirements-test.txt

* Move IMAP operations into new utils.ImapClient
* Add timeout option for SmtpClient and ImapClient
* Add unittests for both clients
https://issues.redhat.com/browse/APPSRE-5894

APPSRE-5894: Refactor utils.SmtpClient

---

reconcile/utils/terrascript_aws_client.py

Reverts app-sre/qontract-reconcile#2519

Revert "Force Terraform to respect DAG [rosa-authenticator]"

---

reconcile/utils/ocm.py

UserList may be empty for a specific group.

fix get user from ocm groups

---

reconcile/utils/terrascript_aws_client.py

I can only mess this up so many times.

(fedramp) rosa-authenticator: fix http_method references (try 3)

---

reconcile/utils/terrascript_aws_client.py

(fedramp) rosa-authenticator: fix http_method references - Try 4

---

reconcile/utils/terrascript_aws_client.py

The way we're doing it now may be making terraform behave unexpectedly.

(fedramp) rosa: strict hcl interpretation for status_codes

---

reconcile/utils/terrascript_aws_client.py

Not in POC:
https://gitlab.redhat-osd.local/service/terraform-ocm-cognito-api-gw/-/blob/efaf6e75e080a71e439fb8f7c06e16aaf6da124d/api_gateway.tf#L121-134

(fedramp) rosa - rm unneeded gw_integration_token property

---

reconcile/openshift_resources_base.py
reconcile/prometheus_rules_tester.py
reconcile/template_tester.py
reconcile/test/fixtures/amtool/alertmanager.yaml
reconcile/test/test_amtool.py
reconcile/utils/amtool.py
reconcile/utils/terrascript_aws_client.py
tools/qontract_cli.py

This is the third attempt of https://github.com/app-sre/qontract-reconcile/pull/2488
I needed to revert the previous attempt #2523 in #2527 due to issues in a cluster that made the concept of deploying new things to prod a bad idea 😅

Create command to test Alertmanager receiver config (3rd attempt)

---

reconcile/gql_queries/service_dependencies/service_dependencies.py
reconcile/service_dependencies.py
requirements/requirements-generator.txt
setup.py

Do not load query from .gql file -> consume string directly.

APPSRE-5046 package gql files

---

Makefile
requirements/requirements-generator.txt
requirements/requirements-type.txt

Install code generator `qenerate` from pypi instead from github commit.

APPSRE-5946 get qenerate from pypi

---

reconcile/sql_query.py

see [#APPSRE-5774](https://issues.redhat.com/browse/APPSRE-5774?focusedCommentId=20561862&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20561862)
needed for #2522

add sql-query label to all k8s objects

---

reconcile/terraform_resources.py

Missing part of https://github.com/app-sre/qontract-reconcile/pull/2569

Fix: Set privileged attribute when populating desired state in tf integration

---

reconcile/gitlab_housekeeping.py
reconcile/utils/gitlab_api.py

the possible values for `merge_status` are: https://docs.gitlab.com/ee/api/merge_requests.html#single-merge-request-response-notes
we can be stricter about the merge requests we want to rebase/merge.

avoid unchecked merge status

---

reconcile/gitlab_housekeeping.py
reconcile/utils/gitlab_api.py

Reverts app-sre/qontract-reconcile#2581

Revert "avoid unchecked merge status"

---

reconcile/sql_query.py
reconcile/test/test_sql_query.py

Instead of retrieving SQL queries as command line parameters, get them via a config map file. So it's possible to run queries larger than 4096 characters long.
Additionally, add type annotations and some small refactorings.
see APPSRE-5774

APPSRE 5774 sql query large queries

---

reconcile/sql_query.py
reconcile/test/test_sql_query.py

Instead of giving SQL query as a command line parameter, get it via a config map file.
find and delete k8s objects by labels
see APPSRE-5774

sql_query: large query support (#2522)

---

reconcile/terraform_resources.py
reconcile/utils/terrascript_aws_client.py

* add required variables to GQL query in terraform_resources.py
* reduce name string lengths to satisfy AWS naming requirements
* add data source resources to tf_resources
* fix parameter path in data source

rosa-authenticator deadline bugfixes

---

reconcile/queries.py

part of https://issues.redhat.com/browse/APPSRE-6028
required for following PRs (such as #2595)

add path to saas file target query

---

reconcile/utils/terrascript_aws_client.py

avoid "legacy formatting" error

Add brackets around statement

---

reconcile/saas_file_owners.py

handle case where saas file target path is none

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager.yaml
reconcile/test/fixtures/helm/aws_account_shards.yml
reconcile/test/fixtures/helm/basic.yml
reconcile/test/fixtures/helm/cache.yml
reconcile/test/fixtures/helm/command.yml
reconcile/test/fixtures/helm/disable_unleash.yml
reconcile/test/fixtures/helm/environment_aware.yml
reconcile/test/fixtures/helm/exclude_service.yml
reconcile/test/fixtures/helm/extra_args.yml
reconcile/test/fixtures/helm/extra_env.yml
reconcile/test/fixtures/helm/integrations_manager.yml
reconcile/test/fixtures/helm/internal_certificates.yml
reconcile/test/fixtures/helm/logs_slack.yml
reconcile/test/fixtures/helm/shards.yml
reconcile/test/fixtures/helm/sleep_duration.yml
reconcile/test/fixtures/helm/state.yml
reconcile/test/fixtures/helm/storage.yml
reconcile/test/fixtures/helm/trigger.yml

```
❯ time oc get rs | wc -l
27254
oc get rs  15.03s user 1.09s system 70% cpu 22.773 total
wc -l  0.11s user 0.22s system 1% cpu 22.772 total
```

Limit the number of revisions per deployment

---

reconcile/utils/mr/auto_promoter.py
reconcile/utils/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-6028
this MR introduces handling for automated promotions in targets which are referenced from saas files and not inlined.

[automated promotions] support referenced targets

---

reconcile/utils/terrascript_aws_client.py

JIRA - [APPSRE-4543](https://issues.redhat.com/browse/APPSRE-4543)

APPSRE-4543 - Replace inline policies for managed policies

---

reconcile/utils/terrascript_aws_client.py

We only need to get log_group_infos for the current account while self.account_resource_specs.values() will return all accounts's resource.

get log_group_infos only for current account

---

reconcile/sql_query.py

* run query jobs with dedicated service account
* set memory and cpu limits
APPSRE-6042

sql-query: DVO complicance

---

reconcile/test/test_unleash.py
reconcile/utils/oc.py
reconcile/utils/unleash.py

Fixing previous PR, that required rollback: https://github.com/app-sre/qontract-reconcile/pull/2596

Unleash client refactor

---

reconcile/utils/oc.py

to handle these cases when validating volumes: https://github.com/RedHatInsights/turnpike/blob/f7332782411acb82a61d9c7de7126c49ea4b6ffa/templates/prometheus-nginx.yml#L47
following up on #2261

validate planned data handle null cases

---

reconcile/utils/oc.py

yes, i am a mess today. here is a fix for the tests that i broke in #2626

fix oc tests

---

reconcile/cli.py

following up on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44052
this PR will make sure we havn't left anything behind.

default to not using jump host

---

reconcile/utils/gitlab_api.py
tools/qontract_cli.py

Don't skip MRs when the last comment is from AppSRE but a trigger phrase.
See APPSRE-6079

qontract-cli review-queue: consider trigger phrases

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.test

To only contain the relevant terraform aws provider versions.
part of APPSRE-3598.

Upgrade base images

---

reconcile/quay_mirror.py

This will help debugging issues in ASIC-280.

Add debug log line on deep sync mode

---

dockerfiles/hack/run-integration.py

Add LOG_LEVEL to dockerfile run-integration script

---

reconcile/utils/terrascript_aws_client.py

fix typo in getting s3 versioning parameter
APPSRE-6048

terraform-resources: s3 bucket versioning

---

reconcile/quay_mirror.py

They're misleading as some checks are not actually done while the
messages appeared to suggest they were being done.

Clarified quay-mirror debug messages

---

reconcile/utils/terrascript_aws_client.py

[JIRA](https://issues.redhat.com/browse/APPSRE-4543)
This time I tested against our dev environment with plan and apply.

APPSRE-4543 Fix - Add inline user policies

---

reconcile/utils/terrascript_aws_client.py

[APPSRE-6073](https://issues.redhat.com/browse/APPSRE-6073)
Update ROSA authenticator to add WAF logging.

rosa-authenticator WAF logging

---

reconcile/utils/saasherder.py

we are currently skipping this test if imagePatterns is empty.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44340

[saasherder] check images when imagePatterns is empty

---

reconcile/gitlab_housekeeping.py

fix bot again

---

reconcile/utils/terrascript_aws_client.py

[APPSRE-6073](https://issues.redhat.com/browse/APPSRE-6073)

fix log_destination_configs param for ROSA authenticator

---

reconcile/utils/terrascript_aws_client.py

[APPSRE-6073](https://issues.redhat.com/browse/APPSRE-6073)

WAF Rename ROSA  Authenticator

---

reconcile/utils/gitlab_api.py

trying to make up a bit for this mess: https://github.com/app-sre/qontract-reconcile/compare/51ea56c3688afe8fccc885ecea2c6e0ebb182066...821b092a230d78a986294d5e497f1eefb347ae36
related to:
- #2659
- #2660
- #2661

add type hint to gl.user

---

tools/qontract_cli.py

this command (running in app-interface-output) will allow us to look into intervals between merges to get an understanding of how slow/fast things are going.
this is a complement to `qontract-cli get app-interface-merge-queue`.

[qontract-cli] add get app-interface-merge-history command

---

reconcile/gql_queries/service_dependencies/service_dependencies.py
tox.ini

CI should check if currently generated classes are indeed based on committed `introspection.json`.

APPSRE-5947 detect generated class drift

---

reconcile/utils/terraform_client.py

expiration date for tf-r deletionApprovals should contain current date

---

reconcile/quay_mirror.py

closes https://issues.redhat.com/browse/SDE-1246
replaces #1349

Don't mirror any docker.io images to public repos

---

reconcile/queries.py

align query indentation

---

reconcile/cli.py

following https://github.com/app-sre/qontract-reconcile/pull/2682
aws-iam-keys is part of tf-r

add environ for tf-r

---

reconcile/openshift_resources.py
reconcile/openshift_resources_base.py
reconcile/openshift_routes.py
reconcile/openshift_vault_secrets.py

some refactoring (no logic change) to prepare for early exit for openshift-resources based integrations.

[openshift-resources*] early exit prepare

---

reconcile/openshift_vault_secrets.py

with this integration, the desired state is captured within namespace files, so the early exit is quite simple.
depends on #2706

[openshift-vault-secrets] early exit

---

reconcile/github_org.py

part of https://issues.redhat.com/browse/APPSRE-6098

[github-org] early exit pr-check dry-runs

---

reconcile/terraform_users.py

we only care about accounts and the roles query (covering roles, users, aws accounts, groups)

[terraform-users] early exit

---

e2e_tests/test_base.py
reconcile/openshift_network_policies.py
reconcile/openshift_resources_base.py
reconcile/queries.py
reconcile/terraform_resources.py

consolidate all jump host queries

---

reconcile/gitlab_housekeeping.py

Keep track of who added a label and remove it when no one else with proper permissions added it as well.

gitlab-housingkeeping: don't fight with gitlab-labeler

---

reconcile/utils/terrascript_aws_client.py

Reverts app-sre/qontract-reconcile#2724

Revert "[terraform-resources] cloudwatch validate elasticsearch domain exists"

---

reconcile/openshift_base.py

Follow up to [2676](https://github.com/app-sre/qontract-reconcile/pull/2676)
Slack thread: https://coreos.slack.com/archives/CCRND57FW/p1661191173355129

Extending services's serving-cert secrets values

---

reconcile/openshift_saas_deploy_trigger_base.py

They are used for saas-faile-1

remove not accessed args

---

reconcile/openshift_resources.py
reconcile/openshift_resources_base.py
reconcile/openshift_routes.py
reconcile/prometheus_rules_tester.py
reconcile/utils/openshift_resource.py

Reverts app-sre/qontract-reconcile#2734
detected a bug during rollout. reverting for now

Revert "openshift-resource/route/prometheus-rule-tester resource resolution and early-exit performance"

---

reconcile/template_tester.py
tools/qontract_cli.py

adapt template tester and qontract-cli alert-to-receiver to cope with https://github.com/app-sre/qontract-schemas/pull/229

[template-tester][qontract-cli alert-to-receiver] adapt to resource resolution

---

reconcile/utils/terrascript_aws_client.py

store es creds in secrets manager for lambda.

[APPSRE-6069] add secretsmanager for es

---

reconcile/terraform_resources.py
reconcile/test/test_utils_aws_api.py
reconcile/test/test_utils_terrascript_aws_client.py
reconcile/utils/aws_api.py
reconcile/utils/terrascript_aws_client.py

design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/terraform-asg-ami-selection.md
needs: https://github.com/app-sre/qontract-schemas/pull/226
APPSRE-6126

terraform-resource: enhance aws asg ami image selection

---

reconcile/checkpoint.py
reconcile/test/test_version_bump.py
reconcile/utils/git_secrets.py
reconcile/utils/gql.py
reconcile/utils/jenkins_api.py
reconcile/utils/raw_github_api.py
reconcile/utils/terrascript_aws_client.py
tools/app_interface_reporter.py
tools/qontract_cli.py

add in https://github.com/PyCQA/pylint/releases/tag/v2.15.0

fix pylint missing-timeout

---

reconcile/gitlab_housekeeping.py

If there is a MR in front of the app-interface merge queue, which has a merge conflict and can't be rebased or merged, it will still count into the rebase attempts of gitlab-housekeeper and slows down or even blocks the entire MR queue.
this change skips such MRs and logs appropriately
Fixes https://issues.redhat.com/browse/APPSRE-6201

[gitlab-housekeeper] non-rebasable MRs blocking merge queue

---

tools/qontract_cli.py

[run-prometheus-test] Adapt to resource resolution

---

reconcile/utils/terrascript_aws_client.py

tags are missing for elastic search and surrounding resources

add tags for elasticsearch resources

---

reconcile/terraform_resources.py
reconcile/utils/terrascript_aws_client.py

Introducing kinesis-to-opensearch lambda
along with the new get_lambda_zip function(will replace get_logtoes_zip and get_rosa_authenticator_zip in a following PR)
depends on https://github.com/app-sre/qontract-schemas/pull/230

[APPSRE-6069] add kinesis-to-opensearch lambda

---

reconcile/queries.py
reconcile/utils/jira_client.py

jira-watcher: set read- and connect timeout on Jira Client

---

reconcile/utils/terrascript_aws_client.py

policy_attachment should depends on role

---

reconcile/utils/terrascript_aws_client.py

Depends on https://github.com/app-sre/qontract-schemas/pull/234

[APPSRE-6199] add warm config for elasticsearch

---

setup.py

contains retries added here: https://github.com/Unleash/unleash-client-python/commit/c47f071d01ee67161b984ace600660b3ccdc2809
that should fix https://issues.redhat.com/browse/APPSRE-6111

Bump UnleashClient

---

reconcile/terraform_users.py

this will prevent many repeating questions on MFA, thus reducing IC toil.

[terraform-users] add instructions to enable MFA in email invitation

---

reconcile/openshift_upgrade_watcher.py
reconcile/slack_cluster_usergroups.py
reconcile/slack_usergroups.py
reconcile/test/test_slack_usergroups.py
reconcile/test/test_utils_slack_api.py
reconcile/utils/slack_api.py

https://coreos.slack.com/archives/C03KQ9M1P6C/p1662138005941939
ref: https://slack.com/help/articles/212906697-Create-a-user-group

[slack] add support to create user groups

---

reconcile/cli.py

[early exit] disable gql url printing and reduce early-exit logs to debug

---

reconcile/queries.py
reconcile/utils/saasherder.py

Reverts app-sre/qontract-reconcile#2778
introduced a bug.

Revert "[openshift-saas-deploy-trigger-configs] consider target name for uniqueness"

---

reconcile/change_owners.py

force deepdiff to leverage context identifiers from app-interface bundles to speed up diff calculation and yield better results. deepdiff usually can heuristically decide when to use context identifiers. with `cutoff_intersection_for_pairs=1` we can force it to use them. this is a valid approach in our case since our data follows a schema and context identifiers are schema enforced, e.g. guaranteeing uniqueness within the context.
```
resourceTemplates:
- name: tmpl-1
url: url
path: path
targets:
- namespace: xxx
ref: ref
...
- namespace: yyy
ref: new-value   <----
....
- name: tmpl-2
url: url
path: path
targets:
- namespace: xxx
ref: ref
....
- namespace: yyy
ref: new-value   <----
......
```
calculating proper diffs in saas-file-2 file where the ref of two targets from different …

[change-owners] faster diffs and better results with context identifiers

---

reconcile/openshift_saas_deploy_trigger_base.py
reconcile/test/test_saasherder.py
reconcile/utils/saasherder.py

instead of using dicts, we can use classes.
this is a refactor only, and should not change any logic.

[openshift-saas-deploy-trigger] introduce trigger spec class

---

tools/qontract_cli.py

Added local secret config support and a way to filter results by path
that will avoid the need to render templates to inspect their names.
This will make calling Vault not needed for many templates, easying the
use for tenants and making it considerably faster for everyone.
The new option --path may seem redundant but it has benefits and we are
keeping backwards compatibility just in case.
Signed-off-by: Rafa Porres Molina rporresm@redhat.com

[qontract-cli] Make template usable by non app-sre

---

reconcile/test/fixtures/saasherder_populate_desired/saas_remote_openshift_template.yaml
reconcile/test/test_saasherder.py
reconcile/utils/saasherder.py

follows up on #2782
utilize trigger specs which are already created.

[openshift-saas-deploy-triggers] minor refactor

---

reconcile/change_owners.py

format old/new value as indented json for structured data

[change-owners] nicer textual change representations

---

reconcile/utils/saasherder.py

cleanup following #2786
this method was added in #2782

remove unused init method for trigger spec

---

reconcile/gql_definitions/change_owners/queries/change_types.py
reconcile/gql_definitions/change_owners/queries/self_service_roles.py
reconcile/gql_definitions/examples/queries/jenkins.py
reconcile/gql_definitions/examples/queries/ocm.py
reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/quay_membership/quay_membership.py
reconcile/gql_definitions/service_dependencies/service_dependencies.py
reconcile/gql_definitions/vpc_peerings_validator/vpc_peerings_validator.py
reconcile/quay_membership.py
reconcile/test/test_change_owners.py
reconcile/test/test_vpc_peerings_validator.py

regenerate (qenerate) all gql classes to adapt latest qontract-server changes
see https://github.com/app-sre/qontract-server/commit/bb640ea8951d8c1875943ff81ffd2651cdb0ec19

adapt to non-nullable lists

---

reconcile/gql_definitions/change_owners/queries/self_service_roles.py
reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/quay_membership/quay_membership.py
reconcile/quay_membership.py

needs https://github.com/app-sre/qontract-schemas/pull/243

APPSRE-6153 reduce optionals

---

helm/qontract-reconcile/templates/template.yaml
reconcile/integrations_manager.py
reconcile/queries.py
reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml
reconcile/test/test_integrations_manager.py
reconcile/test/test_utils_helm.py

Related ticket: https://issues.redhat.com/browse/APPSRE-6100
Related schema change: https://github.com/app-sre/qontract-schemas/pull/216

Enable overrides per shard

---

reconcile/gql_definitions/introspection.json

follows up on https://github.com/app-sre/qontract-schemas/pull/251, #2805

update gql introspection following owned_saas_files deprecation

---

reconcile/change_owners/README.md
reconcile/change_owners/change_owners.py
reconcile/cli.py
reconcile/utils/mr/labels.py

[change-owners] yes - enough typos for a dedicated PR

---

reconcile/prometheus_rules_tester.py
reconcile/test/test_prometheus_rules_tester.py
tools/qontract_cli.py

APPSRE-6316
Schemas: https://github.com/app-sre/qontract-schemas/pull/249/files

Introduce target_clusters to prometheus_rules_tester

---

reconcile/prometheus_rules_tester.py
reconcile/test/test_prometheus_rules_tester.py
tools/qontract_cli.py

Reverts app-sre/qontract-reconcile#2803

Revert "Introduce target_clusters to prometheus_rules_tester"

---

reconcile/prometheus_rules_tester.py
reconcile/test/test_prometheus_rules_tester.py
tools/qontract_cli.py

Introduce target_clusters into promtheus_rules_tester

---

dockerfiles/hack/run-integration.py
tox.ini

and add dockerfiles/hack to lint and format in tox.ini

lint and format run-integrations.py

---

reconcile/gitlab_members.py
reconcile/gitlab_permissions.py
reconcile/gitlab_projects.py
reconcile/jenkins_job_builder.py
reconcile/jenkins_webhooks.py
reconcile/jenkins_webhooks_cleaner.py

part of https://issues.redhat.com/browse/APPSRE-6349
the idea is to reduce calls to gitlab when they are not needed.

add early-exit for gitlab related integrations

---

reconcile/checkpoint.py

https://issues.redhat.com/browse/APPSRE-6353

url_makes_sense test: remove leading and trailing whitespaces from url

---

reconcile/integrations_manager.py
reconcile/test/test_integrations_manager.py

Integrations query will return integrations for unrelated environments. Added a method to filter integrations by environment name

Fix KeyError

---

reconcile/cli.py
reconcile/openshift_saas_deploy_trigger_container_images.py
reconcile/queries.py
reconcile/test/test_saasherder.py
reconcile/utils/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-5799
depends on https://github.com/app-sre/qontract-schemas/pull/259
with this new trigger integration, it doesn't matter where, how and when an image is built. once it is built - it will be deployed.

Create trigger for openshift-saas-deploy based on new registry content

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_resources.gql
reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_resources.py
reconcile/test/test_terraform_cloudflare_resources.py
reconcile/test/test_utils_terrascript_cloudflare_client.py
reconcile/utils/terrascript/cloudflare_resources.py

See the ticket below for links to schema changes and other documentation.
Related to: https://issues.redhat.com/browse/APPSRE-6289
Existing tests were expanded to cover the addition of the `certificates` definition. Additionally, some manual testing was performed:
1. Create a Cloudflare ACM certificate with the apex zone and apex zone wildcard (`my.zone.com and `*.my.zone.com`)
2. Create a Cloudflare ACM certificate with the apex zone and additional subdomain (`my.zone.com` and `sub.my.zone.com`)
3. Deleting certificates

Add support for cloudflare_certificate_pack

---

reconcile/openshift_resources_base.py

This PR adds a custom Jinja2 filter to parse JSON data into dictionaries.

Add Jinja2 custom filter to parse JSON strings into dictionaries

---

reconcile/openshift_saas_deploy_change_tester.py

fixes a bug that started a `openshift-saas-deploy` dry-run for every target of a saas file instead of a saas-file/env-name combination.
this resulted in really poor performance.

[openshift-saas-deploy-change-tester] fix too many openshift-saas-deploy calls

---

tools/qontract_cli.py

Example output: https://gitlab.cee.redhat.com/-/snippets/5874

cluster-upgrade-policies md output with sortable / filterable table

---

setup.py
tox.ini

format setup.py

---

reconcile/utils/oc.py

Reverts app-sre/qontract-reconcile#2871

Revert "Kcp compatible"

---

reconcile/utils/terraform_client.py
reconcile/utils/terrascript_aws_client.py

JIRA - [APPSRE-4543](https://issues.redhat.com/browse/APPSRE-4543)
This one is removing the inline user policies referenced in the ticket.

Remove inline user policies

---

reconcile/utils/terraform_client.py
reconcile/utils/terrascript_aws_client.py

Reverts app-sre/qontract-reconcile#2656

Revert "Remove inline user policies"

---

reconcile/change_owners/change_owners.py

this change makes the coverage report also available when the MR is not self-serviceable

[change-owners] always show MR coverage report

---

reconcile/cli.py
reconcile/terraform_cloudflare_resources.py

This adds the ability to run terraform-cloudflare-resources for a specific account

tf-cloudflare-resources: allow selecting a specific account

---

reconcile/gql_definitions/introspection.json

```
make gql-introspection gql-query-classes
```

qenerate update

---

reconcile/openshift_base.py

a bit information on the failure that is related with #2902

add log message to silent failure area

---

reconcile/openshift_resources_base.py
reconcile/utils/oc.py

Reverts app-sre/qontract-reconcile#2878

Revert "Kcp compatible oc client"

---

reconcile/test/test_utils_terrascript_aws_client.py
reconcile/utils/terrascript_aws_client.py

[APPSRE-5901] enable get ami id from gitlab repo and ci-int for provision asg

---

reconcile/terraform_resources.py

add jenkins intance name to asg query

---

reconcile/cna/assets/asset_factory.py
reconcile/cna/integration.py
reconcile/cna/state.py

Decouple asset creation from main logic by using factory methods.

APPSRE-6295 asset factory

---

reconcile/cna/integration.py
reconcile/gql_definitions/cna/queries/cna_provisioners.gql
reconcile/gql_definitions/cna/queries/cna_provisioners.py
reconcile/gql_definitions/introspection.json

Mark CNA provisioner as experimental
https://github.com/app-sre/qontract-schemas/pull/304

APPSRE-6295 mark CNA as experimental

---

reconcile/ocm_clusters.py

related to https://issues.redhat.com/browse/APPSRE-6532
fixes an underlying bug which was fleshed out in #2901 and reverted in #2914

fix bug with elb fqdn by using the console url

---

requirements/requirements-type.txt

preprocessor errors now print the file where the error happens: https://github.com/app-sre/qenerate/pull/59

bump qenerate

---

reconcile/openshift_rolebindings.py

fix desired state for openshift-rolebindings

---

reconcile/openshift_network_policies.py

add namespace delete to openshift-network-policies query

---

reconcile/ocm_upgrade_scheduler.py

ClusterService refuses scheduling upgrades less than 5m in advance
https://coreos.slack.com/archives/GGC2A0MS8/p1668065861942799

ensure we don't request a cluster upgrade less than 5m in advance

---

reconcile/terraform_resources.py
reconcile/utils/terrascript_aws_client.py

Replace https://github.com/app-sre/qontract-reconcile/pull/2949
Depends on https://github.com/app-sre/qontract-schemas/pull/309

enhance config for asg

---

reconcile/change_owners/change_owners.py

change-owners fix labels not applied because of dry-run

---

reconcile/change_owners/change_types.py
reconcile/gql_definitions/change_owners/queries/change_types.gql
reconcile/gql_definitions/change_owners/queries/change_types.py
reconcile/test/fixtures/change_owners/changetype_cluster_owner.yml
reconcile/test/fixtures/change_owners/changetype_role_member.yaml
reconcile/test/fixtures/change_owners/changetype_saas_file.yaml
reconcile/test/fixtures/change_owners/changetype_secret_promoter.yaml
reconcile/test/test_change_owners_inheritance.py
tools/qontract_cli.py

[app-interface-output] create list for change-types and usage statistics

---

reconcile/cna/assets/asset.py
reconcile/cna/assets/aws_assume_role.py
reconcile/cna/assets/aws_rds.py
reconcile/cna/assets/null.py
reconcile/cna/client.py
reconcile/cna/integration.py
reconcile/cna/state.py
reconcile/gql_definitions/cna/queries/cna_resources.gql
reconcile/gql_definitions/cna/queries/cna_resources.py
reconcile/gql_definitions/introspection.json
reconcile/test/cna/test_asset.py
reconcile/test/cna/test_aws_assume_role.py
reconcile/test/cna/test_integration.py
reconcile/test/cna/test_state_assembly.py
reconcile/test/cna/test_state_diff.py
reconcile/test/cna/test_state_overrides.py

Introduce the concept of `Bindings`:
- Every `Asset` has a set of `Bindings`.
- By default, every `bindable()` asset in desired state is bound to its cluster-namespace in app-interface.
- `Bindings` only happen if an asset is in `READY` state.
Further:
- Delete `TERMINATED` assets

CNA bindings

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.test

Updates the base image to include a new Cloudflare provider version added in https://github.com/app-sre/container-images/pull/60

Update qontract-reconcile base image

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.gql
reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.py
reconcile/terraform_cloudflare_resources.py
reconcile/test/test_utils_terrascript_cloudflare_client.py
reconcile/utils/terrascript/cloudflare_client.py
reconcile/utils/terrascript/cloudflare_resources.py

[APPSRE-6571](https://issues.redhat.com/browse/APPSRE-6571)
This allows setting 2FA enforcement on Cloudflare accounts via the account definition file
Depends on https://github.com/app-sre/qontract-schemas/pull/318

tf-cloudflare: add cloudflare account 2fa enforcement

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.gql
reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_accounts.py
reconcile/terraform_cloudflare_resources.py
reconcile/test/test_utils_terrascript_cloudflare_client.py
reconcile/utils/terrascript/cloudflare_client.py
reconcile/utils/terrascript/cloudflare_resources.py

Reverts app-sre/qontract-reconcile#2964
Due to an oversight, I missed a few things in the PR that are needed and which will be addressed in a new PR

Revert "tf-cloudflare: add cloudflare account 2fa enforcement"

---

reconcile/cna/integration.py

move CNA binding fetching into the asset fetching loop
this way the we can use the same `client` to fetch the `bindings` we used to fetch the actual assets.

move CNA binding fetching into the asset fetching loop

---

reconcile/github_org.py
reconcile/gql_definitions/common/clusters_minimal.py
reconcile/gql_definitions/introspection.json
reconcile/ocm_github_idp.py
reconcile/openshift_base.py
reconcile/openshift_clusterrolebindings.py
reconcile/openshift_groups.py
reconcile/openshift_rolebindings.py
reconcile/slack_cluster_usergroups.py
reconcile/test/test_openshift_base.py
tools/qontract_cli.py

This reverts commit f4f07fed228b2877cf885fa64f0e2a5e0cce162a.

Revert "cluster.auth becomes a list of objects instead of a single object (#2963)"

---

reconcile/cna/assets/asset.py
reconcile/cna/integration.py

Set implicit `secret_name` for a binding.

CNA secret_name

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager-fedramp.yaml
reconcile/test/fixtures/helm/enable_google_chat.yml

Reverts app-sre/qontract-reconcile#2975
Discussed with stream 3 team and decided this was a regression in terms of visibility. Also seems to be causing issues with fluentd now.

Revert "Condense GChat logs to single 'thread'"

---

reconcile/dashdotdb_dvo.py
reconcile/terraform_cloudflare_resources.py
reconcile/utils/exceptions.py
reconcile/utils/secret_reader.py
setup.cfg

add missing type hints and fix `read` return type

secret-reader: type hints

---

reconcile/glitchtip/integration.py
reconcile/utils/glitchtip/models.py
setup.cfg

glitchtip: add missing type hints

---

reconcile/dashdotdb_slo.py
setup.cfg

Add missing types to fully enforce types annotations for dashdotdb_slo.

enforce types for dashdot_slo

---

reconcile/cli.py
reconcile/ocm_update_recommended_version.py
reconcile/queries.py
reconcile/test/test_ocm_update_recommended_version.py
reconcile/utils/mr/ocm_update_recommended_version.py

Add an integration that updates the recommended version based on configurable weight.
Related story: [APPSRE-6543](https://issues.redhat.com/browse/APPSRE-6543)

Add ocm update recommended version integration

---

reconcile/prometheus_rules_tester.py
setup.cfg

Add type hints to prometheus-rules-tester

---

reconcile/quay_mirror.py
reconcile/quay_mirror_org.py

Clarify Skopeo error messages

---

reconcile/openshift_saas_deploy.py

if a gitlab instance does not exist we get exceptions.

[openshift-saas-deploy] really allow execution without gitlab

---

reconcile/cli.py
reconcile/ocm_update_recommended_version.py
reconcile/utils/mr/__init__.py
reconcile/utils/mr/ocm_update_recommended_version.py

Related issues: [APPSRE-6543](https://issues.redhat.com/browse/APPSRE-6543)

Use SQSGateway for update recommended version

---

reconcile/dashdotdb_dvo.py
setup.cfg

Tested this by running integration locally in dry-run mode.

Enforce types for dashdotdb-dvo

---

reconcile/openshift_base.py
reconcile/openshift_limitranges.py
reconcile/openshift_namespace_labels.py
reconcile/openshift_namespaces.py
reconcile/openshift_network_policies.py
reconcile/openshift_resourcequotas.py
reconcile/openshift_resources_base.py
reconcile/openshift_rolebindings.py
reconcile/openshift_serviceaccount_tokens.py
reconcile/test/test_openshift_base.py

instead of duplicating `namespace_info.get("delete")`

[openshift-base] is namespace deleted

---

reconcile/glitchtip/integration.py

fix glitchtip early exit

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.test

Promote the changes from https://github.com/app-sre/container-images/pull/61
Ref.:[APPSRE-6583](https://issues.redhat.com/browse/APPSRE-6583)

update qr base and builder images to use latest version

---

reconcile/openshift_users.py
reconcile/queries.py

`openshift-users` must consider all user identities based on cluster auth configuration, not just GitHub ones.
APPSRE-6646

[openshift-users] OIDC support

---

reconcile/test/test_amtool.py
reconcile/utils/amtool.py
setup.cfg

Or tests silently fail not giving information about the issue.

Add test about amtool minimal version

---

reconcile/dashdotdb_base.py
reconcile/slack_base.py
reconcile/utils/pagerduty_api.py
reconcile/utils/secret_reader.py
reconcile/utils/slack_api.py
reconcile/utils/smtp_client.py

https://service.pages.redhat.com/dev-guidelines/docs/appsre/python-style-guide/#naming-conventions
`s/Supports/Has/g`
[APPSRE-6645](https://issues.redhat.com/browse/APPSRE-6645)

rename some Protocol classes to be compliant with the latest dev guidelines

---

reconcile/change_owners/tester.py

fixes a bug introduced in https://github.com/app-sre/qontract-reconcile/pull/3058

[change-type] fix a bug in the change-type-tester

---

reconcile/terraform_cloudflare_resources.py

Adding code for early exit as well as small refactor to ensure we utilize same data.

[APPSRE-6697] Add early exit to cloudflare integration

---

reconcile/ocm_github_idp.py
reconcile/utils/ocm.py

Depends on: #3029 
Ticket: [APPSRE-6627](https://issues.redhat.com/browse/APPSRE-6627)

[ocm-github-idp] support removal of GitHub IDPs

---

reconcile/ocm_github_idp.py
reconcile/utils/ocm.py

This reverts commit 14d0c122eed71d0709b99b44fb719a603866f06e.

Revert "[ocm-github-idp] support removal of GitHub IDPs (#3048)"

---

reconcile/openshift_rolebindings.py
reconcile/queries.py

related to https://issues.redhat.com/browse/APPSRE-6737
to be able to manage RoleBinding objects in protected namespaces as cluster admin

[openshift-rolebindings] support cluster admin

---

reconcile/slack_usergroups.py
reconcile/test/test_slack_usergroups.py

[slack-usergroups] do not fail for non-existing usergroups

---

dockerfiles/Dockerfile.test

APPSRE-6370: Update test image builder container release tag

---

reconcile/github_org.py
reconcile/openshift_base.py
reconcile/openshift_groups.py
reconcile/openshift_rolebindings.py
reconcile/openshift_users.py
reconcile/test/test_openshift_base.py

Don't try to add non-GitHub usernames if another OIDC authentication provider is configured
APPSRE-6772

[github] don't examine non github usernames

---

reconcile/sql_query.py

[sql-query] early exit

---

setup.py

https://github.com/app-sre/sretoolbox/pull/86

Upgrade sretoolbox to 2.2.0

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/vault_instances/vault_instances.gql
reconcile/gql_definitions/vault_instances/vault_instances.py
reconcile/test/fixtures/vault_replication/jenkins_configs/jenkins_config_insta_path.yaml
reconcile/test/fixtures/vault_replication/vault_policies/vault_policies_query_data.yaml
reconcile/test/test_vault_replication.py
reconcile/utils/vault.py
reconcile/vault_replication.py

Create a new provider for VaultReplication to support replication from a Policy.
Schemas: [Schemas PR](https://github.com/app-sre/qontract-schemas/pull/366)
APPSRE-6778

VaultReplication add policy provider

---

reconcile/change_owners/change_types.py
reconcile/test/change_owners/test_change_type_diff_splitting.py

when a diff is split into smaller chunks that can be covered by a single change-type, a bug ignored all potential approver groups but one.
this change fixes that bug by adding all potential approver groups to such splits. tests have been added to cover that feature on multiple levels.
https://issues.redhat.com/browse/APPSRE-6784

[change-owners] fix missing approvers groups when splitting diffs

---

reconcile/utils/terrascript_aws_client.py

Support aws gov partition when assigning enhanced monitoring policy 

---

reconcile/cli.py
reconcile/ocm_addons_upgrade_scheduler_org.py
reconcile/ocm_upgrade_scheduler.py
reconcile/queries.py
reconcile/test/test_ocm_addons_upgrade_scheduler_org.py
reconcile/test/test_ocm_upgrade_scheduler.py
reconcile/utils/ocm.py
setup.cfg
tools/qontract_cli.py

https://issues.redhat.com/browse/APPSRE-6790
proposal to manage addon upgrade based on our existing upgrade policies. This is targeting hypershift only, as a short term solution
Depends on https://github.com/app-sre/qontract-schemas/pull/368

ocm-addons-upgrade-scheduler-org integration

---

reconcile/jenkins_webhooks_cleaner.py

Add error catching similar to jenkins-webhooks

Add try catch

---

tools/qontract_cli.py

[APPSRE-6821](https://issues.redhat.com/browse/APPSRE-6821)

qontract-cli upgrade-cluster-addon

---

reconcile/terraform_resources.py

based on the prework for sharded-dry-runs (https://github.com/app-sre/qontract-reconcile/pull/3134) this PR implements the `desired_state_shard_config` function for the `terraform-resources` integrations. this way `terraform-resources` opts into the sharded integration dry-run mechanism that processes only the data of affected shards during PR checks.
the resources in desired state returned by `early_exit_desired_state` have been enriched  with `IDENTIFIER_FIELD_NAME` fields to establish stable identifies for objects in lists, for the purpose of faster difference finding (see https://github.com/app-sre/qontract-reconcile/blob/675ce249559d7f7188191258f037ff3f7f116fa2/reconcile/change_owners/diff.py#L115)
https://issues.redhat.com/browse/APPSRE-6785
Signed-off-by: Gerd Oberlechner …

[terraform-resources] implement sharded dry-runs

---

reconcile/cli.py

Redact credentials from skopeo commands to Sentry

---

reconcile/jenkins_job_builder.py
reconcile/ocm/types.py
reconcile/test/test_saasherder.py
reconcile/test/test_utils_quay_api.py
requirements/requirements-type.txt
setup.py
tools/qontract_cli.py

- use latest mypy and bump pydantic
- fix mypy errors and notes
APPSRE 6977

mypy upgrade

---

helm/qontract-reconcile/templates/template.yaml
reconcile/integrations_manager.py
reconcile/test/test_integrations_manager.py

Reverts app-sre/qontract-reconcile#3179

Revert "[integration-manager] sharding labels for integration workload (2nd try)"

---

reconcile/jenkins_worker_fleets.py
reconcile/test/fixtures/jenkins_worker_fleets/gql-queries.yml
reconcile/test/fixtures/jenkins_worker_fleets/jcasc-apply.yml
reconcile/test/fixtures/jenkins_worker_fleets/jcasc-export.yml
reconcile/test/test_jenkins_worker_fleets.py
reconcile/utils/jenkins_api.py

follow up of https://github.com/app-sre/qontract-reconcile/pull/3131
fix plugin issue https://github.com/jenkinsci/ec2-fleet-plugin/issues/323, typo, and clean test data.

fix jcasc issue

---

reconcile/utils/terrascript_aws_client.py

Need to skip by account name and not account

Fix skip account

---

reconcile/utils/terrascript_aws_client.py

This reverts commit b0628b63cda5a3e291a7677528b87b98b12914e5.
How does git work.

Revert accidental commit

---

reconcile/gql_definitions/common/clusters_minimal.gql
reconcile/gql_definitions/common/clusters_minimal.py
reconcile/openshift_users.py
reconcile/typed_queries/clusters_minimal.py
setup.cfg

- Introduce typed `OCMap` to `openshift-users` integration
- Add types to `openshift-users` integration

APPSRE-6609 OCMap for openshift-users

---

reconcile/cluster_deployment_mapper.py
reconcile/cna/integration.py
reconcile/dashdotdb_cso.py
reconcile/dashdotdb_dvo.py
reconcile/dashdotdb_slo.py
reconcile/openshift_users.py
reconcile/typed_queries/app_interface_vault_settings.py

Convenience function to exit with an error if vault settings cannot be found.

APPSRE-6609 convenience function for vaultsettings

---

reconcile/resource_scraper.py
setup.cfg

- new `OCMap` for `resource-scraper`
- fully typing for `resource-scraper`

APPSRE-6609 OCMap for resource-scraper

---

reconcile/terraform_resources.py
reconcile/utils/terrascript_aws_client.py

part of https://issues.redhat.com/browse/APPSRE-7044
required for backplane poc

allow enable/disable http2 for alb

---

reconcile/openshift_groups.py

Bug introduced here https://github.com/app-sre/qontract-reconcile/pull/3216
Apparently `ocm-groups` also uses one of these functions -,-
This makes it backwards compatible again.

APPSRE-6609 fix ocm-groups

---

reconcile/openshift_upgrade_watcher.py
reconcile/test/fixtures/openshift_upgrade_watcher/cluster1.yml
reconcile/test/test_openshift_upgrade_watcher.py
setup.cfg

- `OCMap` for `openshift-upgrade-watcher`
- enforce types for `openshift-upgrade-watcher`

APPSRE-6609 OCMap for openshift-upgrade-watcher

---

reconcile/utils/terrascript_aws_client.py

[APPSRE-7130] [FedRAMP] Fix bug with list reference

---

tools/qontract_cli.py

display cross-org version data inheritance in fleet upgrade policy outputs

---

reconcile/utils/terrascript_aws_client.py

Depends on:
- https://github.com/app-sre/qontract-reconcile/pull/3251
Related: [APPSRE-6370](https://issues.redhat.com/browse/APPSRE-6370)
Signed-off-by: Krzysztof Wilczyński [kwilczynski@redhat.com](mailto:kwilczynski@redhat.com)

Update versions of Terraform Time and Random providers in Terrascript

---

reconcile/openshift_namespace_labels.py
reconcile/test/fixtures/openshift_namespace_labels/namespace.yml
reconcile/test/test_openshift_namespace_labels.py
reconcile/typed_queries/namespaces.py

This is exactly the same as https://github.com/app-sre/qontract-reconcile/pull/3245
This reverts the revert https://github.com/app-sre/qontract-reconcile/pull/3246
The bug is fixed in this PR https://github.com/app-sre/qontract-reconcile/pull/3249
Will merge this on Monday when Im IC :)

Revert "Revert "APPSRE-6609 namespace labels - 2nd try (#3245)" (#3246)"

---

requirements/requirements-type.txt

https://github.com/python/mypy/issues/14850

mypy 1.1.1 behaves weird with pydantic

---

reconcile/change_owners/change_types.py
reconcile/test/change_owners/test_change_type_diff_splitting.py
reconcile/test/test_utils_jsonpath.py
reconcile/utils/jsonpath.py

Certain MRs are not self-serviceable when there are uncovered empty parent elements left after change-type coverage. e.g. all elements of an objects are covered but the object itself not. This prevents self-service even though all relevant changes have been covered.
This bug was fixed once for situations where the empty parent was a top level element of the changed datafile (https://github.com/app-sre/qontract-reconcile/pull/3058). This bugfix handles also situations where the parent element is nested somewhere in the datafile.
```yaml
externalResources:
- provider: aws
...
resources:
- provider: rds
...
overrides:   <-- this element was introduced but is not covered by a change-type
engine_version: "12.13" <-- this is covered by a change-type
apply_immediately: true  <-- this as well
``` …

[change-owners] fix uncovered empty parents

---

reconcile/openshift_saas_deploy_change_tester.py
setup.cfg

Add type hints to `openshift_saas_deploy_change_tester`
Ticket: [APPSRE-7262](https://issues.redhat.com/browse/APPSRE-7262)

[openshift_saas_deploy_change_tester] type hints

---

reconcile/openshift_saas_deploy_trigger_base.py
reconcile/openshift_saas_deploy_trigger_cleaner.py
reconcile/openshift_saas_deploy_trigger_configs.py
reconcile/openshift_saas_deploy_trigger_images.py
reconcile/openshift_saas_deploy_trigger_moving_commits.py
reconcile/openshift_saas_deploy_trigger_upstream_jobs.py
setup.cfg

Add type hints to
- openshift_saas_deploy_trigger_base
- openshift_saas_deploy_trigger_cleaner
- openshift_saas_deploy_trigger_configs
- openshift_saas_deploy_trigger_images
- openshift_saas_deploy_trigger_moving_commits
- openshift_saas_deploy_trigger_upstream_jobs
Ticket: [APPSRE-7262](https://issues.redhat.com/browse/APPSRE-7262)

[openshift_saas_deploy_trigger_*] type hints

---

reconcile/cli.py
reconcile/openshift_saas_deploy.py
reconcile/openshift_saas_deploy_wrapper.py
setup.cfg

Add type hints to 
* openshift_saas_deploy
* openshift_saas_deploy_wrapper
Ticket: [APPSRE-7262](https://issues.redhat.com/browse/APPSRE-7262)

[openshift_saas_deploy] type hints

---

reconcile/jenkins/types.py
reconcile/queries.py
reconcile/test/fixtures/jenkins_worker_fleets/gql-queries.yml
reconcile/test/fixtures/jenkins_worker_fleets/jcasc-apply.yml
reconcile/test/fixtures/jenkins_worker_fleets/jcasc-export.yml

depends on https://github.com/app-sre/qontract-schemas/pull/405
https://issues.redhat.com/browse/APPSRE-7237

[APPSRE-7237] enable config for maxTotalUses and alwaysReconnect

---

reconcile/utils/vault.py

Resolve error not caught by local test / pr check
follow up to https://github.com/app-sre/qontract-reconcile/pull/3291

Ensure vault kube attribute is initialized

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager-fedramp.yaml
openshift/qontract-manager.yaml
reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml
reconcile/test/fixtures/helm/aws_account_shards.yml
reconcile/test/fixtures/helm/basic.yml
reconcile/test/fixtures/helm/cache.yml
reconcile/test/fixtures/helm/command.yml
reconcile/test/fixtures/helm/concurrency_policy.yml
reconcile/test/fixtures/helm/cron.yml
reconcile/test/fixtures/helm/dashdotdb.yml
reconcile/test/fixtures/helm/disable_unleash.yml
reconcile/test/fixtures/helm/enable_google_chat.yml
reconcile/test/fixtures/helm/environment_aware.yml
reconcile/test/fixtures/helm/exclude_service.yml
reconcile/test/fixtures/helm/extra_args.yml
reconcile/test/fixtures/helm/extra_env.yml
reconcile/test/fixtures/helm/failure_history.yml
reconcile/test/fixtures/helm/integrations_manager.yml
reconcile/test/fixtures/helm/internal_certificates.yml
reconcile/test/fixtures/helm/logs_slack.yml
reconcile/test/fixtures/helm/restart_policy.yml
reconcile/test/fixtures/helm/shards.yml
reconcile/test/fixtures/helm/sleep_duration.yml
reconcile/test/fixtures/helm/state.yml
reconcile/test/fixtures/helm/storage.yml
reconcile/test/fixtures/helm/success_history.yml
reconcile/test/fixtures/helm/trigger.yml

APPSRE-7074
Fix issue where integration manager rendered templates with additional `/token` appended
Note: this token is not currently utilized within production

Fix kube sa volume projection

---

tools/qontract_cli.py

with this qontract-cli command (which can be added to [app-interface-output](https://gitlab.cee.redhat.com/service/app-interface-output)), we can get a mapping of resources that are managed on a customer cluster via an ACM Policy, indirectly via a Hive SelectorSyncSet.
this command will provide output that will be helpful in answering the questions:
- is this resource created by a Policy?
- what is the name of that SelectorSyncSet?
- what is the name of that Policy?
- what SaaS file is deploying it?
since SaaS file names are unique, this information will lead to the OpenShift template that contains the SelectorSyncSet.
this is simialr to #3295

[qontract-cli] introduce selectorsyncset-managed-hypershift-resources

---

reconcile/utils/oc_map.py

Fetching secrets with given threadpool size

obey to threadpool size

---

reconcile/utils/vault.py

This change solves 2 issues continue from https://github.com/app-sre/qontract-reconcile/pull/3304:
1. `_auto_refresh_client_auth` will bring back closed connections due to it's running in another thread
2. `VaultClient` singleton is not thread safe, old client is not closed before new one assigned
APPSRE-7274

Implement thread safe close for vault client

---

reconcile/ldap_users.py
reconcile/queries.py
reconcile/utils/mr/user_maintenance.py

This reverts commit a8123d1f740806cd85b4a0f462d4119ac2490b80.

Revert "add ability to remove resetPassword entries for users not in LDAP. (#3309)"

---

reconcile/queries.py

fixes #3319
no idea how that happened.

readd dns record missing piece

---

reconcile/ldap_users.py
reconcile/queries.py
reconcile/utils/mr/user_maintenance.py

* add ability to remove resetPassword entries for users not in LDAP.  Part of APPSRE-6367
* adding upstream changes
* fix type hint in init_users()

add ability to remove resetPassword entries for users not in LDAP. 

---

reconcile/integrations_manager.py
reconcile/queries.py
reconcile/test/test_integrations_manager.py

Relates to https://github.com/app-sre/qontract-schemas/pull/415

Fix awsAccount -> awsAccounts as it is a list

---

tools/qontract_cli.py

follow up of https://github.com/app-sre/qontract-reconcile/pull/3340

fix q-c aws_terraform_resources

---

reconcile/test/oc/test_oc_map.py
reconcile/utils/oc_map.py

Adding some more unit tests for `OCMap`.

APPSRE-6609 some more tests for OCMap

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.publish-release
dockerfiles/Dockerfile.test

... to include the changes from https://github.com/app-sre/container-images/pull/74
Ref.: https://issues.redhat.com/browse/APPSRE-7363

Bump qontract-reconcile base image

---

helm/qontract-reconcile/templates/template.yaml
reconcile/test/fixtures/helm/internal_certificates.yml

Add missing resource config for `internal-certificates`

Add resources config to internal-certificates

---

reconcile/openshift_saas_deploy_trigger_base.py

`OCMap` for `saas-deploy-trigger-base`
**Local Tests Executed against Prod data**
```
qd profile run prod openshift-saas-deploy-trigger-moving-commits
qd profile run prod openshift-saas-deploy-trigger-images
qd profile run prod openshift-saas-deploy-trigger-configs
```

APPSRE-6609 OCMap for saas-trigger-base

---

reconcile/queries.py
reconcile/test/test_queries.py

Remove unused queries

---

reconcile/templates/email.yml.j2
reconcile/test/test_utils_mr.py
reconcile/utils/mr/app_interface_reporter.py
reconcile/utils/mr/aws_access.py
reconcile/utils/mr/base.py
reconcile/utils/mr/notificator.py
setup.cfg

* Fully typed
* Replace dict parameter by a typed class
* Refactor and enhance `app-interface-email` rendering + tests

[utils.mr.notificator] Enhance CreateAppInterfaceNotificator

---

reconcile/test/fixtures/oc_native/api.yml
reconcile/test/test_utils_oc_native.py
reconcile/utils/oc.py

Reverts app-sre/qontract-reconcile#3351

Revert "[OCNative] remove get_api_resources"

---

reconcile/gitlab_fork_compliance.py
reconcile/gitlab_housekeeping.py
reconcile/gitlab_integrations.py
reconcile/gitlab_labeler.py
reconcile/gitlab_members.py
reconcile/gitlab_mr_sqs_consumer.py
reconcile/gitlab_owners.py
reconcile/gitlab_permissions.py
reconcile/gitlab_projects.py
reconcile/jenkins_webhooks.py
reconcile/jenkins_webhooks_cleaner.py
reconcile/openshift_saas_deploy_change_tester.py
reconcile/saas_file_owners.py
reconcile/slack_usergroups.py
reconcile/sql_query.py
reconcile/terraform_vpc_peerings.py
reconcile/test/test_slack_usergroups.py
reconcile/test/test_terraform_vpc_peerings.py
reconcile/utils/github_api.py
reconcile/utils/gitlab_api.py
reconcile/utils/oc.py
reconcile/utils/saasherder/saasherder.py
reconcile/utils/terrascript_aws_client.py

Session is not closed when some clients are not used anymore, this change adds context manager for `oc` and `gitlab` clients to do cleanup to release resources.

Cleanup request session when client is not used

---

reconcile/aus/ocm_upgrade_scheduler.py
tools/qontract_cli.py

fixes a bug introduced in https://github.com/app-sre/qontract-reconcile/pull/3377

fix ocm-addons-upgrade-policies report

---

reconcile/utils/terrascript_aws_client.py

This MR fixes some of the typos that were in the original MR.

Fixing typo in the insights Cognito tokens

---

tools/qontract_cli.py

qontract-cli get ocm-login environment url fix

---

reconcile/saas_auto_promotions_manager/integration.py
reconcile/saas_auto_promotions_manager/utils/vcs.py
reconcile/utils/unleash.py

Adding unleash feature toggle to enable/disable MR deletion and creation. This will be used to test MR housekeeping of SAPM in the real field.
Further, this introduces a way to allow `False` as a default for feature toggles

APPSRE-7367 add feature toggles

---

reconcile/gql_definitions/common/saas_files.py
reconcile/gql_definitions/common/saas_target_namespaces.py
reconcile/gql_definitions/fragments/saas_target_namespace.gql
reconcile/gql_definitions/fragments/saas_target_namespace.py
reconcile/test/fixtures/typed_queries/saas_files_namespaces.yml
reconcile/test/test_typed_queries/test_saas_files.py
reconcile/typed_queries/saas_files.py

* add several attributes that can be used in jsonPathSelectors
* support filtering on existing attributes by removing "None" values from GQL response
* support intuitive filtering (`namespace[?@.environment.labels.type="stage"]`) on Json attributes

[saas-file] enhance dynamic namespaceSelector

---

reconcile/openshift_saas_deploy.py

This unleash flag allows us to turn on/off SQS events for auto-promotions. This flag will be used to smoothly shift towards SAPM and roll-back if necessary.

APPSRE-7367 unleash flag for auto-promoter

---

reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/multiple_namespaces.result.yml
reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/multiple_namespaces.yml

I stumbled across some more interesting saas files. The renderer handles them properly, but we should also cover this in the test files.

APPSRE-7367 more renderer test cases

---

reconcile/utils/promotion_state.py
reconcile/utils/saasherder/saasherder.py

`openshift-saas-deploy` is hard to test -> better to have some more logging here on whats happening with the promotion data.

APPSRE-7414 more logging for promotion upload

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/utils/terrascript_aws_client.py

Also adds support for the fixed-response action type
See the [schema changes PR](https://github.com/app-sre/qontract-schemas/pull/429) for an example of the new schema/data format 
Ref.: https://issues.redhat.com/browse/APPSRE-7483

Refactor AWS ALB action to support multiple action types

---

reconcile/dashdotdb_dvo.py
reconcile/dashdotdb_slo.py
reconcile/jenkins_job_builder.py
reconcile/jenkins_job_builds_cleaner.py
reconcile/jenkins_job_cleaner.py
reconcile/jenkins_plugins.py
reconcile/jenkins_roles.py
reconcile/ocm_addons_upgrade_tests_trigger.py

our certificate management is quite good at this point in time. all our CI instances have valid certificates, and so do prometheus instances of private clusters.
let's validate certificates.

ssl_verify to True everywhere

---

reconcile/test/test_utils_terraform_client.py
reconcile/utils/aws_api.py
reconcile/utils/terraform_client.py

https://issues.redhat.com/browse/APPSRE-6898

[APPSRE-6898] validate_db_upgrade

---

reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py
reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_namespace_ignore_hash.result.yml
reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_namespace_ignore_hash.yml
reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/test_content_single_namespace.py

We do not want to add
```
promotion_data: []
```
when promotion_data is empty.

APPSRE-7517 do not add empty promotion_data

---

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request.py
reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager.py
reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py
reconcile/saas_auto_promotions_manager/publisher.py
reconcile/saas_auto_promotions_manager/subscriber.py

Some explanations around SAPM.

sapm docstrings

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager-fedramp.yaml
openshift/qontract-manager.yaml
reconcile/test/fixtures/helm/aws_account_shard_disabled.yml
reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml
reconcile/test/fixtures/helm/aws_account_shards.yml
reconcile/test/fixtures/helm/basic.yml
reconcile/test/fixtures/helm/cache.yml
reconcile/test/fixtures/helm/command.yml
reconcile/test/fixtures/helm/concurrency_policy.yml
reconcile/test/fixtures/helm/cron.yml
reconcile/test/fixtures/helm/dashdotdb.yml
reconcile/test/fixtures/helm/disable_unleash.yml
reconcile/test/fixtures/helm/enable_google_chat.yml
reconcile/test/fixtures/helm/environment_aware.yml
reconcile/test/fixtures/helm/exclude_service.yml
reconcile/test/fixtures/helm/extra_args.yml
reconcile/test/fixtures/helm/extra_env.yml
reconcile/test/fixtures/helm/failure_history.yml
reconcile/test/fixtures/helm/integrations_manager.yml
reconcile/test/fixtures/helm/internal_certificates.yml
reconcile/test/fixtures/helm/logs_slack.yml
reconcile/test/fixtures/helm/restart_policy.yml
reconcile/test/fixtures/helm/shards.yml
reconcile/test/fixtures/helm/sleep_duration.yml
reconcile/test/fixtures/helm/state.yml
reconcile/test/fixtures/helm/storage.yml
reconcile/test/fixtures/helm/success_history.yml
reconcile/test/fixtures/helm/trigger.yml

Add an environment variable that allows specifing ref for image tags.
[APPSRE-7159](https://issues.redhat.com/browse/APPSRE-7159)

Add environment variable to specify image tag

---

reconcile/utils/terraform_client.py
reconcile/utils/terrascript_aws_client.py

Reverts app-sre/qontract-reconcile#3408

Revert "Remove redundant inline user policies"

---

reconcile/aws_iam_password_reset.py

Remove saas files from roles query
Initialize AWS client only if it is required
https://issues.redhat.com/browse/APPSRE-7583

Improve runtime of aws-iam-password-reset

---

reconcile/aus/base.py
reconcile/aus/ocm_upgrade_scheduler.py
reconcile/openshift_upgrade_watcher.py
reconcile/test/test_ocm_upgrade_scheduler.py
reconcile/utils/ocm/ocm.py

Reverts app-sre/qontract-reconcile#3494

Revert "Add Control Plane upgrade"

---

reconcile/utils/saasherder/saasherder.py

Monitor changes to `rt.secretsParameters` and `saas_file.secretsParameters` as well.

[openshift-saas-deploy-trigger-configs] trigger for rt and saas_file secretsParameters changes

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.publish-release
dockerfiles/Dockerfile.test

Related to: https://github.com/app-sre/container-images/pull/80

Update base, builder and test container images tag reference

---

reconcile/saas_auto_promotions_manager/publisher.py
reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py
reconcile/test/saas_auto_promotions_manager/conftest.py
reconcile/test/saas_auto_promotions_manager/subscriber/conftest.py
reconcile/test/saas_auto_promotions_manager/test_integration_test.py
reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_multiple_publishers_for_single_channel.py
reconcile/test/test_auto_promoter.py
reconcile/test/test_saasherder.py
reconcile/test/test_typed_queries/test_saas_files.py
reconcile/test/utils/test_promotion_state.py
reconcile/typed_queries/saas_files.py
reconcile/utils/promotion_state.py
reconcile/utils/saasherder/interfaces.py
reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py

Reverts app-sre/qontract-reconcile#3473
It triggers a redeployment of all saas-files

Revert "[openshift saas deploy] multiple publishers"

---

reconcile/test/test_typed_queries/test_clusters.py
reconcile/test/test_typed_queries/test_clusters_minimal.py
reconcile/typed_queries/clusters.py
reconcile/typed_queries/clusters_minimal.py

Adding missing tests to some commonly used `get_cluster*` typed queries.

more tests for typed queries

---

reconcile/aus/advanced_upgrade_service.py

removed magic code that processed data from org labels and instead pass it in manually like in good old times so that mypy can tell me that i made a mistake

[aus] fix sector processing from labels

---

grafana-dashboards/sre-capability-aus-ops.configmap.yaml
grafana-dashboards/sre-capability-aus.configmap.yaml

user and ops dashboard for AUS

[AUS] dashboards

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/utils/terrascript_aws_client.py

Add protocol and protocol_version to ALB provider (PROJQUAY-5569)

---

reconcile/aus/base.py
reconcile/aus/ocm_upgrade_scheduler.py
reconcile/openshift_upgrade_watcher.py
reconcile/test/test_ocm_addons_upgrade_scheduler_org.py
reconcile/test/test_ocm_upgrade_scheduler.py
reconcile/utils/ocm/ocm.py

Redoing https://github.com/app-sre/qontract-reconcile/pull/3494 with bugfixes:
- [3237d81](https://github.com/app-sre/qontract-reconcile/pull/3500/commits/3237d816211f08cca27417d30f12415d4400e089)
- [4caf462](https://github.com/app-sre/qontract-reconcile/pull/3500/commits/4caf46291948583f0b78a1071829eb96ee24f901)
https://issues.redhat.com/browse/APPSRE-7243

Add control plane upgrades

---

grafana-dashboards/sre-capability-aus.configmap.yaml

this PR fixes the duplicate metrics errors on the cluster upgrades overview dashboard

[AUS] fix dashboard issues with duplicate metrics

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_repo/terraform_repo.gql
reconcile/gql_definitions/terraform_repo/terraform_repo.py
reconcile/terraform_repo.py
reconcile/test/test_terraform_repo.py

https://issues.redhat.com/browse/APPSRE-7732
Dependencies:
- https://github.com/app-sre/qontract-schemas/pull/458

terraform-repo - add support for remote gitlab module references

---

dockerfiles/hack/run-integration.py
helm/qontract-reconcile/templates/template.yaml
reconcile/test/fixtures/helm/enable_pushgateway.yml

Fix typo in var name/vault key for Pushgateway

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/utils/terrascript_aws_client.py

Support AWS MSK
Depends on: https://github.com/app-sre/qontract-schemas/pull/451
Ticket: APPSRE-7534

[Apache Managed Streaming for Kafka] MSK support

---

reconcile/utils/terrascript_aws_client.py

`bootstrap_brokers_sasl_iam` and `bootstrap_brokers_sasl_scram` outputs

[msk] additional outputs

---

reconcile/utils/gitlab_api.py

the method used to list all groups by name and check if it exists. other methods use `group_name` but actually mean the url. for example, "Metrics Discovery" is a name, but we call that "metrics" (the url).
this PR changes the method to be aligned with the rest, and even to return the group for the caller to use (and save an extra API call).

[gitlab_api] repurpose check_group_exists

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.publish-release
dockerfiles/Dockerfile.test

$SUBJECT
Ref.: https://issues.redhat.com/browse/APPSRE-7758

update base, builder and test container base images

---

grafana-dashboards/sre-capability-aus-ops.configmap.yaml

fix some aggregation glitches and consistency work across panels

AUS dashboard fixes

---

grafana-dashboards/sre-capability-aus.configmap.yaml

* show current version of clusters
* show organization names in addition to just IDs
* dedicated panel to show versions that are actively soaking

[AUS] customer dashboard improvements

---

.coveragerc

milestone :tada: 
we are currently in 51.98%

bump coverage to 50%

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/utils/terrascript_aws_client.py

Support the creation of multiple MSK SASL/SCRAM users.
Depends on: https://github.com/app-sre/qontract-schemas/pull/467
Ticket: [APPSRE-7534](https://issues.redhat.com/browse/APPSRE-7534)

[terraform msk] multi user support

---

reconcile/openshift_resources_base.py
reconcile/test/test_openshift_resources_base.py

We need a way to generate a hash from a list in jinja2. To my knowledge there is not such thing builtin in the jinja2 renderer.

APPSRE-7561 add jinja2 hash filter for lists

---

reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py
reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_target_long_name.result.yml
reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/files/single_target_long_name.yml
reconcile/test/saas_auto_promotions_manager/merge_request_manager/renderer/test_content_single_target.py

This avoids line wraps for long lines in SAPM MRs.

APPSRE-7821 avoid SAPM linewraps

---

grafana-dashboards/sre-capability-aus.configmap.yaml

* show recently upgraded clusters
* show stats for recently upgraded clusters
* show version distribution

[AUS] cluster upgrade overview dashboard improvments

---

reconcile/test/test_vpc_peerings_validator.py
reconcile/vpc_peerings_validator.py

fix vpc-peerings-validator return

---

reconcile/change_owners/self_service_roles.py
reconcile/test/change_owners/test_change_type_self_service_roles.py

to further drive self-service we need to be able to relate a change-type to all files of a certain schema. this is useful if we want to define admin roles, e.g. self-service-admins can approve all self-service related changes to roles or change-type admins can approve all changes to change-types without the need to relate a change-type to all datafiles/resources.
```yaml
self_service:
- change_type:
$ref: /app-interface/changetype/change-type-admin.yml
- change_type:
$ref: /app-interface/changetype/self-service-admin.yml
```
In this example the change-types are mentioned without listing datafiles or resources, hence the declaring role can approve whatever the change-type defines on all files that match the change-types `contextSchema`.
https://issues.redhat.com/browse/APPSRE-7876

[change-owners] relate change-types to all files of a schema

---

reconcile/change_owners/change_types.py
reconcile/change_owners/self_service_roles.py

when inheritance and ownership expansion are combined, there were situations where the no owning role could be found.

[change-owners] change-owner inheritance fix when used with ownership expansion

---

reconcile/terraform_resources.py

Make the update of secrets in Vault more robust. 
The `disable_keys` method could raise an error, and the Vault secret updates are lost. Especially if the integration takes longer, e.g., creating an MSK cluster, the cached bundle version is outdated, and `disable_keys` raises a 404 error.
Write the outputs to Vault as soon as possible (and retry it) to avoid such cases.

[terraform-resources] more robust vault secrets update

---

grafana-dashboards/sre-capability-idp.configmap.yaml

[rhidp] update grafana dashboard

---

reconcile/gitlab_housekeeping.py

with this label, we will know for each MR if it was submitted by AppSRE or not.
this will allow us to not pollute the dashboard where we reflect our (little) involvement with tenant MRs.
while this change is not very "open source", it works for all the places where gitlab-housekeeping is currently used (commercial and fedramp).

[gitlab-housekeeping] add app_sre label to merged_merge_requests metric

---

reconcile/openshift_saas_deploy.py
reconcile/utils/saasherder/saasherder.py

Follow-up on https://github.com/app-sre/qontract-reconcile/pull/3651
A follow-up PR will adjust SAPM to fetch from v2.
A final follow-up PR will adjust SAPMs logic to calculate refs/hashes.

APPSRE-7307 saasherder uses promotion_state v2

---

reconcile/glitchtip/integration.py

Use later introduced:
* `get_glitchtip_settings`
* `create_secret_reader`
Ticket: [APPSRE-7214](https://issues.redhat.com/browse/APPSRE-7214)

[glitchtip] refactoring

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager-fedramp.yaml
reconcile/test/fixtures/helm/enable_google_chat.yml

Update to https://github.com/app-sre/qontract-reconcile/pull/3624
Filter out only `ERROR` messages as we get a lot of repeat `WARNING`s

update filtering to only filter ERROR messages

---

reconcile/test/utils/test_promotion_state.py
reconcile/utils/promotion_state.py

This reverts commit 0d00211f93acdce8bea44d76fa1712448f7febee.
https://github.com/app-sre/qontract-reconcile/pull/3656

Revert "APPSRE-7307 remove publish promotion_v1 (#3656)"

---

reconcile/gitlab_housekeeping.py

Add information on which project that MR is in.

add more log info

---

reconcile/utils/ocm/ocm.py

Filter addons by search parameter on OCM API
https://issues.redhat.com/browse/APPSRE-8011

Refactor get_cluster_addons

---

tools/qontract_cli.py

Migrate `jenkins-node.md` creation from infra repo to app-interface-output.
Ticket: [APPSRE-8083](https://issues.redhat.com/browse/APPSRE-8083)

[qontract-cli] list EC2 jenkins nodes

---

reconcile/aws_cloudwatch_log_retention/integration.py
reconcile/cli.py
reconcile/queries.py
reconcile/test/test_aws_cloudwatch_log_retention.py
reconcile/utils/aws_api.py
reconcile/vpc_peerings_validator.py
setup.cfg

Log groups are created with infinite log retention. All log groups will have a retention period set within app-interface in order to keep storage costs in check.
Qontract-schemas PR: https://github.com/app-sre/qontract-schemas/pull/456
Part of [APPSRE-7249](https://issues.redhat.com/browse/APPSRE-7249)

Implement log retention cloudwatch logic

---

reconcile/aws_cloudwatch_log_retention/integration.py

Fixing var type in comparing log retention days
Follow up to this fix: https://github.com/app-sre/qontract-reconcile/pull/3724
Part of [APPSRE-7249](https://issues.redhat.com/browse/APPSRE-7249)

Fixing var type in comparing log retention days

---

reconcile/utils/metrics.py
reconcile/utils/ocm_base_client.py

Add metrics to OCM to pin down HTTP Rate limiting issues observed in production

First throw at adding OCM metrics

---

reconcile/test/ldap_groups/test_ldap_groups_integration.py
reconcile/utils/internal_groups/models.py

This addresses a reconcile loop. e.g. https://redhat-internal.slack.com/archives/CS0E65QCV/p1692616370687719

[ldap-groups] fix group comparision

---

reconcile/utils/parse_dhms_duration.py

missing refactor from https://github.com/app-sre/qontract-reconcile/pull/3753

use divmod for minutes as well

---

reconcile/dashdotdb_slo.py
reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.gql
reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.py
reconcile/gql_definitions/introspection.json

Update DashdotSLO, and allow it to use an external reference for getting SLO data from Prometheus.
Related schema change: https://github.com/app-sre/qontract-schemas/pull/505
https://issues.redhat.com/browse/APPSRE-8197

Make SLO Reporter RHOBS compatible

---

reconcile/cli.py
reconcile/openshift_resources.py
reconcile/openshift_resources_base.py
reconcile/prometheus_rules_tester/integration.py
reconcile/test/test_openshift_resources_base.py
tools/qontract_cli.py

Reverts app-sre/qontract-reconcile#3721
error
```
[2023-08-24 01:31:59] [ERROR] [DRY-RUN] [runner.py:_integration_dry_run:221] - Failed to run integration shard crcs02ue1: run() got multiple values for argument 'cluster_name'
```

Revert "Enable openshift-resources clusters exclusion and multiple clusters selection"

---

setup.py

https://github.com/app-sre/sretoolbox/pull/96

sretoolbox 2.4.2: fix image pattern to allow multi-level images

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/status_board/status_board.gql
reconcile/gql_definitions/status_board/status_board.py
reconcile/test/test_status_board.py
reconcile/typed_queries/status_board.py

Child Apps where are missing as of now. Adding Child Apps with this PR.
https://issues.redhat.com/browse/APPSRE-8227

Fix missing child apps

---

reconcile/typed_queries/status_board.py

Fixes: https://issues.redhat.com/browse/APPSRE-8227

Remove print statement

---

reconcile/typed_queries/status_board.py

Reverts app-sre/qontract-reconcile#3769

Revert "Remove print statement"

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/status_board/status_board.gql
reconcile/gql_definitions/status_board/status_board.py
reconcile/test/test_status_board.py
reconcile/typed_queries/status_board.py

Reverts app-sre/qontract-reconcile#3767

Revert "Fix missing child apps"

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/status_board/status_board.gql
reconcile/gql_definitions/status_board/status_board.py
reconcile/test/test_status_board.py
reconcile/typed_queries/status_board.py

Will create apps, that are note referenced by any namespace, but only by a child app relationship
Fixes: https://issues.redhat.com/browse/APPSRE-8227

Fix status board missing apps

---

reconcile/utils/ocm/ocm.py

Quick fix to ignore worker machine pool: https://issues.redhat.com/browse/APPSRE-8258

Ignore worker machine pool in get_machine_pools, see: APPSRE-8258

---

reconcile/utils/saasherder/saasherder.py

We currently silently fail when saasherder cannot populate desired state due to secret management issues.
This patch also contain a safeguard to make sure that populate desired state does log something (in DEBUG, to avoid duplicates in prod) so that debugging is feasible. Not the cleanest, but a better solution would require a whole refactoring of _process_template.

Capture errors from secrets in saasherder

---

reconcile/utils/jenkins_api.py

changeSet may be empty if there are no previous build jobs.

use lastBuiltRevision to get latest commit sha

---

reconcile/cli.py
reconcile/openshift_saas_deploy.py

gitlab_project_id is no longer used

add trigger_integration to slack_notify

---

reconcile/openshift_tekton_resources.py

Minor fix: Set the deploy_resources logic in the right place. `deploy_resources` at saas-file level was skipped.

Fix tekton-resources deploy_resources

---

reconcile/openshift_base.py

`100` will timeout about 1.4 hours, increase it to `200` to wait for about 6 hours.

Increase max_attempts for validate_realized_data

---

reconcile/aws_cloudwatch_log_retention/integration.py

Part of [APPSRE-8172](https://issues.redhat.com/browse/APPSRE-8172) and a follow up to [APPSRE-7249](https://issues.redhat.com/browse/APPSRE-7249)
Currently, the integration is written to make the log retention value configurable. This PR will track the work to include the logic in order to add a default retention value to all log groups in all aws accounts.

Creating logic for default log retention set up on all log groups

---

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py

Reverts app-sre/qontract-reconcile#3816
Forgot tests...

Revert "Fix S3 -> SQS Notifications"

---

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/test/utils/test_terrascript_aws_client.py

Reverts app-sre/qontract-reconcile#3818
Erroring out with AWS API

Revert "Fix S3 -> SQS Notifications "

---

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/test/utils/test_terrascript_aws_client.py

Reverts app-sre/qontract-reconcile#3822

Revert "Bring back S3 -> SQS Notifications MR"

---

reconcile/openshift_saas_deploy.py

[openshift-saas-deploy] actually re-use saas files

---

reconcile/gitlab_housekeeping.py
reconcile/utils/mr/labels.py

to be able to visualize in https://grafana.app-sre.devshift.net/d/xNTPSl-Vk/appsre-overview?orgId=1

add onboarding label to merged merge requests metric

---

reconcile/utils/external_resource_spec.py

part of https://issues.redhat.com/browse/APPSRE-8184

add qontract_reconcile to external resource inventory metric

---

reconcile/terraform_cloudflare_resources.py

[terraform-cloudflare-resources] publish external resource invetory metics

---

reconcile/openshift_base.py
reconcile/utils/openshift_resource.py
reconcile/utils/three_way_diff_strategy.py

* Use the 3-way diff strategy as default, without the feature flag. 
* Remove the old logic 
* Turn the logging messages of the diff method to DEBUG

Remove Feature flag usage for enabling 3 way diff strategy

---

reconcile/utils/state.py

too noisy
followup for https://github.com/app-sre/qontract-reconcile/pull/3827

reduce log level for state init

---

reconcile/gql_definitions/status_board/status_board.gql
reconcile/gql_definitions/status_board/status_board.py
reconcile/test/test_typed_queries/test_status_board.py
reconcile/typed_queries/status_board.py

Change application naming to be consistent, always prefix with parent name

Update Status board

---

reconcile/aus/base.py
reconcile/aus/metrics.py

report OCM environment errors instead of failing the integration
part of https://issues.redhat.com/browse/APPSRE-8433

[AUS] report OCM environment errors

---

reconcile/terraform_cloudflare_resources.py
reconcile/test/test_terraform_cloudflare_resources.py
reconcile/test/test_terraform_cloudflare_users.py

Relates to: [APPSRE-8315](https://issues.redhat.com/browse/APPSRE-8315)
Adds tests to the validation logging in `terraform-cloudflare-resources`.

Test terraform cloudflare resources logging

---

reconcile/openshift_resources_base.py

This is needed by:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/86339

adds path to the namespace query

---

reconcile/dashdotdb_base.py
reconcile/dashdotdb_slo.py
reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.gql
reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.py
reconcile/gql_definitions/introspection.json

Related schema change: https://github.com/app-sre/qontract-schemas/pull/544
[APPSRE-8496](https://issues.redhat.com/browse/APPSRE-8496)

Add basic auth for tokerefresher based SLOs

---

setup.py

The only change upstream is from https://github.com/app-sre/sretoolbox/pull/100

bump sretoolbox to 2.4.3

---

reconcile/database_access_manager.py
reconcile/test/test_database_access_manager.py

Need to pass in entire settings dictionary into _process_db_access and split usage there

DBAM Fixing settings

---

grafana-dashboards/sre-capability-aus.configmap.yaml

show aborted cluster upgrades within the last 24h
https://issues.redhat.com/browse/APPSRE-8560

[AUS dashboard] show aborted cluster upgrades

---

reconcile/cli.py
reconcile/database_access_manager.py
reconcile/test/test_database_access_manager.py

DBAM:
- Update PSQLScriptGenerator, adding update handling
- Add vault output

Dbam add delta and vault export

---

reconcile/gql_definitions/common/saas_files.gql
reconcile/gql_definitions/common/saas_files.py
reconcile/openshift_saas_deploy.py
reconcile/test/test_openshift_saas_deploy.py
reconcile/test/test_typed_queries/test_saas_files.py
reconcile/typed_queries/saas_files.py

Reverts app-sre/qontract-reconcile#3942
Let's give this a go again.

Revert "Revert "APPSRE-8300: Optionally silence successful deploy notices""

---

reconcile/aus/base.py
reconcile/aus/metrics.py
reconcile/aus/ocm_addons_upgrade_scheduler_org.py

part of https://issues.redhat.com/browse/APPSRE-8611
with this PR, the metric will show information about number of rosa/osd/hypershift clusters.

enhance aus_cluster_upgrade_policy_info with product and hypershift labels

---

README.md

Update the list of all available Qontract Reconcile integrations.

[README] update integration list

---

README.md

fix style guide section

---

reconcile/utils/ocm/ocm.py

follows up on https://github.com/app-sre/qontract-reconcile/pull/3954
part of https://issues.redhat.com/browse/APPSRE-8656

[ocm-clusters] maintain oidc endpoint url for HCPs

---

reconcile/utils/mr/clusters_updates.py

See https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/91568/diffs
Tested locally via
```
qd profile run prod ocm-clusters
```

prevent line wraps

---

reconcile/gql_definitions/common/clusters.gql
reconcile/gql_definitions/common/clusters.py
reconcile/gql_definitions/common/clusters_minimal.gql
reconcile/gql_definitions/common/clusters_minimal.py
reconcile/gql_definitions/introspection.json
reconcile/queries.py
reconcile/test/fixtures/clusters/cluster1.yml
reconcile/test/fixtures/clusters/osd_spec_ai.yml
reconcile/test/fixtures/clusters/rosa_spec_ai.yml
reconcile/test/fixtures/oc_connection_parameters/cluster_custom_token.yml
reconcile/test/fixtures/oc_connection_parameters/cluster_no_jumphost.yml
reconcile/test/fixtures/oc_connection_parameters/cluster_with_jumphost.yml
reconcile/test/fixtures/openshift_upgrade_watcher/cluster1.yml

part of https://issues.redhat.com/browse/APPSRE-8663
removing unused code.

remove kibana url

---

reconcile/glitchtip_project_alerts/integration.py
reconcile/test/glitchtip/test_glitchtip_project_alerts.py

Add a glitchtip project alerts webhook uniqueness check to be sure a webhook won't be called multiple times for a project.
Ticket: [APPSRE-8306](https://issues.redhat.com/browse/APPSRE-8306)

[glitchtip-project-alerts] uniq web hook urls

---

reconcile/openshift_clusterrolebindings.py
reconcile/openshift_rolebindings.py

fix set comparision

---

reconcile/jira_permissions_validator.py

[jira-permissions-validator] fix typo

---

reconcile/utils/terrascript_aws_client.py

part of https://issues.redhat.com/browse/APPSRE-8666

[tf-vpc-peering] add missing provider to sg group rules

---

reconcile/jira_permissions_validator.py

Display the priority names instead of the IDs.

[jira-permissions-validator] fix prio mapping error message

---

reconcile/gql_definitions/common/clusters.gql
reconcile/gql_definitions/common/clusters.py
tools/qontract_cli.py

this command will allow adding a cluster file into app-interface and generating a `rosa create cluster` command.
this is a handy shortcut that will remove some manual error prone operations in provisioning rosa clusters.

[qontract-cli] add get rosa-create-cluster-command

---

reconcile/gql_definitions/advanced_upgrade_service/aus_clusters.py
reconcile/gql_definitions/advanced_upgrade_service/aus_organization.py
reconcile/gql_definitions/cna/queries/cna_provisioners.py
reconcile/gql_definitions/common/clusters.py
reconcile/gql_definitions/common/clusters_with_peering.py
reconcile/gql_definitions/common/ocm_environments.py
reconcile/gql_definitions/fragments/ocm_environment.gql
reconcile/gql_definitions/fragments/ocm_environment.py
reconcile/gql_definitions/ocm_labels/clusters.py
reconcile/gql_definitions/rhidp/organizations.py
reconcile/test/fixtures/clusters/osd_spec_ai.yml
reconcile/test/fixtures/clusters/rosa_spec_ai.yml
reconcile/test/fixtures/oc_connection_parameters/cluster_custom_token.yml
reconcile/test/fixtures/oc_connection_parameters/cluster_no_jumphost.yml
reconcile/test/fixtures/oc_connection_parameters/cluster_with_jumphost.yml
reconcile/test/fixtures/ocm_labels/clusters.yml
reconcile/test/fixtures/openshift_upgrade_watcher/cluster1.yml
reconcile/test/ocm/aus/conftest.py
reconcile/test/ocm/aus/fixtures.py
reconcile/test/ocm_labels/test_ocm_labels_integration.py

add labels to ocm environment query

---

reconcile/jenkins_job_builds_cleaner.py

Just to have another SHA, previous has collision and length auto increased to 8 symbols

APPSRE8701 dummy commit to have uniq SHA

---

reconcile/utils/pagerduty_api.py

The PD schedule now would return an empty user list if since = until

fix pd schedule api

---

reconcile/openshift_cluster_bots.py

fix error logging

---

setup.py

Include fix from https://github.com/app-sre/sretoolbox/pull/105
[APPSRE-8176](https://issues.redhat.com/browse/APPSRE-8176)

Bump sretoolbox to 2.5.1

---

reconcile/openshift_cluster_bots.py
reconcile/test/test_openshift_cluster_bots.py

[APPSRE-8784](https://issues.redhat.com/browse/APPSRE-8784)
That's a miss from https://github.com/app-sre/qontract-reconcile/pull/4016

grant cluster-admin clusterrole to the cluster-admin bot

---

reconcile/status_board.py

Deletions need to be handled in a reverse priority order.

Status-board: Handle creations before deletions

---

.coveragerc

we are at 61.5%
previously: #3586

bump coverage to 60%

---

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py
reconcile/saas_auto_promotions_manager/merge_request_manager/reconciler.py

Only ping me if there is an unbatching happening.

APPSRE-8505 proper pinging

---

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py
reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py

Forgot to unset canary flag for title dedup

APPSRE-8505 set proper flag

---

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py
reconcile/saas_auto_promotions_manager/merge_request_manager/metrics.py
reconcile/saas_auto_promotions_manager/merge_request_manager/reconciler.py
reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_merge_request_manager.py
reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_reconciler.py

Exposing SAPM metrics:
- Gauge for parallel open MRs
- Counter for opened MRs (batchable and non-batchable)
- Counter for closed MRs (including reason for closing)
This is required to observe (and potentially alert on) behavior of our auto-promotion batching algorithm.

APPSRE-8804 SAPM metrics

---

reconcile/glitchtip/reconciler.py
reconcile/test/glitchtip/test_utils_glitchtip_client.py
reconcile/utils/glitchtip/client.py
reconcile/utils/glitchtip/models.py

glitchtip client `update_project` needs to be updated too :(
Ticket: APPSRE-9732

[glitchtip] fix update_project

---

reconcile/utils/terrascript_aws_client.py

The result of `terraform_configurations` is used as cache key, but some items in `Terrascript` are not in a stable order, use `sort_keys=True` when dump json as string for consistent hash value.
[Doc](https://python-terrascript.readthedocs.io/en/stable/quickstart.html) mentions
> Option 2: Use the json module from the Python Standard Library but ensure that sort_keys is set to False. indent can be set as preferred.
Not sure about edge cases that lead to unexpected result, so the actual file dumped still using `str(ts)`.
[APPSRE-8725](https://issues.redhat.com/browse/APPSRE-8725)

Sort keys for terraform config used for cache key

---

grafana-dashboards/grafana-dashboard-sapm-metrics.configmap.yaml

Plot opened MR by batch size (counter):
```
round(sum(increase(sapm_opened_mrs_total[5m])) by (batch_size))
```
Plot closed MR by reason (counter):
```
round(sum(increase(sapm_closed_mrs_total[5m])) by (reason))
```
Plot parallel open MRs (gauge):
```
sapm_parallel_open_mrs
```
Plot number of opened un-batchable MRs:
```
round(sum(increase(sapm_opened_mrs_total{is_batchable="False"}[5m])))
```

APPSRE-8804 sapm metric dashboard

---

reconcile/ldap_groups/integration.py

Fix stupid typo
Ticket: APPSRE-9764

[ldap-groups] fix typo in early exit

---

grafana-dashboards/grafana-dashboard-sapm-metrics.configmap.yaml

Follow-up on https://github.com/app-sre/qontract-reconcile/pull/4052
Resizing dashboards (cc @rporres )

APPSRE-8804 resize dashboards

---

reconcile/openshift_resources_base.py
reconcile/utils/terrascript_aws_client.py

Lets remove settings as much as possible. Vast majority of cases we want a secret_reader

terrascript secret_reader support

---

reconcile/aws_saml_idp/integration.py

Refactor the `aws-saml-idp` integration and remove the usage of the untyped `settings` query.
Depends on: #4063

[aws-saml-idp] remove queries

---

reconcile/openshift_saas_deploy.py

It would be used as a product name for defectdojo

[APPSRE-7832] add app name in clamav_file

---

reconcile/terraform_resources.py

same as we did for openshift-resources in https://github.com/app-sre/qontract-reconcile/pull/3784
this simplifies the changed shard detection by having the shard as top level element in the desired state dict.

[terraform-resources] restructure desired state for early exit

---

tools/qontract_cli.py

parse input json file obtained with `oc get PrometheusRule -A` to output a summarized table: https://gitlab.cee.redhat.com/-/snippets/7707

[qontract-cli] get alerts

---

reconcile/test/utils/jobcontroller/fixtures.py
reconcile/test/utils/jobcontroller/test_controller.py
reconcile/utils/jobcontroller/controller.py

* one-off error on backoff_limit handling
* added missing tests for job status checking

[job controller] fix backoff_limit handling and add tests for status checking

---

tools/qontract_cli.py

Example md output: https://gitlab.cee.redhat.com/-/snippets/7779
https://issues.redhat.com/browse/APPSRE-9858

new cli to list all RDS instances

---

tools/qontract_cli.py

https://issues.redhat.com/browse/APPSRE-9858
Example MD ouptut: https://gitlab.cee.redhat.com/-/snippets/7779

add account_uid in qontract-cli get rds output

---

reconcile/test/test_saasherder.py
reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py

replace https://github.com/app-sre/qontract-reconcile/pull/4116
part of https://issues.redhat.com/browse/APPSRE-9856

[openshift-saas-deploy] multiple image auth using dockerconfigjson

---

setup.py

include https://github.com/app-sre/sretoolbox/pull/107

promote sretoolbox

---

reconcile/aus/version_gate_approver.py
reconcile/utils/rosa/session.py

add action logs for reconcile and dry-runs

[version-gate-approver] add action logs

---

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py
reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py

Better visibility of SAPM batch sizes.

SAPM batch size in MR title

---

reconcile/test/utils/test_mr_clusters_updates.py
reconcile/utils/extended_early_exit.py
reconcile/utils/mr/clusters_updates.py

Close `StringIO` after value extracted from stream, free memory.

Close StringIO after use

---

reconcile/utils/terrascript_aws_client.py

discovered as part of the exploration in https://issues.redhat.com/browse/APPSRE-9906
this doesn't change anything except for variable names.

[terraform-resources] rename variables from 0_13

---

reconcile/saas_auto_promotions_manager/integration.py
reconcile/saas_auto_promotions_manager/publisher.py
reconcile/saas_auto_promotions_manager/s3_exporter.py
reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py
reconcile/test/saas_auto_promotions_manager/s3_exporter/conftest.py
reconcile/test/saas_auto_promotions_manager/s3_exporter/test_s3_exporter.py
reconcile/test/saas_auto_promotions_manager/subscriber/conftest.py
reconcile/test/saas_auto_promotions_manager/test_integration_test.py

Export SAPM publisher data to S3
```json
{
"{saas-name}/{resource-template}/{target-name}/{cluster}/{namespace}":
{
"commit_sha": "1234",
"deployment_state": "success|failed|missing"
},
...
}
```

APPSRE-9898 export SAPM publisher data to S3

---

reconcile/saas_auto_promotions_manager/integration.py

Follow up of https://github.com/app-sre/qontract-reconcile/pull/4158

APPSRE-9898 cleanup connections

---

reconcile/saas_auto_promotions_manager/s3_exporter.py
reconcile/test/saas_auto_promotions_manager/s3_exporter/test_s3_exporter.py

The `State.add()` internally already uses `json.dumps` on the given value.

APPSRE-9898 remove json dumps

---

dockerfiles/Dockerfile

Need to put the original entrypoint as an argument to tini.

add original entrypoint to fips layer

---

reconcile/test/utils/test_terrascript_cloudflare_client.py
reconcile/utils/terrascript/cloudflare_client.py

a breaking change behavior, as opposed to #4170
part of https://issues.redhat.com/browse/APPSRE-8451

remove account_id from terraform cloudflare provider

---

dockerfiles/Dockerfile

Reverts app-sre/qontract-reconcile#4174

Revert "bump qontract-reconcile-base to 0.11.2"

---

README.md
dockerfiles/Dockerfile
dockerfiles/README.md

Debugging the q-r image led me down a dependency path so I figured I would capture it for posterity.  
One additional minor change in file comments.

add README to document the qr image and its build and testing process

---

dockerfiles/Dockerfile

part of https://issues.redhat.com/browse/APPSRE-8577
depends on https://github.com/app-sre/container-images/pull/105

[qontract-reconcile-base] add 5.x aws provider

---

reconcile/gql_definitions/jira_permissions_validator/jira_boards_for_permissions_validator.gql
reconcile/gql_definitions/jira_permissions_validator/jira_boards_for_permissions_validator.py
reconcile/jira_permissions_validator.py
reconcile/utils/jira_client.py

Validate the `escalationPolicy.channels.jiraComponent` attribute.
Ticket: [APPSRE-9923](https://issues.redhat.com/browse/APPSRE-9923)

:sparkles: jira-permissions-validator: check jira components

---

reconcile/utils/terrascript_aws_client.py

terrascript remove providers from configuration block

---

reconcile/cli.py

Send only critical events to Glichtip to avoid unnecessary traffic.
Ticket: [APPSRE-9911](https://issues.redhat.com/browse/APPSRE-9911)

:zap: sentry: set default event level to CRITICAL

---

reconcile/aus/version_gate_approver.py

forgot to register
follows up on https://github.com/app-sre/qontract-reconcile/pull/4214

[AUS] fix for ingress-gate handler

---

helm/README.md
helm/qontract-reconcile/templates/template.yaml
reconcile/gql_definitions/integrations/integrations.gql
reconcile/gql_definitions/integrations/integrations.py
reconcile/gql_definitions/introspection.json
reconcile/test/fixtures/helm/cache_storage_vars.yml
reconcile/test/utils/test_helm.py

This will allow to run integrations where there are different storage class provider available.
related to APPSRE-9916
schema changes: https://github.com/app-sre/qontract-schemas/pull/608

Allow cache cfg storageClassName integrations

---

reconcile/aus/advanced_upgrade_service.py
reconcile/aus/ocm_addons_upgrade_scheduler_org.py
reconcile/aus/ocm_upgrade_scheduler.py
reconcile/aus/ocm_upgrade_scheduler_org.py
reconcile/aus/version_gate_approver.py
reconcile/utils/ocm_base_client.py
reconcile/utils/prometheus.py

this PR makes sure several requests sessions in the AUS context are closed properly when they are not required anymore. 
* for the `OCMBaseClient` class, a context manager was implemented which takes care of that
* for prometheus queries, an explicit session is used as well in a context manager
local testing showed a constant FD count even after hours of running the integration.
part of https://issues.redhat.com/browse/APPSRE-9971

[AUS] memory leaks with requests sessions

---

reconcile/utils/jobcontroller/controller.py
reconcile/utils/oc.py

Requirement for ERv2. It introduces the option to write job logs into stdout.

Enable writting Job logs to stdout

---

tools/cli_commands/cost_report/view.py
tools/cli_commands/test/fixtures/cost_report.md
tools/cli_commands/test/fixtures/empty_cost_report.md

Add `[TOC]` to cost report to avoid scrolling.

[cost-report] Add TOC to cost report

---

reconcile/gql_definitions/common/pipeline_providers.py
reconcile/gql_definitions/fragments/pipeline_provider_retention.gql
reconcile/gql_definitions/fragments/pipeline_provider_retention.py
reconcile/gql_definitions/introspection.json
reconcile/openshift_saas_deploy_trigger_cleaner.py
reconcile/test/fixtures/openshift_saas_deploy_trigger_cleaner/pipeline_runs.yaml
reconcile/test/test_openshift_saas_deploy_trigger_cleaner.py

This will be helpful to avoid bloating on those providers with too many PipelineRuns, even for a day.
APPSRE-10006
https://github.com/app-sre/qontract-schemas/pull/616

Add maximum setting to PipelineRun retention

---

reconcile/utils/saasherder/saasherder.py

Reverts app-sre/qontract-reconcile#4090

Revert "Add logging in case ClowdApp and Deployment are used together"

---

reconcile/utils/ocm/addons.py

Fix the addon upgrade plan url.

fix addon upgrade plan url template

---

grafana-dashboards/grafana-dashboard-external-resource-inventory.configmap.yaml
grafana-dashboards/grafana-dashboard-integrations.configmap.yaml
grafana-dashboards/grafana-dashboard-openshift-resource-inventory.configmap.yaml
grafana-dashboards/grafana-dashboard-sapm-metrics.configmap.yaml

APPSRE-9916
Updates grafana datasources from appsrep05ue1 > appsrep09ue1

update grafana datasources

---

reconcile/utils/acs/base.py

add error logging to ACS base generic request

---

reconcile/acs_policies.py
reconcile/acs_rbac.py
reconcile/test/test_acs_policies.py
reconcile/utils/acs/base.py

in order to simplify initialization of inheriting classes.

AcsBaseApi based on BaseModel

---

reconcile/cli.py
reconcile/utils/amtool.py
reconcile/utils/promtool.py
tools/qontract_cli.py

Check for amtool and promtool versions

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/templating/template_collection.gql
reconcile/gql_definitions/templating/template_collection.py
reconcile/gql_definitions/templating/templates.gql
reconcile/gql_definitions/templating/templates.py
reconcile/templating/lib/merge_request_manager.py
reconcile/templating/lib/model.py
reconcile/templating/renderer.py
reconcile/templating/validator.py
reconcile/test/templating/lib/test_tr_merge_request_manager.py
reconcile/test/templating/test_renderer.py

Related schema change: https://github.com/app-sre/qontract-schemas/pull/626
[APPSRE-10065](https://issues.redhat.com/browse/APPSRE-10065)

Add auto approval and labels support

---

reconcile/templating/renderer.py

Writes must be done after each template iteration.
Will look into improving tests for this.

Output must be written after each template

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_cloudflare_dns/terraform_cloudflare_zones.gql
reconcile/gql_definitions/terraform_cloudflare_dns/terraform_cloudflare_zones.py

https://issues.redhat.com/browse/APPSRE-10082
Requires https://github.com/app-sre/qontract-schemas/pull/634

terraform_cloudflare_dns: add support for CAA record types

---

reconcile/gabi_authorized_users.py

APPSRE-10157
schema change in https://github.com/app-sre/qontract-schemas/pull/635

gabi-authorized-users can be disabled in a cluster

---

dockerfiles/Dockerfile
reconcile/utils/terrascript_aws_client.py

APPSRE-9975
Depends on https://github.com/app-sre/container-images/pull/117
Tested using https://gitlab.cee.redhat.com/app-sre/app-interface-dev-data/-/merge_requests/118/diffs

Replace deprecated `template` provider with `cloudinit`

---

pyproject.toml
reconcile/external_resources/manager.py
reconcile/ocm_aws_infrastructure_access.py
reconcile/test/test_openshift_base.py
requirements/requirements-test.txt

Upgrade `ruff` to latest version.
Ticket: [APPSRE-10165](https://issues.redhat.com/browse/APPSRE-10165)

:arrow_up: ruff 0.4.1

---

reconcile/test/utils/aws_api_typed/test_aws_api_typed_api.py
reconcile/utils/aws_api_typed/api.py

Fix some mypy 1.10.0 errors in `aws_api_typed`

:white_check_mark: aws_api_typed: fix mypy 1.10.0 errors

---

reconcile/utils/promotion_state.py
reconcile/utils/saasherder/saasherder.py

related to https://issues.redhat.com/browse/APPSRE-10117
with this additional information we will know when a deployment occurred so we can measure how much time passed since, so we can decide if soak days have passed.

[saasherder] add check_in date to promotion data

---

reconcile/statuspage/atlassian.py

status-page-components integration fails without pagination due to attempted component creation that already exists
this adds pagination when listing components

[statuspage-components] list_component pagination

---

reconcile/test/utils/test_promotion_state.py
reconcile/utils/promotion_state.py
reconcile/utils/saasherder/saasherder.py

Follow-up of https://github.com/app-sre/qontract-reconcile/pull/4323
Required by https://github.com/app-sre/qontract-reconcile/pull/4320

APPSRE-10117 check-in ts

---

reconcile/glitchtip_project_alerts/integration.py
reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.gql
reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.py
reconcile/test/fixtures/glitchtip/project_alerts.yml
reconcile/test/glitchtip/test_glitchtip_project_alerts.py

Honor the `jiraboard.disable.integrations` attribute.
Ticket: [APPSRE-8679](https://issues.redhat.com/browse/APPSRE-8679)

:sparkles: glitchtip-project-alerts: honor jiraboard.disable.integrations

---

reconcile/gql_definitions/common/saas_files.gql
reconcile/gql_definitions/common/saas_files.py
reconcile/gql_definitions/introspection.json
reconcile/saas_auto_promotions_manager/publisher.py
reconcile/saas_auto_promotions_manager/subscriber.py
reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py
reconcile/test/saas_auto_promotions_manager/conftest.py
reconcile/test/saas_auto_promotions_manager/s3_exporter/conftest.py
reconcile/test/test_saasherder.py

Preparation for basic `soakDays` logic in SAPM.

APPSRE-10117 preparation for basic soakDays logic

---

reconcile/statuspage/atlassian.py

follow up on #4332
now that we are paging we are hitting more rate limit. retry the get request to avoid errors.

[statuspage-components] atlassian retry get

---

tools/qontract_cli.py

Remove the `qontract-cli terraform-users-credentials` command because it's entirely [outdated](https://gitlab.cee.redhat.com/service/app-interface-output/-/blob/master/terraform-users-credentials.md) and shows wrong information. No integration or job removes old IAM user secrets from Vault or the S3 state. SSO is enabled for most of our AWS accounts, so it isn't worth investing time fixing that.
Ticket: [APPSRE-10216](https://issues.redhat.com/browse/APPSRE-10216)

:coffin: qontract-cli: remove outdated terraform_users_credentials output

---

grafana-dashboards/sre-capability-aus-addons.configmap.yaml
grafana-dashboards/sre-capability-aus-ops.configmap.yaml
grafana-dashboards/sre-capability-aus.configmap.yaml
grafana-dashboards/sre-capability-idp.configmap.yaml

update sre-capabilities datasources after migration

update sre-capabilities datasources

---

reconcile/cli.py
reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/statuspage/statuspages.gql
reconcile/gql_definitions/statuspage/statuspages.py
reconcile/statuspage/atlassian.py
reconcile/statuspage/integrations/maintenances.py
reconcile/statuspage/page.py
reconcile/test/statuspage/fixtures.py

[status-page-maintenances] introduce integration

---

reconcile/gql_definitions/statuspage/statuspages.gql
reconcile/gql_definitions/statuspage/statuspages.py
reconcile/statuspage/atlassian.py
reconcile/statuspage/integrations/maintenances.py
reconcile/statuspage/page.py

follows up on #4344
in this PR we add support to add affected components to an incident.

[status-page-maintenances] component support

---

reconcile/gql_definitions/maintenance/maintenances.gql
reconcile/gql_definitions/maintenance/maintenances.py
reconcile/gql_definitions/statuspage/statuspages.gql
reconcile/gql_definitions/statuspage/statuspages.py
reconcile/statuspage/atlassian.py
reconcile/statuspage/page.py

follows up on https://github.com/app-sre/qontract-reconcile/pull/4344
in this PR we add support to set notifications settings on an incident.

[status-page-maintenances] notifications support

---

reconcile/statuspage/atlassian.py

follows up on #4344
depends on #4349
in this PR we add conditions to have the components integration not set status when there is an active maintenance.

[wip][status-page-components] consider active maintenances when setting status

---

tools/saas_metrics_exporter/commit_distance/commit_distance.py
tools/saas_metrics_exporter/commit_distance/metrics.py
tools/test/saas_metrics_exporter/test_commit_distance.py

follow-up on https://github.com/app-sre/qontract-reconcile/pull/4285
Specifically addressing:
- cleaner structure, suggestions from https://github.com/app-sre/qontract-reconcile/pull/4285#discussion_r1596561634
- unify tests
- more advanced test case for multiple distances

APPSRE-10053 saas-metrics-exporter enhancements

---

tools/saas_metrics_exporter/commit_distance/commit_distance.py

Fixing error in prod
```
TypeError: unhashable type: 'VaultSecret'
```

hashable distancekey

---

helm/qontract-reconcile/templates/template.yaml
helm/qontract-reconcile/values-manager-fedramp.yaml
openshift/qontract-manager-fedramp.yaml

Editing fluentd configuration to filter out more warning messages coming from Unleash in the FedRAMP environment

adding Unleash log filters for FR

---

tools/qontract_cli.py

based on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/106045
let's try to automate the progress of the HCP migration effort with an app-interface-output.

[qontract-cli/get] hcp migration status

---

tools/qontract_cli.py

mostly using a class to do the math, and changing the summary from completed services to completed targets

Hcp migration status touchtups

---

reconcile/statuspage/atlassian.py
reconcile/test/statuspage/test_statuspage_atlassian.py

statuspage fixes following up on deep testing

---

reconcile/dynatrace_token_provider/integration.py
reconcile/dynatrace_token_provider/metrics.py

Expose number of DTP managed clusters

Expose metric for DTP managed clusters

---

pyproject.toml
requirements/requirements-test.txt

:arrow_up: ruff 0.4.5

---

reconcile/saas_auto_promotions_manager/subscriber.py
reconcile/test/saas_auto_promotions_manager/subscriber/test_soak_days.py

Add accumulated soakDays logic to SAPM.

APPSRE-10117 soak days logic

---

helm/qontract-reconcile/templates/template.yaml
openshift/qontract-manager-fedramp.yaml
openshift/qontract-manager.yaml
reconcile/test/fixtures/helm/aws_account_shard_disabled.yml
reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml
reconcile/test/fixtures/helm/aws_account_shards.yml
reconcile/test/fixtures/helm/basic.yml
reconcile/test/fixtures/helm/cache.yml
reconcile/test/fixtures/helm/cache_storage_vars.yml
reconcile/test/fixtures/helm/command.yml
reconcile/test/fixtures/helm/disable_unleash.yml
reconcile/test/fixtures/helm/enable_google_chat.yml
reconcile/test/fixtures/helm/environment_aware.yml
reconcile/test/fixtures/helm/exclude_service.yml
reconcile/test/fixtures/helm/extra_args.yml
reconcile/test/fixtures/helm/extra_env.yml
reconcile/test/fixtures/helm/integrations_manager.yml
reconcile/test/fixtures/helm/internal_certificates.yml
reconcile/test/fixtures/helm/logs_slack.yml
reconcile/test/fixtures/helm/shards.yml
reconcile/test/fixtures/helm/sleep_duration.yml
reconcile/test/fixtures/helm/state.yml
reconcile/test/fixtures/helm/storage.yml
reconcile/test/fixtures/helm/trigger.yml

We've currently more than 19k replicasets.

 lower revision history limit

---

grafana-dashboards/sre-capability-aus.configmap.yaml

Allows more drill down in this wonderful dashboard

AUS dashboard: additional filters

---

grafana-dashboards/sre-capability-aus.configmap.yaml

This filter needs to include a wildcard regex since the label contains a list of workloads

AUS dashboard: Fix workloads filter

---

setup.py

Fix https://github.com/app-sre/qontract-reconcile/security/dependabot/7

Upgrade requests to 2.32

---

reconcile/gql_definitions/common/app_code_component_repos.gql
reconcile/gql_definitions/common/app_code_component_repos.py
reconcile/gql_definitions/introspection.json
tools/cli_commands/systems_and_tools.py

this PR adds a description and more code components to the report.
depends on https://github.com/app-sre/qontract-schemas/pull/658

[qontract-cli] get systems-and-tools feature enhancements

---

tools/cli_commands/systems_and_tools.py
tools/qontract_cli.py

as part of this report we need to demonstrate an API that enumerates the different items.
this PR adds an `enumeration` field to the report that will contain the graphql query definition which is used to obtain the information of that row.

[qontract-cli] get systems-and-tools add enumeration api

---

reconcile/test/fixtures/saasherder/saas-multi-channel.gql.yml
reconcile/test/fixtures/saasherder/saas-soak-days.gql.yml
reconcile/test/test_saasherder.py
reconcile/utils/saasherder/interfaces.py
reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py

- saasherder gating promotions with accumulated soakDays
- fixing a bug in which certain promotion criteria can skip validation of following promotions.

APPSRE-10117 soakDays for saasherder

---

reconcile/openshift_resources_base.py

Fix mocking of jinja2 template function in early exit.
`prometheus-rules-tester` is failing with 
```
--- Logging error ---
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/jinja2/utils.py", line 191, in process_jinja2_template
r = template.render(vars)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 18, in top-level template code
File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
raise SecurityError(f"{__obj!r} is not safely callable") …
```

:bug: openshift-resouces-base: fix jinja2 functions mocks for early exit

---

reconcile/jenkins_job_builder.py
reconcile/jenkins_webhooks.py
reconcile/queries.py
tools/qontract_cli.py

cli command to track Jenkins RHEL8 migration

---

reconcile/external_resources/factories.py

This PR adds the same resource tags logic as terraform-resources.

Add AWS tags to input data

---

reconcile/gitlab_permissions.py
reconcile/test/test_gitlab_permissions.py
reconcile/test/utils/test_gitlab_api.py
reconcile/utils/gitlab_api.py

Fixes :https://issues.redhat.com/browse/APPSRE-10362

added code to reshare projects with different permission

---

reconcile/gql_definitions/common/saas_files.gql
reconcile/gql_definitions/common/saas_files.py
reconcile/gql_definitions/common/saas_target_namespaces.py
reconcile/gql_definitions/fragments/saas_target_namespace.gql
reconcile/gql_definitions/fragments/saas_target_namespace.py
reconcile/gql_definitions/introspection.json
reconcile/test/test_saasherder.py
reconcile/test/test_typed_queries/test_saas_files.py
reconcile/utils/saasherder/interfaces.py
reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-10364
depends on https://github.com/app-sre/qontract-schemas/pull/669
with this PR, commit sha which will be defined under `hotfixVersions` for a `codeComponent` will be able to be promoted even being published with success to any subscribed channels (automated promotion).

saasherder validate promotion of hotfix versions

---

reconcile/gql_definitions/common/saas_files.gql
reconcile/gql_definitions/common/saas_files.py
reconcile/gql_definitions/common/saas_target_namespaces.py
reconcile/gql_definitions/fragments/saas_target_namespace.gql
reconcile/gql_definitions/fragments/saas_target_namespace.py
reconcile/gql_definitions/introspection.json
reconcile/test/test_saasherder.py
reconcile/utils/saasherder/interfaces.py
reconcile/utils/saasherder/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-10279
depends on #670
with this PR, commit sha which will be defined under `blockedVersions` for a `codeComponent` will not be able to be promoted.

saasherder validate promotion of blocked versions

---

reconcile/glitchtip/integration.py
reconcile/glitchtip_project_alerts/integration.py
reconcile/glitchtip_project_dsn/integration.py
reconcile/gql_definitions/glitchtip/glitchtip_project.py
reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.py
reconcile/gql_definitions/introspection.json
reconcile/test/glitchtip/test_glitchtip.py
reconcile/test/glitchtip/test_glitchtip_project_alerts.py
reconcile/test/glitchtip/test_glitchtip_project_dsn.py

Rename the GQL class `GlitchtipProjects_v1` to `GlitchtipProject_v1`
Depends on: https://github.com/app-sre/qontract-schemas/pull/666

:recycle: s/GlitchtipProjects_v1/GlitchtipProject_v1/g

---

reconcile/terraform_vpc_resources/integration.py
reconcile/test/terraform_vpc_resources/test_terraform_vpc_resources_integration.py
reconcile/test/utils/test_terraform_client.py
reconcile/utils/terraform_client.py

This prevent users approving a failed run of `terraform plan`.

:bug: Raises exception when plan errors are detected

---

reconcile/saas_auto_promotions_manager/subscriber.py
reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py
reconcile/test/saas_auto_promotions_manager/conftest.py
reconcile/test/saas_auto_promotions_manager/subscriber/test_blocked_version.py

- SAPM must not open MRs for blocked versions.
- more logging for visibility which gate blocked a promotion

APPSRE-10279 blockversions for SAPM

---

tools/qontract_cli.py

This command is to facilitate resources migration. It prints the resource input data that can be used directly by a module to import existing assets to the new terraform state.

Add a external-resources get-input cli command to get er spec input data

---

reconcile/test/utils/dynatrace/conftest.py
reconcile/test/utils/dynatrace/test_dynatrace_client.py
reconcile/utils/dynatrace/client.py

A client wrapper around the Dynatrace API.
The functions are fairly simple, but test layer is easily extensible for future functions which might be more complex.

APPSRE-10229 dynatrace client

---

reconcile/utils/saasherder/saasherder.py

Nested directories fail with 404. Lets also point out that nested dirs are a problem currently.

APPSRE-10406 more details

---

reconcile/test/utils/test_terrascript_aws_client.py
reconcile/utils/terrascript_aws_client.py

To prevent error described in jira.

[APPSRE-9928] Add validation code to ensure output_resource_name is unique in a namespace

---

tools/qontract_cli.py

Print quick access link to the saas deploy state file in S3 for further debugging.

APPSRE-10351 print state url

---

tools/qontract_cli.py

Follow up on https://github.com/app-sre/qontract-reconcile/pull/4450#discussion_r1638005209

APPSRE-10351 add region

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/templating/template_collection.py

Update GQL classes after the latest [schema changes](https://github.com/app-sre/qontract-schemas/pull/667).

:bug: template-renderer: update GQL classes

---

reconcile/templating/lib/merge_request_manager.py

As title says. This will be helpful when trying to see what MRs are being skipped or closed

templating: log mr urls when skipping or closing them

---

reconcile/cli.py
reconcile/templating/renderer.py

make it easier to check output of new template collection.

enable render specific template collection

---

reconcile/gitlab_labeler.py

To automate the testing in rhel8 nodes. This won't last long, but will save a few clicks in the meantime.
related to APPSRE-7238

Add test-on-rhel8-ai label to app-sre MRs

---

reconcile/test/ocm/fixtures.py
reconcile/test/ocm/test_utils_ocm_syncset.py
reconcile/utils/ocm/syncsets.py

Add a way to query all syncsets of a cluster.

APPSRE-10229 list all syncsets

---

reconcile/change_owners/approver.py
reconcile/change_owners/self_service_roles.py
reconcile/gql_definitions/change_owners/queries/self_service_roles.gql
reconcile/gql_definitions/change_owners/queries/self_service_roles.py
reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/slack_usergroups/permissions.py
reconcile/test/change_owners/fixtures.py
reconcile/test/change_owners/test_change_type_self_service_roles.py

depends on https://github.com/app-sre/qontract-schemas/pull/673
with this change, users will be instructed in what slack channel to reach out to a slack usergroup for a MR review.

comment on self-service MRs with channel to reach out to slack usergroup

---

reconcile/gql_definitions/aws_account_manager/aws_accounts.gql
reconcile/gql_definitions/aws_account_manager/aws_accounts.py
reconcile/gql_definitions/introspection.json

Query the `/aws/account-request-1.additionalFeatures` attribute and add it to the render variables.
Ticket: [APPSRE-10384](https://issues.redhat.com/browse/APPSRE-10384)
Depends on: https://github.com/app-sre/qontract-schemas/pull/674

:sparkles: aws-account-manager: accountRequest.additionalFeatures support

---

reconcile/utils/saasherder/saasherder.py

saasherder populate_desired_state_saas_file log error

---

reconcile/cli.py
reconcile/utils/helm.py
reconcile/utils/saasherder/saasherder.py

depends on https://github.com/app-sre/qontract-schemas/pull/676
with this PR we intend to enable deploying helm charts.
example MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/109504

[openshift-saas-deploy] initial support for helm charts

---

reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py

minor refactor to expose properties and reduce number of input arguments to TargetSpec.

[saasherder] TargetSpec simplification

---

reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py

follow up on #4478
move parameters handling into TargetSpec to simplify saasherder.

[saasherder] TargetSpec parameters

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/templating/template_collection.gql
reconcile/gql_definitions/templating/template_collection.py
reconcile/templating/renderer.py

fix https://github.com/app-sre/qontract-reconcile/pull/4443
depends on https://github.com/app-sre/qontract-schemas/pull/677

enable searchable for template collection name

---

reconcile/aws_account_manager/merge_request_manager.py
reconcile/gitlab_fork_compliance.py
reconcile/gitlab_housekeeping.py
reconcile/saas_auto_promotions_manager/merge_request_manager/mr_parser.py
reconcile/test/test_gitlab_housekeeping.py
reconcile/test/utils/test_gitlab_api.py
reconcile/utils/gitlab_api.py
reconcile/utils/merge_request_manager/merge_request_manager.py
setup.py

[APPSRE-10438](https://issues.redhat.com/browse/APPSRE-10438)
Main changes:
* methods change
* `.members.all()` -> `.members_all.list()`
* `.pipelines()` -> `.pipelines.list()`
* `list` now has more support for pagination (`get_all` and `iterator`), warning when used without any paging params.
* const import path from `gitlab` to `gitlab.const`
* more typing added
Verified by running a few integrations locally such as `gitlab-housekeeping`, `gitlab-labeler`, more issues maybe found after promote.
Followup card created to address `TODO` [APPSRE-10450](https://issues.redhat.com/browse/APPSRE-10450)

Upgrade python-gitlab to 4.6

---

tools/qontract_cli.py

part of https://issues.redhat.com/browse/APPSRE-10450
follow up on #4467

[qontract-cli] mr.pipelines fixes

---

reconcile/test/test_saasherder.py
reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py

consolidate more logic into TargetSpec

[saasherder] TargetSpec simplification: html_url, error_prefix

---

reconcile/test/utils/dynatrace/conftest.py
reconcile/test/utils/dynatrace/test_dynatrace_client.py
reconcile/utils/dynatrace/client.py

Dynatrace Client needs to fetch token ids for tokens with given prefix

APPSRE-10229 dt client list token ids

---

reconcile/ocm_groups.py
reconcile/openshift_groups.py
reconcile/utils/ocm/base.py

with this PR we enable management of the `cluster-admins` group via OCM.

cluster-admins group management

---

reconcile/templating/lib/merge_request_manager.py
reconcile/templating/lib/model.py
reconcile/templating/renderer.py
reconcile/test/templating/lib/test_tr_merge_request_manager.py
reconcile/test/templating/test_renderer.py

restructure TemplateInput to be TemplateResult

[Template] use generated outputs as hash source

---

reconcile/queries.py

a required fix on top of #4504

ocm-clusters query for billing account

---

reconcile/openshift_base.py

should be set in options to be considered

fix cluster admin usage in oc delete

---

.tool-versions

helm used in integrations deployment but is also now supported in saas-deploy

request helm 3.11.1 to be installed

---

tools/qontract_cli.py

Display only the last 100 MRs and not ALL MRs.

:bug: app-interface-merge-history: show the last 100 MRs only

---

reconcile/aws_account_manager/integration.py
reconcile/cli.py
reconcile/test/aws_account_manager/test_aws_account_manager_integration.py

Store initial user credentials in the new app-sre versioned key store.
Ticket: [APPSRE-10496](https://issues.redhat.com/browse/APPSRE-10496)

:recycle: aws-account-manager: update initial-user-secret-vault-path

---

reconcile/utils/helm.py

consider this as an example of the functionality: https://github.com/stackrox/acs-fleet-manager/blob/main/dp-terraform/helm/rhacs-terraform/Chart.yaml
this PR adds functionality to perform `helm repo add` and `helm dependency build`, to be able to template the chart, should it have dependencies.

[saasherder\helm] handle dependencies

---

reconcile/utils/jinja2/filters.py
reconcile/utils/jinja2/utils.py

Useful while fetching resources from a template.
Needed to create an alert for APPSRE-10556

Create yaml_to_dict jinja2 filter

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.publish-release
dockerfiles/Dockerfile.test

Update docker images

---

reconcile/openshift_serviceaccount_tokens.py
reconcile/test/test_openshift_serviceaccount_tokens.py

OpenShift [4.16+](https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-notable-technical-changes_release-notes) doesn't automatically create a service account token secret for new service accounts anymore. This PR adds the token creation functionality into `openshift-serviceaccount-tokens`.
Ticket: [APPSRE-10518](https://issues.redhat.com/browse/APPSRE-10518)
Hint for the reviewers: We want to create the token secret and leave it "unmanaged" afterward. So we can leverage `ResourceInventory` instead of manual `oc apply`.

:sparkles: openshift-serviceaccount-tokens: create service account token secret for OpenShift 4.16+

---

reconcile/gql_definitions/integrations/integrations.gql
reconcile/gql_definitions/integrations/integrations.py
tools/qontract_cli.py

convenience function to get a command to get logs from an integration

[qontract-cli] get logs for integration

---

reconcile/utils/glitchtip/models.py

Glitchtip 4.0.10 introduces some API breaks :(

:bug: glitchtip: fix REST API models for Glitchtip 4.0.10+

---

reconcile/utils/glitchtip/client.py

The glitchtip v4.0.11 org user REST API has some breaking changes

:bug: glitchtip api: fix org user REST API model

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py

terraform-resources aws-iam-role query for policies

---

reconcile/test/utils/test_promotion_state.py
reconcile/utils/promotion_state.py

Follow-up on https://github.com/app-sre/qontract-reconcile/pull/4539

avoid KeyError on promotion without success

---

reconcile/utils/helm.py

fixes error:
```
Error: mkdir /.config: permission denied
[ERROR] [saasherder.py:populate_desired_state_saas_file:1285] - Error in populate_desired_state_saas_file: Error running helm template [helm repo add external-secrets https://charts.external-secrets.io/]
```
flag described in https://helm.sh/docs/helm/helm_repo/

saasherder helm temporary repositories file

---

reconcile/utils/terrascript_aws_client.py

Closes: [APPSRE-10578](https://issues.redhat.com/browse/APPSRE-10578).
This adds the needed `vpc_endpoint` module to terraform-vpc-resources.

🐛 Fix - Add a vpc_endpoint to vpc-resources

---

reconcile/cli.py
reconcile/external_resources/integration.py
reconcile/external_resources/manager.py

- **Check resource diffs when a resource falls into a PENDING_SERET_SYNC state**
- **Implement Early exit for external-resources integration**
APPSRE-10626

Implement Early-exit in External-Resources integration

---

reconcile/external_resources/secrets_sync.py

Introduce Output values formatter

---

reconcile/quay_base.py

part of https://issues.redhat.com/browse/APPSRE-10662
enable adding orgs without automation token to support saas file validation in #4569

quay skip orgs without automation token

---

reconcile/openshift_base.py

[APPSRE-10657](https://issues.redhat.com/browse/APPSRE-10657)
Up to now we were using the standard / dedicated-admin token. We were lucky that dedicated-admin can "read" most global resources.

Use the clusterAdmin creds when fetching current state for clusterAdmin enabled saas-files

---

reconcile/change_owners/self_service_roles.py
reconcile/gql_definitions/change_owners/queries/self_service_roles.gql
reconcile/gql_definitions/change_owners/queries/self_service_roles.py
reconcile/test/change_owners/fixtures.py
reconcile/test/change_owners/test_change_type_self_service_roles.py

allows defining temporary self-service ownership

self-service consider expiration date in roles

---

reconcile/gql_definitions/common/app_quay_repos_escalation_policies.gql
reconcile/gql_definitions/common/app_quay_repos_escalation_policies.py
tools/qontract_cli.py

qc get container-image-details support parentApp

---

reconcile/saas_file_validator.py

part of https://issues.redhat.com/browse/APPSRE-10662
fixes #4569
oopsie

[saas-file-validator] actually exit with error on missing image patterns

---

reconcile/test/utils/test_terraform_client.py
reconcile/utils/aws_api.py
reconcile/utils/terraform_client.py

Adds validation for rds enable blue_green_update

[APPSRE-10253] - Add validation for rds enable blue_green_update

---

reconcile/external_resources/manager.py
reconcile/external_resources/state.py
reconcile/test/external_resources/test_outputs_formatter.py
tools/qontract_cli.py

- **Add OutputSecretsFormatter tests**
- **Add a CLI command to request a resource reconciliation**

ERv2 output resource format tests + ad-hoc reconciliations request cmd

---

build_deploy.sh

part of https://issues.redhat.com/browse/APPSRE-10692
depends on #4576, which needs to be promoted to commercial first.

send a message to SQS on push to trigger promotion

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.publish-release
dockerfiles/Dockerfile.test

Update base docker images

---

reconcile/test/utils/test_mr.py
reconcile/utils/mr/promote_qontract.py

part of https://issues.redhat.com/browse/APPSRE-10692
style improvements on top of #4576

style improvements for promote_qontract_reconcile

---

reconcile/utils/mr/promote_qontract.py

fix qontract-reconcile promotion

---

reconcile/endpoints_discovery/integration.py
reconcile/endpoints_discovery/merge_request_manager.py

Always check for outdated MRs and close them.

:bug: endpoints-discovery: always close outdated MRs

---

reconcile/test/utils/test_mr.py
reconcile/typed_queries/users.py
reconcile/utils/mr/promote_qontract.py

attempt to find the author based on the email from the git commit and ping that person on the auto-generated promotion merge request

[promote_qontract_reconcile] ping author

---

Makefile

depends on #4600 being promoted to production
this PR adds the commit author email to the SQS message leading to the promotion merge request

[promote_qontract_reconcile] make sqs pass commit author email

---

reconcile/cli.py
reconcile/dynatrace_token_provider/dependencies.py
reconcile/dynatrace_token_provider/integration.py
reconcile/dynatrace_token_provider/validate.py
reconcile/test/dynatrace_token_provider/conftest.py
reconcile/test/dynatrace_token_provider/test_create_manifest.py
reconcile/test/dynatrace_token_provider/test_create_syncset.py
reconcile/test/dynatrace_token_provider/test_dry_run.py
reconcile/test/dynatrace_token_provider/test_no_change_manifest.py
reconcile/test/dynatrace_token_provider/test_no_change_syncset.py
reconcile/test/dynatrace_token_provider/test_ocm_org_filters.py
reconcile/test/dynatrace_token_provider/test_patch_manifest.py
reconcile/test/dynatrace_token_provider/test_patch_syncset.py
reconcile/test/dynatrace_token_provider/test_spec_token_diff.py
reconcile/test/dynatrace_token_provider/test_spec_validation.py

We cannot catch all spec misconfiguration via json schema. In this PR we add spec validation.

APPSRE-10615 DTP pr-check

---

reconcile/saas_auto_promotions_manager/merge_request_manager/batcher.py

SAPM batching works reliably. No need to get pinged any longer.

remove pinging kfischer

---

reconcile/dynatrace_token_provider/integration.py
reconcile/dynatrace_token_provider/metrics.py

- Fix cluster metric -> previously we also counted filtered clusters
- add token gauge -> `dtp_tokens_managed{ ocm_env_name, dt_tenant_id }`

APPSRE-10615 more DTP metrics

---

reconcile/dynatrace_token_provider/integration.py
reconcile/dynatrace_token_provider/ocm.py

Lets name the default spec explicitly to what it is.
Also added more logging which is interesting for dry-runs

APPSRE-10615 DTP default spec and logging

---

reconcile/openshift_resources_base.py
reconcile/test/test_utils_jinja2.py
reconcile/utils/aws_api.py
reconcile/utils/jinja2/filters.py
reconcile/utils/jinja2/utils.py

part of https://issues.redhat.com/browse/APPSRE-10734
similar to #4169
this PR introduces templating based on a list of S3 objects.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/114882

[openshift-resources] support templating from s3 list

---

reconcile/test/utils/test_mr.py
reconcile/utils/mr/base.py
reconcile/utils/mr/promote_qontract.py

Port behavior from qr promotion.
Depends on https://github.com/app-sre/qontract-schemas/pull/701

ping author on schema promotion

---

reconcile/gql_definitions/common/saas_files.gql
reconcile/gql_definitions/common/saas_files.py
reconcile/gql_definitions/introspection.json
reconcile/saas_auto_promotions_manager/publisher.py
reconcile/saas_auto_promotions_manager/s3_exporter.py
reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py
reconcile/test/saas_auto_promotions_manager/conftest.py
reconcile/test/saas_auto_promotions_manager/s3_exporter/conftest.py
reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_saas_files_use_target_config_hash.py
reconcile/test/test_saasherder.py

This reverts commit f7ea837fd99d771cfd8862e3213e387206786593.
https://github.com/app-sre/qontract-reconcile/pull/4626

Revert "APPSRE-7516 saas target re-deploy flag (#4626)"

---

reconcile/gql_definitions/common/clusters_with_peering.gql
reconcile/gql_definitions/common/clusters_with_peering.py
reconcile/gql_definitions/introspection.json
reconcile/terraform_tgw_attachments.py
reconcile/test/test_terraform_tgw_attachments.py
reconcile/utils/terraform_client.py
reconcile/utils/terrascript_aws_client.py

This reverts commit cf78c39d288f63647f4dc657e1821ef509c0d83b / PR #4632
```
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/terraform_client.py", line 345, in log_plan_diff
resource_change["address"],
~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'address'
```
reverting as it is becoming a bit late before the weekend. I have a fix ready for this, but would like to have the time to test a bit more

Revert "APPSRE-10782 support multiple cidr blocks routing to TGW"

---

dockerfiles/Dockerfile
reconcile/external_resources/aws.py
reconcile/external_resources/factories.py
reconcile/external_resources/manager.py
reconcile/external_resources/model.py
reconcile/gql_definitions/external_resources/external_resources_namespaces.gql
reconcile/gql_definitions/external_resources/external_resources_namespaces.py
reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/utils/oc.py

Enable ERv2 support for MSK.
Ticket: [APPSRE-10598](https://issues.redhat.com/browse/APPSRE-10598)

external-resources: MSK ERv2 support

---

reconcile/change_owners/change_log_tracking.py
reconcile/cli.py

part of part of part of https://issues.redhat.com/browse/APPSRE-10755
this PR orders the commits by their order to create a chronological change log.

[change-log] order commits by creation date

---

reconcile/change_owners/change_log_tracking.py

part of part of part of https://issues.redhat.com/browse/APPSRE-10755
if a change is to a cluster, all apps that have namespaces on that cluster are impacted.

[change-log] detect apps by cluster

---

README.md

update m1/m2 to apple silicon to include m3 and any future chips
verified the instructions are applicable to m3

update m1/m2 to apple silicon

---

reconcile/utils/terrascript_aws_client.py

Introduce a function to validate RDS parameter group settings.
Enforce rds.logical_replication apply method to be `pending-reboot`.

APPSRE-10846 validate rds parameter group

---

reconcile/gitlab_housekeeping.py

part of https://issues.redhat.com/browse/APPSRE-10864
the integration sometimes takes a long time to merge a ready MR. let's shard it to improve run time.

[gitlab-housekeeping] support sharding

---

reconcile/utils/saasherder/saasherder.py

Lets make clear what app validation means.

clarify error message

---

reconcile/gitlab_housekeeping.py

Reverts app-sre/qontract-reconcile#4663
Error in my code.

Revert "[gitlab-housekeeping] remove duplicate token expiration metrics"

---

grafana-dashboards/grafana-dashboard-external-resource-log.configmap.yaml
reconcile/external_resources/model.py

- **Add an External resource logs grafana dashboard**

Add External resource logs grafana dashboard

---

reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py

falling back to auto approval by change type
Follow up on https://github.com/app-sre/qontract-reconcile/pull/4671

APPSRE-10875 auto approve

---

reconcile/change_owners/change_log_tracking.py

https://github.com/app-sre/qontract-schemas/blob/d4349be301f929d5bd24f5c60efe52dcbd196017/schemas/dependencies/status-page-component-1.yml#L14

[change-log] detect app in status-page component

---

reconcile/utils/helm.py
reconcile/utils/saasherder/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-10902
this corrects the template behavior to what is expected

[helm/template] proper use of namespace

---

reconcile/utils/git.py
reconcile/utils/helm.py
reconcile/utils/saasherder/saasherder.py

part of https://issues.redhat.com/browse/APPSRE-10884
another attempt at #4677
this time with `git fetch` as well.

[saasherder/helm] support ref

---

reconcile/test/fixtures/openshift_namespace_labels/namespace.yml

fix openshift-namespace-labels tests

---

reconcile/dashdotdb_slo.py

https://issues.redhat.com/browse/APPSRE-10974
Fixes
```
requests.exceptions.InvalidJSONError: Out of range float values are not JSON compliant
```
NaN can happen when the SLO query does a divide by zero. For example:
```
sum(fci_successful_ops_total) / sum(fci_processed_ops_total)
```
and there are no `fci_processed_ops_total`...

fix dashdotdb-slo failures when the detected SLO is not a number

---

tools/qontract_cli.py

[APPSRE-10882](https://issues.redhat.com/browse/APPSRE-10882)
Improves the command by adding a check to see if the destination object already exists and quit if it does unless the user passes a `--force` flag.

[copy_tfstate] add a check for overwriting statefiles

---

reconcile/change_owners/change_log_tracking.py

same for any other object that has an `app` reference

[change-log] app detection for slo-document, scorecard and sre-checkpoint

---

reconcile/external_resources/integration.py
reconcile/external_resources/metrics.py
reconcile/utils/external_resources.py

Erv2: publish external resources inventory metrics 
APPSRE-10975

Erv2: publish inventory metrics

---

reconcile/external_resources/manager.py
reconcile/external_resources/metrics.py
reconcile/external_resources/state.py
reconcile/test/external_resources/test_manager.py

* Add app + environment to metrics. This will enable an improved alert routing 
* Add ReconciliationStatus class to handle reconciliation metrics and flags 
* Some manager refactorings to make the code cleaner.

Erv2: Improve metrics for alerting + some refactors

---

reconcile/dashdotdb_slo.py

fixes
```
File "/usr/local/lib/python3.11/site-packages/reconcile/cli.py", line 609, in run_class_integration
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 158, in run_integration_cfg
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 167, in _integration_wet_run
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/integration.py", line 315, in run
File "/usr/local/lib/python3.11/site-packages/reconcile/dashdotdb_slo.py", line 215, in run
dashdotdb_slo.run()
File …
```

fix a dashdotdb-slo crash when hitting a HTTP error on prom queries

---

reconcile/external_resources/manager.py

Erv2 resource status metric is carried over when a new resource is created. Only the last/current status should be exposed

Use transactional metrics to expose the latest status

---

reconcile/external_resources/model.py

Removed data from app-interface was not getting deleted in the external-resources inventory because the class was using an instance class attribute.

Fix: Use object variable to hold er inventory data

---

reconcile/queries.py

tried typed queries in #4716
no harm in using the old fashion for now.

add queries for schemas

---

reconcile/queries.py
reconcile/terraform_resources.py
reconcile/test/utils/test_terrascript_aws_client.py
reconcile/utils/terrascript_aws_client.py

Reverts app-sre/qontract-reconcile#4746

Revert "Improve terraform-resources provider exclusions"

---

reconcile/gql_definitions/introspection.json
reconcile/queries.py
reconcile/terraform_resources.py
reconcile/test/utils/test_terrascript_aws_client.py
reconcile/utils/terrascript_aws_client.py

Readds #4746 
With the proper schema this shall succeed.

Improve terraform-resources provider exclusions

---

reconcile/gitlab_fork_compliance.py

with this PR, gitlab-fork-compliance only queries app-interface-settings for the vault setting.

[gitlab-fork-compliance] reduce query

---

reconcile/cli.py
reconcile/jira_permissions_validator.py
reconcile/test/test_jira_permissions_validator.py
reconcile/utils/jira_client.py

Refactor error handling. The integration will throw an error during the MR checks for all Jira board issues but will ignore permission errors, issue creation errors and project archived errors in prod runs. 
Ticket: [APPSRE-11118](https://issues.redhat.com/browse/APPSRE-11118)

:bug: archived projects

---

reconcile/external_resources/reconciler.py

During a delete reconciliation run, the `K8sJob` doesn't have access to the `outputs_secrets` global config because it's not persisted in the DynamoDB state; nevertheless a deletion run don't need to run the `outputs-secrets` container at all.

:bug: do not run outputs-secrets container for delete action

---

reconcile/utils/ocm/subscriptions.py
reconcile/utils/ocm_base_client.py

Thanks Gerd for spotting this one :heart: 
~Attempting to set `orderBy: id` as default if no order is given~

orderby to avoid pagination issue

---

reconcile/external_resources/secrets_sync.py

Avoid overriding the stored external resources vault secret by saving them to `external-resources/<CLUSTER_NAME>/<NAMEPSPACE>/<OUTPUT_RESOURCE_NAME>"` instead of `.../<IDENTIFIER>`
Example:
```yaml
- provider: rds
identifier: glitchtip-dev
output_resource_name: glitchtip-rds
...
- provider: elasticache
identifier: glitchtip-dev
output_resource_name: glitchtip-elasticache
...
```

:bug: external-resources: fix vault path

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_repo/terraform_repo.gql
reconcile/gql_definitions/terraform_repo/terraform_repo.py
reconcile/test/test_terraform_repo.py

Related to: [APPSRE-11139](https://issues.redhat.com/browse/APPSRE-11139)
Depends on: https://github.com/app-sre/qontract-schemas/pull/742

Add app to terraform repo query

---

reconcile/test/utils/test_terraform_client.py
reconcile/utils/terraform_client.py

the error now gets swallowed and the pr-check would pass.

fix validate_db_upgrade

---

reconcile/jenkins_webhooks.py
reconcile/test/utils/test_jjb_client.py
reconcile/utils/gitlab_api.py
reconcile/utils/jjb_client.py

As part of APPSRE-11112, we need to create webhook for triggering OnDemand test job with only MR comments

[APPSRE-11112] enable webhook for only MR comments

---

tools/cli_commands/erv2.py
tools/qontract_cli.py

Add a `qontract-cli external-resources debug-shell` command to create and enter an ERv2 debug environment easily, e.g., this could be used to run `terraform` commands manually.
Example usage:
```
$ qontract-cli --config config.prod.toml external-resources --provision-provider aws --provisioner app-sre-stage --provider rds --identifier glitchtip-dev debug-shell
Preparing environment ... 0:00:00
bash-5.1# cdktf synth
...
Generated Terraform code for the stacks: CDKTF
bash-5.1# cd cdktf.out/stacks/CDKTF
bash-5.1# ls -l
total 4
-rw-r--r-- 1 root root 3663 Nov 22 13:01 cdk.tf.json
bash-5.1# terraform init
Initializing the backend...
...
Terraform has been successfully initialized!
bash-5.1# terraform plan
Acquiring state lock. This may take a few moments... …
```

:sparkles: erv2 debug-shell command

---

reconcile/external_resources/manager.py
reconcile/external_resources/metrics.py
reconcile/external_resources/model.py
reconcile/external_resources/state.py
reconcile/test/external_resources/test_manager.py

The state timestamp was updated at every run, causing the drift detection not to trigger.

Fix Erv2 drift detection runs

---

reconcile/openshift_resources_base.py

Exclude external resources optimistic locking data from openshift-vault-secrets

---

reconcile/utils/saasherder/saasherder.py

issue:- https://issues.redhat.com/browse/APPSRE-10991
Image (https://github.com/app-sre/sretoolbox/blob/54d5077072c3bc028fb52fbc2590da83b85d3b5f/sretoolbox/container/image.py#L74) internally implements `__bool__`(https://github.com/app-sre/sretoolbox/blob/54d5077072c3bc028fb52fbc2590da83b85d3b5f/sretoolbox/container/image.py#L630) which checks the manifest for the image. In This PR we use this to verify if image exists

APPSRE-10991:added code to verify image

---

dockerfiles/Dockerfile

prod image: fix helm chart dir

---

Makefile

remove obsolete coverage reports

---

reconcile/external_resources/integration.py
reconcile/external_resources/manager.py
reconcile/external_resources/model.py
reconcile/test/external_resources/test_manager.py

Erv2: Output_resource_names duplications validation

---

reconcile/cli.py

https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/cli.py#L50
Add version 4.16.2

add version of oc being used in fr

---

reconcile/utils/saasherder/saasherder.py

Lets make this error less confusing.

enhance saas error message

---

reconcile/utils/terrascript_aws_client.py

FedRAMP hasn't switched to ERv2 yet.

Revert ":coffin: terraform-resources: remove MSK and ElastiCache"

---

reconcile/external_resources/aws.py
reconcile/external_resources/factories.py
reconcile/external_resources/manager.py
reconcile/test/external_resources/test_rds_factory.py
tools/cli_commands/erv2.py

* Include the module_configuration in the resources resolve and validate methods. 
* Validate RDS timeouts / set default timeouts based on the module spec.

Erv2: Validation improvements

---

pyproject.toml
reconcile/utils/output.py
tools/app_interface_reporter.py
tools/cli_commands/gpg_encrypt.py
tools/cli_commands/test/test_gpg_encrypt.py
tools/qontract_cli.py
tools/test/test_qontract_cli.py
tools/test/test_sd_app_sre_alert_report.py
tools/test/test_sre_checkpoints.py

Add and enable type hints for some `tools`
Ticket: [APPSRE-11458](https://issues.redhat.com/browse/APPSRE-11458)

:label: more type hints

---

tools/qontract_cli.py

:bug: qontract-cli: fix hcp_migration_status command

---

reconcile/utils/terrascript_aws_client.py

Needed as part of FedRAMP HCP buildout in stage and prod.

[FR] [terraform-resources] Add OSDFleetManagerService-scope to rosa-authenticator

---

reconcile/utils/terrascript_aws_client.py

BugFix: Typo in access_logs bucket-policy

---

grafana-dashboards/grafana-dashboard-external-resource-log.configmap.yaml

The log lines are sometimes mixed

External resources logs dashboard: sort log lines

---

reconcile/utils/terrascript_aws_client.py

🐛 remove unused method on access_logs for ALB

---

reconcile/endpoints_discovery/integration.py

:bug: endpoints-discovery: fix for deleted namespaces

---

reconcile/fleet_labeler/integration.py
reconcile/fleet_labeler/merge_request.py
reconcile/test/fleet_labeler/conftest.py
reconcile/test/fleet_labeler/fixtures.py
reconcile/test/fleet_labeler/test_fleet_labeler_cluster_inventory_lifecycle.py
reconcile/test/fleet_labeler/test_fleet_labeler_filters.py

Fix MR paths/branch name
Ran locally without dry-run to test

APPSRE-11390 fix fleet-labeler MR creation

---

reconcile/fleet_labeler/integration.py
reconcile/fleet_labeler/merge_request.py

- Add some info logging to fleet labeler integration in order to properly see changes in MR diffs.
- enhance MR description for cluster lifecycle

APPSRE-11390 fleet-labeler logging and mr description

---

reconcile/test/fixtures/container_images_report/app-sre-observability-stage-namespace.yaml
reconcile/test/fixtures/container_images_report/app-sre-pipelines-namespace.yaml
tools/cli_commands/container_images_report.py
tools/qontract_cli.py
tools/test/test_get_container_images.py

Add apps to the container-images report

---

reconcile/gql_definitions/external_resources/external_resources_namespaces.gql
reconcile/gql_definitions/external_resources/external_resources_namespaces.py
reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/utils/terrascript_aws_client.py

depends on
https://github.com/app-sre/qontract-schemas/pull/775
APPSRE-11566

Add max_session_duration to iam roles

---

reconcile/external_resources/integration_secrets_sync.py

Exclude deleted namespaces on external-resources-secrets-sync integration

---

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py

Missing part to exclude KMS resources from terraform-resources

Fix TFR query to exclude KMS resources

---

reconcile/utils/quay_api.py

I'm not sure if this is a safe implementation.
Context: https://redhat-internal.slack.com/archives/CCRND57FW/p1741609565646869

Revert ":bug: quay-memberships: fix user removal from last team"

---

reconcile/dynatrace_token_provider/dependencies.py
reconcile/dynatrace_token_provider/integration.py

Lets avoid `dependency.populate_all()` and use classmethod creator instead.

APPSRE-11583 DTP cleanup dep creation

---

reconcile/external_resources/aws.py
reconcile/gql_definitions/external_resources/external_resources_namespaces.gql
reconcile/gql_definitions/external_resources/external_resources_namespaces.py
reconcile/gql_definitions/introspection.json
reconcile/test/external_resources/test_rds_factory.py

design [doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/aws-rds-blue-green-deployment-support.md)
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)

ERv2 Blue Green Deployment Input Handling

---

reconcile/fleet_labeler/integration.py
reconcile/fleet_labeler/metrics.py
reconcile/test/fleet_labeler/test_fleet_labeler_metrics.py

Lets expose more metrics about this capability:
- number unique clusters under management
- number of labels under management across all clusters

APPSRE-11583 more fleet labeler metrics

---

dockerfiles/Dockerfile
reconcile/utils/promtool.py

promtool 2.54.1

---

grafana-dashboards/sre-capability-aus.configmap.yaml

https://issues.redhat.com/browse/APPSRE-11646
screenshot available in the Jira ticket

AUS dashboard: add ongoing upgrade durations panels

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql
reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
reconcile/utils/terrascript_aws_client.py

We need ALB health check paths to be configurable.
Schema: https://github.com/app-sre/qontract-schemas/pull/789

APPSRE-11551 add ALB health path

---

reconcile/gql_definitions/external_resources/external_resources_namespaces.gql
reconcile/gql_definitions/external_resources/external_resources_namespaces.py
reconcile/gql_definitions/introspection.json

Depends on https://github.com/app-sre/qontract-schemas/pull/790
Expose `switchover_timeout` to module input.
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)

[ERv2] support switchover_timeout for blue/green deployment

---

reconcile/aws_account_manager/integration.py
reconcile/endpoints_discovery/integration.py
reconcile/terraform_init/integration.py

Leave a comment for us to prevent any future resource file deletions.
Context: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/138279#note_15164508

leave a comment to avoid resource file deletion

---

reconcile/utils/oc.py

`object_clients: dict[Any, Any]` is not threadsafe, use [functools.cache](https://docs.python.org/3/library/functools.html#functools.cache) instead.

fix(oc): threadsafe obj client

---

reconcile/external_resources/integration_secrets_sync.py

Exclude deleted resources from erv2 secrets-sync

---

reconcile/openshift_saas_deploy_trigger_base.py

https://issues.redhat.com/browse/APPSRE-11856
These labels will also be added to subsequent taskruns and pods. It will then allow to select pods per saasfile or env name. It will also appear as log labels in cloudwatch, for better filtering.

add saas-file name and env name as labels in pipelineruns

---

reconcile/gql_definitions/introspection.json
reconcile/gql_definitions/quay_membership/quay_membership.gql
reconcile/gql_definitions/quay_membership/quay_membership.py
reconcile/quay_membership.py
reconcile/test/fixtures/quay_membership/desired_state_simple.yml

depends on https://github.com/app-sre/qontract-schemas/pull/823
this PR adds support to manage quay membership for external users.

[quay-membership] support external users

---

reconcile/external_resources/model.py
reconcile/gql_definitions/external_resources/external_resources_namespaces.gql
reconcile/gql_definitions/external_resources/external_resources_namespaces.py
reconcile/gql_definitions/introspection.json

Add external-resources support for `cloudwatch` 
module: https://github.com/app-sre/er-aws-cloudwatch
* [qontract-schema update](https://github.com/app-sre/qontract-reconcile/pull/4955)

APPSRE-11718 - aws cloudwatch log group er v2 support

---

pyproject.toml
reconcile/utils/dynatrace/client.py
uv.lock

DT lib now has a fix for the date time parsing issue https://github.com/dynatrace-oss/api-client-python/pull/110
After bump we do not need the patch fix anylonger.

APPSRE-11428 bump dt lib

---

reconcile/utils/saasherder/interfaces.py
reconcile/utils/saasherder/saasherder.py

openshift-saas-deploy-trigger-configs should not ignore managedResourceNames change

[APPSRE-11838] fix openshift-saas-deploy-trigger-configs

---

dockerfiles/Dockerfile
reconcile/test/test_amtool.py
reconcile/utils/amtool.py

so that it matches alertmanager in our clusters

Upgrade amtool to 0.28.1

---

reconcile/dashdotdb_dora.py
reconcile/github_repo_permissions_validator.py
reconcile/service_dependencies.py
reconcile/slack_usergroups.py
reconcile/test/utils/vcs/test_vcs.py
reconcile/utils/gitlab_api.py
reconcile/utils/saasherder/saasherder.py
reconcile/utils/terrascript_aws_client.py
reconcile/utils/vcs.py

follow up on https://github.com/app-sre/qontract-reconcile/pull/4993#discussion_r2102062542
Use one util function `parse_repo_url` to avoid repeated checks.
[APPSRE-12038](https://issues.redhat.com/browse/APPSRE-12038)

refactor(vcs): extract parse_repo_url

---

reconcile/utils/aws_api.py
reconcile/utils/terrascript_aws_client.py

account is unhashable type: 'dict'

fix cache for get_alb_network_interface_ips

---

reconcile/automated_actions/config/integration.py
reconcile/gql_definitions/automated_actions/instance.gql
reconcile/gql_definitions/automated_actions/instance.py
reconcile/gql_definitions/introspection.json

…-elasticache actionSupport the `external-resource-flush-elasticache` action
Ticket: [APPSRE-12014](https://issues.redhat.com/browse/APPSRE-12014)

:sparkles: [automated-actions-config] support external-resource-flush-elasticache action

---

reconcile/automated_actions/config/integration.py
reconcile/gql_definitions/automated_actions/instance.gql
reconcile/gql_definitions/automated_actions/instance.py
reconcile/gql_definitions/introspection.json

Support automated-actions RDS snapshot action.
Ticket: [APPSRE-12183](https://issues.redhat.com/browse/APPSRE-12183)

:sparkles: [automated-actions] RDS snapshot action

---

dockerfiles/Dockerfile.konflux

This label is handled by konflux

APPSRE-11020 remove expiry label

---

pyproject.toml
reconcile/aws_saml_roles/integration.py
reconcile/aws_version_sync/integration.py
reconcile/ocm_labels/integration.py
reconcile/rhidp/common.py
reconcile/utils/glitchtip/models.py
reconcile/utils/mr/user_maintenance.py

Configure ruff pep8 checks for pydantic validators instead of ignoring them in the models files.

:rotating_light: pep8 pydantic validators

---

tools/alert_report.py
tools/qontract_cli.py

Add a new column in the report to indicate the percentage of alert notifications that were responded to via threads or emojis.

[APPSRE-12213] add Response Rate for alert report

---

reconcile/test/utils/aws_api_typed/test_aws_api_typed_account.py
reconcile/test/utils/aws_api_typed/test_aws_api_typed_iam.py
reconcile/utils/aws_api_typed/account.py
reconcile/utils/aws_api_typed/iam.py

followup on https://github.com/app-sre/qontract-reconcile/pull/5099
`Code` for access denied exception is `AccessDeniedException`
[APPSRE-12236](https://issues.redhat.com/browse/APPSRE-12236)

fix(aws-account-manager): correctly handle AccessDeniedException

---

reconcile/aws_account_manager/reconciler.py

Use the account name intead of the security team nam

:pencil2: aws-account-manager: fix log message

---

reconcile/automated_actions/config/integration.py
reconcile/gql_definitions/automated_actions/instance.gql
reconcile/gql_definitions/automated_actions/instance.py
reconcile/gql_definitions/introspection.json

Support the `openshift-workload-delete` automated-action argument.
Ticket: [APPSRE-12246](https://issues.redhat.com/browse/APPSRE-12246)

[automated-actions-config] openshift-workload-delete action support

---

dockerfiles/Dockerfile

This reverts commit 56478206579a67ce72b79a13cca74dc1fab32eaa.

Revert "switch to konflux version of qr oc image"

---

pyproject.toml
reconcile/requests_sender.py
reconcile/sendgrid_teammates.py
reconcile/status.py
reconcile/terraform_aws_route53.py
reconcile/terraform_cloudflare_resources.py
reconcile/terraform_users.py
reconcile/test/test_requests_sender.py
reconcile/test/test_terraform_cloudflare_resources.py
reconcile/test/test_terraform_users.py
tools/qontract_cli.py

- **:label: request_sender: type hints**
- **:label: status: type hints**
- **:label: sendgrid-teammates: type hints**
- **:label: terraform_aws_route53: type hints**
- **:label: terraform_cloudflare_resources: type hints**
- **:label: terraform_users: type hints**

:label: qontract reconcile type hints

---

pyproject.toml
reconcile/openshift_base.py
reconcile/openshift_limitranges.py
reconcile/openshift_resources_base.py
reconcile/openshift_tekton_resources.py
reconcile/test/glitchtip/test_glitchtip_project_dsn.py
reconcile/test/skupper_network/test_skupper_network_integration.py
reconcile/test/test_openshift_resource.py
reconcile/test/test_openshift_resources_base.py
reconcile/utils/openshift_resource.py
reconcile/utils/three_way_diff_strategy.py
tools/qontract_cli.py

:label: utils.openshift_resource: type hints

---

build_deploy.sh

Lets make sure we dont push sqs anylonger if we revive ci.ext job

remove sqs

---

dockerfiles/Dockerfile

Include `sloth` binary, added within base images in:
- https://github.com/app-sre/container-images/pull/257
- https://github.com/app-sre/container-images/pull/253
Dependency for https://github.com/app-sre/qontract-reconcile/pull/5153
SDE-4648

Upgrade qr base images

---

.tekton/qontract-reconcile-fips-master-push.yaml
dockerfiles/Dockerfile

Re-introducing this change: https://github.com/app-sre/qontract-reconcile/commit/2bfe95eb2493daa3fe404343976c545f13996c10
Following additional konflux-release-data changes I initially missed: https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/9772

[APPSRE-12264] Create QR-FIPS images w/ Konflux (Try #2)

---

openshift/qontract-manager-fedramp.yaml

Reverts app-sre/qontract-reconcile#5197

Revert "update 'INTEGRATION_EXTRA_ARGS' qr-fips quay-path in qontract-manager-fedramp.yaml"

---

reconcile/aws_ecr_image_pull_secrets.py
reconcile/aws_saml_roles/integration.py
reconcile/change_owners/diff.py
reconcile/cli.py
reconcile/endpoints_discovery/merge_request_manager.py
reconcile/external_resources/model.py
reconcile/external_resources/secrets_sync.py
reconcile/gabi_authorized_users.py
reconcile/gitlab_mr_sqs_consumer.py
reconcile/openshift_cluster_bots.py
reconcile/openshift_saas_deploy.py
reconcile/templating/renderer.py
reconcile/test/utils/test_json.py
reconcile/typed_queries/saas_files.py
reconcile/utils/aggregated_list.py
reconcile/utils/helm.py
reconcile/utils/jjb_client.py
reconcile/utils/json.py
reconcile/utils/mr/base.py
reconcile/utils/oc.py
reconcile/utils/openshift_resource.py
reconcile/utils/output.py
reconcile/utils/saasherder/models.py
reconcile/utils/saasherder/saasherder.py
reconcile/utils/sqs_gateway.py
reconcile/utils/state.py
reconcile/utils/terrascript_aws_client.py

Some integrations are calculating hash of `json.dumps` result, the dict object passed to `json.dumps` may have different key orders, lead to flappy hash changes. This change extracted a common util function `json_dumps` to always sort dict keys, produce consistent json string.
**Core Refactoring: JSON Serialization**
* Replaced all instances of `json.dumps` with the new `json_dumps` function across the codebase, ensuring consistent JSON formatting and options. [[1]](diffhunk://#diff-2acb95cdd7a0a430498f8631afd8f363ffd7992d6c2c9dbbaf9a0c2b3b7c1978L38-R38) [[2]](diffhunk://#diff-f7cabfa1e5dd313115cdbc2a19fc224bd8754579c1d7863901dc870ad5039553L90-R90) [[3]](diffhunk://#diff-44e609414961b0f2e25c4d2cdafe87971023f904b76a19c6cd8a730c14d36255L78-R78) …

feat: consistent json dumps

---

helm/qontract-reconcile/values-manager-fedramp.yaml
openshift/qontract-manager-fedramp.yaml

Follow up to https://github.com/app-sre/qontract-reconcile/pull/5172

enabling helm value for govslack
