reconcile/openshift_resources_base.py
For the dynatrace effort we need labels for `cluster` and `namespace` available in our jinja2 templates, to do things like 
```
{%- set cluster_labels = resource.namespace.cluster.labels | json_to_dict -%}
```
That way we can use labels for configuration w/o schema changes - especially useful during PoC phases
=> APPSRE-7561 pass resource labels to jinja template

reconcile/test/test_utils_aws_helper.py, reconcile/utils/aws_helper.py, reconcile/utils/terrascript_aws_client.py
This allows to not share providers when 2 clusters are running on the same account. This is especially important when different assume role and/or region need to be used.
Note: this will rename all providers and add some. We checked with @maorfr and terraform accepts that without wanting to reapply everything.
The same function `get_alias_name_from_assume_role` is used to set the provider name and reference that provider from resources (as far as we could see).
=> Add the assumed role name into each terraform provider name.

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py
reconcile errors in one organization prevents reconciling to continue for other organizations
this PR catches such unhandled exceptions and summarizes them at the end
https://issues.redhat.com/browse/APPSRE-7835
=> [AUS] handle reconcile errors and continue reconciling

reconcile/cli.py, reconcile/gql_definitions/common/clusters.gql, reconcile/gql_definitions/common/clusters.py, reconcile/ocm_machine_pools.py, reconcile/test/test_ocm_machine_pools.py, reconcile/utils/ocm/ocm.py
Adding Node Pool support to ocm_machine_pools
- Refactoring query, using data class-based Query
- Introduce data classes for handling existing machine/node pools 
- Refactoring calculate_diff to use introduced data classes
- Adding tests 
https://issues.redhat.com/browse/APPSRE-7661
Related schema change: https://github.com/app-sre/qontract-schemas/pull/475
=> ocm machine pools add hypershift support

reconcile/queries.py
Clusters with enabled OIDC authentication use `users.org_username` as the username attribute, which was missing in the gabi instance query.
=> [gabi-authorized-users] add missing users.org_username

reconcile/gitlab_housekeeping.py
with this new label, we can distinguish between self-serviceable and not-self-serviceable MRs.
this will allow us to visualize our self-service frequency, and also to establish internal SLOs for percentage of self-serviceable MRs (if we want).
example of the current metric: https://prometheus.appsrep05ue1.devshift.net/graph?g0.expr=qontract_reconcile_merged_merge_requests_total&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
=> [gitlab-housekeeping] add self-service label to qontract_reconcile_merged_merge_requests counter

tools/qontract_cli.py
A `saas.resource_template.target.parameter` can be a JSON object which can't be rendered in a rich table. Cast all parameters to string.
=> [qontract-cli] fix NotRenderableError on saas-targets subcommand

reconcile/test/fixtures/slack_api/conversations_history_messages.yaml, reconcile/test/test_utils_slack_api.py, reconcile/utils/slack_api.py, tools/qontract_cli.py, tools/sd_app_sre_alert_report.py, tools/test/test_sd_app_sre_alert_report.py
Create a report parsing the output of the conversations.list API
endpoint for our #sd-app-sre-alert channel that can be filtered by days
from the moment that report is run.
We also have explicit timestamp to be able to recreate a certain report
from the past.
This is a `get` qontract-cli command as the rest of the similar reports
we have.
It generates a table with the following colums:
* Alert name
* Triggered
* Resolved
* Median time to resolve
A few comments about the potential scenarios:
* Triggered doesn't need to be equal to resolved, as triggering message
can be outside the considered time window.
* Median time to resolve sometimes cannot be determined as we use alert
messages for that that can contain dynamic parts.
part of APPSRE-7762
Signed-off-by: Rafa Porres Molina …
=> Add alerts report from sd-app-sre-channel

reconcile/change_owners/change_owners.py, reconcile/change_owners/decision.py, reconcile/test/change_owners/test_change_type_decision.py
an eligible auto-approver must be the only approver in ALL eligible approver roles for a specific change.
see decision.py#apply_decisions_to_changes
part of https://issues.redhat.com/browse/APPSRE-7883
=> [change-owners] tighten auto-approval situations

reconcile/gitlab_housekeeping.py
following up on #3612, we want to distinct non self-serviceable MRs from such that are submitted and merged by the bot (`bot/automerge`) in dashboard.
this PR adds an `auto_merge` label to the metric, so we can exclude such MRs.
=> [gitlab-housekeeping] add auto_merge as a label to merge metric

reconcile/rhidp/ocm_oidc_idp/base.py, reconcile/rhidp/ocm_oidc_idp/integration.py, reconcile/rhidp/ocm_oidc_idp/standalone.py, reconcile/rhidp/sso_client/base.py, reconcile/rhidp/sso_client/integration.py, reconcile/rhidp/sso_client/standalone.py
Create unique metric context managers to avoid overriding metrics from another OCM environment.
=> [rhidp] fix metrics

reconcile/rhidp/ocm_oidc_idp/base.py, reconcile/rhidp/ocm_oidc_idp/standalone.py, reconcile/test/rhidp/test_ocm_oidc_idp_base.py
Enable `ocm-oidc-idp-standalone` (OCM labeled clusters) to leave other manually configured IDPs untouched. This doesn't apply to AppInterface managed clusters!
=> [ocm-oidc-idp-standalone] do not delete manually configured IDPs

reconcile/rhidp/common.py, reconcile/rhidp/metrics.py, reconcile/rhidp/ocm_oidc_idp/base.py, reconcile/rhidp/ocm_oidc_idp/integration.py, reconcile/rhidp/ocm_oidc_idp/metrics.py, reconcile/rhidp/ocm_oidc_idp/standalone.py, reconcile/rhidp/sso_client/base.py, reconcile/rhidp/sso_client/integration.py, reconcile/rhidp/sso_client/standalone.py
Add a unique `ocm_environment` label to all metrics to avoid overrides.
=> [rhidp] ocm_environment label

grafana-dashboards/sre-capability-idp.configmap.yaml
First grafana dashboard for the RedHat SSO IDP capability.
See it live at the [stage grafana instance](https://grafana.stage.devshift.net/d/0lZiDarVz/redhat-sso-idp-overview?orgId=1)
=> [rhidp] grafana dashboard

reconcile/test/test_saasherder.py, reconcile/test/utils/test_promotion_state.py, reconcile/typed_queries/saas_files.py, reconcile/utils/promotion_state.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/models.py, reconcile/utils/saasherder/saasherder.py
We need a way to support multiple publishers for a single channel.
We already had multiple attempts on this (https://github.com/app-sre/qontract-reconcile/pull/3521). For that reason we chunk this effort into smaller backwards-compatible PRs. You can regard this PR as a subset of https://github.com/app-sre/qontract-reconcile/pull/3521
This PR introduces a new additional publisher path for promotions in the s3 state: `f"promotions_v2/{channel}/{target_uid}/{sha}"`.
The `target_uid` is a uid based on a hash from unique combination of `(saas_file_name, resource_template_name, namespace, cluster)`. That uid allows us to distinguish between multiple publishers for the same channel.
This PR only handles the publishing aspect and is fully backwards compatible. Follow-up PRs will deal with the …
=> APPSRE-7563 start publishing promotions_v2

reconcile/queries.py, reconcile/utils/aws_api.py, tools/qontract_cli.py
Include CCS/Rosa clusters in `qontract-cli clusters-network`
https://issues.redhat.com/browse/APPSRE-7848
Those clusters don't rely on OCM infrastructure access to retrieve their network info. Instead, we'll use the direct access to their account (no `assume_role`).
=> Clusters-network for CCS/ROSA clusters

reconcile/queries.py, reconcile/utils/aws_api.py, tools/qontract_cli.py
Reverting #3638 as this causes Pydantic issues in OCMSpec:
```
File "/usr/local/lib/python3.9/site-packages/reconcile/cli.py", line 513, in run_class_integration
File "/usr/local/lib/python3.9/site-packages/reconcile/utils/runtime/runner.py", line 158, in run_integration_cfg
File "/usr/local/lib/python3.9/site-packages/reconcile/utils/runtime/runner.py", line 229, in _integration_dry_run
File "/usr/local/lib/python3.9/site-packages/reconcile/utils/runtime/integration.py", line 318, in run
File "/usr/local/lib/python3.9/site-packages/reconcile/ocm_clusters.py", line 302, in run …
```
=> Revert "Clusters-network for CCS/ROSA clusters (#3638)"

reconcile/ocm_clusters.py, reconcile/queries.py, reconcile/utils/aws_api.py, tools/qontract_cli.py
https://issues.redhat.com/browse/APPSRE-7848
New try for #3638, reverted by #3646, adding a fix in the last commit.
Include CCS/Rosa clusters in qontract-cli clusters-network.
Those clusters don't rely on OCM infrastructure access to retrieve their network info. Instead, we'll use the direct access to their account (no assume_role).
=> clusters-network for CCS/ROSA clusters #2

reconcile/utils/aws_api.py
this allows to lookup VPCs for clusters which are not hosted in the default region of the account.
=> fix: use the cluster region when configuring an AWS client without assume_role

reconcile/test/utils/test_promotion_state.py, reconcile/utils/promotion_state.py
`promotion_state` now tries to fetch data from `promotions_v2` path. This is fully backwards-compatible, as saasherder and SAPM are still not passing any `target_uid` to the get call.
This is a follow-up on https://github.com/app-sre/qontract-reconcile/pull/3639
A follow-up PR will adjust saasherder to pass the target_uid and fetch from v2.
Another follow-up PR will adjust SAPM to fetch from v2.
A third final follow-up PR will adjust SAPMs logic to calculate refs/hashes.
=> APPSRE-7307 promotion state get_v2

reconcile/gitlab_housekeeping.py
this is an attempt to be able to visualize the average time it takes to merge a MR per priority.
=> [gitlab-housekeeping] add priority label to time_to_merge histogram

reconcile/change_owners/diff.py, reconcile/test/change_owners/test_change_type_diff.py
field type changes are not reported as proper change, instead they are surfaced as metadata change only (change in SHA for the datafile).
now, type changes are reported as regular changes which can be owned and self-serviced.
https://issues.redhat.com/browse/APPSRE-7934
=> [change-owners] detect field type changes

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/gql_definitions/common/saas_target_namespaces.py, reconcile/gql_definitions/fragments/saas_target_namespace.gql, reconcile/gql_definitions/fragments/saas_target_namespace.py, reconcile/test/fixtures/saasherder/saas.gql.yml, reconcile/test/test_saasherder_allowed_secret_paths.py, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-7939
alternative for #3661
following up on #3485, we no longer need to validate saas file ownership to the user/bot level.
this PR changes the validation so we validate the app file is self-serviceable, as we are going to include the saas file self-service as part of app ownership in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/73509
=> [saas-file-owners] validate saas file app self-service instead of saas file

reconcile/sendgrid_teammates.py
the sendgrid teammates integration run into an API paging issue hiding certain pendinv invites and generating new ones over and over again. for a quick resolution this PR queries the pending invites with a big page of 300 which should resolve the issue for now.
=> sendgrid teammates dirty hack for paging

reconcile/sendgrid_teammates.py
use the proper `limit/offset` combination to page until no new items are returned
=> sendgrid API proper paging for invites and teammates

reconcile/glitchtip/reconciler.py, reconcile/test/fixtures/glitchtip/reconciler/projects/mixed.yml, reconcile/test/fixtures/glitchtip/reconciler/projects/no_desired_projects.yml, reconcile/test/glitchtip/conftest.py, reconcile/test/glitchtip/test_utils_glitchtip_client.py, reconcile/utils/glitchtip/client.py
Fix the deletion of a project together with its related team. The Glitchtip API offers several endpoints for the same operation 🤷, use the team independent to delete a project. 
Ticket: [APPSRE-7871](https://issues.redhat.com/browse/APPSRE-7871)
=> [glitchtip] fix project deletion error

dockerfiles/hack/run-integration.py, helm/README.md, helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-manager-fedramp.yaml, openshift/qontract-manager-fedramp.yaml, reconcile/test/fixtures/helm/enable_google_chat.yml
https://issues.redhat.com/browse/APPSRE-7881
We make use of Fluentd for shipping logs to Cloudwatch, Slack, and Google Chat (within FedRamp). Unfortunately, Google Chat isn't well suited for displaying tons of log messages and the UI performance becomes atrocious if we're shipping every single info message to gchat. So instead, let's just send non-INFO (warning, error) to gchat within FedRamp.
- A new environment variable `PREFIX_LOG_LEVEL`, is set to true which triggers QR to format log messages prefixed with their log level `INFO`, `ERROR`, etc.
- The fluentd config is updated for FedRamp such that [rewrite_tag_filter](https://docs.fluentd.org/output/rewrite_tag_filter) is used to rewrite error and warning log events to `gchat`
- A new `match` statement is added for `gchat`, meaning …
=> Fluentd error log filtering for Google Chat

reconcile/rhidp/common.py, reconcile/test/rhidp/test_common.py
Our OCM implementation needs to have a unique OCM name
=> [rhidp] fix OCM KeyError

reconcile/saas_auto_promotions_manager/publisher.py, reconcile/saas_auto_promotions_manager/subscriber.py, reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py, reconcile/test/saas_auto_promotions_manager/subscriber/conftest.py, reconcile/test/saas_auto_promotions_manager/subscriber/test_multiple_publishers_moving_ref.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_multiple_publishers_for_single_channel.py
Introduce multi-publisher support for moving refs.
This is a follow-up on a range of PRs for this effort:
- https://github.com/app-sre/qontract-reconcile/pull/3651
- https://github.com/app-sre/qontract-reconcile/pull/3650
- https://github.com/app-sre/qontract-reconcile/pull/3639
Note, this does not support target-config-hashes yet. They require introduction of publisher_uid into the hash object. Target-config-hashes are subject to further discussion https://issues.redhat.com/browse/APPSRE-7516
Currently only a small set of saas files rely on target-config-hash (saas files dedicated to tests), i.e., this PR will provide multi-publisher support for majority of saas files.
=> APPSRE-7307 multi-publisher support for SAPM

reconcile/rhidp/sso_client/base.py, reconcile/test/rhidp/test_sso_client_base.py
Rosa clusters use `:433` in the redirect URI which was forgotten in the last bug fix #3674. The CRC is also not displaying the OAuth callback URL correctly 🤦
=> [rhidp] fix idp callback uri for rosa clusters

reconcile/rhidp/common.py, reconcile/rhidp/sso_client/base.py, reconcile/rhidp/sso_client/integration.py, reconcile/test/fixtures/rhidp/clusters.yml, reconcile/test/rhidp/conftest.py, reconcile/test/rhidp/test_ocm_oidc_idp_integration.py, reconcile/test/rhidp/test_sso_client_integration.py
The `rhidp-sso-client` doesn't act on OCM; it just uses the `cluster.ocm.org_id` to store the SSO client data in a unique Vault path. We want to use the app-interface flavor for clusters w/o an OCM relation; all cluster names are unique within an app-interface instance; therefore, we can use a static "fake" ocm org id instead.
Ticket: [APPSRE-7986](https://issues.redhat.com/browse/APPSRE-7986)
=> [rhidp-sso-client] do not depend on cluster OCM relation

helm/qontract-reconcile/templates/template.yaml, reconcile/gql_definitions/integrations/integrations.gql, reconcile/gql_definitions/integrations/integrations.py, reconcile/integrations_manager.py, reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml, reconcile/test/test_integrations_manager.py, reconcile/test/test_utils_helm.py
This fix addresses a bug where the `shardSpecOverride.imageRef` is not picked up to as the image for a shard. The main problem is that the helm template uses AWSShardSpecOverride.image_ref attribute instead of the alias `imageRef`. 
This change also includes a refactor over all the helm tests using the generated pedantic classes instead of dictionaries. This issue was not caught in the tests because of that. 
APPSRE-7982
=> Fix: ShardSpecOverrides do not pick the imageRef

reconcile/test/utils/test_promotion_state.py, reconcile/utils/promotion_state.py
Our promotions do not rely on the v1 path any longer:
- https://github.com/app-sre/qontract-reconcile/pull/3650
- https://github.com/app-sre/qontract-reconcile/pull/3653
This PR stops publishing promotions to our v1 path.
=> APPSRE-7307 remove publish promotion_v1

reconcile/aus/base.py, reconcile/utils/ocm/ocm.py
Make it possible to filter returned addons by state. Add filter to aus addon upgrade scheduler
Fixes bug: https://issues.redhat.com/browse/APPSRE-8011
=> Add filter option to get_cluster_addons

reconcile/terraform_repo.py
Through usage in FedRamp, this error message can appear if a tenant hasn't rebased their merge request, leading their MR to appear as if multiple repos are going to be modified when in fact only one is.
=> [tf-repo] update error message to be more descriptive

reconcile/ocm/types.py, reconcile/ocm_clusters.py, reconcile/test/test_ocm_clusters.py, reconcile/utils/ocm/ocm.py
This PR adds "read" support for non-sts ROSA clusters (clusters w/o an `aws.sts` attribute). No support for the creation of non-sts rosa clusters! Basically, it makes all arns in the `sts` attribute optional.
Ticket: [APPSRE-8040](https://issues.redhat.com/browse/APPSRE-8040)
=> [ocm] basic support for rosa non-sts clusters

reconcile/utils/terrascript_aws_client.py
Our current AWS terraform provider doesn't support `ap-southeast-4` yet, use `skip_region_validation` to bypass validation.
https://github.com/hashicorp/terraform-provider-aws/issues/29231
[APPSRE-8071](https://issues.redhat.com/browse/APPSRE-8071)
=> Set skip_region_validation to work with not supported regions

requirements/requirements-test.txt
Found, that pip will download every minor version to determine fitting version. This drasticaly slows down builds. Pin version to same as in setup.py to speed up builds
=> Pin botocore to same version as in setup.py

tools/qontract_cli.py
follow up fix of https://github.com/app-sre/qontract-reconcile/pull/3711#discussion_r1280907271
=> fix get labels for app_interface_merge_queue

reconcile/utils/ocm/upgrades.py
```
qontract-reconcile-ocm-addons-upgrade-scheduler-org Traceback (most recent call last):
qontract-reconcile-ocm-addons-upgrade-scheduler-org   File "/usr/local/lib/python3.11/site-packages/reconcile/cli.py", line 514, in run_class_integration
qontract-reconcile-ocm-addons-upgrade-scheduler-org     run_integration_cfg(
qontract-reconcile-ocm-addons-upgrade-scheduler-org   File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 161, in run_integration_cfg
qontract-reconcile-ocm-addons-upgrade-scheduler-org     _integration_wet_run(run_cfg.integration)
qontract-reconcile-ocm-addons-upgrade-scheduler-org   File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 170, in _integration_wet_run …
```
=> fix missing slash in url

reconcile/aus/base.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/utils/ocm_base_client.py
due to a bug, the current state for addon upgrade policies had duplicates, which then failed duplicate check during reconciling.
also use the correct service account for addon related work - the one on the org if it exists and only if not the one from the env
=> [AUS] fix addon spec duplication error + use correct SA

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/models.py, reconcile/gql_definitions/advanced_upgrade_service/aus_clusters.py, reconcile/gql_definitions/advanced_upgrade_service/aus_organization.py, reconcile/gql_definitions/common/clusters.py, reconcile/gql_definitions/fragments/upgrade_policy.gql, reconcile/gql_definitions/fragments/upgrade_policy.py, reconcile/gql_definitions/rhidp/clusters.py, reconcile/test/fixtures/oc_connection_parameters/cluster_custom_token.yml, reconcile/test/fixtures/oc_connection_parameters/cluster_no_jumphost.yml, reconcile/test/fixtures/oc_connection_parameters/cluster_with_jumphost.yml, reconcile/test/fixtures/openshift_upgrade_watcher/cluster1.yml, reconcile/test/ocm/aus/fixtures.py, reconcile/test/ocm/aus/test_base.py
add support to block versions on cluster level
part of https://issues.redhat.com/browse/APPSRE-7870
depends on https://github.com/app-sre/qontract-schemas/pull/479
=> [AUS] cluster level blocked versions

reconcile/aws_cloudwatch_log_retention/integration.py
Follow up to https://github.com/app-sre/qontract-reconcile/pull/3587
The retention day condition is currently sitting outside of the regex log name match condition and so the regex logic is not functioning as intended.
Part of [APPSRE-7249]( https://issues.redhat.com/browse/APPSRE-7249)
=> Move condition inside matching log group regex name

reconcile/aws_cloudwatch_log_retention/integration.py
Whenever a user pushes a log retention value, the following shows up in the integration pod:
```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter retentionInDays, value: 365, type: <class 'str'>, valid types: <class 'int'>
```
This PR fixes the var type as well as fixes the logic to implement integration tagging.
=> Fixing conditional logic and var type in log retention integration

reconcile/aws_cloudwatch_log_retention/integration.py
The condition to compare the log retention value in AWS and what is set in app-interface is not working as expected. This PR will fix that conditional so log retentions that are set in app-interface won't continuously reset and reconcile like that.
Part of [APPSRE-7249](https://issues.redhat.com/browse/APPSRE-7249)
=> Fixing compare block to better check log retention day amount set

reconcile/aws_ami_cleanup/integration.py
https://github.com/app-sre/qontract-reconcile/pull/3587 introduces a change to the AWS query:
```
cleanup {
provider
... on AWSAccountCleanupOptionCloudWatch_v1 {
regex
retention_in_days
}
... on AWSAccountCleanupOptionAMI_v1 {
regex
age
region
}
}
```
The AMI cleaner only checks for any cleanup entry, thus also taking cloudwatch entries into account. We need to properly distinguish between the 2.
**Test**
Ran locally
```
qd profile run prod aws-ami-cleanup
```
=> APPSRE-8127 fix ami cleaner

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py, reconcile/aus/models.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, reconcile/utils/ocm/ocm.py
introduce two new organizations labels to describe publish/inherit intent for version data between organizations.
```
sre-capability.aus.version-data.inherit: CSV of org IDs to inherit version data from
sre-capability.aus.version-data.publish: CSV of org IDs to publish version data to
```
if an inherit label is not accompanied with a publish label on the other side, the organization trying to inherit is in error mode and a service log is published for each cluster with an upgrade policy in the inheriting org
part of https://issues.redhat.com/browse/APPSRE-7838
=> [AUS] inherit version data feature for label based AUS

reconcile/utils/ocm/ocm.py
filter for `managed` clusters and filtering on the `product` (OSD/ROSA/Hypershift) is now done as part of the CS request instead of filtering the raw result afterwards. this reduces the number of queries a lot in big organizations with clusters that dod not fit those filters.
filtering for state `ready` is still on the raw result because certain code relies on knowing about non-ready clusters. we can reconsider this in a later PR.
part of https://issues.redhat.com/browse/APPSRE-8152
=> [ocmmap] basic cluster filtering during CS request

reconcile/utils/glitchtip/client.py
Deleting Glitchtip resources (projects, teams, ...) is a synchronous API call. When deleting a project with many issues/events, this API call easily exceeds the default 30 seconds timeout.
=> disable timeout for glitchtip client DELETE requests

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager.yaml, reconcile/test/fixtures/helm/aws_account_shard_disabled.yml, reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml, reconcile/test/fixtures/helm/aws_account_shards.yml, reconcile/test/fixtures/helm/basic.yml, reconcile/test/fixtures/helm/cache.yml, reconcile/test/fixtures/helm/command.yml, reconcile/test/fixtures/helm/concurrency_policy.yml, reconcile/test/fixtures/helm/cron.yml, reconcile/test/fixtures/helm/dashdotdb.yml, reconcile/test/fixtures/helm/enable_google_chat.yml, reconcile/test/fixtures/helm/enable_pushgateway.yml, reconcile/test/fixtures/helm/environment_aware.yml, reconcile/test/fixtures/helm/exclude_service.yml, reconcile/test/fixtures/helm/extra_args.yml, reconcile/test/fixtures/helm/extra_env.yml, reconcile/test/fixtures/helm/failure_history.yml, reconcile/test/fixtures/helm/integrations_manager.yml, reconcile/test/fixtures/helm/internal_certificates.yml, reconcile/test/fixtures/helm/logs_slack.yml, reconcile/test/fixtures/helm/restart_policy.yml, reconcile/test/fixtures/helm/shards.yml, reconcile/test/fixtures/helm/sleep_duration.yml, reconcile/test/fixtures/helm/state.yml, reconcile/test/fixtures/helm/storage.yml, reconcile/test/fixtures/helm/success_history.yml, reconcile/test/fixtures/helm/trigger.yml
to run an integrationsmanager without unleash interaction, we make the unleash secretKeyRef in the template optional. a missing unleash secret in the namespace will then disable the unleash feature for the integrations-manager.
part of https://issues.redhat.com/browse/APPSRE-8161
=> integration-manager template optional unleash secret

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_tekton_resources.py
[APPSRE-8164](https://issues.redhat.com/browse/APPSRE-8164)
PipelineRun `.spec.timeout` is [deprecated](https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout) and replaced by `.spec.timeouts`: 
> ⚠️ ** timeout is deprecated and will be removed in future versions. Consider using timeouts instead.
In this new field:
* `.spec.timeouts.tasks` sets the timeout globally for all tasks in the pipeline.
* `.spec.timeouts.pipeline` needs to be greater or equal to `.spec.timeouts.tasks + .spec.timeouts.finally`.
So we set `.spec.timeouts.pipeline = 0` and `.spec.timeouts.tasks = ${saas-file-timeout}`, allowing tasks to benefit from that timeout, and all finally tasks to run successfuly, even in case of timeout.
However, that is not sufficient. If we only set values in …
=> APPSRE-8164 set tekton taskrun timeouts according to saas files settings

reconcile/cli.py, reconcile/utils/gql.py, tools/qontract_cli.py
Adding a session to the GQL transport adapter. Allows reusing HTTP sessions. Adding a session cache to clean up sessions after an integration run.
Tested locally against qontract-server on appsrep05 showed around 20% improvement for a shared openshift-resources run.
[APPSRE-5616](https://issues.redhat.com/browse/APPSRE-5616)
=> Use a sticky session for GQL requests

reconcile/aus/ocm_upgrade_scheduler.py
if creds are available on an OCM organization, prefer them over the ones from the environment.
mitigates https://issues.redhat.com/browse/APPSRE-8162
=> [ocm-upgrade-scheduler] use the org creds for OCM interaction if available

reconcile/dashdotdb_slo.py, reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.gql, reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.py, reconcile/gql_definitions/introspection.json
Update DashdotSLO, and allow it to use an external reference for getting SLO data from Prometheus.
Related schema change: https://github.com/app-sre/qontract-schemas/pull/501
https://issues.redhat.com/browse/APPSRE-8197
=> Update DashdotSLO, allow configuration of external reference

reconcile/utils/helm.py
Revert changes in https://github.com/app-sre/qontract-reconcile/pull/3750/files#diff-b1dab64139515cc76cf5052912473f2813d58c19c3dd54cac4e718fb7318b637,
`./helm/qontract-reconcile` is outside of package, so path won't be the same as local run, error in pipeline
```
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/helm.py", line 42, in template
result = run(cmd, capture_output=True, check=True, cwd=cwd)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/subprocess.py", line 571, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['helm', 'template', './helm/qontract-reconcile', '-n', 'qontract-reconcile', '-f', '/tmp/tmp0aohl31b']' returned non-zero exit status 1.
During …
```
=> Revert changes to helm template run

reconcile/aus/ocm_addons_upgrade_scheduler_org.py
We are currently considering all addons to compute addon-specific version data stats.
This means we end up with cert-manager version as a minimum version for acm version data.
=> APPSRE-8218 fix addon upgrade

reconcile/openshift_tekton_resources.py, reconcile/test/utils/test_parse_dhms_duration.py, reconcile/utils/parse_dhms_duration.py
https://issues.redhat.com/browse/APPSRE-8219
We can define a pipeline timeout with any Golang accepted duration format.
However tekton will update the Pipeline specs with timeouts following the default format XhYmZs. For example, 90m gets updated as 1h30m0s.
To avoid continuous reconciliation due to this discrepency, we need to set the timeout value with the default Golang format
=> APPSRE-8219 normalize tekton pipeline timeout format

tools/qontract_cli.py
a bug prevented the display of ongoing cluster upgrades
=> fix soakday str on a-i output reports

tools/qontract_cli.py
clusters-network report is broken for ROSA clusters that define `awsInfrastructureManagementAccounts`. This patch fixes it while APPSRE-8224 is addressed.
=> Fix clusters-network report for ROSA clusters

tools/qontract_cli.py
We need to use the cluster id instead of the cluster name
=> fix qontract-cli upgrade-cluster-addon 

reconcile/rhidp/common.py
The integration can only calculate the redirect URL with a cluster console URL. Otherwise skip the cluster.
=> [rhidp app-interface flavor] skip cluster with an empyt console url

dev/run.sh, dockerfiles/Dockerfile
Install debug requirements in the dev image instead of installing them at startup. This will speed up the startup of the local development container a little bit.
=> [dev-image] install debugger

reconcile/test/ldap_groups/test_ldap_groups_integration.py, reconcile/test/utils/internal_groups/test_internal_groups_models.py, reconcile/utils/internal_groups/models.py
Deleted LDAP users are flagged as type `deleteduser`. Do not use the entity type to compare the member lists.
Ticket: [APPSRE-8259](https://issues.redhat.com/browse/APPSRE-8259)
=> [ldap-groups] ignore "deleted users"

reconcile/test/utils/test_terrascript_cloudflare_client.py, reconcile/utils/terrascript/cloudflare_resources.py
We need to use `safe_resource_id` in the terraform resource identifier because zone can contain dots for e.g `stage.quay.io`
=> Fix cloudflare logpush/logpull data lookup identifier

reconcile/test/utils/test_keycloak.py, reconcile/utils/keycloak.py, tools/qontract_cli.py
Create/Remove SSO clients via `qontract-cli`.
Ticket: [APPSRE-8203](https://issues.redhat.com/browse/APPSRE-8203)
```
$ qontract-cli --config $CONFIG sso-client create --help                                                                                                         
Usage: qontract-cli sso-client create [OPTIONS] CLIENT_NAME
Create a new SSO client
Options:
--contact-email TEXT            Specify the contact email address  [default:
sd-app-sre+auth@redhat.com; required]
--keycloak-instance-vault-path TEXT
Path to the keycloak secret in vault
[default: app-
sre/creds/rhidp/auth.redhat.com; required]
--request-uri TEXT              Specify an allowed request URL; first one
will be used as the initial one URL. Can be
specified multiple times  [required]
--redirect-uri TEXT …
```
=> [qontract-cli] sso-client management command

reconcile/jenkins_job_cleaner.py, reconcile/utils/jjb_client.py
fix https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/79861
test job is for filter [centos](https://github.com/app-sre/qontract-reconcile/pull/479) Jenkins instance which has gone. 
openshift-saas-deploy jobs also have been removed. 
jenkins-job-cleaer is not running.
=> remove unused job filter

reconcile/glitchtip_project_alerts/integration.py, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.gql, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.py, reconcile/gql_definitions/introspection.json, reconcile/test/fixtures/glitchtip/project_alerts.yml, reconcile/test/glitchtip/test_glitchtip_project_alerts.py
A webhook URL may contain credentials, e.g. slack webhooks. Add an `urlSecret` attribute to retrieve a URL via Vault as well.
Depends on: https://github.com/app-sre/qontract-schemas/pull/514
Ticket: [[glitchtip project-alerts] Webhook URL from vault](https://issues.redhat.com/browse/APPSRE-8288)
=> [glitchtip-project-alerts] add urlSecret attribute

reconcile/openshift_base.py, reconcile/test/fixtures/openshift_resource/deployment.yml, reconcile/test/test_gabi_authorized_users.py, reconcile/test/test_openshift_base.py, reconcile/test/test_openshift_resource.py, reconcile/test/test_unleash.py, reconcile/utils/openshift_resource.py, reconcile/utils/unleash.py, setup.py
This PR changes the way Openshift objects are compared to know if they need to be applied or not. This change affects multiple integrations, like all openshift-related integrations and terraform-resources. 
Currently, QR uses a custom method to compare objects which sometimes is not accurate. For example, removing an annotation from an object is not detected, non-expected attributes in desired objects that are removed by the API server are not detected, etc. 
This PR introduces a 3-way merge strategy to compare objects. 
* The Original object is represented by the QR hash. It's the last Desired state that was applied 
* The last comparison is made for the desired object attributes only. Changes introduced by operators or other stuff are not considered.
* A feature toggle to use this …
=> Introduce 3way Merge diff for openshift resources

reconcile/openshift_saas_deploy_change_tester.py
following https://github.com/app-sre/qontract-reconcile/commit/d9f735da22d76d2e40df0945c93eed857e238ac1
gitlab_project_id is unused anymore https://github.com/app-sre/qontract-reconcile/pull/3650
=> remove gitlab_project_id in osd_run_wrapper

reconcile/gql_definitions/terraform_repo/terraform_repo.gql, reconcile/gql_definitions/terraform_repo/terraform_repo.py, reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
[APPSRE-8242](https://issues.redhat.com/browse/APPSRE-8242)
Allows Terraform Repo to work with [terraform-state-1.yml](https://github.com/app-sre/qontract-schemas/blob/main/schemas/dependencies/terraform-state-1.yml) files. terraform-state files are separate from the actual Terraform state and allow you to specify where state files for specific AppSRE integrations are stored within AWS rather than relying on hard-coded paths and Vault secret values. This is a key step to getting terraform-repo in commercial.
Here's what a terraform state file would look like for Terraform Repo:
```
$schema: /dependencies/terraform-state-1.yml
provider: s3
bucket: tf-state
region: us-east-1 
integrations:
- integration: terraform-repo
key: tf-repo
```
So then, if you created a terraform repo named …
=>  terraform-state-1.yml support for Terraform Repo #3766 

reconcile/openshift_tekton_resources.py
Since the removal of the cpu limit, the Desired object is built with `{ "limits": {"cpu": None}}}`. This PR gets rid of the None values in these resources.
=> Remove None values from openshift-tekton-resources deploy_resources

reconcile/skupper_network/integration.py
The integration is getting `Role.authorization.openshift.io` Roles as current resources (default roles in Openshift 4.x) but it expects `Role.rbac.authorization.k8s.io`. Using full resource names ensures the integration is using the same resources
=> Skupper-network: Use full resource names

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/changes.py, reconcile/change_owners/self_service_roles.py, reconcile/gql_definitions/change_owners/queries/self_service_roles.gql, reconcile/gql_definitions/change_owners/queries/self_service_roles.py, reconcile/test/change_owners/fixtures.py, reconcile/test/change_owners/test_change_type_self_service_roles.py, reconcile/test/change_owners/test_change_type_various.py, reconcile/utils/mr/labels.py, tools/qontract_cli.py
self-serviceable MRs intentionally do not show up in the review queue. but if an MR is self-serviceable and the approvers are AppSRE, we would still love to see such MRs in the review queue, so IC is aware and can review and approve.
to fix this we will:
* include MRs with the label "change-owner/show-self-serviceable-in-review-queue" in the review-queue, regardless of its self-serviceable state
* change-owners will apply additional labels to MRs based on the "change-owners-label" label of the involved self-service roles (prefixing them with `change-owners` to ensure uniqueness and avoid conflict)
E.g. if the following role is approver on an MR, the `change-owner/show-self-serviceable-in-review-queue` label will be added the the MR.
```yaml
---
$schema: /access/role-1.yml
labels: …
```
=> [change-owners] place change-owners role labels from self-service roles on MRs

reconcile/cli.py, reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
When trying to update terraform-repo in FedRamp where there are a number of different statefiles already saved in S3, I ran into many validation errors:
```
[2023-09-15 14:37:43] [ERROR] [DRY-RUN] [terraform_repo.py:get_existing_state:184] - 1 validation error for TerraformRepoV1
account -> terraformState
field required (type=value_error.missing)
Unable to parse existing state for repo: '/app-sre-base-networking', skipping
```
This is due to the updates to the GQL syntax updates done in a previous MR: https://github.com/app-sre/qontract-reconcile/pull/3777/files#diff-07306e78e084b1597025733d9c9787506f617028ba6ebe1cb240937c39ed8f34R11
It seems that Pydantic expects the terraformState attribute to be defined, just as `null` so it's unable to parse. To fix this, I've added a CLI flag to the …
=> [terraform-repo] option to ignore statefile loading errors

grafana-dashboards/sre-capability-aus.configmap.yaml, reconcile/aus/base.py, reconcile/aus/metrics.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/utils/ocm/upgrades.py
we lack upcoming and ongoing upgrade information on the AUS dashboards.
this patch encodes such data as negative values in the `aus_cluster_version_remaining_soak_days` metric. this is safe since the metric currently has a min value of 0.
we will use
* -1 for scheduled upgrades (upgrade policy created in OCM)
* -2 for started/ongoing upgrades.
the dashboard tile for "currently soaking" has been adapted to deal with negative numbers (ignore them) and the matrix now shows the well known icons for ready, scheduled and ongoing.
part of https://issues.redhat.com/browse/APPSRE-7878
additionally the channel group of a cluster is exposed in the AUS info metric for dashboarding purposes.
part of https://issues.redhat.com/browse/APPSRE-7877
=> expose cluster upgrade state via metrics

reconcile/gabi_authorized_users.py
part of https://issues.redhat.com/browse/APPSRE-8298
the origin of the 90 days limitation is unclear.
design doc: https://docs.google.com/document/d/1rQBCGFy2rc6A9RdeqOkTEXsr0kZlRwXTer5qarabjbA
extending this to 1 year, as even compliance training are only done once per year.
we can argue over making this number parameterized, but i don't think it is worth the effort.
=> extend gabi expiration max days to 365 days

reconcile/utils/output.py
Escape `|` in markdown table cells to avoid badly formatted tables.
=> [utils.output] escape md pipe char

reconcile/utils/output.py
Reverts app-sre/qontract-reconcile#3804
```
[2023-09-19 08:12:59] [INFO] [DRY-RUN] [change_owners.py:run:253] - running in `limited` mode that prevents full self-service MR 81094 contains changes other than datafiles, resources, docs or testdata
[2023-09-19 08:13:03] [INFO] [DRY-RUN] [change_owners.py:run:286] - fetching change types and permissions from comparison bundle (sha=c9dad9d48217430e9663f9ecbd03ad7bebd70b25bb312842a1a307e5a82be30b, commit_id=5d3b60e70ffa5e47b62146d2470e1d0aaab7b97a, build_time 2023-09-19T08:10:29+00:00)
[2023-09-19 08:13:04] [INFO] [DRY-RUN] [change_owners.py:run:302] - detected 4 changed files with 4 differences and 0 metadata-only changes
[2023-09-19 08:13:29] [ERROR] [DRY-RUN] [change_owners.py:run:398] - Traceback (most recent call last):
File …
```
=> Revert "[utils.output] escape md pipe char"

reconcile/aus/advanced_upgrade_service.py
errors identified on the organization level are published as service logs but are not deduped as of now. this results in new service logs to be generated during each reconcile loop, even though it is the same error every time.
the dedup feature prevents that. such org level errors will be reraised once per day, should they persist.
part of APPSRE-7838 (since such service logs were introduced with version data inheritance)
=> [AUS] dedup organization error service logs

reconcile/change_owners/change_owners.py, reconcile/change_owners/self_service_roles.py, reconcile/test/change_owners/test_change_type_self_service_roles.py
due to a bug, empty `change-owner/` labels were added to MRs
followup to https://github.com/app-sre/qontract-reconcile/pull/3796 part of https://issues.redhat.com/browse/APPSRE-8322
=> [change-owners] don't add empty change-owner/ labels

reconcile/openshift_base.py, reconcile/test/fixtures/openshift_resource/deployment.yml, reconcile/test/test_openshift_resource.py, reconcile/test/test_three_way_diff_strategy.py, reconcile/utils/three_way_diff_strategy.py, setup.py
* Code reorg: 3-way diff strategy code + tests have been moved to their own files 
* Added an extensible logic to control object mutations. 
* For now, only cpu mutations are checked. K8s mutates cpu values. e.g: "1000m" becomes "1"
=> Introduce mutation controls to the 3way-diff strategy

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/test/test_openshift_saas_deploy.py, reconcile/test/test_saasherder_allowed_secret_paths.py, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/typed_queries/saas_files.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/models.py, reconcile/utils/saasherder/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-4355
in this PR we leverage the `managedResourceNames` field in saas files (currently unused) to create an experience similar to using that field in namespace files. we override that field of the namespace with the same field coming from the saas file (like we do for `managedResourceTypes`) and let the core openshift_base logic take over.
this is basically sufficient and will create an identical experience to namespace files - an exception and failure in case a desired item is not defined in `managedResourceNames`.
in saas files, differently, we want to allow the openshift template to contain other resources, and simply filter them. for that, we except `ResourceNotManagedError`. the approach of excepting and handling the error out of the …
=> Allow restricting resources by name in saas files

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
Ticket: https://issues.redhat.com/browse/APPSRE-8351
A GQL change broke the `event_notifications` functionality of S3 buckets due to an alias being used in GQL. This MR removes that alias and adds a test for this functionality specifically for sending notifications to SQS from S3.
I also ran QR locally against App Interface production and noted that the output indicates that the bucket notification objects are being created now.
```
[2023-09-20 09:27:11] [INFO] [DRY-RUN] [terraform_client.py:log_plan_diff:332] - ['create', 'app-sre-stage', 'aws_s3_bucket_notification', 'a-stage-event-notifications', set()]
[2023-09-20 09:27:11] [INFO] [DRY-RUN] [terraform_client.py:log_plan_diff:332] - ['create', 'app-sre-stage', 'aws_s3_bucket_notification', 'b-stage-event-notifications', set()]
``` …
=> Fix S3 -> SQS Notifications

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/test/utils/test_terrascript_aws_client.py
Ticket: https://issues.redhat.com/browse/APPSRE-8351
A GQL change broke the event_notifications functionality of S3 buckets due to an alias being used in GQL. This MR removes that alias and adds a test for this functionality specifically for sending notifications to SQS from S3.
I also ran QR locally against App Interface production and noted that the output indicates that the bucket notification objects are being created now.
[2023-09-20 09:27:11] [INFO] [DRY-RUN] [terraform_client.py:log_plan_diff:332] - ['create', 'app-sre-stage', 'aws_s3_bucket_notification', 'a-stage-event-notifications', set()]
[2023-09-20 09:27:11] [INFO] [DRY-RUN] [terraform_client.py:log_plan_diff:332] - ['create', 'app-sre-stage', 'aws_s3_bucket_notification', 'b-stage-event-notifications', set()]
Slack …
=> Fix S3 -> SQS Notifications 

dockerfiles/Dockerfile, dockerfiles/Dockerfile.publish-release, dockerfiles/Dockerfile.test
Bump version for container images, changes in https://github.com/app-sre/container-images/pull/88, this is to support https://github.com/app-sre/qontract-reconcile/pull/3793.
=> Bump versions for container images

README.md, reconcile/cli.py, reconcile/dashdotdb_base.py, reconcile/dashdotdb_dora.py, reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/test/test_dashdotdb_dora.py, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/typed_queries/saas_files.py, reconcile/utils/github_api.py, reconcile/utils/gitlab_api.py, reconcile/utils/saasherder/interfaces.py, requirements/requirements-type.txt, setup.py
As part of the Services Dashboard effort, the DORA LTTC (lead time to change metrics) must be collected.
Definitions:
- `app_name` is the value of `.name` in the saas-file.
- `env_name` is the value of a given `.resourceTemplates.targets.namespace.$ref -> ns file -> environment file -> .name`.
- `trigger_reason` is one of the fields registered in DeploymentDB that identifies the promotion event. It looks like: `https://gitlab.../service/app-interface/commit/<sha>`.
- `promotion_sha` is the `sha` contained in the `trigger_reason`.
The purpose of this MR is to add a new DashdotDB collector that does the following:
* Get a list of saasfiles that contain the `dora` field in its `labels`. The value is a comma-separated list of target `env_name`s. Relevant …
=> DORA LTTC collector

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/test/utils/test_terrascript_aws_client.py
Un-revert the revert...
Brings back this change: https://github.com/app-sre/qontract-reconcile/pull/3818
After some further discussion, the code is sound however the errors that showed up in App Interface were due to a tenant specifying multiple destionations for an event notification. See the AWS docs here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html
My plan is to re-introduce this fix into QR and remove one of the tenant's queues as well as update our README docs to inform tenants of this limitation. It's not very feasible to validate this limitation at `plan` time.
=> Bring back S3 -> SQS Notifications MR

README.md
Update README for new dependencies for `psycopg2` setup, also includes existing runtime tools needed.
=> Update installation doc

reconcile/dynatrace_token_provider.py
Currently the Secret is being created by cronjob [here](https://gitlab.cee.redhat.com/service/dynatrace-config/-/blob/main/resources/dynatrace-cluster-bootstrap/files/10-CronJob.yaml#L229) so dtp need to create the same json structure so it is consumable.
1. No syncset with defined name exist, was able to see syncset with following structure created:
```
{
"kind": "Syncset",
"href": "/api/clusters_mgmt/v1/clusters/abc/external_configuration/syncsets/ext-dynatrace-tokens-test",
"id": "ext-dynatrace-tokens-test",
"resources": [
{
"data": {
"apiUrl": "https://ddl70254.live.dynatrace.com",
"apiToken": "dt0c01.X",
"apiTokenId": "dt0c01.XID",
"dataIngestToken": "dt0c01.Y",
"dataIngestTokenId": "YID"
},
"kind": "Secret",
"metadata": {
"name": "dynatrace-token-dtp"
},
"apiVersion": "v1"
}
]
}
``` …
=> [dynatrace-token-provider]Correct the Secret content

reconcile/openshift_namespaces.py, reconcile/test/oc/test_oc_filters.py, reconcile/utils/oc_filters.py, setup.cfg
They're currently broken because cli.py passes a tuple from `--cluster-name` and `--namespace-name` options. Since this is something that is taken into consideration by other integrations, this patch changes the interface of `filter_namespaces_by_cluster_and_namespace` as it is only currently used by `openshift-namespaces`.
=> Fix openshift-namespaces cluster and namespace options

reconcile/openshift_resources_base.py, reconcile/utils/openshift_resource.py
As there are cases where empty data entries in Secrets are needed, let's handle all of the options the same way. 
Context:
* https://issues.redhat.com/browse/APPSRE-1448 
* https://github.com/app-sre/qontract-reconcile/pull/1144
=> Vault-secrets empty values are not populated

reconcile/openshift_saas_deploy.py, reconcile/openshift_saas_deploy_change_tester.py, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/typed_queries/saas_files.py
related to https://issues.redhat.com/browse/APPSRE-8352
it was observed that runs of the integration were taking a long time. by re-using the results of the first `get_saas_files` call we avoid multiple processing of dynamic namespace selectors.
=> [openshift-saas-deploy-change-tester] re-use get_saas_files

dockerfiles/hack/run-integration.py
```
/run-integration.py:126: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
ep.name: ep for ep in metadata.entry_points()["console_scripts"]
```
=> get rid of the deprecation metadatalib warning when running an integration

reconcile/jenkins/types.py, reconcile/jenkins_worker_fleets.py, reconcile/queries.py, reconcile/test/fixtures/jenkins_worker_fleets/gql-queries.yml, reconcile/test/fixtures/jenkins_worker_fleets/jcasc-apply.yml, reconcile/test/fixtures/jenkins_worker_fleets/jcasc-export.yml, reconcile/test/test_jenkins_worker_fleets.py
This PR enhances fleet manager configuration to enable the sshConnector configuration. With this we will be able to set JVM_OPTS in the remote agents and other ssh options as well. 
Notes: 
* Requires: https://github.com/app-sre/qontract-schemas/pull/524 
* Fixes: https://issues.redhat.com/browse/APPSRE-7529
=> Include Jenkins SSHConnector Options with fleet-manager

reconcile/gql_definitions/introspection.json, reconcile/jenkins/types.py, reconcile/queries.py, reconcile/test/fixtures/jenkins_worker_fleets/gql-queries.yml, reconcile/test/fixtures/jenkins_worker_fleets/jcasc-apply.yml, reconcile/test/fixtures/jenkins_worker_fleets/jcasc-export.yml
Fix reconcile loop caused by wrong case name for `jvmOptions`
schema changes in https://github.com/app-sre/qontract-schemas/pull/527
Follow up for https://github.com/app-sre/qontract-reconcile/pull/3838
=> Fix jvmOptions case sensitive field name

reconcile/terraform_resources.py, reconcile/test/utils/test_external_resources.py, reconcile/utils/external_resource_spec.py, reconcile/utils/external_resources.py
part of https://issues.redhat.com/browse/APPSRE-8184
this PR attempts to add a metric to describe the inventory of external resources managed by `terraform-resources`.
nice to have: make it re-usable between other integrations managing external resources.
=> [terraform-resources] publish external resource invetory metrics

reconcile/utils/aws_api.py
The current log retention integration does not take pagination into account when setting a retention period. This PR will enable pagination in order to target all log groups in an AWS account.
[APPSRE-8375](https://issues.redhat.com/browse/APPSRE-8375)
=> enabling pagination for the log retention integration

reconcile/openshift_resources_base.py
We have a use case where we want to render the slo documents into PrometheusAlerts.
The fields in the slo-documents datafile do contain Jinja2 parameters, for example:
```
expr: |
sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route="api.repository",status!~"5[0-9][0-9]",method="GET"}[{{window}}]))
/
sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route="api.repository",method="GET"}[{{window}}]))
```
The `{{window}}` parameter must be evaluated inside the jinja2 expression:
```
{{% set expr = slo.expr | eval(window=slo.SLOParameters.window) | trim + ' <= ' + slo.SLOTarget | string %}}
```
In order for the `eval` part to work, this filter is required.
=> Add `eval` filter to jinja2

reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_groups.py, reconcile/openshift_resources_base.py, reconcile/openshift_rolebindings.py, reconcile/test/test_openshift_groups.py, reconcile/utils/openshift_resource.py
this PR adds a new `qontract_reconcile_openshift_resource_inventory` metric, a guage which describes the number of resources managed per cluster, namespace, kind and state (current/desired).
=> openshift resource inventory metrics

reconcile/cli.py
Field name of `OCMUserManagementIntegrationParams` is `ocm_organization_ids` instead of `ocm_org_ids`, wrong params assign caused `ocm_org_ids` not being used as filter, lead to reconcile error for not managed ocm org.
=> Fix wrong params assign of ocm_standalone_user_management

grafana-dashboards/grafana-dashboard-external-resource-inventory.configmap.yaml, grafana-dashboards/grafana-dashboard-openshift-resource-inventory.configmap.yaml
adding dashboards for metrics implemented in #3848, #3847, #3858
dashboards can be viewed at:
- https://grafana.stage.devshift.net/d/tf8Xe6WIz/external-resource-inventory
- https://grafana.stage.devshift.net/d/5i2sy6WSk/openshift-resource-inventory
=> Add inventory dashboards

reconcile/cli.py, reconcile/quay_mirror.py, reconcile/test/fixtures/quay_mirror/get_quay_repos_ok.yaml, reconcile/test/fixtures/quay_mirror/get_quay_repos_public_dockerhub.yaml, reconcile/test/test_quay_mirror.py
The previous option (--image) was not very intuitive to understand. It is clearer now with --repository-url what we mean when we want to filter repositories. This patch also includes an exclude option
part of APPSRE-8401
=> Refactor repo filtering in quay-mirror

reconcile/aus/base.py, reconcile/test/ocm/aus/test_base.py, reconcile/test/ocm/aus/test_calculate_diff.py
With only 5 minutes node pool upgrades might fail at times. Increase to 6 minutes
=> Bump skip minutes

reconcile/openshift_saas_deploy.py, reconcile/test/test_saasherder.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/models.py, reconcile/utils/saasherder/saasherder.py
This is a prerequisite to switch to promotions_v2 in saasherder, which is needed to allow multi-publisher channels.
A subscriber needs a relation to all publisher target uids in order to validate promotions from multiple different publishers towards the same publisher channel.
This PR mainly introduces a method to introduce a channel class to the saas file class. The channel object holds all publisher uids.
Saasherder gets a full list of saas files from openshift-saas-deploy. This list is required to resolve publisher -> channel -> subscriber relations. Currently only openshift-saas-deploy uses validate_promotions, so this should be fine.
Note, that saasherder is still primarily using promotions_v1 to validate promotions.
If this change does not lead to issues, we will switch to …
=> APPSRE-7307 validate promotion via publisher uid

reconcile/test/saas_auto_promotions_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/test_integration_test.py, reconcile/test/utils/test_promotion_state.py, reconcile/utils/promotion_state.py
Deprecate promotions_v1. Deployment validation logic will not use any data from old promotions storage prefix.
Note, in the meantime we still keep publishing to promotions_v1 path, so that we can easily revert without having lost potential promotion data. Once this PR is confirmed to have worked, we will remove publishing to promotions_v1 in a follow-up PR.
=> APPSRE-7307 remove promotions_v1 fetch

reconcile/test/utils/test_mr_clusters_updates.py, reconcile/utils/gitlab_api.py, reconcile/utils/mr/__init__.py, reconcile/utils/mr/app_interface_reporter.py, reconcile/utils/mr/aws_access.py, reconcile/utils/mr/base.py, reconcile/utils/mr/clusters_updates.py, reconcile/utils/mr/ocm_update_recommended_version.py, reconcile/utils/mr/ocm_upgrade_scheduler_org_updates.py, reconcile/utils/mr/user_maintenance.py
the a-i default branch name can't be assumed to be "master" for all a-i repos but can be "main" or anything else as well.
this PR introduces main branch name detection.
(also added some typehints along the way, thought it is not comprehensive since the gitlab api does not really expose good typehints on its own 😢 )
https://issues.redhat.com/browse/APPSRE-8420
=> autodetect default branch name for automated MRs

reconcile/test/test_saasherder.py, reconcile/utils/saasherder/saasherder.py
Replaces https://github.com/app-sre/qontract-reconcile/pull/3685
Let `saas-file-validator` integration properly validate multi-publisher channels.
**Test**
Adjusted selector-sync-set demo to have multiple publishers per channel and ran validator locally
```
qd profile run prod saas-file-validator
```
=> APPSRE-7307 support multi-publisher in validator

reconcile/aus/ocm_upgrade_scheduler.py
if an upgrade gets delayed for too long, it is not in state `running` anymore but in state `delayed`. we can report such cluster upgrades as `long running` as well, as we do for `running` ones that run for > 6h already.
=> [AUS] show delayed upgrade policies as long running upgrades

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/aus/ocm_upgrade_scheduler_org.py, reconcile/cli.py, reconcile/test/ocm/aus/fixtures.py, reconcile/test/ocm/aus/test_base.py, tools/qontract_cli.py
* add compatibility for the integrations-manager OCM org sharding functionality to AUS (relies on `--org-id` and `--exclude-org-id` parameters)
* deprecate reporting for `ocm-upgrade-scheduler` and `advanced-upgrade-service` and link to the AUS dashboard instead
part of https://issues.redhat.com/browse/APPSRE-8414
=> [AUS] OCM sharding and ocm-upgrade-scheduler deprecation

reconcile/utils/internal_groups/client.py
`types-requests` now allows `requests.exceptions.HTTPError.response` to be `None` and in order to make mypy happy, we need to check for it
see https://github.com/python/typeshed/pull/10875
=> [mypy/requests] code fixes because of types-requests changes

reconcile/test/ocm/test_utils_ocm_search_filters.py, reconcile/test/ocm/test_utils_ocm_service_log.py, reconcile/utils/ocm/service_log.py
the service log LIST endpoint `/api/service_logs/v1/cluster_logs` is being deprecated and we need to switch to the `/api/service_logs/v1/clusters/cluster_logs` one.
the new endpoint is cluster specific and not org specific anymore, but since we were fetching service logs for specific cluster anyways (filtering server side via `search`) the change has low impact to the overall usage of service logs in qontract-reconcile.
part of https://issues.redhat.com/browse/APPSRE-8422
=> [OCM service logs] switch to cluster specific service log list endpoint

reconcile/cli.py
in the course of enabling AUS to shard on OCM orgs, the new `--org-id` flag has been introduced, which deprecated the `--ocm-org-ids` flag. this MR cleans up the old one.
background: singular-named flags that can be repeated are used on cluster and AWS account based sharding already and the PR check scripts know how to deal with these
follows up on https://github.com/app-sre/qontract-reconcile/pull/3883
part of https://issues.redhat.com/browse/APPSRE-8414
=> [AUS] remove deprecated --ocm-org-ids CLI flag

reconcile/test/test_integrations_manager.py, reconcile/utils/runtime/sharding.py
K8s requires deployment names to be compliant with RFC 1123, which requires all characters of the name to be lowercase. https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
this PR lowercases the OCM organization IDs before making them part of the shard deployment name
follows up on https://github.com/app-sre/qontract-reconcile/pull/3883
part of https://issues.redhat.com/browse/APPSRE-8414
=> [integration-manager] lowercase OCM org ID shards on deployment name suffix

reconcile/openshift_upgrade_watcher.py, reconcile/test/test_openshift_upgrade_watcher.py
fix the place where the upgrade policy state can be found in the dict
```
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/reconcile/openshift_upgrade_watcher.py", line 89, in _get_start_hypershift
schedule = [s for s in schedules if s["state"]["value"] == "started"]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/reconcile/openshift_upgrade_watcher.py", line 89, in <listcomp>
schedule = [s for s in schedules if s["state"]["value"] == "started"]
```
=> [openshift-update-watcher] fix HCP control plane upgrade notification

reconcile/test/utils/test_promotion_state.py, reconcile/utils/promotion_state.py
saasherder now fully relies on promotion v2. We can stop publishing promotion v1 states to s3.
=> APPSRE-7307 remove prom v1 publishing

reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py
The namespace selector matcher for the SAPM renderer has been copy/pasted from `typed_queries.saas_files.py`. That function had a recent make over in `SaasFileList` (https://github.com/app-sre/qontract-reconcile/pull/3846).
In this PR SAPM's renderer gets a simplified version to reverse match a given namespace to a selector and stay more decoupled from `SaasFileList`.
=> APPSRE-8410 simplify selector matcher

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/models.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py
catch sectors defined on clusters but missing on the organization level.
there will be a companion MR on the aus-cli project to prevent this situation client side.
=> [AUS] catch and report missing sector on organization level

helm/qontract-reconcile/templates/template.yaml, reconcile/test/fixtures/helm/command.yml, reconcile/test/utils/test_helm.py
Follow up on https://github.com/app-sre/qontract-reconcile/pull/3898#pullrequestreview-1692859265, `COMMAND_NAME` was supported in `CronJob` only, this change make it work for `Deployment` too.
=> Support COMMAND_NAME for Deployment in helm

reconcile/test/fixtures/slack_api/conversations_history_messages.yaml, tools/sd_app_sre_alert_report.py, tools/test/test_sd_app_sre_alert_report.py
It makes an assumption on the shape of the alert slack messages from the prometheus alert schema. But sometimes the schema cannot be validated (if the rules file is a template) and it may have an unexpected shape. We introduce a workaround to be able to count them.
=> Alerts report crashes on missing message

README.md, reconcile/utils/aws_api.py
[APPSRE-8486](https://issues.redhat.com/browse/APPSRE-8486)
Updates the AWS API wrapper to configure any client for a GovCloud account to use FIPS endpoints in order to comply with FedRamp compliance requirements. GovCloud accounts are determined by checking the `partition` value in the `account.yml` file for each. The reason being is that we have some non GovCloud accounts in FedRamp so we cannot enable FIPS across the board for all accounts.
Tested locally against FedRamp App Interface with a variety of AWS based integrations (terraform-resources, users, etc.). Should not affect commercial at all since we have no us-gov partition accounts there but I will do a rollout to stage before promoting to prod in commercial.
Also adds a note to the README about libpq and Fedora
=> Use FIPS endpoints with AWS for GovCloud Accounts

reconcile/openshift_serviceaccount_tokens.py
This patch eliminates the condition that checks if a token is already present in the destination namespace so that it is that one that is copied instead of the first of the list. This made that in case we had multiple tokens associated to an account, we could potentially copy to different tokens to two different clusters if there was already a token copied that it was not the first of the `sa_token_list` list. This also made the Vault shared-resources secret to be updated multiple times in each run if we had different tokens being copied.
fixes APPSRE-8480
=> Ensure the same SA token is always copied

reconcile/aus/metrics.py, reconcile/aus/ocm_upgrade_scheduler.py
with these metrics we will be able to show the experience we have gained with different versions. this will help demonstrate the value we provide as customer zero.
=> [AUS] expose version data metrics

reconcile/dashdotdb_slo.py, reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.gql, reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.py, reconcile/gql_definitions/introspection.json
Renames `namespaceTarget` to `SLONamespace` according to:
https://github.com/app-sre/qontract-schemas/pull/548
In addition it adds a temporary workaround that skips namespaces with `SLONamespace` defined until https://issues.redhat.com/browse/APPSRE-8513 is implemented.
=> skip namespaces with targetNS in dashdotdb-slo

reconcile/acs_rbac.py, reconcile/cli.py, reconcile/gql_definitions/acs/acs_instances.gql, reconcile/gql_definitions/acs/acs_instances.py, reconcile/gql_definitions/acs/acs_rbac.gql, reconcile/gql_definitions/acs/acs_rbac.py, reconcile/gql_definitions/introspection.json, reconcile/test/test_acs_rbac.py, reconcile/utils/acs_api.py
https://issues.redhat.com/browse/APPSRE-8467
https://issues.redhat.com/browse/APPSRE-7607
Dependencies:
*  https://github.com/app-sre/qontract-schemas/pull/539
This integration will be responsible for reconciling [RH ACS rbac resources](https://docs.openshift.com/acs/4.2/operating/manage-user-access/manage-role-based-access-control-3630.html) . The integration will derive necessary rbac resources via oidc-permissions (see [expansion to oidc-permission-1 schema](https://github.com/app-sre/qontract-schemas/pull/539/files#diff-7a842619b2728c197543a91c51fc7eb0b944b2cb85b43900c981ce6522073faaR71-R96)) associated with App Interface roles that users reference.
`acs` variants of the oidc-permission are defined like so:
```yaml
---
$schema: /access/oidc-permission-1.yml
name: app-sre-cluster-scope …
```
=> Add integration for RHACS rbac configuration

reconcile/acs_rbac.py
Custom acs rbac roles are allowed to reference the system default `Unrestricted` access scope. However, if a custom role referencing `Unrestricted` scope is to be deleted, the final portion of rbac deletion (removal of referenced access scope) should be skipped. The `Unrestricted` access scope cannot be deleted and an error will be returned from attempts to do so.
=> [acs-rbac] disallow attempts to delete system default Unrestricted access scope

reconcile/aus/base.py, reconcile/aus/metrics.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/openshift_resources_base.py, reconcile/test/ocm/aus/test_expose_metrics.py
expose metrics for addon upgrades
* `aus_addon_upgrade_policy_info` - cluster and addon metadata, including upgrade policy details
* `aus_addon_version_remaining_soak_days` - remaining soak days for a addon version on a cluster
they have the same set of labels as their cluster upgrade counterparts but have an additional one called `addon` to distinguish between addons managed on the same cluster.
part of [APPSRE-8524](https://issues.redhat.com/browse/APPSRE-8524)
=> [AUS] expose metrics for addon upgrades

reconcile/ocm_upgrade_scheduler_org_updater.py
HCPs don't have external config labels so default to an empty set of labels in the context of the ocm-upgrade-scheduler-org-updater
=> [org-updater] don't query external config labels on HCPs

reconcile/dashdotdb_slo.py
implement early-exit for dashdotdb-slo. the integration queries several schemas but most of the data in those schemas is not part of the relevant desired state.
part of https://issues.redhat.com/browse/APPSRE-8526
=> [dashdotdb-slo] early exit

reconcile/database_access_manager.py, reconcile/test/test_database_access_manager.py
Need to pass in admin permission to Script Generator. Terraform-resources allows it to change the username of the admin connection. Need to pass the admin connection in to be able to create a managed user
=> Pass in Admin connection to Script generator

reconcile/database_access_manager.py, reconcile/test/test_database_access_manager.py
This enables the deletion of provisioned users.
Content created by these users will not be deleted, but ownership transferred to the admin user. Schemas are retained as well.
=> Add user deletion to DBAM

reconcile/gql_definitions/common/clusters.py, reconcile/gql_definitions/introspection.json, reconcile/ocm_clusters.py, reconcile/test/test_ocm_clusters.py
HCP clusters don't have a controlplane account role
part of [APPSRE-8561
](https://issues.redhat.com/browse/APPSRE-8561)
depends on https://github.com/app-sre/qontract-schemas/pull/552/files
=> [ocm-clusters] make controlplane role optional

reconcile/openshift_base.py
When troubleshooting resource apply, it is useful to also have the DESIRED resource as part of debug logging
=> add logging of DESIRED resource when debugging

setup.py
No difference in prod run as `UnleashClient~=5.3` will install latest `5.x` version client, bump to `UnleashClient~=5.11` to make it explicit.
[APPSRE-7691](https://issues.redhat.com/browse/APPSRE-7691)
=> Bump UnleashClient version to 5.11

reconcile/glitchtip_project_alerts/integration.py, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.gql, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.py, reconcile/gql_definitions/introspection.json, reconcile/test/fixtures/glitchtip/project_alerts.yml, reconcile/test/glitchtip/test_glitchtip_project_alerts.py
Add support for custom labels on glitchtip Jira alert tickets.
Ticket: [APPSRE-8523](https://issues.redhat.com/browse/APPSRE-8523)
Depends on: https://github.com/app-sre/qontract-schemas/pull/553
=> [glitchtip-project-alerts] support custom jira labels

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_repo/terraform_repo.gql, reconcile/gql_definitions/terraform_repo/terraform_repo.py, reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
[APPSRE-8520](https://issues.redhat.com/browse/APPSRE-8520)
Corresponds with the following PRs:
- Schemas: https://github.com/app-sre/qontract-schemas/pull/554
- Executor: https://github.com/app-sre/terraform-repo-executor/pull/16
Basically updates what tf-repo expects as integration input and the output it feeds to the executor to include this new validation flag.
=> FIPS Validation for Terraform Repos

reconcile/aws_version_sync/merge_request_manager/merge_request_manager.py, reconcile/test/aws_version_sync/merge_request_manager/test_merge_request_manager.py, reconcile/utils/mr/labels.py, tools/qontract_cli.py
... otherwise, we don't see such MRs because the `engine_version` field is `self-serviceable`.
=> [aws-version-sync] show not auto-merge MRs in AppSRE review queue

reconcile/aws_version_sync/integration.py, reconcile/test/aws_version_sync/test_avs_integration.py, reconcile/test/utils/test_semver_helper.py, reconcile/utils/semver_helper.py
Convert the `engine_version` strings to `semver.VersionInfo` objects to have a proper version comparison to avoid RDS downgrade MRs. 
Additionally, enhance our custom `parse_semver` function with `optional_minor_and_patch` to mimik semver3 [Version.parse](https://python-semver.readthedocs.io/en/latest/api.html#semver.version.Version.parse)
=> [aws-version-sync] no RDS downgrades

reconcile/cli.py, reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
Start here for some context: https://github.com/app-sre/qontract-reconcile/pull/3799
TLDR is that Pydantic has issues when updating schemas for terraform-repo causing the `load_existing_state` part of the tf-repo reconcile operation to fail. This PR updates that behavior such that if a state load error is encountered, tf-repo just re-creates its own representation of states based on what is in app interface. 
This means that no plan is output to the executor and no infrastructure is updated once the failing MR is merged, only terraform-repo's state is updated (not the actual .tfstate backend files). We could cause more issues if we go in and re-apply every single Terraform Repo in a particular App Interface instance so this PR removes that behavior.
Validated this locally against our FR …
=> [tf-repo] update behavior to recreate state on error

reconcile/database_access_manager.py, reconcile/test/test_database_access_manager.py
Do not print statements (changed psql flag to -b)
Alter password after user creation, removes extra print of create role statement containing the password
Example output of the job:
```
?column?
----------------------------------
CREATE DATABASE "jboll-testfcbd"
(1 row)
CREATE DATABASE
REVOKE
You are now connected to database "jboll-testfcbd" as user "unleash".
?column?
------------------------------
CREATE ROLE "jboll-testfcbd"
(1 row)
CREATE ROLE
ALTER ROLE
GRANT
GRANT ROLE
CREATE SCHEMA
```
=> Fix password leak

reconcile/gql_definitions/introspection.json, reconcile/ocm/types.py, reconcile/ocm_clusters.py, reconcile/queries.py, reconcile/test/fixtures/clusters/rosa_spec_ai.yml, reconcile/test/test_ocm_clusters.py, reconcile/utils/ocm/ocm.py
Import the OIDC endpoint URL of ROSA clusters into app-interface cluster files, similar to the ID and external ID of a cluster. It is supposed to be read only information that can be used by people and automation to define trust policies in IAM policies without the need to do OCM lookups. Since this URL is static, "caching" it like this in the cluster file is a legit approach.
part of https://issues.redhat.com/browse/APPSRE-8656
depends on https://github.com/app-sre/qontract-schemas/pull/560
=> import OCM cluster OIDC endpoint URL into a-i cluster files

requirements/requirements-test.txt
Newer [response](https://github.com/getsentry/responses/releases/tag/0.23.2) requires `requests >= 2.30.0`, but we are currently on `2.22.0`
=> [reqs-dev] pin response package to 0.23.1

reconcile/queries.py
follow up on #2942 and #3010
openshift-serviceaccount-tokens currently does not handle deleted namespaces. with this PR, we add the `delete` field to the query, allowing the proper handle of this scenario.
=> [openshift-serviceaccount-tokens] ignore deleted namespace

reconcile/utils/terrascript_aws_client.py
An MSK user must be an object with `username` and `password` keys.
Ticket: [APPSRE-8357](https://issues.redhat.com/browse/APPSRE-8357)
=> [msk] validate scram user objects from vault secrets

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_aws_client.py
the HCP API is offered via a VPC endpoint in the clusters AWS account. access to this VPCE is per default only granted from within the VPC. when accessing the API via VPC peering, the security group of the VPCE is preventing communication.
this patch will add new rules to the security group of the VPC endpoint. sadly we can't create a dedicated SG and add it to the VPCE because that is only possible with the AWS TF provider > 4 (and we are at 3.7.x). so our only way is to add more rules to the existing SG.
i checked the code of the hypershift operator that reconciling this SG. it is not removing any excessive rules, only adding missing ones. once we upgrade to a newer TF provider, we can add new security groups to existing VPC endpoints. but for now we need to accept this approach.
for …
=> [tf-vpc-peerings] allow access to private HCP API VPCE via peering

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_resources.gql, reconcile/gql_definitions/terraform_cloudflare_resources/terraform_cloudflare_resources.py, reconcile/terraform_cloudflare_resources.py, reconcile/test/test_terraform_cloudflare_resources.py, reconcile/test/utils/test_terrascript_cloudflare_client.py, reconcile/utils/terrascript/cloudflare_resources.py
Related to: https://issues.redhat.com/browse/APPSRE-8315
Needs to be tested with: https://github.com/app-sre/qontract-schemas/pull/532
This adds support to create [custom_ssl_certificate](https://registry.terraform.io/providers/cloudflare/cloudflare/3.32.0/docs/resources/custom_ssl) for Cloudflare.
=> Terraform cloudflare resources custom ssl certificate

reconcile/jira_permissions_validator.py, reconcile/test/test_jira_permissions_validator.py, reconcile/utils/jira_client.py
Public available projects must have the `issueSecurityId` attribute explicitly set.
This ensures the Jira board owner is aware.
Ticket: [APPSRE-8688](https://issues.redhat.com/browse/APPSRE-8688)
=> [jira-permissions-validator] public projects must have issueSecurityId set

reconcile/aus/base.py, reconcile/aus/models.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, reconcile/test/ocm/aus/test_base.py, reconcile/test/ocm/aus/test_calculate_diff.py, reconcile/test/ocm/aus/test_version_gates.py
change: if a minor version has no version gates, upgrades to that minor versions are skipped.
reasoning: usually every minor version has at least one version gate in place. this is not technically necessary but practically speaking this has been the case for every minor version of the last couple of years. we want to skip scheduling an upgrade in such situations because missing version gates might be an indicator that the gap analysis has not been conducted yet from the platform team. such upgrades bear many unknowns and are not considered safe. this mostly happens early during pre-GA, e.g. for RCs.
https://issues.redhat.com/browse/APPSRE-8694
=> [AUS] expect at least one version gate for a minor version

reconcile/utils/output.py
Pipes in content can break the review queue, see: https://gitlab.cee.redhat.com/service/app-interface-output/-/blob/249d7417ff9e9552589ba65614f35aab26b810bb/app-interface-review-queue.md
=> Review queue, escape pipes in titles

reconcile/aus/base.py
add the org name of a cluster to the log output because the org ID is not providing immediate help to identify an org without a human looking it up.
=> [AUS] add org name to log output

reconcile/utils/terrascript_aws_client.py
This consists of code to fix the issue - [APPSRE-8280](https://issues.redhat.com/browse/APPSRE-8280)
Problem - The parsing logic created the same identifier for `"aws_sns_topic_subscription`. Hence  the terrascipt only used to render the resource considering the last subscription added
Now with the new code every subscription for an sns topic will have a unique  identifier. As a result all the subscription for a particular topic will be created.
Local Testing
For the following configuration
The terrascript created the following plan
With single subscription the output is like
the output we get is as follows
=> APPSRE-8280: added code to fix multiple sns subscription for terraform

reconcile/openshift_resources_base.py, reconcile/test/test_prometheus_rules_tester.py
Noticed that in App Interface FedRamp, all of our alert `html_url` values were pointing to commercial App Interface. This change updates such alerts to get the `html_url` base value from App Interface settings.
Some of the changes are updates from ruff formatting.
=> [openshift-resources] Switch out hard-coded App Interface Git URL for dynamic one

reconcile/aus/base.py, reconcile/test/ocm/aus/test_version_gates.py, reconcile/utils/ocm/base.py
OCM does not allow creating version gate agreements that have no effect anymore, e.g. if the cluster is already on a minor version or has a later minor version.
hence, this code change will ignore such version gates
https://issues.redhat.com/browse/APPSRE-8747
=> [AUS] ignore version gates other than for future minor versions

reconcile/openshift_resources_base.py, reconcile/test/test_prometheus_rules_tester.py
A second attempt at #3990 
Some colleagues pointed out that the earlier attempt resulted in a doubling of qontract-server requests which means more $$$. This take removes that additional GQL call as the function already has a settings dict passed to it which includes the `repoUrl` value I was previously querying for in GQL.
=> [openshift-resources] Fix for html_url in Prometheus alerts

reconcile/utils/terrascript_aws_client.py
Ensure that we aren't logging sensitive info into CloudWatch when a user interacts with rosa-authenticator.
=> [rosa-authenticator] redact sensitive field in CloudWatch

reconcile/test/utils/test_early_exit_cache.py, reconcile/test/utils/test_promotion_state.py, reconcile/test/utils/test_state.py, reconcile/utils/early_exit_cache.py, reconcile/utils/state.py, setup.py, tools/qontract_cli.py, tools/test/test_qontract_cli.py
Extended early exit cache management, with `qontract-cli` methods to test.
Support 3 methods:
* `head` check cache status
* `get` get cache value
* `set` set cache value
Local test via `localstack`
```shell
$ make localstack
$ export $(cat ./dev/localstack/.env.local | xargs)
$ qontract-cli --config config.toml early-exit-cache head -i a -v b --dry-run -c {}
CacheStatus.MISS
$ qontract-cli --config config.debug.toml early-exit-cache set -i a -v b --dry-run -c {} -d {} --ttl 30
$ qontract-cli --config config.toml early-exit-cache head -i a -v b --dry-run -c {}
CacheStatus.HIT
$ qontract-cli --config config.toml early-exit-cache get -i a -v b --dry-run -c {}
desired_state={} log_output='' applied_count=0
$ qontract-cli --config config.toml early-exit-cache head -i a -v b --dry-run -c {} …
```
=> Extended early exit cache management

reconcile/gql_definitions/common/clusters_with_peering.gql, reconcile/gql_definitions/common/clusters_with_peering.py, reconcile/queries.py, reconcile/terraform_tgw_attachments.py, reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_tgw_attachments.py, reconcile/test/test_terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py, reconcile/test/utils/test_terrascript_aws_client.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_aws_client.py
Trying to remove the need for osd-experience/network-mgmt role for TGW attachments and peerings. This is done by using directly the cluster account terraform user instead of relying on a remote terraform user and assuming role onto the network-mgmt role.
The review should be easier one commit at a time.
The basic idea is to add an `infra_account_name` field in desired state items. This field represents the account against which we run terraform (basically the one holding the state). This allows to have requester/accepter cluster account which do not use this central account + assume_role for their provider, but can directly be targeted with their own terraform user.
The aim here is that running the integration outputs a TF script which is fully identical if we keep the `assumeRole` fields …
=> ROSA TGW attachments and peerings without osd-experience

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/data_keys.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_housekeeping.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_merge_request_manager.py
This is the first step in allowing SAPM to aggregate promotions into a single MR.
SAPM is difficult to test with all edge cases locally - for that reason we do small incremental steps and observe.
In this first step, we allow the metadata in the MR description to be a concatenation of multiple MRs. The idea is to touch as less as possible to finish this critical issue quickly. By simply aggregating strings, we can keep the data types as is and still hold the state of multiple MRs within a single MR.
In a follow-up MR, we will implement the actual aggregation logic.
=> APPSRE-8505 allow hash/channel concatenation

reconcile/test/utils/vcs/conftest.py, reconcile/test/utils/vcs/test_vcs.py, reconcile/utils/vcs.py
Lets allow our VCS layer to fetch latest pipeline state. The logic is taken from gitlab_housekeeping integration.
Further, this adds a builder pattern to allow tests for VCS functions. The builder pattern can be easily extended for other VCS functions too in the future.
This will be required by SAPM to properly unbatch MRs that are failing, so they do not block each other.
=> APPSRE-8505 allow to fetch latest pipeline state

reconcile/jenkins_job_builds_cleaner.py
If last build is cleaned then SCM that pools git consider as it newer built last commit and initiates new (duplicated) build.
We should preserve last SUCCESSFUL built even if cleanup rules matches it.
=> APPSRE8701 retain last successed builds for CI

reconcile/utils/terrascript/cloudflare_resources.py
Quick fixing the default value for bundle_method in cloudflare custom ssl certificates.
The way it was implemented before could lead to bundle_method being setted to `None` which leads to an error in Terraform.
=> Fix default value or bundle_method

reconcile/openshift_clusterrolebindings.py
[APPSRE-8786](https://issues.redhat.com/browse/APPSRE-8786)
This allows to set `managedClusterRoles: true` even if we don't have tokens yet
=> openshift-clusterrolebinding silently skip clusters without automation token

reconcile/gcr_mirror.py, reconcile/quay_mirror.py, reconcile/quay_mirror_org.py, reconcile/test/test_gcr_mirror.py, reconcile/test/test_quay_mirror.py, reconcile/test/test_quay_mirror_org.py, setup.py
Quay mirror started OOM kill after urllib3 upgrade in https://github.com/app-sre/qontract-reconcile/pull/4002, main change is from this commit https://github.com/urllib3/urllib3/commit/a80c248c34a77e106551bf997e726457b03f42b5.
We need to avoid creating too many connections. This change applies `session` and `timeout` to integrations using `Image`.
* quay-mirror
* quay-mirror-org
* gcr-mirror
Depends on https://github.com/app-sre/sretoolbox/pull/103, need to bump version after merged.
[APPSRE-8176](https://issues.redhat.com/browse/APPSRE-8176)
=> Apply session and timeout to quay mirror integrations

reconcile/cli.py, reconcile/gql_definitions/introspection.json, reconcile/resource_template_tester.py
Rename it to resource template test, cause it's testing resource templates. Template Test would collide with future addition of templating
[APPSRE-8710](https://issues.redhat.com/browse/APPSRE-8710)
=> Rename template test integration

tools/qontract_cli.py
fixes some of the empty cells: https://gitlab.cee.redhat.com/service/app-interface-output/-/blob/e50fe385afdc72ef9ffc877c2eb3944171b7b2ea/clusters-aws-account-ids.md
=> qontract-cli get clusters-aws-account-ids take account id from spec.account if exists

reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py, reconcile/test/utils/test_aws_api.py
[APPSRE-8792](https://issues.redhat.com/browse/APPSRE-8792)
This allows to define the peerings at cluster creation. We rely here on the fact that `awsapi.get_cluster_vpc_details` returns None when the cluster VPC cannot be discovered. It raises an Exception if something goes wrong with the AWS API call, so we should not end up removing a peering if the discovery fails for infra reasons.
=> skip vpc-peerings when cluster VPC cannot be discovered

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py
SAPM MergeRequestManagerV2 has been opening MRs in Draft mode and the MRs looked good.
In this PR we allow V2 to open MRs in non-draft mode, but with the do-not-merge label. By doing so, we allow CI checks to run. We want to observe the behavior of V2 on failed MR checks, i.e., if it properly unbatches MRs if an MR check fails.
Since we apply the do-not-merge label, nothing will be merged. The MR description also indicates that this MR must not be merged.
=> APPSRE-8505 run V2 in non-draft mode

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py
The titles of V1 and V2 do not have a diff now -> in our api lib the MR is not opened properly if title already exists.
Without this, the first MR wins. If it comes from V2, then it will never get merged.
=> APPSRE-8505 titles must have diff

reconcile/openshift_saas_deploy.py, reconcile/test/fixtures/saasherder/saas-trigger.gql.yml, reconcile/test/fixtures/saasherder/saas_deploy.state.json, reconcile/test/test_saasherder.py, reconcile/utils/saasherder/saasherder.py
This is a missing part of [APPSRE-8072](https://issues.redhat.com/browse/APPSRE-8072). Deploy services built by RHTAP would be triggered by image build, We should also allow triggering sast scan in this case. I revisit this feature as I would like to use the same logic for triggering malware detection scan.
=> trigger sast scan for image build

reconcile/openshift_resources_base.py
to be able to facilitate data from environments in resources, openshift-resources should query for environment information.
part of https://issues.redhat.com/browse/OSD-20607
required for https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/95166
=> [openshift-resources] add environment to query

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/utils/terrascript_aws_client.py
part of https://issues.redhat.com/browse/APPSRE-8794
depends on https://github.com/app-sre/qontract-schemas/pull/580
this PR adds support to define a policy to be created and attached to a role, instead or in addition to an inline policy.
this change is quite similar to https://github.com/app-sre/qontract-reconcile/blob/94db30819eceadcb38e99d107eb2c1f1f163b321/reconcile/utils/terrascript_aws_client.py#L2328-L2342
=> [terraform-resources] add support for aws-iam-role role policy

reconcile/test/utils/test_gitlab_api.py, reconcile/utils/gitlab_api.py
as we observe group tokens breaing reconcile,
i started a experiment with filtering bot usernames
the correct solution is to eventually update python-gitlab
but the breaking api changes needed more time than i have right now
=>  reconcile gitlab ignore group bots

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/test/utils/test_terrascript_aws_client.py, reconcile/utils/terrascript_aws_client.py
part of https://issues.redhat.com/browse/APPSRE-8799
depends on https://github.com/app-sre/qontract-schemas/pull/583
this PR adds logic to consider a `lifecycle` attribute on an `aws-iam-role`.
=> [terraform-resources] aws-iam-role add support for lifecycle

reconcile/utils/gitlab_api.py
```
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 462, in _make_request
httplib_response = conn.getresponse()
^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/http/client.py", line 1378, in getresponse
response.begin()
File "/usr/lib64/python3.11/http/client.py", line 318, in begin
version, status, reason = self._read_status()
^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/http/client.py", line 279, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/socket.py", line 706, in readinto …
```
=> [gitlab_api] retry get_project_labels

reconcile/saas_auto_promotions_manager/merge_request_manager/reconciler.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_reconciler.py
Bug in SAPM -> contents of an unbatched MR must never be batched again
=> APPSRE-8505 fix rebatching

reconcile/gql_definitions/introspection.json
No logic change, just sync `introspection.json` for https://github.com/app-sre/qontract-schemas/pull/582
[APPSRE-8759](https://issues.redhat.com/browse/APPSRE-8759)
=> Sync introspection for run_order

reconcile/cli.py, reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py, reconcile/test/utils/test_early_exit_cache.py, reconcile/test/utils/test_extended_early_exit.py, reconcile/test/utils/test_metrics.py, reconcile/utils/early_exit_cache.py, reconcile/utils/extended_early_exit.py, reconcile/utils/external_resources.py, reconcile/utils/metrics.py, reconcile/utils/terraform_client.py, reconcile/utils/terrascript_aws_client.py, tools/qontract_cli.py, tools/test/test_qontract_cli.py
Extended early exit for terraform resources.
* Refactored terraform resources for easy split desired state and apply result
* Add `extended_early_exit_run` to use cache to do early exit
* `extended_early_exit_run` applied in terraform resources to achieve early exit
* export metrics `qontract_reconcile_extended_early_exit_count`
Test locally:
```shell
$ make localstack
$ export $(cat ./dev/localstack/.env.local | xargs)
$ qontract-reconcile --config config.toml \
--log-level DEBUG \
--dry-run \
terraform-resources \
--enable-extended-early-exit \
--extended-early-exit-cache-ttl-seconds 3600 \
--log-cached-log-output \
--account-name YOUR_ACCOUNT_NAME
```
[APPSRE-8725](https://issues.redhat.com/browse/APPSRE-8725)
=> Extended early exit for terraform resources

reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py, reconcile/saas_auto_promotions_manager/merge_request_manager/metrics.py
- properly calculate parallel open MRs
- add batch size as dimension for open MR counter -> batch sizes are limited, so cardinality will stay low
=> APPSRE-8804 better SAPM metrics

reconcile/openshift_resources_base.py
part of https://issues.redhat.com/browse/APPSRE-9783
in order to template resources with the cluster's aws account - we need to query for this information.
also add `hypershift` to the query since it should be useful.
=> add rosa/hypershift fields to openshift-resources namespaces query

reconcile/openshift_rolebindings.py, reconcile/utils/openshift_resource.py
evidently, these silences have worked pretty well:
- #391
- #551
- #973
=> authorization.openshift.io -> rbac.authorization.k8s.io

reconcile/utils/terrascript_aws_client.py
This adds the ability to set the following in an s3 bucket's (and s3-related resources) defaults file
```yaml
s3_bucket_logging:
target_bucket_name: "foo" # Optional
target_prefix: "logs/" # Optional
```
If `s3_bucket_logging` is defined the code does the following:
- Looks up the target S3 bucket using terraform's data resource
- Creates an s3_bucket_logging resource
It is left to the user to create an S3 bucket with appropriate permissions and lifecycle rules to log into. This allows turning off logging while retaining the bucket because it is defined separately
=> APPSRE-9796: allow enable s3 logging on bucket

reconcile/utils/terrascript_aws_client.py
Configuring logging on a bucket adds a logging configuration to the bucket but we don't set that on the bucket resource itself. If we do not ignore it this causes a reconcile loop
Ref.: https://registry.terraform.io/providers/hashicorp/aws/3.76.1/docs/resources/s3_bucket_logging
=> APPSRE-9796: S3 bucket logging lifecycle change must be ignored

reconcile/openshift_rolebindings.py
another fix on top of #4067
```
unsupported role reference kind: ""
```
since we use admin/edit/view and other ClusterRoles, it should be ok to hard code `ClusterRole`, at least for now.
=> [openshift-rolebindings] add kind to roleRef

reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py, reconcile/test/utils/test_early_exit_cache.py, reconcile/test/utils/test_extended_early_exit.py, reconcile/utils/early_exit_cache.py, reconcile/utils/extended_early_exit.py, tools/qontract_cli.py, tools/test/test_qontract_cli.py
Current early exit cache can't handle stale cache, for example in `terraform-resources`:
* MR1: modify resource A
* MR2: revert MR1
Expect MR2 to show some diff, but due to cache hit for MR2 same as state before MR1, pr check will show nothing, prod run will skip until cache expire.
From terraform config point of view, the config after MR2 is the same as before MR1, but the real current state already changed due to MR1, we need to let cache aware of it.
New design is to let `no-dry-run` mode have one cache item per shard, bump cache hash when set cache so old cache won't be reused. `dry-run` mode will additionally check `no-dry-run` latest cache to determine if it's stale.
This change redesign the cache key path:
* dry-run path: `/<integration>/<integration_version>/dry-run(/<shard>)/<cach …
=> Add shard to early exit cache and avoid stale cache

setup.py
`deepdiff` diff paths format is different, break shard check, revert back to `6.4.1`
=> Revert deepdiff version to 6.4.1

reconcile/change_owners/diff.py, reconcile/terraform_resources.py, reconcile/test/change_owners/test_change_type_diff.py, setup.py
the deepdiff 6.7.x library yields different path formats for the found diffs. our custom parse logic was not able to deal with that but deepdiff now also offers a native way to parse paths.
this PR uses the deepdiff path parse logic instead of our own. additionally a bug in the produced early exit desired state was fixed. the state can only contain dicts and not dataclasses.
=> native deepdiff 6.7.x path parsing and tf-res sharded pr check fix

.tool-versions, dockerfiles/Dockerfile, reconcile/cli.py
Bring the required oc client version up-to-date with the version of OpenShift we run
Depends on https://github.com/app-sre/container-images/pull/93
=> bump oc version from 4.10.15 to 4.14.12

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/utils/terrascript_aws_client.py
Support AWS ALB Listener Rule action type "Redirect" following arguments in the [provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#redirect)
Depends on https://github.com/app-sre/qontract-schemas/pull/589
=> APPSRE-9803: add support for AWS ALB Listener Rule Redirect action

reconcile/test/utils/jobcontroller/conftest.py, reconcile/test/utils/jobcontroller/fixtures.py, reconcile/test/utils/jobcontroller/test_controller.py, reconcile/utils/jobcontroller/controller.py, reconcile/utils/jobcontroller/models.py
the `K8sJob` class can define secret data it relies on and the job controller will manage the lifecycle of a kubernetes Secret based on that data.
```python
class MyJob(K8sJob):
...
def secret_data(self) -> dict[str: str]:
return {
"super": "secret"
}
```
the resulting secret has an `ownerReference` towards the job, which implies that the secret gets cleaned up when the job gets cleaned up.
=> [job-controller] support secret data for jobs

reconcile/test/utils/rosa/conftest.py, reconcile/test/utils/rosa/test_log_handler.py, reconcile/test/utils/rosa/test_rosa_cli.py, reconcile/test/utils/rosa/test_session.py, reconcile/test/utils/test_aws_api.py, reconcile/utils/aws_api.py, reconcile/utils/jobcontroller/controller.py, reconcile/utils/jobcontroller/models.py, reconcile/utils/oc.py, reconcile/utils/ocm_base_client.py, reconcile/utils/rosa/model.py, reconcile/utils/rosa/rosa_cli.py, reconcile/utils/rosa/session.py
several ROSA operations are offered via the ROSA CLI only. the utilities in the new `reconcile.utils.rosa` module offer a way to setup the required sessions towards OCM and AWS and integrates into the `reconcile.utils.jobcontroller` to run CLI commands as K8S jobs.
```python
with rosa_session_ctx(cluster, job_controller, secret_reader) as rosa:
result = rosa.cli_execute("rosa whoami")
assert result.status == JobStatus.SUCCESS
print(result.get_log_lines(5))
```
=> [rosa] utilities for ROSA cli usage in q-r

reconcile/aws_version_sync/integration.py, reconcile/aws_version_sync/merge_request_manager/merge_request.py, reconcile/test/aws_version_sync/test_avs_integration.py
Don't format the version number always in the MAJOR-MINOR-PATCH format. Instead, use the format of the reported version number from the AWS resource exporter. E.g. `14.10` instead of `14.10.0`
Ticket: [APPSRE-9839](https://issues.redhat.com/browse/APPSRE-9839)
=> [aws-version-sync] handle version format correctly

pyproject.toml, reconcile/ocm_upgrade_scheduler_org_updater.py, reconcile/openshift_resources_base.py, reconcile/prometheus_rules_tester/integration.py, reconcile/test/test_ocm_upgrade_scheduler_org_updater.py, reconcile/test/test_openshift_resources_base.py, reconcile/test/test_utils_jinja2.py, reconcile/utils/external_resource_spec.py, reconcile/utils/jinja2/extensions.py, reconcile/utils/jinja2/filters.py, reconcile/utils/jinja2/utils.py, reconcile/utils/saasherder/saasherder.py, reconcile/utils/terrascript_aws_client.py
The first commit is a refactoring which will make the jinja templating more usable for non openshift resources, like the ongoing templating.
The second commit adds new filters which allow templates to check for existence of some items in the input object.
For example in a role, checking if a datafile is already present:
```
{% set up_to_date = (role | matches_jsonpath('self_service[?(@.change_type["$ref"]=="' + change_type_path + '")].datafiles[?(@["$ref"]=="' + data_file_path + '")]')) %}
```
`json_pointers` allows to retrieve [RFC6901](https://www.rfc-editor.org/rfc/rfc6901)  JSON pointers. Those are useful to create [JSONPatches](https://www.rfc-editor.org/rfc/rfc6902.html)
=> Refactor jinja env and add extract_jsonpath and matches_jsonpath filters

reconcile/cli.py, reconcile/saas_auto_promotions_manager/integration.py
If we run SAPM locally, we would like to be able to reduce the amount of queries to github/gitlab.
=> SAPM allow running on reduced set of saas files

reconcile/utils/terraform_client.py
it's been a while since anyone actually had to `--enable-deletion`. let's avoid new soon-to-be-out-of-date instructions and use custom messages from app-interface settings.
related to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/97499
=> [terraform-resources] custom disabled deletion instructions

reconcile/gql_definitions/common/clusters.gql, reconcile/gql_definitions/common/clusters.py, reconcile/utils/aws_api.py, requirements/requirements-type.txt, tools/qontract_cli.py
this PR adds the `--billing-account` option to the rosa create-cluster-command subcommand.
related to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/97504
=> [qontract-cli] get rosa-create-cluster-command billing-account

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/aus_label_source.py, reconcile/gql_definitions/advanced_upgrade_service/aus_clusters.py, reconcile/gql_definitions/advanced_upgrade_service/aus_organization.py, reconcile/gql_definitions/common/clusters.py, reconcile/gql_definitions/fragments/upgrade_policy.gql, reconcile/gql_definitions/fragments/upgrade_policy.py, reconcile/gql_definitions/introspection.json, reconcile/test/oc/fixtures.py, reconcile/test/ocm/aus/fixtures.py, reconcile/test/test_openshift_upgrade_watcher.py
upgrade policies can now hold a list of version gate labels AUS should handle and approve automatically in the `versionGateApproval` field.
this PR only transfers such declaration to OCM subscription labels. the AUS change to act on them is handled in this PR: https://github.com/app-sre/qontract-reconcile/pull/4103
depends on https://github.com/app-sre/qontract-schemas/pull/594
=> [AUS] declare version gates to approve and handle

reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py
Some resource spec such as `output_format` is not used in terraform config, only used for openshfit secrets. Terraform config is not enough to cover all desired changes, changes for `output_format` won't cause cache miss, need to wait for cache expire to apply.
Add `resource_spec_inventory` to cache source to cover all config from desired state.
=> Update cache source of terraform_resources to include resource specs

reconcile/templating/renderer.py, reconcile/templating/rendering.py, reconcile/templating/validator.py, reconcile/test/templating/conftest.py, reconcile/test/templating/test_full_rendering.py, reconcile/test/templating/test_patch_rendering.py, reconcile/test/templating/test_renderer.py, reconcile/utils/jinja2/utils.py
Add the openshift_namespace_exists method, which can be used by templates to check if a namespace exists on a cluster.
Make it possible to mock these lambdas by passing in `_template_mock` variables.
=> Enhance template rendering

.tool-versions, dockerfiles/Dockerfile, dockerfiles/Dockerfile.publish-release, dockerfiles/Dockerfile.test, reconcile/cli.py
[APPSRE-9849](https://issues.redhat.com/browse/APPSRE-9849)
Unfortunately the newer version of oc updated in https://github.com/app-sre/qontract-reconcile/pull/4082 caused issues in the FedRamp environment. Switching the oc binary to a 4.12 version to match up with what our FedRamp clusters are running.
Specifically: https://access.redhat.com/solutions/7046917
=> Change oc binary in QR to 4.12

reconcile/test/utils/aws_api_typed/test_aws_api_typed_api.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_api_credentials.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_iam.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_organization.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_sts.py, reconcile/test/utils/test_aws_api.py, reconcile/utils/aws_api.py, reconcile/utils/aws_api_typed/api.py, reconcile/utils/aws_api_typed/iam.py, reconcile/utils/aws_api_typed/organization.py, reconcile/utils/aws_api_typed/sts.py, requirements/requirements-type.txt
Introduce a new typed and fully tested boto3 AWS API abstraction. This preperation work for [SDE-3698 - AWS account management](https://issues.redhat.com/browse/SDE-3698)
Usage example:
```python
with AWSApi(
AWSStaticCredentials(
region="us-east-1",
access_key_id="XXX",
secret_access_key="XXX",
)
) as aws_api:
with aws_api.assume_role(
account_id="1234567890", role="AwsAccountManager"
) as acct_manager_role_api:
status = acct_manager_role_api.organizations.create_account(
email="mail@mail.org",
account_name="JeanLuc",
tags={"managed-by": "app-interface"},
)
print(status)
```
=> [aws_api_typed] New AWS API

reconcile/templating/rendering.py, reconcile/templating/validator.py, reconcile/test/templating/test_validator.py, reconcile/utils/jinja2/utils.py, setup.py, tools/template_validation.py
This adds a CLI which helps develop templates locally. It can be invoked as such:
```bash
template_validation.py --template-path /templating/templates/cert-manager/cert-manager.yml --ai-path $HOME/app-interface
```
The cli will do:
- Evaluate the provided template by parsing it and checking it against configured tests
- Ensuring the YAML is valid by running `yamllint`
It is a more convenient way to develop new templates, focused on creating tests first,
=> Add validation cli

Makefile, build_deploy.sh, dockerfiles/Dockerfile, reconcile/cli.py, reconcile/utils/binary.py
`oc` is fickle when it comes to FIPS so this change builds a separate FIPS image with a known working version of `oc`. Also updates QR to support checking for multiple binary versions.
[APPSRE-9849](https://issues.redhat.com/browse/APPSRE-9849)
Depends on:
- https://github.com/app-sre/container-images/pull/96
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/97565
There will be a bit of duplication of the `oc` binary with how Docker image layering works, however the dependency chain of how the QR base image is used means that it probably wouldn't be a good idea to remove the `oc` binary from the base image.
=> Build a FIPS compatible QR image

reconcile/test/utils/jobcontroller/fixtures.py, reconcile/test/utils/jobcontroller/test_controller.py, reconcile/test/utils/rosa/test_log_handler.py, reconcile/test/utils/rosa/test_rosa_cli.py, reconcile/utils/jobcontroller/controller.py, reconcile/utils/jobcontroller/models.py, reconcile/utils/rosa/rosa_cli.py
not all rosa cli automations are single commands. if longer scripts are required, passing commands as ENV variables becomes cumbersome and brittle. mounting the script as a file into the job container is much more stable.
this PR introduces such scripting functionality.
bonus: get the last x logfiles from a pod
=> [rosa-cli] support for running longer scripts

helm/qontract-reconcile/values-manager-fedramp.yaml, openshift/qontract-manager-fedramp.yaml
[APPSRE-9849](https://issues.redhat.com/browse/APPSRE-9849)
Now that we have a new FIPS compatible qontract-reconcile image being built, we need to ensure that all integration pods spawned in FedRamp are using that image not the standard QR image. integrations_manager is responsible for creating those pods and supports an `--image/-i` option to specify which image to use in the newly created pods so I've updated the FR OpenShift template so that new pods use the correct image.
I did not update the `IMAGE` tag [here](https://github.com/cubismod/qontract-reconcile/blob/bac0399c1f3e77b5d4464ac54146dadbe89cee1a/openshift/qontract-manager-fedramp.yaml#L264) as that can just be adjusted within the saas file deploying QR.
=> [fedramp] helm updates for FIPS image

reconcile/templates/rosa-hcp-cluster-creation.sh.j2, reconcile/test/fixtures/rosa/rosa_hcp_script_result.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_dry_run.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_no_provision_shard.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_private.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_reuse_oidc_config.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_uwm_enabled.sh, reconcile/utils/jobcontroller/controller.py, reconcile/utils/oc.py, reconcile/utils/rosa/session.py
for the HCP cluster creation automation, we assume one cluster per account right now. instead of just assuming, lets enforce it.
if a cluster exists already in an account, the rosa cli script will fail (also during PR checks).
bonus: fix some logging issue where job logs were not always shown
=> [ocm-clusters] enforce one HCP cluster per AWS account

reconcile/utils/rosa/session.py
increase the timeout for the ROSA HCP cluster creation job to 5 minutes up from 60 seconds. this is defined statically for now to solve an issue. an upcoming PR will make this configurable
=> increase timeout for rosa cluster creation job

reconcile/templating/rendering.py, reconcile/test/fixtures/templating/patch_add_newline_list.yaml, reconcile/test/fixtures/templating/patch_overwrite_newline_list.yaml, reconcile/test/templating/test_patch_rendering.py
When parse template using ruamel, there needs to be 2 newlines at start for it to be recognized as a newline comment. See example in [patch_add_newline_list.yaml](https://github.com/hemslo/qontract-reconcile/blob/f6a45e21acbbc18595156fcec9cf16b72931293c/reconcile/test/fixtures/templating/patch_add_newline_list.yaml)
To support keeping newlines when overwrite item in list, the item in list has to be replaced by parsed yaml object instead of update in place.
There is one remaining issue about overwrite item in dict, so far the dict items are patched, for example in test case [patch_overwrite_nested.yaml](https://github.com/app-sre/qontract-reconcile/blob/cfb5b6fc1e3594afdcbda82551b37269864fa352/reconcile/test/fixtures/templating/patch_overwrite_nested.yaml), matched `$.version` is a dict, …
=> [template-renderer] Keep newline when patch template

reconcile/ocm_aws_infrastructure_access.py
related to https://issues.redhat.com/browse/OSD-21345
split from #4142, related to #4146
this is work to prevent OCM integrations from running on changes such as https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/98491.
how?
from inspecting the queries, all OCM integrations are running for this change (a role addition that is not related to OCM access) due to querying for users who have access to roles with aws access to groups that have aws infrasturcture access.
in this PR, we prevent ocm-aws-infrastructure-access from running in a MR that does not change the desired state.
=> [ocm-aws-infrastructure-access] early exit

reconcile/ocm_aws_infrastructure_access.py, reconcile/queries.py
related to https://issues.redhat.com/browse/OSD-21345
split from #4142, related to #4144
this is work to prevent OCM integrations from running on changes such as https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/98491.
how?
from inspecting the queries, all OCM integrations are running for this change (a role addition that is not related to OCM access) due to querying for users who have access to roles with aws access to groups that have aws infrasturcture access.
in this PR, we prevent other ocm integrations from querying for this information.
=> [ocm-aws-infrastructure-access] reduce query

reconcile/gql_definitions/common/clusters.gql, reconcile/gql_definitions/common/clusters.py, reconcile/test/fixtures/oc_connection_parameters/cluster_custom_token.yml, reconcile/test/fixtures/oc_connection_parameters/cluster_no_jumphost.yml, reconcile/test/fixtures/oc_connection_parameters/cluster_with_jumphost.yml, reconcile/test/fixtures/openshift_upgrade_watcher/cluster1.yml
related to https://issues.redhat.com/browse/OSD-21345
split from #4142, relates to #4143
this is work to prevent OCM integrations from running on changes such as https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/98491.
how?
from inspecting the queries, all OCM integrations are running for this change (a role addition that is not related to OCM access) due to querying for users who have access to roles with aws access to groups that have aws infrasturcture access.
in this PR, we prevent future ocm integrations from querying for this information, by removing it from the typed queries. the intention is that we keep `ocm-aws-infrastructure-access` on a "deprecated" code path.
=> prevent usage of aws infrastructure access in typed queries

reconcile/ocm_groups.py, reconcile/openshift_groups.py, reconcile/openshift_users.py
related to https://issues.redhat.com/browse/OSD-21345
split from #4142, related to #4145
this is work to prevent OCM integrations from running on changes such as https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/98491.
how?
from inspecting the queries, all OCM integrations are running for this change (a role addition that is not related to OCM access) due to querying for users who have access to roles with aws access to groups that have aws infrasturcture access.
in this PR, we prevent ocm-groups from running in a MR that does not change the desired state.
=> [ocm-groups] early exit

reconcile/openshift_namespaces.py
we currently do not fail in dry-run: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/97765
leading to reverts: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/98529
this is known - we can not create `openshift-` namespaces. let's fail in dry-run.
the logic to raise an exception is consistent and will be handled in https://github.com/app-sre/qontract-reconcile/pull/4148/files#diff-3faaaf915e42878fb84d5d26fff3791258ff2e290185c31da412e4ab0f5104beR129-R141
=> [openshift-namespaces] fail on openshift namespaces on dry-run

reconcile/slack_usergroups.py, reconcile/test/test_slack_usergroups.py, reconcile/utils/pagerduty_api.py
Ignore cluster access roles with `tag_on_cluster_updates: false` to improve PR runtime and reduce pagerduty API calls.
Context: https://redhat-internal.slack.com/archives/GGC2A0MS8/p1709551646681289
=> [slack-usergroups] speedup PR checks

reconcile/slack_usergroups.py
Fix typo in early exit function
=> [slack-usergroups] typo

reconcile/aus/base.py, reconcile/aus/models.py, reconcile/test/ocm/aus/conftest.py, reconcile/test/ocm/aus/test_calculate_diff.py, reconcile/test/ocm/aus/test_version_gate_approver.py
prevent multiple node pool upgrades from being scheduled. OCM prevents it anyways. so this is mostly about not failing the integration in such situations, keeping a tidy log and less reconcile alerts.
how: add the ID of the cluster as a mutex
=> [AUS] prevent multiple concurrent upgrades per cluster

reconcile/gql_definitions/common/clusters_with_peering.gql, reconcile/gql_definitions/common/clusters_with_peering.py, reconcile/gql_definitions/introspection.json, reconcile/terraform_tgw_attachments.py, reconcile/utils/terrascript_aws_client.py
similar to regular peerings, we want traffic via TGW attachments to reach the API of a private HCP via its VPC endpoint
follows up on https://github.com/app-sre/qontract-reconcile/pull/3969
part of https://issues.redhat.com/browse/APPSRE-9883
depends on https://github.com/app-sre/qontract-schemas/pull/598
=> [terraform-tgw-attachments] allow traffic from the TGW on an HCPs VPC endpoint

reconcile/utils/terrascript_aws_client.py
discovered as part of the exploration in https://issues.redhat.com/browse/APPSRE-9906
https://developer.hashicorp.com/terraform/language/values/outputs#sensitive-suppressing-values-in-cli-output
this needs to be tested to see what is the impact to the integration, since it relies on the state to later populate output secrets.
=> [terraform-resources] sensitive outputs

reconcile/utils/terrascript_aws_client.py
discovered as part of the exploration in https://issues.redhat.com/browse/APPSRE-9906
this is required for future compatibility with terraform v1, whenever we get there.
=> [terraform-resources] required providers

.tool-versions, dockerfiles/Dockerfile, reconcile/cli.py
part of https://issues.redhat.com/browse/APPSRE-9906
depends on https://github.com/app-sre/container-images/pull/97
note: this PR is into `tfv1` and not into `master`.
this PR is an attempt to work on a long lived feature branch, and perhaps explore promoting it with `shardSpecOverrides`.
=> [terraform-resources] terraform v1 poc

dockerfiles/Dockerfile
[APPSRE-9812](https://issues.redhat.com/browse/APPSRE-9812)
The qontract-reconcile integration cannot clean up zombie processes, leading to issues with memory and thread startup.
This update incorporates [tini](https://github.com/krallin/tini) as the init system to improve process cleanup.
The change was locally tested to observe process cleanup efficiency. Additionally, this will apply to the fips build stage for testing purposes.
=> add tini to qr image to help reap orphaned processes

dockerfiles/Dockerfile
part of https://issues.redhat.com/browse/APPSRE-9906
depends on https://github.com/app-sre/container-images/pull/99
=> bump qontract-reconcile-base to 0.12.0-tfv1-rc2

dockerfiles/Dockerfile
depends on https://github.com/app-sre/container-images/pull/100
this PR adds terraform cloudflare provider version 3.35.0 (latest 3.x)
required for https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-4-upgrade
=> bump qontract-reconcile-base to 0.11.2

reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py
we currently fail if `--account-name` is used with `--exclude-accounts`.
this failure is introduced by the `select-integrations.py` enhancement to only check affected shards (the implementation is the usage of `--account-name`), while also supporting `shardSpecOverrides`.
with this adjustment, we only fail if the same account is both included and excluded.
=> [terraform-resources] prevent same account from being included and excluded

reconcile/utils/terrascript/cloudflare_client.py
related to https://issues.redhat.com/browse/APPSRE-8451
this PR introduces a conditional behavior to avoid adding `account_id` to provider section.
related to https://github.com/cloudflare/terraform-provider-cloudflare/issues/1646
=> terraform cloudflare client provider version behavior

reconcile/utils/terrascript/cloudflare_resources.py
related to https://issues.redhat.com/browse/APPSRE-9906
in an attempt to upgrade to terraform v1, the following error shows up (#4173):
```
The argument "account_id" is required, but no definition was found.
```
this PR would add the missing attribute while we are on a 3.x provider, so we are ready for a terraform v1 migration.
=> cloudflare_worker_script add account_id

reconcile/test/utils/test_terrascript_cloudflare_client.py, reconcile/utils/terrascript/cloudflare_client.py, reconcile/utils/terrascript_aws_client.py
terraform integrations validate the binary version.
there are cases that require manual intervention, such as importing resources. in such cases, we use the `--print-to-file` option and execute `terraform` locally.
this PR adds usage of `required_version` to avoid mistakes of binary version: https://developer.hashicorp.com/terraform/language/settings#specifying-a-required-terraform-version
=> terraform required version

reconcile/aus/base.py, reconcile/aus/ocm_upgrade_scheduler.py, reconcile/test/ocm/aus/test_version_data.py
the version data metrics should not incorporate inherited version data from other organizations. version data metrics need to be as plain as possible so we can aggregate them in prometheus to slice and dice in grafana. pre-agregation during metric exposure prevents that.
https://issues.redhat.com/browse/APPSRE-9865
=> [AUS] report version data without org inheritance

reconcile/openshift_resources_base.py, reconcile/utils/aws_api.py, reconcile/utils/jinja2/utils.py
part of https://issues.redhat.com/browse/APPSRE-9898
following up on #4158, we want to be able to dump these results from s3 to a ConfigMap.
this PR introduces templating from an s3 object, which will allow us to:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: publisher-data
data:
publisher-data.json:
{{ s3('account-name', 'bucket-name', 'path/to/object') | tojson }}
```
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/99057
=> [openshift-resources] support templating from s3 object

reconcile/utils/terrascript_aws_client.py
part of https://issues.redhat.com/browse/APPSRE-8577
these changes are required to be backwards compatible with data in app-interface(s), and also with terraform aws provider version 5.x.
we do this by updating `values` to match changes in the terraform provider.
testing release candidate here: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/99480
=> [terraform-resources] aws provider 5.x enhancements

reconcile/openshift_resources_base.py
part of https://issues.redhat.com/browse/APPSRE-9898
fixes #4169
```
Arguments: (TypeError("_early_exit_monkey_patch_assign() missing 1 required positional argument: 'lookup_s3_object'"),)
```
=> lookup_s3_object add to yield _early_exit_monkey_patch_assign

reconcile/dynatrace_token_provider.py
Lack of namespace was causing SyncSet throwing error.
=> [dynatrace-token-provider] add namespace definition so Secret can be properly created.

reconcile/utils/saasherder/saasherder.py
this error would be swallowed by https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/utils/saasherder/saasherder.py#L1351-L1356
=> add logging for image error

reconcile/utils/terrascript_aws_client.py
part of https://issues.redhat.com/browse/APPSRE-8577
follow up on #4188
since `replica_source` can no longer co-exist with `name` or `db_name`, we popped them in #4188. the implication is that read replica output for db_name is now empty, which results in missing fields in output secrets (namespace/vault).
this PR sets `db_name` for read replicas based on the source replica info.
=> [terraform-resources] aws provider 5.x fixes

reconcile/utils/terrascript_aws_client.py
use `tag` instead of `tags` for autoscaling groups.
https://registry.terraform.io/providers/hashicorp/aws/3.76.1/docs/resources/autoscaling_group#tag-and-tags
vs
https://registry.terraform.io/providers/hashicorp/aws/5.39.1/docs/resources/autoscaling_group#tag
=> [terraform-resources] 5.x provider asg updates

reconcile/aws_version_sync/merge_request_manager/merge_request_manager.py, reconcile/test/aws_version_sync/merge_request_manager/test_merge_request_manager.py, reconcile/utils/mr/labels.py, tools/qontract_cli.py
The change-owners integration manages the `show-self-serviceable-in-review-queue` label and can't be used to show arbitrary MRs in the review queue. As long as we don't enable the auto-merge of AVS MRs, we need to show them in the review queue filtered by the `AVS` label.
=> :bug: aws-version-sync: fix showing MRs in the review queue if auto-merge is disabled

pyproject.toml, reconcile/aus/base.py, reconcile/change_owners/change_owners.py, reconcile/change_owners/diff.py, reconcile/dynatrace_token_provider.py, reconcile/test/utils/test_external_resource_spec.py, requirements/requirements-test.txt, tools/qontract_cli.py
Keeping ruff up to date because my ruff-lsp keeps updating and using a global ruff instead of the local venv.
=> Update ruff to 3.2

reconcile/utils/terrascript_aws_client.py
```
[terraform-resources] [<account> - apply] Error: creating RDS Event Subscription (terraform-20240317103136899600000001): operation error RDS: CreateEventSubscription, https response error StatusCode: 404, RequestID: ef365010-5ac2-4010-bdba-c4d331553266, SourceNotFound: Could not find source :db-X2DZTPZZBF4OCRVD35QD4PJQIU
```
=> [terraform-resources] rds event notifications use identifier instead of id

reconcile/utils/terrascript_aws_client.py
Remove the `${aws.username}` and `${aws.accountid}` string replacement in favor of properly escaped variables in the policy. E.g. `$${aws.username}` instead of `${aws.username}`. 
Part of: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/98869
See [IAM policy elements: Variables and tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html) for more details about all available AWS variables.
Why this change, you may ask?
During the development of https://github.com/app-sre/qontract-reconcile/pull/4184, I found some problems with this replacement:
* `${aws.username}` in an app-interface policy yaml can't be [parsed by terraform](https://github.com/hashicorp/terraform-provider-aws/issues/5984)
* To use the official AWS variable, you must …
=> [terraform-users] do not replace special AWS variables

reconcile/terraform_users.py, reconcile/utils/terrascript_aws_client.py
We don't need IAM users, groups, and user policies in accounts with SSO enabled.
Ticket: [APPSRE-9811](https://issues.redhat.com/browse/APPSRE-9811)
=> [terraform-users] do not create IAM users in AWS accounts with SSO enabled

reconcile/terraform_tgw_attachments.py
to avoid running this integration in pr-check or changes to, for example, deletion of external resources.
if nothing changes except for deletion approvals, the integration has nothing to do.
=> [terraform-tgw-attachments] ignore deletion approvals in early exit

reconcile/change_owners/change_owners.py, reconcile/change_owners/change_types.py, reconcile/change_owners/decision.py
consider a path in a datafile approved if all individual parts of the datafile are covered by change-types and have been approved.
e.g. consider the introduction of an RDS overrides section in a namespace
```yaml
externalResources:
- provider: aws
provisioner:
$ref: /aws/account.yml
resources:
- provider: rds
...
+   overrides:
+     timeouts:
+       create: 2h
+      apply_immediately: true
```
the entire `overrides` section is covered by a high priviledge change-type and the `timeouts` and `apply_immediately` properties are covered by two other specialized change-types.
this PR will allow the change to be self-serviceable by:
* the high priviledge change-type...
* ... or the two specialized change-types, without the need of the high priviledge change-type
=> [change-owners] approval detection for split changes

reconcile/utils/terraform_client.py
Avoid issues when multiple terraform init try to populate plugin cache at the same time.
https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache
> Note: The plugin cache directory is not guaranteed to be concurrency safe. The provider installer's behavior in environments with multiple terraform init calls is undefined.
=> Run terraform init in sequence

reconcile/utils/terrascript_aws_client.py
We need default_regions to check whether the rds replica is in same region from the source. region can not be None.
=> [APPSRE-9947] fix default_regions in tf-r

reconcile/cli.py
Only `kwargs` can be override in [copy_and_update](https://github.com/app-sre/qontract-reconcile/blob/dcf849f9f2441fbd906b52ccb1e3abfa5d783d86/reconcile/utils/runtime/integration.py#L262) for [_integration_dry_run](https://github.com/app-sre/qontract-reconcile/blob/b8281476eb8876e264f80b1f6eaeed93e46a2118/reconcile/utils/runtime/runner.py#L173).
Otherwise it will fail due to `run() got multiple values for argument 'account_name'`.
=> [terraform-tgw-attachments] Pass account_name as kwargs for shard dry run

reconcile/aus/base.py, reconcile/aus/version_gates/__init__.py, reconcile/aus/version_gates/ingress_gate_handler.py
add the `gate-ingress` version gate to the list of valid gates to be auto acknowledable by the AUS version-gate-approver
the implementation is mostly about letting the version-gate-approver integration know that such a gate exists and how to handle it if users decide that they want to auto ack it.
depends on https://github.com/app-sre/qontract-schemas/pull/609
part of https://issues.redhat.com/browse/APPSRE-7949
=> [AUS] enable ingress gate to be auto approvable

reconcile/aus/base.py
if a cluster has unacked version gates, the OCM API to create an upgrade policy will fail. this PR prevents that failure by not scheduling an upgrade in such situations.
follow up to https://github.com/app-sre/qontract-reconcile/pull/4103 which was incomplete
part of APPSRE-7949
=> [AUS] skip cluster upgrade scheduling on unacked gates

reconcile/aus/base.py
the variable `gates` representing all the version gates that exist in an OCM environment was accidentally overwritten in a subsequent code branch with a shorter and potentially even empty list.
the condition that prevents cluster upgrades from happening when there are no gates defined started to act arbitrarily
=> [AUS] bugfix in gate handling

reconcile/aus/base.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/cli.py, reconcile/queries.py, reconcile/test/ocm/aus/test_base.py, reconcile/utils/ocm/addons.py, reconcile/utils/ocm/upgrades.py, tools/qontract_cli.py
certain addon related OCM API endpoints have been moved to their own service. this PR introduces support for the new endpoints while keeping support for the old ones during the time of migration.
the most involved change is the rename of `upgrade_policies` to `upgrade_plans` with some minor nuances in field names.
a label on the OCM environment schema file controls which version of the API is to be used for that specific OCM environment.
```yaml
---
$schema: /openshift/openshift-cluster-manager-environment-1.yml
labels:
feature_flag_addon_service_version: "$version"
```
use `v1` for the old APIs under `cluster_mgmt` and `v2` for the new API under `addons_mgmt`.
new API: https://gitlab.cee.redhat.com/ocm/ocm-addons-service/-/blob/main/openapi/ocm-addons-service.yaml
part of: …
=> [AUS] support new addon service

reconcile/aws_saml_idp/integration.py, reconcile/queries.py, reconcile/test/aws_saml_idp/test_aws_saml_idp_integration.py, reconcile/test/fixtures/aws_saml_idp/aws_accounts.yml
A newly created AWS account (`/aws/account-1.yml` via `aws-account-manager`) doesn't have a `terraformState` set; this will be done via another additional integration `terraform-init` later based on the account file (`/aws/account-1.yml`). All terraform related integrations should ignore such an account until a `terraformState` attribute is present.
Context: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/101355
=> :bug: ignore AWS accounts without a terraformState

reconcile/aws_saml_idp/integration.py, reconcile/queries.py, reconcile/test/aws_saml_idp/test_aws_saml_idp_integration.py, reconcile/test/fixtures/aws_saml_idp/aws_accounts.yml
Reverts app-sre/qontract-reconcile#4232
Several integrations fail for accounts with missing `terrafromState`. I need to review that again.
=> Revert ":bug: ignore AWS accounts without a terraformState"

reconcile/aws_account_manager/integration.py, reconcile/aws_account_manager/metrics.py
Expose these metrics:
```
aws_account_manager_payer_account_count{flavor="app-interface-commercial"} X
aws_account_manager_org_account_count{flavor="app-interface-commercial", payer_account="XXXX"} X
aws_account_manager_non_org_account_count{flavor="app-interface-commercial"} X
```
Ticket: [APPSRE-9983](https://issues.redhat.com/browse/APPSRE-9983)
=> :stethoscope: aws-account-manager: expose some metrics

reconcile/aws_account_manager/integration.py
Fix just a stupid typo introduced in #4235
=> :pencil2: aws-account-manager: fix typo

tools/qontract_cli.py
when saas files were first created, one of the underlying structures was: [environments](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-interface/api/entities-and-relations.md?ref_type=heads#products-environments-namespaces-and-apps).
the command in this PR outputs a list of components and their versions per environment.
=> [qontract-cli] get component-versions

reconcile/deadmanssnitch.py, reconcile/test/test_deadmanssnitch.py
While testing it was found out that while writing data to vault...the integration is not upserting the data rather writing. This is not desired for the integration and lead to data loss.
Added changes to integration for reading/writing to vault only once if there is change in vault secret object
=> APPSRE-8713: fix vault writes with deadmanssnitch integration

reconcile/utils/jinja2/utils.py
Added additional SecretFieldNotFound exception to supress unwanted exception caused during rendering templates.
While testing template rendering it was observed that SecretFieldNotFound is another exception that can occur in case the secret does not exists in vault which lead to MR fails.
=> added SecretFieldNotFound to exception list

reconcile/utils/terrascript_aws_client.py
vpc peerings HCP requester and accepter scurity group rules had the same terrascript id, so when both ends are HCP only one side of the peering had rules associated to it.
=> Fix HCP security groups config being overwritten

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-manager-fedramp.yaml, openshift/qontract-manager.yaml, reconcile/test/fixtures/helm/aws_account_shard_disabled.yml, reconcile/test/fixtures/helm/aws_account_shard_spec_override.yml, reconcile/test/fixtures/helm/aws_account_shards.yml, reconcile/test/fixtures/helm/basic.yml, reconcile/test/fixtures/helm/cache.yml, reconcile/test/fixtures/helm/cache_storage_vars.yml, reconcile/test/fixtures/helm/command.yml, reconcile/test/fixtures/helm/disable_unleash.yml, reconcile/test/fixtures/helm/enable_google_chat.yml, reconcile/test/fixtures/helm/environment_aware.yml, reconcile/test/fixtures/helm/exclude_service.yml, reconcile/test/fixtures/helm/extra_args.yml, reconcile/test/fixtures/helm/extra_env.yml, reconcile/test/fixtures/helm/integrations_manager.yml, reconcile/test/fixtures/helm/internal_certificates.yml, reconcile/test/fixtures/helm/logs_slack.yml, reconcile/test/fixtures/helm/shards.yml, reconcile/test/fixtures/helm/sleep_duration.yml, reconcile/test/fixtures/helm/state.yml, reconcile/test/fixtures/helm/storage.yml, reconcile/test/fixtures/helm/trigger.yml
`/tmp` is part of overlay fs right now. However it is used by i.e. terraform-resources and will be used by template-renderer soon for writig temporary data. Using an OverlayFS for writes can cause significant performance issues. Thus, create a separate mount for it using emptyDir
=> Make tmp an emptydir

reconcile/cli.py, reconcile/templating/renderer.py, reconcile/test/templating/test_renderer.py, reconcile/utils/git.py
This introduces ClonedRepoGitlabPersistence, which uses local directory for read and gitlab api for writes. 
This drastically reduces API calls and speeds up the process overall. It also fixes a bug by introducing the persistence context.
=> Template Renderer use git clone

reconcile/saas_auto_promotions_manager/publisher.py, reconcile/saas_auto_promotions_manager/s3_exporter.py, reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py, reconcile/test/saas_auto_promotions_manager/s3_exporter/conftest.py, reconcile/test/saas_auto_promotions_manager/s3_exporter/test_s3_exporter.py, reconcile/test/saas_auto_promotions_manager/subscriber/conftest.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_multiple_publishers_for_single_channel.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_saas_files_use_target_config_hash.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_saas_files_with_auto_promote.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_saas_files_without_auto_promote.py
This PR brings improves several things in the SAPM S3 exporter:
- `app_name` is provided as part of the node. This is necessary because integrations using the publisher data will filter by `app_name`
- Information about whether or not a job is a test job is codified via `publish_job_logs`.
- If target is not defined, it defaults to `None` instead of default. This is more in line with other integrations we have.
- And more importantly, now all nodes that publish will be in the output, which is a changed compared with the current state, where only those that publish AND are being subscribed to by other nodes do appear.
=> Improvements to the SAPM S3 publisher

reconcile/openshift_base.py
if we try to apply a Job and the server objects due to fields being immutable - delete and re-apply the job.
=> [openshift] delete and apply Job on FieldIsImmutableError

tools/qontract_cli.py
Building on top of `qontract-cli get cidr-blocks`, with this we can get the latest available CIDR block for a new cluster. This can server as a building block for later automation of one yaml cluster provisioning.  Example: `qontract-cli --config config.debug.toml get cidr-blocks --for-cluster True --mask 24` Output:
```
INFO: Latest available network address: 10.170.71.0
INFO: You are reserving 256 network addresses.
You can use: 10.170.71.0/24
```
Note that this is only for cluster but not AWS resource VPC for now.
=> [CLI]Add cli option to get a cidr block for a new cluster.

reconcile/cli.py, reconcile/prometheus_rules_tester/integration.py, reconcile/test/test_prometheus_rules_tester.py
Passed in cluster_name is already an iterable, do not convert it to list anymore, so the namespace filter can use it correctly
[APPSRE-10066](https://issues.redhat.com/browse/APPSRE-10066)
=> Fix bug in prometheus rules tester

reconcile/jira_permissions_validator.py, reconcile/test/test_jira_permissions_validator.py
Those 401 messages are just annoying in #sd-appsre-reconcile.
=> :bug: jira-permission-validator: do not log sporadic 401 jira server errors

reconcile/utils/jira_client.py
`jiraclient.public_project` may hang because of missing HTTP timeout.
=> :bug: jiraclient: add timeout to public_project

reconcile/test/utils/test_oauth2_backend_application_session.py, reconcile/utils/oauth2_backend_application_session.py, reconcile/utils/rest_api_base.py, tools/cli_commands/cost_report/cost_management_api.py, tools/cli_commands/cost_report/view.py, tools/cli_commands/test/fixtures/aws_cost_report.md, tools/cli_commands/test/fixtures/empty_aws_cost_report.md, tools/cli_commands/test/test_cost_management_api.py, tools/cli_commands/test/test_cost_report.py, tools/qontract_cli.py, tools/test/test_qontract_cli.py
* rename `cost-report` to `aws-cost-report` to make it explicit as later we will have `openshift-cost-report`
* add retries to `CostManagementApi` due to sometimes got 504 gateway timeout from server
* Refactor `CostManagementApi` using new `ApiBase` from https://github.com/app-sre/qontract-reconcile/pull/4265
Note other code renames will be done in openshift cost report change.
[SDE-3693](https://issues.redhat.com/browse/SDE-3693)
=> Cost Report improvements

reconcile/utils/jira_client.py
`self.timeout` is not set, therefore just use the class defaults.
=> :bug: fix jiraclient timeout settings

reconcile/terraform_users.py
Do not run `terraform-users` for accounts were the integration is disabled. 
Ticket: [APPSRE-9978](https://issues.redhat.com/browse/APPSRE-9978)
=>  terraform-users: do not run PR checks for disabled accounts

reconcile/terraform_tgw_attachments.py
Do not run `terraform-tgw-attachments` for accounts were the integration is disabled. This will speedup the PR checks!
=> :bug: terraform-tgw-attachment: honor aws_account.disable.integrations during PR checks

reconcile/test/utils/vcs/conftest.py, reconcile/test/utils/vcs/test_vcs.py, reconcile/utils/vcs.py
We need a way to calculate the number of commits between 2 given commits. We extend the VCS util to calculate that diff. This is vcs agnostic, i.e., the consumer doesn't concern itself on whether the underlying repo url is gitlab or github.
=> APPSRE-10053 extend vcs to get diff

reconcile/terraform_users.py, reconcile/test/test_terraform_users.py
`terraform-users` should always ignore disabled accounts, also if running shared in dry run mode.
=> :bug: terraform-users: do not fail PR checks for disabled accounts

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_repo/terraform_repo.gql, reconcile/gql_definitions/terraform_repo/terraform_repo.py, reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
[APPSRE-8705](https://issues.redhat.com/browse/APPSRE-8705)
Implements new functionality for Terraform Repo based off of the [Milestone 1 design document](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/initiatives/terraform-repo-commercial.md?ref_type=heads#milestone-1-commercialize-terraform-repo).
Majority of this PR is updating GQL definitions to match my updates proposed in: https://github.com/app-sre/qontract-schemas/pull/579 and then produce a new output with those fields for the Terraform Repo Executor to use.
This adds two fields to a Terraform Repo representation in App Interface. The first of which allows a user to specify which version of the Terraform binary to use when planning/applying. The second allows them to load Vault secrets from a …
=> [tf-repo qr] Versioning and Improved Vault Secret Support

reconcile/cli.py, reconcile/jira_permissions_validator.py, reconcile/utils/jira_client.py
Enhance `jira-permissions-validator` with [extended early exit feature](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/runbook/extended-early-exit.md) to avoid hitting Jira API rate limits too often. Additionally, cache some API replies in `jiraclient`.
Tickets:
* [APPSRE-10091](https://issues.redhat.com/browse/APPSRE-10091)
* [APPSRE-10096](https://issues.redhat.com/browse/APPSRE-10096)
=> jira permissions validator: extended early exit

reconcile/utils/vcs.py
`vcs.get_file_content_from_app_interface_master` should accept file path strings starting with `data` as well.
Ticket: [APPSRE-10097](https://issues.redhat.com/browse/APPSRE-10097)
=> :bug: vcs: do not enforce 'data' in file path name

reconcile/aus/base.py, reconcile/utils/ocm/addons.py, reconcile/utils/ocm/base.py
an addon upgrade policy field name (`schedule_type`) in the new addon service is named differently compared to the previous version of the addon service.
instead of passing addon upgrade policy current state around as dicts, a dataclass has been introduced and the field name mismatches in the addon service versions are now contained in the implementation of the respective addon service access code.
part of https://issues.redhat.com/browse/APPSRE-10137
=> [AUS] bugfix addon upgrade policy field name mismatch

reconcile/utils/jump_host.py
Bastion should use localhost to connect directly to tinyproxy instead of using its hostname, so we don't need an lb listener for the tinyproxy port.
=> fix ssh_tunnel to use new bastion

reconcile/aus/base.py, reconcile/sql_query.py, reconcile/test/test_ocm_machine_pools.py, reconcile/test/test_status_board.py, reconcile/test/utils/merge_request_manager/conftest.py, reconcile/test/utils/merge_request_manager/test_merge_request_manager_.py, reconcile/test/utils/merge_request_manager/test_parser.py, reconcile/utils/ocm/base.py
**:white_check_mark: rename wrongly named test classes**
`pytest` uses `Test` as a pattern to discover tests. <- @janboll, @geoberle 
**:coffin: sql-query: fix deprecation warning**
=> fix test warnings

reconcile/saas_auto_promotions_manager/integration.py, reconcile/saas_auto_promotions_manager/merge_request_manager/desired_state.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py, reconcile/saas_auto_promotions_manager/merge_request_manager/reconciler.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py, reconcile/saas_auto_promotions_manager/meta.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_desired_state.py
We extract the calculation of SAPM desired promotion state into a dedicated class with proper tests. 
In a follow-up PR we will add soakDays logic, which will bring some substantial change to the DesiredState logic.
=> APPSRE-10117 refactor for SAPM soakDays

reconcile/gql_definitions/aws_account_manager/aws_accounts.gql, reconcile/gql_definitions/aws_account_manager/aws_accounts.py, reconcile/gql_definitions/introspection.json
Get `resourcesDefaultRegion` and `supportedDeploymentRegions` region related field.
Ticket: [APPSRE-9984](https://issues.redhat.com/browse/APPSRE-9984)
Depends on: https://github.com/app-sre/qontract-schemas/pull/638
=>  aws-account-manager: region related fields

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/ldap_groups/roles.gql, reconcile/gql_definitions/ldap_groups/roles.py, reconcile/ldap_groups/integration.py, reconcile/test/fixtures/ldap_groups/roles.yml, reconcile/test/ldap_groups/conftest.py, reconcile/test/ldap_groups/test_ldap_groups_integration.py, reconcile/utils/internal_groups/models.py
`ldap-groups` manage Rover notes and owners.
The goal is to enable our LDAP groups to be authZ groups for Bitwarden collections. Rover group requirements are:
* Rover group notes must contain the string `@BW@` somewhere
* At least 2 owners are set
Depends on: https://github.com/app-sre/qontract-schemas/pull/639
Tickets
* [APPSRE-10201](https://issues.redhat.com/browse/APPSRE-10201)
* [APPSRE-8399](https://issues.redhat.com/browse/APPSRE-8399)
=> :sparkles: ldap-groups: manage notes and owners

reconcile/saas_auto_promotions_manager/integration.py, reconcile/saas_auto_promotions_manager/merge_request_manager/batcher.py, reconcile/saas_auto_promotions_manager/merge_request_manager/desired_state.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py, reconcile/saas_auto_promotions_manager/merge_request_manager/mr_parser.py, reconcile/saas_auto_promotions_manager/merge_request_manager/open_merge_requests.py, reconcile/saas_auto_promotions_manager/merge_request_manager/reconciler.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py, reconcile/saas_auto_promotions_manager/meta.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_merge_request_manager.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_mr_parser.py, reconcile/test/saas_auto_promotions_manager/merge_request_manager/merge_request_manager/test_reconciler.py, reconcile/test/saas_auto_promotions_manager/test_integration_test.py
SAPM MRs now hold a `kind` attribute. a MR can be of kin `scheduler` or `batcher`. The `batcher` is what we already actively use today. In follow-up PRs, we will create a `Scheduler` component that will handle SAPM MRs of kind `scheduler`, separate from the batcher.
=> APPSRE-10117 SAPM introduce MR kind

dockerfiles/Dockerfile
Removing the `/run-integration.py` argument in the FIPS image entrypoint. The reason being that this will break Jenkins builds as they attempt to perform a docker/podman run.
`podman run --rm ... quay.io/app-sre/qontract-reconcile-fips:9a81949 qontract-reconcile --config /config/config.toml ...` will evaluate to actually running the following command in the container:
`/tini -- /run-integration.py qontract-reconcile --config /config/config.toml ...` when it should just run `/tini -- qontract-reconcile --config /config/config.toml ...`
=> update entrypoint for tini

reconcile/utils/promotion_state.py, reconcile/utils/saasherder/saasherder.py
Reverts app-sre/qontract-reconcile#4319
```
File "/usr/local/lib/python3.11/site-packages/reconcile/cli.py", line 608, in run_class_integration
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 161, in run_integration_cfg
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 170, in _integration_wet_run
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/integration.py", line 315, in run
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/defer.py", line 13, in func_wrapper
return func(*args, …
```
=> Revert "[saasherder] add check_in date to promotion data"

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/test/test_openshift_saas_deploy.py, reconcile/utils/oc.py, reconcile/utils/openshift_resource.py, reconcile/utils/saasherder/saasherder.py
https://issues.redhat.com/browse/APPSRE-10198
Use generateName instead of timestamp to create a unique PipelineRun name. https://ibm.github.io/tekton-tutorial-openshift/lab1/6_create-pipeline-run/. And fix PipelineRun name too long to retrigger issue.
`
admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: Invalid resource name: length must be no more than 63 characters: metadata.name
`
=> [APPSRE-10198] Use generateName instead of timestamp to create a unique PipelineRun name

reconcile/terraform_repo.py
Schema changes to the [`/aws/terraform-repo-1.yml` schemas](https://github.com/app-sre/qontract-schemas/blob/main/schemas/aws/terraform-repo-1.yml) require Terraform Repo's internal concept of state to be recreated. 
My initial approach was to simply have tf-repo go in and recreate its own statefiles with no terraform plan/apply, however that doesn't provide much confidence that future plans and applies will be executed without issue. Therefore, I've updated the function to run plans and applies when tf-repo's own state is recreated.
=> [tf-repo] change behavior when state has to be recreated

reconcile/dashdotdb_dora.py
catch new error:
```
dashdotdb_dora.run()
File "/usr/local/lib/python3.11/site-packages/reconcile/dashdotdb_dora.py", line 305, in run
] = threaded.run(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sretoolbox/utils/threaded.py", line 72, in run
return pmap(func,
^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sretoolbox/utils/concurrent.py", line 87, in pmap
return list(pool.map(func_partial, iterable))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
yield _result_or_cancel(fs.pop())
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
return fut.result(timeout)
^^^^^^^^^^^^^^^^^^^
File …
```
=> dashdotdb-dora catch none saas files

dockerfiles/Dockerfile
Followup to #4315
According to [this issue](https://github.com/moby/moby/issues/5147) & [stackoverflow](https://stackoverflow.com/questions/49028644/is-cmd-in-parent-docker-overriden-by-cmd-entrypoint-in-child-docker-image) along with running a `docker inspect` on the FIPS image:
when using a multistage build, if you define an entrypoint in the child image, the `CMD` is set to `null` which breaks functionality on OpenShift. I've updated the Dockerfile to match [Tini's recommend method](https://github.com/krallin/tini?tab=readme-ov-file#using-tini) in light of this.
=> [fips image] add CMD

reconcile/statuspage/atlassian.py, setup.py
* the underlying library is not maintained anymore
* the library has no type annotated
* the library does not support pagination which becomes important for this API
=> [status-page-components] deprecate usage of transity-statuspageio

reconcile/utils/saasherder/saasherder.py
`Image` default timeout as `None`, will cause integration hang indefinitely, set `timeout` on usage to avoid that.
Fix [ASIC-549](https://issues.redhat.com/browse/ASIC-549)
=> Add timeout to Image request

grafana-dashboards/sre-capability-idp.configmap.yaml
Update the prometheus data source off the RHIDP dashboard because `sre-capabilities` has been migrated to appsrep09ue1.
=> update prometheus datasource for sre-capabilities related dashboards

reconcile/statuspage/atlassian.py, reconcile/statuspage/integrations/maintenances.py, tools/qontract_cli.py
follows up on https://github.com/app-sre/qontract-reconcile/pull/4344 and #4348
in this PR we add a condition to only manage scheduled maintenances.
=> [status-page-maintenances] only manage scheduled maintenances

reconcile/statuspage/integrations/maintenances.py
follows up on https://github.com/app-sre/qontract-reconcile/pull/4344
in this PR we limit the scope of maintenances to return only to ones that were created by the integration:
https://github.com/app-sre/qontract-reconcile/blob/e1238a0e29bded55c993a362da20ae1f3636ab1c/reconcile/statuspage/atlassian.py#L421-L425
this is because we want to allow maintenances to be managed from both the integrations and by humans. the integration can not be authoritative, and the binding is used to determine if a maintenance is owned by the integration or not.
=> [status-page-maintenaces] only return maintenances with bindings

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/utils/external_resources.py
RDS/IAM Role resources with te `managed_by_erv2` attribute set to True should not be taken by terraform-resources
=> Filter out managed_by_erv2 resources from Terraform_resources

reconcile/cli.py, reconcile/slack_usergroups.py
This implements extended early exit for slack usergroups integration. 
- Payload is not set in Result, since the state data structure is not JSON hashable (using sets)
- This does not reduce the runtime by much (around. 1/5th). It drastically reduces API requests towards slack, which caused API rate liming errors in the past. More caching for computing desired state would be required to further reduce runtime.
=> Add extended early exit

reconcile/cli.py, reconcile/ocm_labels/integration.py, reconcile/test/ocm_labels/conftest.py, reconcile/test/ocm_labels/test_ocm_labels_integration.py
`ocm-labels` must ignore `sre-capabilities.rhidp` because it's managed by `cluster-auth-rhidp`. Having a `--ignored-label-prefixes` command line option makes the integration setting easier to maintain.
Ticket: [APPSRE-8307](https://issues.redhat.com/browse/APPSRE-8307)
=> :sparkles: ocm-labels: add --ignored-label-prefixes command line option

run-test-container-image.sh
When working on https://github.com/app-sre/terraform-repo-executor/pull/22, I noticed that one error case didn't return an error on failure so fixing that here.
=> [cst] add a missing error return

reconcile/utils/secret_reader.py, reconcile/utils/vault.py
Stacked `@retry` definitions multiply the retry attempts for a function call. 
```python 
@retry()  
def func1():
func2()
@retry() 
def func2():
do_stuff
```
`retry` has a default `max_attemps=3`. In case of failure in `func2`, `func1` will be retried 9 times.
=> Remove stacked retry() calls in secrets_reader

reconcile/test/test_three_way_diff_strategy.py, reconcile/utils/openshift_resource.py, reconcile/utils/three_way_diff_strategy.py
The diff strategy was not detecting missing annotations in the current objects if they were removed outside of QR.
=> fix annotations comparison in 3way diff strategy

reconcile/statuspage/integrations/maintenances.py
part of https://issues.redhat.com/browse/APPSRE-10268
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/106453
this PR adds a slack output when a maintenance is less then an hour away. using state, we guarantee the notification is only sent once.
=> [status-page-maintenances] slack output

reconcile/ocm_aws_infrastructure_access.py
`clusters` already fetched in `run`, but not passed to `fetch_desired_state`, causing desired state still contain clusters with the integration disabled, causing error in reconcile (`KeyError` when trying to get cluster).
[ASIC-550](https://issues.redhat.com/browse/ASIC-550)
=> [ocm-aws-infrastructure-access] Fix desired state not checking enabled

reconcile/gitlab_permissions.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-10271
depends on https://github.com/app-sre/qontract-schemas/pull/656
by adding `managePermissions: false`, a code component owner can define to avoid having AppSRE team members added to the repository as Maintainers.
=> [gitlab-permissions] exclude repositories with manage permissions false

reconcile/test/aws_account_manager/test_aws_account_manager_reconciler.py, reconcile/test/utils/test_state.py, reconcile/utils/state.py, requirements/requirements-test.txt, requirements/requirements-type.txt, setup.py
Fix
```
qontract-reconcile 0.10.1rc831 requires boto3==1.34.94, but you have boto3 1.34.15 which is incompatible.
qontract-reconcile 0.10.1rc831 requires botocore==1.34.94, but you have botocore 1.34.15 which is incompatible.
qontract-reconcile 0.10.1rc831 requires urllib3~=2.2, but you have urllib3 2.0.7 which is incompatible.
```
=> :heavy_minus_sign: do not install old botocore

reconcile/gql_definitions/common/app_code_component_repos.gql, reconcile/gql_definitions/common/app_code_component_repos.py, reconcile/typed_queries/repos.py, tools/cli_commands/systems_and_tools.py
depends on https://github.com/app-sre/qontract-schemas/pull/494
follows up on #4384
adds output to the report for every repository mentioned in app codeComponents if the resource equals app-interface.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/106876
=> [qontract-cli] get systems-and-toold include app-interface instances

reconcile/utils/jinja2/utils.py
allows converting structures from data files into flat dicts.
a possible use case is to take a cluster upgradePolicy and use it as labels.
=> expose flatten to openshift resource templating

reconcile/utils/saasherder/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-10312
the commit sha is generally used to figure out IMAGE_TAG (first N chars, usually 7, of the commit sha).
in case a team needed the full 40, they could specify `hash_length: 40` and be done with it.
what if some teams needs both?
by adding `COMMIT_SHA`, we always provide the full 40. this allows to keep using IMAGE_TAG for images.
example requirement:
deploying a ConfigMap for HyperShift Operator that includes the following section:
```
hypershift-operator: quay.io/acm-d/rhtap-hypershift-operator:dcb53a0aba273de04ded0285aa4a2c5a63a04ed2
```
`dcb53a0` / `dcb53a0aba273de04ded0285aa4a2c5a63a04ed2` are the image tag / commit sha.
=> saasherder autogenerate parameter COMMIT_SHA

reconcile/utils/three_way_diff_strategy.py
Followup to #4368, see [slack discussion here](https://redhat-internal.slack.com/archives/GGC2A0MS8/p1716990846684109)
The following is considered valid YAML for an OpenShift Route:
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
annotations:
name: cool-route
namespace: app-interface
```
`annotations` can be left blank which will result in this function failing when trying to read `annotations.items()` as it is trying to call `.items()` on a `NoneType` object. This fix ensures that if `annotations = None`, then an empty dictionary will be returned.
=> bug fix for normalizing openshift resources with Null annotations

reconcile/typed_queries/pagerduty_instances.py
in an attempt to run `qc get systems-and-tools` on sre-capabilities, there is no pagerduty in that repository.
generally, the code should accept multiple situations. slack-usergroups should be able to run for repos without pagerduty.
this PR makes the behavior more forgiving.
=> do not raise on no pagerduty instances

reconcile/gql_definitions/advanced_upgrade_service/aus_clusters.py, reconcile/gql_definitions/advanced_upgrade_service/aus_organization.py, reconcile/gql_definitions/fragments/aus_organization.gql, reconcile/gql_definitions/fragments/aus_organization.py, reconcile/gql_definitions/introspection.json, reconcile/ocm_upgrade_scheduler_org_updater.py, reconcile/test/ocm/aus/fixtures.py, reconcile/utils/mr/ocm_upgrade_scheduler_org_updates.py, tools/cli_commands/systems_and_tools.py
depends on https://github.com/app-sre/qontract-schemas/pull/660
with this addition we can run the report on sre-capabilities and expose OSD-FM managed clusters.
output: https://gitlab.cee.redhat.com/service/sre-capabilities-output/-/blob/main/systems-and-tools.md
=> [qontract-cli] get systems-and-tools collect clusters from ocm organizations

reconcile/aws_saml_idp/integration.py, reconcile/cli.py
Add extended early exit to `aws-saml-idp` to speed up PR checks.
Ticket: [APPSRE-10276](https://issues.redhat.com/browse/APPSRE-10276)
=>  aws-saml-idp: add extended early exit

reconcile/aws_saml_roles/integration.py, reconcile/cli.py
Add extended early exit to `aws-saml-roles` to speed up PR checks.
Ticket: [APPSRE-10277](https://issues.redhat.com/browse/APPSRE-10277)
=>  aws-saml-roles: add extended early exit

pyproject.toml, reconcile/openshift_resources.py, reconcile/openshift_resources_base.py
This PR fixes the mocking of some jinja2 template functions during the PR checks. The goal is to prevent any external requests to speedup them. 
Initially, the plan was to add an extended early exit, but the integration needs a lot of time to compute the desired state, which would also be used in the extended early exit; therefore it doesn't make any sense.
Ticket: [APPSRE-8726](https://issues.redhat.com/browse/APPSRE-8726)
Review commit by commit:
1. :recycle: openshift-resources-base: add type hints
2. fix early exit
=> ✨ openshift-resources: bugfix

reconcile/gql_definitions/common/aws_vpc_requests.py, reconcile/gql_definitions/fragments/aws_vpc_request.gql, reconcile/gql_definitions/fragments/aws_vpc_request.py, reconcile/gql_definitions/introspection.json, reconcile/terraform_vpc_resources/integration.py, reconcile/test/terraform_vpc_resources/test_terraform_vpc_resources_integration.py, reconcile/utils/terrascript_aws_client.py
Related to: [APPSRE-8743](https://issues.redhat.com/browse/APPSRE-8743)
After the deployment I've found some issues in the integration code:
Due to the way sharding is done in production the integration floods the reconcile channel in Slack. That is because most of the accounts don't have vpc-requests and if you pass one account (what is done in the shards) the integration raises an error. That was done to warn the user that they are not creating anything and do an early exit.
Also, if the integration is run without shards but there is no vpc-request defined, i.e. all the previously defined vpc-requests are deleted in app-interface, the integration skips the terraform apply step. That was also done to early exit.
=> Fix terraform vpc resources exit conditions

README.md, reconcile/cli.py, reconcile/openshift_prometheus_rules.py, reconcile/openshift_resources_base.py
Introduce `openshift-prometheus-rules` as a separate integration that handles prometheus rule for namespace `openshiftResources`. Similar to `openshift-routes` or `openshift-vault-secrets`. This will speed up app-interface PR checks.
Ticket: [APPSRE-10344](https://issues.redhat.com/browse/APPSRE-10344)
=> openshift resources prometheus rules

reconcile/test/test_three_way_diff_strategy.py, reconcile/utils/three_way_diff_strategy.py
part of https://issues.redhat.com/browse/APPSRE-10344
a fix on top of #4411
we currently ignore the integration annotation. in the above mentioned PR, existing resources are going to be managed by a new integration and we must update them in-place.
=> explicitly return diff when a resource switches integrations

reconcile/cli.py, reconcile/external_resources/integration.py, reconcile/external_resources/integration_secrets_sync.py, reconcile/external_resources/manager.py, reconcile/external_resources/meta.py, reconcile/external_resources/secrets_sync.py, reconcile/external_resources/state.py, reconcile/gql_definitions/external_resources/external_resources_modules.gql, reconcile/gql_definitions/external_resources/external_resources_modules.py, reconcile/gql_definitions/external_resources/external_resources_settings.gql, reconcile/gql_definitions/external_resources/external_resources_settings.py, reconcile/gql_definitions/introspection.json, reconcile/test/external_resources/test_manager.py, reconcile/test/external_resources/test_secrets_sync.py, reconcile/utils/external_resource_spec.py, reconcile/utils/openshift_resource.py
This PR introduces an integration to sync External resource outputs from Vault into the target clusters.
As discussed in the design, ERv2 will continuously sync the outputs from Vault instead of running Terraform for all the resources at each iteration.
The full Picture: 
ERv2 Resource ACTION (Create or Update) -> It will update Vault and Sync the Outputs into the target cluster. 
ERv2 Secrets Sync Integration -> Will loop over all Outputs and sync them into clusters to ensure the Outputs desired state.
Requires: 
* https://github.com/app-sre/qontract-schemas/pull/654/files
=> Introduce ERv2 Outputs sync integration

reconcile/gitlab_permissions.py
fixes below issue while sharing project with app-sre group
```
gitlab.exceptions.GitlabCreateError: 409: Project cannot be shared with the group it is in or one of its ancestors.
```
=> fix parent group exception for gitlab-permissions

reconcile/utils/gql.py
for usage with `qontract-reconcile --no-validate-schemas`
=> ignore missing integration file when not validating schemas

reconcile/slack_usergroups.py, reconcile/test/test_slack_usergroups.py, reconcile/utils/slack_api.py
api ref: https://api.slack.com/methods/users.list
deleted users still appear in the system, with a `deleted` attribute. let's avoid acting on deleted users, unless we are very intentional (like when emptying a usergroup).
=> [slack-usergroups] ignore deleted users

reconcile/test/conftest.py, reconcile/test/utils/test_promotion_state.py, reconcile/utils/promotion_state.py, reconcile/utils/saasherder/saasherder.py
Saas promotion data will now be cached. The cache is disabled by default, to be fully backwards-compatible.
In a follow-up PR, saasherder will need to run more queries on promotion data - most of it will be redundant, but for saasherder logic it will be easier to not concern itself with the caching aspect.
=> APPSRE-10351 promotion data cache

reconcile/gql_definitions/common/aws_vpc_requests.py, reconcile/gql_definitions/fragments/aws_vpc_request.gql, reconcile/gql_definitions/fragments/aws_vpc_request.py, reconcile/gql_definitions/introspection.json
This will enable us to delete the resources created by the integration by using the `deletionApprovals` object in app-interface.
Related to: [APPSRE-8743](https://issues.redhat.com/browse/APPSRE-8743)
=> :bug: Add enableDeletions and deletionApprovals to vpc_requests query

reconcile/templating/renderer.py, reconcile/test/templating/test_renderer.py
This allows this kind of variable settings in template collections:
```
variables:
static:
parentApp: app-sre
dynamic:
- name: parentApp
query: |
{
apps: apps_v1
(name: "{{ static.parentApp }}")
{
path
}
}
```
=> template-renderer: allow using variables in dynamic variables

reconcile/terraform_vpc_resources/integration.py
To avoid using empty outputs we are using the `init_outputs` method before `_handle_outputs`.
=> Fix terraform vpc resources inint outputs

reconcile/terraform_vpc_resources/integration.py
If we create the outputs this can lead to a vpc data file being created with an empty `vpc_id`.
=> :bug: Don't create outputs for deleted requests

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/templating/template_collection.gql, reconcile/gql_definitions/templating/template_collection.py, reconcile/templating/renderer.py, reconcile/test/templating/test_renderer.py
https://issues.redhat.com/browse/APPSRE-10379
depends on https://github.com/app-sre/qontract-schemas/pull/667
Example in a template-collection:
```yaml
forEach:
items:
- cluster_name: app-sre-prod-01
value: value1
- cluster_name: app-sre-prod-04
value: value2
variables:
static:
foo: FOO
bar: "This is for value {{ foreach_item.value }}"
dynamic:
- name: cluster
query: |
{
clusters: clusters_v1(filter: {
name: "{{ foreach_item.cluster_name }}"
})
{
name
consoleUrl
}
}
```
=> template-renderer: foreach loop

reconcile/openshift_base.py, reconcile/utils/oc.py
part of https://issues.redhat.com/browse/APPSRE-10378
Because of several escaping and the last-applied-configuration holds an older version of the enormous grafana JSON.
There is a potential solution that could work-removing the existing last-applied-configuration annotation before oc apply.
=> oc apply handle request entity too large

reconcile/glitchtip_project_alerts/integration.py, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.gql, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.py, reconcile/gql_definitions/introspection.json, reconcile/test/fixtures/glitchtip/project_alerts.yml, reconcile/test/glitchtip/test_glitchtip_project_alerts.py
Add support for Jira components and custom issue type.
Ticket: [APPSRE-10356](https://issues.redhat.com/browse/APPSRE-10356)
Depends on:
* https://github.com/app-sre/qontract-schemas/pull/671
* https://github.com/app-sre/glitchtip-jira-bridge/pull/16
=> :sparkles: glitchtip-project-alerts: support Jira components and issue type

tools/qontract_cli.py, tools/saas_promotion_state/saas_promotion_state.py, tools/test/conftest.py, tools/test/test_saas_promotion_state.py
qontract-cli command to help debugging saas deploy state. The command lists all publisher states from S3 for a given channel/sha
```
qontract-cli --config config.cli.toml get-promotion-state --channel my-channel --sha my-sha
Last state for publisher with ID 398f48dcaa4bbcac0a95f7ad0d94211d7c212bd0:
success=True target_config_hash='ada2226de1208856' saas_file='saas-file-name' check_in='2024-06-10 08:34:58.595463+00:00'
```
=> APPSRE-10351 fetch saas state via cli

tools/qontract_cli.py, tools/saas_promotion_state/saas_promotion_state.py, tools/test/test_saas_promotion_state.py
qontract-cli tool to override last saas deploy state as successful. This can be necessary to unblock auto-promotions.
=> APPSRE-10351 mark saas deploy state successful

reconcile/test/utils/vcs/conftest.py, reconcile/test/utils/vcs/test_vcs.py, reconcile/utils/vcs.py
A branch in app-interface must be deleted when its MR gets closed.
=> APPSRE-10406 delete branch when close mr

reconcile/aws_account_manager/integration.py, reconcile/gql_definitions/aws_account_manager/aws_accounts.gql, reconcile/gql_definitions/aws_account_manager/aws_accounts.py, reconcile/gql_definitions/introspection.json, reconcile/test/aws_account_manager/test_aws_account_manager_integration.py
If `account-request.uid` is specified, `aws-account-manager` will take over an existing account instead of creating a new one.
Ticket: [APPSRE-10430](https://issues.redhat.com/browse/APPSRE-10430)
Depends on: https://github.com/app-sre/qontract-schemas/pull/672
=> :sparkles: aws-account-manager: support takeover of existing accounts

reconcile/test/utils/test_jira_client.py, reconcile/utils/jira_client.py
Disable JIRA library logs like
```
[jira-permissions-validator] Request rate limited by Jira. Request should be retried after 0 seconds.
[jira-permissions-validator] 5 tokens are issued every 1 seconds.
[jira-permissions-validator] You can accumulate up to 5 tokens.
[jira-permissions-validator] Consider adding an exemption for the user as explained in: https://confluence.atlassian.com/adminjiraserver/improving-instance-stability-with-rate-limiting-983794911.html
[jira-permissions-validator] Got recoverable error from GET https://issues.redhat.com/rest/api/2/mypermissions, will retry [1/3] in 1.413039281676533s. Err: 429 Too Many Requests
```
=> jira-permissions-validator: disable JIRA logs

reconcile/test/ocm/test_utils_ocm_clusters.py, reconcile/utils/ocm/base.py, reconcile/utils/ocm/clusters.py
Extending OCM lib to query service clusters and provision shards.
Note, that for querying service clusters we use the OSDFleetManager API, which uses different internal cluster ids than our cluster management API.
The idea is to query the `/provision_shard` of an HCP cluster and compare that to a list of service clusters we got from OSDFleetManager API.
=> APPSRE-10229 OCM get service clusters

reconcile/templates/rosa-classic-cluster-creation.sh.j2, reconcile/templates/rosa-hcp-cluster-creation.sh.j2, reconcile/test/fixtures/rosa/rosa_classic_script_result.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_dry_run.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_no_provision_shard.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_private.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_reuse_oidc_config.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_uwm_enabled.sh
`initial_version` spec is meant to be used at first while `version` is usually backfilled by AppSRE bot.
=> Use initial_version instead of version when creating cluster.

helm/README.md
documentation enhancement to show the connection between integrations-manager and the helm chart.
=> add integration spec reference to qontract-schemas

reconcile/utils/jjb_client.py
a disabled job does not require a webhook
=> [jenkins-webhooks] skip disabled jobs

reconcile/terraform_resources.py, reconcile/test/utils/test_terraform_client.py, reconcile/utils/terraform_client.py
Follow up on https://github.com/app-sre/qontract-reconcile/pull/3576
Skip validation when no target upgrade info available.
[APPSRE-7777](https://issues.redhat.com/browse/APPSRE-7777)
=> [terraform-resources] skip validation when no target upgrade info available for RDS

reconcile/templating/validator.py, reconcile/test/templating/test_validator.py
Handle unset `/app-interface/template-test-1,expectedToRender` like `/app-interface/template-test-1.expectedToRender: true`. Otherwise, if `expectedToRender` is not set, tests may not work correctly.
=> :bug: template-validator: expectedToRender must be default True

reconcile/openshift_base.py
to avoid the last-applied annotation. This may still fail if the resource is still too big, but then we cannot do more!
error:
```
for: "STDIN": error when patching "STDIN": Request entity too large: limit is 3145728
```
https://issues.redhat.com/browse/APPSRE-10378
The previous fix from https://github.com/app-sre/qontract-reconcile/pull/4437/files was trying to remove the annotation from the existing resource and then still used `apply`, which contains the annotation and fails.
=> handle RequestEntityTooLargeError by using `oc create` or `oc replace`

reconcile/utils/saasherder/saasherder.py
depends on #4479
this PR changes the `helm` provider from only using target level parameters to all supported levels, including secret parameters.
=> [saasherder] enable usage of all levels of parameters for provider helm

reconcile/utils/jjb_client.py
All jobs are currently always skipped as `disable` is a string containing `"true"` or `"false"` and thus always evaluating to `True`. This fix should allow both booleans and strings to be accepted.
Fixing https://github.com/app-sre/qontract-reconcile/pull/4451
cc @maorfr
=> fix: all jobs are currently always skipped

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/templating/template_collection.gql, reconcile/gql_definitions/templating/template_collection.py, reconcile/gql_definitions/templating/templates.gql, reconcile/gql_definitions/templating/templates.py, reconcile/templating/lib/rendering.py, reconcile/templating/renderer.py, reconcile/templating/validator.py, reconcile/test/templating/test_renderer.py, reconcile/utils/jinja2/utils.py
Make the jinja [whitespace control](https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control) behavior configurable for a template by introducing `trim_blocks`, `lstrip_blocks`, and `keep_trailing_newline` as `templateRenderOptions`. The default will still be `False` for all three options.
Depends on: https://github.com/app-sre/qontract-schemas/pull/675
=> :sparkles: template-renderer: make the jinja2 whitespace control behavior configurable

reconcile/test/test_saasherder.py, reconcile/utils/promotion_state.py, reconcile/utils/saasherder/saasherder.py
Adding a `has_succeeded_once` attribute to our openshift-saas-deploy state data.
Currently, saasherder validation can fail for unrelated targets in a saas file if any targets re-deployment failed (e.g., due to parameter changes).
The idea of this flag is to remember if a promotion for a ref has ever been successful. If we deploy a publisher ref multiple times (e.g., due to parameter change), we each time override the state with the latest result. This might lead to saas files failing validation in unexpected situations (they worked once for a ref, but then stop at some point for that same ref in a completely unrelated target).
By remembering if a deployment ever succeeded, we neglect potential issues stemming from re-deployments.
Note, that SAPM will still fully rely on latest state only. …
=> APPSRE-10351 remember if promotion was successful

reconcile/templating/lib/merge_request_manager.py, reconcile/templating/lib/model.py, reconcile/templating/renderer.py, reconcile/test/templating/test_renderer.py
fix https://github.com/app-sre/qontract-reconcile/pull/4429
according to https://github.com/app-sre/qontract-reconcile/blob/e58b957b523d0dd46f0197eb41dd5fcd73569439/reconcile/templating/lib/merge_request_manager.py#L237-L250 for a single template collection, it can only open one MR at the same time. So all outputs generated by one collection should be written together to be included in one MR. (Failed example:   https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/108782)
Meanwhile, template_hash should include all unpack variables to detect collection changes.
=> fix template foreach loop

reconcile/utils/saasherder/models.py, reconcile/utils/saasherder/saasherder.py
set `image.tag` parameter (values) by default to match provider `openshift-template` behavior: https://github.com/app-sre/qontract-reconcile/blob/57bf641261bc966627f6e0120b1b9c923249461b/reconcile/utils/saasherder/saasherder.py#L916
=> [saasherder] set image.tag by default in helm provider

reconcile/gitlab_housekeeping.py, reconcile/utils/gitlab_api.py
part of https://issues.redhat.com/browse/APPSRE-10433
this PR attempts to add a metric for remaining days of personal access tokens until expiration. we can use these metrics for alerting.
=> [gitlab-housekeeping] publish personal access token expiration metrics

reconcile/gitlab_fork_compliance.py
part of https://issues.redhat.com/browse/APPSRE-10450
follow up on #4467
```
reconcile/gitlab_fork_compliance.py:67: UserWarning: Calling a `list()` method without specifying `get_all=True` or `iterator=True` will return a maximum of 20 items. Your query returned 20 of 29 items. See https://python-gitlab.readthedocs.io/en/v4.6.0/api-usage.html#pagination for more details. If this was done intentionally, then this warning can be supressed by adding the argument `get_all=False` to the `list()` call.
maintainers = group.members.list()
```
=> [gitlab-fork-compliance] group.members.list iterator=True

reconcile/utils/gitlab_api.py
After python-gitlab [upgraded](https://github.com/app-sre/qontract-reconcile/pull/4467), `all` is conflict with current `get_items`, either use `group.projects.list(get_all=True)` or `get_items(group.projects.list)`.
=> Fix infinite get group projects

reconcile/gql_definitions/ocm_labels/organizations.gql, reconcile/gql_definitions/ocm_labels/organizations.py, reconcile/ocm_labels/integration.py
query for `disable.integrations` and consider it for ocm orgs for ocm-labels
=> [ocm-labels] enable disabling integration per ocm org

reconcile/templates/rosa-classic-cluster-creation.sh.j2, reconcile/templates/rosa-hcp-cluster-creation.sh.j2, reconcile/test/fixtures/rosa/rosa_classic_script_result.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_dry_run.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_no_provision_shard.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_private.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_reuse_oidc_config.sh, reconcile/test/fixtures/rosa/rosa_hcp_script_result_uwm_enabled.sh
partially revert #4136 
supporting a single cluster per aws account is an AppSRE decision for managing our own clusters.
app-interface, as a tool, should be able to support multiple clusters in an aws account. open source ftw :tada: 
we can add a safety net in app-interface to enforce that every cluster in the AppSRE OCM org is in a unique aws account. this should not be a code limitation.
=> [ocm-clusters] do not enforce one HCP cluster per AWS account

reconcile/gitlab_labeler.py
No longer needed, we're moving to rhel8 for app-interface MR builds.
This reverts commit b38a1f7bcf840e633c5c459b5fbe32ac73572832.
=> Revert "Add test-on-rhel8-ai label to app-sre MRs (#4466)"

reconcile/test/utils/dynatrace/conftest.py, reconcile/test/utils/dynatrace/test_dynatrace_client.py, reconcile/utils/dynatrace/client.py
When a token is created, it has the secret and an id. We should return both to the caller.
=> APPSRE-10229 return token id too

reconcile/gql_definitions/common/clusters.gql, reconcile/gql_definitions/common/clusters.py, reconcile/gql_definitions/introspection.json, reconcile/ocm/types.py, reconcile/ocm_clusters.py, reconcile/templates/rosa-hcp-cluster-creation.sh.j2, reconcile/test/fixtures/rosa/rosa_hcp_script_result_billing_account.sh, reconcile/test/utils/rosa/test_rosa_hcp_script_template.py, tools/qontract_cli.py
part of https://issues.redhat.com/browse/APPSRE-10457
depends on https://github.com/app-sre/qontract-schemas/pull/681
with this change we can explicitly define an aws account to act as the billing account. even... self.
=> ROSA HCP provisioning support explicit aws billing account

reconcile/utils/saasherder/saasherder.py
required to deploy raw files inside a directory with files able to contain multiple documents (`---`)
example: https://github.com/stackrox/acs-fleet-manager/tree/main/dp-terraform/helm/rhacs-terraform/crds
=> [openshift-saas-deploy] process multiple documents in each file

reconcile/cli.py, reconcile/templating/lib/rendering.py, reconcile/templating/renderer.py, reconcile/test/fixtures/templating/full.yaml, reconcile/test/fixtures/templating/patch_path_template.yaml, reconcile/test/templating/lib/test_patch_rendering.py, reconcile/test/templating/test_renderer.py, reconcile/utils/gitlab_api.py
This PR has several `template-renderer` improvements and bugfixes:
`template.patch.path` can be a template, too.
`-clone-repo` command line option is a flag
Strip whitespaces and new lines from `targetPath`. Especially useful if `targetPath` is multiline and a template. 
In case two templates are dependent, e.g., the 1st one introduces an `openshiftResource` for an AWS account, and the 2nd adds an additional resource, then the internal file cache must have the result from the 1st one. See [this as an example](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/109948/diffs#e159c5d0c1477875efa58ad0e33e050a7fa84e98_444_416). `aws-resource-exporter` introduces `provisioner: $ref: /aws/jeanluc/account.yml` and `cloudwatch-exporter` adds another `resource.provider: …
=> template renderer improvements

reconcile/templating/renderer.py
fix https://github.com/app-sre/qontract-reconcile/pull/4499/commits/65a97e0fc556b277a6462b4a11f93a64a835f92c
outputs should be emptied for each template collection, and we should do nothing if ClonedRepoGitlabPersistence gets no output.
=> fix ClonedRepoGitlabPersistence

reconcile/dynatrace_token_provider/integration.py
Catching error in label discovery call. We want to process all ocm envs, even if one is failing.
=> APPSRE-10229 catch exception

reconcile/utils/saasherder/saasherder.py
`image` is sometimes just a string.
=> saasheder fix helm image.tag handling to consider image not a map

reconcile/gitlab_housekeeping.py, reconcile/test/test_gitlab_housekeeping.py, reconcile/utils/gitlab_api.py, reconcile/utils/saasherder/saasherder.py, reconcile/utils/terrascript_aws_client.py, tools/qontract_cli.py
We use `per_page=1` in `list` to get first item back, new `python-gitlab` requires explicit set `get_all` or `page`, so it will be `.list(per_page=1, page=1)`.
> UserWarning: Calling a `list()` method without specifying `get_all=True` or `iterator=True` will return a maximum of 1 items. Your query returned 1 of many items. See https://python-gitlab.readthedocs.io/en/v4.6.0/api-usage.html#pagination for more details. If this was done intentionally, then this warning can be supressed by adding the argument `get_all=False` to the `list()` call.
Also fixed a few other places when calling `list()` without specifying `get_all` or `iterator`.
=> Suppress warnings when list items using gitlab api

reconcile/gql_definitions/common/users.py, reconcile/gql_definitions/fragments/user.gql, reconcile/gql_definitions/fragments/user.py, reconcile/gql_definitions/openshift_groups/managed_roles.py, reconcile/gql_definitions/slack_usergroups/permissions.py, reconcile/gql_definitions/slack_usergroups/users.py, reconcile/slack_usergroups.py, reconcile/test/fixtures/slack_usergroups/permissions.yml, reconcile/test/fixtures/slack_usergroups/users.yml, reconcile/test/test_gitlab_members.py, reconcile/test/test_slack_usergroups.py
in our use case, such groups are used for PR review requests on slack.
if a user sets `tag_on_merge_requests: false`, they shouldn't be pinged for reviews, not in gitlab (current implementation) and not in slack as well.
=> [slack-usergroups] do not add users with tag_on_merge_requests false to groups from OWNERS files

reconcile/test/ocm/test_utils_ocm_manifest.py, reconcile/utils/ocm/manifests.py
This is  a copy of the existing tests and implementation of Syncset. No changes apart from naming have been made. There is no intent of optimizing the current syncset tests/implementation.
=> APPSRE-10229 add ocm manifests API

reconcile/statuspage/atlassian.py, reconcile/statuspage/integrations/maintenances.py, reconcile/statuspage/page.py
The API might return a different precision than what we put in app-interface. Lets compare diffs based on datetime.
=> use datetime instead of str

reconcile/terraform_resources.py, reconcile/test/utils/test_aws_api.py, reconcile/test/utils/test_terraform_client.py, reconcile/utils/aws_api.py, reconcile/utils/terraform_client.py
Follow up on #4464
Use `IncludeAll` in [DescribeDBEngineVersions](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBEngineVersions.html), this will return all versions including deprecated ones.
So we can assume all current RDS versions can always fetch related info back, test case for empty valid upgrade target fallback to normal target not found case.
[APPSRE-7777](https://issues.redhat.com/browse/APPSRE-7777)
=> Rds upgrade validation

reconcile/cli.py
Fix hardcoded `ocm_environment="ocm-integration"` from https://github.com/app-sre/qontract-reconcile/pull/4224
=> Extract ocm-env as optional param for ocm_addons_upgrade_scheduler_org

reconcile/utils/terrascript_aws_client.py
depends on https://github.com/app-sre/qontract-schemas/pull/690
similar implementation to `aws-iam-service-account`: https://github.com/app-sre/qontract-reconcile/blob/7b9af0c0811915405f2c4649cf96988a5c959890/reconcile/utils/terrascript_aws_client.py#L2476-L2483
=> [terraform-resources] aws-iam-role add support for managed policies

reconcile/utils/helm.py
avoid error:
```
Error: looks like "https://charts.external-secrets.io/" is not a valid chart repository or cannot be reached: open /.cache/helm/repository/external-secrets-index.yaml: no such file or directory
[ERROR] [saasherder.py:populate_desired_state_saas_file:1285] - Error in populate_desired_state_saas_file: Error running helm template [helm repo add external-secrets https://charts.external-secrets.io/ --repository-config /tmp/tmp6wbzfi5k]
```
=> [saasherder/helm] repository cache

reconcile/utils/helm.py
fixes #4547
avoid error:
```
Error: looks like "https://charts.external-secrets.io/" is not a valid chart repository or cannot be reached: open /tmp/tmp0w9w6vxl/external-secrets-index.yaml: not a directory
[ERROR] [saasherder.py:populate_desired_state_saas_file:1285] - Error in populate_desired_state_saas_file: Error running helm template [helm repo add external-secrets https://charts.external-secrets.io/ --repository-config /tmp/tmpba2sdc98 --repository-cache /tmp/tmp0w9w6vxl]
```
=> helm repository-cache is actually a dir and not a file

reconcile/utils/terrascript_aws_client.py
To support MSK cluster upgrades, use a version-dependent Terraform resource id for the AWS MSK configuration. There is no need to replace the existing configuration.
I'll tackle the resource ID change during the promotion by manually removing and importing the existing MSK configurations.
Ticket: [APPSRE-10579](https://issues.redhat.com/browse/APPSRE-10579)
=> :bug: terraform-resources msk: fix MSK cluster upgrade

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/gql_definitions/introspection.json, reconcile/saas_auto_promotions_manager/subscriber.py, reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py, reconcile/test/saas_auto_promotions_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/subscriber/test_schedule.py, reconcile/test/test_saasherder.py
Adding `schedule` gate to saas auto-promotions.
SAPM will obey to the given cron expression and only schedule auto-promotions if they fall within the schedule.
Note, that we do not add this gate to saasherder, as it could block unrelated promotions. The `schedule` feature is relevant for auto-promotions only.
Schema: https://github.com/app-sre/qontract-schemas/pull/680
=> APPSRE-10086 sapm cron schedule

reconcile/utils/saasherder/saasherder.py
follow up on #4483
this PR updates the auto-generated image tag to be exposed in the values file at the following levels:
- `image.tag`
- `global.image.tag`
this is to enable deployment of "parent" charts. the global pattern is quite common.
=> [saasherder/helm] image.tag functionality update

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_repo/terraform_repo.gql, reconcile/gql_definitions/terraform_repo/terraform_repo.py, reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
[APPSRE-8705](https://issues.redhat.com/browse/APPSRE-8705)
Depends on https://github.com/app-sre/qontract-schemas/pull/691, see that MR for more background on why this approach was chosen. Re-runs are implemented in Terraform Repo by just adding a new key that is considered during the diffing process between `existing` and `desired`. If a user updates the timestamp in an MR, then tf-repo will perform a `terraform plan` & `apply` again. No changes are needed to executor since this key isn't used by executor.
=> Support forced re-runs of Terraform Repo with a new key in the schema file

reconcile/terraform_repo.py
Reverts app-sre/qontract-reconcile#4326
This behavior made sense back then but now in FedRamp we have Terraform resources having to do with API gateway objects which don't gracefully handle recreations like other AWS resources in Terraform.
=> Revert "[tf-repo] change behavior when state has to be recreated"

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/gql_definitions/introspection.json, reconcile/openshift_saas_deploy.py, reconcile/test/test_typed_queries/test_saas_files.py, reconcile/typed_queries/saas_files.py, reconcile/utils/saasherder/saasherder.py
depends on https://github.com/app-sre/qontract-schemas/pull/692
follow up on #2261
this PR introduces handling for a saas file to define `validatePlannedData: false` and to skip validation of planned data:
https://github.com/app-sre/qontract-reconcile/blob/ccca2e5031ce5436d011dbabfc557368c1215cfc/reconcile/openshift_base.py#L1117-L1129
=> [openshift-saas-deploy] enable skipping planned data validation

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/base.py, reconcile/aus/models.py, reconcile/aus/node_pool_spec.py, reconcile/aus/ocm_upgrade_scheduler_org.py, reconcile/test/ocm/aus/fixtures.py, reconcile/test/ocm/aus/test_advanced_upgrade_service.py, reconcile/test/ocm/aus/test_base.py, reconcile/test/ocm/aus/test_calculate_diff.py, reconcile/test/ocm/aus/test_expose_metrics.py, reconcile/test/ocm/aus/test_node_pool_specs.py, reconcile/test/ocm/aus/test_ocm_upgrade_scheduler_org.py, reconcile/test/ocm/aus/test_version_data.py, reconcile/test/ocm/test_utils_ocm_clusters.py, reconcile/test/utils/test_models.py, reconcile/utils/ocm/clusters.py
Current metric `aus_cluster_upgrade_policy_info` will use cluster's version as `current_version`, when hypershift (HCP) cluster upgrade, control plane version will upgrade first, node pools will be upgraded after control plane upgrade, we want `current_version` in metrics stay as old version until all node pools upgrade done.
This change fetches node pools info early, avoid refetch in later stages, and combine node pool versions and cluster versions to expose metrics.
After new `raw_id` field exposed in node pools response at [OCM-9026](https://issues.redhat.com/browse/OCM-9026), we no longer need to send another request for version info, `get_version` call removed.
To test integration
```shell
$ qontract-reconcile --config config.toml --log-level DEBUG --dry-run …
```
=> [AUS] consider node pool versions when exposing current version metrics

reconcile/aus/ocm_upgrade_scheduler_org.py, reconcile/test/ocm/aus/test_ocm_upgrade_scheduler_org.py
Fix `KeyError` for `node_pool_specs_by_org_cluster` when org has no clusters.
Follow up for #4460
[APPSRE-10332](https://issues.redhat.com/browse/APPSRE-10332)
=> Fix error in ocm-upgrade-scheduler-org for org without clusters

reconcile/gitlab_housekeeping.py, reconcile/test/test_gitlab_housekeeping.py, tools/qontract_cli.py
```
[].work_in_progress 	boolean 	Deprecated: Use draft instead. Indicates if the merge request is a draft. 
```
from https://docs.gitlab.com/ee/api/merge_requests.html
ref: https://gitlab.com/gitlab-org/gitlab/-/issues/228685
=> [gitlab] replace wip with draft

reconcile/utils/mr/__init__.py, reconcile/utils/mr/promote_qontract.py
part of https://issues.redhat.com/browse/APPSRE-10688
given a message such as `{"pr_type": "promote_qontract_schemas", "version": "testing123"}` reaches the app-interface SQS queue, it will produce a merge request such as https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/113644
this merge request is not auto merged and should be used by the person wanting to promote.
=> gitlab merge request to promote qontract-schemas

reconcile/utils/saasherder/saasherder.py
A successful saas re-deployment of the same ref currently overrides the `check_in` time. This can easily block saas files which rely on the soakDays feature. Example https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/113754
In this PR we avoid overrides of `check_in` time if the deployment was successful. On unsuccessful deployments, we update the `check_in` time, i.e., we reset the soakDays counter for this target.
=> saas re-use check_in time

reconcile/utils/aws_api.py
reconcile/utils/aws_api.py:1387: error: Incompatible return value type (got "list[ResourceRecordSetExtraOutputTypeDef]", expected "list[ResourceRecordSetTypeDef]")  [return-value]
=> fix mypy error in aws_api

reconcile/utils/oc.py
`OCLOgMessage` show error message.
before:
```
raise OCLogMsg(log_level=logging.ERROR, message="foo")
File "<stdin>", line 1, in <module>
reconcile.utils.oc.OCLogMsg
```
fixed:
```
raise OCLogMsg(log_level=logging.ERROR, message="foo")
File "<string>", line 1, in <module>
reconcile.utils.oc.OCLogMsg: foo
```
=> :bug: oc: show error message

reconcile/endpoints_discovery/integration.py
Debugging
```
File "/usr/local/lib/python3.11/site-packages/reconcile/cli.py", line 609, in run_class_integration
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 158, in run_integration_cfg
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 167, in _integration_wet_run
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/defer.py", line 13, in func_wrapper
return func(*args, defer=stack.callback, **kwargs)
File "/usr/local/lib/python3.11/site-packages/reconcile/endpoints_discovery/integration.py", line 336, in run
self.runner(**runner_params) …
```
=>  endpoints-discovery: debug message

reconcile/dynatrace_token_provider/integration.py, reconcile/test/dynatrace_token_provider/fixtures.py, reconcile/test/dynatrace_token_provider/test_create_manifest.py, reconcile/test/dynatrace_token_provider/test_create_syncset.py, reconcile/test/dynatrace_token_provider/test_patch_manifest.py, reconcile/test/dynatrace_token_provider/test_patch_syncset.py, reconcile/test/dynatrace_token_provider/test_spec_token_diff.py
Enable DTP to detect diffs between token spec in app-interface and current existing API token in Dynatrace. If diff is detected, then DTP will make an API call to DT to properly configure the API token.
We use the DT token name to store a config hash (currently scope hash). By doing so, we can detect diffs between the token in Dynatrace and the token spec defined in app-interface. Further, we do not need any additional API calls, as we must query the token name and id with list queries anyways. Note, that a list query on tokens does not return every detail about each token, such as scopes. We do not need to query any additional information about each API token (such as scopes). By comparing the hash in the name, we know if we need to POST an update for the token.
Note, this will rename …
=> APPSRE-10615 sync token with spec

reconcile/cli.py, reconcile/endpoints_discovery/integration.py, reconcile/test/endpoints_discovery/test_endpoints_discovery_integration.py
* extended early exit: Add missing extended early exit command line options.
* fix `get_endpoint_changes`: use `/` as delimiter between cluster, namespace and route names, otherwise endpoints for namespaces like `namespace` and `namespace-stage` collides
=>  endpoints-discovery: bug fixes

reconcile/gitlab_permissions.py, reconcile/test/test_gitlab_permissions.py, reconcile/test/utils/test_gitlab_api.py, reconcile/utils/gitlab_api.py
Reverts app-sre/qontract-reconcile#4541
Apologies @mehfuz but I am reverting this MR. Unsure why CI didn't catch this but the old `get_group_id_and_projects` function call was not updated in this file: https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/gitlab_projects.py#L26 causing a failure when trying to promote qontract-reconcile in FedRamp.
=> Revert "refactor gitlab-permissions integration"

reconcile/test/change_owners/test_change_type_admission.py, reconcile/test/terraform_vpc_resources/test_terraform_vpc_resources_integration.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py, reconcile/test/utils/test_slack_api.py, tox.ini
We also need to install the test requirements in your CI `type` test. Otherwise, `mypy` can't validate all our test Python files, and errors may be hidden. 
Especially, `mypy` shows different output/errors in the local developer environment than in the CI checks.
=> mypy ci fixes

reconcile/cli.py, reconcile/dynatrace_token_provider/integration.py, reconcile/test/dynatrace_token_provider/conftest.py, reconcile/test/dynatrace_token_provider/test_ocm_org_filters.py
In DTP we had 2 places to filter ocm orgs: the token spec and integration arg `--ocm-org-ids`
The ocm org filter in the token spec should be the only source of truth. We remove `--ocm-org-ids` integration argument.
=> APPSRE-10731 DTP single ocm org filter

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/gql_definitions/introspection.json, reconcile/saas_auto_promotions_manager/publisher.py, reconcile/saas_auto_promotions_manager/s3_exporter.py, reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py, reconcile/test/saas_auto_promotions_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/s3_exporter/conftest.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_saas_files_use_target_config_hash.py, reconcile/test/test_saasherder.py
This new flag on saas targets determines whether we want to re-deploy the target on config changes in its publishers. (aka setting target_config_hash)
Corresponding schema https://github.com/app-sre/qontract-schemas/pull/705
=> APPSRE-7516 saas target re-deploy flag

reconcile/gql_definitions/common/saas_files.gql, reconcile/gql_definitions/common/saas_files.py, reconcile/gql_definitions/introspection.json, reconcile/saas_auto_promotions_manager/publisher.py, reconcile/saas_auto_promotions_manager/s3_exporter.py, reconcile/saas_auto_promotions_manager/utils/saas_files_inventory.py, reconcile/test/saas_auto_promotions_manager/conftest.py, reconcile/test/saas_auto_promotions_manager/s3_exporter/conftest.py, reconcile/test/saas_auto_promotions_manager/utils/saas_files_inventory/test_saas_files_use_target_config_hash.py, reconcile/test/test_saasherder.py
This new flag on saas targets determines whether we want to re-deploy the target on config changes in its publishers. (aka setting target_config_hash)
Corresponding schema https://github.com/app-sre/qontract-schemas/pull/705
---
This reverts commit 146bdca3933ce3e7af25eeddc04a015570d38b01.
https://github.com/app-sre/qontract-reconcile/pull/4626
https://github.com/app-sre/qontract-reconcile/pull/4629
=> Revert "Revert "APPSRE-7516 saas target re-deploy flag (#4626)" (#4629)"

reconcile/test/utils/test_terraform_client.py, reconcile/utils/terraform_client.py
Adds validation for RDS blue/green updates to raise an error when storage_type or allocated_storage fields have changed.
=> [APPSRE-10253] - Validate storage changes for RDS blue/green updates

reconcile/gql_definitions/common/clusters_with_peering.gql, reconcile/gql_definitions/common/clusters_with_peering.py, reconcile/gql_definitions/introspection.json, reconcile/terraform_tgw_attachments.py, reconcile/test/test_terraform_tgw_attachments.py, reconcile/utils/terraform_client.py, reconcile/utils/terrascript_aws_client.py
https://issues.redhat.com/browse/APPSRE-10782
depends on https://github.com/app-sre/qontract-schemas/pull/709
We need to support routing multiple CIDR blocks towards a TGW.
We will name route resources with the target CIDR block and not with a simple list index so we can easily modify the list of CIDR blocks without delete/create actions.
Any CIDR block defined in `cidrBlock` will have its `aws_route` resource renamed to match the new pattern. This is done using the terraform `moved` block which is available since terraform 1.1 ([doc](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring#moved-block-syntax)). This allows to be backward compatible and to move the value from `cidrBlock` to `cidrBlocks` after the resource rename has been performed.
=> APPSRE-10782 support multiple cidr blocks routing to TGW

reconcile/slack_usergroups.py, reconcile/test/test_slack_usergroups.py
Skip user group if any errors when getting user names, this will cover some dependency outage such as gitlab or github, to ensure other user groups can be managed.
=> Handle errors when getting user names for slack usergroup

reconcile/gql_definitions/common/clusters_with_peering.gql, reconcile/gql_definitions/common/clusters_with_peering.py, reconcile/gql_definitions/introspection.json, reconcile/terraform_tgw_attachments.py, reconcile/test/test_terraform_tgw_attachments.py, reconcile/utils/terraform_client.py, reconcile/utils/terrascript_aws_client.py
https://issues.redhat.com/browse/APPSRE-10782
Fixing PR https://github.com/app-sre/qontract-reconcile/pull/4632 which was reverted by https://github.com/app-sre/qontract-reconcile/pull/4633
```
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/terraform_client.py", line 345, in log_plan_diff
resource_change["address"],
~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'address'
```
`resource_change` is being redefined in between... The fix is in commit [01300ea5eb728624e767caf6dbe15dbbba2b7f88](https://github.com/app-sre/qontract-reconcile/pull/4634/commits/01300ea5eb728624e767caf6dbe15dbbba2b7f88)
Still depends on https://github.com/app-sre/qontract-schemas/pull/709
=> APPSRE-10782 support multiple cidr blocks routing to TGW - 2

grafana-dashboards/grafana-dashboard-integrations.configmap.yaml
Adds a new visualization to the Integrations Dashboard indicating when GitLab tokens will expire.
=> Update dashboard to include token expiration dates

reconcile/queries.py, tools/qontract_cli.py
https://issues.redhat.com/browse/APPSRE-10783
This allows to include those CIDR block in this view and avoid collisions
=> APPSRE-10783 add tgw attachements CIDR blocks in the output of qontract-cli get cidr-blocks

reconcile/change_owners/change_log_tracking.py, tools/qontract_cli.py
we care less when a commit was created, and more when it became active in production (merged).
this PR changes the date to be merged at, from the associated merge request(s).
=> [change-log-tracking] replace commit created_at with merge request merged_at

tools/qontract_cli.py
to display the change log by date
=> qontract-cli get change-log-tracking disable natural sort to sort by merged_at

reconcile/utils/output.py
we mostly use the markdown output to render tables in gitlab (app-interface-output). this PR reduces file size without hurting functionality.
=> [qontract-cli] markdown output remove spaces

Makefile, reconcile/dynatrace_token_provider/ocm.py
Up until now the DTP spec was set via `sre-capabilities.dtp = spec-name`. However, our integrations treat `sre-capabilites.dtp` as a map.
In this PR we set the DTP spec now via `sre-capabilities.dtp.spec = spec-name` to comply with our schema.
Note, that this is fully backwards compatible. If a spec label is missing, DTP falls back to a default spec (which is what all clusters are doing right now).
In this PR we also start printing host level tooling versions for any potential debugging.
=> APPSRE-10844 dedicated dtp.spec label

reconcile/change_owners/change_log_tracking.py
part of https://issues.redhat.com/browse/APPSRE-10755
add a check for the changed paths of the gitlab commit objects, to discover changes to paths (data, hack) that are not covered by the granular permissions model (data, resoruces)
this PR depends on the existence of dummy change types: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/117790
=> [change-log] add handling for special dirs in app-interface (docs, hack)

reconcile/utils/vault.py
We repeatedly see `TooManyRedirects` on `openshift-saas-deploy`, which will make tenants retry the pipeline. Note, that this happens on every integration, but for saas deploys this is especially annoying.
Lets add `TooManyRedirects` to the list of exceptions for which we retry
Example error from a recent pipeline run:
```
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/vault.py", line 163, in _refresh_client_auth
self._client.auth_approle(self.role_id, self.secret_id)
File "/usr/local/lib/python3.11/site-packages/hvac/v1/__init__.py", line 1428, in auth_approle
return self.login('/v1/auth/{0}/login'.format(mount_point), json=params, use_token=use_token)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> retry on TooManyRedirects

reconcile/gitlab_housekeeping.py
When a PAT becomes inactive, do not publish metrics indicating that token is active since that will result in alerting and pages.
The current behavior is that when a token becomes inactive, two gauges are created with `active=true` and `active=false`.
=> [gitlab-housekeeping] remove duplicate token expiration metrics

reconcile/external_resources/manager.py, reconcile/external_resources/metrics.py, reconcile/external_resources/model.py, reconcile/external_resources/reconciler.py, reconcile/external_resources/state.py, reconcile/test/external_resources/test_er_state.py, reconcile/utils/jobcontroller/controller.py
- **Ignore mypy errors. This will be enventually solved once all resources have the managed_by_erv2 attr.**
- **Add a method to get the job duration time for a successful run**
- **External resources metrics redesign**
- reconcile_errors moved out of the state. I t can be handled with prometheus metrics directly
- add reconcile_time
=> External Resources metrics redesign

reconcile/change_owners/change_types.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py, reconcile/saas_auto_promotions_manager/merge_request_manager/renderer.py
- add a dedicated progressive delivery priority in change types (1 above medium)
- SAPM sets the new label directly on every MR -> no change-type role is responsible for this prio
- SAPM does not use lgtm semantic (change-type role)
Once we fix https://issues.redhat.com/browse/APPSRE-10875, we can again define a change-type role for this prio in app-interface.
=> APPSRE-10875 dedicated progressive delivery label

grafana-dashboards/grafana-dashboard-integrations.configmap.yaml
Now that GitLab housekeeping is run as a sharded process with 5 replicas, that means 5 times the data points for the PAT expiration graph. This fixes that behavior by performing a `max` summation by name to remove duplicates.
`max by(name) (qontract_reconcile_gitlab_token_expiration_days{active=\"True\"}`
=> Fix PAT graph in Integrations dashboard

reconcile/ocm_clusters.py, reconcile/test/test_ocm_clusters.py, reconcile/utils/ocm/products.py
OCM API doesn't support update `network.type` after cluster created, we need to update `type` from `OpenShiftSDN` to `OVNKubernetes` to ensure the value matches cluster for OVN migration tasks. We need to ignore this field until OCM has proper support for CNI migration.
[APPSRE-10881](https://issues.redhat.com/browse/APPSRE-10881)
=> [ocm-clusters] ignore network type change

reconcile/utils/internal_groups/client.py
`InternalGroupsApi` sending request without timeout, lead to integrations like `ldap-groups` hang, add `timeout` to `_request` so it can self recover.
[ASIC-549](https://issues.redhat.com/browse/ASIC-549)
=> [ldap-groups] set request timeout to avoid integration hang

reconcile/change_owners/bundle.py, reconcile/change_owners/change_log_tracking.py, reconcile/change_owners/changes.py, reconcile/gql_definitions/external_resources/external_resources_namespaces.gql, reconcile/gql_definitions/external_resources/external_resources_namespaces.py, reconcile/gql_definitions/jenkins_configs/jenkins_configs.gql, reconcile/gql_definitions/jenkins_configs/jenkins_configs.py, reconcile/test/fixtures/vault_replication/jenkins_configs/jenkins_config_insta_path.yaml, reconcile/test/test_vault_replication.py, reconcile/typed_queries/jenkins.py
part of https://issues.redhat.com/browse/APPSRE-10755
we iterate over changes. if the change is to a resource file, we want to add each backref to the list of changes, as if that file is changing as well.
for example, if a ConfigMap that is referenced from a namespace is updated, we want to express the change in the context of the namespace, to later match all change types that refer to a namespace.
=> [change-log] support for resource analysis

reconcile/change_owners/change_log_tracking.py
to not depend on `changes`, and to be able to parse a commit that only has changes to docs.
=> [change-log] fix docs/hack section indentation

reconcile/utils/helm.py, reconcile/utils/saasherder/saasherder.py
Some tenants would like to checkout the helm chart from the ref in the saas file. I believe this makes sense.
Are there scenarios in which we always want to checkout from main? Do we need an extra saas helm provider flag (`checkoutChartFromRef`?) or can we make this general behavior?
=> APPSRE-10884 always checkout chart from ref

reconcile/utils/oc.py
Annotations might be set to None. Lets avoid
```
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/oc.py", line 906, in recycle_pods
qontract_recycle = dep_annotations.get("qontract.recycle")
AttributeError: 'NoneType' object has no attribute 'get'
```
=> make sure dep_annotations is always dict

reconcile/change_owners/change_log_tracking.py
```
File "/usr/local/lib/python3.11/site-packages/reconcile/cli.py", line 609, in run_class_integration
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 158, in run_integration_cfg
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 167, in _integration_wet_run
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/defer.py", line 13, in func_wrapper
return func(*args, defer=stack.callback, **kwargs)
File "/usr/local/lib/python3.11/site-packages/reconcile/change_owners/change_log_tracking.py", line 152, in run
changed_apps = {
^
File …
```
=> [change-log] support app ref or obj

reconcile/utils/helm.py, reconcile/utils/saasherder/saasherder.py
Checkout not working properly on good refs, e.g.,
```
Error in populate_desired_state_saas_file: git checkout failed: 05c58fb26cccc880a7cd75fbab89658ab98cea22
```
This reverts commit e5113e73507f7a5438412526c9556518d4f7acc3.
=> Revert "APPSRE-10884 always checkout chart from ref (#4677)"

reconcile/utils/saasherder/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-10885
removing this functionality (for now) to enable more strict helm charts.
this may be re-introduced in the future with a different implementation.
=> [saasherder/helm] remove image.tag functionality

reconcile/utils/ocm_base_client.py
For example, during a status board application DELETE failure, the reason is hidden in the text:
```
{"id":"6","kind":"Error","href":"/api/status-board/v1/errors/6","code":"OCM-SB-6","reason":"Cannot delete an application with services or dependencies.","operation_id":"..."}
```
=> log ocm client DELETE failure text to easily get more details

reconcile/statuspage/integrations/maintenances.py, reconcile/statuspage/page.py
If there are no components, status page replies with a `500`
Also added a commit to sort current and desired states so we can diff the 2 lists securely
=> Ensure a status page component is set before creating a maintenance

grafana-dashboards/grafana-dashboard-integrations.configmap.yaml, reconcile/gitlab_housekeeping.py
Updates the `qontract_reconcile_gitlab_token_expiration_days` metric exported by `gitlab-housekeeping` to only factor in active tokens. This also removes the `active` label from the metric which should cut down on unnecessary cardinality. There's no real need to monitor inactive tokens since they cannot be used.
Additionally updates the Grafana dashboard for integrations to remove that `active` label.
Second take at https://github.com/app-sre/qontract-reconcile/pull/4663
=> [git-housekeeping] update token expiration metric to only include active tokens

reconcile/change_owners/change_log_tracking.py, reconcile/change_owners/changes.py, reconcile/gql_definitions/common/namespaces.gql, reconcile/gql_definitions/common/namespaces.py, reconcile/test/fixtures/openshift_namespace_labels/namespace.yml
part of https://issues.redhat.com/browse/APPSRE-10755
follows up on #4669
this PR fixes problems which prevented resource analysis from fully working:
1. we didn't query for `openshiftResources`
2. we didn't use `by_alias`, which means the query result as a dict had `openshift_resources`.
=> [change-log] fix support for resource analysis

grafana-dashboards/grafana-dashboard-external-resource-log.configmap.yaml, reconcile/external_resources/manager.py, reconcile/external_resources/metrics.py, reconcile/test/external_resources/test_manager.py
* Add external_resources_resource_status metric to hold resource status. This metric is useful for filtering since it has a value at every run (not only when a resource has been reconciled)
* Use the new metric on the dashboard filtering options
=> Erv2: Improve Logs dashboard + add a new metric

reconcile/change_owners/change_log_tracking.py, reconcile/cli.py
mostly for debugging purposes, but can be useful to process existing commits
=> [change-log] support processing single commit

tools/qontract_cli.py
we have not seen errors since work to stabilize, it's now safe to remove the error from the report
part of https://issues.redhat.com/browse/APPSRE-10740
=> [change-log] remove error from app-interface-output report

reconcile/gitlab_housekeeping.py
Follow-up from #4695 
I found out how this `remove()` function is supposed to work (it's not actually documented by the Prometheus client library). This should take care of removing inactive/expired tokens from the exported metrics.
=> [gitlab-housekeeping] remove expired PAT tokens

reconcile/change_owners/change_log_tracking.py
protect against missing `app` or `app.path` in the query, and be more defensive if that information is missing.
also provide helpful logging.
=> [change-log] defense against missing app and helpful logging

reconcile/aus/ocm_addons_upgrade_scheduler_org.py
https://issues.redhat.com/browse/APPSRE-10973
Since recently, addon service does not delete the addon upgrade plans but sets them as completed. AUS will not create any new plan if one exists already. Also, if a plan exists, the addon upgrade holds any configured mutex for that cluster. So this blocks further upgrades.
This PR cleans up the completed upgrade plan, much like what we do for automatic upgrade plans
=> [AUS/addon] clean completed upgrade plans

reconcile/external_resources/integration.py, reconcile/external_resources/integration_secrets_sync.py, reconcile/typed_queries/external_resources.py, tools/cli_commands/erv2.py, tools/qontract_cli.py, tools/test/test_erv2.py
This PR introduces the `qontract-cli external-resources migrate` command, which will help us with the ERv2 migration. It makes the [terraform-resources -> ExternalResources RDS migration Guide](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/runbook/external-resources/aws-rds-migration.md) much easier.
High-level: it retrieves the ERv2 and the terraform-resources configs and states and moves all involved resources. Something like
```
get CDKTF output and state
get terraform-resources output and state
for resources in diff CDKTF terraform:
terraform state mv -lock=false -state=terraform-resources-state -state-out=scdktf_state \
"resource_in_terraform_state" \
"resource_in_cdktf_state"
terraform push both states
```
Example run:
```
$ qontract-cli …
```
=> :sparkles: qontract-cli: external-resources migrate command

tools/qontract_cli.py
[APPSRE-10882](https://issues.redhat.com/browse/APPSRE-10882)
Introduces a new command to Qontract CLI for migrating Terraform statefiles for usage with Terraform Repo.
Example of usage:
`qontract-cli --config config.debug.toml copy-tfstate app-sre my-backend-bucket app-sre-ci-stage.tfstate app-sre-ci-stage us-east-1`
This command allows for migration from manually managed Terraform repositories (ex: our infra repo on GitLab), to be Terraform Repo managed. 
The command will prompt the user to OK the change like so:
```
❯ qontract-cli --config config.debug.toml copy-tfstate app-sre my-backend-bucket app-sre-ci-stage.tfstate app-sre-ci-stage us-east-1 
Are you sure you want to copy 's3://my-backend-bucket/app-sre-ci-stage.tfstate' to …
```
=> [qontract-cli] copy_tfstate command

reconcile/aws_account_manager/merge_request_manager.py
If the AWS account manager template MR has already been merged but the `template-renderer` isn't running yet, the account template collection file already exists, which throws an error message. Just remove this confusing message.
Ticket: [APPSRE-10814](https://issues.redhat.com/browse/APPSRE-10814)
=> :recycle: aws-account-manager: do not raise an error

reconcile/endpoints_discovery/integration.py, reconcile/test/endpoints_discovery/conftest.py, reconcile/test/endpoints_discovery/test_endpoints_discovery_integration.py
Several routes may have the same hostname, e.g., if `path` is used. Remove duplicates and unclutter the `app.yml` files 
Ticket: https://issues.redhat.com/browse/APPSRE-10847
=> :bug: endpoints-discovery: avoid duplicated urls

reconcile/dashdotdb_slo.py, reconcile/gql_definitions/dashdotdb_slo/slo_documents_query.py, reconcile/gql_definitions/introspection.json
https://issues.redhat.com/browse/APPSRE-8513
Depends on https://github.com/app-sre/qontract-schemas/pull/718
This allows to get SLO data into dash.db for SLO queries which are not targeting the local cluster prometheus.
Also do not fail on connection errors to prometheus and allow unauthenticated access (eg local token refresher services)
=> [dashdotdb-slo] query the prometheus instance configured in prometheusAccess, even when SLONamespace is set

reconcile/utils/mr/promote_qontract.py
[SDE-3686](https://issues.redhat.com/browse/SDE-3686)
Dependent on this MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/120268
Includes Terraform Repo in the auto promotion process for Qontract Reconcile
=> Promote QR Image in Terraform Repo SaaS File

reconcile/change_owners/changes.py
```
File "/home/mafriedm/repos/app-sre/qontract-reconcile/reconcile/cli.py", line 609, in run_class_integration
File "/home/mafriedm/repos/app-sre/qontract-reconcile/reconcile/utils/runtime/runner.py", line 155, in run_integration_cfg
File "/home/mafriedm/repos/app-sre/qontract-reconcile/reconcile/utils/runtime/runner.py", line 226, in _integration_dry_run
File "/home/mafriedm/repos/app-sre/qontract-reconcile/reconcile/utils/defer.py", line 13, in func_wrapper
return func(*args, defer=stack.callback, **kwargs)
File "/home/mafriedm/repos/app-sre/qontract-reconcile/reconcile/change_owners/change_log_tracking.py …
```
=> aggregate_resource_changes allow datafile to not exist

reconcile/aws_version_sync/integration.py
Another Redis `7.1` bugfix. Always cast the version to string to get all version properties.
=> :bug: aws-version-sync: enforce string

requirements/requirements-type.txt
New mypy version discovers new errors that need to get fixed aside. 
```reconcile/utils/oc_map.py:125: error: Incompatible types in assignment (expression has type "OC", variable has type "OCCli | OCLogMsg")  [assignment]```
=> Pin mypy version

reconcile/test/test_vault_replication.py, reconcile/vault_replication.py
we may have policies with paths that do not have globs, being just a single secret:
```
path my/nice/secret
```
instead of the more general that catches everything inside the folder
```
path my/nice/*
```
The code didn't behave properly with the former ones.
related to APPSRE-10999
=> Allow the replication of single secret policies

reconcile/test/test_vault_replication.py
When secrets don't end with a "/", we don't call Vault, hence the side effect was wrong and we were not testing the case of a path with dashes or underscores.
=> Fix misleading vault replication test

tools/qontract_cli.py
APPSRE-10882
Following some feedback in the migration guide: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/120196#note_13167927, this updates the migrate command to use explicitly named options instead of value ordered arguments. Here is what the output/format looks now:
```
qontract-cli --config config.debug.toml copy-tfstate --account-uid <account_uid> --source-bucket <source_bucket> --source-object-path athena.tfstate
Are you sure you want to copy 's3://<source_bucket>/athena.tfstate' to 's3://<dest_bucket>/tf-repo-statefiles/athena-tf-repo.tfstate'? [y/N]: y
Nicely done! Your tfstate file has been migrated. Now you can create a repo definition in App-Interface like so:
---
$schema: /aws/terraform-repo-1.yml
account:
$ref: /aws/<account_name>/account.yml
name: …
```
=> [tf-repo migrate] explicitly named arguments

reconcile/gql_definitions/cost_report/cost_namespaces.gql, reconcile/gql_definitions/cost_report/cost_namespaces.py, reconcile/test/test_typed_queries/cost_report/test_get_cost_namespaces.py, reconcile/typed_queries/cost_report/cost_namespaces.py, tools/cli_commands/cost_report/aws.py, tools/cli_commands/cost_report/cost_management_api.py, tools/cli_commands/cost_report/model.py, tools/cli_commands/cost_report/openshift.py, tools/cli_commands/cost_report/openshift_cost_optimization.py, tools/cli_commands/cost_report/response.py, tools/cli_commands/cost_report/util.py, tools/cli_commands/cost_report/view.py, tools/cli_commands/test/conftest.py, tools/cli_commands/test/fixtures/empty_openshift_cost_optimization_report.md, tools/cli_commands/test/fixtures/openshift_cost_optimization_report.json, tools/cli_commands/test/fixtures/openshift_cost_optimization_report.md, tools/cli_commands/test/test_aws_cost_report.py, tools/cli_commands/test/test_cost_management_api.py, tools/cli_commands/test/test_openshift_cost_optimization_report.py, tools/cli_commands/test/test_openshift_cost_report.py, tools/cli_commands/test/test_util.py, tools/qontract_cli.py, tools/test/test_qontract_cli.py
Export openshift cost optimization report from [Cost Management Optimizations](https://console.redhat.com/openshift/cost-management/optimizations).
Preview a sample report at [test cost optimization report](https://gitlab.cee.redhat.com/-/snippets/8885).
Local verification:
```shell
qontract-cli --config config.toml get openshift-cost-optimization-report > openshift-cost-optimization-report.md
```
[design doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/openshift-cost-report.md#for-cost-optimization)
[APPSRE-10233](https://issues.redhat.com/browse/APPSRE-10233)
=> feat(cost-optimization-report): add openshift cost optimization report

reconcile/quay_mirror.py, reconcile/test/test_quay_mirror.py, reconcile/test/utils/test_helpers.py, reconcile/utils/helpers.py
When both `tags` and `tags_exclude` are specified in mirror config, if the tag matches `tags`, `tags_exclude` will be ignored, this change bring exclude check take precedence than include check to allow matches in exclude list to be skipped for sync.
Example use case is to allow `\d+\.\d+\.\d+`, but to ignore `1.0.0`.
[APPSRE-11045](https://issues.redhat.com/browse/APPSRE-11045)
=> feat(quay-mirror): tags_exclude check take precedence than tags

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
`terraform-resources` must exclude Elasticache instances with `managed_by_erv2: true`.
=> :bug: terraform-resources: ERv2 elasticache support

reconcile/external_resources/manager.py, reconcile/external_resources/model.py, reconcile/external_resources/reconciler.py, reconcile/external_resources/state.py, reconcile/gql_definitions/external_resources/external_resources_modules.gql, reconcile/gql_definitions/external_resources/external_resources_modules.py, reconcile/gql_definitions/external_resources/external_resources_namespaces.gql, reconcile/gql_definitions/external_resources/external_resources_namespaces.py, reconcile/gql_definitions/external_resources/external_resources_settings.gql, reconcile/gql_definitions/external_resources/external_resources_settings.py, reconcile/gql_definitions/introspection.json, reconcile/test/external_resources/conftest.py, reconcile/test/external_resources/test_er_state.py, reconcile/test/external_resources/test_module_configuration.py, tools/cli_commands/erv2.py
Remove hardcoded `er-outputs-secrets` image and version.
The image and the version must be configured in `/external-resources/settings-1.yml` but can be overridden in `/external-resources/module-1.yml` and `/external-resources/module-overrides-1.yml`
Depends on: https://github.com/app-sre/qontract-schemas/pull/724
Ticket: [APPSRE-11049](https://issues.redhat.com/browse/APPSRE-11049)
=> :sparkles: ERv2: make outputs-secret image and version configurable

reconcile/queries.py, reconcile/terraform_resources.py, reconcile/test/utils/test_terrascript_aws_client.py, reconcile/utils/external_resources.py, reconcile/utils/terrascript_aws_client.py
This allows external resource providers to be excluded from specific provisioners (accounts) for terraform_resources. For example, once all RDS instances have been migrated to V2, we don't want new RDS resources to use terraform_resources. 
schemas: app-sre/qontract-schemas#725
=> Add settings to exclude providers from provisioners in terraform_resources

reconcile/ocm_machine_pools.py
Related to: [APPSRE-10481](https://issues.redhat.com/browse/APPSRE-10481)
This validates that if the user wants to create machine pools that uses the ROSA HCP default machine pools ids (workers-0, workers-1 and workers-2) and the subnet ids attached to them is not in the correct alphabetical order the `ocm-machine-pools` integrations fails.
This is due to a limitation on the cluster creation side that is well documented on the ticket.
To test this you can use the template from this [MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/114908#969c6a8503d37323d7484aa18c2bfeac0f348c2f).
The templating side was already fixed this is a safe measure for if someone tries to create cluster by using only the cluster schema.
EDIT: 
After much debate and analysis I think It's bet …
=> Improve error message for ocm machine pools validation

reconcile/queries.py, reconcile/terraform_resources.py, reconcile/test/utils/test_terrascript_aws_client.py, reconcile/utils/terrascript_aws_client.py
An improvement over how the provider exclusions are managed in AI settings. 
* Allows to exclude all provisioners for a provider: (useful for new modules and for new accounts when created) 
* Now the list is based on providers instead of provisioners. 
Requires: app-sre/qontract-schemas#727
=> Improve terraform-resources provider exclusions

reconcile/utils/terrascript_aws_client.py
example error:
```
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```
=> [terrascript/s3] enable API V2

reconcile/change_owners/change_log_tracking.py
part of https://issues.redhat.com/browse/APPSRE-11125
this PR adds an optional description to a change log item, and initiates it from from the commit message.
a commit message has the following structure: `<commit title>\n\n<merge request title>\n<merge request refernce>`
for example:
```
"Merge branch 'create_clusters_updates_mr-e71167' into 'master'\n\n[create_clusters_updates_mr] clusters updates\n\nSee merge request service/app-interface!123657"
```
we want a one line description that is as human friendly as possible, which is why we use the original merge request title.
=> [change-log] enhance item with commit description

reconcile/external_resources/aws.py, tools/cli_commands/erv2.py, tools/qontract_cli.py
1. It should be possible to share parameter groups between Elasticache instances in app-interface. In the ERv2 state, it must be applied separately; otherwise, one instance would depend on another.
2. ElastiCache migration
=>  erv2 elasticache

reconcile/aus/base.py, reconcile/test/ocm/aus/test_calculate_diff.py
not all gap analysis will create version gate, no gate for 4.17, removing this check to allow cluster version upgrade.
=> feat(aus): allow cluster upgrade to a version without version gates

reconcile/terraform_repo.py, reconcile/test/test_terraform_repo.py
Terraform Repo was created initially with a limit at the PR check level: only one repo can be modified in one PR
While this made sense when the project was initially created, it limits AppSRE whenever we need to make an update to [the schema](https://github.com/app-sre/qontract-schemas/blob/main/schemas/aws/terraform-repo-1.yml). If we add a new required property that requires mass-updating each reference to that schema, AppSRE would have to submit a separate MR for each repo file. This removes that limitation allowing for mass updates like other integrations.
The concern around tenants updating multiple repos at once is addressed through change-types within App-Interface limiting the amount of repos a tenant can self-service.
This will enable faster updates of tf-repo going forward. …
=> [tf-repo] remove restriction on number of repos that can be updated in one MR

reconcile/gitlab_members.py, reconcile/test/test_gitlab_members.py, reconcile/test/utils/test_gitlab_api.py, reconcile/utils/gitlab_api.py
issue - [APPSRE-11133](https://issues.redhat.com/browse/APPSRE-11133)
Changes - 
1. introduced `id` field to avoid user lookup while removing user.
2. modify code to use `username` while adding member to group to avoid additional lookup. 
3. changes to `state` object in `gitlab_members` to save group info to avoid additional lookup.
4. make use of `diff_mappings` to reconcile.
=> APPSRE-11133: fix desired state in case of inactive/blocked user

reconcile/test/fixtures/container_images_report/app-sre-observability-stage-pods.yaml, reconcile/test/fixtures/container_images_report/app-sre-pipelines-pods.yaml, tools/cli_commands/container_images_report.py, tools/qontract_cli.py, tools/test/test_get_container_images.py
```
$ qontract-cli --config config.development.toml get  container-images --help
Usage: qontract-cli get container-images [OPTIONS]
Get all container images in app-interface defined namespaces
Options:
--cluster-name TEXT             openshift cluster names to act on i.e.:
--cluster-name cluster-1 --cluster-name
cluster-2
--namespace-name TEXT           namespace name to act on.
--thread-pool-size INTEGER      number of threads to run in parallel.
--use-jump-host / --no-use-jump-host
use jump host if defined.
--exclude-pattern TEXT          Exclude images that match this pattern
--include-pattern TEXT          Only include images that match this pattern
--help                          Show this message and exit.
```
APPSRE-11229
=> Container Images used report

reconcile/test/utils/test_aws_api.py, reconcile/utils/aws_api.py
When no endpoints found before HCP cluster creation but peering config in `cluster.yml` file exist, integration `terraform-vpc-peerings` will fail with error
```
File "/usr/local/lib/python3.11/site-packages/reconcile/cli.py", line 609, in run_class_integration
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 155, in run_integration_cfg
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/runner.py", line 226, in _integration_dry_run
File "/usr/local/lib/python3.11/site-packages/reconcile/utils/runtime/integration.py", line 315, in run
self.params.module.run(dry_run, *self.params.args, …
```
=> fix(vpc-peering): skip security group for HCP if no endpoints

tools/cli_commands/container_images_report.py, tools/test/test_get_container_images.py
The code from #4769 did not handle errors properly. Errors have been added in a sort of hackish way (at the end of the image list), but it is better to show them somewhere than hiding them.
Output is now sorted by default for clarity.
APPSRE-11229
=> Handle errors in container-images report

reconcile/test/utils/test_aws_api.py, reconcile/utils/aws_api.py
Update security group name match to include `-vpce-private-router` ones as the logic changed in HCP, new clusters will have the new security group name.
[APPSRE-11280](https://issues.redhat.com/browse/APPSRE-11280)
=> fix(vpc-peering): match new security group name for HCP cluster

tools/cli_commands/erv2.py, tools/qontract_cli.py
We disable `terraform-resources` via app-interface settings. Therefore, the Unleash note is misleading. Also, set the default answer to "yes" for "Would you like to upload the modified terraform states".
=> qontract-cli erv2 migration: fix warning and default upload answer

reconcile/aus/base.py, reconcile/saas_auto_promotions_manager/subscriber.py
https://issues.redhat.com/browse/APPSRE-11287
The `croniter` `day_or` parameter allows to AND the 2 `day` of a cron expression instead of the default OR.
For example, by default `0 13 1-7 * 2` matches all first 7 days of each months AND all tuesdays of each month. This is because the `day-of-month` and `day-of-week` fields are ORed by default.
With `day_or=False`, the `day-of-month` and `day-of-week` fields are ANDed, which allows to get "the first tuesday of each month"
=> Allow "2nd friday of each month" type of schedule in AUS and saas-deploy

reconcile/change_owners/change_log_tracking.py, reconcile/test/change_owners/test_change_log_tracking.py
Fix error when app file deleted.
```text
File "/usr/local/lib/python3.11/site-packages/reconcile/change_owners/change_log_tracking.py", line 189, in run
raise KeyError(
KeyError: "app name is expected. missing in query? app information: {'$ref': '/services/xxxx/app.yml'}"
```
This pull request includes changes to handle missing app names more gracefully and adds a new test for this scenario. The most important changes are:
* Modified `reconcile/change_owners/change_log_tracking.py` to log a message and use the app path as the name if the app name is not found, instead of raising a `KeyError`.
* Added a comprehensive test in `reconcile/test/change_owners/test_change_log_tracking.py` to verify the behavior when an app is deleted and its name is missing. This includes setting up necessary …
=> fix(change-log-tracking): use app path when name not found

reconcile/test/fixtures/container_images_report/app-sre-observability-stage-pods.yaml, tools/cli_commands/container_images_report.py, tools/test/test_get_container_images.py
this is a valid image spec:
```
image: quay.io/app-sre/prom-cloudwatch-exporter
```
and the report is not taking it into account.
=> Count images w/out tag in container-images report

grafana-dashboards/grafana-dashboard-external-resource-log.configmap.yaml, reconcile/external_resources/aws.py, reconcile/external_resources/factories.py, reconcile/external_resources/manager.py, reconcile/external_resources/model.py, reconcile/external_resources/secrets_sync.py
This PR implements resource reconciliation dependencies. 
The main use case for now is RDS read replicas. Every time a Primary is reconciled, it will trigger a reconciliation for its read replicas. This is needed to sync the credentials output secrets in case a password reset is requested.
=> Erv2: Implement resource reconciliation dependencies

reconcile/external_resources/manager.py, reconcile/external_resources/model.py
Prevent Erv2 resources removal without setting the delete flag.
=> Fail ERv2 DRY-RUN mode when there are orphaned resources

reconcile/external_resources/manager.py, reconcile/external_resources/model.py
Reverts app-sre/qontract-reconcile#4787
I noticed a little issue with this change when deleting resources. I will raise a new MR with a minor change.
=> Revert "Fail ERv2 DRY-RUN mode when there are orphaned resources"

dockerfiles/Dockerfile
$TITLE
```
File "/work/reconcile/cli.py", line 609, in run_class_integration
File "/work/reconcile/utils/runtime/runner.py", line 155, in run_integration_cfg
File "/work/reconcile/utils/runtime/runner.py", line 226, in _integration_dry_run
File "/work/reconcile/utils/runtime/integration.py", line 315, in run
File "/work/reconcile/utils/defer.py", line 13, in func_wrapper
return func(*args, defer=stack.callback, **kwargs)
File "/work/reconcile/integrations_manager.py", line 299, in run
fetch_desired_state(
File …
```
=> :bug: prod image: add missing helm charts

reconcile/typed_queries/app_interface_metrics_exporter/terraform_repo.py, tools/app_interface_metrics_exporter.py, tools/test/test_app_interface_metrics_exporter.py
[APPSRE-11304](https://issues.redhat.com/browse/APPSRE-11304)
Adds a new gauge to QR, `qontract_reconcile_terraform_repo_inventory` which tracks deployed Terraform Repositories via AWS account. The reason this is in the metrics exporter file rather than in [`reconcile/terraform_repo.py`](https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/terraform_repo.py) has to do with the deployment architecture of Terraform Repo. 
The Terraform Repo integration is event-driven so trying to scrape metrics from it would probably involve a Prometheus gateway. Instead of that approach, I've just added it to this existing integration that is constantly reconciling and uses GQL information to create the gauge.
=> [terraform-repo] metrics

grafana-dashboards/grafana-dashboard-terraform-repo.yaml
[APPSRE-11304](https://issues.redhat.com/browse/APPSRE-11304)
Adds a basic dashboard for Terraform Repo. Screenshot from stage:
(AWS account names blurred for privacy). Currently, TF Repo is being utilized in a more limited way which is why logs are missing currently but they will be populated whenever a pipeline is run.
=> Add a dashboard for terraform-repo

grafana-dashboards/grafana-dashboard-terraform-repo.yaml
[APPSRE-11304](https://issues.redhat.com/browse/APPSRE-11304)
Updates the dashboard to use an instant query to get the inventory. Otherwise, duplicate AWS accounts are shown when QR gets updated.
=> [tf-repo] dashboard fix for inventory

reconcile/aus/base.py
This avoids that one cluster upgrade failure skips the remaining upgrades
=> AUS: do not fail if one cluster upgrade gets rejected

reconcile/gitlab_permissions.py, reconcile/test/test_gitlab_permissions.py
We can create new repos via app-interface. Gitlab-permissions will fail though, if a repo doesn't exist yet. This leads to a chicken-egg problem.
We introduce a skip on non-existing app-interface managed projects, whenever a new addition is detected in the diff.
Tested locally with failing tenant MR.
=> Catch null project

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_repo/terraform_repo.py
[APPSRE-11333](https://issues.redhat.com/browse/APPSRE-11333)
Allow our tenants using secrets for inputs/outputs to have the flexibility to specify one or the other, or both. Basically a [logical "disjunction"](https://en.wikipedia.org/wiki/Logical_disjunction)
Dependent MR:
- [Qontract Schemas](https://github.com/app-sre/qontract-schemas/pull/750)
=> [tf-repo secrets] allow tenants to use inputs OR outputs

tools/cli_commands/cost_report/aws.py, tools/cli_commands/cost_report/openshift.py, tools/cli_commands/cost_report/openshift_cost_optimization.py, tools/qontract_cli.py, tools/test/test_qontract_cli.py
This pull request introduces changes to allow the specification of a `thread_pool_size` parameter in various cost report command creation methods and updates the corresponding CLI commands and tests to support this new parameter.
Set default thread pool size to 5 instead of 10 when run in cli to reduce load on server.
[APPSRE-11357](https://issues.redhat.com/browse/APPSRE-11357)
=> feat(cost-report): adjust thread pool size

reconcile/slack_usergroups.py, reconcile/utils/github_api.py, reconcile/utils/gitlab_api.py, reconcile/utils/repo_owners.py
Don't download the complete git repo file list.
`slack-usergroups` uses just the root level (`.`) `OWNERS` file but downloads a list of all files from the git repos. [clusterimagesets](https://gitlab.cee.redhat.com/service/clusterimagesets) has more than 31000 files, `get_repository_tree` receives the file catalog in 100 chunks. In total, ~310 HTTP requests, and each takes 1 second.
This fix reduces the runtime of a reconciliation loop by 6 minutes.
=> :zap: slack-usergroups: performance fix

reconcile/utils/saasherder/saasherder.py
In case of target marked as deleted and having a publish promotion..all the upcoming subscribe promotion will be blocked..as `_assemble_channels` will still consider the deleted target
fixes : https://issues.redhat.com/browse/APPSRE-11364
=> skip target if deleted while assembling channels for promotion

tools/cli_commands/cost_report/view.py, tools/cli_commands/test/fixtures/openshift_cost_optimization_report_without_items.md, tools/cli_commands/test/test_openshift_cost_optimization_report.py
This pull request introduces changes to handle cases where there are no items in the OpenShift cost optimization report. To save space and use less scrolls when reading report, render no table for app without actual items.
[APPSRE-10233](https://issues.redhat.com/browse/APPSRE-10233)
=> feat(cost-optimization-report): skip json table if no items

reconcile/service_dependencies.py
Fix
```
File "/work/reconcile/cli.py", line 609, in run_class_integration
File "/work/reconcile/utils/runtime/runner.py", line 155, in run_integration_cfg
File "/work/reconcile/utils/runtime/runner.py", line 226, in _integration_dry_run
File "/work/reconcile/utils/runtime/integration.py", line 315, in run
File "/work/reconcile/service_dependencies.py", line 103, in run
desired_deps = get_desired_dependency_names(app, dependency_map)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/work/reconcile/service_dependencies.py", line 37, in get_desired_dependency_names …
```
=> :bug: service-dependencies: fix KeyError

reconcile/dynatrace_token_provider/integration.py, reconcile/test/dynatrace_token_provider/fixtures.py
Follow-up on https://github.com/app-sre/qontract-reconcile/pull/4223
> to be a little consistent with standard qontract resource annotation, and to provide a hint on the Secret that lands on clusters as to what owns it.
=> Proper DTP resource labels

reconcile/dynatrace_token_provider/integration.py, reconcile/test/dynatrace_token_provider/fixtures.py
Follow up on https://github.com/app-sre/qontract-reconcile/pull/4807
Lets also add the DTP version. This helps us to compare if a change actually lead to a reconcile in a secret.
Also adding version to early_exit dict. Not sure if it makes sense, as we always reconcile anyways on version bump w/o early_exit. But at the same time it doesnt harm to have it here.
=> APPSRE-11389 annotate DTP version in secret too

tools/cli_commands/erv2.py, tools/qontract_cli.py
`qontract-cli external-resources force-unlock` subcommand to easily unlock an ERv2 terraform state.
Example usage:
```
$ qontract-cli --config config.prod.toml external-resources --provision-provider aws --provisioner app-sre --provider elasticache --identifier error-tracking-production force-unlock --lock-id 1234-1234-1234
Preparing environment ... 0:00:01
Generated Terraform code for the stacks: CDKTF
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
...
The state has been unlocked, and Terraform commands should now be able to
obtain a new lock on the remote state.
```
Ticket: [APPSRE-11400](https://issues.redhat.com/browse/APPSRE-11400)
=> :sparkles: qontract-cli erv2: force-unlock subcommand

reconcile/utils/github_api.py, uv.lock
Ref: https://redhat-internal.slack.com/archives/GGC2A0MS8/p1737664565157489
GitHub made an API change that broke PyGithub and thus caused lots of 404 errors that were unhandled by our code, see https://github.com/PyGithub/PyGithub/issues/3179
To resolve this, I did a temporary workaround that just checks the generic exception status to see if its a 404 and return `None`, keeping up the same return behavior our functions expect.
=> Temporary workaround for github 404 issues

reconcile/cli.py, reconcile/jira_permissions_validator.py, reconcile/test/test_jira_permissions_validator.py
* Fix default `board-check-interval` to 120 minutes instead of 120 seconds 
* Add random jitter not to check all boards at the same time 
* Remove extended-early-exit because it collides with per board state cache
Ticket: [APPSRE-11408](https://issues.redhat.com/browse/APPSRE-11408)
=> jira-permissions-validator: add jitter and remove extended early exit

dockerfiles/Dockerfile
Use oc binary from 4.16 release.
https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html
Previously, when running a cluster with FIPS enabled, you might have received the following error when running the OpenShift CLI (oc) on a RHEL 9 system: FIPS mode is enabled, but the required OpenSSL backend is unavailable. With this release, the default version of OpenShift CLI (oc) is compiled with Red Hat Enterprise Linux (RHEL) 9 and works properly when running a cluster with FIPS enabled on RHEL 9. Additionally, a version of oc compiled with RHEL 8 is also provided, which must be used if you are running a cluster with FIPS enabled on RHEL 8. ([OCPBUGS-23386](https://issues.redhat.com/browse/OCPBUGS-23386), …
=> use qr oc base image 0.3.1 for FIPS

reconcile/external_resources/factories.py, reconcile/external_resources/manager.py, reconcile/external_resources/model.py, reconcile/gql_definitions/external_resources/external_resources_namespaces.gql, reconcile/gql_definitions/external_resources/external_resources_namespaces.py
=> ERv2: Support for KMS

reconcile/gitlab_housekeeping.py, reconcile/gql_definitions/introspection.json, reconcile/queries.py, reconcile/test/test_gitlab_housekeeping.py, reconcile/utils/gitlab_api.py
allow to check if MR has passed all necessary test jobs and add comments to indicate test results.
=> [APPSRE-11112] add verify_ondemend_tests for gitlab-housekeeping

reconcile/external_resources/aws.py, reconcile/gql_definitions/external_resources/external_resources_namespaces.gql, reconcile/gql_definitions/external_resources/external_resources_namespaces.py, reconcile/gql_definitions/fragments/saas_target_namespace.py, reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/status_board/status_board.py, reconcile/utils/external_resource_spec.py
Add service updates related fields to ERv2 AWS elasticache settings.
Depends on:
* https://github.com/app-sre/qontract-schemas/pull/760
* https://github.com/app-sre/er-aws-elasticache/pull/103
Ticket: [APPSRE-11432](https://issues.redhat.com/browse/APPSRE-11432)
=> :sparkles: external-resources: elasticache service updates

reconcile/jira_permissions_validator.py
Typically, the MR checks run only for the new/updated Jira board. Use the Jira board cache in case of running the MR checks for all boards, e.g., during `qontract-reconcile` promotions.
This will avoid hitting the Jira rate limit during our promotions.
=> :bug: honor jira board cache if dry-run mode runs over all boards

reconcile/external_resources/aws.py, reconcile/test/external_resources/test_rds_factory.py
Fix timeout validation to include formats with 'h' and 'm'. e.g: 2h30m
=> ERv2: Disable RDS timeout validation

tools/qontract_cli.py, uv.lock
[APPSRE-11480](https://issues.redhat.com/browse/APPSRE-11480)
I tried fetching log group data via CloudWatch metrics but ran into limitations due to the vast number of log groups we have in our accounts. This is another approach which fetches the data from the AWS API and outputs it with the command.
=> Add a qontract-cli command for getting logGroup usage from CloudWatch

reconcile/test/utils/test_jjb_client.py, reconcile/utils/jjb_client.py
If jenkins job name contains `/` such as `group/subgroup-project-xxx`, generated jenkins `config.xml` is in nested dir, causing error
```
File "/work/reconcile/jenkins_job_builder.py", line 103, in run
jjb.print_diffs(io_dir, instance_name)
File "/work/reconcile/utils/jjb_client.py", line 177, in print_diffs
self.print_diff(create, desired_path, "create")
File "/work/reconcile/utils/jjb_client.py", line 189, in print_diff
instance, item, _ = f.replace(replace_path + "/", "").split("/")
^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)
```
This PR validates job to ensure no `/` in name.
[APPSRE-11502](https://issues.redhat.com/browse/APPSRE-11502)
=> fix(jjb): validate job name

reconcile/utils/aws_api.py
`init_users` will call `get_session_client`, but cached version `get_session_client` was set after `init_users` call, which means all `iam` clients are not cached. This change moves it to the end of `__init__` to use cached methods.
Compare memory usage for `aws-support-cases-sos` integration:
[memray](https://github.com/bloomberg/memray) profile result compare:
before: 89.4 MiB
after: 7.3 MiB
Other integrations using aws api with `init_users=True` (default `True`) will also benefit from caching if `iam` client used later.
[APPSRE-11506](https://issues.redhat.com/browse/APPSRE-11506)
=> perf(aws-api): init users using cached session client

reconcile/utils/terrascript_aws_client.py
This should fix the deployment of access logs for ALB by adding a policy attached to the bucket ans instructed by AWS docs:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html#access-log-create-bucket 
I've tested this locally using dry run and printing to file.
=> :bug: Add policy to s3 bucket for access logs

reconcile/external_resources/reconciler.py
We want to introduce memory-based quotas to avoid killing the k8s node. If needed, we can replace the hardcoded values with app-interface settings in the future
```
Error creating: pods "er-dry-run-mr-132420-02db23c11d-qhk6p" is forbidden: failed quota: external-resources-quota: must specify limits.memory for: outputs; requests.memory for: outputs
```
Ticket: [APPSRE-11514](https://issues.redhat.com/browse/APPSRE-11514)
=> :zap: external-resource: specify memory limits for outputs-secret container

reconcile/test/ocm/test_utils_ocm_labels.py, reconcile/utils/ocm/labels.py
Simple call to get a dict of cluster labels via OCM client.
Note, that cluster label is very different from our existing labels. Cluster label does not contain any timestamp or type attribute. I.e., adding it as an `OCMLabel`, would require substantial change in the base class which might not be worth it for this effort.
=> APPSRE-11390 get cluster labels

reconcile/utils/terrascript_aws_client.py
The ELB account id map comes from AWS documentation:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html#access-log-create-bucket
Depending on the region we need to select the `"Principal"` for the policy.
=> Select the correct policy for access_logs bucket based on region

tools/qontract_cli.py, tools/test/test_qontract_cli.py
This pull request to `tools/qontract_cli.py` and `tools/test/test_qontract_cli.py` introduces a new function for fetching external resource credentials and refactors existing code to use this new function. Additionally, new tests are added to ensure the functionality works as expected.
Example usage
```shell
qontract-cli --config $CONFIG external-resources --provisioner $PROVISIONER --provider $PROVIDER --identifier $IDENTIFIER get-credentials
```
* Added `_get_external_resources_credentials` function to fetch external resource credentials.
* Refactored `migrate`, `debug_shell`, and `force_unlock` functions to use the new `_get_external_resources_credentials` function instead of directly reading credentials. [[1]](diffhunk://#diff-b578cd66cb4dad72a0138f86ff8b6e4c241eb0850381f1d8cf3133a651c …
=> [ERv2] add new commands to get credentials for debug

reconcile/aws_account_manager/merge_request_manager.py, reconcile/aws_version_sync/merge_request_manager/merge_request_manager.py, reconcile/endpoints_discovery/merge_request_manager.py, reconcile/saas_auto_promotions_manager/merge_request_manager/merge_request_manager_v2.py, reconcile/terraform_init/merge_request_manager.py, reconcile/terraform_vpc_resources/merge_request_manager.py, reconcile/test/aws_version_sync/merge_request_manager/test_avs_merge_request_manager.py, reconcile/test/endpoints_discovery/test_endpoints_discovery_merge_request_manager.py, reconcile/test/templating/test_renderer.py, reconcile/test/terraform_init/test_terraform_init_merge_request_manager.py, reconcile/test/utils/vcs/conftest.py, reconcile/test/utils/vcs/test_vcs.py, reconcile/utils/vcs.py
Our `vcs.get_file_content_from_app_interface_master` function only fetches data from the `data/` folder in `master`. However, we would like to be able to use this method on other app-interface instances too, such as `sre-capabilities` (i.e., `main` branch). In this PR we:
- allow fetching from any ref
- allow fetching outside `data/` folder
- rename function name appropriately to avoid confusion
- add tests for this function
- keep fully backwards compatible via function defaults
=> APPSRE-11390 vcs more fetch options

grafana-dashboards/grafana-dashboard-terraform-repo.yaml
[APPSRE-11538](https://issues.redhat.com/browse/APPSRE-11538)
Improves Terraform Repo visibility by updating the Grafana dashboard to allow for querying per PipelineRun. I'll update docs and the Slack message posted when a PipelineRun completes to reflect this change.
=> update terraform repo grafana dashboard to filter based on pipelineruns

reconcile/aws_version_sync/integration.py
AVS needs to compare the formatted engine version strings and not the "raw" values. For example, ElastiCache 6+ reports `MAJOR.MINOR.PATCH` but the AWS API (and app-interface) must use `MAJOR.MINOR`.
This will avoid those [MRs](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/133434)
Ticket: [APPSRE-11542](https://issues.redhat.com/browse/APPSRE-11542)
=> :bug: aws-version-sync: compare final engine version strings

reconcile/statuspage/page.py
Ignore `StatusMaintenance.components.status_provider_configs` in the diff detection because it's not available in the desired state.
This will avoid the `[status-page-maintenances] Update StatusPage Maintenance is not supported at this time` warning. E.g. https://redhat-internal.slack.com/archives/CS0E65QCV/p1739882499198949
=> :bug: status-page-maintenances: fix diff detection

reconcile/utils/terrascript_aws_client.py
When the tenant removes the `access_lotg: true` from the ALB resource in `app-interface` the integration fails to remove the bucket because the log files are still present.
This forces the deletion of the bucket along with all the log files.
=> 🐛  BugFix: Force destroy access_logs buckets

reconcile/external_resources/secrets_sync.py, reconcile/test/external_resources/test_outputs_formatter.py
Erv2 does not need output prefixes since the state is not shared across the resources
=> Erv2 outpouts don't need to have __ to get populated

grafana-dashboards/grafana-dashboard-terraform-repo.yaml
Updates the Grafana dashboard from Terraform Repo to display log lines as oldest first and update the pipelinerun variable to refresh on dashboard time range update:
Thanks @hemslo for the tip!
=> update tf-repo dashboard to sort log lines oldest first

reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/test/ocm/aus/test_ocm_upgrade_scheduler_org.py
`aus_addon_version_remaining_soak_days` metric is broken when multiple addons in one cluster, when exposing metrics, `org_upgrade_spec` (with all addons) was used, expect to expose per addon (`addon_org_upgrade_spec`).
This PR changes all usages in addons iteration to use `addon_org_upgrade_spec` to avoid confusion.
[APPSRE-11549](https://issues.redhat.com/browse/APPSRE-11549)
=> fix(aus): expose matching remaining soak days for addon

reconcile/fleet_labeler/dependencies.py, reconcile/fleet_labeler/integration.py, reconcile/fleet_labeler/vcs.py, reconcile/test/fleet_labeler/conftest.py, reconcile/test/fleet_labeler/fixtures.py, reconcile/test/fleet_labeler/test_fleet_labeler_dry_run.py
We must handle newly created fleet labeler spec files, which are not in main branch yet.
Since these files are not in main branch, we cannot fetch their current content from VCS. If we are in dry-run and hit a 404 on a vcs fetch, then this is very likely because we are adding a new spec file. In that case we can skip the rendering steps, as the desired diff has already been printed before.
We could also skip the rendering altogether in dry-run, however, most MRs will be on existing files. Having the rendering procedure run on those adds extra certainty in MR check, which is why we should keep it for dry-run.
If we are not in dry-run or receive any other non 404 error, then the integration should still fail.
=> APPSRE-11390 fleet labeler - handle new spec files

reconcile/external_resources/manager.py, reconcile/external_resources/model.py
When overriding a module configuration: 
* The associated MR must run the DRY_RUN reconciliation. 
* When merged, the resource must be reconciled.  
This only applies with module_overrides, not when updating the default module versions.
=> Module overrides should trigger reconciliations

reconcile/fleet_labeler/integration.py, reconcile/fleet_labeler/merge_request.py, reconcile/fleet_labeler/ocm.py, reconcile/gql_definitions/fleet_labeler/fleet_labels.gql, reconcile/gql_definitions/fleet_labeler/fleet_labels.py, reconcile/gql_definitions/introspection.json, reconcile/test/fixtures/fleet_labeler/1_cluster.yaml, reconcile/test/fixtures/fleet_labeler/2_clusters.yaml, reconcile/test/fleet_labeler/fixtures.py, reconcile/test/fleet_labeler/test_fleet_labeler_cluster_inventory_lifecycle.py, reconcile/test/fleet_labeler/test_fleet_labeler_dry_run.py, reconcile/test/fleet_labeler/test_fleet_labeler_filters.py
Add `subscriptionId` to clusters inside fleet labelers inventories.
Fleet labeler uses this `subscriptionId` to properly synchronize subscription labels (will be part of follow-up PR).
Schema: https://github.com/app-sre/qontract-schemas/pull/773
=> APPSRE-11390 store subscription_id in inventory

reconcile/fleet_labeler/integration.py, reconcile/fleet_labeler/meta.py, reconcile/fleet_labeler/ocm.py, reconcile/test/fleet_labeler/test_fleet_labeler_dry_run.py, reconcile/test/fleet_labeler/test_fleet_labeler_label_synch.py
The Fleet Labeler integration already has the ability to synchronize cluster inventories and declare desired subscription label state.
In this PR, we leverage the existing desired subscription label state and make the actual OCM API calls to create/update subscription labels to have them in synch with the fleet-labeler-spec.
Note, that we intentionally do not remove labels under the managed prefix. This might lead to unwanted removals on prefixes with many sub keys, which might not be managed by fleet labeler. However, if desired, this could easily be added later (maybe with an optional flag in the spec).
=> APPSRE-11390 fleet labeler synchronize subscription labels

reconcile/fleet_labeler/integration.py, reconcile/fleet_labeler/ocm.py, reconcile/test/fleet_labeler/test_fleet_labeler_filters.py
The `discover_clusters_by_labels()` function currently only populates labels into the result that are part of the filter. Our desired labels are not part of the default label matchers.
To circumvent this, we for now widen the filter by an `OR {spec.managed_prefix}.%` query. This will lead to all managed labels being populated into the `ClusterDetails` result.
Note, that the API call overhead here is neglectable, since we anyways most of the times have to fetch subscription labels for the whole inventory and our currently managed prefixes are very exclusive. Still, longterm, we should fix this by extending the utils.ocm module to provide this functionality.
=> APPSRE-11390 fleet labeler - fix filter

reconcile/dynatrace_token_provider/integration.py, reconcile/dynatrace_token_provider/ocm.py
DTP should favor v2 labels now.
fleet-labeler already migrated integration/staging cluster labeling to the v2 schema.
Production clusters are not yet affected by this yet, which is why we keep the old labeling schema as fallback.
Note, also made adjustments to log `cluster.id` instead `cluster.external_id`, because `cluster.id` is used by fleet labeler (makes debugging easier).
=> APPSRE-11584 DTP use v2 labels

reconcile/fleet_labeler/integration.py, reconcile/gql_definitions/fleet_labeler/fleet_labels.gql, reconcile/gql_definitions/fleet_labeler/fleet_labels.py, reconcile/gql_definitions/introspection.json, reconcile/test/fixtures/fleet_labeler/2_clusters-alternative.yaml, reconcile/test/fleet_labeler/test_fleet_labeler_dry_run.py
Extra flag to disable label synchronization for a spec.
This is especially useful for prod environments, if you want to let fleet labeler render the inventory first and investigate/change any desired labels manually before the first synchronization starts.
Schema: https://github.com/app-sre/qontract-schemas/pull/778
=> APPSRE-11584 fleet-labeler: optional disable label synch

reconcile/dynatrace_token_provider/integration.py, reconcile/dynatrace_token_provider/ocm.py
Our fleet labeler capability is now managing DTP subscription labels. Lets enforce the v2 labeling schema and drop backwards compatibility with old schemas. Since fleet labeler is managing the labels, all the labels for the new schema already exist on the subscriptions.
Note, that for now we log a warning if expected labels are missing. During the DTPv3 transition, we will expose this as a metric. If we run into this case, it is likely that fleet-labeler didnt label the cluster yet - however, it should do so soon - thus we shouldnt fail here.
=> APPSRE-11584 DTP enforce v2 labels

reconcile/fleet_labeler/dependencies.py, reconcile/fleet_labeler/integration.py, reconcile/fleet_labeler/validate.py, reconcile/gql_definitions/fleet_labeler/fleet_labels.gql, reconcile/gql_definitions/fleet_labeler/fleet_labels.py, reconcile/gql_definitions/introspection.json, reconcile/test/fixtures/fleet_labeler/0_clusters.yaml, reconcile/test/fixtures/fleet_labeler/0_clusters_no_defaults.yaml, reconcile/test/fixtures/fleet_labeler/1_cluster.yaml, reconcile/test/fixtures/fleet_labeler/1_cluster_no_defaults.yaml, reconcile/test/fixtures/fleet_labeler/2_clusters-alternative.yaml, reconcile/test/fixtures/fleet_labeler/2_clusters.yaml, reconcile/test/fleet_labeler/conftest.py, reconcile/test/fleet_labeler/fixtures.py, reconcile/test/fleet_labeler/test_fleet_labeler_spec_validation.py
Fleet Labeler should use `OCMEnvironment` directly instead of going via `ClusterManager`. We currently have no need for any `ClusterManager` attributes.
This also makes it easier to align Fleet Labeler with DTP, as currently both are using different OCM tokens, which leads to different cluster discovery results.
Using `OCMEnvironment` directly eases spec validation as most things are covered at schema check. Further, we require use of our sre-capa tokens in the environments to see more clusters.
Schema: https://github.com/app-sre/qontract-schemas/pull/781
=> APPSRE-11583 FleetLabeler use OCMEnvironment

reconcile/utils/quay_api.py
Removing a user from the last team throws a new API error:
```
User cannot remove themselves from their only admin team.
```
Ignore it and delete the user anyway.
=> :bug: quay-memberships: fix user removal from last team

reconcile/gitlab_owners.py
this PR adds support to use a gitlab group in an OWNERS file.
the implementation is to iterate over each name, and if it's a group - add it's members to the list of approvers.
required to support a self-service onboarding, for example: https://gitlab.cee.redhat.com/service/managed-tenants/-/merge_requests/4870
=> [gitlab-owners] support groups

reconcile/external_resources/integration.py
I observed cases where DRY_RUN  runs are made with `dry_run_job_suffix = ""`.  This parameter contains the MR number to identify the MR on the job pods. I think Jenkins launches these runs under certain circumstances. 
DRY_RUN runs must always run under an MR context. Therefore, these runs will be terminated with a RuntimeException.
=> ERv2: RuntimeError when dry_run without dry_run_job_suffix

reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/utils/terrascript_aws_client.py
ALB health checks should be configurable. The defaults are taken from currently provisioned ALB instances.
schema: https://github.com/app-sre/qontract-schemas/pull/783
Verified locally by changing only a few target groups
```
qontract-reconcile-terraform-resources  | [2025-03-18 10:15:17] [INFO] [DRY-RUN] [terraform_client.py:log_plan_diff:374] - ['update', 'quayio-prod', 'aws_lb_target_group', 'quayio-production-alb01-quay-pull', {'health_check'}]
qontract-reconcile-terraform-resources  | [2025-03-18 10:15:17] [INFO] [DRY-RUN] [terraform_client.py:log_plan_diff:374] - ['update', 'quayio-prod', 'aws_lb_target_group', 'quayio-production-alb01-quay-push', {'health_check'}]
qontract-reconcile-terraform-resources  | [2025-03-18 10:15:17] [INFO] [DRY-RUN] …
```
=> APPSRE-11551 ALB health checks

dockerfiles/Dockerfile, reconcile/utils/promtool.py
lots of
```
.venv/lib64/python3.11/site-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
```
in many integrations
This reverts commit c434b28c1cc5cd4858d1cd4cee9a235041925416.
reverting https://github.com/app-sre/qontract-reconcile/pull/4908
=> Revert "promtool 2.54.1 (#4908)"

dockerfiles/Dockerfile, reconcile/utils/promtool.py
and an update of the base images. This patch contains an attempt to fix the issues found in #4908 wrt timezones, see https://github.com/app-sre/container-images/pull/186
APPSRE-11598
=> promtool 2.54.1 (#4908)

reconcile/gql_definitions/aws_account_manager/aws_accounts.gql, reconcile/gql_definitions/aws_account_manager/aws_accounts.py, reconcile/gql_definitions/introspection.json
The resulting account file path in app-interface must be configurable. This PR adds `accountFileTargetPath` to customize the path.
Ticket: [APPSRE-11540](https://issues.redhat.com/browse/APPSRE-11540)
=> :sparkles: aws-account-manager: customizable AWS account file path

reconcile/aws_account_manager/integration.py, reconcile/gql_definitions/aws_account_manager/aws_accounts.gql, reconcile/gql_definitions/aws_account_manager/aws_accounts.py, reconcile/gql_definitions/introspection.json, reconcile/test/aws_account_manager/test_aws_account_manager_integration.py
This PR enhances the `aws-account-manager` integration to be able to tag all organization accounts with tags based on the payer account (`/aws/account-1/organizationAccountTags`).
Depends on: https://github.com/app-sre/qontract-schemas/pull/785
Ticket: [APPSRE-11633](https://issues.redhat.com/browse/APPSRE-11633)
=> :sparkles: aws-account-manager: tag org accounts

reconcile/openshift_base.py
Handle immutable field deployment changes by recreating the deployment objects. 
* This only happens when immutable fields are changed. 
* This rollout strategy has an intrinsic downtime when this behavior happens, this code only automates it.
=> Handle immutable field changes in Recreate type deployments

grafana-dashboards/sre-capability-aus.configmap.yaml
https://issues.redhat.com/browse/APPSRE-11646
* Avoid duplicate series on integration restart
* Display 0 when no value
* Colorize long running upgrades (>= 6h)
* Nicer colum names
=> AUS dashboard: few fixes on ongoing upgrades panels

grafana-dashboards/sre-capability-aus.configmap.yaml
https://issues.redhat.com/browse/APPSRE-11646
The null value ends up being dropped on JSON dashboards and are replaced by `0` instead of `NaN`. So let's use a very high number
=> AUS dashboard ongoing upgrades: fix color mapping

reconcile/openshift_serviceaccount_tokens.py, reconcile/test/test_openshift_serviceaccount_tokens.py
secret without data (created by `service_account_token_request`) should be ignored when write to vault.
[APPSRE-11650](https://issues.redhat.com/browse/APPSRE-11650)
=> fix(openshift_serviceaccount_tokens): handle secret without data

reconcile/aws_account_manager/integration.py, reconcile/aws_account_manager/reconciler.py, reconcile/gql_definitions/aws_account_manager/aws_accounts.py, reconcile/gql_definitions/fragments/aws_account_managed.gql, reconcile/gql_definitions/fragments/aws_account_managed.py, reconcile/test/aws_account_manager/test_aws_account_manager_integration.py, reconcile/test/aws_account_manager/test_aws_account_manager_reconciler.py, reconcile/test/fixtures/aws_account_manager/accounts.yml, reconcile/test/utils/aws_api_typed/test_aws_api_typed_account.py, reconcile/utils/aws_api_typed/account.py
This PR adds region support to the `aws-account-manager`. Users can enable and disable AWS regions for an account via the `/aws/account-1/supportedDeploymentRegions` attribute. 
The 15 default-enabled AWS regions can't be enabled/disabled and are ignored by the integration.
Additionally, this PR enhances the log messages.
Ticket: [APPSRE-11624](https://issues.redhat.com/browse/APPSRE-11624)
=> :sparkles: aws-account-manager: enable/disable regions

reconcile/external_resources/aws.py
`old_parameter_group` no longer needed in ERv2 RDS
[APPSRE-11657](https://issues.redhat.com/browse/APPSRE-11657)
=> chore(erv2): deprecate old_parameter_group

tools/cli_commands/erv2.py
By default `WORK` not set then script will use `/work`, it's not exist as should be mounted as volume in real run, no permission to create it in container, so use `/tmp/work` when debug.
Updates to docstrings and environment variables:
* [`tools/cli_commands/erv2.py`](diffhunk://#diff-d751b0b90dc403eba502fee7947218c9887f5ce4b3dc2d0c4236b4b8f5a12fccL225-R225): Updated the docstring in the `enter_shell` method to refer to the ERv2 container instead of the CDKTF container.
* [`tools/cli_commands/erv2.py`](diffhunk://#diff-d751b0b90dc403eba502fee7947218c9887f5ce4b3dc2d0c4236b4b8f5a12fccR245-R246): Added the `WORK=/tmp/work` environment variable in the `enter_shell` method.
=> fix(erv2): set WORK env for debug-shell

reconcile/aus/advanced_upgrade_service.py, reconcile/aus/aus_label_source.py, reconcile/aus/base.py, reconcile/aus/models.py, reconcile/gql_definitions/advanced_upgrade_service/aus_clusters.py, reconcile/gql_definitions/advanced_upgrade_service/aus_organization.py, reconcile/gql_definitions/common/clusters.gql, reconcile/gql_definitions/common/clusters.py, reconcile/gql_definitions/fragments/aus_organization.gql, reconcile/gql_definitions/fragments/aus_organization.py, reconcile/gql_definitions/introspection.json, reconcile/queries.py, reconcile/test/ocm/aus/fixtures.py, reconcile/test/ocm/aus/test_aus_label_source.py, reconcile/test/ocm/aus/test_calculate_diff.py
https://issues.redhat.com/browse/APPSRE-11690
Adding support for limiting the number of parallel upgrades within a sector. The main changes involve adding new fields and methods to handle the `maxParallelUpgrades` attribute for sectors, updating existing functions to consider this new attribute, and adding tests to verify the new functionality.
The new field is added as part of https://github.com/app-sre/qontract-schemas/pull/802
The main change is in commit 4618c40f2c380c460fd4c467bba9e94c8afe8aa8, updating `reconcile/aus/base.py` to introduce the function `verify_max_upgrades_should_skip`
=> APPSRE-11690 AUS max parallel upgrades

reconcile/external_resources/aws.py
Use deepcopy to generate resolved data to ensure that we don’t modify the date in ExternalResourceSpec.resource. This prevents issues when resolving sourcedb [here](https://github.com/app-sre/qontract-reconcile/blob/aa32044ed8d80e20751c80486f63a8e801cc2315/reconcile/external_resources/aws.py#L176), where we might find that target["parameter_group"] has been replaced by a dictionary. e.g https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/137521
=> fix blue_green_deployment target parameter_group

tools/qontract_cli.py
filter out deleted namespace, remove ca_cert_identifier as upgrade finished for all fleet.
=> fix rds output

reconcile/templates/email.yml.j2
Fix failed generated email yaml due to indentation, example [mr](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/138375).
=> fix(email): reformat email template to match yamllint

reconcile/external_resources/aws.py, reconcile/test/external_resources/test_rds_factory.py
Expose the whole `blue_green_deployment` in `replica_source` to support more validations in https://github.com/app-sre/er-aws-rds/pull/139
[APPSRE-11714](https://issues.redhat.com/browse/APPSRE-11714)
=> feat(erv2): expose blue_green_deployment in replica_source

Makefile, README.md, dockerfiles/Dockerfile
`run-integration` script created by `uv sync` has shebang `#!/work/.venv/bin/python3`, can't simply move `.venv` to `/venv`, have to run `uv sync` under the new location.
Now use `/opt/app-root/src` as code dir in `dev-image` to hold `.venv`.
=> fix(dev): update config to make dev-reconcile-loop works with uv setup

reconcile/utils/terrascript_aws_client.py
nodejs10.x is no longer supported for creating or updating AWS Lambda functions
=> fix default lambda runtime

tools/qontract_cli.py
The namespace field is None for namespace resources and results in 
```
16:43:46   File "/work/reconcile/utils/output.py", line 15, in print_output
16:43:46     content = sorted(content, key=lambda c: tuple(c.values()))
16:43:46               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:43:46 TypeError: '<' not supported between instances of 'str' and 'NoneType'
```
=> fix selectorsyncset_managed_resources

reconcile/openshift_tekton_resources.py, reconcile/queries.py, reconcile/test/fixtures/openshift_tekton_resources/provider1.json, reconcile/test/fixtures/openshift_tekton_resources/provider2-with-resources.json, reconcile/test/fixtures/openshift_tekton_resources/provider5-with-unknown-task.json, reconcile/test/fixtures/openshift_tekton_resources/provider6-too-long-pipeline-name.yaml, reconcile/test/fixtures/openshift_tekton_resources/provider7-deleted-namespace.json, reconcile/test/fixtures/openshift_tekton_resources/saas7-deleted-namespace.json, reconcile/test/test_openshift_tekton_resources.py
https://issues.redhat.com/browse/APPSRE-11857
Avoids continuous logs like
```
[openshift-tekton-resources] [<cluster>/<namespace>] namespace does not exist (yet).
```
=> Skip pipeline setup on deleted namespaces

reconcile/utils/terrascript_aws_client.py
Follow-up from #4961
[APPSRE-11853](https://issues.redhat.com/browse/APPSRE-11853)
This PR allows users to add additional secrets to their Elasticsearch `admin_user_credentials` secret which can then be used when setting up a Kinesis lambda (https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/utils/terrascript_aws_client.py#L3994). The additional values are stripped out when provisioning the Elasticache domain to meet the expected schema from AWS.
```yaml
$schema: /aws/elasticsearch-defaults-1.yml
ebs_options:
ebs_enabled: true
volume_size: 350
auth:
admin_user_credentials:
path: <your_vault_path_here>
```
=> [elasticsearch] allow additional keys in admin credentials

reconcile/openshift_saas_deploy_trigger_base.py
https://issues.redhat.com/browse/APPSRE-11873
This will trickle down to the pods as well, and it will appear in cloudwatch logs as a filterable field. This means we can filter logs in cloudwatch per commitref
=> add trigger information to pipelinerun annotations

reconcile/dynatrace_token_provider/integration.py, reconcile/dynatrace_token_provider/model.py, reconcile/dynatrace_token_provider/ocm.py, reconcile/test/dynatrace_token_provider/conftest.py, reconcile/test/dynatrace_token_provider/fixtures.py, reconcile/test/dynatrace_token_provider/test_create_manifest.py, reconcile/test/dynatrace_token_provider/test_create_syncset.py, reconcile/test/dynatrace_token_provider/test_dry_run.py, reconcile/test/dynatrace_token_provider/test_no_change_manifest.py, reconcile/test/dynatrace_token_provider/test_no_change_syncset.py, reconcile/test/dynatrace_token_provider/test_ocm_org_filters.py, reconcile/test/dynatrace_token_provider/test_patch_manifest.py, reconcile/test/dynatrace_token_provider/test_patch_syncset.py, reconcile/test/dynatrace_token_provider/test_spec_token_diff.py
This is in preparation for DTP `v3` labeling. The new labeling will allow multiple `tenant:spec` label pairs for every cluster.
This PR is mainly a refactor for:
- Preparing structure to allow multiple `Tenant:Spec` pairs for clusters
- moving label parsing logic out of ocm abstraction layer and into integration logic, because it will grow more complex with `v3` -> this makes it part of the test logic now
- adjusting tests to properly harbor label parsing logic
Note, that we still keep the old `v2` labeling in place. **The functionality does not change in this PR.**
In follow a follow up PR we will address the new DTP `v3` labeling itself.
=> APPSRE-11142 DTP allow multiple specs per cluster

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py
This is necessary for `terraform-resources` to be aware of `cloudwatch` resources that should be excluded, due to management within `external-resources`.
This is also a dependency for https://github.com/app-sre/qontract-reconcile/pull/4967 and follow up to https://github.com/app-sre/qontract-reconcile/pull/4955
Similar PR for ref: https://github.com/app-sre/qontract-reconcile/pull/4742
=> terraform-resources erv2 cloudwatch support

reconcile/utils/terrascript_aws_client.py
Fixes a bug/quirk with aws-terraform-provider when cognito token expiration units are not defined.
Starting with just the ocm-ams client to reduce blast radius.
Issue explained here: https://github.com/hashicorp/terraform-provider-aws/issues/32504
AWS console UI appears to apply "default" token duration units as follows when saving changes to cognito clients:
```
token_validity_units={
"access_token":  "minutes",
"id_token":      "minutes",
"refresh_token": "days"
}
```
This conflicts with terraform-aws-provider's default units. For `access_token` and `id_token`, AWS console seems to default to `minutes`, while terraform-aws-provider defaults these to `hours`. Both default `refresh_token` to `days`.
By making QR and the AWS console UI use the same "default" unit types, we reduce the …
=> [FR] Fix cognito token-duration units (ocm-ams client only)

reconcile/utils/terrascript_aws_client.py
followup to: https://github.com/app-sre/qontract-reconcile/commit/dd3d6bfce88232b153dd179e99a36f3bdacc5a87
Same idea, but applying duration units to all tokens.
This should have no impact on the commercial environment.
Caution and manual intervention will likely be needed when promoting this in FedRAMP.
For example, a cognito client access token pre-promotion with a "1 hour" expiration may be changed to "1 minute" as a result of this PR being promoted. In such a case, values should be changed as needed for each client in the stage and prod FR AWS accounts via the AWS console UI immeadiately after promotion (e.g., change "1 minute" to "1 hour").
=> [FR] Fix cognito token-duration units (all clients)

reconcile/utils/terrascript_aws_client.py
Adds a fleet-manager user-pool-client under the rosa-authenticator terraform-resource.
Part of [OCM-12752] as part of the FR HCP buildout.
=> [FR] create fleet-manager user-pool-client under rosa-authenticator

tools/cli_commands/erv2.py, tools/qontract_cli.py
Currently, `external-resources` integration `migrate` functionality only supports modules of type `cdktf`. `cdktf` has been deprecated in favor of HCL(type `terraform`) modules. This PR adds state migration support for HCL modules.
Depends on ERv2 modules built on base image that includes change in https://github.com/app-sre/er-base-terraform/pull/27
=> APPSRE-11886: Add support to migrate HCL/terraform modules

reconcile/gcp_image_mirror.py, reconcile/quay_mirror.py, reconcile/test/test_quay_mirror.py, reconcile/utils/quay_mirror.py
Moves `sync_tag` function from a class method in quay_mirror.py to a shared method so that gcp_image_mirror can use the same logic.
The reason for this change is because this prior MR https://github.com/app-sre/qontract-reconcile/pull/4740 was only applied to one integration and not the other. Longer term we should look into doing class inheritence with the integrations to cut down on duplicated code (https://issues.redhat.com/browse/APPSRE-12007).
[APPSRE-11221](https://issues.redhat.com/browse/APPSRE-11221?filter=-1)
=> move sync_tag to shared file for GCP sync + quay mirror

reconcile/quay_mirror_org.py, uv.lock
`quay_mirror_org` is also using the same function, updates usage after function move from https://github.com/app-sre/qontract-reconcile/pull/4974.
Also sync uv.lock file, not sure why it's missed in https://github.com/app-sre/qontract-reconcile/pull/4969.
=> fix(quay_mirror_org): update util function usages

reconcile/acs_rbac.py
A gap in permissions provided by the `vuln-admin` permission set has been uncovered: `vuln-admin` allows **generating** reports using existing report templates but does not allow **creation** of new report templates.  
depends on https://github.com/app-sre/qontract-schemas/pull/827
=> APPSRE-12023 - expand ACS permission set mappings

reconcile/aus/base.py, reconcile/test/ocm/aus/test_base.py, reconcile/test/ocm/aus/test_calculate_diff.py
https://issues.redhat.com/browse/APPSRE-12022
The AUS `maxParallelUpgrades` setting needs to be applied to each tuple sector+mutex
If the sector `maxParallelUpgrades`  setting is not set (or there are no sector defined), mutexes keep their original behavior: only 1 cluster can hold the mutex and be upgraded
If the sector `maxParallelUpgrades`  setting is set and there are no mutexes set, the setting is not effective. Each cluster in the sector actually has its own mutex, the setting applies individually to each cluster and thus allows its upgrade.
If the sector `maxParallelUpgrades`  setting is set and multiple clusters of teh sector share a single mutex, the setting applies to each list of clusters sharing the same mutex (& sector).
When a cluster has multiple mutexes, it is checked …
=> APPSRE-12022 AUS apply maxParallelUpgrades on sector+mutex tuples

reconcile/gitlab_members.py, reconcile/gitlab_permissions.py, reconcile/test/test_gitlab_permissions.py, reconcile/test/utils/test_gitlab_api.py, reconcile/utils/github_api.py, reconcile/utils/gitlab_api.py, reconcile/utils/repo_owners.py, reconcile/utils/saasherder/saasherder.py
deprecate old `get_items`, use [keyset pagination](https://docs.gitlab.com/api/rest/#keyset-based-pagination) by default, follow [python-gitlab doc](https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination).
[APPSRE-10450](https://issues.redhat.com/browse/APPSRE-10450)
* Replaced `get_items` utility with direct use of iterators (`iterator=True`) for API calls in methods like `get_group_members`, `get_project_maintainers`, and `get_group_id_and_projects`. This improves efficiency and aligns with GitLab's pagination model. [[1]](diffhunk://#diff-1d5ab1abb6ecb1d8c243a9e8c04d4cf6505e6be2c8932df654ea9a11c6c1b64bL270-R279) [[2]](diffhunk://#diff-1d5ab1abb6ecb1d8c243a9e8c04d4cf6505e6be2c8932df654ea9a11c6c1b64bL312-R316) [[3]](diffhunk://#diff-1d5ab1abb6ecb1d8c243a9e8c04d4cf6505e6b …
=> feat(gitlab): use keyset pagination as default

reconcile/test/utils/test_gitlab_api.py, reconcile/utils/gitlab_api.py
Fix wrong methods replace in https://github.com/app-sre/qontract-reconcile/pull/4981/files#diff-1d5ab1abb6ecb1d8c243a9e8c04d4cf6505e6be2c8932df654ea9a11c6c1b64bR271.
Should use `members_all` instead of just `members`.
[APPSRE-10450](https://issues.redhat.com/browse/APPSRE-10450)
=> fix(gitlab_fork_compliance): use members_all instead of members

reconcile/automated_actions/config/integration.py, reconcile/test/automated_actions/conftest.py
Persist the `maxOps` action attribute in the automated-action config to enable throttling support.
Ticket: [APPSRE-12021](https://issues.redhat.com/browse/APPSRE-12021)
=> :sparkles: automated-actions-config: throttling support

reconcile/gql_definitions/acs/acs_policies.gql, reconcile/gql_definitions/acs/acs_policies.py, reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/jira_permissions_validator/jira_boards_for_permissions_validator.gql, reconcile/gql_definitions/jira_permissions_validator/jira_boards_for_permissions_validator.py, reconcile/jira_permissions_validator.py, reconcile/test/fixtures/jira_permissions_validator/boards.yml, reconcile/test/test_acs_notifiers.py, reconcile/test/test_acs_policies.py, reconcile/test/test_jira_permissions_validator.py, reconcile/utils/acs/notifiers.py, reconcile/utils/jira_client.py
Adapt `jira-permissions-validator` and `acs-notifiers` to verify and use the common `jira-board.issueFields` as a replacement for `issueSecurityId`.
This allows any arbitrary issue field definitions for our tenants, such as the new `Work Type` one.
Ticket: [APPSRE-12034](https://issues.redhat.com/browse/APPSRE-12034)
Depends on: https://github.com/app-sre/qontract-schemas/pull/828
=> :recycle: jira-boards: common issueFields 

reconcile/aus/base.py, reconcile/aus/metrics.py, reconcile/aus/ocm_addons_upgrade_scheduler_org.py, reconcile/aus/ocm_upgrade_scheduler.py
https://issues.redhat.com/browse/APPSRE-11140
Will allow to inform (dashboard or alert) users on missing version gate agreements
copilot summary:
This pull request introduces a new metric to track missing version gate agreements during cluster upgrades and updates related functionality to improve clarity and consistency. The most significant changes include adding a new gauge metric, modifying how missing gates are logged, and updating method signatures to support integration identification.
* Added a new gauge metric `AUSClusterMissingVersionGateAgreementsGauge` to track the number of missing version gate agreements for a cluster and a target version prefix. (`reconcile/aus/metrics.py`, [reconcile/aus/metrics.pyR59-R70](diffhunk://#diff-6d929caa7ce45dabb9f7f13fb859dfccfe166af3da59f2d8dbec …
=> [AUS] new cluster_missing_version_gate_agreements metric

reconcile/dashdotdb_dora.py, reconcile/github_repo_permissions_validator.py, reconcile/integrations_manager.py, reconcile/service_dependencies.py, reconcile/test/utils/test_gitlab_api.py, reconcile/test/utils/test_terrascript_aws_client.py, reconcile/utils/gitlab_api.py, reconcile/utils/jjb_client.py, reconcile/utils/saasherder/saasherder.py, reconcile/utils/terrascript_aws_client.py, reconcile/utils/vcs.py
Use [Get file archive](https://docs.gitlab.com/api/repositories/#get-file-archive) to download tar.gz file for a dir instead of iterate repo tree then download files one by one.
Also refactor determine if a repo is for GitHub or GitLab by extract `GITHUB_BASE_URL` and do strict prefix match to avoid gitlab repo name contains `github` to be classified as GitHub repo.
[APPSRE-12038](https://issues.redhat.com/browse/APPSRE-12038)
* Added `GITHUB_BASE_URL` constant in `reconcile/utils/vcs.py` to centralize the GitHub base URL.
* Replaced hardcoded GitHub URL strings with `GITHUB_BASE_URL` in various files and functions, such as `compare`, `_github_compare_commits`, and `_get_directory_contents`. [[1]](diffhunk://#diff-a1ca374a2cf09b0d017bff4299973c839cdc1380b48f5332350204abf7c43feeL424-R425) …
=> [gitlab] Use archive api to download dir

reconcile/terraform_tgw_attachments.py
`account_name` is a `str | None`, join by `_` will lead to unexpected result. For example, `'_'.join("app-sre")` will return `a_p_p_-_s_r_e`.
=> fix(terraform_tgw_attachments): use correct shard name

reconcile/utils/slack_api.py
response_metadata may be empty for a newly created channel.
=> fix get_flat_conversation_history

pyproject.toml, reconcile/dashdotdb_dora.py, reconcile/test/utils/test_github_api.py, reconcile/test/utils/test_gitlab_api.py, reconcile/test/utils/test_mr_clusters_updates.py, reconcile/test/utils/vcs/test_vcs.py, reconcile/utils/github_api.py, reconcile/utils/gitlab_api.py, reconcile/utils/jinja2/utils.py, reconcile/utils/mr/aws_access.py, reconcile/utils/mr/clusters_updates.py, reconcile/utils/mr/ocm_update_recommended_version.py, reconcile/utils/mr/ocm_upgrade_scheduler_org_updates.py, reconcile/utils/mr/promote_qontract.py, reconcile/utils/mr/update_access_report_base.py, reconcile/utils/mr/user_maintenance.py, reconcile/utils/repo_owners.py, reconcile/utils/saasherder/saasherder.py, reconcile/utils/vcs.py
Use [raw file api](https://docs.gitlab.com/api/repository_files/#get-raw-file-from-repository) download single file. No major performance differences, only reduced response size and no need to do another base64 decode anymore. Also refactored GitHub api to use the same method to get file.
[APPSRE-12038](https://issues.redhat.com/browse/APPSRE-12038)
* Added a `get_raw_file` method in `GithubRepositoryApi` to handle file retrieval, including support for large files and directory checks. This method replaces direct calls to `get_contents` and improves error handling. (`reconcile/utils/github_api.py`) [[1]](diffhunk://#diff-ab174d601846566383961ef80e2598ffcddfd0b0d081b6408afee089dc13535dR1-R18) [[2]](diffhunk://#diff-ab174d601846566383961ef80e2598ffcddfd0b0d081b6408afee089dc13535dR77-L78)
* …
=> [vcs] use raw file api to get file

reconcile/change_owners/change_log_tracking.py, reconcile/test/change_owners/test_change_log_tracking.py
Support extract description from squashed merge request commit, use the same way to skip [default template for merge commits](https://gitlab.cee.redhat.com/help/user/project/merge_requests/commit_templates#default-template-for-merge-commits), pick the first meaningful line.
Also use commit's `committed_date` as merge/squash commit is created when merge request merge, so can be used as merged timestamp, save one request to gitlab per merge.
[APPSRE-12074](https://issues.redhat.com/browse/APPSRE-12074)
=> feat(change-log-tracking): support squash merge request

reconcile/utils/terraform_client.py
Reverts app-sre/qontract-reconcile#5009
rate limit is not during terraform plan step, it's during setup.
Track in [APPSRE-12114](https://issues.redhat.com/browse/APPSRE-12114)
=> Revert "increase terraform plan max_attempts"

reconcile/gql_definitions/common/rhcs_provider_settings.gql, reconcile/gql_definitions/common/rhcs_provider_settings.py, reconcile/gql_definitions/introspection.json, reconcile/openshift_rhcs_certs.py, reconcile/test/test_openshift_rhcs_certs.py, reconcile/utils/rhcsv2_certs.py
Update to create `kubernetes.io/tls`-compliant secrets and include `ca.crt` attribute. 
https://github.com/app-sre/qontract-schemas/pull/837
=> Update `openshift-rhcs-certs` output secrets 

reconcile/glitchtip_project_alerts/integration.py, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.gql, reconcile/gql_definitions/glitchtip_project_alerts/glitchtip_project.py, reconcile/gql_definitions/introspection.json, reconcile/gql_definitions/jira_permissions_validator/jira_boards_for_permissions_validator.gql, reconcile/gql_definitions/jira_permissions_validator/jira_boards_for_permissions_validator.py, reconcile/jira_permissions_validator.py, reconcile/test/fixtures/glitchtip/project_alerts.yml, reconcile/test/fixtures/jira_permissions_validator/boards.yml, reconcile/test/glitchtip/test_glitchtip_project_alerts.py, reconcile/test/test_jira_permissions_validator.py
Convert `jiraComponent` to a list of Jira components `jiraComponents`
Depends on https://github.com/app-sre/qontract-schemas/pull/835
Ticket: [APPSRE-12116](https://issues.redhat.com/browse/APPSRE-12116)
=> :recycle: migrate jiraComponent -> jiraComponents

reconcile/openshift_resources_base.py, reconcile/test/test_openshift_resources_base.py
https://issues.redhat.com/browse/APPSRE-12138
Add a change to the `fetch_current_state` function in `reconcile/openshift_resources_base.py` to skip processing resources managed by ArgoCD. This ensures that such resources are not modified unintentionally.
Key change:
Added a check for the `app.kubernetes.io/part-of` label in the resource's metadata. If the label's value is "argocd", the resource is skipped with an informational log message.
=> add a label check in fetch_current_state to not add argocd managed resources to the inventory

reconcile/openshift_rhcs_certs.py
Address memory leak caused by `oc_map`
=> Ensure oc_map cleanup occurs in openshift-rhcs-certs

reconcile/openshift_rhcs_certs.py, reconcile/test/test_openshift_rhcs_certs.py
Utilize `VaultClient`, which is a singleton. This addresses memory leak caused by continuously growing open sessions
=> [openshift-rhcs-certs] - utilize VaultClient singleton to address memory leak

reconcile/gitlab_housekeeping.py
Adjust the AppSRE bot for pending On-demand tests message.
Developers often get confused about how to define multiple on-demand jobs in a single comment.
Also, we want to inform that any update of the MR will reset the previous executions of the on-demand tests.
=> Adjust the AppSRE bot On-demand test message

reconcile/openshift_saas_deploy_trigger_base.py
The `target_ref` is the SHA ref of the target and is added as a label to the PipelineRun resource.
We're using pod labels & annotations to build a dashboard for saas deploy logs and a tenant requested the abillity to query by targetted refs, see https://redhat-internal.slack.com/archives/CCRND57FW/p1750433539235259
=> feat: Add target_ref to saas deploy trigger

reconcile/openshift_saas_deploy_trigger_base.py
Reverts #5041 & #5048 as these changes broke saas pipelines.
=> Revert saas deploy labeling changes

reconcile/utils/gitlab_api.py
We considered GitLab's "List all billable members of a group" API (/groups/:id/billable_members), but it didn't meet our needs for two main reasons:
Includes Project Users: It returns users from nested projects, not just direct group members. While we could filter these out, it's an extra step.
Excludes Inactive Users: Crucially, this endpoint doesn't include inactive users, which we need for comprehensive user management.
[Endpoint Info](https://docs.gitlab.com/api/members/#list-all-billable-members-of-a-group)
[APPSRE-8777](https://issues.redhat.com/browse/APPSRE-8777)
=> Change gitlab api _is_bot_username documentation

dockerfiles/Dockerfile, dockerfiles/structure-test.yaml
Note, that our base containers have the setgid flag enabled on terraform plugin dir. Adjusting the structure test accordingly here. This has no further effect on our integrations, since we do not change this dirs contents at runtime anyways.
Tested this locally by running terraform-resources with that image.
=> APPSRE-11020 Konflux base images

pyproject.toml, reconcile/test/test_jenkins_api.py, reconcile/test/test_saasherder.py, reconcile/utils/jenkins_api.py, reconcile/utils/saasherder/interfaces.py, reconcile/utils/saasherder/models.py, reconcile/utils/saasherder/saasherder.py
Add types and explicit list of fields stored as state, avoid unexpected null pointer like https://github.com/app-sre/qontract-reconcile/pull/5057.
* Added a new `JobBuildState` `TypedDict` to represent the state of Jenkins builds, improving type safety and readability (`reconcile/utils/jenkins_api.py`).
* Refactored the `get_jobs_state` method to use helper methods `_get_commit_sha_from_build` and `_build_job_build_state`, simplifying the logic and improving maintainability (`reconcile/utils/jenkins_api.py`).
* Added type annotations to all methods in `JenkinsApi`, ensuring stricter type checking and better documentation (`reconcile/utils/jenkins_api.py`). [[1]](diffhunk://#diff-ef3e0025228a0d9395553d563aae4769227f0ec0e38ace08ca42334c643ac280L46-R64) …
=> [saasherder] add types to all TriggerSpec

.tekton/qontract-reconcile-master-pull-request.yaml, .tekton/qontract-reconcile-master-push.yaml, dockerfiles/Dockerfile.konflux
We introduce qr unittests for konflux build pipeline.
We introduce a new dockerfile, as we make changes to the targets and their deps. For now we dont want to affect ci.ext builds with those changes. Long-term, we will move completely to the new Dockerfile.
**dockerfile target chain**
on master push
```
builder -> prod-pre-test-image -> test-image -> prod-image -> pypi -> prod-image-post-pypi-push
```
on PR
```
builder -> prod-pre-test-image -> test-image -> prod-image
```
Note, that the pypi push is still in TODO. We are implementing it in a follow up PR (when we obsolete ci.ext builds). This PR introduces the general pipeline stucture
=> APPSRE-11020 konflux pipeline tests

reconcile/aus/base.py, reconcile/aus/models.py, reconcile/test/ocm/aus/fixtures.py, reconcile/test/ocm/aus/test_expose_metrics.py, reconcile/utils/ocm/upgrades.py
Ensure metrics `aus_cluster_version_remaining_soak_days` still include current cluster version before all node pools upgraded to match cluster version, so we can view the schedule and progress in grafana, and long running upgrade alerts can trigger.
* Replaced manual dictionary manipulation with the `|` operator to merge dictionaries when constructing `ControlPlaneUpgradePolicy`, `NodePoolUpgradePolicy`, and `ClusterUpgradePolicy` objects in `reconcile/aus/base.py`. This improves readability and reduces repetitive code.
* Introduced a `TypedDict` class `UpgradePolicy` to define the structure of upgrade policies and refactored utility methods (`get_upgrade_policies`, `get_control_plane_upgrade_policies`, and `get_node_pool_upgrade_policies`) to use this type, simplifying the logic and …
=> [AUS] include current cluster version in metrics when node pool upgrade pending

pyproject.toml, reconcile/cli.py, reconcile/mr_client_gateway.py, reconcile/ocm_additional_routers.py, reconcile/ocm_addons.py, reconcile/ocm_aws_infrastructure_access.py, reconcile/ocm_clusters.py, reconcile/ocm_external_configuration_labels.py, reconcile/ocm_groups.py, reconcile/ocm_machine_pools.py, reconcile/openshift_groups.py, reconcile/test/test_ocm_additional_routers.py, reconcile/test/test_ocm_clusters.py, reconcile/test/test_ocm_clusters_manifest_updates.py, reconcile/test/test_ocm_machine_pools.py
- **:label: mr_client_gateway: type hints**
- **:label: ocm_additional_routers: type hints**
- **:label: ocm_addons: type hints**
- **:label: ocm_aws_infrastructure_access: type hints**
- **:label: ocm_clusters: type hints**
- **:label: ocm_external_configuration_labels: type hints**
- **:label: test_ocm_clusters_manifest_updates: type hints**
- **:label: ocm_groups: type hints and refactor openshift_groups**
- **:label: ocm_machine_pools: type hints**
Depends on: https://github.com/app-sre/qontract-reconcile/pull/5094
=> more type hints

reconcile/aws_account_manager/integration.py, reconcile/cli.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_account.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_iam.py, reconcile/utils/aws_api_typed/account.py, reconcile/utils/aws_api_typed/iam.py
We want to onboard and manage AWS accounts created by IT. These accounts have restrictions on changing the alias and the security contact information. The plan is to ignore all AWS API errors as long as the app-interface settings match those in the account; otherwise, throw an exception as usual.
Ticket: [APPSRE-12236](https://issues.redhat.com/browse/APPSRE-12236)
=> [aws-account-manager] support IT managed accounts

grafana-dashboards/grafana-dashboard-terraform-repo.yaml
Fixes some queries in the Terraform Repo dashboard that don't work now since task names were updated, ref: [APPSRE-11687](https://issues.redhat.com/browse/APPSRE-11687)
A lot of the diff is also because Grafana was upgraded recently.
=> Update terraform-repo dashboard queries to reflect pipeline changes

reconcile/templates/rosa-classic-cluster-creation.sh.j2, reconcile/templates/rosa-hcp-cluster-creation.sh.j2, reconcile/test/fixtures/rosa/rosa_hcp_script_result_private.sh, tools/qontract_cli.py
After changes in rosa cli https://issues.redhat.com/browse/OCM-15992, create private HCP cluster with all private subnets without `--default-ingress-private` will throw error
```text
ERR: The number of public subnets for a public hosted cluster should be at least one
```
we need both `--private` and `--default-ingress-private` to use full private subnets.
[APPSRE-12219](https://issues.redhat.com/browse/APPSRE-12219)
=> feat(ocm-clusters): set default-ingress-private for private HCP cluster

reconcile/gql_definitions/status_board/status_board.gql, reconcile/gql_definitions/status_board/status_board.py, reconcile/status_board.py, reconcile/test/test_status_board.py, reconcile/test/test_typed_queries/test_status_board.py, reconcile/typed_queries/status_board.py, reconcile/utils/ocm/status_board.py, tools/qontract_cli.py
Reverts app-sre/qontract-reconcile#5064
error
```text
File "/work/reconcile/cli.py", line 584, in run_class_integration
File "/work/reconcile/utils/runtime/runner.py", line 156, in run_integration_cfg
File "/work/reconcile/utils/runtime/runner.py", line 165, in _integration_wet_run
File "/work/reconcile/status_board.py", line 589, in run
self.apply_diff(dry_run, ocm_api, diff)
File "/work/reconcile/status_board.py", line 562, in apply_diff
d.act(dry_run, ocm_api)
File "/work/reconcile/status_board.py", line 251, in act
self.status_board_object.update(ocm)
File "/work/reconcile/status_board.py", line 144, in update
update_application(ocm, self.id, spec)
File …
```
=> Revert "RHCLOUD-39268 status-board-exporter add saas-files to metadata"

reconcile/rhidp/common.py, reconcile/test/ocm/fixtures.py, reconcile/test/rhidp/test_common.py, reconcile/utils/ocm/base.py
If a ROSA cluster has external authentication enabled, we can't list the identity providers:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.openshift.com/api/clusters_mgmt/v1/clusters/XXX/identity_providers?size=100
```
```
$ ocm get /api/clusters_mgmt/v1/clusters/XXXX/identity_providers
{
"kind":"Error",
"id":"400",
"href":"/api/clusters_mgmt/v1/errors/400",
"code":"CLUSTERS-MGMT-400",
"reason":"Listing identity providers is not supported for clusters with external authentication configured",
"operation_id":"270dba7f-8b96-49fb-8a74-dac923dd9c36",
"timestamp":"2025-07-31T07:04:32.191403696Z"
}
```
This PR filters out all clusters with an enabled external authentication.
=> :bug: rhidp: ignore clusters with enabled external auth

reconcile/utils/terrascript_aws_client.py
The trailing comma was causing the value to be a tuple instead of a dict.
=> Fix: Enable VPC and Subnets tagging in the VPC management

.tekton/qontract-reconcile-master-push.yaml, reconcile/test/utils/test_mr.py, reconcile/utils/mr/base.py, reconcile/utils/mr/promote_qontract.py
Using konflux for SQS auto MRs.
Note, that we currently cannot run after the RPA. I.e., the SQS message will be sent before the RPA finished publishing the prod image. We trigger the SQS message as late as possible in the build pipeline, after all checks have passed. I.e., likely auto-bump MR will fail initially, but should work shortly after with a `/retest`. Note, that we have no guarantee that the RPA passed - so we cannot be sure at that point that we will actually receive a valid image. However, at least we get the MR created and pinged on it - and most of the time that should work out just fine.
Note, that we do not have author-email any longer. We now have the author id.
We could also add a ~30s timeout or some wait-for-image mechanics before opening the MR. However, I'd leave that …
=> APPSRE-12383 konflux sqs message

reconcile/utils/ocm/base.py
Fix an `ocm-oidc-idp` bug:
```
pydantic.error_wrappers.ValidationError: 1 validation error for OCMOIdentityProviderOidc
open_id -> claims -> name
field required (type=value_error.missing)
```
Some dev SSO issuers don't have the `name` claim!
Ticket: [ASIC-666](https://issues.redhat.com/browse/ASIC-666)
=> ocm: default openid name claim

tools/qontract_cli.py
In some cases, triggered_alerts can be 0 if only resolved_alerts messages are present.
=> fix ZeroDivisionError

reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.gql, reconcile/gql_definitions/terraform_resources/terraform_resources_namespaces.py, reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py, reconcile/test/utils/test_terrascript_aws_client.py, reconcile/utils/terrascript_aws_client.py
Support proper tagging for all `terraform-resources` managed external resources.
The default tags are configured in the `external-resource-settings` and custom tags can be applied via `namespace.external_resources.tags`.
Ticket: [APPSRE-12424](https://issues.redhat.com/browse/APPSRE-12424)
=> terraform-resources: external resources tags

reconcile/external_resources/model.py, reconcile/test/external_resources/test_er_models.py
Automatically delete all ERv2-managed resources when a namespace is marked for deletion. This enables the deletion of a namespace, including all managed resources, in one MR.
Bugfix: Additionally, external resources in namespaces with `managedExternalResources: false` must be ignored!
Ticket: [APPSRE-11552](https://issues.redhat.com/browse/APPSRE-11552)
=> external-resources: handle namespace.delete flag

reconcile/database_access_manager.py, reconcile/test/test_database_access_manager.py
Use `external_resource.provisioner.name/resource.identifier/db_access.name` as state key and vault path to ensure one database instance secrets won't overwrite another one.
This integration is only responsible to put secrets to vault, remove the feature to write secret to cluster namespace, as run job once per change won't cover cluster/namespace migration, lead to secrets missing in new cluster/namespace. Sync secrets from vault to cluster can be done by other integrations such as openshift resources vault secret.
**Resource handling and code simplification:**
* Removed the `DBAMResource` class and changed all resource management logic to use plain `OpenshiftResource` objects, simplifying resource creation and deletion throughout the codebase. …
=> fix(database-access-manager): unique state key and vault path

reconcile/external_resources/factories.py, reconcile/external_resources/manager.py, reconcile/test/external_resources/conftest.py, reconcile/test/external_resources/test_aws_external_resource_factory.py
Merge `default_tags` from settings and spec `tags` as final `tags` to external resource module. So `tags` means the tags set on all resources created by module, avoid confusing merge tags logic in each module.
**Tag handling and type consistency:**
* Changed the type of `default_tags` from `Mapping[str, str]` to `dict[str, str]` in the constructor of `AWSExternalResourceFactory` to ensure stricter type enforcement and compatibility with dictionary operations.
* Updated the merging logic for tags in `create_external_resource` to use dictionary union (`|`), combining `default_tags` and resource-specific tags into a single dictionary, removing the previous nested structure.
* Applied a `cast` to `settings.default_tags` in the manager setup to guarantee it is treated as a dictionary, matching …
=> feat(erv2): merge default tags into tags

pyproject.toml, reconcile/cli.py, reconcile/gql_definitions/terraform_init/aws_accounts.gql, reconcile/gql_definitions/terraform_init/aws_accounts.py, reconcile/terraform_init/integration.py, reconcile/test/fixtures/terraform_init/accounts.yml, reconcile/test/fixtures/terraform_init/settings.yml, reconcile/test/terraform_init/conftest.py, reconcile/test/terraform_init/test_terraform_init_integration.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_api.py, reconcile/test/utils/aws_api_typed/test_aws_api_typed_cloudformation.py, reconcile/utils/aws_api_typed/api.py, reconcile/utils/aws_api_typed/cloudformation.py, uv.lock
The initial s3 bucket used for terraform state was created by calling s3 API once directly in `terraform-init` on AWS account setup stage. This change moves the bootstrap of terraform env (s3 bucket) in CloudFormation. Now we can apply tags from external resource settings and use best practices for [s3 backend](https://developer.hashicorp.com/terraform/language/backend/s3), like enable versioning and use lifecycle to cleanup non current versions. 
To handle existing S3 buckets, we need a minimal template to import first, example
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for Terraform state
Parameters:
BucketName:
Type: String
Description: Name for the bucket
Resources:
TerraformStateBucket:
Type: AWS::S3::Bucket
DeletionPolicy: RetainExceptOnCreate …
```
=> [terraform-init] manage terraform state s3 bucket and tags via cloudformation
