reconcile/aggregated_list.py, reconcile/openshift_rolebinding.py
When integrations run, they may raise exceptions. If they do, the
reconcile tool crashes. This commit ensures that actions are run in a
try/except block and logs the error properly.
=> Capture action exceptions

reconcile/cli.py, reconcile/openshift_resources.py, utils/openshift_resource.py
The previous parallelism was running only in the `fetch_desired_state` function, and was running in parallel per namespace.
The current state runs both `fetch_current_state` and `fetch_desired_state` in parallel, for all resources in parallel (from all clusters, from all namespaces).
This improves the execution time to be well under a minute!
=> improve parallelism in openshift-resource

reconcile/openshift_resources.py, reconcile/test/test_openshift_resource.py, utils/openshift_resource.py
Currently, if a manual change is done on an object in the cluster, the sha256sum will not change, and the integration will not detect that change. The current result is that manual changes persist through a run of the integration.
The expected result is that manual changes are detected and reconciled back to their previous state.
This PR makes it so that the sha256sum is calculated even for existing objects which have the sha256sum annotation, which will detect manual changes.
=> detect manual changes

reconcile/openshift_resources.py, reconcile/test/test_openshift_resource.py, utils/openshift_resource.py
This PR makes the integration work correctly with ServiceMonitors and PrometheusRules, which have the additional metadata field `generation` - which we now pop during canonicalize.
=> Reconcile prometheus

utils/raw_github_api.py
This cleans up the exception messages such that
1) Headers are not printed anymore (would expose Authorization token)
2) request URL is not printed anymore - it is already included in Requests exception messages
It would also be possible to sanitize the headers before printing them but this seemed a bit pointless as we only have 2 headers: Authorization and Accept which don't need to be shown on exceptions really.
=> Clean up github api exception messages

utils/terrascript_client.py
added the lifecycle section to the login profile:
https://www.terraform.io/docs/providers/aws/r/iam_user_login_profile.html#import
this will allow us to import existing users without resetting their password or recreating them.
=> import existing users fix

reconcile/terraform_users.py, utils/terrascript_client.py
This is to avoid cases such as:
```
aws_iam_user_group_membership.username-groupname: NoSuchEntity: The group with name groupname cannot be found.
```
This is a result of a race condition between the group creation and the group membership creation.
This is a quick fix, and a refactor will probably be required as we move forward.
=> add group dependency to group membership

utils/openshift_api.py
removing the final `else`, since that will happen many times (user names will not match, which is valid).
adding `userName` to remove the service account from the userNames list properly.
=> Rolebinding fix

utils/openshift_resource.py
If we always remove `status` then we don't need to manage specifically some CRDs, like `HiveConfig`. I've made sure there are no resources with `status` field in app-interface.
=> remove status

.dockerignore, .gitignore, reconcile/aws_garbage_collector.py, reconcile/cli.py, reconcile/terraform_resources.py, reconcile/terraform_users.py, utils/aws_api.py, utils/terraform_client.py
this PR does:
* `terraform-uesrs` and `terraform-resources` will output a file with users who are to be deleted.
* `aws-garbage-collector` will pick up those outputs (if running in dry_run only) and act as if these users do not exist.
the purpose is to have a clear view of what resources are going to be deleted when removing a user. instead of waiting for the next run and possibly losing needed resources.
this means that the `aws-gc` integration should run after both terraform integrations are complete.
=> link terraform integrations to aws-gc

reconcile/openshift_resources.py
Currently if a vault secret and/or secret version is not found, the integration will show the following exception and fail the integration
```
File "/usr/bin/qontract-reconcile", line 11, in <module>
load_entry_point('reconcile==0.1.0', 'console_scripts', 'qontract-reconcile')()
File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 1137, in invoke
File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 956, …
```
=> Catch vault secrets not found and raise useful exception

reconcile/terraform_resources.py, utils/terraform_client.py, utils/terrascript_client.py
this PR adds the ability to define `output_resource_name` to explicitly define what will be the name of the generated OpenShift resource (Secret in this case).
this will add the ability to define the same output resource name in different namespaces, allowing for simpler templating.
=> [terraform-resources] introduce ouput_resource_name field

reconcile/terraform_resources.py, utils/terrascript_client.py
these variables are moved out of vault and into app-interface:
* db_subnet_group_name
* vpc_security_group_ids
=> [terraform-resources] take subnet and security group from app-interface

README.md, reconcile/cli.py, reconcile/slack_usergroups.py, setup.py, utils/slack_api.py
* reconciles channels for user groups
* reconciles users for user groups
* create user groups/channels/users
* add/remove users from channels
by using the a user group, members will be added automatically to newly added channels, so the order will be first to update channels and only then to update users.
=> [slack-usergroups] introduce new integration

reconcile/slack_usergroups.py, setup.py, utils/pagerduty_api.py
this PR adds the ability to link a slack user group to a pagerduty schedule.
it is still possible to use the role + permission, so if anyone wants to always be in a group regardless of pagerduty, it is possible.
=> [slack-usergroups] add support for PagerDuty as additional source of truth

reconcile/openshift_resources.py, reconcile/terraform_resources.py, reconcile/terraform_users.py, utils/terraform_client.py, utils/terrascript_client.py
when the terraform-resources integration attempts to create a resource, it constructs the terraform configuration according to the definitions in app-interface. one of the configurations is the desired password for RDS instances.
since the terraform-resources integration generates secrets in openshift, the integration relied on those secrets to obtain the current password from the output openshift secret, so that the password of the RDS instance will not be changed.
this PR changes the behavior to obtain the password from the last applied terraform configuration using `terraform output`. in case the secrets are deleted from openshift, the integration will recover in the next run without any changes to existing infrastructure.
important to note that in case a matching output is not found …
=> [terraform-resources] do not depend solely on openshift secret

README.md, reconcile/cli.py, reconcile/gitlab_permissions.py, reconcile/ldap_users.py, utils/gitlab_api.py
for all GitLab repositories in app-interface:
* verifies that the user who's token is used has Maintainer access level
* adds all users from the `app-sre` gitlab group to all gitlab `codeComponents`
i chose to add members one by one and not add the group as this group is not selectable in the scope outside `service` and we may have repos outside it in the future.
=> [gitlab-permissions] introduce new integration

reconcile/openshift_namespaces.py, reconcile/openshift_resources.py, utils/oc.py
in some clusters if the namespace does not exist we will get a `Forbidden` message. this PR adds a check if the namespace exists.
if it doesn't, the `openshift-resources` integration will not query for existing resources - as there aren't any, and instead will return an empty list `[]`.
this change will allow the `openshift-resources` integration to run smoothly even if the namespace does not exist.
when this integration is not running in dry-run mode, it depends on the namespace existing.
this is a valid assumption, as:
1. the `openshift-resources` is running [after](https://gitlab.cee.redhat.com/service/app-interface/blob/master/build_deploy.sh#L165) the `openshift-namespaces` is running.
2. the `openshift-resources` get the context for the resources from the `namespace` file, which …
=> [openshift-resources] do not get resources if namespace does not exist

reconcile/terraform_resources.py, reconcile/terraform_users.py, terrascript/__init__.py, utils/terrascript_client.py
the `ts.validate()` function in terrascript was calling `terraform init` for no reason
=> [terraform-*] terraform validate without init

reconcile/slack_usergroups.py, utils/slack_api.py
this PR reduces the required fields in a user file:
* if `pagerduty_name` == `name` - `pagerduty_name` is not required
* if `slack_username` == `redhat_username` - `slack_username` is not required
=> [slack-usergroups] reduce required fields

reconcile/cli.py, reconcile/gitlab_housekeeping.py, utils/gitlab_api.py
iterates over housekeeping and adds `stale` label to stale issues (no activity over 30d) + adds a comment.
after 'stale' is added and 30d more passed - the integration closes the issue.
if after adding 'stale' someone added a note of '/stale cancel' - the integration will remove the label.
=> [gitlab-housekeeping] introduce new integration

README.md, reconcile/cli.py, reconcile/github_users.py, utils/smtp_client.py
for each user in app-interface, the integration checks that "Red Hat" is present in the user's GitHub profile under the Company field. if this is false, the integration will delete the user (submit a MR) file from app-interface.
to actually perform deletions - use the `--enable-deletion` flag.
to send mail notifications to users - use the `--send-mails` flag (overrides `--enable-deletion`).
* both these flags only work if `dry-run` is false.
=> [github-users] introduce new integration

reconcile/cli.py, reconcile/jenkins_job_builder.py, reconcile/jenkins_plugins.py, setup.py, utils/jjb_client.py
this integration is running jenkins-jobs to apply job configurations to jenkins.
when this integration is working in dry-run mode, it is executing `jenkins-jobs test`.
when it is not in dry run mode, it is executing `jenkins-jobs update`.
to be able to show diffs between the current state and the desired state, this integration needs to be executed twice:
1. execute with a config file pointing to prod (current state) and add the `--no-compare` flag, to indicate that this should only collect data
2. execute with a config file pointing to a local server (in a PR) (desired state). this run will fetch the desired state and compare it to the current state.
1 + 2 are not required when running this integration in a non dry-run mode, but only a single execution.
the ability to run integrations …
=> [jenkins-job-builder] introduce new integration

utils/jjb_client.py
this PR prevents a change to the logging of OTHER integrations.
=> [jenkins-job-builder] import on execute

reconcile/cli.py, reconcile/jenkins_job_builder.py, reconcile/jenkins_webhooks.py, utils/gitlab_api.py, utils/jjb_client.py
gets the list of jobs that exist in jjb, and for each job it checks if this job should be triggered (if at all) by a merge request or by a push, and adds that webhook to the project.
* currently only supports gitlab.
* delete webhooks (allowing users to add additional hooks manually)
=> [jenkins-webhooks] introduce new integration

reconcile/slack_usergroups.py
like we can have slack usergroup members be based on pagerduty (schedules and escalation policies) - this PR adds the ability to base the members on github OWNERS files!
=> [slack-usergroups] add github as source

utils/aws_api.py
adds garbage collection of rds db snapshots without an existing db instance
refs:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Client.describe_db_snapshots
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Client.delete_db_snapshots
=> [aws-gc] add rds snapshots

reconcile/github_org.py
1. migrate the github configuration from config.toml to app-interface (1st commit)
2. adds a github-org schema object, which may define a `managedTeams` field.
* if this field is defined - we only manage the specified teams
* if this field is not defined - we manage the entire org
=> [github-orgs] allow team membership in unmanaged orgs

e2e_tests/dedicated_admin_rolebindings.py, e2e_tests/test_base.py
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-periodic-job-e2e-tests/5/console
the `dedicated-admin-rolebindings` test is checking a namespace created and tested by the `create-namespace` test.
=> [e2e-tests] fix race condition between tests

dockerfiles/Dockerfile, utils/jjb_client.py
when using the python package, whenever the integration is run - ci-int jenkins prometheus metrics are missing for a short while, which causes our alerts to "flap".
until we decide (if we decide) to look into it - this solves it.
=> [jjb] use jenkins-jobs cli instead of package on update

reconcile/terraform_resources.py, utils/terrascript_client.py
This PR adds support for AWS ElastiCache (HA mode) to the terraform-resources integration, similarly to existing supported resources such as RDS and S3.
external refs:
https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html#redis-cluster-mode-enabled
https://aws.amazon.com/getting-started/tutorials/setting-up-a-redis-cluster-with-amazon-elasticache/
=> [terraform-resources] add support for ElastiCache

reconcile/openshift_resources.py, setup.py
This PR adds support for Jinja2 template processing on resource files prior to processing them.
I've tried to design the feature so that it is easy to add more kinds of (template) processing. A potential future candidate for this may be processing `jsonnet` templates to render OpenShift resources and then reconcile them
As part of the PR, I've also added a custom `vault` function in Jinja2 which allows retrieving secrets from vault
This can be useful to retrieve information from vault to apply on one or more resources
Example
```yaml
apiVersion: v1
kind: Deployment
metadata:
name: myapp
spec:
...
template:
spec:
containers:
- image: '{{ vault('some/vault/path', 'image', 1) }}'
...
```
=> Add jinja2 templating for resources

README.md, reconcile/cli.py, reconcile/openshift_users.py, utils/oc.py
for each cluster - get the list of users, compare with list of desired users (have any RoleBinding in openshift-rolebindings or members of any group in openshift-groups), and deletes users who are not found in the desired state.
this integration only deletes users with `github` identities.
this integration does not create users.
=> [openshift-users] introduce new integration

reconcile/github_org.py
this integration will delete empty teams in real time to avoid complexity for such an uncommon routine.
e.g. it will not let us know in the dry run.
=> [github] delete empty teams

reconcile/openshift_resources.py, utils/jinja2_ext.py
This also make the jinja2 template engine try kv and kv2 when looking up secrets (only kv2 was implemented before)
=> Add jinja2 extension for base64 encoding

reconcile/terraform_resources.py, utils/terrascript_client.py
This PR adds the ability to self-service service accounts in AWS.
An example use case would be a user required to export AWS metrics ([aws-resource-exporter](https://github.com/app-sre/aws-resource-exporter)).
This is what it would look like in a namespace file:
```yaml
terraformResources:
- provider: service-account
account: app-sre
identifier: aws-resource-exporter-production
policies:
- AmazonRDSReadOnlyAccess
output_resource_name: aws-resource-exporter
```
This would create a user in AWS with the specified policies, and would result in a Secret created in the namespace containing credentials.
=> [terraform-resources] introduce service-account

utils/jjb_client.py
This PR does:
- rename "common" to "defaults"
- add new type "base-templates"
=> [jenkins-job-builder] support consolidation

reconcile/github_org.py, reconcile/github_repo_invites.py, reconcile/openshift_resources.py, reconcile/openshift_resources_annotate.py, reconcile/openshift_rolebinding.py, reconcile/quay_membership.py, reconcile/quay_repos.py, utils/aws_api.py, utils/jenkins_api.py, utils/jjb_client.py, utils/jump_host.py, utils/pagerduty_api.py, utils/slack_api.py, utils/smtp_client.py, utils/terrascript_client.py, utils/vault_client.py
To review this PR, start from looking at the function changes in vault_client.py.
the `read` and `read_all` functions are now KV version agnostic.
=> [vault_client] consolidate all read functions to be KV engine agnostic

utils/slack_api.py
we have been seeing this more frequently lately:
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-build-master/1118/artifact/reports/reconcile_reports_fail/reconcile-slack-usergroups.txt
=> [slack-usergroups] add retry to get_usergroup

e2e_tests/create_namespace.py, e2e_tests/dedicated_admin_rolebindings.py, reconcile/openshift_groups.py, reconcile/openshift_namespaces.py, reconcile/openshift_resources.py, reconcile/openshift_rolebinding.py, reconcile/openshift_users.py, reconcile/terraform_resources.py, utils/defer.py
when initializing oc_map, temporary directories are created for jump host configurations.
this PR adds a cleanup of those directories.
covers https://jira.coreos.com/browse/APPSRE-605
=> [openshift-*] handle cleanup of oc_map (jump host)

reconcile/cli.py, reconcile/github_users.py, reconcile/gitlab_housekeeping.py, reconcile/gitlab_members.py, reconcile/gitlab_permissions.py, reconcile/jenkins_webhooks.py, reconcile/ldap_users.py, reconcile/queries.py, utils/gitlab_api.py
covers https://jira.coreos.com/browse/APPSRE-938
this PR does:
* removes the need for a `gitlab` section in the config file - it will be consumed through app-interface.
* updates integrations to consume token from app-interface
* updates gitlab api to get the instance query result instead of a server and a token
* adds a `queries.py` file for common queries (long needed)
* more then just a bit of a refactor to gitlab-members
Notes for the reviewer: i suggest to review this commit by commit.
=> [gitlab-*] move token out of config file and add it as a token in the gitlab instance file

reconcile/aws_garbage_collector.py, reconcile/aws_iam_keys.py, reconcile/queries.py, reconcile/terraform_resources.py, reconcile/terraform_users.py, utils/aws_api.py, utils/terrascript_client.py
we currently have this in the config file:
```
[terraform]
[terraform.aws1]
secrets_path = 'creds/terraform/aws1'
[terraform.aws2]
secrets_path = 'creds/terraform/aws2'
```
this PR makes this config redundant by moving it to app-interface aws account objects.
=> extract terraform/aws secrets from config

reconcile/openshift_resources.py, utils/threaded.py, utils/vault_client.py
This PR sorts the resources to fetch according to their type (`current` - oc get, or `desired` - graphql+vault queries).
since calls to clusters tend to take longer then to fetch resources from graphql and vault, we have a tail of `current` calls that make the integration be a bit slower. by sorting them and running them concurrently but in order (`chunksize=1`), we loose the tail.
that's the theory at least.
also disabled the `WARNING` level logs from vault_client, to hide these warnings: `Connection pool is full, discarding connection`, which means:
> a connection is dropped (because the pool is full); however, the same connection will be re-tried later on when connection pool becomes available
ref: https://stackoverflow.com/questions/53765366/urllib3-connectionpool-connection-pool-is-fu …
=> [openshift-resources] sort by type

reconcile/gitlab_housekeeping.py, setup.py
This PR adds a rebase of merge requests to housekeeping to keep all MRs rebased at all times.
It also changes the way `stale` items are calculated - changing it from update date of the item to the latest note added on the item (to ignore rebases).
=> [gitlab-housekeeping] add rebase of merge requests

reconcile/cli.py, reconcile/gitlab_housekeeping.py
This PR adds a `--rebase-limit` flag to gitlab-housekeeping.
this is to control how many MRs are being rebased.
=> [gitlab-housekeeping] limit rebases

reconcile/cli.py, setup.py, utils/openssl.py
Using the `openssl` binary and parsing the output to extract certificate info is error prone.
This PR changes this to use pyOpenSSL instead.
This fixes an issue where on my system running OpenSSL 1.1.1d the output format is different from version 1.0.2k in CentOS 7
OpenSSL 1.1.1d
```
subject=C = US, ST = North Carolina, L = Raleigh, O = "Red Hat, Inc.", OU = Developer Tools, CN = *.api.prod-preview.openshift.io
```
OpenSSL 1.0.2k
```
subject= /C=US/ST=North Carolina/L=Raleigh/O=Red Hat, Inc./OU=Developer Tools/CN=*.api.prod-preview.openshift.io
```
=> Switch openssl utils to pyOpenSSL

utils/oc.py
I was investigating why running the openshift-resources integration would sometimes takes multiples minutes (sometimes over 10 minutes) on my local machine
I believe I've isolated the problem to the oc client repeatedly doing lookups on the kubeconfig (the one we have on the jumphost has a few hundreds). This does not seem to happen when connecting directly (locally) however this may very well happen if the user has a large local kubeconfig.
The multiple looks are ampolified when we're querying for many resources, in my case (as seen in the examples below) the command was retrieving nearly 2000 objects
The following line appeared thousands of times when running with `loglevel=8` on a remote jumphost with a somawhat large kubeconfig
```
I1017 17:57:48.014903   22011 loader.go:359] Config …
```
=> Pass config option to oc command with /dev/null as value

utils/gpg.py
This PR broke build master:
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/1881
The reason is that a sub key was missing. This PR adds a check for that to avoid this in the future.
=> gpg check pub and sub keys exist

dockerfiles/Dockerfile.test, reconcile/aws_support_cases_sos.py, reconcile/cli.py, reconcile/queries.py, setup.py, tox.ini, utils/aws_api.py, utils/gitlab_api.py
This PR introduces a new integration called aws-support-cases-sos.
This integration iterates over support cases in AWS support center to find support cases reporting of leaked AWS access keys. For each found key, the integration will submit a PR to app-interface to remove that key from the account (will be handled by aws-iam-keys integration upon merge).
Future work will include searching the page where the leak was detected for leaked GitHub tokens, and if those exist - the PR to app-interface will be one that removes the user completely.
**NOTE** This PR removes python 3.4 from tests due to incompatibility with ruamel.yaml.
=> [aws-support-cases-sos] introduce new integration

reconcile/queries.py, reconcile/terraform_resources.py, utils/terrascript_client.py
defined in app-interface as follows:
```
terraformResources:
- provider: sqs
account: app-sre
identifier: app-interface-stage-sqs
defaults: /terraform/resources/sqs-1.yml
output_resource_name: app-interface-sqs
queues:
- app-interface-stage-pr-submitter
```
=> [terraform-resources] add support for sqs

reconcile/cli.py, reconcile/gitlab_pr_submitter.py, reconcile/pull_request_gateway.py, utils/sqs_gateway.py
this integration relays messages from the `pullRequestGateway` (currently only implements `sqs`) to gitlab.
this is a lightweight integration that reads messages from the gateway and submits PRs to app-interface.
this integration should be used when app-interface is unreachable from the location where the following integrations are running:
- github-users
- github-scanner
- aws-support-cases-sos
=> [github-pr-submitter] introduce new integration

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/pull_request_gateway.py, utils/aws_api.py, utils/sqs_gateway.py
we may be having trouble with the AWS credentials chain since we set environment variables.
remove usage of environment variables and infer aws account from queue url instead.
=> [sqs-gateway] use creds obtained from app-interface

utils/oc.py
This fixes a bug introduced by #287 where `List.extend(string)` appends individual characters from the string as array items resulting in unexpected behavior causing no current state to be found
```
['get', '-o', 'json', 'Project', u'a', u'p', u'p', u'-', u's', u'r', u'e', u'-', u'o', u'b', u's', u'e', u'r', u'v', u'a', u'b', u'i', u'l', u'i', u't', u'y', u'-', u's', u't', u'a', u'g', u'e']
```
The fix is to use `List.append `instead which result in the expected `cmd` to be produced
```
['get', 'Role', '-o', 'json', '-n', u'app-sre-observability-stage']
```
=> Fix cmd.extend in oc.py OC.get()

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
moving it to build master to control its flow with terraform-resources.
when terraform-resources is running on the cluster, we can move it back.
=> disable aws-iam-keys integration

reconcile/aws_iam_keys.py, reconcile/queries.py, utils/terrascript_client.py
this PR adds the ability to disable the following integrations from running for specific aws accounts:
- terraform-resources
- terraform-users
=> aws disable integrations

README.md, reconcile/cli.py, reconcile/pull_request_gateway.py, setup.py, tools/app_interface_reporter.py, utils/gitlab_api.py, utils/sqs_gateway.py
This tools generates reports for all the services defined in app-interface and
submits a PR to App-Interface to commit them in the repo (auto-merge).
The core functionality is:
- Get the list of apps from app-interface.
- Generate a report for each app.
- The reports currently contain a dummy content, which will be extended.
Additionally the following things were changed:
- Support for tools in project
- Extract some decorators from cli so they can be reused
- create_mr methods in gitlab_api now return the actual object
- pull request gateway code was cleaned up a bit
- a new create_mr method was added to the gitlab_api
- a generic create_commit function was created in gitlab_api
TODO:
- The foundations to run this via SQS have been written, but probably a few
changes will need to be …
=> [new-tool] app-interface-reporter

reconcile/openshift_rolebindings.py, reconcile/queries.py, setup.py, utils/oc.py
covers https://jira.coreos.com/browse/APPSRE-1201
this integration should use the same patterns as other openshift integrations.
additional benefits:
1. the rolebindings integration will also work for Kubernetes clusters and not only for OpenShift since it will no longer use the `oc policy` commands.
2. it allows us to manage RoleBindings in a non authoritative manner (manual RoleBindngs can live side by side with ones created by this integration).
3. RoleBindings are annotated with qontract-reconcile annotations like other resources.
4. we are no longer limited to manage a specific Role (view/edit/admin).
Note: in app-interface, `managedRoles` is now boolean instead of a list of Roles we manage.
=> [openshift-rolebindings] refactor to match common patterns

utils/config.py, utils/secret_reader.py
finalizes https://jira.coreos.com/browse/APPSRE-1102
to use a configuration file instead of Vault, the tokens need to be present in the config file in the same path as in Vault. for example, the slack-usergroups integration uses these secrets:
```
path: app-sre/creds/slack-app-sre-groups
field: token
path: app-sre/ci-int/pd_api_key
field: pd_api_key
```
this is how it would look like in a config file:
```
[app-sre]
[app-sre.creds]
[app-sre.creds.slack-app-sre-groups]
token = "REDACTED"
[app-sre.ci-int]
[app-sre.ci-int.pd_api_key]
pd_api_key = "REDACTED"
```
=> add config implementation for secret-reader

utils/openshift_resource.py
This is a temporary fix until we refactor `canonicalize` completely.
this is to fix the never reconciling RoleBindings on OSDv4:
```
INFO: ['apply', 'insights', 'approval', 'RoleBinding', 'username']
```
=> [openshift-rolebindings] fix reconcile for OSDv4

reconcile/openshift_base.py
We currently specify which resources types are allowed to be managed by `openshift-resources` in a section in the namespace file called `managedResourceTypes`. Any resource type that is specified in this section but does not have any desired resources causes the integration run time to increase.
This PR adds a warning message when resource types are not being used. Current output:
```
WARNING: [hive-integration/uhc-integration] unused resource type: ConfigMap. please remove it in a following PR.
WARNING: [app-sre/app-sre-observability-production] unused resource type: ServiceAccount. please remove it in a following PR.
WARNING: [app-sre/app-sre-observability-production] unused resource type: Role. please remove it in a following PR.
WARNING: [app-sre/app-sre-observability-production] …
```
=> [openshift-resources] add warnings for unused resource types

e2e_tests/default_project_labels.py
following https://redhat.service-now.com/surl.do?n=INC1053265
add a check that this label exist on all required namespaces.
=> [e2e/default project labels] add monitoring label

utils/terraform_client.py
not sure why how this worked until now, i'm guessing there was a version upgrade that i missed.
in any case:
https://github.com/beelit94/python-terraform/blob/develop/python_terraform/__init__.py#L112
=> fix terraform apply

utils/terraform_client.py
we are currently not handling the onboarding on AWS accounts very well.
at first run, the outputs are empty: https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-pr-check/4657/artifact/temp/reports/reconcile_reports_fail/reconcile-terraform-users.txt
this PR catches that error and handles it gracefully.
ref: https://github.com/beelit94/python-terraform/blob/develop/python_terraform/__init__.py#L336-L342
=> terraform add handle for empty output

utils/openshift_resource.py
covers https://jira.coreos.com/browse/APPSRE-1227
This PR adds a name validation for openshift resources.
If this starts getting out of hand we will need to use a 3rd party tool, as suggested on the issue.
This should be good enough for now.
chose not to include the `^` and `$` in the pattern to make the error message identical to the `oc` output.
```
$ cat test.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
name: Test
data:
key: value
$ oc apply -f test.yaml --dry-run --validate
configmap/Test created (dry run)
$ oc apply -f test.yaml 
The ConfigMap "Test" is invalid: metadata.name: Invalid value: "Test": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation …
```
=> add openshift resource name validation

utils/git_secrets.py
Original Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.0-py3.6.egg/utils/threaded.py", line 10, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.0-py3.6.egg/utils/defer.py", line 15, in func_wrapper
return func(*args, defer=defer, **kwargs)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.0-py3.6.egg/utils/retry.py", line 19, in f_retry
raise e
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.0-py3.6.egg/utils/retry.py", line 16, in f_retry
return f(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.0-py3.6.egg/utils/git_secrets.py", line 39, in scan_history
suspected_files = get_suspected_files(err)
File …
=> [github-scanner] fix reading error

reconcile/cli.py, reconcile/openshift_base.py, reconcile/openshift_limitranges.py
This PR introduces a new argument to `realize_data` - `take_over`.
If `take_over` is set to `True`, all existing un-managed resources (of the types managed by the running integration) will be taken over and removed if they do not exist in app-interface.
This makes an integration the sole owner of a resource type in a namespace.
=> [openshift-*] allow taking over resources

reconcile/test/test_github_org.py, reconcile/test/test_quay_membership.py, reconcile/test/test_quay_repos.py, utils/gql.py
covers https://jira.coreos.com/browse/APPSRE-1206
To be able to run integrations without concern that the data may be reloaded at run time, expose the graphql endpoint at a url that includes the sha256 sum of the current bundle.
when data is reloaded, the endpoint changes and running integrations will fail if they are still performing graphql queries. this is the expected result.
depends on https://github.com/app-sre/qontract-server/pull/63
=> graphql server endpoint with sha

reconcile/cli.py, reconcile/openshift_acme.py, reconcile/openshift_base.py, reconcile/openshift_groups.py, reconcile/openshift_limitranges.py, reconcile/openshift_namespaces.py, reconcile/openshift_network_policies.py, reconcile/openshift_resources.py, reconcile/openshift_rolebindings.py, reconcile/openshift_users.py, reconcile/queries.py, reconcile/terraform_resources.py, utils/oc.py, utils/terraform_client.py
This PR adds a new capability for OpenShift related integrations - running them on all resources (default), running only for internal clusters (`--internal`) or running only for external clusters (`--external`).
This new feature is required so we can run our integrations on a cluster without access to internal clusters and ignore any internal clusters, or to run only for internal clusters (integration should run internally as well).
Done as part of https://jira.coreos.com/browse/APPSRE-1206
Currently we can move all our OpenShift related integrations to our cluster, except for `openshift-resources` and `terraform-resources` which should ADDITIONALLY be running internally with the `--internal` flag.
app-interface PR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2137 …
=> Add internal/external/all option for OpenShift related integrations

reconcile/openshift_resources.py
an empty secret can be applied, but is currently not being reconciled
=> allow empty secret

utils/openshift_resource.py
this keeps the openshift-rolebindings integration sane.
=> revert remove of temporary reconcile assistance

dockerfiles/Dockerfile, dockerfiles/hack/run-integration.sh, helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
Instead of embedding the command in the container spec, we are now
calling a specific script that will use the environment variables to run
the integration.
Note that there is some logic borrowed from:
https://github.com/app-sre/qontract-reconcile/pull/383
meaning that that PR needs to be rebased
=> use script to run integration

reconcile/openshift_base.py, reconcile/openshift_resources.py, utils/oc.py
Covers https://jira.coreos.com/browse/APPSRE-1349
This PR adds support for management of resources in namespaces with limited permissions.
Example addition to namespace file:
```
managedResourceNames:
- resource: Secret
resourceNames:
- alertmanager-config
- alertmanager-main
```
=> [openshift-resources] allow to manage resources in a limited namespace

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
as each integration is running in its own pod, and we now have more than 1 container, its becoming a hassle to get logs from the integration container.
this will shorten things a bit:
```
oc logs -c int <pod>
```
also increases reqs/limits for openshift-namespaces
=> rename integration container from integration name to int

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/email_sender.py, reconcile/github_users.py, reconcile/queries.py, utils/ocm.py, utils/smtp_client.py, utils/state.py
This PR introduces a new integration that allows us to send emails through app-interface.
Matching app-interface PR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2531
The biggest challenge was: how do we only send each email only once.
The proposed solution: we use S3 as a simple state for app-interface.
This approach will allow us to implement new integrations that do not have a source of truth that we can fetch current state from. For example, this will allow running SQL queries only once (RDS self service).
=> [email-sender] introduce new integration

reconcile/email_sender.py, reconcile/queries.py, utils/gitlab_api.py
covers https://issues.redhat.com/browse/APPSRE-1176
depends on https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2543
When an AWS key leak is detected, a PR is created in app-interface to recycle that key.
This PR adds an email to that PR to notify account owners defined in app-interface.
This email will be picked up and sent by email-sender (#418).
Example of a PR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2542/diffs
=> add email notification when aws key leak is found

README.md, reconcile/openshift_acme.py, reconcile/openshift_limitranges.py, reconcile/openshift_rolebindings.py, reconcile/queries.py, requirements.txt, setup.py, tools/qontract_cli.py, utils/state.py
This PR adds a new tool called `qontract-cli`. As it grows on us, a `q` alias is suggested.
This cli tool is currently really good at getting information, but doesn't do anything else.
Update: the tool now has 2 subcommands -get and state.
Try it:
```
$ q get users
$ q get -o json cluster app-sre
$ q state ls
```
=> Introducing qontract-cli

utils/container.py
Apart from the small interface improvement, the main point of this PR is to allow the mirror to be specified togheter with a new quay repository in the app-interface.
When a new repository is specified, if a mirror is also there, currently the quay-mirror integration will crash in the MR CI for not being able to acquire the tags.
This patch fixes it by making sure that the _tags property will return an empty list when the image repository is not available, which also makes sense in terms of interface.
=> Improve container.Image interface

README.md, reconcile/cli.py, reconcile/queries.py, reconcile/service_dependencies.py
covers https://issues.redhat.com/browse/APPSRE-1232
This integration is validating that all services define their dependencies. It does it based on the used resources of that service.
It is currently only validating, but we can enhance it later to submit PRs when a dependency is missing. Definitely a future PR, if at all, as we want service owners to be mindful of their dependencies.
=> [service-dependencies] introduce validating integration

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_clusters.py, reconcile/queries.py, utils/ocm.py
This PR adds a new integration called ocm-clusters.
This integration will eventually provision and update clusters via OCM.
Currently it only validates that the cluster spec+network in app-interface matches the same info in OCM.
=> [ocm-clusters] introduce new integration

reconcile/email_sender.py, reconcile/queries.py, tools/app_interface_reporter.py, utils/gitlab_api.py
covers https://issues.redhat.com/browse/APPSRE-1081
This PR adds an email notification of App SRE monthly reports.
It creates an email to be picked up by email-sender (#418), which will be sent to `all-service-owners`.
Tthis PR also adds the `all-service-owners` alias implementation.
Everything in this PR is negotiable, as this is an implementation suggestion.
=> [app-interface-reporter] add email notification

utils/container.py
Sometimes the registry API sends an incomplete response, causing an
exception when parsing the JSON. Even Skopeo faces that issue:
```
$ skopeo inspect docker://docker.io/library/memcached:1.4.24
FATAL[0004] Error parsing image name "docker://docker.io/library/memcached:1.4.24": unexpected EOF
```
Trying again:
```
$ skopeo inspect docker://docker.io/library/memcached:1.4.24
{
"Name": "docker.io/library/memcached",
"Tag": "1.4.24",
"Digest": "sha256:a23496a073d3fef620815f8a9224afb6162b7c7213e4faaf05a051c74f157605",
"RepoTags": [
"1-alpine",
"1.4-alpine",
"1.4.21",
"1.4.22",
...
```
This patch adds to `get_manifest()` the `retry()` decorator, which does not solve the
issue in the registry, but makes the client more resilient.
=> Adding retry to get_manifest()

reconcile/github_org.py
newly created team with members who have not yet accepted the org invitation are deleted and re-created.
=> [github] disable team deletion

reconcile/cli.py
This message is displayed when the data on the server is changed.
This happens after every merge to app-interface.
This is fine.
=> This is fine

utils/container.py
Besides some minor fixes, this MR is adding to the `utils.container.Image()` support for additional registries:
- **registry.access.redhat.com**, which has a different Www-Authenticate format (when compared to quay.io and docker.io).
- **registry.redhat.io**, which requires user authentication.
This works now:
```
>>> from utils.container import Image
>>> i = Image('registry.access.redhat.com/rhel7/net-snmp') 
>>> bool(i)
True
```
This also works:
```
>>> from utils.container import Image
>>> i = Image('registry.redhat.io/rhel8/redis-5', username='***', password='***')          
>>> list(i)                                            
['1-9', '1-52', '1-37', '1-25', '1-35', '1', '1-11', '1-13.1561735341', '1-13', '1-45', 'latest']
```
=> Adding support for more registries

reconcile/sentry_config.py
This PR moves the check for teams in a role to happen before collecting users and bots information.
We currently have 288 users in app-interface.
The total number of users that came up for querying github is:
before this change: 613
after this change: 45
We already have email caching in the integration, so -
The total number of UNIQUE users that came up for querying github is:
before this change: 288
after this change: 45
=> [sentry-config] reduce number of calls to github

reconcile/openshift_base.py, reconcile/openshift_resources.py
Covers https://issues.redhat.com/browse/APPSRE-1458
There are cases where there are multiple resource types with the same name but with a different apiVersion. For example - `project.openshift.io` and `project.config.openshift.io`.
This PR adds support for a `managedResourceTypeOverrides` section to specify how to query for such resources.
Matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2887
=> [openshift-resources] add support for resource type override

reconcile/jenkins_job_builder.py, utils/jjb_client.py
not all jenkins instances were created equal, and we need to not delete job on some of them.
=> [jenkins-job-builder] add deleteMethod

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/openshift_serviceaccount_tokens.py, reconcile/queries.py, utils/oc.py
covers https://issues.redhat.com/browse/APPSRE-929
depends on https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3006
this PR adds a new integration that takes ServiceAccount tokens from a namespace and places them in a Secret in a different namespace (could be a different cluster as well) to be consumed by other applications.
the output can also go to Vault to be consumed in templating.
=> [openshift-serviceaccount-tokens] introduce new integration

reconcile/openshift_base.py, reconcile/openshift_resources.py, utils/oc.py
with this PR, when pods are about to be recycled due to a change in a Secret, it will be printed even in dry-run mode.
=> [openshift] oc recycle pods dry-run

reconcile/openshift_base.py, reconcile/openshift_resources.py, reconcile/sql_query.py, reconcile/terraform_resources.py, utils/oc.py, utils/terraform_client.py
This PR adds an ability to specify an annotation on a Secret - `qontract.recycle`.
When this annotation is set to `true`, pods which use this Secret will be recycled.
The annotation will be added to all terraform-resources Secrets to keep recycling pods as before, when `recycle_pods` was passed as `True`.
In order to avoid recycling all pods just by adding this annotation, the recycle_pods call is currently commented out and will be uncommented after all Secrets are updated.
The annotation can be defined on app-interface resources to specify that pods using that Secret should be recycled.
=> Secret recycle annotation

reconcile/sql_query.py
The inversed quotes are fixing an issue with single quotes in selects.
=> Fix quotes

reconcile/openshift_base.py, utils/openshift_resource.py
based on a suggestion by the glorious @jmelis:
https://gist.github.com/jmelis/594ca4fc7566159c4efbce8e80c4bc3f
compare resources only by the desired resource and the attributes it has. in case default values are added by k8s, they are ignored in this comparison.
=> [openshift-*] compare resources recursively by desired item

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
Now that we have the github-mirror, it's safe to re-enable this
integration.
This reverts d735809233f70e4a3343da2e130db4aae25babc0
=> Re-enable github-users integration

reconcile/openshift_resources.py, reconcile/terraform_resources.py, utils/oc.py
Reconciling openshift-resources breaks if one of the cluster's token has expired.
Also he `-config` flag for OC client has been deprecated and `kubeconfig` is the new flag to use.
=> Catch exception in populate_oc_resources

reconcile/cli.py, reconcile/openshift_resources.py
openshift_resources will now log error and let the pipeline continue. This PR also modified the log message format. Log messages will now include timestamp, filename, function name, and line number.
=> Added error handling for openshift_resources

utils/container.py
get_manifest() raises its own custom exception now. Let's
adapt to that.
=> Fixing bool() exception handler

reconcile/openshift_base.py, reconcile/queries.py
currently `managedResourceNames` is only taken into consideration in openshift-resources.
this change adds it to all openshift integrations.
=> [openshift-*] consider managedResourceNames in all integrations

utils/saasherder.py, utils/skopeo.py
Part of https://issues.redhat.com/browse/APPSRE-1276
This PR adds image existence check in saas-deploy before deploying them.
Currently very raw, but as we move forward, a failure in this check for one image should not fail the process and should allow the deployment of other resources.
=> [openshift-saas-deploy] check images

tox.ini
No need for separate envs. This will speed up the CI.
=> Unifying tox envs

reconcile/openshift_saas_deploy.py, utils/saasherder.py
- check image per resource and skip applying if image does not exist
- deleting resources is enabled only if no errors had occurred
- removed default `None` values from SaasHerder init method
=> [openshift-saas-deploy] improvements #1

README.md, reconcile/cli.py, reconcile/gitlab_housekeeping.py, reconcile/owner_approvals.py, reconcile/queries.py, utils/gitlab_api.py
part of https://issues.redhat.com/browse/APPSRE-707
This PR introduces a new integrations called owner-approvals.
This integration will assist in allowing external users (non App SRE) to approve changes to their apps.
The start will be only for saas files.
The flow is:
1. run owner-approvals with `--no-compare` to only collect approvers from the production graphql endpoint (prevent privilege escalation).
2. run owner-approvals again, to determine if this change is approved by an owner.
app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3309
=> [owner-approvals] introduce new integration

reconcile/openshift_acme.py, reconcile/queries.py, utils/openshift_acme.py
This reverts PR (#536) as openshift-acme needs to be able to delete any
secret in the namespace it's running.
See https://issues.redhat.com/browse/APPSRE-1435
cc @maorfr 
This reverts commit f916267f60fe652289cf8bcbceae0e9c192fe32b.
=> Revert support for named secrets in openshift-acme

reconcile/openshift_clusterrolebindings.py, utils/openshift_resource.py
OpenShift v3 vs v4 have different Kubernetes versions, so the apiVersion of ClusterRolebindings is not inter compatible
=> Fix openshift-clusterrolebindings broken across v3/v4

README.md, reconcile/cli.py, reconcile/gitlab_owners.py, reconcile/queries.py, utils/gitlab_api.py
An `OWNERS` file in any directory will allow users listed in that file to comment a merge request with a `/lgtm` and have that merge request labelled with `approved`, that will be later used by the housekeeping periodic integration to automerge the merge request.
- This is not meant to be used by the App-Interface.
- This first use case we have for this integration is the managed-tenants project.
Example of this integration in action:
[https://gitlab.cee.redhat.com/asegundo/my-awesome-project/merge_requests/6](https://gitlab.cee.redhat.com/asegundo/my-awesome-project/merge_requests/6)
=> New integration: gitlab-owners

reconcile/queries.py
this causes some failures.
let's restore this when the schema is updated.
cc @apahim
=> remove gitlabOwners until schema is updated

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_aws_infrastructure_access.py, reconcile/queries.py, utils/ocm.py
Covers https://issues.redhat.com/browse/APPSRE-1588
This PR adds a new integration that grants access to AWS infrastructure behind a cluster in OCM.
It uses existing resources of type AWS groups to get users eligible for that access.
matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/3501
ref: https://docs.openshift.com/dedicated/4/getting_started/cloud_infrastructure_access/dedicated-aws-access.html
=> [ocm-aws-infrastructure-access] introduce new integration

dockerfiles/Dockerfile, helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/openshift_acme.py, reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_groups.py, reconcile/openshift_limitranges.py, reconcile/openshift_namespaces.py, reconcile/openshift_network_policies.py, reconcile/openshift_resources.py, reconcile/openshift_rolebindings.py, reconcile/openshift_serviceaccount_tokens.py, reconcile/openshift_users.py, reconcile/terraform_resources.py, utils/oc.py
The OpenShift integrations are using a jump host to be able to reach private clusters.
In case the integrations are running in an environment with access to those clusters (by VPC peering for example), using the jump host is not required.
This PR adds a `--use-jump-host/--no-use-jump-host` option (defaults to True - use a jump host).
Since our jump host implementation relies on SSH, and to use SSH in a container in OpenShift a valid user must exist, this PR removes the need to have such user(s), hence the Dockerfile change.
This just may work!
=> Add option to run OpenShift related integrations without using a jump host

utils/gpg.py
no-options did not work as expected and led to a new error:
```
gpg: keyblock resource `//.gnupg/secring.gpg': No such file or directory
gpg: keyblock resource `//.gnupg/pubring.gpg': No such file or directory
```
replacing with usage of a temp dir as home dir.
=> gpg replace no-options with temp homedir

reconcile/queries.py, tools/qontract_cli.py
This will print a table of a user's roles.  The listing is not complete,
but the function can be easily added to to include more access
integrations.
Example invocation:
qontract-cli --config config.toml get roles klape
=> Add 'roles' CLI command

reconcile/gitlab_fork_compliance.py
Fixing the issue with members of the source project not being listed.
Yep, we have to call `all()` and pass `all=True` to it:
https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects.py#L1094-L1098
=> Listing all members

reconcile/owner_approvals.py, utils/jjb_client.py, utils/throughput.py
covers https://issues.redhat.com/browse/APPSRE-1643
We're seeing app-interface jenkins jobs failing with the following error:
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/service-app-interface-gl-pr-check/9931/console
This is caused by the owner-approval integration, which is executed twice and uses a file on the file system to send information from the first iteration to the second iteration.
The file ownership should be changed so it can be deleted.
=> [owner-approval] change file ownership

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/queries.py, reconcile/terraform_vpc_peerings.py, utils/ocm.py, utils/terrascript_client.py
this PR adds an integration that creates VPC peering between OSDv4 cluster VPCs and AWS accounts managed in app-interface.
This is currently a manual step done during cluster provisioning.
covers https://issues.redhat.com/browse/APPSRE-1586
matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3503
=> [terraform-vpc-peerings] introduce new integration

utils/vault_client.py
in most cases, vault_client is used via secret_reader, which already uses `retry`.
openshift-resources uses vault_client directly when trying to fetch secrets of provider `vault-secret`.
this PR adds `retry` to vault_client read functions for better resiliency.
=> [vault_client] retry read

reconcile/terraform_resources.py, utils/terrascript_client.py
Covers https://issues.redhat.com/browse/APPSRE-1614
This PR adds support in terraform-resorces for a new provider: `cloudwatch`.
This provider will add:
- CloudWatch log group
- IAM user (+access key)
- IAM user policy (to allow log group access)
Matching app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3786
=> [terraform-resources] add support for cloudwatch log groups

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
Reuse fluentd to ship log to both slack and cloudwatch.
Need to update fluentd image first. 
https://github.com/app-sre/fluentd/pull/2
=> ship log to cloudwatch via fluentd

utils/saasherder.py
This is useful for the insights migration so that we can update the image tag by hand while the deployment templates are in a different repo from the code.
=> Don't override IMAGE_TAG if it's already specified in target params

reconcile/openshift_groups.py
most of the groups we manage are either built-in (dedicated-admins/dedicated-readers) or are created by external resources (operators).
it's usually not the right move to delete groups (we've never really had to delete a group).
disabling this option for now, we can re-evaluate again later.
cc @jmelis
=> [openshift-groups] don't delete groups

utils/quay_api.py
This avoids hitting a KeyError when iterating over members if the quay team does not yet exist:
```
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/quay_membership.py", line 163, in run
current_state = fetch_current_state(quay_api_store)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/quay_membership.py", line 56, in fetch_current_state
members = quay_api.list_team_members()
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/utils/quay_api.py", line 36, in list_team_members
for member in body[u'members']:
KeyError: 'members'
```
Instead the 404 response from quay should clue us in to what went wrong.
=> Check status code of members response

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
one of the objectives of logs is to be able to determine what happened when.
the current state does not allow us to know that, since the names of log streams are the name of pods, and we don't know what pod came before another.
this PR renames the log stream to be the integration name, so we have a single place to view logs by each integration, regardless of which pod made these changes.
cc @BumbleFeng @tparikh
=> rename cloudwatch log stream from pod name to integration name

utils/terrascript_client.py
Parameter group name is not required by terraform. However, our integration has it marked as required. If user does not provide a name, we will use the rds identifier as the name. This will allow us to reuse parameter group configfor multiple RDS instances.
=> RDS parameter group name should be optional

openshift/qontract-reconcile.yaml
This will allow us to select a deployment and view the pod running as part of it. right now we use same label on all pods which makes it harder to filter
=> update integration deployment labels to match name

tools/qontract_cli.py
covers https://issues.redhat.com/browse/APPSRE-1736
This PR adds a new command to qontract-cli:
```
qontract-cli --config config.toml get clusters-network
```
It shows the network information of all clusters, allowing to select an unused range.
=> [qontract-cli] add clusters-network

reconcile/openshift_base.py, utils/saasherder.py
this PR adds the html url of a resource to the error details, so that it can be displayed when apply caused an error. this adds quite a bit of traceability.
=> [openshift-saas-deploy] add template url to error message

utils/saasherder.py
in order to allow specifying images that do not require authentication in the same saas file as images that require authentication, let's check the image again without authentication in case authentication is defined.
=> [openshift-saas-deploy] check image again without auth

tools/qontract_cli.py
adding a small touch on https://issues.redhat.com/browse/APPSRE-1718.
`qontract-cli get bot-login <cluster>` will print out the `oc login` command with the bot's token.
=> [qontract-cli] get bot-login

utils/saasherder.py
Instead of a stack trace, print the url to the file and the target hash,
along with the error message pulled from the original Exception object.
=> Print more useful error message when a deployment template can't be fetched

reconcile/queries.py, tools/qontract_cli.py
This PR adds the following commands to qontract-cli:
```
get products
describe product <name> - shows a list of namespaces which belong to the product
get environments
describe environment <name> - shows a list of namespaces which compose the environment
```
=> [cli] Add Products and Environments

reconcile/cli.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py
Part of https://issues.redhat.com/browse/APPSRE-1276
Following the work in https://gitlab.cee.redhat.com/service/app-interface/merge_requests/4267
This PR adds the ability to run the openshift-saas-deploy integration for a specific saas-file and for a specific environment targeted from that saas file.
Each target is a namespace, and each namespace is a part of an environment.
This will allow us to create dedicated jenkins jobs that will deploy using this integration, but without dependency on other saas files.
Example:
```
qontract-reconcile --config config.toml --dry-run openshift-saas-deploy --saas-file-name saas-github-mirror --env-name App-SRE-stage
```
=> [openshift-saas-deploy] add option to deploy only specific saas-files and specific envs

utils/gql.py
currently when a resource is not found, it may be a result of a data reload.
this PR helps to reflect that better, while preserving the "resource not found" error.
=> [gql quary] reflect conflict when resource is not found

reconcile/openshift_acme.py, reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_limitranges.py, reconcile/openshift_network_policies.py, reconcile/openshift_resources.py, reconcile/openshift_rolebindings.py, reconcile/openshift_saas_deploy.py, reconcile/openshift_serviceaccount_tokens.py, reconcile/terraform_resources.py
This PR makes `oc delete` actions allowed only if no errors were found (and logged in ResourceInventory (`ri`)).
=> consolidate openshift delete behavior

reconcile/aws_garbage_collector.py, reconcile/cli.py, reconcile/queries.py, utils/aws_api.py
This PR changes aws-garbage-collector to be an opt in feature (must specify `garbageCollection: true` in an aws account file, and enabling resource deletion.
=> [aws-garbage-collector] enable deletion, add opt in

reconcile/openshift_resources.py
resolves ```10:50:12   File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/utils/threaded.py", line 10, in wrapper
10:50:12     return func(*args, **kwargs)
10:50:12   File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/openshift_resources.py", line 473, in fetch_states
10:50:12     spec.parent)
10:50:12   File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/openshift_resources.py", line 415, in fetch_desired_state
10:50:12     openshift_resource = fetch_openshift_resource(resource, parent)
10:50:12   File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/openshift_resources.py", line 374, in fetch_openshift_resource
10:50:12     openshift_resource = fetch_provider_route(path, tls_path, …
```
=> pop cannot have default on list

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py, utils/openshift_resource.py, utils/saasherder.py
This PR adds support for a new feature - `multiple_callers`.
When openshift integrations call `realize_data` with `multiple_callers=True`, the execution assumes that there may be multiple running instances of the integration, and each instance should only handle its own resources.
In our use case, the openshift-saas-deploy integration can now run in multiple instances, modifying the same namespaces from different saas files, and still not get in the way of itself.
We introduce a new annotation that will be used for that purpose - `qontract.caller_name`. This annotation will only be set by the openshift-saas-deploy integration.
=> [openshift-saas-deploy] enable multiple running instances of the integration

reconcile/openshift_saas_deploy.py, utils/saasherder.py
to allow executing the integration externally, as long as there are no access attempts to gitlab - this should work just fine!
=> [openshift-saas-deploy] allow execution without access to gitlab

utils/openshift_resource.py
improving the comparison logic for openshift-saas-deploy to not attempt to reconcile ServiceAccounts over and over due to the default dockercfg secrets attached to SAs by OpenShift.
=> [openshift-saas-deploy] ignore default dockercfg secret in SAs

reconcile/queries.py, utils/saasherder.py
This PR makes it not required to specify hash_length, and the default will be set in app-interface settings.
It also renames the field `hash` to `ref`, as this is what the field holds.
=> [openshift-saas-deploy] extract hash_length to settings and rename hash to ref

README.md, reconcile/cli.py, reconcile/jenkins_job_builder.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/queries.py, tools/qontract_cli.py, utils/saasherder.py, utils/state.py
This PR adds an integration called `openshift-saas-deploy-trigger-moving-commits`.
Whenever a commit is changed under a ref in a saas file (a new PR is merged to `master` for example), this integration will trigger the correct jobs in Jenkins to perform the required deployment operations.
If such a job has an `upstream` field, it will not be triggered, but rather listen to another job and execute after it (enabling image build to be synced).
=> [openshift-saas-deploy] trigger by moving commits integration

utils/saasherder.py
to prevent repeated triggers due to namespaces in the same environment in the same saas file
=> [openshift-saas-deploy-triggers] improve key uniqueness

utils/repo_owners.py
This will reduce the number of un-cachable calls to github mirror.
=> Only get OWNERS_ALIASES when it's present in the repo tree

reconcile/queries.py, utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-1871
this PR adds support for `imagePatterns` which will verify that each deployed image is in this list.
we are checking that each image starts with any of the given strings in the list.
=> [openshift-saas-deploy] add support for image patterns

reconcile/queries.py, tools/qontract_cli.py
covers https://issues.redhat.com/browse/APPSRE-1883
This PR adds a command to qontract-cli to allow developers to deploy templates as deployed via app-interface.
```
(venv) $ q saas-dev --help
Usage: qontract-cli saas-dev [OPTIONS]
Options:
--app-name TEXT        app to act on.
--saas-file-name TEXT  saas-file to act on.
--env-name TEXT        environment to use for parameters.
--help                 Show this message and exit.
```
=> [qontract-cli] add saas-dev command

reconcile/cli.py, utils/unleash.py
part of https://issues.redhat.com/browse/APPSRE-1728
use a temp directory as unleash cache directory to avoid:
```
File "/usr/local/bin/qontract-reconcile", line 11, in <module>
load_entry_point('reconcile==0.2.2', 'console_scripts', 'qontract-reconcile')()
File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", …
```
=> [unleash] use temp dir for cache

README.md, reconcile/cli.py, reconcile/jenkins_webhooks_cleaner.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-1210
this PR adds a new integration that removes webhooks in gitlab projects to previous jenkins instances.
=> [jenkins-webhooks-cleaner] introduce new integration

reconcile/queries.py, reconcile/terraform_vpc_peerings.py
This updates the terraform_vpc_peerings integration to support targetting clusters as VPC peering targets
=> add support for cluster as vpc peering target

reconcile/queries.py, reconcile/terraform_vpc_peerings.py
Reverts app-sre/qontract-reconcile#730
This did not work as intended. The peer_owner_id (the account) used in the requester peering has to be the ID of the AWS account that we are peering to.
=> Revert "add support for cluster as vpc peering target"

utils/oc.py
Pods with ownerReferences that do not contain 'controller' raise a
KeyError when trying to find the root owner in order to recycle the
deployment.
It seems that the 'controller' attribute does not appear in
ownerReferences of pods that are not running, e.g. *-deploy pods that
were not immediately deleted upon termination of the pod.  Therefore it
seems safe to assume pods without the 'controller' attribute in
ownerReferences can be skipped for recyling.
=> Allow for absence of controller attribute in owner ref

README.md, helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/aws_ecr_image_pull_secrets.py, reconcile/cli.py, reconcile/queries.py, utils/aws_api.py
this integration generates image pull secrets for AWS ECR and stores them in vault.
the plan is to consume these secrets into namespaces using openshift-vault-secrets.
this integration will run once every 6 hours in a CronJob.
=> [aws-ecr-image-pull-secrets] introduce new integration

utils/terrascript_client.py
covers https://projects.engineering.redhat.com/browse/RHCLOUD-6817
since we give permissions for the specific log group, adding this shouldn't be harmful despite the fact that app-interface is creating these log groups.
=> add logs:CreateLogGroup permission to cloudwatch provider

reconcile/saas_file_owners.py
solves this (lgtm is valid, so no lines should be added to comment, so no comment should be added):
```
File "/usr/local/lib/python3.6/site-packages/python_gitlab-1.11.0-py3.6.egg/gitlab/exceptions.py", line 259, in wrapped_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/python_gitlab-1.11.0-py3.6.egg/gitlab/mixins.py", line 204, in create
server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
File "/usr/local/lib/python3.6/site-packages/python_gitlab-1.11.0-py3.6.egg/gitlab/__init__.py", line 674, in http_post
**kwargs
File "/usr/local/lib/python3.6/site-packages/python_gitlab-1.11.0-py3.6.egg/gitlab/__init__.py", line 564, in http_request
response_body=result.content,
gitlab.exceptions.GitlabHttpError: …
```
=> [saas-file-owners] ignore empty comment

reconcile/aws_ecr_image_pull_secrets.py
this will allow us to supply the basic-auth output secret to jenkins jobs that need to push images to ECR.
the secret will always contain valid push credentials.
=> [aws-ecr-image-pull-secrets] add url to basic-auth output secret

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
these integrations do not have to run continuously.
this PR changes:
- aws-garbage-collector to run once a week
- github-users - to run once a month (and send emails to users that do not have "Red Hat" in their github profile)
=> aws-garbage-collector and github-users to CronJobs

reconcile/github_owners.py
covers https://issues.redhat.com/browse/APPSRE-1981
this PR makes the integration avoid users with pending invitations.
=> [github-owners] take invitations into account

utils/gitlab_api.py, utils/saasherder.py
following a gitlab upgrade, the `project.files.get` is broken if path is passed with a leading `/`.
=> gitlab upgrade fixes

README.md, helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_github_idp.py, reconcile/queries.py, utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-1819
this integration will create github IDPs in OCM, based on the `auth` data in a cluster file.
Vault secrets with github OAuth apps client-id and client-secret should pre-exist (manually :cry:)
this integration only creates new IDPs, allowing us to keep managing manually as well.
=> [ocm-github-idp] introduce new integration

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, utils/aws_api.py
part of https://issues.redhat.com/browse/APPSRE-1819
until now, we had to supply the cluster's VPC ID in order to be able to set VPC peerings.
this PR adds usage of AWS API in the integration to find the cluster's VPC ID according to the CIDR block defined in the cluster file.
this makes the cluster on-boarding much easier, as no one has to login to the cluster's AWS console to find the VPC ID.
=> [terraform-vpc-peerings] cluster vpc_id no longer required

setup.py
It contains a fix to the image comparison between two registries
=> Bump sretoolbox to 0.5.3

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py
in the case a namespace and a saas file are created in the same MR, the trigger to the job may arrive before the namespace was created.
this PR adds the option for an integration to request to wait for the namespace to exist.
=> [openshift-saas-deploy] wait for namespace to exist

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile.yaml
This is supposed to be a pod label, not a deployment one.
=> Moving label to the right place

reconcile/sentry_config.py
When the same team shows up in different places, the data structure is reset
and only the projects from the last definition are taken into account.
This patch add a check to decide if we have to extend the team projects.
=> Fix sentry: support multiple instances of the same team

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
In a typical unconstrained execution, it spikes at 88MB. That spike
should be covered by the requests (with some margin). The limit is set
to 50% above the requests.
=> Increase the memory requests/limits for the github integration

reconcile/openshift_network_policies.py
Shard 2 is running consistently slower than shard 0. I think this is because we are not sharding on the correct key.
Right now we are sharding based on the namespace name only, and we have many instances of the same name, and those are all sharded to same instance:
```
$ q get -o json namespaces|jq -r '.[].name'|sort |uniq -c |sort -k1 -n|tail
3 redacted
3 redacted
3 redacted
3 redacted
3 redacted
5 redacted
5 redacted
12 redacted
13 redacted
13 redacted
```
Since it's preferable to shard on unique keys, I propose this patch, with this we will favour shards to run similar workloads.
=> distribute shards

reconcile/openshift_resources_base.py
there are cases when we want to add templating for the vault path or key to use. this PR implements that.
=> preprocess jinja vault path and key

dockerfiles/hack/run-integration.py
in the case of a CronJob, if the data changes during execution, we want to re-try it.
i guess we also want to expose metrics on CronJobs as well...
=> exit on RUN_ONCE only after return_code checks

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
The integration was oom-killed 42 times out of 339 runs in the last 24h.
It currently peaks at ~770Mi. Let's set the requests to 800 and the limits to 30% above that.
=> Increasing openshift-routes memory

utils/saasherder.py
currently, even if there is a change to `managedRoles` in a namespace file, a new deployment will be triggered to that namespace.
this PR sanitizes the namespace object to avoid triggering jobs on unrelated changes.
=> [openshift-saas-deploy-trigger-configs] only trigger on changes in relevant fields

reconcile/queries.py, utils/saasherder.py
this PR adds a way to disable deployments in openshift-saas-deploy to specified targets.
the actual job in Jenkins will still be enabled, but the target will be skipped during execution.
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/5471
=> [openshift-saas-deploy] add option to disable deployment to a target

utils/saasherder.py
currently we only allow to supply a single image authentication secret in a saas file. moving forward, we will probably need to allow a list quite soon.
even now, not all images in a saas file require authentication, and specifically some of them (and sometimes most of them) do not require the authentication specified in the image auth section.
sretoolbox's `Image` already supports an `auth_server` argument. using it, it will decide if the image that is currently checked belongs to the server to which we authenticate to. if not equal, the image check will be done without authentication.
this speeds up saas file deployments, as it reduces the number of authentication calls.
=> [openshift-saas-deploy] use auth_server to check image when it exists

utils/saasherder.py
openshift-saas-deploy currently works in parallel per saas file. this is ~fine for deploying multiple saas files, but has no impact when deploying a single saas file.
this PR updates the behavior to first initiate a list of specs to fetch when populating the desired state, and populate all specs in parallel. each spec represents the `target` level, so in fact this is changing the parallelism from per saas file to per target.
this PR also changes the image check to happen only once per target and not once per every resource in the target.
in addition, images are checked in parallel (a sane pool size is estimated by number of saas files and total number of namespaces, which represent targets). for a saas file with many images such as telemeter, this reduces the execution time from ~2m to …
=> [openshift-saas-deploy] improve parallelism model

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py
for multiple reasons, let's just apply all resources in every execution:
1. better user experience (why wasn't this Service applied?)
2. faster execution (even if by a bit)
3. avoids errors in our internal compare logic
=> [openshift-saas-deploy] skip compare when running in non dry-run mode

reconcile/cli.py
this is to be able to run openshift-saas-deploy jobs without being worried that they will fail due to updating data. since each job only deploys a single saas file and a single environment, changes to the data are likely not affecting it, so better to let it run.
=> add option to run integrations without using the gql sha endpoint

reconcile/cli.py, reconcile/openshift_saas_deploy.py, reconcile/saas_file_owners.py, reconcile/saas_file_validator.py, utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-2113
this PR adds an option to pass the `--io-dir` argument to openshift-saas-deploy and let it run only on the input in that directory.
input is a file called `diffs.json`, containing a list of dictionaries, each of them with 2 keys: `saas_file_name` and `environment`. the input file is generated by the saas-file-owners integration, which should be executed before openshift-saas-deploy.
when io-dir is passed, saas-file-name and env-name may not be passed.
in addition, since openshift-saas-deploy will not be using io-dir in our pr checks, we still need to validate all our saas files, so adding a very simple saas-file-validator integration.
=> [openshift-saas-deploy] add option to get input from io-dir

reconcile/cli.py, reconcile/openshift_saas_deploy.py, reconcile/openshift_saas_deploy_wrapper.py, utils/saasherder.py, utils/threaded.py
partially reverts #865.
this PR adds a wrapper integration around openshift-saas-deploy.
the reason for this change is that we want to use saas_file_name as the caller. this is to prevent false prints of resources that are about to be deleted in case there is more then a single saas file deploying to each namespace.
=> [openshift-saas-deploy] introduce wrapper for io-dir

reconcile/saas_file_owners.py
prevent running openshift-saas-deploy twice from openshift-saas-deploy-wrapper.
=> [saas-file-owners] unique diffs only

reconcile/openshift_saas_deploy_trigger_configs.py, utils/jenkins_api.py
openshift-saas-deploy-trigger-configs triggers deployment jobs when a configuration changes.
however, if a configuration change occurs while a target's upstream job is running, it may mean that an image is in the process of being built, and we will be unable to deploy.
in such a case, it makes sense to assume that the deployment will be triggered by the upstream job upon success (as they are linked in jenkins). if the job fails, it's better that we didn't deploy.
the integration should skip triggering jobs who's upstream job is currently running. this PR does just that.
=> [openshift-saas-deploy-trigger-configs] skip trigger when upstream is building

utils/oc.py
we allow Secrets and ConfigMaps to trigger a re-deployment by specifying the following annotation: `qontract.reconcile: "true"`.
the value has to be a string. this PR adds a validation for it.
=> check qontract.recycle annotation

reconcile/queries.py, reconcile/slack_usergroups.py, utils/pagerduty_api.py
part of https://issues.redhat.com/browse/APPSRE-2057
instead of using the user's name field (which may contain special chars) we use the user's id and get his email (organization username).
=> [slack-usergroups] do not depend on PagerDuty name

utils/oc.py
It can be `None` if unset, so the checks will become a bit convoluted. It
is valuable to keep the check to be the string `"true"` to give
information in case of error.
=> Just check for qontract.recycle to be the string "true"

utils/openshift_resource.py
fixes https://issues.redhat.com/browse/APPSRE-2124
since moving to openshift-saas-deploy in a distributed model, we have added support for a `caller` key to be passed to openshift_resource. this key is used to enable deploying to the same namespace from multiple saas files without interfering with one another.
this PR fixes a bug due to which resources in "shared" namespaces were not being deleted.
:facepalm:
=> fix resource delete to due missing caller

reconcile/openshift_saas_deploy.py, utils/saasherder.py
in a case where a job only deploys to a single target and that target is disabled, openshift-saas-deploy should exit cleanly.
=> [openshift-saas-deploy] exit 0 on no namespaces

reconcile/jenkins_job_builder.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-1536
this will allow users outside or red hat to be defined as jjb admins, as long as they have sponsors (sponsors are validated in the json schema).
=> [jenkins-job-buider] add external users

reconcile/gitlab_housekeeping.py
in addition to merging in reversed order (FIFO), we want to merge according to label priority.
the most important label is `approved` which indicates a tenant is self-servicing a merge.
`automerge` comes next to allow our automations to accomplish their goals. `lgtm` comes last since this is a manual process anyway.
=> [gitlab-housekeeping] merge and rebase by label priority

utils/vault_client.py
requests has a default connection pool of 10. Creating
multiple threads will consume from that same pool, since
the underlying implementation of the requests pool is a singletown.
Let's limit our thread_pool_size to the requests connection pool
size so we don't exhaust it.
=> Fix warning "Connection pool is full, discarding connection: ..."

reconcile/openshift_saas_deploy.py
since some resources may only be deployed in a specific resource template, this is an inaccurate check at this time.
=> [openshift-saas-deploy] don't check unused resources

reconcile/terraform_resources.py
we don't want to catch all exceptions (stack traces are fantastic!).
we especially don't want to catch 409 conflict exceptions, so that the integration can exit cleanly and without failing, as this is a known and handled situation.
=> [terraform-resource] remove try-except from run

utils/terrascript_client.py
The policy might contain "/", but that is not accepted
in the group name.
=> Fix policy group name

reconcile/ocm_groups.py
The OCM API does not have an endpoint to create/delete groups.
This is probably because groups are "created" when a user is added to them (I did not test this yet).
Assuming this is true, this PR makes the ocm-groups integration ignore group create/delete and only adds/removes users, which is all it should be doing (it shouldn't attempt to create/delete groups).
=> [ocm-groups] don't create/delete groups

utils/smtp_client.py
```
sys.exit(load_entry_point('reconcile==0.2.2', 'console_scripts', 'qontract-reconcile')())
File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1066, in invoke
File …
```
=> [smtp client] retry sending mail

README.md, reconcile/cli.py, reconcile/integrations_validator.py, reconcile/queries.py, reconcile/status.py, utils/gql.py
The goal of this PR is twofold:
- ensure that all integrations are defined in App-Interface
- blocks integration from querying schemas if the schema is not defined in the corresponding App-Interface integrtaion file
In order to achieve these two goals the following changes are included in this PR:
**Integration**
> `integrations-validator`: Ensures all integrations are defined in App-Interface.
This integration programmatically iterates through all the integration click commands, and ensures that they exist in App-Interface
**Mandatory schema validation**
Integrations now run with the enabled feature of validating schemas: `--validate-schemas` which is set to True by default.
If necessary this can be disabled with the option `--no-validate-schemas`.
Also, in order to make the developer …
=> validate integrations and schemas (introduces a new integration: integrations-validator) 

utils/gql.py
some queries will not return extensions/schemas, so this PR ensures that
the code does not crash in that case
=> account for missing extensions/schemas in the payload

reconcile/cli.py, utils/gql.py
The `--dump-schemas FILE` option is especially useful in conjunction with `--no-validate-schemas` during local development in order to compile the list of schemas that an integration queries.
=> add --dump-schemas FILE option

utils/terrascript_client.py
fixes https://issues.redhat.com/browse/APPSRE-2196
as per https://github.com/hashicorp/terraform/pull/8622, we are able to define a password even when restoring from a snapshot.
when restoring from a snapshot, the password will be randomly generated and applied to the new DB instance.
if we want to keep an old password, that required manual intervention to:
- disable terraform-resources in unleash
- run the integration with --print-only
- manually update the password (in 2 places!)
- tf init, tf plan, tf apply
- merge the MR adding the DB
- enable the integration in unleash
=> [terraform-resources] rds include username and password when using snapshot

reconcile/github_org.py, reconcile/openshift_groups.py, reconcile/openshift_rolebindings.py
currently, to run the github integration we need an automationToken so we can initialize an oc client for each cluster.
the reason we are initializing an oc client for each cluster (oc_map) is because the integration relies on logic from other integrations (openshift-rolebindings and openshift-groups) which REQUIRE an oc client.
the github integration, however, does not care about this. it will add users to github teams for cluster access, even if that cluster does not have an automationToken.
this makes sense because in the cluster on-boarding process we first want to allow access for users to the console, and only after that we are able to create the bot SA to add the automationToken.
tl;dr - another chicken/egg situation solved.
=> [github] do not depend on automationToken

reconcile/queries.py, utils/saasherder.py
covers https://issues.redhat.com/browse/APPSRE-1753
this PR adds the ability to specify the `directory` provider in a saas file to indicate that the resources to apply are raw manifests in a directory (applies all resources).
=> [openshift-saas-deploy] add support for raw manifests in directory

reconcile/openshift_saas_deploy.py, utils/saasherder.py
when a target specifies an `upstream` job, it is mostly because that upstream job is building an image required for the deployment job.
if we trigger the deployment job while the upstream job is running, the deployment job will wait until the build job is complete. this is thanks to [this block-upstream field](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/global/templates.yaml#L211).
this means that it is ok to merge a MR while the upstream job is running, which means that it's pr-check should pass.
this change implements this behavior.
=> [openshift-saas-deploy] skip image check if upstream job is running

reconcile/jenkins_plugins.py, reconcile/openshift_saas_deploy.py
this is to allow jobs to run in ci-ext without asking for creds for ci-int, which are not permitted.
=> [openshift-saas-deploy] only use jenkins instances in saas files

reconcile/terraform_vpc_peerings.py, utils/terrascript_client.py
covers https://issues.redhat.com/browse/APPSRE-2234
when the vpc peering is between clusters, we need to use the accepter's alias provider (the cluster's aws account id).
when the vpc peering is between a cluster and an aws account, we need to use the default provider (the aws account).
=> [terraform-vpc-peerings] use default provider for account-vpc accepter

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, utils/aws_api.py, utils/terrascript_client.py
covers https://issues.redhat.com/browse/APPSRE-1861
this PR adds the ability to manage routes in existing route tables in a cluster's aws account.
that cluster can be a requester, an accepter or the requester in an `account-vpc` connection. it all works.
issues:
- for now, it only works with creating new routes (i am still unable to import all the existing routes which were created manually).
- since we don't have permissions to delete routes, we can't "unmanage" routes (this will involve removing routes from the state).
for that reason i have added a selective `manageRoutes` field to be used.
=> [terraform-vpc-peerings] add routes capability

reconcile/openshift_saas_deploy.py, reconcile/queries.py, utils/saasherder.py
in case we want to exclusively manage resources defined in a saas file, we can now add `takeover: true` in the saas file.
this uses the existing functionality in openshift_base.realize_data.
=> [openshift-saas-deploy] add support for takeover

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml
The process was OOM-killed multiple times today
=> dashdotdb-cso: increase memory requests & limits

reconcile/github_repo_permissions_validator.py, reconcile/jenkins_job_builder.py, reconcile/jenkins_webhooks.py, tools/app_interface_reporter.py
just like we do for any jjb definition.
one of the reasons is that behind the scenes, we are backing up all repos listed under codeComponents.
=> [jenkins-job-builder] validate all saas file repos in codeComponents

reconcile/cli.py, reconcile/unleash_watcher.py, utils/state.py
part of https://issues.redhat.com/browse/APPSRE-2249
we don't want to miss events because of a pod restart, so let's use state instead of io-dir.
=> [unleash-watcher] use state instead of io-dir

reconcile/cli.py, reconcile/openshift_resources.py, reconcile/openshift_resources_base.py, reconcile/openshift_routes.py, reconcile/openshift_vault_secrets.py
this PR adds two new flags to be passed to the following integrations:
- openshift-resources
- openshift-vault-secrets
- openshift-routes
the flags are:
- `cluster-name` - only run for a cluster with this name
- `namespace-name` - only run for namespaces with this name
this allows us to run integrations for any particular namespace we choose.
or for all namespaces with that name (think hive).
or for all namespaces in a cluster (think hive).
=> allow running openshift-resources based integrations per cluster and namespace

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py, utils/oc.py
we sometimes want to add deployment of CRs which their CRDs have not yet been applied to the cluster.
this PR adds a check that a resource kind under `managedResourceTypes` is also available in `oc api-resources`.
if it doesn't, the integration will not attempt to fetch it's current state.
assuming such a resource will only be available in the template after the CRD has been applied.
example issue that this PR solves: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/6808
=> [openshift-saas-deploy] check that kind exists in api-resources

helm/qontract-reconcile/values.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_clusters.py, reconcile/pull_request_gateway.py, reconcile/queries.py, utils/gitlab_api.py, utils/ocm.py, utils/sqs_gateway.py
part of https://issues.redhat.com/browse/APPSRE-2273
with this PR, ocm-clusters does not fail when cluster version is different - it will submit a MR to update the version in app-interface if the current version is larger. in addition, a cluster creation is now done based on the version defined in `initial_version` instead of `version`, as the latter will be used to track the current version.
=> [ocm-clusters] submit cluster version update MRs and install from initial_version

reconcile/openshift_saas_deploy_wrapper.py
since the underlying function is using sys.exit(), the thread is not being closed and the execution of openshift-saas-deploy-wrapper does not end.
=> [openshift-saas-deploy] don't hang when thread exits

reconcile/openshift_base.py, utils/oc.py
fixes https://issues.redhat.com/browse/APPSRE-2064
this PR adds a check if `oc apply` failed due to this issue, and if so - it will remove the annotation and re-apply.
=> remove last-applied-configuration annotation on 0x0

reconcile/openshift_base.py, utils/openshift_resource.py
in cases where we deploy from a saas file and it defines that it is taking over, we should skip the equal resource compare to avoid any misses to apply (when a label is removed for example).
this is mostly about ClusterImageSets, but we can revisit this later.
=> [openshift] skip equal compare in specific cases

reconcile/openshift_resources.py, reconcile/openshift_resources_base.py
based on the work in #950.
we sometimes want to add resources of CRs which their CRDs have not yet been applied to the cluster.
this PR adds a check that a resource kind under managedResourceTypes is also available in oc api-resources.
if it doesn't, the integration will not attempt to fetch it's current state.
assuming such a resource will only be available in the template after the CRD has been applied.
example issue that this PR solves:
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/7101
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/7104
=> [openshift-resources] check that kind exists in api-resources

utils/terrascript_client.py
When `transit_encryption_enabled` is set to `False` (default), setting `auth_token` will cause tf to fail.
=> only set auth_token if transit_encryption_enabled is true

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
Running as a normal integration (every 2min) is too much. Let's convert
it into a CronJob and run every 6 hours.
=> dashdotdb-cso as a cronjob

reconcile/cli.py, reconcile/gitlab_ci_skipper.py, utils/gitlab_api.py
this integration checks if a `skip-ci` label exists on the MR and prints `yes` or `no` accordingly.
if the answer is `yes` - we can skip integrations in manual_reconcile.sh.
this also fixes ocm-clusters to not submit empty MRs.
=> [gitlab-ci-skipper] introduce integration + ocm-clusters fix

reconcile/pull_request_gateway.py, reconcile/queries.py, utils/gitlab_api.py
part of https://issues.redhat.com/browse/OSD-4840
this PR adds an option to receive an MR request through SQS gateway to update CIDR blocks for cloud-ingress-operator.
the message to the queue should be of the form:
```
{'pr_type': 'create_cloud_ingress_operator_cidr_blocks_mr', 'cidr_blocks': ['x.x.x.x/xx', 'y.y.y.y/yy']}
```
this message in the SQS queue will result in a MR to app-interface similar to this one:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8060
requests will be sent from the private-cluster-rhapi-apischeme-updater CronJob:
https://github.com/openshift/private-cluster-rhapi-apischeme-updater/pull/18
=> [gitlab-api] add create_mr function for cloud-ingress-operator

reconcile/sql_query.py
identifier is not mandatory and sometimes it does not exist.
=> Fix sql query

README.md, reconcile/cli.py, reconcile/gitlab_labeler.py, utils/gitlab_api.py
this integration adds labels to MRs based on the changed paths and on the existing labels in the project.
for example, if the `/services/myservice/` path changed and we have a label containing the word `myservice` - that label will be added.
the integration basically guesses labels and we will probably need to modify the logic or the data in app-interface as we find issues.
=> [gitlab-labeler] introduce new integration

reconcile/openshift_base.py, utils/oc.py
in some cases when we apply resources we get an invalid value error `Invalid Value 0x0`, which can be handled by removing the last applied configuration annotation.
this PR changes the way the `apply` method works, and makes it retry apply actions which got an error which is not the invalid value error.
this should allow us to apply resource types which depend on the previously applied resources. for example, an operator creating a CR - with this change we should be able to apply both resource types from the same saas file, as long as the dependant CR is listed after the creating resources under `managedResourceTypes`.
=> retry apply on error if it's not an invalid value error

reconcile/queries.py, utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2162
this PR adds support for OCM's API channel_group field, with which we can provision clusters in channels other then `stable` (in our case, `fast`).
=> [ocm-clusters] add support for channel

reconcile/gitlab_labeler.py
if the path contains `cicd`, which is very common, ignore it.
=> [gitlab-labeler] ignore cicd

reconcile/gitlab_mr_sqs_consumer.py
We have to create a new object to pass in for the lambda, otherwise
all lambdas will ping to the last message.
=> Fix SQS message deletion

utils/saasherder.py
we don't really want to babysit for users enabling/disabling their targets. let's not warn about this.
=> logging debug for disabled targets instead of warning

reconcile/openshift_saas_deploy_trigger_moving_commits.py
This ensures we don't trigger jobs for saas-file targets that are disabled
=> saas-deploy-trigger-moving-commits: only consider targets that are not disabled

utils/saasherder.py
The parameters are no really mandatory. Let's not fail when they are not
present in the template.
=> Don't fail on template missing parameters

reconcile/openshift_resources_base.py
fixes #1054
oc.api_resources is always set, either to None or to an actual value.
=> oc.api_resources fix

reconcile/queries.py, reconcile/saas_file_owners.py
part of https://issues.redhat.com/browse/APPSRE-2466
this PR adds an option for a user to define `tag_on_merge_requests: true` in their user file, which will lead to them being pinged on MRs for saas file they own.
=> [saas-file-owners] allow users to be tagged on MRs

reconcile/gitlab_housekeeping.py, reconcile/saas_file_owners.py, utils/mr/labels.py
to make it clear that these labels are used by bots and not by humans, instead of using:
- `approved`
- `hold`
- `automerge`
- `skip-ci`
we will now use:
- `bot/approved`
- `bot/hold`
- `bot/automerge`
- `bot/skip-ci`
we may remove the usage of the previous labels after this change.
=> use explicit bot labels

reconcile/ocm_clusters.py, reconcile/queries.py, utils/ocm.py
depends on https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/2140 reaching production
this PR adds the ability to provision clusters in specific hive shards according to their id, as defined here: https://gitlab.cee.redhat.com/service/app-interface/-/blob/96ea6b2233a9416c7d3126d0462ac7bed7280d5c/data/services/ocm/namespaces/uhc-production.yml#L50
=> [ocm-clusters] add support for provision_shard_id

reconcile/openshift_resources_base.py
in the openshift-config namespace we use the `managedResourceTypeOverrides` field, which allows us to apply resources which have a `kind` that exists in more then a single api group.
this PR adds a handle for this case when checking if the desired kind exists in `oc api-resources`.
=> [openshift-resources] fix api_resources check to match managedResourceTypeOverrides

reconcile/terraform_resources.py
This makes tf-r fail to create a new RDS isntance.
This reverts commit 25e77ab8926c5b0835ee74b7c39c1b406f6a8c53.
=> Revert "tf-r-dry-run-no-oc (#1040)"

README.md, reconcile/cli.py, reconcile/jenkins_job_cleaner.py, reconcile/queries.py, utils/jenkins_api.py
this PR adds a new integration: jenkins-job-cleaner
this integration iterates through jenkins instances with a `deleteMethod: manual` and compares the existing jobs in the instance to the desired jobs calculated by jenkins-job-builder. for each such found job, if the job name starts with one of the `managedProjects` of the intsance - the integration will delete the job.
this ensures that we can only delete our own jobs in a multi-tenant jenkins instance.
=> [jenkins-job-cleaner] introduce integration

utils/openshift_resource.py
https://access.redhat.com/solutions/5332041
https://github.com/kubernetes/kubernetes/issues/90066
the new field `managedFields` which available in OpenShift (we're seeing it first in 4.5.7) makes all our integrations believe they need to reconcile resources over and over. this PR will make the integrations ignore this field.
=> openshift canonicalize - remove metadata.managedFields

reconcile/jenkins_job_cleaner.py, utils/jjb_client.py
the cleaner should look at all jobs, including ones with `test` in their name :facepalm:
=> [jenkins-job-cleaner] include test jobs

reconcile/jenkins_job_builder.py
this PR makes the default `upstream` value a string instead of None in case `upstream` is not defined on the first job.
fixes:
```
sys.exit(load_entry_point('reconcile==0.2.2', 'console_scripts', 'qontract-reconcile')())
File …
```
=> [jenkins-job-builder] fix upstream error

reconcile/openshift_resources_base.py
this will allow us to use the cluster's version in templating resources.
=> [openshift-resources] add cluster .spec.version to query

reconcile/sql_query.py
fixes https://issues.redhat.com/browse/APPSRE-2506
this PR adds a check that the terraform resource info is not None, which indicates that the rds identifier does not exist in the specified namespace.
=> [sql-query] check resource info is found

setup.py
since this package was released in a new breaking version, we want to pin it to a previous working version.
breaking version: https://github.com/regebro/tzlocal/releases/tag/3.0b1
=> persist tzlocal to version 2.1

reconcile/aws_route53.py, reconcile/queries.py, utils/aws/route53/__init__.py
This PR adds the ability to specify a list of regexes via `unmanaged_record_names` in a zone file.
The regex in this list will be compiled and records will be checked for a `fullmatch` against the list of regexes. If the record name is found, it is then removed from both the current and the desired state.
This will allow us to add records in AWS outside of the integration flow, without having the integration remove them
This is a quick fix to an immediate problem. Longer term we may want to add state management to the integration instead.
=> aws_route53: exclude records matching items in unmanaged_record_names

reconcile/gitlab_labeler.py
Fix all saas file change get labeled to `tenant-dsass`
=> [gitlab-labeler] add 'saas' in ignore_tokens

reconcile/gitlab_labeler.py
Fix rds file get labeled with `tenant-telemeter-ocp-dashboards`
=> add rds to ignore_tokens

reconcile/terraform_resources.py
Temporary solutions for running tf-r per account locally. 
The integration running on the cluster will manage the secret after any manual running.
Will refactor with `caller` for further operator implement
=> skip apply secret when running tf-r per account

reconcile/gitlab_housekeeping.py
part of https://issues.redhat.com/browse/APPSRE-2484
if a job is cancelled, in many cases the gitlab pipeline will hang and wait forever. we want to merge based on the latest result only, as each run already cancelled the previous one.
=> [gitlab-housekeeping] merge without waiting for pending jobs

reconcile/cli.py, reconcile/gitlab_housekeeping.py
add argument to indicate if rebase/merge should wait for pending/running pipelines before acting.
=> [gitlab-housekeeping] add wait-for-pipeline option

reconcile/openshift_resources_base.py
Part of https://issues.redhat.com/browse/APPSRE-2524
Dpends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/9822
Now that we are running multiple instances of the same service, we are duplicating a lot of the content of a namespace file. Mostly we are duplicating the openshift resources that we want to apply to the namespace.
This PR allows users to define shared resources that can be added to multiple namespace files, thus removing the need to duplicate this content and allow users to update all their namespaces in a single place.
The lack in this ability recently led to 2 namespace files overriding each other and causing a service misconfiguration.
=> [openshift-resources] add support for openshift shared resources

templates/email.yml.j2
as observed in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10036, the aliases section is using refs. as aliases are plain strings, we only need to list the aliases themselves.
=> [app-interface-reporter] fix aliases section

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/jira_watcher.py, reconcile/openshift_saas_deploy.py, reconcile/openshift_upgrade_watcher.py, reconcile/queries.py, reconcile/sentry_helper.py, reconcile/slack_base.py, reconcile/slack_cluster_usergroups.py, reconcile/slack_usergroups.py, reconcile/unleash_watcher.py, utils/slack_api.py
this integration adds all users with access to a certain cluster to a slack usergroup named <cluster_name>-cluster (same as .auth.team in a cluster file).
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10072
=> [slack-cluster-usergroups] introduce new integration

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
it's not really needed to overload the reconcile channel (especially since it's going to be disabled for a week or so)
=> remove logging from slack-cluster-usergroups

reconcile/terraform_resources.py, utils/terrascript_client.py
part of https://issues.redhat.com/browse/RHCLOUD-8432
this PR adds the option to define an altername db name in the namespace file, which will only override the value in the output resource.
this PR replaces the suggested implementation in #941. the difference is that 941 implemented this through the defaults file which is not visible enough and will allow us to keep accumulating such debt.
=> Allow users to provide alternate database name

reconcile/saas_file_owners.py
if there are changes outside the scope of a saas file owner, let's add a note indicating that the MR can not be self-serviced.
=> [saas-file-owners] add note when MR can not be self-serviced

reconcile/saas_file_owners.py
using a better calculated variable to decide whether or not we should include a note that the MR can not be self-serviced.
=> [saas-file-owners] fix self-service note

reconcile/queries.py, reconcile/slack_cluster_usergroups.py
if a user has a role with `tag_on_cluster_updates: false` - exclude them from the user group.
unless there is another role granting access to the same cluster without `tag_on_cluster_updates: false`.
we preserve the previous functionality -
if a user defines `tag_on_cluster_updates: false` on their user file - they are excluded in any case.
=> [slack-cluster-usergroups] do not include users with tagged roles

utils/oc.py
Quick Jobs get to Succeeded before we have time to check them.
=> Add "Succeeded" state to the validation

reconcile/gitlab_housekeeping.py
this PR does:
1. changes the priority to merge `lgtm` MRs before `bot/automerge` MRs. this is to allow faster service to our tenants at the expense of merging automated MRs a bit later (user off-boarding, cluster version updates, etc).
2. adds MRs with `saas-file-update` to be rebased last. there may be cases where a MR that is not rebased is mistakenly understood as changing (recently merged) saas files. at this point, the `bot/approved` label will be removed and such MRs will halt (since the rebasing integration is looking for approved labels). example of what this will fix: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10421
=> [gitlab-housekeeping] update merge/rebase labels

reconcile/gitlab_housekeeping.py
we often see cases of pending pipelines in gitlab when the jenkins job completed.
let's ignore those cases.
=> [gitlab-housekeeping] ignore pending pipelines

reconcile/cli.py, reconcile/jenkins_job_builder.py, utils/jjb_client.py
part of https://issues.redhat.com/browse/APPSRE-2591
the way we currently use the jjb integration (in dry-run mode) is by running it twice: first time to read the current state from the production endpoint and a second time to read the desired state from the local endpoint and print the diffs.
this means that every MR is running the 1st execution even if the jjb integration is not selected for execution afterwards.
this PR changes the way we run the jjb integration - we run it once, like every other integration. that's it.
it will collect the current state from `State` instead.
we tried to read the current state from Jenkins itself, but the JJB defintions and the queried jobs from Jenkins are different to a degree we can't "patch" them to look alike (was attempted a few times in …
=> [jenkins-job-builder] change from compare/no-compare to state

reconcile/saas_file_owners.py
part of https://issues.redhat.com/browse/APPSRE-2591
we will use this output to better select which integrations we want to run in https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/hack/select-integrations.py.
for example, if this MR contains valid saas file changes only (updating a `ref` for example), there is no reason to run the jjb integrations, as this MR will not create/delete any jobs.
=> [saas-file-owners] print if this is a valid saas file changes MR only

reconcile/dashdotdb_cso.py
The API was expecting a List of all imagemanifestvuln from a given
cluster, but that list is just way too big.
Now the API expects each imagemanifestvuln object individually. This
patch is the client implementation for that. Now we loop all the items
in the big imagemanifestvuln list and post them one by one.
Depends on https://github.com/app-sre/dashdotdb/pull/30
=> [APPSRE-2596] Fix "Request Entity Too Large"

reconcile/gitlab_housekeeping.py
gitlab-housekeeping may get jammed trying to rebase/merge an empty MR (without commits). this will make the integration skip such MRs.
example that this solves: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10612
this one had commits but the changes were merged in another MR, causing it to be empty.
=> [gitlab-housekeeping] skip empty MRs

reconcile/openshift_serviceaccount_tokens.py
part of https://issues.redhat.com/browse/APPSRE-2606
we want to write all output secrets to the shared location so it's easier to migrate apps between clusters.
in a follow up PR we will do the work to support `openshiftServiceAccountTokens` in the integration.
allows us to do: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10729
=> [openshift-serviceaccount-tokens] write to shared resources location

reconcile/openshift_base.py, reconcile/openshift_resources_base.py, reconcile/openshift_serviceaccount_tokens.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-2606
Now that we are running multiple instances of the same service, we are duplicating a lot of the content of a namespace file. In addition to openshift resources (#1095), we are duplicating the service account tokens that we want to apply to the namespace.
This PR allows users to define shared resources that can be added to multiple namespace files, thus removing the need to duplicate this content and allow users to update all their namespaces in a single place.
depends on:
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10723
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10727
allows us to do: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10728
note to the reviewer: …
=> [openshift-serviceaccount-tokens] add support for sharedResources

utils/aws_api.py
part of https://issues.redhat.com/browse/APPSRE-2193
replaces #1027
=> Improve terraform-vpc-peerings error handling to indicate that "awsInfrastructureAccess" may be missing when role is null

reconcile/openshift_users.py
in the past, dedicated-admin did not have permissions to manage users and groups (the reason this logic exists here).
we do now, so let's!
=> [openshift-users] run on v4 clusters

reconcile/gitlab_owners.py
to allow for self documented labels, same as we did for app-interface.
=> [gitlab-owners] change label to bot/approved

README.md, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocm_upgrade_scheduler.py, reconcile/queries.py, utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2638
this PR adds an integration to manage upgrade schedules for clusters via OCM.
example usage:
```
upgradePolicy:
schedule_type: automatic
schedule: '0 8 * * 2'
```
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10912
=> [ocm-upgrade-scheduler] introduce new integration

reconcile/openshift_base.py, utils/oc.py
fixes https://issues.redhat.com/browse/APPSRE-2631
this PR adds a handle to the case where the last-applied-configuration annotation is too long, in which case we should use `oc replace` instead of `oc apply`.
=> use oc replace when last-applied-configuration annotation is too long

reconcile/ocm_machine_pools.py, reconcile/ocm_upgrade_scheduler.py
this PR changes the ocm-machine-pools and ocm-upgrade-scheduler integrations to exit on empty input (no clusters).
=> ocm exit on empty output

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/jira_watcher.py
for better performance, this integration should run with as many shards as jira boards.
=> [jira-watcher] shard

reconcile/ocm_upgrade_scheduler.py, utils/ocm.py
manual ones will be added by users via the UI and will interfere with the integration for now.
=> [ocm-upgrade-scheduler] only get automatic upgrade policies

reconcile/terraform_resources.py
since if this is a dry-run we exit before checking openshift resources, there is no need to initiate them.
=> [terraform-resources] do not initiate oc_map on dry-run

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/jira_watcher.py
instead of using the local fs, we should use s3 state like most other integrations. this will prevent the loss of a state.
=> [jira-watcher] change from io-dir to s3 state

reconcile/openshift_base.py, utils/oc.py
fixes https://issues.redhat.com/browse/APPSRE-2660
this PR solves an issue with applying EgressNetworkPolicy, as this resource can not be applied, only replaced.
=> [openshift-resources] replace instead of apply on UnsupportedMediaType

utils/terrascript_client.py
since #1143, we no longer initiate oc_map in dry-run, this is bound to fail for a new DB (that it's password is not in the state yet).
=> [terraform-resources] rds determine password in dry-run without oc

utils/jsonnet.py, utils/oc.py
Instead of raise log the error on an unreachable cluster and move on to the next cluster after retries
=> Don't fail on unreachable cluster retry & move on

reconcile/openshift_resources_base.py
part of https://issues.redhat.com/browse/APPSRE-1838
this is to allow us to template an OAuth secret using the auth section of a cluster file.
=> openshift-resources add cluster.auth to query

dockerfiles/Dockerfile
this is temporary until libgcc, libgomp and libstdc++ in version 8.3.1-5.1.el8 are available in:
https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/Packages/g/
=> add temp fix for failing rpm packages

dockerfiles/Dockerfile
this is temporary until libgcc, libgomp and libstdc++ in version 8.3.1-5.1.el8 are available in:
https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/Packages/g/
=> temporary fix for gcc dependencies

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/ocp_release_ecr_mirror.py, reconcile/queries.py, setup.py, utils/aws_api.py, utils/oc.py, utils/ocm.py
Gets all the ocp-release images specified by all the ClusterImageSet on a given Hive cluster and copies them to the specified ECR mirror repositories.
App Interface Payload:
```
---
$schema: /dependencies/ocp-release-ecr-mirror-1.yml
hiveCluster:
$ref: /openshift/hivep01ue1/cluster.yml
ecrResourcesNamespace:
$ref: /services/app-interface/namespaces/app-interface-production.yml
ocpReleaseEcrIdentifier: ocp-release
ocpArtDevEcrIdentifier: ocp-art-dev
```
Debug log:
```
[2020-11-05 13:52:27] [INFO] [ocp_release_ecr_mirror.py:_run_mirror:144] - Image quay.io/openshift-release-dev/ocp-release:4.3.12-x86_64 already in the mirror. Skipping.
[2020-11-05 13:52:40] [INFO] [ocp_release_ecr_mirror.py:_run_mirror:148] - Mirroring quay.io/openshift-release-dev/ocp-release:4.3.13-x86_64 to …
```
=> [new integration] ocp-release-ecr-mirror

reconcile/terraform_resources.py, utils/terrascript_client.py
this PR adds an option to define `reset_password` on an rds provider, which will lead to the reset of the DB password.
this PR uses the terraform state.
=> [terraform-resources] reset db password #2

utils/terrascript_client.py
fixes https://issues.redhat.com/browse/APPSRE-2717
this small `continue` call causes the working_dirs to not get updated. this will lead to empty working_dirs, which will lead to the inability to get the existing state from terraform. this causes a password generation for all DBs in the account (since the oc_map fallback is not available since we are running in dry-run).
=> [terraform-resources] fix dry-run + print-only password generation issue

reconcile/queries.py, reconcile/sql_query.py
part of https://issues.redhat.com/browse/APPSRE-2715
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/11665
this PR adds support for recurring sql queries. if a `schedule` field exists in the sql-query object, the resource will be a `CronJob` instead of a `Job` and will not be deleted.
=> [sql-query] add support for CronJob

dockerfiles/hack/run-integration.py
This patch will drop the subprocess call from the main loop (used to run
the integrations on kubernetes) in favor of a direct call to the Click
entrypoint.
With that, both the Main lopp and the integration execution will happen
in the same Python session, meaning we can more data from the
integration executiuon in the Main loop.
This sets the foundation for instrumenting the integrations to  report
the reconciliation time or any other executions attributes we want to
track.
=> [APPSRE-2609] Main loop: drop subprocess

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/openshift_rolebindings.py
sharding was implemented for openshift-rolebindings in #932 and removed from use in #942.
in this PR we fix the issue we had with calculating the desired state (we rely on roles and permissions and were not filtering out roles for cluster/namespace not in the shard).
also splitting the integration to 4 shards (currently takes ~1k seconds to complete).
=> [openshift-rolebindings] fix shards

reconcile/gitlab_housekeeping.py
if `rebase` is false, we shouldn't continue if the MR is not rebased.
=> [gitlab-housekeeping] merge not rebased

dockerfiles/hack/run-integration.py
We are close, but there are still integrations not surviving to long sessions:
```
[openshift-resources] Error running qontract-reconcile: can't start new thread
```
Working on it, but meanwhile I want to unlock promotions to prod. Also, there are many changes already that can be promoted to prod if this change here is disabled.
Let's revert this until I have a bug-free version.
=> Revert main loop drop subprocess

utils/slack_api.py
retry `update_usergroup` to reduce flakiness such as:
https://ci.int.devshift.net/job/qontract-reconcile-timed-slack-usergroups/29169/console
=> [slack_api] retry update_usergroup

dockerfiles/hack/run-integration.py
Not such a great idea. Too much noise.
This reverts commit 704116187dbfe592c04d2bf2b9aecdb6c7f74326.
=> Revert "Conditionally make noise for SystemExit"

README.md, reconcile/ocm_clusters.py, utils/ocm.py
following https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/commit/ce4bd1ebfdb7af4221ad47c0430726bf0b25b24c
there is now support for quota and preflight checks in OCM. this PR adds usage of those in dry-run.
=> [ocm-clusters] add usage of dryRun

reconcile/service_dependencies.py
part of https://issues.redhat.com/browse/APPSRE-2727
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/12321
this will add a check that all apps that rely on kafka specify that in their dependencies.
=> [service-dependencies] add kafka dependency

utils/vault.py
This PR adds a cache to VaultClient, which will prevent getting the same data multiple times.
In openshift-resources alone, this saved ~1k of calls to Vault.
=> [VaultClient] add cache

reconcile/terraform_resources.py, utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-2755
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/12410
this PR adds terraform-resources support for kinesis streams based on:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_stream
it also creates a new function `get_tf_iam_service_user` which can be reused by other populate functions.
=> [terraform-resources] add support for kinesis streams

setup.py
depends on https://github.com/app-sre/sretoolbox/pull/25 and https://github.com/app-sre/sretoolbox/pull/26
=> bump sretoolbox to 0.9.2

reconcile/gitlab_housekeeping.py
part of https://issues.redhat.com/browse/APPSRE-2768
```
09:52:01 [2020-12-02 07:52:01] [INFO] [gitlab_housekeeping.py:merge_merge_requests:189] - ['merge', 'managed-services-api', 145]
09:52:01 Traceback (most recent call last):
09:52:02   File "/usr/local/lib/python3.6/site-packages/python_gitlab-1.11.0-py3.6.egg/gitlab/exceptions.py", line 259, in wrapped_f
09:52:02     return f(*args, **kwargs)
09:52:02   File "/usr/local/lib/python3.6/site-packages/python_gitlab-1.11.0-py3.6.egg/gitlab/v4/objects.py", line 2834, in merge
09:52:03     server_data = self.manager.gitlab.http_put(path, post_data=data, **kwargs)
09:52:03   File "/usr/local/lib/python3.6/site-packages/python_gitlab-1.11.0-py3.6.egg/gitlab/__init__.py", line 711, in http_put
09:52:03     **kwargs
09:52:04   File …
```
=> [gitlab-housekeeping] handle error in merge

dockerfiles/hack/run-integration.py
Before, when we were using subprocess, we would collect the subprocess
messages to STDOUT and log them using this module's logger.
Now, running integrations in the same session, the strategy is
different: we setup the root logger handlers and they will tackle
any messages generated.
=> [APPSRE-2772] Fix logging configuration

utils/oc.py, utils/saasherder.py
fixes #1214 
since we use OC in saasherder process_template to do `oc process`, we are initializing a "local" oc client (without an actual server). this PR will skip `get_version` if OC is initialized with `local=True`.
=> allow OC init to skip version

utils/oc.py
the openshift-groups integration thinks that an empty group does not exist.
instead of diving into it, adding a check if the group exists before creating it (which is good practice in any case).
=> [oc] create group if not exists

tools/qontract_cli.py, utils/ocm.py
Example output:
```
NAME               UPGRADE    UPGRADEPOLICY    SCHEDULE    NEXT_RUN
-----------------  ---------  ---------------  ----------  --------------------
REDACTED           batch0     automatic        0 7 * * *   2020-12-12T07:00:00Z
REDACTED           batch0     automatic        0 10 * * *  2020-12-12T10:00:00Z
REDACTED           batch0     automatic        0 8 * * *   2020-12-12T08:00:00Z
REDACTED           batch1     manual
REDACTED           batch1     manual
REDACTED           batch1     manual
REDACTED           batch1     manual
REDACTED           batch1     automatic        0 11 * * *  2020-12-12T11:00:00Z
REDACTED           batch1     manual
REDACTED           batch1     automatic        0 13 * * *  2020-12-12T13:00:00Z
REDACTED           batch1     manual
REDACTED …
```
=> adds next run to qontract-cli get cluster-upgrades

dockerfiles/Dockerfile
Installing skopeo has some mirror issues:
```
11:18:03 Downloading Packages:
11:18:04 [MIRROR] skopeo-1.2.0-12.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 12764780 but expected size is: 12746092
11:18:04 [MIRROR] containers-common-1.2.0-12.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 93400 but expected size is: 93392
11:18:05 [MIRROR] skopeo-1.2.0-12.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 12764780 but expected size is: 12746092
11:18:05 [MIRROR] containers-common-1.2.0-12.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 93400 but expected size is: 93392
11:18:05 [FAILED] containers-common-1.2.0-12.el8.x86_64.rpm: No more mirrors to try - All mirrors …
```
=> Dockerfile temp updated to fix skopeo install

reconcile/quay_mirror.py
```
[2020-12-16 09:45:33] [ERROR] [quay_mirror.py:process_repos_query:104] - Image docker://docker.io/library/eclipse-mosquitto:latest can't be mirrored to a public quay repository.
```
=> Don't mirror to public repos

utils/repo_owners.py
handle cases such as https://gitlab.cee.redhat.com/service/managed-services-api/-/blob/1bfbc4ebee12b7834c5074bd1d8d9a1d9378a36a/OWNERS#L16
```
approvers:
- a
- b
reviewers:
```
manifests in: https://ci.int.devshift.net/job/qontract-reconcile-timed-gitlab-owners/4068/console
=> [gitlab-owners] handle empty or malformed approvers/reviewers

utils/jjb_client.py
this PR will retry failures we have been seeing recently:
```
sys.exit(load_entry_point('reconcile==0.2.2', 'console_scripts', 'qontract-reconcile')())
File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1066, in invoke
return …
```
=> [jjb] retry lock cache

reconcile/slack_usergroups.py
this PR enables to pass a `url:ref` in `ownersFromRepos`.
part of https://issues.redhat.com/browse/APPSRE-2838
app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13264
=> [slack-usergroups] allow specifying a branch

reconcile/quay_mirror.py
quay-mirror can not get downstream repo's tag and keeping copying.
=> fix quay-mirror lack of credentials for downstream repo

reconcile/gitlab_owners.py, utils/gitlab_api.py
This Pull Requests introduces two main changes:
- Stale approval comments, created before the last update, are removed.
- Comments are now less verbose and in Markdown (instead of JSON). Example:
Then
```
{
"README.md": {
"approvers": [
"asegundo",
"jeder",
"jmelisba",
"kasingh"
],
"reviewers": [
"amoran",
"asegundo",
"jeder",
"jmelisba",
"kasingh",
"mafriedm"
]
},
"docs/addons_has_external_resources.md": {
"approvers": [
"asegundo",
"jeder",
"jmelisba",
"kasingh"
],
"reviewers": [
"amoran",
"asegundo",
"jeder",
"jmelisba",
"kasingh",
"mafriedm"
]
},
"addons/managed-api-service/metadata/stage/sku-limits.yaml.j2": {
"approvers": [
"cbrookes",
"dffrench",
"gryan",
"jcoleman",
"pamccart",
"pbrookes",
"ppaszki",
"sfrancog",
"trepel",
"weil"
],
"reviewers": [
"cbrookes",
"dffrench",
"gryan", …
```
=> [APPSRE-2765] gitlab-owners approval comment improvements

reconcile/openshift_resources_base.py
e.g. https://vault.devshift.net/ui/vault/secrets/insights/show/secrets/insights-stage/platform-docs-stage/service-credentials
=> fix base64 secret keep reconcile when contains newline

dockerfiles/Dockerfile, reconcile/cli.py, reconcile/prometheus_rules_validator.py, reconcile/queries.py, utils/promtool.py
Part of https://issues.redhat.com/browse/APPSRE-1146
It is debatable that this is actually an integration, as it will only
run on pr-check. But the code made sense here, as all the utils are here
and I would have needed to copy too much code elsewhere.
The complication here has been to be able to query qontract-server for
PrometheusRules. This has been done to just resolve the templates we
needed, reducing the run time (in my laptop) from 1m20 to 10s. Since
this is an integration that will run with every namespace change (see
app-interface related PR) and we're committed to reduce the PR check
time, this is important.
Related PRs:
* App-interface schema
* https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13366
* Add schema to resource in app-interface bundle
* …
=> Add prometheus-rules-validator integration

reconcile/jira_watcher.py, reconcile/queries.py
to allow adding jira boards as data without watching them
=> [jira-watcher] ignore jira boards without slack

reconcile/openshift_resources_base.py, utils/saasherder.py
this PR changes the way we process PrometheusRules.
if we want to allow deploying PrometheusRules from upstream repos, we need to be able to trace them back to their definition.
in this PR, we add a `html_url` annotation to PrometheusRule resources deployed by openshift-saas-deploy and by openshift-resources.
we can later use this annotation in our slack template for a quick navigation to the rule (for example)
=> add (and fix) html_url to PrometheusRule resources

utils/terrascript_client.py
this PR changes the way values are collected.
instead of pushing any value, we now avoid adding `None` to the values. In turn, we need to `.pop` with a `None` default value where needed.
this is required to upgrade to terraform 0.13, which fails if there are null values with unknown keys. for example, an rds instance can not be created if it contains an `es_identifier` key.
this PR alone should cause no changes to the integration.
=> [terrascript_client] push and pop

utils/terraform_client.py, utils/terrascript_client.py
this PR adds terrraform 0.13 compliant outputs (no `.`, `[`, `]`) which will eventually replace the current outputs.
we need the outputs to exist in parallel to be able to start using the new outputs and only remove the old ones before migrating to terraform 0.13.
=> [terraform] add 0.13 compliant outputs

utils/terraform_client.py, utils/terrascript_client.py
following up on #1271, where we added 0.13 compliant outputs, we now need to consume them and remove the 0.11 compliant outputs.
this PR should be promoted to production only after #1271 is already promoted itself (and had a chance to create the 0.13 compliant outputs before we remove the 0.11 ones):
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13448
=> [terraform] use 0.13 outputs and remove 0.11 outputs

reconcile/cli.py, reconcile/terraform_resources.py
this PR will prevent terraform integrations from deleting resources. this is a safety net for the duration of the terraform 0.13 upgrade and this PR should be reverted once we gained confidence.
=> add safety nets to terraform integrations

utils/terrascript_client.py
in order to upgrade to terraform 0.13.5, we need provider names to be valid names (start with a letter or an underscore and contain only letters/numbers/dashes). the current name is the aws account uid.
=> [terraform-vpc-peerings] change provider aliases

utils/terraform_client.py
related to https://issues.redhat.com/browse/APPSRE-2269
this PR will make terraform integrations consume outputs in the 0.13 format (required for removing the old ones).
=> terraform fix populate_desired_state to match 0.13 outputs

utils/lean_terraform_client.py, utils/terraform_client.py
there are cases where `terraform show` claims that:
```
Saved plan is stale
The given plan file can no longer be applied because the state was changed by
another operation after the plan was created.
```
let's retry the plan phase to see if it helps.
=> retry terraform plan

utils/terrascript_client.py
would this fix the following error?
```
Error: Error creating Cloudwatch log subscription filter: InvalidParameterException: Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
```
based on https://forums.aws.amazon.com/thread.jspa?threadID=310484
=> [terraform-resources] lambda permission fix

reconcile/openshift_base.py
This improves the log messages when we're validating desired state to give more info to the end users:
* Deployment/DeploymentConfig: tell the user how many replicas are ready vs total desired
* Subscription: tell the user what the actual state is
* Job: tell the user what the conditions are (currently dumped as-is to simplify code)
* ClowApp: tell the user how many deployments are ready vs. total managed
=> Improve logs returned when validating desired state

dockerfiles/Dockerfile
There seems to be checksum issues coming from the header when using DNF.  
This will check for the package nvr and then we can install with `rpm -vi` instead
=> find skopeo package and install with rpm

reconcile/cli.py
following #1275, this PR is enabling terraform-users to delete resources.
=> [terraform-users] enable deletion by default

reconcile/utils/sentry_client.py, setup.py
as we grew larger in numbers, some calls now do not return all results and include a `link` header in the response indicating of more pages.
this PR adds usage of these pages to return the complete response (if pages exist, the response is a list of items).
=> [sentry-config] add pagination

reconcile/sql_query.py
avoid a warning `tar: Removing leading / from member names` which may make the user think the command failed
=> Removing leading /

reconcile/utils/vault.py
should fix the following errors:
```
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/openshift_resources_base.py", line 189, in lookup_vault_secret
vault_client = VaultClient()
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/vault.py", line 189, in __new__
if not cls._instance._client.is_authenticated():
File "/usr/local/lib/python3.6/site-packages/hvac-0.7.2-py3.6.egg/hvac/v1/__init__.py", line 529, in is_authenticated
self.lookup_token()
File "/usr/local/lib/python3.6/site-packages/hvac-0.7.2-py3.6.egg/hvac/v1/__init__.py", line 377, in lookup_token
return self._adapter.get(path, wrap_ttl=wrap_ttl).json()
File "/usr/local/lib/python3.6/site-packages/hvac-0.7.2-py3.6.egg/hvac/adapter …
```
=> [VaultClient] try-except is_authenticated

reconcile/utils/lean_terraform_client.py
just so it's easier to read in integration logs
=> [lean_terraform_client\show] no color and log account name

reconcile/quay_mirror.py
The official images can't be mirrored to a public repository. We already
skip them. Let's also fail the integration so that case is caught on MRs
to app-interface.
=> quay-mirror: exit with error on official images made public

reconcile/utils/saasherder.py
fixes #1323
```
Original Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/threaded.py", line 10, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/saasherder.py", line 611, in populate_desired_state_saas_file
self._process_template(process_template_options)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/saasherder.py", line 393, in _process_template
target_promotion['commit_sha'] = commit_sha
TypeError: 'NoneType' object does not support item assignment
```
=> target_promotion init to dict if None

reconcile/queries.py, reconcile/terraform_resources.py, reconcile/utils/terraform_client.py
We can't set the username/password for a RDS replica in terraform, but
we still want them in the OpenShift Secret. For that, we find the
username/password from the replica_source in the terraform output and
copy them to the replica Secret data.
=> Getting credentials from the replica_source for the replica Secret

reconcile/cli.py, reconcile/dashdotdb_dvo.py
o added chunking of prom data blob into dddb for dvo into optionally configurable size (default: 20 metric/value pairs per post)
o added parameter to run dvo sync for single cluster
=> support slow receiver timeouts for dashdotdb in dvo

reconcile/cli.py, reconcile/openshift_saas_deploy.py, reconcile/openshift_saas_deploy_wrapper.py, reconcile/queries.py, reconcile/utils/mr/auto_promoter.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-2244
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13902
this PR adds support for automated promotions for saas file targets defining `auto: true` in the `promotion` section.
this works by sending messages to the SQS gateway to promote a change and consumed by the MR consumer integration.
=> [openshift-saas-deploy] add support for automated promotions

reconcile/utils/sqs_gateway.py
fixes #1327
this will avoid deployment jobs from initiating tokens for all AWS accounts, and only do it for the AWS account with the MR submitter queue.
fixes https://ci.ext.devshift.net/view/github-mirror/job/openshift-saas-deploy-saas-github-mirror-test-App-SRE-stage/25/console
=> [SQSGateway] only initiate submitter queue account

reconcile/test/fixtures/openshift_resource/invalid_resource_container_name_format.yml, reconcile/test/fixtures/openshift_resource/invalid_resource_container_name_too_long.yml, reconcile/test/fixtures/openshift_resource/invalid_resource_name_format.yml, reconcile/test/fixtures/openshift_resource/invalid_resource_name_too_long.yml, reconcile/test/test_openshift_resource.py, reconcile/utils/openshift_resource.py
This PR adds validation for container names in OpenshiftResource. Corresponding tests have also been added.
This also extracts the DNS-1123 based regexes as global variables so they can be reused elsewhere in the future.
I have also changed the error messages slightly for clarity and added a link to the kubernetes docs on object naming
=> Validate container names against DNS-1123 in OpenshiftResource

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
Ensure DDDB crons don't run multiple of the same job concurrently and add additional success/fail pod history to dddb-dvo job
=> Fix dddb crons

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
even if it fails, it succeeds on the next run (been that way for over a year).
=> [aws-garbage-collector] don't keep failed history

dockerfiles/Dockerfile, reconcile/openshift_resources_base.py, reconcile/utils/amtool.py
This is done via a `validate_alertmanager_config` option in openshift
resources. In this way we don't have to write a new integration that
resolves templates we are already resolving.
Closes [APPSRE-2419](https://issues.redhat.com/browse/APPSRE-2419)
Needs https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/14174
=> Add validation to alertmanager config

reconcile/cli.py
The `amtool` binary is required by the `openshift-resources` integration to validate PrometheusRules
=> add amtool binary req. for openshift_resources

reconcile/queries.py, reconcile/utils/terrascript_client.py
Removed references to vault secret for the `aws_provider_version` to `providerVersion` in the account config. 
Updates for `providerVersion` have already been made on the app-interface side and merged.
=> get providerVersion from account schema and not vault

reconcile/utils/vault.py
- Properly raise vault access forbidden errors (with useful message)
- Refactor the naive try/except for falling back to KV_1 if KV_2 failed into a proper detection of the KV version 
This will hopefuully solve most of the very lengthy stack traces we've been getting in the logs which were caused by bad secrets and/or permission denied. With this we should be able to spot and fit these more easily
=> Improved detection of Vault KV version and better handling of Forbidden errors

reconcile/utils/slack_api.py
fixes:
```
16:25:40 Traceback (most recent call last):
16:25:40   File "/usr/local/bin/qontract-reconcile", line 33, in <module>
16:25:40     sys.exit(load_entry_point('reconcile==0.2.2', 'console_scripts', 'qontract-reconcile')())
16:25:40   File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 829, in __call__
16:25:40     return self.main(*args, **kwargs)
16:25:40   File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 782, in main
16:25:40     rv = self.invoke(ctx)
16:25:40   File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1259, in invoke
16:25:40     return _process_result(sub_ctx.command.invoke(sub_ctx))
16:25:40   File …
```
=> [slack-usergroups] handle usergroup without users

reconcile/slack_usergroups.py
now that it seems that slack supports empty usergroups via the API, we can allow for empty PagerDuty targets to be defined (an escalation policy or a schedule with no one in it). this _should_ lead to an empty slack usergroup.
related to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13802
=> [slack-usergroups] handle empty pagerduty targets

reconcile/utils/slack_api.py
part of https://issues.redhat.com/browse/APPSRE-2949
we found out that if you pass a deleted user to a usergroup, it can be emptied out.
this will allow us to support usergroups which are not active 24/7.
=> [slack-usergroups] add support for empty usergroups

reconcile/utils/saasherder.py
related to https://issues.redhat.com/browse/APPSRE-2959
upstream issue: https://github.com/PyGithub/PyGithub/issues/661
this PR adds a handle to errors caused by files with a size of over 1MB. the new code can handle files up to 100MB, which i doubt we'll ever reach in text files.
=> [openshift-saas-deploy] add github large file handler

reconcile/cli.py, reconcile/utils/binary.py
- Add `binary_version` decorator
- Add `binary_version` decorator to all `cli.py` commands that uses `terraform` or `oc`
Solves APPSRE-2932 and should help with APPSRE-2724
=> Add decorator for ensuring specific binary versions are available

dockerfiles/hack/run-integration.py, reconcile/cli.py
Using the same format we have in the cli. Current format without dates makes difficult to debug stuff in pods stdout.
=> Useful stdout logging in run-integration

reconcile/openshift_base.py, reconcile/openshift_resources_base.py, reconcile/terraform_resources.py, reconcile/utils/openshift_resource.py
related to https://issues.redhat.com/browse/APPSRE-2942
we have recently added an ability to check if a cluster is reachable and skip it if it isn't: #1214
one scenario that is not covered by this PR is a cluster starting to be unreachable during an integration (and not in the beginning like covered by #1214). In this scenario as things stand, we will try to reconcile all resources that failed to be fetched:
```
(venv) (master) $ git diff
diff --git a/reconcile/openshift_resources_base.py b/reconcile/openshift_resources_base.py
index 9600245..f8295ee 100644
--- a/reconcile/openshift_resources_base.py
+++ b/reconcile/openshift_resources_base.py
@@ -593,6 +593,7 @@ def fetch_desired_state(oc, ri, cluster, namespace, resource, parent):
def fetch_states(spec, ri):
try:
if spec.type == …
```
=> prevent openshift integrations from reconciling errored clusters

reconcile/utils/ocm.py
following https://issues.redhat.com/browse/SDA-3297, we can now update cluster channel through the API.
the API will soon change to PATCH `version.channel_group` instead of `upgrade_channel_group`, but that's WIP
=> [ocm-clusters] allow to change cluster channel group

reconcile/utils/sentry_client.py, reconcile/utils/vault.py
This issue implements the changes from: https://issues.redhat.com/browse/APPSRE-2866
We figured, that this pattern:
```python
class Foo:
__init__(self):
self._cache = {}
get_something(self):
cache_key = 'something'
cached = self._cache.get(cache_key)
if cached is not None:
return cached
fresh = do_expensive_operation_to_get_something()
self._cache[cache_key] = fresh
```
can be expressed in a simpler way using [@functools.lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache):
```python
import functools
class Foo:
@functools.lru_cache()
get_something(self):
return do_expensive_operation_to_get_something()
@functools.lru_cache()
get_something_by_id(self, id):
return do_expensive_operation_to_get_something_by_id(id)
update_something(self): …
```
=> move self-implemented caches to functools.lru_cache

reconcile/utils/oc.py
fixes:
```
[openshift-namespaces] Error running qontract-reconcile: [REDACTED]: Error from server (AlreadyExists): project.project.openshift.io "REDACTED" already exists
[openshift-namespaces] Traceback (most recent call last):
[openshift-namespaces]   File "/run-integration.py", line 69, in <module>
[openshift-namespaces]     integration.invoke(ctx)
[openshift-namespaces]   File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1259, in invoke
[openshift-namespaces]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[openshift-namespaces]   File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1066, in invoke
[openshift-namespaces]     return ctx.invoke(self.callback, **ctx.params)
[openshift-namespaces]   File …
```
=> [openshift-namespaces] do not fail if namespace exists

reconcile/sentry_config.py
sentry-config fails often for being forbidden to access secrets in vault.
this is likely due to the sequential execution of the integration.
there are 3 options to handle this:
1. extend token lifetime
2. read all secrets before execution
3. parallelize the execution
i chose 2 to not change the token lifetime (undesired) and to not change the resource consumption of the integration.
if we ever choose to measure SLOs for sentry-config, we'll probably want to go with 3.
=> [sentry-config] read all secrets before execution

reconcile/utils/oc.py
OC.apply can only deal with unserialized obj due to https://github.com/app-sre/qontract-reconcile/pull/1382
cc @rporres 
=> fix recycle_pods

.pylintrc, reconcile/terraform_aws_route53.py
[`ts.populate_route53`](https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/utils/terrascript_client.py#L370-L421) has no explicit return, so no need to check for it.
=> [APPSRE-3917] pylint assignment-from-no-return

reconcile/utils/smtp_client.py
we have been recently seeing errors with the SMTP client. any such issue is causing the following integrations to fail:
- email-sender
- requests-sender
- sql-query
- terraform-users
- sentry-helper
the integrations are failing to initiate the SMTP client, which is happening on every iteration, even if there are no changes to be made (most of the time). the client should only be initialized when it's needed (to send a mail).
this PR changes the smtp client to a property (also adding consistency to `server`) which means it will only initialize the client when it's needed and not as part of a class instantiation.
=> [smtp] lazy client init

reconcile/utils/promtool.py
a minor fix for #1399 
the change moved the promtool check out of the scope of the temp file context manager, leading to the removal of the temporary file before the execution of `promtool check`.
=> [promtool] fix temporary file scope

reconcile/saas_file_owners.py
related to https://issues.redhat.com/browse/APPSRE-3072
the current behavior will not remove the hold label if there isn't a valid lgtm. this isn't the right behavior, and the hold label should be removed if it's cancelled.
=> [saas-file-owners] remove hold label when hold is cancelled

reconcile/utils/binary.py
it didn't help me install promtool, but it does help with all other commands.
=> [binary check] add command-not-found hint

reconcile/status.py
one of our e2e tests is `create_namespace` which creates a namespace on each cluster that we manage and verifies that it is created according to a predefined template.
this test has been failing:
```
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/threaded.py", line 10, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/e2e_tests/create_namespace.py", line 29, in test_cluster
oc.delete_project(ns_under_test)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/oc.py", line 116, in wrapper
integration=running_state.integration
AttributeError: 'RunningState' object has no attribute 'integration'
```
e2e tests should not be …
=> [RunningState] Default value for attributes not explicetly created is None

reconcile/utils/jenkins_api.py
Jira link: https://issues.redhat.com/browse/APPSRE-2954
Issue: Visual-qontract is displaying only the last 100 build histories in a month, instead of all. 
Report example: https://visual-app-interface.devshift.net/reports#/reports/app-interface/2021-02-01.yml 
Proposed solution: According to the [jenkens api doc](https://ci.ext.devshift.net/job/openshift-assisted-service-gh-build-master/api/), we should change the url pattern from `url = f"{self.url}/job/{job_name}/api/json?tree=builds[timestamp,result]` to `url = f"{self.url}/job/{job_name}/api/json?tree=allBuilds[timestamp,result]"` in order to get all builds. 
Jenkins example:
https://ci.ext.devshift.net/job/openshift-assisted-service-gh-build-master/api/json?tree=builds[timestamp,result] …
=> [App-interface-reporter] Get all builds 

reconcile/sentry_config.py
When a user belong to more than one role that grants access to the same sentry team, the integration will keep trying to reconcile the state while showing the following log
```
[sentry-config] ['team_membership', 'example@redhat.com', 'my-sentry-project,my-sentry-project', 'https://sentry.example.com']
```
Upon investigation, the above user was in fact member of multiple roles that granted access to the `my-sentry-project` sentry project.
While this may seem odd, I believe it is a very valid case when two different roles might grants different permission and access to one common sentry project. The alternative to this fix would be to ask the users to split out the roles into more roles, but I think this may lead to a more cumbersome experience to users.
This change ensures that a team is …
=> sentry-config: prevent a user from being in the same team twice

reconcile/utils/ocm.py
follows up on #1372, based on https://source.redhat.com/groups/public/service-delivery/service_delivery_blog/switching_clusters_channel_group
=> [ocm-clusters] update update channel_group api endpoint

reconcile/utils/gql.py
related to https://issues.redhat.com/browse/APPSRE-3084
there may be cases where the active sha in one pod is different from another pod, which may lead to inconsistencies in data fetched. adding a retry to this function eventually makes sure that we are using a matching sha and git commit info (even if those were queried between different qontract-server pods).
we also add a `max_attempts` of 5 to allow time for s3-reload to reload data. the default is: https://github.com/app-sre/csnotify/blob/a3522611b4d05c63525529b2a522977fc5aa3478/s3-watcher.go#L105
=> [gql] retry init from config

reconcile/utils/slack_api.py
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api
`channels.list` is Replaced by: `conversations.list` since today
=> fix slack api deprecated channels

reconcile/utils/vault.py
following #1348, we now know what secrets are forbidden.
those secrets are usually not really forbidden, and my suspicion is that we are hitting the SA token limit. this makes sense since we recently moved to a singleton vault client, which means we are using the token without refreshing it.
this PR adds a refresh every time we find a secret forbidden and we find that the client is not authenticated.
=> [vault] reauthenticate on missing data if not authenticated

reconcile/utils/gql.py, reconcile/utils/qontract_server_client.py, reconcile/utils/test/test_qontract_server_client.py, setup.py, tox.ini
The goal of this PR is to enable session reusage in the graphql queries.
We were using the [GraphQLClient](https://pypi.org/project/graphqlclient/), but the codebase seems abandoned, and it doesn't support reusing sessions, so this PR has replaced the external `GraphQLClient` with an internal `QontractServerClient`.
It's important to note that the session will be regenerated every time we `init` again, which is good, because the [run-integration.py](https://github.com/jmelis/qontract-reconcile/blob/sticky-sessions/dockerfiles/hack/run-integration.py#L69) script will reinitialize every time. This has been tested (although manually, no automated tests for this).
=> Sticky sessions

reconcile/utils/ocm.py
the `name` is prefixed with `addon-`, and i think we'd prefer to use the `id`.
related to:
- https://issues.redhat.com/browse/APPSRE-2865
- https://issues.redhat.com/browse/APPSRE-2697
=> [ocm] get_addon by id instead of by name

reconcile/queries.py, reconcile/terraform_aws_route53.py, reconcile/terraform_resources.py, reconcile/terraform_users.py, reconcile/terraform_vpc_peerings.py, reconcile/utils/terraform_client.py
part of https://issues.redhat.com/browse/APPSRE-2936
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/15710
this PR will allow deleting resources in terraform integrations from aws accountss where `enableDeletion` is true.
there is a cli argument that can be passed to terraform integrations called `--enable-deletion`. this PR will enable deleting resources even if the default for enable deletion for the entire integration is false.
tl;dr - what we define on an aws account file is stronger.
=> terraform enable deletion per account

reconcile/openshift_users.py
fixes:
```
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/threaded.py", line 10, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/openshift_users.py", line 20, in get_cluster_users
users = [u['metadata']['name'] for u in oc.get_users()
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/openshift_users.py", line 21, in <listcomp>
if len(u['identities']) == 1
TypeError: object of type 'NoneType' has no len()
During handling of the above exception, another exception occurred:
sys.exit(load_entry_point('reconcile==0.2.2', …
```
=> [openshift-users] allow users without identities

reconcile/slack_usergroups.py
due to the way we collect slack user groups (per role, per user) we are not taking into account that the same slack usergroup can be referenced from multiple roles. this leads to people being added and removed from such defined groups.
this PR takes into account that a previous item referencing the same slack usergroup was already added to the desired state. if such item is found, we append the additional users into it instead of adding a new item to the desired state.
=> [slack-usergroups] allow usergroup permission to be defined from multiple roles

tools/app_interface_reporter.py
Jira: https://issues.redhat.com/browse/APPSRE-2954
Issue: Although we are trying to collect[ both saas_deploy and promote-to-prod](https://github.com/app-sre/qontract-reconcile/blob/master/tools/app_interface_reporter.py#L421), saas-deploy jobs are [ignored](https://github.com/app-sre/qontract-reconcile/blob/11dd2f09566a430a6bba0b3d62312a493c631c61/reconcile/utils/jjb_client.py#L347) in jjb_client. saas_deploy and promote-to-prod have different ways to fetch jenkins history. Also, each saas file/ promotion job might have multiple environments and thus multiple job names {saas_file_name}-{env_name}. However, the key is [repo url of a job](https://github.com/app-sre/qontract-reconcile/blob/86753c4f5bb545e1c2a4053278a76e105775ca08/tools/app_interface_reporter.py#L582) and multiple job names …
=> [App-interface-reporter] Remove production promotions, add saas-deploy

reconcile/utils/openshift_resource.py
same as https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/utils/openshift_resource.py#L77-L79
```
[2021-03-09 19:26:19] [INFO] [openshift_base.py:apply:206] - ['apply', 'telemeter-prod-01', 'telemeter-production', 'ServiceAccount', 'prometheus-telemeter']
[2021-03-09 19:26:19] [INFO] [openshift_base.py:apply:206] - ['apply', 'app-sre-prod-04', 'uhc-production', 'ServiceAccount', 'clusters-service']
[2021-03-09 19:26:19] [INFO] [openshift_base.py:apply:206] - ['apply', 'app-sre-prod-04', 'uhc-production', 'ServiceAccount', 'account-manager']
[2021-03-09 19:26:19] [INFO] [openshift_base.py:apply:206] - ['apply', 'app-sre-prod-04', 'uhc-production', 'ServiceAccount', 'ocm-service-log']
[2021-03-09 19:26:20] [INFO] [openshift_base.py:apply:206] - ['apply', …
```
=> add imagePullSecrets for sha256sum

reconcile/utils/vault.py
following #1414, we saw a major decrease in authentication errors. we do see them from time to time still, but they have reduced a lot.
in this PR, we add a retry in case where we get access forbidden for a v1 secret, which is most of what we are currently seeing. this should reduce the noise completely!
=> [vault] retry reading secret when access is forbidden

tools/app_interface_reporter.py
Jira: https://issues.redhat.com/browse/APPSRE-2954
Issue: Currently merges_to_master only collects activities in master branch, while it is also possible to have activities in main, tag, etc. 
Example (`merge_activities` is not null):
```
$schema: /app-sre/report-1.yml
labels:
app: quayio
name: quayio-2021-03-12
app:
$ref: /services/quayio/app.yml
date: '2021-03-12'
contentFormatVersion: 1.0.0
content: |
promotions:
quay-production-standby:
total: 1
success: 1
merge_activities:
https://github.com/quay/quay:
- branch: master
total: 1
success: 0
https://github.com/app-sre/syslog-cloudwatch-bridge:
- branch: master
total: 1
success: 1
https://github.com/quay/clair:
- branch: master
total: 10
success: 10
https://github.com/coreos-inc/apostille:
- branch: master
total: 1
success: 0 …
```
=> [App Interface Reporter] Collect info for multi env merge activities 

reconcile/queries.py, reconcile/terraform_vpc_peerings.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3133
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/15769
this PR adds logic to create VPC peerings between a cluster and all VPCs (or tagged VPCs) in an AWS account - VPC mesh.
the PR does not change the logic of how we create VPC peerings, but only adds logic to the collection phase - where we now take into consideration a new provider - `account-vpc-mesh`.
=> [terraform-vpc-peerings] add support for VPC mesh (PrivateLink)

reconcile/ocp_release_ecr_mirror.py
we are currently mirroring all images.
Let's avoid some mirroring:
- if a CIS is disabled
- if a CIS is not in the stable channel
future work should include actually performing a reconciliation and not just mirroring, but this is an easy start.
Just with these changes we reduce the number of unique mirrored releases from 141 to 17.
=> [ocp-release-ecr-mirror] only mirror stable+enabled ClusterImageSets

reconcile/ocm_aws_infrastructure_access.py, reconcile/utils/ocm.py, tools/qontract_cli.py
a utility function to get a list of all the switch role links from the OCM console for all our clusters.
related to https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/FAQ.md#get-access-to-cluster-logs-via-log-forwarding
=> [qontract-cli] add get command for aws infrastructure access switch role links

reconcile/ocm_clusters.py, reconcile/utils/ocm.py
querying for each cluster's provision shard is time consuming and only required for the ocm-clusters integration.
=> [ocm] skip provision shards mapping

reconcile/utils/vault.py
this PR adds a retry to vault's write function like we did for the read function. it also adds a handle in case the token needs to be refreshed (otherwise we will never be able to write output secrets)
=> [vault] retry write

reconcile/utils/dnsutils.py, setup.py, tools/qontract_cli.py
The `aws-route53-zones` command is used to list information about DNS zones that are managed in app-interface.
Other than listing the zone name and number of records, it also uses the `dnspython` package to query the nameservers (NS) and return them. This is useful for tenants who are looking for their nameservers to use after adding a new zone to app-interface.
I went with a simple DNS query rather than somehow looking at the terraform state or doing AWS API calls. DNS queries should work just fine and don't require extra privileges
I also added a small change to handle lists in table cells. tabular supports multiline cells natively for some table formats but does not have support for github-flavored markdown multiline cells, hence the addition of `<br>` tags when that format is used
The …
=> [qontract-cli] add aws-route53-zones command

reconcile/openshift_resources_base.py
this PR adds a retry around a method to fetch a secret from vault which often fails. this is probably a problem with vault, but as consumers we just want to retry.
```
error processing jinja2 template: error fetching vault secret: local node not active but active cluster node not found
Original Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/openshift_resources_base.py", line 187, in lookup_vault_secret
vault_client = VaultClient()
File "/usr/local/lib/python3.6/site-packages/reconcile-0.2.2-py3.6.egg/reconcile/utils/vault.py", line 251, in __new__
is_authenticated = cls._instance._client.is_authenticated()
File "/usr/local/lib/python3.6/site-packages/hvac-0.7.2-py3.6.egg/hvac/v1/__init__.py", line 529, in …
```
=> retry lookup_vault_secret

tools/app_interface_reporter.py
Jira: https://issues.redhat.com/browse/APPSRE-2955
Example usage:
```
app-interface-reporter --config config.reporter.toml --log-level INFO --reports-path throughput --dry-run 
```
Dashdotdb pr: https://github.com/app-sre/dashdotdb/pull/39
If running dashdotdb locally =>
```
dashdotdb_url = "http://localhost:8080/"
dashdotdb_user = "postgres"
dashdotdb_pass = "postgres"
```
Report Example (`service_slo` not null):
```
$schema: /app-sre/report-1.yml
labels:
app: Cincinnati
name: Cincinnati-2021-03-26
app:
$ref: /services/cincinnati/app.yml
date: '2021-03-26'
contentFormatVersion: 1.0.0
content: |
promotions:
saas-cincinnati:
- env: osd-stage
cluster: app-sre-stage-01
namespace: cincinnati-stage
total: 7
success: 5
- env: osd-production
cluster: app-sre-prod-04
namespace: …
```
=> [App Interface Reporter] Add Service SLO Metrics

reconcile/terraform_aws_route53.py, reconcile/utils/dnsutils.py
Currently if someone uses `_target_cluster` on a `A` record the integration will happily take it but terraform will fail to apply because a hostname is not valid for an `A` record.
Furthermore, we have users that desire pointing the apex of their zone to a cluster. Since `CNAME` is not permitted at the zone apex, an `A` record have to be used.
This change handles using `_target_cluster` for `A` records by resolving the `_target_cluster`'s `elbFQDN` host and then it uses the IPs as targets for the `A` record. If the ELB IPs were to change, the integration would pick up the changes and update the zone accordingly.
This also add a safeguard for when no values are set or discovered so we don't and up configuring a record with no values
=> add support for _target_cluster for A records

reconcile/terraform_aws_route53.py
This fixes an issue where a record may point to a cluster (via `_target_cluster`) but the cluster `elbFQDN` value is an empty string
=> terraform-route53: ensure elbFQDN is set and not an empty string

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py, setup.py
since public ecr repositories are now available in terraform, we can provision them.
the dependency is implementation in terrascript, which should be followed up  in https://github.com/mjuenema/python-terrascript/issues/160.
EDIT: i believe i found a hack that allows us to create aws_ecrpublic_repository resources without upgrading terrascript (added comments in the code).
terraform docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecrpublic_repository
schema changes: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/16919
=> [terraform-resources] add support for public repositories

dockerfiles/Dockerfile
depends on https://github.com/app-sre/container-images/pull/14
=> update qontract-reconcile-base image to 0.2.1 to include terraform aws provider 3.30.0

reconcile/queries.py, reconcile/terraform_tgw_attachments.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3150
this PR adds support for managing routes in the VPC's route tables (in the cluster's aws account).
the cidr block comes from app-interface and is not known at run time.
=> [terraform-tgw-attachments] add support for routes

README.md
Previously this was rendering as a file path.
=> Trivial: Fix email address in README.md

reconcile/utils/terrascript_client.py
=> Don't set the availability zone for an RDS instance if that instance

reconcile/github_owners.py
in case a github username has capital letters, the integration keeps trying to add the user as an owner.
this PR makes the compare logic set the username to lower first.
=> [github-owners] make integration not case sensitive

reconcile/queries.py, reconcile/utils/saasherder.py
Previously some consumers were using `IMAGE_TAG` as only *part* of the actual image tag referenced by a saas template, e.g.:
`  image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}`
This was clearly wrong and misleading.
With this change, if the saas file/template specifies the parameter:
`  USE_CHANNEL_IN_IMAGE_TAG: "true"` (note: `"true"`, not `true`)
...then we will calculate the value of `IMAGE_TAG` to include the channel; so the above example can be changed to:
`  image: ${REGISTRY_IMG}:${IMAGE_TAG}`
This also makes it possible for `REPO_DIGEST` to be used by such consumers. They would specify:
```
parameters:
- name: REGISTRY_IMG
required: true
- name: CHANNEL
required: true
- name: USE_CHANNEL_IN_IMAGE_TAG
value: "true"
- name: IMAGE_TAG
required: true
- name: REPO_DIGEST
required: true …
```
=> APPSRE-3207: Support `use_channel_in_image_tag`

reconcile/utils/terrascript_client.py
domain_name and subject_alternative_names should be set as variables
Was needed for #1491
=> terrascript_client: update variable keys

reconcile/quay_base.py, reconcile/quay_membership.py, reconcile/quay_mirror.py, reconcile/quay_permissions.py, reconcile/quay_repos.py, reconcile/queries.py, reconcile/service_dependencies.py, reconcile/test/fixtures/quay_membership/desired_state_simple.yml, reconcile/test/fixtures/quay_repos/current_state_simple.yml, reconcile/test/fixtures/quay_repos/desired_state_simple.yml, reconcile/utils/quay_api.py
Depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17290
The `instance { url }` section is now mandatory for all quay_orgs (and `serverUrl` was never used). We will always pass the full api_url to the contructor.
=> APPSRE-3225: support multiple quays

reconcile/openshift_base.py, reconcile/utils/oc.py
The case we're specifically addressing here is making a Service
headless. We need to set the clusterIP to either None or "" (empty).
Kubernetes doesn't allow for clusterIP to be unset or modified, hence we
need to delete the Service and recreate it again.
=> More immutable-type errors

reconcile/ocm_aws_infrastructure_access.py, reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3234
this PR adds the option to define `aws_infrastructure_access` for an IAM service account created with terraform-resources.
this is to allow such users the network-mgmt role via the AWS infrastructure access feature of OCM.
this is done to enable Hive to access it's own cluster's AWS account to perform PrivateLink related operations (https://github.com/openshift/aws-account-operator/pull/539).
the final result of all this is that the IAM user created by terraform-resources will be granted AWS infrastructure access through ocm-aws-infrastructure-access. once that access is granted, a `role_arn` key will be added to the output Secret created by terraform-resources, as required for section (3) of …
=> [terraform-resources] Allow AWS IAM service accounts access to cluster's AWS infrastructure via OCM

reconcile/terraform_resources.py
we currently write all output secrets on every iteration of the integrations.
with this PR, we will skip it in case no resources were applied. this should speed up the integrations significantly.
=> [terraform-resources] don't write to vault if no resources were applied

reconcile/quay_base.py, reconcile/quay_repos.py, reconcile/test/fixtures/quay_repos/current_state_simple.yml, reconcile/test/test_quay_repos.py
The `managedRepos` is an option of interest for the quay-repos
integration.
Instead of changing the behaviour of the `get_quay_api_store()` acording
to the integration using it, let' s just make sure it ships enough
information so the quay-repos integration knows what to do.
Then, in the quay-repos intregration, we test the `managedRepos` in the
`fetch_current_state()`, the same way we do for the `fetch_desired_state()`.
=> Move the managedRepos processing to where we need it

setup.py
promotes sretoolbox to version 0.13.0, which includes https://github.com/app-sre/sretoolbox/pull/35
=> promote sretoolbox

reconcile/utils/saasherder.py
When an Image is not found, `promotion` returns as None, which we do not handle.
This PR changes the behavior to skip validating a `None` promotion. The integration will still exit with an error code and the promotion itself will be published as failed (unable to promote to it, as expected).
=> [openshift-saas-deploy] skip empty promotion

reconcile/saas_file_owners.py
since `use_channel_in_image_tag` was introduced as a new top-level section of a saas file, we need to explicitly add it to the logic of comparing if there were changes to a saas file. this is done so we do a dry-run of a deployment in the MR adding usage of `use_channel_in_image_tag`.
the dry-run deployment did not run for MRs such as https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17951, which causes the tests to pass, despite having issues (now fixed).
=> [saas-file-owners] consider use_channel_in_image_tag as a diff

reconcile/utils/openshift_resource.py
since this annotation is added automatically, our integrations think that they need to reconcile OperatorGroup.
=> openshift compare logic for OperatorGroup

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/kafka_clusters.py, reconcile/queries.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-2728
for a consumer to use a cluster, they need a service account. this PR adds support for creating a service account per cluster (with the cluster name being the service account name) and returns the credentials for that service account in the output Secret to be consumed by applications.
=> [kafka-clusters] add support for multi_az and service accounts

reconcile/openshift_resources_base.py
This fix will avoid the possible consequences of mutating the default arguments if none are passed. Instead if no such arguments are passed, an empty dict is created.
> severity:error rule:python.lang.correctness.common-mistakes.default-mutable-dict.default-mutable-dict: Function process_jinja2_template mutates default dict vars. Python only instantiates default function arguments once and shares the instance across the function calls. If the default function argument is mutated, that will modify the instance used by all future function calls. This can cause unexpected results, or lead to security vulnerabilities whereby one function consumer can view or modify the data of another function consumer. Instead, use a default argument (like None) to indicate that no argument was provided and …
=> openshift_resources_base: avoid mutating default arguments in process_jinja2_template

reconcile/kafka_clusters.py
part of https://issues.redhat.com/browse/APPSRE-2728
when we create a SA, we write it to vault only when the cluster is ready. this creates a situation where an SA was created (sync) and the cluster was not (async) and we lose the SA clientSecret. the workaround is to delete the SA through the API and everything falls back into place.
this PR fixes it so we only create the SA when the cluster is ready, thus avoiding the situation.
=> [kafka-clusters] fix SA creation

reconcile/saas_file_owners.py
since `hold` is being calculated per diff, we need to keep a global hold variable if a previous diff indicated a hold.
fixes the madness in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/18509
=> [saas-file-owners] overall hold

reconcile/utils/saasherder.py
related to https://issues.redhat.com/browse/APPSRE-3265
we currently only generate IMAGE_TAG if it is a parameter in the openshift template and it is not explicitly specified in the saas file parameters. there are cases where we need to use the image tag to generate other parameters, such as REPO_DIGEST.
generally, since there are no real operations to generate the image tag, we can just always do it.
=> [openshift-saas-deploy] always generate IMAGE_TAG

reconcile/utils/saasherder.py
Today referencing an image with:
`  image: ${REPO_DIGEST}`
requires designating `REGISTRY_IMG` as a required parameter even if it is not explicitly used anywhere in the template. To make things more scrutable, this commit adds support for generating a new `IMAGE_DIGEST` value, which comprises just the digest (`sha256:xxxx...`) whereas `REPO_DIGEST` comprises the full by-digest URL. With this change, the template file can include:
```
parameters:
- name: REGISTRY_IMG
required: true
- name: IMAGE_DIGEST
required: true
...
image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
```
To wit, you're explicitly using all the parameters you require.
APPSRE-3265
=> Support generating IMAGE_DIGEST

reconcile/jira_watcher.py
related to https://issues.redhat.com/browse/ASIC-16
we sometimes get empty responses from Jira but without an error, which causes the integration to think all tickets were deleted.
similarly to what we did with unleash-watcher in #1047, let's not act on empty jira boards.
=> [jira-watcher] don't act on empty jira boards

reconcile/utils/amtool.py
amtool has the strange behaviour of throwing important data on stdout
when it fails to validate
=> Show stdout and stderr in amtool error messages

reconcile/gitlab_housekeeping.py
`saas-file-update` label is added when the changes on a MR are valid saas file changes only. in these cases, it is expected that the saas file owners add a `/lgtm` comment, which will add the `bot/approved` label which will lead make gitlab-housekeeping merge the MR.
this PR will cause gitlab-housekeeping to remove a `lgtm` label when this is a valid saas file change.
this effectively means that our team loses our powers to add the lgtm label to saas file update MRs (but we can always force merge in case of emergency)
example MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/19002
slack thread: https://coreos.slack.com/archives/CCRND57FW/p1620312615431000
=> [gitlab-housekeeping] remove lgtm label if saas-file-update label exists

reconcile/ocm_addons.py
parameters are a list of dicts, and the diff calculation causes addons to be reinstalled.
=> [ocm-addons] sort parameters

reconcile/utils/oc.py
part of APPSRE-3284
this is required to recycle fluentd pods in openshift-logging after a new instance secret was created.
or in general - recycle DaemonSet pods.
=> add support to recycle DaemonSet

reconcile/test/test_vault_utils.py, reconcile/utils/vault.py
The vault token has a TTL. Once that TTL has expired, when trying to
access vault secrets it will return a permission error, as the token is
no longer valid.
Our code is currently reactive, we watch when that happens, we refresh
the vault token, and try again.
That approach is not optimal as it requires handling the same error in
multiple places. We want to proactively refresh the token before it
expires in order to avoid the problem altogether.
Note that this is required because our integrations are long running and
our goal is to exceed the TTL.
We were previously assuming SecretAccessForbidden was a symptom of token
expiration. Therefore we were catching that exception, refreshing the
token, and raising a SecretNotFound to get the code to retry the
operation.
With the proactive token …
=> periodic vault refresh

reconcile/openshift_groups.py
this change affects the following integrations:
- openshift-groups
- ocm-groups
- openshift-users
if a cluster is defined as `internal`, instead of using the github username, we use the org username.
this PR is done in the context of https://issues.redhat.com/browse/APPSRE-3261, where we create an internal OSD cluster.
=> add support for group association by org username

reconcile/openshift_groups.py
Reverts app-sre/qontract-reconcile#1550
reverting this and going to use github auth for internal clusters as well
cc @rporres
=> Revert "add support for group association by org username"

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-external.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
Currently some integrations do not ship logs to cloudwatch:
- jira-watcher
- unleash-watcher
- github-scanner
- openshift-upgrade-watcher
- openshift-resourcequotas
- sentry-helper
- slack-cluster-usergroups
- ocp-release-mirror
We want to always ship logs to cloudwatch. This PR will make it part of the
template. It is recommended to review this PR commit by commit.
=> All integrations ship to cloudwatch always

reconcile/utils/terrascript_client.py
this will allow using this file-like secret as a mounted volume in pods. this is another option to use the aws credentials chain.
in our case, this key is added to the `instance` secret in openshift-logging namespaces where we use log forwarding and we want to override it to enable https://issues.redhat.com/browse/APPSRE-3284
=> [terraform-resources] add crendentials file like secret

reconcile/utils/saasherder.py
openshift-saas-deploy collects parameters for deployment from 2 places:
1. saas file parameters (top level, resource template level, target level)
2. environment parameters
if a parameter is defined with values that can be reused from the environment level, we currently log a warning message.
this PR changes the behavior so that we log an error message and exit with error instead, which means we will enforce reusing parameters.
this is an alternative for #1557
output example: https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/61084/artifact/temp/reports/reconcile_reports_success/reconcile-saas-file-validator.txt
=> [saasherder] change parameters not reused log from warning to error

reconcile/gitlab_mr_sqs_consumer.py, reconcile/mr_client_gateway.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, reconcile/saas_file_owners.py, reconcile/saas_file_validator.py, reconcile/utils/saasherder.py, tools/qontract_cli.py
this is the first PR to add support for saas files v2 (implemented with Tekton under the hood). we try to make the logic for v1 and v2 as similar as possible, with only the underlying implementation different (trigger job in jenkins vs do something in tekton).
related to https://issues.redhat.com/browse/APPSRE-3187
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/19569
this PR changes logic in the following way:
1. add v2 queries
2. treat (jenkins) instance as optional (as tekton things will be running inside a cluster)
essentially, this PR does not add any new functionality and only influences integrations to make them work as they did until today.
=> tekton saas file v2 support #1

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/queries.py, reconcile/utils/saasherder.py
this PR refactors the openshift-saas-deploy trigger integrations to be aware of api version and trigger a new deployment in the appropriate provider (v1 - jenkins, v2 - tekton (not yet implemented)).
=> [openshift-saas-deploy-triggers] prepare for v2 pipelines provider

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, reconcile/cli.py, reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/queries.py
follows up on #1577
this PR adds Tekton trigger implementation (applying `PipelineRun`s). it also adds any required cli args for `oc` usage and does a small refactor of the setup phase of the triggering integrations.
=> [openshift-saas-deploy-triggers] add tekton support

reconcile/queries.py
this will re-enable slack events output notifications for v2 saas files.
=> add slack to saas file v2 query

reconcile/ocm_clusters.py, reconcile/utils/ocm.py
this PR changes the way we update a cluster via OCM.
first, we validate that any updated fields are able to be updated in OCM. second, we only pass the updated fields to the clusters PATCH endpoint instead of passing all fields that can be updated, even if they were not updated.
this really solves 2 problems:
1. the integration will return an error when trying to update an invalid field.
2. assuming we want to update cluster storage quota (for example) during an upgrade. in the current situation, since we are passing the `channel` field as well, the cluster update will be rejected. with this change, only updated fields will be passed.
=> [ocm-clusters] improve cluster update and add validation

reconcile/utils/aws_api.py
The call to `list_users` need to be paginated. At the moment only the first 100 users is returned as this is the default for `iam.list_users()`
Once the fix is deployed it is possible that other functionality that relied on the list of users may trigger changes or errors which were not caught before as we were not evaluating the users after the first 100. After review the following functionality may be impacted:
- Verification of IAM keys
- Deletion of IAM users
- AWS resource owners (resources without owners)
=> aws_api: paginate when initializing the list of users

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/utils/saasherder.py
this PR adds the ability to set a timeout for a deployment (for saas-file-1 - supported through the Jenkins timeout wrapper).
docs: https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout
=> [openshift-saas-deploy-triggers] add support for timeout

reconcile/openshift_saas_deploy.py, reconcile/queries.py
this PR adds slack start and end notifications. this functionality replaces the functionality of the Jenkins Slack publisher for v2 saas files. it also adds a console url to open to view the pipelines run.
=> [openshift-saas-deploy] add slack start and end notifications

reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py
now that this integration runs as a pod, we don't need to enter a loop and trigger at any cost. if an error occurs, it may be fixed in the next iteration. this way we will not be blocked on our problematic trigger and will still trigger other jobs.
=> [openshift-saas-deploy-trigger-configs] remove trigger loop

reconcile/utils/saasherder.py
when adding an automated promotion in a single step (both `publish` and `subscribe`) - there isn't a first success published yet, which causes app-interface pr-check jobs to fail.
this PR is meant to relax that a bit and allow for smoother migrations as part of https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/19968.
since the structure of the data we store in the state is a dict, this PR also makes things more correct.
=> [saasherder] set default value for state promotion to empty dict

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py
Even this is too lenient - the spec and settings dictionaries can
probably be flattened or converted into something friendly static analyzer.
Using named arguments instead of passing a dictionary and unpacking it
makes the code less surprising, and allows linters to detect typos
instead of having crashes at runtime.
If I screw up during my development, pylint is now able to say things
like:
```
reconcile/openshift_saas_deploy_trigger_configs.py:53:24: E1120: No value for argument 'spec' in function call (no-value-for-parameter)
reconcile/openshift_saas_deploy_trigger_configs.py:53:24: E1120: No value for argument 'jenkins_map' in function call (no-value-for-parameter)
reconcile/openshift_saas_deploy_trigger_configs.py:53:24: E1120: No value for argument 'oc_map' in function call …
```
=> Give trigger(...) named arguments

reconcile/utils/saasherder.py
when going over a v2 saas file, instnace_name is None. in this case, we will default to checking images.
=> [openshift-saas-deploy] only check image if instance_name is not None

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/openshift_saas_deploy_trigger_upstream_jobs.py
It seems that the trigger integrations get a bit backed up and take a long time to apply `PipelineRun`s.
This PR adds some CPU resources and adds sharding to the integrations (3 shards each for now).
=> [openshift-saas-deploy-triggers] improve integration run time

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/openshift_saas_deploy_trigger_configs.py, reconcile/openshift_saas_deploy_trigger_moving_commits.py, reconcile/openshift_saas_deploy_trigger_upstream_jobs.py, reconcile/utils/saasherder.py
this PR started out as adding usage of multi threading.
from there, it was difficult not to refactor the trigger function to lock for as little time as possible.
from there, it was difficult not to make the different trigger provider sections look as similar as possible.
from there, it was difficult not to change `already_triggered` to a set (also was a debt to @Piojo).
from there, it was difficult not to extract them to functions (also was a debt to @rporres).
from there, it was difficult not to update `setup` from options to **options (also was a debt to @Piojo).
from there, it was difficult not to drop one line in the `oc_map` initiation (also was a debt to my OCD).
note to the wise reviewers: commit by commit.
note to future selves: this is likely not a complete refactor (thoughts of …
=> [openshift-saas-deploy-triggers] threaded run + refactor

reconcile/gitlab_housekeeping.py
we currently rebase MRs with a `saas-file-update` label to achieve a faster merge when someone `/lgtm`s.
this is not proving itself and is causing a (sometimes) painful review experience (a MR waiting for a few days becomes a problem).
this will also reduce pressure from ci-int, leading to these very same MRs to become faster indirectly.
=> [gitlab-housekeeping] do not rebase saas-file-update MRs

reconcile/openshift_saas_deploy.py
since we use `ri` to check for errors and decide the result based on that - let's register an error when we encounter an invalid promotion.
=> [openshift-saas-deploy] register error on invalid promotions

reconcile/utils/openshift_resource.py
related to https://issues.redhat.com/browse/APPSRE-3331
as some consumers of the ResourceInventory class rely on it's error registering, we need to start registering more.
in [today's example](https://console-openshift-console.apps.appsrep05ue1.zqxk.p1.openshiftapps.com/k8s/ns/app-sre-pipelines/tekton.dev~v1beta1~PipelineRun/saas-grafana-app-sre-stage-202106070212/logs/openshift-saas-deploy), a deployment reported success while it actually failed due to this exception being raised.
=> register error on ResourceKeyExistsError

reconcile/ocm_clusters.py
to update a cluster to have autoscaling (for example), we remove the `nodes` section and add an `autoscaling` section. with this PR, this change will not lead to a KeyError.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/20298
=> [ocm-clusters] allow field to be replaced

.coveragerc, .gitignore, reconcile/test/test_make.py, tox.ini
To get the tests ball rolling. We seem to be using tox for testing, so
I adapt its configuration to generate reports.
The minimum required coverage is 19%. We currently have 19.07%
coverage.
I also disable the `test_make` file, which doesn't work at all on my
system, even without any local changes to my git repository.
=> [APPSRE-3325]Introduce code coverage in tox configs

reconcile/utils/openshift_resource.py
This reverts commit d9c7d2ab8e9f9ad21d27e72c1e6af2356e9aec17.
This is making openshift-rolebindings and openshift-clusterrolebindings silently fail
=> Revert "register error on ResourceKeyExistsError (#1610)"

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, reconcile/cli.py, reconcile/openshift_saas_deploy_trigger_cleaner.py, reconcile/queries.py
part of https://issues.redhat.com/browse/APPSRE-3340
this PR introduces a new integration called `openshift-saas-deploy-trigger-cleaner`.
this integration goes over all pipelines providers, and for each one of type `tekton` it performs a cleanup according to an optinal `retention` section.
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/20431
=> [openshift-saas-deploy-trigger-cleaner] introduce new integration

helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml
the reconcile channel is too busy to be usable with the amount of deployments we are triggering.
this PR will allow to split the slack output of trigger integrations to their own slack channel.
=> [openshift-saas-deploy-triggers] split to separate slack channel

helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml
fixes #1619
i expected this to work since i believed the fluentd configuration feeds from the actual environment in the running container. it seems the template parameters are actually used.
cc @BumbleFeng
=> fix fluentd args for slack triggers

reconcile/openshift_base.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py
part of https://issues.redhat.com/browse/APPSRE-3351
```
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
this PR adds support to apply every additional changes to StatefulSets without incurring any downtime.
When we detect a fields immutable error for a StatefulSet:
1. delete statefulset with cascade false to prevent the pods from being deleted
2. apply the updated statefulset
3. delete one pod at a time and wait for the new statefulset to bring it up
=> [openshift] add support for recycling StatefulSet

reconcile/test/test_utils_threaded.py, reconcile/utils/threaded.py
It is based on `asyncio.gather`.  It will run the given function on
the entire iterable, but any failures will become part of the result
list. The caller will tell good results from errors by inspecting on
instances of `Exception`.
The idea is to simplify exception handling by not having to convert exceptions in underlying code into some return values that will then be converted into something else, which makes us lose information along the way.
Also an example of code with tests.
=> Add an option to threaded.run to return all exceptions

reconcile/openshift_base.py
related to https://issues.redhat.com/browse/APPSRE-3351
this PR adds validation that a deployment on a StatefulSet was successful.
follow up on #1627
about keeping a state in case the deployment stops mid-run -
in such case, it is expected that the next deployment realizes that the StatefulSet is not in a healthy state and fail.
with this PR - this will now be the reality.
=> [openshift-saas-deploy] validate StatefulSet after deployment

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml, reconcile/cli.py, reconcile/jenkins_job_builds_cleaner.py, reconcile/queries.py, reconcile/utils/jenkins_api.py
We currently have a cronjob running on jenkins master that looks at the builds folders creation time and deletes them according to timestamps. The behavior is similar in this new integration but while the cronjob is deleting the build folders from the filesystem this integration will do it via the jenkins REST API
The problem with deleting the build folders from the filesystem is that jenkins still keeps all the builds loaded in memory until there is a safe or full restart of jenkins. This causes increased memory and overhead when jobs and build history are queried. Listing build history happens frequently from many places: the web UI, monitoring/prometheus and upon every webhook among others.
This integration is meant to replace the cronjob that we have on the server so that builds are …
=> introduce integration jenkins-job-builds-cleaner

reconcile/openshift_saas_deploy_trigger_base.py
related to https://issues.redhat.com/browse/APPSRE-3375
in all openshift-saas-deploy-trigger integrations, we update a state based on the last triggered spec.
sometimes, there will be multiple specs that would trigger the same deployment. in such cases, we only want to trigger the deployment once. however, we still need to persist the spec to the state so this deployment is not triggered again in the next iteration.
this is actually a regression. here is the a previous working version: https://github.com/app-sre/qontract-reconcile/blob/864a5d500da0300177004d1ef411013297a8e6d3/reconcile/openshift_saas_deploy_trigger_configs.py#L60-L63
summary: even if a deployment is skipped because it was already triggered, we still need to persist the spec to the state.
=> [openshift-saas-deploy-trigger] update state even if not triggered

reconcile/requests_sender.py, reconcile/test/test_requests_sender.py, reconcile/test/test_utils_gpg.py, reconcile/utils/gpg.py
If, instead of relying on return values we use exceptions, we can
pass a lot of context to the part of the stack best suited to handle
it or to produce the most useful reporting.
So, I have replaced `Popen` with `run` in `gpg_encrypt`, so that I can
get such an exception while removing code.  I have not updated
`gpg_key_valid` since I'd need to update its callers and they are out
of the scope of this task.
I have also replaced some calls to `defer` with a more Pythonic
context manager.  In this case I have adapted `gpg_key_valid`, for
consistency and because it doesn't change its behaviour or API.  This
removes some code, more notably two imports.
Finally, I have tweaked the integration's `run` to keep the happy path
uninterrupted - that's the beauty of exceptions.  We also guarantee
that …
=> [APPSRE-3369]Improve error handling and reporting in requests_sender

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
Increase the default sync interval from 30 seconds to 300 (5 minutes)
=> quay-mirror: increase default sleep duration

reconcile/requests_sender.py
We are merging stdout and stderr, and in this case it actually
simplifies code.
=> Improve reporting of GPG errors in requests-sender

reconcile/openshift_saas_deploy_trigger_base.py, reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-3342
we are deploying using Tekton PipelineRuns, which need to have a name of 63 chars or less (kubernetes limitation).
since we add a timestamp, we need to generate a unique combination in 51 chars to avoid conflicts between deployments.
=> [saas-file-validator] add validation for unique saas file and env combination

reconcile/test/test_utils_gpg.py, reconcile/utils/gpg.py
Even though `run` accepts `stdin=PIPE` , it actually finishes the
execution before we can call `communicate` on its return
value. Instead, we have to pass the input as the `input` parameter.
Added tests that truly run GPG.
=> Fix GPG encryption

dockerfiles/hack/run-integration.py, helm/qontract-reconcile/templates/template.yaml, openshift/qontract-reconcile-internal.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/status.py, reconcile/utils/gql.py, reconcile/utils/metrics.py
related to https://issues.redhat.com/browse/APPSRE-3368
we are often not getting alerted for failing integrations. this PR changes the run_status metrics from Counter to Gauge, with the value being the exit code.
this will allow us to replace our existing alert:
```
sum(increase(qontract_reconcile_run_status_total{status!~"0|3|-9"}[5m])) by (integration, shards, shard_id, status) > 0
```
with a much simpler one:
```
qontract_reconcile_run_status_total > 0
```
this PR also removes the 409 conflict handling which was removed in https://github.com/app-sre/qontract-server/pull/88. with this, we can just check that the run_status is `> 0`.
=> [metrics] Change run_status from Counter to Gauge

reconcile/aws_iam_keys.py, reconcile/cli.py, reconcile/test/test_aws_iam_keys.py
related to https://issues.redhat.com/browse/APPSRE-3399
required for #1664
this PR enables running the `aws-iam-keys` integration for a specific AWS account. since this integration is called from within `terraform-resources`, which can be run for a specific account, this will be beneficial.
=> [aws-iam-keys] add support to run per account

reconcile/terraform_resources.py, reconcile/utils/terraform_client.py
related to https://issues.redhat.com/browse/APPSRE-3399
required for #1664
this PR will add the caller (aws account name) to all desired resources (==output secrets).
this will allow us to use these values in the next PR to filter out resources we do not want to touch in a run for a different aws account.
this change should be applied manually while not allowing pods to be restarted.
=> [terraform-resources] add caller to desired resources

reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
When we try to fetch a non-existing commit from the Github API, we get
an exception that prints the offending commit but not the
repository.
In the context of integrations, when we are processing many different
repositories, we don't know which of them is actually giving problems.
=> Report failed repo in saasherder.get_sha

reconcile/terraform_resources.py, reconcile/test/test_terraform_resources.py, reconcile/utils/terraform_client.py
related to https://issues.redhat.com/browse/APPSRE-3399
depends on #1666
until now we couldn't run the integration fully with `--account-name` as it would have removed Secrets from other accounts.
with this PR, we now filter the Secrets based on their called (the name of the aws account), and it enables to run the integration per account.
future work:
1. create terraform-resources-wrapper, which will run the integration in parallel per account (makes tf init, tf plan, tf apply run per account and not wait for all accounts to finish each stage)
2. implement a sharded run per account (https://issues.redhat.com/browse/APPSRE-2963)
=> [terraform-resources] add support for a full run with account_name

reconcile/sendgrid_teammates.py
deleting a user is done with the `username`: https://sendgrid.com/docs/api-reference/
a username can be retrieved from the api, and will sometimes differ from the email name.
=> [sendgrid-teammates] fix user deletion

dockerfiles/hack/run-integration.py, reconcile/cli.py, reconcile/terraform_resources.py, reconcile/utils/metrics.py
related to https://issues.redhat.com/browse/APPSRE-3424
It will be useful to be able to expose additional labels on metrics based on the data that is being processed.
One use case would be - if terraform-resources is running per account and is running slowly, we would want to know which is the problematic account.
this is just an implementation proposal that works. feel free to review it and suggest improvements to things i'm obviously missing.
note: this works.
=> add support for additional labels in metrics (+implement for terraform-resources)

reconcile/queries.py, reconcile/test/test_saasherder.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-3425
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/21589
this PR adds support for a `delete` boolean in a saas file target to indicate that resources associated to that target should be removed.
the implementation is quite simple: if the target has `delete: true`, we don't add it's resources to the desired state. since they will be found in the current state and not in the desired state, they will be removed.
=> [openshift-saas-deploy] add support to delete target

reconcile/saas_file_owners.py
part of https://issues.redhat.com/browse/APPSRE-3425
follow up on #1680
this PR will make `saas-file-owners` realize there was a change in a target, thus causing the `openshift-saas-deploy-wrapper` to show proper results in pr-checks.
=> [saas-file-owners] add support to delete target

reconcile/utils/saasherder.py
when publishing promotions, some of them may be set to None (no deployment happened). let's handle it.
=> [saasherder] handle None promotions

Makefile, dockerfiles/Dockerfile.test
The main reason for this change is to fix a personal annoyance. This also bumps the Helm version in the test image.
Helm v3 has been out for a while and the default binary name is `helm`. As far as I can tell distributions are packaging the binary as such and not `helm3`. This has been an annoyance for me personally as the Makefile wants a `helm3` binary
=> bump helm version, rename binary from helm3 to helm

reconcile/utils/terrascript_client.py
We need this when we increase the storage size of the master
=> Allow for update read replica allocated storage

reconcile/quay_mirror.py, reconcile/test/test_instrumented_wrappers.py, reconcile/utils/instrumented_wrappers.py, reconcile/utils/metrics.py
As part of APPSRE-3385 we need to review measure how often we reach
to the external registry, and how effective our cache is.
For the first part, we keep `sretools.container.Image` decoupled from
Prometheus by subclassing it inside this repository, and instrumenting
the method that matters in this context: `_get_requests`. We make
`quay_mirror` use this instrumented version.
Then, we add a simple dictionary-like class that reports on hits,
misses and size. This will become our cache. We don't subclass `dict`
here since we may need to use a more sophisticated, persistent cache
with the same look and feel.
TODO:
* Is this the right way to use Prometheus metrics?
=> Add instrumented classes for common usage

reconcile/openshift_upgrade_watcher.py
part of https://issues.redhat.com/browse/APPSRE-3376
due to the UpgradeConfig resource changing it's name in https://github.com/openshift/managed-upgrade-operator/pull/224, we are no longer getting notifications for upgrades.
we also added internal OSD clusters, which means this integration needs to run internally.
=> [openshift-upgrade-watcher] fix missing upgrades due to resource name

reconcile/ocm_addons.py, reconcile/ocm_clusters.py, reconcile/utils/ocm.py
we do not need to initiate addons in every integration that uses OCM, so changing that to be opt-in.
also changing the skip to init for a positive declaration which is less confusing.
=> [ocm] add option to not init addons, rename skip to init

reconcile/openshift_base.py, reconcile/openshift_saas_deploy.py, reconcile/queries.py, reconcile/utils/oc.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-3457
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/22078
in order to be able to apply resources to facilitate this ticket, we need to apply them as cluster admins. with this PR, we can add `clusterAdmin: true` to a saas file and the credentials will be used from the `clusterAdminAutomationToken` key instead of the `automationToken` key of a cluster.
=> [openshift-saas-deploy] add support for cluster-admin automation token

helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
we use VPC peerings when running integrations inside our clusters instead of a jump host.
=> do not use jump host in internal openshift integrations

reconcile/github_org.py, reconcile/test/fixtures/github_org/current_state_simple.yml, reconcile/test/test_github_org.py, reconcile/utils/raw_github_api.py
The Github_org integration is using an old endpoint to check the teams invitations that is deprecated by github 
https://docs.github.com/en/rest/reference/teams#list-pending-team-invitations-legacy
We found a problem with the endpoint and the github-mirror that seems that do not return information about the next pages of the request. 
This PR changes the endpoint to use the new endpoint 
https://docs.github.com/en/rest/reference/teams#list-pending-team-invitations
=> [APPSRE-3481] Change teams invitations endpoint on github integration

reconcile/ocp_release_mirror.py, reconcile/test/test_utils_oc.py, reconcile/utils/oc.py, reconcile/utils/saasherder.py
part of https://issues.redhat.com/browse/APPSRE-3326
some actions are logged from within `oc.py`, which is unaware of the name of the cluster. this PR adds the name of the cluster to the OC initiation and adds it to logging messages.
=> add logging of cluster name from within oc

reconcile/test/test_utils_oc.py, reconcile/utils/oc.py
related to https://issues.redhat.com/browse/APPSRE-3326
from the time we collect pods and until we look for their owner some time may pass. during that time, the pod may be deleted or its owner can be deleted (like we are seeing here: https://coreos.slack.com/archives/CS0E65QCV/p1626791826140700).
to handle that we allow the owner to not be found, which will allow us to move on to the next object and successfully recycle pods.
=> [oc] recycle pods allow controller object to not be found

README.md
Adding instructions to install `python-devel` and `gcc-c++` packages for developers having trouble in the development environment setup.
=> add instructions to install python-devel and gcc-c++ packages

reconcile/kafka_clusters.py
we've observed cases where output Secrets were deleted. this PR denies that.
until we can further investigate - let's add this safety net.
=> [kafka-clusters] disable deletion

reconcile/saas_file_owners.py
we are currently only adding this label. in a situation where a MR was created with saas file changes only and later changed to contain more - we need to remove the saas file update label.
related to an observation made in https://issues.redhat.com/browse/APPSRE-3515
=> [saas-file-owners] remove saas-file-update label if MR changed

reconcile/terraform_resources.py, reconcile/utils/terraform_client.py, reconcile/utils/terrascript_client.py
Adds a terraform output field for annotations.  The value is a base64-encoded JSON document containing the annotations.
=> Ability to add annotations to terraform openshift secrets

reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings.py
a minor refactor. also adds tests.
=> [terraform-vpc-peerings] set assume_region and assume_cidr only once

reconcile/test/test_terraform_vpc_peerings.py, reconcile/utils/aws_api.py, tools/qontract_cli.py
related to https://issues.redhat.com/browse/APPSRE-3383
we want to make it easier to get the clusters' Egress IPs in case:
- we migrate a service between clusters and there is a matter of whitelisting IPs
- we onboard a new hive cluster (required for cloud-ingress-operator / managed-cluster-config): https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/hive-shard-provisioning.md#cloud-ingress-operator
with this PR, we can add this command to app-interface-output and get the required information automatically.
depends on #1729, #1730 (both currently merged into this one)
note to the reviewer: review only last 2 commits.
=> [qontract-cli] add get clusters egress IPs command

tox-devel.ini
To speed up development, it only runs pytest, and we can pass
positional arguments to narrow down the tests we want executed, like:
```
tox -c tox-devel.ini -- reconcile/test/test_utils_gpg.py
tox -c tox-devel.ini -- reconcile/test/test_utils_gpg.py::TestGpgKeyValid
tox -c tox-devel.ini
```
=> Add a tox config friendlier to development

reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3531
It appears these files were never used to create an ElastiCache instance, which means this may fail: https://github.com/app-sre/qontract-reconcile/blob/c917dcfaebd58d02031440b8b4aced2ad546f312/reconcile/utils/terrascript_client.py#L1544-L1547
If it does, we will need to add this output only if cluster mode is disabled, and otherwise use `configuration_endpoint_address`, as explained here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#attributes-reference
The idea was that we only support HA setups, as can be inferred from the initial documentation: https://gitlab.cee.redhat.com/service/app-interface/-/blob/f3b3475e1858d02a7f775c98d28c413ef7833973/README.md#L1378
But it seems …
=> [terraform-resources] use correct elasticache endpoint depending on cluster_mode

reconcile/ocp_release_mirror.py
https://issues.redhat.com/browse/APPSRE-3526
This pr fix 2 problems in ocp-release-mirror which results in it keeps pushing images to ocm-quay.
1. urlparse('quay.io').netloc return empty
According to https://docs.python.org/3/library/urllib.parse.html
> Following the syntax specifications in RFC 1808, urlparse recognizes a net2. 
loc only if it is properly introduced by ‘//’. Otherwise the input is presumed to be a relative URL and thus to start with a path component.
2. _build_quay_auths() does not include username and password
=> fix ocp-release-mirror keeps mirroring to ocm-quay

tox-devel.ini, tox.ini
The move to native oc introduced a dependency on kubernetes that
breaks some tests. And then, I'm introducing testslide on some other
work.
=> Add missing dependencies to tox.ini

reconcile/dashdotdb_slo.py
Currently the data in Dash.DB doesn't have enough precision:
```
serviceslometrics{cluster="...",name="Tenant Manager API availability",namespace="...",service="...",slitype="availability",type="slo_target"} 95.0
```
This is because we are doing an `int()` on the SLO values. This PR changes that to a float.
=> APPSRE-3559: Recorded SLO values in Dash.DB don't have enough precision

reconcile/github_org.py, reconcile/test/test_github_org.py
before this MR, we had a giant `retry` over `fetch_current_state`. if anything failed, the entire function was retried.
with this PR, we are retrying more specific things and avoiding repeating previously successful operations.
example failure: https://coreos.slack.com/archives/CS0E65QCV/p1628183673223500
```
Error running qontract-reconcile: 502 {"message": "Error reaching https://api.github.com: ReadTimeout"}
File "/run-integration.py", line 73, in <module>
integration.invoke(ctx)
File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1066, in invoke
return …
```
=> [github] retry be more specific

reconcile/github_repo_invites.py, reconcile/github_repo_permissions_validator.py
for the bot user to be able to post test results to a commit, it needs to have write permissions in the github repository.
we currently validate that the user has that write permission when a pr-check job is added for that repository.
when adding both the pr-check job and the repository to a `codeComponents` section, there is a chicken and egg situtation -
assuming an invitation is pending, we will only automatically accept it (with `github-repo-invites`) after the MR was merged. so the invitation is pending, but the MR will keep failing because the bot doesn't have write permissions for the repo. but the invitation in pending...
this PR adds a check if there is a pending invitation.
=> [github-repo-permissions-validator] consider invitations

reconcile/queries.py, reconcile/slack_usergroups.py, reconcile/utils/pagerduty_api.py
related to https://issues.redhat.com/browse/APPSRE-3566
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/23544
this PR will make slack-usergroups initiate PagerDuty users only once, instead of once per pagerduty target.
=> [slack-usergroups] only initiate pagerduty users once

openshift/qontract-reconcile.yaml, reconcile/quay_mirror.py, setup.py
To reduce the load we put on the APIs of external registries. We'll evaluate which integrations actually need it when we see the metrics on cache efficiency.
refs APPSRE-3385
Depends on https://github.com/app-sre/sretoolbox/pull/45
=> Add a response cache to quay_mirror

reconcile/utils/slack_api.py, tools/qontract_cli.py
with this command, we can add users to a usergroup:
```
qontract-cli --config config.debug.toml set slack-usergroup <workspace> <usergroup> <username>
```
adding someone to a usergroup is easier through the slack UI, but this command is mostly useful to empty a slack usergroup:
```
qontract-cli --config config.debug.toml set slack-usergroup <workspace> <usergroup> ''
```
this will help us with adding/removing ourselves from usergroups, such as the upcoming @app-sre-onboarding-ic.
=> [qontract-cli] add set slack-usergroup command

reconcile/openshift_base.py
with this PR, when there is an error applying a Secret (when there is a possibility the error contains the Secret itself), we will not print the error.
this will allow us to add slack output for other integrations, such as openshift-secrets.
=> [openshift] redact error when applying secrets

.gitignore, reconcile/quay_membership.py, reconcile/test/test_utils_quay_api.py, reconcile/utils/quay_api.py, tox-devel.ini, tox.ini
This change creates a Quay team when it doesn't exist and a member needs to be added to the team.  A default role of `member` is assigned to the team as a sane default.  Prior to this change an exception would be thrown and the team would need to be created manually.
=> Create Quay teams that don't already exist

reconcile/utils/oc.py
init_oc_client is running in different threads. If there are multi namespaces from the same cluster, we actually will init oc_client for that cluster multi times.
=> de-duplication cluster when init oc_map from namespaces

reconcile/utils/oc.py
Catch error when running `oc version` during `init_oc_client`. 
If failed 10 times, registered the cluster unreachable.
=> raise error while init

reconcile/terraform_vpc_peerings.py, reconcile/test/test_terraform_vpc_peerings_build_desired_state.py
This is the first step to prevent this integration from crashing when
some resource is not available. First I add tests, which has helped me
understand the code (which is complicated), next I can modify it and
refactor whatever's necessary.
It introduces a testing dependency on
[testslide](https://testslide.readthedocs.io).
Some of the mocked-out classes have lots of side effects in their
constructor, and mocking that out is a royal pain. Instead, I can rely
on `mock_constructor` to do the right thing, and I also gain far
better and stricter mocks.
=> Refactor terraform_vpc_peerings.build_desired_*state

reconcile/utils/gitlab_api.py
returns only the first 20 results by default. let's get all of them.
ref: https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html#id11
=> [gitlab-members] list all group members

tekton/rbac.yaml
to show how we manage permissions inside a pipelines namespace
=> add tekton rbac example

reconcile/cli.py, reconcile/ocm_upgrade_scheduler.py, reconcile/queries.py, reconcile/test/test_ocm_upgrade_scheduler.py, reconcile/test/test_utils_data_structures.py, reconcile/utils/data_structures.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-3638
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/24369
In order to be able to upgrade based on our first condition (soak days of a version), we need to keep track of versions running on our clusters, what workloads each cluster is running.
With this information, we can start building our logic of "to upgrade or not to upgrade" based on the conditions described in the Epic's design document.
=> [ocm-upgrade-scheduler] keep track of workload types and days of usage per version

tools/qontract_cli.py
part of https://issues.redhat.com/browse/APPSRE-3639
depends on #1793 (so only review the last 2 commits)
as version history changes, we want to be able to see information about versions that we are using or have used. based on this information, we will be able to understand why an upgrade is scheduled or not.
the intention is to invoke this command as part of the app-interface-output repository.
=> [qontract-cli] add get version-history command

reconcile/ocm_upgrade_scheduler.py, reconcile/test/test_ocm_upgrade_scheduler.py, reconcile/utils/ocm.py, setup.py
part of https://issues.redhat.com/browse/APPSRE-3640
depends on #1793
Conditions are defined in an `upgradePolicy` of a cluster. in this ticket, we will switch from using automatic upgrades to manual upgrades that will be set by the ocm-upgrade-scheduler integration if conditions are met for a specific version that is available for upgrade.
=> [ocm-upgrade-scheduler] add support to schedule upgrades based on conditions

reconcile/ocm_upgrade_scheduler.py, reconcile/queries.py, reconcile/test/test_utils_ocm.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-3641
schema: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/24403
as we discover versions which are not working well for us, we need to have a way to define a list of versions we shouldn't upgrade to.
=> [ocm-upgrade-scheduler] add support to reject specific versions

reconcile/test/test_utils_ocm.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-3646
follows up on #1796
this PR adds support to define a regex expression in `blockedVersions` in addition to a specific version.
this will allow us to avoid upgrades to feature candidate versions (for example).
=> [ocm-upgrade-scheduler] add support to reject versions based on regex expressions

reconcile/ocm_upgrade_scheduler.py, reconcile/test/test_utils_semver_helper.py, reconcile/utils/semver_helper.py
part of https://issues.redhat.com/browse/APPSRE-3647
We are currently using python's builtin `sorted` function, which incorrectly sorts versions when there are feature/release candidates involved. We want release candidates to be considered earlier from a release. In this example, we want a sorting function that sorts `4.8.0-rc.2` to be before `4.8.0`.
=> [ocm-upgrade-scheduler] properly sort versions

reconcile/quay_mirror.py, setup.py
Re-add caching of manifests to alleviate pressure on the docker APIs.
Using now a better version of sretoolbox.
TODO: How do I test this without downloading everything under the sun
to my laptop?
=> Re-add response caches to quay-mirror images

reconcile/test/test_utils_ocm.py, reconcile/utils/ocm.py
part of https://issues.redhat.com/browse/APPSRE-3646
follows up in #1799
this PR adds validation that all blocked versions are valid regex expressions.
=> [ocm] validate blocked versions regex expressions

setup.py
The previous version didn't handle image caches properly. Also, the
new version is almost twice as fast at handling image metadata.
Refs APPSRE-3385
=> Depend on a newer sretoolbox

reconcile/slack_usergroups.py, reconcile/test/test_utils_slack_api.py, reconcile/utils/slack_api.py
This was tested successfully in the app-sre environment on usergroups that were failing to create due to throttling, as well as catching errors associated with a usergroup that had a description that was too long.
Note that there is some code duplication here in the error handling.  Normally I'd generalize this, but I plan to upgrade for the Slack SDK v1 to v3 in the next couple of weeks, which has retry capability built into it.
=> [slack-usergroups] Add retry for throttled usergroups.update calls

reconcile/queries.py, reconcile/terraform_tgw_attachments.py
part of https://issues.redhat.com/browse/APPSRE-3645
this PR will enable the `terraform-tgw-attachments` integration to operate in an environment without OCM (OCP clusters).
in such an environment, a role ARN to assume should be supplied in the TGW definitions in the cluster file.
app-interface counterpart: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/24596
(even though we are not going to implement this into this instance of app-interface, but only for fedramp's root environment).
=> [terraform-tgw-attachments] add support for non OCM environments

reconcile/utils/quay_api.py
in the quay_api, when we get a 403, the `message` key may not exist, causing us to raise the wrong exception.
=> get_repo_team_permissions message may not exist

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
To store the in-memory cache we introduce as part of
https://issues.redhat.com/browse/APPSRE-3385 . The initial estimate is
50,000 failed requests at 20KB each - manifests are usually around
10KB, so this should give us plenty of room.
=> Increase memory allocation for quay-mirror

reconcile/slack_cluster_usergroups.py, reconcile/slack_usergroups.py, reconcile/test_slack_usergroups.py
This change saves a call to usergroups.update and usergroups.users.update
per usergroup for cases where there isn't a diff. Both of these APIs are
Tier 2 Slack API calls only allowing ~20 calls per minute. This can save
hundreds of calls per minute assuming a modest number of Slack usergroups.
Additionally, performed some refactoring to log inline with Slack API
calls and improved the data structures used to represent state for
simpler lookups.
=> [slack-usergroups] Update Slack usergroups only when there is a diff

reconcile/quay_permissions.py, reconcile/test/test_gitlab_housekeeping.py, reconcile/test/test_utils_quay_api.py, reconcile/utils/quay_api.py
There are more methods that can raise exceptions, so we cover each
iteration (i.e, each reviewed repository) in a try-except block.
Also, we replace the old `RequestsException` with the `HTTPError`
class supplied by `requests`. This gives us more information,
including access to the failed response and request.
This way, we can get complete error messages, such as:
```[2021-09-06 22:12:54] [ERROR] [quay_permissions.py:run:116] - Could not manage repo permissions on repo $REPO_NAME,team $TEAM_NAME - status code: 403 - resource URL: https://quay.io/api/v1/repository/$REPOSITORY_SHA/$REPOSITORY_NAME/permissions/team/$TEAM_NAME
[...]
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: ...
```
=> Improve error handling in quay-permissions

reconcile/utils/semver_helper.py, tools/qontract_cli.py
to properly sort the version, we need the sorting to happen according to semver.
in this PR, we change the `version` field to be semver sortable. to properly print, we need to stringify the values beforehand.
=> [qontract-cli] properly sort version history

reconcile/utils/gql.py
in a case where the call to get the current sha failed, we are currently silently proceeding to get git commit info of that sha.
instead, we need to make sure we got a valid response for the sha request and retry otherwise.
reported in https://coreos.slack.com/archives/CCRND57FW/p1631524355358800
error details:
```
sys.exit(load_entry_point('qontract-reconcile==0.3.0', 'console_scripts', 'qontract-reconcile')())
File …
```
=> [gql] get_sha raise and retry

reconcile/terraform_resources.py, reconcile/utils/terraform_client.py
related to https://issues.redhat.com/browse/APPSRE-3702
We are seeing this issue multiple times in pr-checks:
```
Error: Saved plan is stale
The given plan file can no longer be applied because the state was changed by
another operation after the plan was created.
```
This is probably because the actual terraform integration(s) are running continuously and performing `terraform apply` even without anything to change.
Let's try to avoid `terraform apply` if no changes are going to be made. This should alleviate this error and cause it to appear much less (and indirectly, speeding up app-interface pr-check time)
=> [terraform-resources] only apply if apply is needed

reconcile/terraform_tgw_attachments.py, reconcile/terraform_vpc_peerings.py, reconcile/utils/aws_api.py
there is no use to initiate users in these integrations, and we'll avoid some precious rate limit:
```
File "/usr/local/lib/python3.6/site-packages/qontract_reconcile-0.3.0-py3.6.egg/reconcile/terraform_vpc_peerings.py", line 182, in build_desired_state_all_clusters
cluster_info, ocm_map, settings
File "/usr/local/lib/python3.6/site-packages/qontract_reconcile-0.3.0-py3.6.egg/reconcile/terraform_vpc_peerings.py", line 108, in build_desired_state_single_cluster
aws_api = awsapi.AWSApi(1, [req_aws], settings=settings)
File "/usr/local/lib/python3.6/site-packages/qontract_reconcile-0.3.0-py3.6.egg/reconcile/utils/aws_api.py", line 32, in __init__
self.init_users()
File "/usr/local/lib/python3.6/site-packages/qontract_reconcile-0.3.0-py3.6.egg/reconcile/utils …
```
=> [terraform-vpc/tgw] avoid init users in aws api

reconcile/cli.py, reconcile/gitlab_housekeeping.py, reconcile/gitlab_labeler.py, reconcile/jenkins_job_builds_cleaner.py, reconcile/openshift_limitranges.py, reconcile/sentry_helper.py, reconcile/test/test_aggregated_list.py, reconcile/test/test_openshift_namespace_labels.py, reconcile/utils/gitlab_api.py, reconcile/utils/gql.py, reconcile/utils/jenkins_api.py, reconcile/utils/jjb_client.py, reconcile/utils/quay_api.py, reconcile/utils/terraform_client.py, requirements-test.txt
Use a version of flake8 that doesn't crash, fix any new errors, and
make pylint ignore an instantiation that has always worked.
=> Fix linters on Python 3.9

README.md, dockerfiles/Dockerfile
easy_install (used with `setup.py install`) will install pre-releases
which is unexpected and undesirable behavior.
More information:
https://github.com/pypa/setuptools/issues/855
I tested this by creating a venv with `python setup.py install` and another with `pip install .`  The diff of the `pip freeze` output was:
```
$ diff easy_install.txt pip.txt 
29c29
< jira==2.0.1.0rc1
---
> jira==2.0.0
56c56
< python-jenkins==1.8.0.0a0
---
> python-jenkins==1.7.0
86c86
< wrapt==1.13.0rc3
---
> wrapt==1.12.1
```
This is exactly what I expect.  The `pip` install ignored alpha and release candidates while easy_install was happy to install versions that we don't want to rely on in production.
=> Replace easy_install usage with the pip equivalents

helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml
This pod is using about 420MB, let's give it 550 for good measure.
=> Reduce the memory allocations for quay mirror

reconcile/openshift_base.py, reconcile/openshift_saas_deploy_trigger_base.py
according to https://coreos.slack.com/archives/CG5GV6CJD/p1631635926321200?thread_ts=1631621387.310900&cid=CG5GV6CJD, we can use `create` instead of `apply` to resolve the issue mentioned in that thread.
=> [openshift-saas-deploy-trigger] oc create instead of apply

.pylintrc
They are new in pylint 2.11, and fixing them belongs in a different
PR.
=> Disable some linter checks

reconcile/utils/terrascript_client.py
For reasons currently unknown to me, [my PR](https://github.com/app-sre/qontract-reconcile/pull/1825) that attempted to refactor a few things seems to have still caused [some issues](https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/85469/artifact/temp/reports/reconcile_reports_fail/reconcile-terraform-users.txt) in our staging environment. So now I am breaking that PR up into even smaller PRs. Starting with this. 
This just adds some type-hints.
MyPy seems happy when ran on this file.
```
$ mypy --ignore-missing-imports --install-types --non-interactive --no-implicit-optional reconcile/utils/terrascript_client.py
Success: no issues found in 1 source file
```
=> add some typehints to terrascript_client.py

reconcile/utils/oc.py
related to https://issues.redhat.com/browse/ASIC-86
in some cases, a `Deployment` was applied along (and before) a `ConfigMap`. we may be trying to apply an outdated `Deployment`, so let's get it before we act on it and retry for this particular case:
```
Operation cannot be fulfilled on deployments.apps "<deployment_name>": the object has been modified; please apply your changes to the latest version and try again
```
=> [oc] retry recycle

tools/qontract_cli.py
Due to recent changes on `print_output` function  two sub commands of `qontract-cli` are not working `qontract-cli state ls` and `qontract-cli template`
This fix it by sending an object as argument instead of a string.
I've choose to type content as `List[Dict]` Because `Iterable` doesn't let you use `.sort` in objects.
=> Fix argument for print_output in qontract-cli

reconcile/cli.py, reconcile/openshift_base.py, reconcile/openshift_clusterrolebindings.py, reconcile/openshift_limitranges.py, reconcile/openshift_network_policies.py, reconcile/openshift_resourcequotas.py, reconcile/openshift_rolebindings.py, reconcile/test/test_openshift_base.py, reconcile/utils/oc.py, reconcile/utils/openshift_resource.py, reconcile/utils/saasherder.py, reconcile/utils/terraform_client.py
We were silently skipping resource types we weren't managing, making
troubleshooting misconfigurations very hard.
First, we add type hints to `openshift_base.init_specs_to_fetch`, to
make it easier to understand and to refactor. 
Then, we can log skipped managedResourceNames in this method. This PR
refactors the namespace handling path to achieve that. There are unit
tests to confirm the behaviour is the same as it used to be, but
please have a look and feel free to suggest relevant configurations
that need extra tests.
Next, we raise an exception if `oc.apply`. There is a failure mode in
which an invalid input can be discarded and not raise any exceptions,
we now have a fall-back exception if that happens. I am not sure
unmanaged types can reach the `apply` phase - probably not - but I …
=> Fix handling of managedResourceTypes

.coveragerc, reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/25145
this PR adds support to provision LBs using terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb
this PR initially adds support for Application LB only, and only for HTTPS (with an HTTP redirection). we can refactor when future use cases come along.
=> [terraform-resources] add support to provision aws load balancer

reconcile/utils/terrascript_client.py
according to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group_attachment#availability_zone:
>  If the private ip address is outside of the VPC scope, this value must be set to 'all'.
this PR adds a handle for this case
=> [terraform-resources] add handling for alb ip out of VPC

reconcile/utils/terrascript_client.py
the output value is currently `aws_lb.<alb_identifier>.dns_name`, while it should be the actual terraform value.
=> [terraform-resources] alb output value from string to value

reconcile/test/test_utils_slack_api.py, reconcile/utils/slack_api.py
This fixes a regression from #1824 that was missed due to refactoring
of tests. The current impact is only that a single error message is
displayed each time we empty a group.
=> Ignore expected invalid_users errors

reconcile/test/test_terrascript_client_utils.py, reconcile/utils/terrascript_client.py
Because the integration uses the record name to build the terraform resource ID we need to sanitize * characters such that the resulting resource ID is valid
Ref APPSRE-3776
=> terraform_aws_route53: safe_resource_id should sanitize * characters

reconcile/utils/terrascript_client.py
For the current use case, the target ELB/App is expecting HTTP2 traffic
=> [terraform-resources] LB target group should be HTTP2

reconcile/utils/terrascript_client.py
The ALB security group should allow egress to the ports of the backing instances (target groups)
=> terrascript_client: alb security group egress rules

reconcile/utils/saasherder.py
We cannot assume errors is always going to appear. It is not there when
the GH error is a 404.
Related to https://issues.redhat.com/browse/APPSRE-3838
=> Fix missing error key in GH exception

reconcile/utils/saasherder.py, reconcile/utils/semver_helper.py
* Update the semver parse method (deprecated) to VersionInfo.parse
* Add type hints to semver helper methods. 
https://issues.redhat.com/browse/APPSRE-3648
=> APPSRE-3648: Update semver.parse method to VersionInfo.parse

reconcile/terraform_resources.py, reconcile/utils/terraform_client.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3785
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/25874
this PR adds support to define a `ca_cert` in an RDS definition. this will lead to an additional key in the output Secret containing the content of the specified key in a vault secret.
this is a generic way to provide the global CA certificate for usage with AWS RDS databases.
=> [terraform-resources] add support for ca_cert output in RDS secret

reconcile/utils/terraform_client.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3785
fixes #1872
terraform outputs can handle multi-line strings just fine, no need to work around anything.
=> [terraform-resources] remove spacial handling for ca_cert

reconcile/utils/terraform_client.py
part of https://issues.redhat.com/browse/APPSRE-3867
following #1840, we currently skip `terraform apply` unless there is a change to an actual resource. there are cases that only outputs are updated, and we currently skip it.
with this PR, we compare the predicted outputs (produced by `terraform plan` + `terraform show`) with the current outputs (produced by `terraform output`). if we find a mismatch - we set `should_apply` to `True`.
this will cause the integration to perform `terraform apply` for output changes only (such as adding a ca_cert to a DB).
=> [terraform] add handle to apply updated outputs

setup.py
This issue was discovered after the move to installing with pip
install instead of setup.py install. It was discovered that the
template files were missing. The templates were never included in
the correct location in the wheel distribution, only when q-r was
installed locally via setup.py install. This fix will ensure that
they are included in the expected directory for both local installs
and wheel distributions.
As per the setuptools docs, package_data is more appropriate because
these template files are closely related to the package implementation
and they are expected to be in the package directory.
To prove this only made the expected changes I generated a wheel with `python3 setup.py bdist_wheel` and got a checksum and list of all the files in the wheels. The diff produced is …
=> Fix template inclusion during packaging

reconcile/ocp_release_mirror.py, reconcile/queries.py
related to https://issues.redhat.com/browse/APPSRE-3880
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/26503
back when we created this integration, it was a choice to only mirror stable (due to ECR limitations?).
as ocm-quay has turned into our fallback, we want to mirror more release channels into it (no space/other limitations).
=> add support to mirror multiple ocp release channels

reconcile/email_sender.py
bug introduced in #1853
```
File "/run-integration.py", line 73, in <module>
integration.invoke(ctx)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/reconcile/utils/environ.py", line 15, in f_environ
f(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File …
```
=> [email-sender] remove faulty sections

reconcile/utils/terrascript_client.py
Reverts app-sre/qontract-reconcile#1845
reverted due to errors in all terraform integration when promoting: https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/89334/app-interface_20JSON_20validation/
cc @bkez322
=> Revert "bug fix: Q-R cannot create RDS replicas w/ enhanced-monitoring"

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/26162
this PR adds support to control the weights of traffic split between read and write paths (as opposed to only write path currently).
@jfchevrette PTAL
=> [terraform-resources] add support for read/write path split in alb

reconcile/openshift_base.py
Depends on https://github.com/RedHatInsights/clowder/pull/430
Adds validation logic for checking whether a Clowder ClowdJobInvocation has completed, and if it is 'completed', checks to see if any of its invoked child Jobs have failed.
Also follows logs of all jobs invoked by a ClowdJobInvocation
=> Add validation logic for ClowdJobInvocation

reconcile/openshift_base.py, reconcile/test/test_openshift_base.py
Log in `init_specs_to_fetch` any `managedResourceNames` or
`managedResourceTypeOverrides` not processed because they are not of a
kind listed in `managedResourceTypes`.
These configurations are currently dropped on the floor, making bad
configurations extremely hard to detect.
Continuation of APPSRE-3668
=> Log skipped managedResources on openshift_resource_base

reconcile/kafka_clusters.py
related to https://issues.redhat.com/browse/APPSRE-3901
we are often seeing cases where the integration attempts to delete all output Secrets, while there are no errors printed prior to that.
without the ability to debug this, let's attempt to add logging in places we suspect may be the cause.
=> [kafka-clusters] warn when cluster is not ready

Makefile
After the mess with #1917 - we confirm we can build and release every
PR.
Since docker caches layers locally, the overhead on our tests is
fairly small:
$ time make test
[...]
real	3m54,172s
user	0m0,619s
sys 	0m0,342s
$ time make test
real	3m53,636s
user	0m0,337s
sys 	0m0,200s
=> Build production image during tests

reconcile/utils/state.py
when integrations are using `State`, they only care about the actual state (stored in S3) and not about users in the account.
https://coreos.slack.com/archives/C024FNN7202/p1635838811182800
=> [state] don't initiate AWS users

README.md, reconcile/cli.py
i never want to type `--config` again.
=> allow config file to be defined through environment variable

reconcile/saas_file_owners.py
when an empty MR is submitted to app-interface they are immediately added with saas file related labels.
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/27947
this PR fixes that by validating that saas file changes only actually include any changes.
=> [saas-file-owners] avoid adding approved label to empty MRs

reconcile/utils/terrascript_client.py
resources which do not specify a `region` are supposed to be created in the default region defined at the account level.
until now, they were created in the terraform state bucket region instead.
=> [terraform] fix default region provider

reconcile/queries.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-4008
depends on https://github.com/app-sre/qontract-schemas/pull/8
this PR adds an option to define a `partition` on an aws account file. this is required for policies and other aws resources to be compliant with the aws account type (regular (`aws`) vs GovCloud (`aws-us-gov`)).
=> [terraform-resources] support aws partition (in sqs)

reconcile/utils/mr/auto_promoter.py
This MR addresses multiple issues in the qontract-reconcile auto-promotion feature
When the auto-promote processes more than one target-promotion in a saas file
at the same time, the second promotion reverts the first one.
walkthrough:
* while processing the first promotion, the saas file from the master branch
is loaded, the target ref is updated, and a commit to the temporary branch
is created
* when another promotion for the same saas file is processed, the saas file
is loaded again from the master branch, which does not contain the change
from the first promotion. then the change from the promotion is applied and
a commit is added to the temporary branch. this commit effectively reverts
the change from previous commits in the temporary branch to the saas file.
the behaviour can be …
=> Fix various auto-promotion issues

dockerfiles/Dockerfile, dockerfiles/Dockerfile.test
* Helm installation moved to qontract-reconcile-builder image. 
* Now the dockerfile.test image extends from qontract-reconcile-base. Now all tooling binaries are available for testing purposes.
=> Add tooling binaries to Dockerfile.test

reconcile/ocm_clusters.py
related to https://issues.redhat.com/browse/APPSRE-3793
`version` is not really the desired version. it is only here for tracking purposes and the cluster version (or the upgrade of it) is determined by `ocm-upgrade-scheduler`.
=> [ocm-clusters] clearer error message on wrong version

reconcile/utils/ocm.py
app-interface uses the 'storage' key and OCM uses the 'storage_quota'
key. Using the wrong key to parse the a-i spec was result in discarding
any storage changes. There are some other changes that can be made here
to ensure that an empty cluster spec patch doesn't occur silently, but
that will be handled in a separate PR.
For additional testing, I added some logging at the beginning/end of the `update_cluster` method.
```
{'storage': 4100} 
{}
{'storage': 4100}
{'storage_quota': {'value': 4402341478400.0}}
```
=> Fix storage updates performed by the ocm-clusters integration

reconcile/queries.py, reconcile/slack_usergroups.py, reconcile/test/fixtures/slack_usergroups/permissions.yml, reconcile/test/test_queries.py, reconcile/test/test_slack_usergroups.py
Originally slack-usergroups integration query the roles and loop through it to update permission, which means when there is no role for a permission, it will be skipped. And we want to avoid that. So the proposal was to query permissions and iterate those instead, with the schema change to include the information about roles there.
- Update the query of permissions with the updated schema; 
- Use permissions instead of roles to generate desired state so no permission update will be skipped due to role not exist; 
- Fail integration instead of log warning when the user group is not in managedUsergroup.
- pull permission query to queries module
- Add tests
Dry-run success before adding the failing mechanism, which result in a failing for crc-bop-team. Asking what to do there right now. …
=> APPSRE-3784: Use permissions instead of roles

reconcile/github_scanner.py
This function is using a persistent connection to github-mirror for each repo to list forks.
This connection may drop in case of a github-mirror pod restart
Setting `max_attempts` to 6 since we have 5 github-mirror pods. Open to discussion.
=> github-scanner: add @retry when listing forks

dockerfiles/hack/run-integration.py, helm/qontract-reconcile/templates/template.yaml, helm/qontract-reconcile/values-internal.yaml, openshift/qontract-reconcile-internal.yaml
These changes adapt the cronjob helm chart template and qontract-reconcile container CMD script run-integration.py to allow the execution of arbitrary click based entry point commands. This will enable us to run tools like app-interface-reporter or e2etests.
The additional ENV variable `COMMAND_NAME` can be used to specify an entry point command made available through setup.py. If not specified, `COMMAND_NAME` will default to `qontract-reconcile` for backward compatibility. The `INTEGRATION_NAME` env var is used as subcommand when `COMMAND_NAME` references a click group.
An example of how to specify a command can be found in the `values-internal.yaml` file changed with this PR.
Ref APPSRE-3535
=> Run app-interface-reporter in an Openshift cronjob

dockerfiles/hack/run-integration.py
Click consumes and removes elements from the argument list past along
to the execution of a command. Therefore the argument list can not be
reused accross integration runs, and a new one needs to be created
each time.
=> Generate click arguments on each integration run

.coveragerc
Python 3.9 counts these differently (and I don't know why). We are now
at almost 27.4%.
=> Bump coverage thresholds

reconcile/openshift_base.py, reconcile/test/test_openshift_base.py
It is a configuration error for a namespace to list entries in
`managedResourceNames` or `managedResourceTypeOverrides` of kinds that
are not in `managedResourceTypes`.
The first step here is to re-add #1901 - it was doing most of the work
and had all the tests.
Then, we fix the bug that forced [its revert](#1911), together with
better tests.  In this case, when a namespace lists
`managedResourceTypes` that have no match in `managedResourceNames` we
still want to initialize an `StateSpec` - we may be adding resources
of this kind without modifying or overriding their names.
Finally, instead of logging stuff we raise `KeyError`, to let the
integration handle the error.
TODO: Adjust schemas to forbid the combination of empty/non-existing
`managedResourceTypes` with non-empty …
=> Fail when namespaces list resource names or overrides of unmanaged types

reconcile/queries.py, reconcile/slack_usergroups.py
There is a [permission](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/teams/placeholder-escalation-permission.yml) defined as placeholder for app-sre-escalation-undefined usergroup. Now that we loop through permissions, the integration breaks when it run to it because the usergroup has no actual usergroup etc
Skipping it.
=> Skip construct desired_state for app-sre-escalation-undefined usergroup

reconcile/utils/terrascript_client.py
required for aws accounts with a partition different from `aws` (such as `aws-us-gov`)
=> [terraform-users] support partition

reconcile/ldap_users.py, reconcile/queries.py, reconcile/utils/mr/__init__.py, reconcile/utils/mr/user_maintenance.py
depends on:
- https://github.com/app-sre/qontract-schemas/pull/11
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/28361
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/28360
this PR adds support to remove user refs from gabi instances to allow user offboarding.
=> add support to remove user ref from gabi instances when deleting a user

e2e_tests/test_base.py, reconcile/github_org.py, reconcile/openshift_network_policies.py, reconcile/openshift_resources_base.py, reconcile/queries.py, reconcile/terraform_resources.py, reconcile/utils/vault.py
part of https://issues.redhat.com/browse/APPSRE-4068
since read operations are cached, we can not allow for secrets in a kv v2 secret engine to be referenced without a version, since that prevents us from getting an expected result (i.e. we would get the latest version, which doesn't happen).
with this change, secrets in kv v2 secret engines can only be referenced together with a version.
=> [vault] read v2 version should not be none

reconcile/openshift_base.py, reconcile/openshift_resources_base.py, reconcile/test/fixtures/namespaces/openshift-resources-only.yml, reconcile/test/fixtures/namespaces/valid-ns.yml, reconcile/test/test_openshift_base.py, reconcile/test/test_openshift_resources_base.py
See the description of #1986
We fix the bug that made it crash with integrations that wanted to
override managed resource types, such as openshift-limitranges or
openshift-vault-resources.
To achieve that, we rework how `openshift_resources_base` filters
`openshiftResources` in `canonicalize_namespaces`. We add type hints
to assist the refactoring and change its return type to make overrides
explicit.
Note to reviewers: the types for `canonicalize_namespaces` are
correct. We use features specific of `dict` and `list` that can't be
matched with `Mapping` or `Iterable` or any other abstraction.
=> Fail again when resource names or overrides have unexpected kinds

dockerfiles/Dockerfile, reconcile/utils/terrascript_client.py
This PR solves an issue where it is not possible to update a target group while it is attached to a rule/listener
The issue was described upstream in https://github.com/hashicorp/terraform-provider-aws/issues/636 which was closed without a fix
The approach to the fix takes inspiration from a workaround found on the upstream issue
- Use the random provider to generate an ID based on some values
- As long as the values (keepers) do not change across plan execution, the ID will remain the same
- Use the ID as part of the ALB target group name
- Set the target groups lifecycle policy `create_before_destroy` to `true` such that whenever a target group has to be re-created it is done so before the old resource is destroyed
This PR has been tested in staging and the existing ALB configurations …
=> re-create target groups instead of updating them

reconcile/utils/terrascript_client.py
`alias` conflicts with `ttl` and `records`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record#alias
=> [terraform-aws-route53] do not set ttl on alias

reconcile/queries.py, reconcile/terraform_resources.py, reconcile/utils/aws_api.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-4107
depends on https://github.com/app-sre/qontract-schemas/pull/20
This allows for setting an OpenShift Service name as the target for an ALB.
With `openshift_service` defined, the integration will search the cluster's AWS account for a load balancer matching the OpenShift service, find its network interfaces and get their private IP (instead of manually doing it and hard coding the IP).
it is strongly recommended to review commit by commit.
=> [terraform-resources] support openshift service for alb

reconcile/openshift_tekton_resources.py
We don't want to have any overcommit issues with deployments which are a
critical part of our infra. We want to make sure that every taskrun
scheduled will have enough node resources and potential problems will
only come from the limits being too strict.
Part of APPSRE-3389
=> Guaranteed default QoS for deploy resources

reconcile/utils/terraform_client.py
follow up on:
- #1992
- #2008
with this PR, resources that are expected to get re-created will not cause an error when attempted to be deleted.
=> [terraform] add support for always enabled deletions for specific resource types

reconcile/utils/terrascript_client.py
Follow up on
- #2009
With this PR the integration/terraform will not cause a re-creation of the Target Group when the IPs change
=> terrascript_client: alb ips do not need to trigger a delete+recreate of the group

README.md, config.toml.example, helm/qontract-reconcile/values-external.yaml, openshift/qontract-reconcile.yaml, reconcile/cli.py, reconcile/dyn_traffic_director.py, reconcile/queries.py, reconcile/test/test_dyn_traffic_director.py, reconcile/utils/config.py, setup.py
Ref.: https://issues.redhat.com/browse/APPSRE-3884
Depends on schema changes: https://github.com/app-sre/qontract-schemas/pull/7
Notes for reviewers:
- The Dyn module is old and has not been updated in almost 4 years. It works well for our purpose and avoids having to re-implement their REST API. The Dyn service is being retired so we should not expect changes in their APIs or the module: https://www.oracle.com/corporate/acquisitions/dyn/technologies/enterprise-customer-faq.html
- I've used type hints where it made sense
- Unfortunately no tests. I think it may be acceptable to not have tests considering this is a service that is being retired and not being updated. I'm happy to add tests if deemed absolutely necessary
=> introduce new integration: dyn-traffic-director

reconcile/openshift_groups.py
The integration is crashing on timeout issues and the exception does not have any context.
This is not ideal but this should be safe and will help find out what cluster/group is causing issues
=> openshift_groups: catch exceptions and log error for context before re-throwing exception

reconcile/utils/oc.py
Issue title says it all.
Some servers may be temporarily overloaded and we can let the integration retry a few times when that happens
=> utils/oc.py: native client retry a few times get if we got a ServerTimeoutError

reconcile/utils/terrascript_client.py
this PR changes the initiation of the lambda zip to only be initiated when needed and to only be initiated once.
we use a lock because there is concurrency.
the implementation of hard coding `app-sre` is wrong, but this is not what this change is about.
=> [terrascript] init log to ES zip only lazy and once

reconcile/cli.py, reconcile/queries.py, reconcile/status_page_components.py, reconcile/test/fixtures/statuspage/test_bind_component.yaml, reconcile/test/fixtures/statuspage/test_create_component.yaml, reconcile/test/fixtures/statuspage/test_delete_component.yaml, reconcile/test/fixtures/statuspage/test_group_does_not_exist.yaml, reconcile/test/fixtures/statuspage/test_state_management_on_bind.yaml, reconcile/test/fixtures/statuspage/test_state_management_on_fetch.yaml, reconcile/test/fixtures/statuspage/test_update_component.yaml, reconcile/test/test_status_page_components.py, reconcile/utils/state.py, reconcile/utils/vaultsecretref.py, setup.py, tox.ini
the new integration can create, update and delete status page components based on the qontract-schemas `dependencies/status-page-1.yml` and `dependencies/status-page-component-1.yml``
The integration is currently implementing page management for Atlassian status pages (statuspage.io). Other status page provided can be added as necessary. The provider of a page is defined in the `provider` field of `dependencies/status-page-1.yml`
I wanted to point out the use of pydantic and dataclasses since this integration is also a POC for that approach. Please note the following:
* Field aliases are used to bridge the camelCase world of schemas with the snake_case world of python
Please also note that VaultSecretRef is not using pydantic but plain python dataclasses. I've chosen this approach to …
=> add integration for status page component management

reconcile/terraform_users.py, reconcile/test/test_terrascript_client_utils.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-4122
depends on https://github.com/app-sre/qontract-schemas/pull/21
this PR adds support to define `aws_username` in a user file to create aws IAM users with user name different from `org_username`.
=> [terraform-users] add support to define alternate aws username

reconcile/utils/aws_api.py
part of https://issues.redhat.com/browse/APPSRE-4117
this PR adds logic to skip "unready" network interfaces from being added to an ALB's IP list.
=> [terraform-resources] only add ready network interfaces to ALB private IPs

reconcile/terraform_resources.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-3925
depends on https://github.com/app-sre/qontract-schemas/pull/26
allow create IAM role for aws service 
=> add assume_service to aws-iam-role

reconcile/sentry_config.py
```
12:15:02 lint run-test: commands[1] | pylint -j0 --extension-pkg-whitelist=pydantic reconcile tools e2e_tests
12:15:16 ************* Module reconcile.sentry_config
12:16:32 reconcile/sentry_config.py:482:39: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
```
=> [sentry-config] iterate over keys implicitly

reconcile/utils/terraform_client.py
we currently rely on the terraform state to understand if a new user was created.
in #1897 we introduced a way to reset user passwords by deleting the login profile.
this PR detects when a new login profile is created and sends an email as a result.
=> [terraform-users] improve new users detection

reconcile/openshift_resources_base.py
this will enable us to use this value for templating in openshift-resources
ref: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/30037
slack thread: https://coreos.slack.com/archives/C02HE93TAFN/p1638971788033100
=> add network.pod to namespaces query

reconcile/aws_iam_password_reset.py, reconcile/utils/aws_api.py
though these actions are not always required to happen together, it is simpler to add the MFA reset in the same functionality as reset password.
slack thread: https://coreos.slack.com/archives/CCRND57FW/p1639393370415200
=> [aws-iam-password-reset] also reset MFA device

reconcile/queries.py, reconcile/terraform_aws_route53.py, reconcile/utils/terrascript_client.py
part of https://issues.redhat.com/browse/APPSRE-4179
depends on https://github.com/app-sre/qontract-schemas/pull/32
by referencing a VPC, we are making the zone "private".
=> [terraform-aws-route53] add support for private zones

reconcile/utils/sqs_gateway.py
related to https://issues.redhat.com/browse/APPSRE-4141
sqs-gateway is used by openshift-saas-deploy to publish promotions. without init_users, we are actually initiating all users, which takes a lot of memory.
example: saas-app-sre-observability-per-cluster -
with `init_users=True`:
with `init_users=False`:
=> [sqs-gateway] do not init aws users

reconcile/queries.py, reconcile/test/test_utils_terraform_client.py, reconcile/utils/terraform_client.py
part of https://issues.redhat.com/browse/APPSRE-4186
depends on https://github.com/app-sre/qontract-schemas/pull/38
this PR adds an ability to define resources that are approved for deletion, even for an account that does not have deletions enabled.
=> add support to delete specific aws resources

setup.py
```
/usr/local/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/x509.py:14: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
```
https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/102727/console
=> upgrade openssl

reconcile/openshift_serviceaccount_tokens.py, reconcile/queries.py
depends on https://github.com/app-sre/qontract-schemas/pull/39
this will allow an ability to define the name of the output Secret (both in OpenShift and in Vault).
=> [openshift-serviceaccount-tokens] add support to define resource output name

reconcile/cli.py, reconcile/status_page_components.py, reconcile/test/fixtures/statuspage/test_component_status_update.yaml, reconcile/test/test_status_page_components.py, tools/qontract_cli.py
qontract-cli get statuspage-components
this command lists all available status page components
qontract-cli set statuspage-component-status <component-name> <status>
this command sets the status for a status page component
Ref: https://issues.redhat.com/browse/APPSRE-4206
=> qontract-cli command to set status page component status

reconcile/utils/pagerduty_api.py
apparently users can be inactive in PD: https://coreos.slack.com/archives/CS0E65QCV/p1640860881303600
there is no direct api to get inactive users: https://community.pagerduty.com/forum/t/getting-a-list-of-inactive-or-unused-pagerduty-users/1789
so this has to be done from the schedule perspective.
=> [pagerduty] get schedule users if user is not deleted
